### ISSUE TITLE
Augmented API for Rectangles, Points, Sizes

### ISSUE THREAD

**Issue by migueldeicaza** [mono/SkiaSharp#1]
Currently we use a barebones implementation of those structures.

While we need to keep the structure fields in the same order, we should copy/paste the code for RectangleF and Rectangle into SKRect;   PointF/PointI into SKPoint and so on.

**Comment by migueldeicaza** [comment]
Added the PointF/Point, perhaps some improvements can be done to Point3.

Pending: Rectangles and Sizes.

**Comment by mattleibow** [comment]
Added this in 89d5e9d6e992d5d06fa6b439b844d0eece48e92d
