### ISSUE TITLE
[BUG] Memory leak in Android SKCanvasView

### ISSUE THREAD

**Issue by Kn4av** [mono/SkiaSharp#1004]
**Description**

Scenario: open 10 times screen with full screen SKCanvasView. App crashes with OutOfMemoryException

**Reason**

SKCanvasView doesn't release captured Bitmap

**Fix**

Recycle bitmap on detach from window:

```
SKCanvasView.cs
...

    protected override void OnDetachedFromWindow()
    {
        FreeBitmap();

        base.OnDetachedFromWindow();
    }
```

**Comment by mattleibow** [comment]
Thanks for reporting this. Got that fix coming in...
