### ISSUE TITLE
[BUG] Memory leak when create and dispose SKBitmap and SKCanvas using SkiaSharp

### ISSUE THREAD

**Issue by MadhanKumarasamy** [mono/SkiaSharp#1009]
**Description**
I have create a SKBitmap and SKCanvas and then i call dispose for both SKBitmap and SKCanvas but the memory is not released. I have the checked the memory usage using Visual Studio. I have compare the third and first snapshot after the dispose method but it holds some bytes. Attached screenshots shows that memory is not released after disposing the object.

**Code**
`Console.WriteLine();` // First snapshot
`SKBitmap bitmap = new SKBitmap(10, 10);`
            `SKCanvas sKCanvas = new SKCanvas(bitmap);`
`Console.WriteLine();` // Second snapshot
            `bitmap.Dispose();`
            `sKCanvas.Dispose();`
            `bitmap = null;`
            `sKCanvas = null;`
`Console.WriteLine();` // Third snapshot

**Expected Behavior**
In second screenshot - Size Diff (bytes): 0.

**Actual Behavior**
In second screenshot - Size Diff (bytes): +216.

**Basic Information**

- Version with issue:  1.59.3
- IDE: Visual Studio 2017 
- Platform Target Frameworks: .NET Core 2.0

**Screenshots**
Compare the Second snapshot with First snapshot:
![image](https://user-images.githubusercontent.com/48026813/68918257-6a1b9180-0793-11ea-90ad-09a4edbd06d0.png)

Compare the Third snapshot with First snapshot: After the dispose the SKBitmap and SKCanvas
<img width="694" alt="Memoryissue" src="https://user-images.githubusercontent.com/48026813/68917898-283e1b80-0792-11ea-8904-55d079f8f023.png">

**Comment by MadhanKumarasamy** [comment]
Hi @mattleibow,

Any update on this?

**Comment by Gillibald** [comment]
Just use a more recent version of SkiaSharp. That should solve your issue.

**Comment by MadhanKumarasamy** [comment]
> Just use a more recent version of SkiaSharp. That should solve your issue.

Hi @Gillibald ,

I have checked in the latest SkiaSharp version(2.80.2) but still the issue is not resolved. kindly resolve this issue and please find the below screenshot for your reference.
<img width="914" alt="Latest" src="https://user-images.githubusercontent.com/48026813/93904681-b91d4600-fd17-11ea-852a-692983712667.png">

**Comment by VijayRM** [comment]
@Gillibald - Can you look into this and share us the possible solution?

**Comment by mattleibow** [comment]
I can't seem to repro that. I run the code to the end, and then all the skia objects are just these:

![image](https://user-images.githubusercontent.com/1096616/94474083-689d6100-01cd-11eb-92f2-b2d385bb52d0.png)

**Comment by mattleibow** [comment]
Closing this as I am unable to repro this. If this is still happening, please open a new issue with a reproducible sample.
