### ISSUE TITLE
Cannot build Xamarin.Android packages on Windows.

### ISSUE THREAD

**Issue by gentledepp** [mono/SkiaSharp#101]
On windows, I can only build the UWP libraries.
When running

`.\bootstrapper.ps1 -target externals-android`
I get: 

> Error: Could not reach target 'externals-android' since it was skipped due to a criteria.

According to the readme, the android build can only be run on [mac]
Why is this? 
I would really like to make a private nuget package as miguel kindly added some methods that I was missing (SKMatrix.Invert, etc)

The full output is:
`PS D:\Code\SkiaSharp> .\bootstrapper.ps1 -target externals-android
Feeds used:
  C:\Users\alexa\AppData\Local\NuGet\Cache
  C:\Users\alexa\.nuget\packages\
  https://www.nuget.org/api/v2

Alle in "D:\Code\SkiaSharp\tools\packages.config" aufgeführten Pakete sind bereits installiert.
Analyzing build script...
Processing build script...
Installing addins...
Compiling build script...
Cake.exe ToolPath: D:/Code/SkiaSharp/tools/Cake/Cake.exe
Cake.exe NUnitConsoleToolPath: D:/Code/SkiaSharp/tools/Cake/../NUnit.Console/tools/nunit3-console.exe
NuGet.exe ToolPath: D:/Code/SkiaSharp/tools/Cake/../nuget.exe
Xamarin-Component.exe ToolPath: D:/Code/SkiaSharp/tools/Cake/../xamarin-component.exe
genapi.exe ToolPath: D:/Code/SkiaSharp/tools/Cake/../genapi.exe
Environment Variables:
        Key: SystemDrive        Value: "C:"
        Key: ProgramFiles(x86)  Value: "C:\Program Files (x86)"
        Key: Path       Value: "C:\ProgramData\Oracle\Java\javapath;C:\Program Files (x86)\Intel\iCLS Client\;C:\Program
 Files\Intel\iCLS Client\;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\
v1.0\;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management
Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\Inte
l(R) Management Engine Components\IPT;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files (x86)\Skyp
e\Phone\;C:\Program Files\Microsoft SQL Server\120\Tools\Binn\;C:\Program Files\Microsoft\Web Platform Installer\;C:\Pro
gram Files\Microsoft SQL Server\110\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\110\Tools\Binn\;C:\Program F
iles\Microsoft SQL Server\110\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL Server\110\Tools\Binn\ManagementStudio\;C:\
Program Files (x86)\Microsoft SQL Server\110\DTS\Binn\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOW
S\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\nodejs\;C:\Program Files (x86)\Microsoft SQL Server\Client SDK
\ODBC\130\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL S
erver\130\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL Server\130\Tools\Binn\ManagementStudio\;C:\Program Files\Tortoi
seGit\bin;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files (x86)\Windows Kits\10\Windows Performan
ce Toolkit\;C:\Program Files\Git\cmd;C:\Program Files (x86)\GtkSharp\2.12\bin;C:\Python27;C:\Users\alexa\.dnx\bin;C:\Use
rs\alexa\AppData\Roaming\npm;C:\Program Files (x86)\Microsoft VS Code\bin;C:\ProgramData\chocolatey\bin;"
        Key: ProgramW6432       Value: "C:\Program Files"
        Key: ChocolateyInstall  Value: "C:\ProgramData\chocolatey"
        Key: PROCESSOR_IDENTIFIER       Value: "Intel64 Family 6 Model 94 Stepping 3, GenuineIntel"
        Key: APPDATA    Value: "C:\Users\alexa\AppData\Roaming"
        Key: TMP        Value: "C:\Users\alexa\AppData\Local\Temp"
        Key: PROCESSOR_ARCHITECTURE     Value: "AMD64"
        Key: PATHEXT    Value: ".COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC;.CPL"
        Key: VisualInstallerDesignTimeConfig    Value: "C:\Program Files (x86)\Xeam\Visual Installer\DesignTimeConfig"
        Key: USERPROFILE        Value: "C:\Users\alexa"
        Key: PROCESSOR_REVISION Value: "5e03"
        Key: GTK_BASEPATH       Value: "C:\Program Files (x86)\GtkSharp\2.12\"
        Key: TEMP       Value: "C:\Users\alexa\AppData\Local\Temp"
        Key: FPS_BROWSER_APP_PROFILE_STRING     Value: "Internet Explorer"
        Key: FPS_BROWSER_USER_PROFILE_STRING    Value: "Default"
        Key: LOGONSERVER        Value: "\\MicrosoftAccount"
        Key: USERNAME   Value: "alexa"
        Key: SystemRoot Value: "C:\WINDOWS"
        Key: LOCALAPPDATA       Value: "C:\Users\alexa\AppData\Local"
        Key: VS110COMNTOOLS     Value: "C:\Program Files (x86)\Microsoft Visual Studio 11.0\Common7\Tools\"
        Key: CommonProgramFiles Value: "C:\Program Files\Common Files"
        Key: PROCESSOR_LEVEL    Value: "6"
        Key: ProgramData        Value: "C:\ProgramData"
        Key: HOMEPATH   Value: "\Users\alexa"
        Key: COMPUTERNAME       Value: "LAPTOP-3M6KT9KO"
        Key: ALLUSERSPROFILE    Value: "C:\ProgramData"
        Key: CommonProgramW6432 Value: "C:\Program Files\Common Files"
        Key: VS140COMNTOOLS     Value: "C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\Tools\"
        Key: WIX        Value: "C:\Program Files (x86)\WiX Toolset v3.10\"
        Key: SESSIONNAME        Value: "Console"
        Key: CommonProgramFiles(x86)    Value: "C:\Program Files (x86)\Common Files"
        Key: HOMEDRIVE  Value: "C:"
        Key: windir     Value: "C:\WINDOWS"
        Key: NUMBER_OF_PROCESSORS       Value: "8"
        Key: OS Value: "Windows_NT"
        Key: ProgramFiles       Value: "C:\Program Files"
        Key: ComSpec    Value: "C:\WINDOWS\system32\cmd.exe"
        Key: VS120COMNTOOLS     Value: "C:\Program Files (x86)\Microsoft Visual Studio 12.0\Common7\Tools\"
        Key: VSSDK140Install    Value: "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VSSDK\"
        Key: JAVA_HOME  Value: "C:\Program Files (x86)\Java\jdk1.7.0_55"
        Key: PSModulePath       Value: "C:\Users\alexa\Documents\WindowsPowerShell\Modules;C:\WINDOWS\system32\WindowsPo
werShell\v1.0\Modules\;C:\Program Files (x86)\Microsoft SQL Server\110\Tools\PowerShell\Modules\;C:\Program Files (x86)\
Microsoft SQL Server\130\Tools\PowerShell\Modules\;C:\Program Files\WindowsPowerShell\Modules\;C:\Program Files (x86)\Mi
crosoft SDKs\Azure\PowerShell\ResourceManager\AzureResourceManager\;C:\Program Files (x86)\Microsoft SDKs\Azure\PowerShe
ll\ServiceManagement\"
        Key: TelerikWPFDir      Value: "C:\Program Files (x86)\Telerik\UI for WPF Q1 2016\"
        Key: USERDOMAIN Value: "LAPTOP-3M6KT9KO"
        Key: VisualInstaller    Value: "C:\Program Files (x86)\Xeam\Visual Installer\"
        Key: ANDROID_NDK_PATH   Value: "C:\Users\alexa\Documents\Android\ndk\android-ndk-r10e"
        Key: USERDOMAIN_ROAMINGPROFILE  Value: "LAPTOP-3M6KT9KO"
        Key: PUBLIC     Value: "C:\Users\Public"
Error: Could not reach target 'externals-android' since it was skipped due to a criteria.`

**Comment by gentledepp** [comment]
I am really sorry for bothering you guys, but this is currently a blocking issue for me.
Reason is, that I whould like to proceed with my SVG implementation, but for this I'd need the current SkiaSharp master branch built and packaged as an alpha nuget package.

I currently cannot afford to buy a mac, and obviously I also do not want to do so. :-/
Are there any nightly builds of the Android binding libary, or even the nuget packages so I could get my hands on the latest bits?

**Comment by mattleibow** [comment]
@gentledepp This is currently a limitation of Google Skia: https://skia.org/user/quick/android

> Currently we only support building Skia for Android on a Linux or Mac host! In addition, we only use the Mac build for local development. All shipping variants are compiled on Linux for performance reasons.

@bholmes @migueldeicaza Is this something that is a priority?
