### ISSUE TITLE
[Question] Error building 'externals-tizen'

### ISSUE THREAD

**Issue by mackel90** [mono/SkiaSharp#1016]
I downloaded the and followed the guides, did not made changes to any file. 
Installed tizen and a few tizen-packages that I found timportant.

The '.\bootstrapper.ps1 -t everything -v "Diagnostic"'-Call get stopped reporting this error below.

It thells me there is a header file missing which is indeed not there. 
Is there configured something wrong? Can I exclude tizen, ('cause I probably don't need it)

Why all that ? I only want to change something in "source/SkiaSharp.Views.Forms.Android/SKTouchHandler.cs" that it don't allow touch stealing by interception. Only few lines of code.

`Executing: "C:/Users/mackel/source/repos/SkiaSharp/externals/depot_tools/ninja.exe" skia -C out/tizen/armel
ninja: Entering directory 'out/tizen/armel'
[3/991] compile ../../../src/opts/SkBlitRow_opts_arm.cpp
FAILED: obj/src/opts/armv7.SkBlitRow_opts_arm.o
C:/Users/mackel/tizen-studio/tools/llvm-4.0.0/bin/clang++.exe -MMD -MF obj/src/opts/armv7.SkBlitRow_opts_arm.o.d -DNDEBUG -DSK_SAMPLES_FOR_X -DSK_GAMMA_APPLY_TO_A8 -DSK_ALLOW_STATIC_GLOBAL_INITIALIZERS=0 -DSK_ENABLE_DISCRETE_GPU -DSKIA_IMPLEMENTATION=1 -I../../../include/android -I../../../include/c -I../../../include/codec -I../../../include/config -I../../../include/core -I../../../include/effects -I../../../include/encode -I../../../include/gpu -I../../../include/atlastext -I../../../include/pathops -I../../../include/ports -I../../../include/svg -I../../../include/utils -I../../../include/utils/mac -I../../../include/private -I../../../src/c -I../../../src/codec -I../../../src/core -I../../../src/effects -I../../../src/fonts -I../../../src/image -I../../../src/images -I../../../src/lazy -I../../../src/opts -I../../../src/pathops -I../../../src/pdf -I../../../src/ports -I../../../src/sfnt -I../../../src/shaders -I../../../src/shaders/gradients -I../../../src/sksl -I../../../src/utils -I../../../src/utils/win -I../../../src/xml -I../../../third_party/gif -I../../../src/gpu -fstrict-aliasing -fPIC -fvisibility=hidden -march=armv7-a -mfpu=neon -mthumb --sysroot=C:/Users/mackel/tizen-studio/platforms/tizen-4.0/mobile/rootstraps/mobile-4.0-device.core --target=arm-tizen-linux-gnueabi -BC:/Users/mackel/tizen-studio/tools/arm-linux-gnueabi-gcc-6.2/arm-tizen-linux-gnueabi/bin -O3 -fdata-sections -ffunction-sections -Wno-unused-parameter -DSKIA_C_DLL -DSK_BUILD_FOR_TIZEN -std=c++11 -fvisibility-inlines-hidden -isystemC:/Users/mackel/tizen-studio/tools/arm-linux-gnueabi-gcc-6.2/arm-tizen-linux-gnueabi/include/c++/6.2.1 -isystemC:/Users/mackel/tizen-studio/tools/arm-linux-gnueabi-gcc-6.2/arm-tizen-linux-gnueabi/include/c++/6.2.1/arm-tizen-linux-gnueabi -fno-exceptions -fno-rtti -c ../../../src/opts/SkBlitRow_opts_arm.cpp -o obj/src/opts/armv7.SkBlitRow_opts_arm.o
In file included from ../../../src/opts/SkBlitRow_opts_arm.cpp:8:
In file included from ../../../src/core\SkBlitRow.h:11:
In file included from ../../../include/core\SkBitmap.h:11:
In file included from ../../../include/core/SkColor.h:11:
In file included from ../../../include/core/SkScalar.h:11:
In file included from ../../../include/core/../private/SkFloatingPoint.h:11:
In file included from ../../../include/private/../private/SkFloatBits.h:12:
In file included from ../../../include/core\SkTypes.h:21:
In file included from C:/Users/mackel/tizen-studio/tools/arm-linux-gnueabi-gcc-6.2/arm-tizen-linux-gnueabi/include/c++/6.2.1\ciso646:37:
In file included from C:/Users/mackel/tizen-studio/tools/arm-linux-gnueabi-gcc-6.2/arm-tizen-linux-gnueabi/include/c++/6.2.1/arm-tizen-linux-gnueabi\bits/c++config.h:507:
C:/Users/mackel/tizen-studio/tools/arm-linux-gnueabi-gcc-6.2/arm-tizen-linux-gnueabi/include/c++/6.2.1/arm-tizen-linux-gnueabi\bits/os_defines.h:39:10: fatal error: 'features.h' file not found
#include <features.h>
         ^~~~~~~~~~~~
1 error generated.`

**Comment by Gillibald** [comment]
If you just want to change something android related to can use `-t externals-android`

**Comment by mattleibow** [comment]
@Gillibald is right. And then you can just open one of the MSBuild projects - either the source or even a sample.

Also check out this wiki that can help you get started without building any of the native bits: https://github.com/mono/SkiaSharp/wiki/Building-SkiaSharp#managed-only-building

**Comment by mattleibow** [comment]
@mackel90 Did you manage to go any further?

**Comment by mackel90** [comment]
I managed to set that up  like you(@mattleibow) mentioned and worked around this by omitting the build step. Thanks!

The real thing I wanted to do is build myself so I dont need to wait for a release for following exsisting issue, because it is stucked in checks: https://github.com/mono/SkiaSharp/pull/953
Would be happy if this will be ready in a NuGet release in the near future.

**Comment by charlesroddie** [comment]
@mackel90 pending merge of that PR we are using a custom renderer. @FoggyFinder can share the code if it would help you.
