### ISSUE TITLE
Colors in Android x86 Emulator are wrong in version 1.68.1-rc.170

### ISSUE THREAD

**Issue by inforithmics** [mono/SkiaSharp#1017]
**Description**

Colors in Android X64 Emulator are wrong

**Code**

Attached sample project

**Expected Behavior**

The same colors as with version 1.68

**Actual Behavior**

After upgrading the colors are wrong in skia sharp in The android emulator on on target x64 on a real device they are correct.

**Basic Information**

- Version with issue:  1.68.1-rc.170
- Last known good version:  1.68
- IDE:  Visual Studio 2019 16.3.9
- Platform Target Frameworks: Android X64 (In Emulator)
  - Android: Android Pie 9.0
- Target Devices:   Android Pie 9.0 Emulator (X64)
  - 
  - 

**Screenshots**

Version 1.68 (Working)
<img width="382" alt="1 68" src="https://user-images.githubusercontent.com/2290863/69009454-95e67500-0955-11ea-80e6-255409b8fa04.PNG">

Version 1.68.1-rc.170 (Both Images did occur when changing for example the background color to White)
<img width="382" alt="1 68 1-rc 170_1" src="https://user-images.githubusercontent.com/2290863/69009467-ae568f80-0955-11ea-8589-76b733308326.PNG">
<img width="385" alt="1 68 1-rc 170_2" src="https://user-images.githubusercontent.com/2290863/69009468-b1518000-0955-11ea-9865-a3fb1641c2db.PNG">

**Reproduction Link**

[App15.zip](https://github.com/mono/SkiaSharp/files/3855715/App15.zip)

I don't know if this only occours in the Emulator because I don't have a real x64 Android Device
I only execute it in the Emulator on a Ryzen 1700 in the Android Emulator which has a target of x64

**Comment by inforithmics** [comment]
I investigated a litte further and found out why the Colors change in the Android Emulator. Somehow the Windows Accent Color (Theme Color is connected to the Android Emulator).

Windows Accent Color Blue -> Android SkiaSharp Blue becomes Green.
Windows Accent Color Gray -> Android SkiaSharp Blue becomes Dark Blue.

I have set on my Computer to Automatically pick the Accent Color Dending on the Background. And because I change the Background every few minutes the Accent Color Changes with it and the Image in the Android Emulator.

So I googled a little bit and in Android there seems to be a Theme Color (Connected with the Theme Color of Windows) and I think SkiaSharp somehow listens to that in the new Version causing this behavior.

**Comment by inforithmics** [comment]
Experimenting arround I have the Impression that a Default Theme ColorFilter is applied, because I could correct the Colors with a "Inverse Color Filter" but naturally on a real Android Device the colors where wrong.

**Comment by mattleibow** [comment]
That is really strange, and I don't actually think that feature exists. In fact, there should be no way your Windows machine influences the Android emulator.
But, it is happening, so who knows anymore. ¯\_(ツ)_/¯

What emulator are you using HAXM or Hyper-V?

Also, maybe try deleting your emulator image and recreating it - or create a new image. Also, if you roll back to v1.68.0, does it go away, or stay? What happens if you try an x86 emulator?

Do you have a mac that you could test on?

**Comment by mattleibow** [comment]
One separate thing that you could test is adding a label to the screen, or using the native Android drawing APIs on a custom view to see where the color stops.

If you have not done native Android dev, then I can maybe whip up a sample app for you to try.

**Comment by inforithmics** [comment]
I use Hyper-V (Because I run it on a Amd Ryzen 1800 Processor). But it exists although on a Intel PC where I although use Hyper-V. 
Strangly the Problem goes away when I downgrade to 1.68
I will make later a sample with Native Android.

**Comment by inforithmics** [comment]
On the Mac Emulator it is although somehow greenish and not blue.
![iosBug](https://user-images.githubusercontent.com/2290863/69168699-78e9a780-0af7-11ea-9270-487f3f42d98a.gif)

**Comment by inforithmics** [comment]
I have a intresting finding The Colors don't work on x86 Target Device on a x64 Target Device they work.
I discovered this because I recreated all Emulators and redownloaded the images.
On x64 it worked on a x86 Target device it didn't work.

**Comment by inforithmics** [comment]
Background of the Image label has the same color as the lines

![image](https://user-images.githubusercontent.com/2290863/69175057-58bfe580-0b03-11ea-9e2c-987e3336520f.png)

**Comment by inforithmics** [comment]
Heureka I found the problem:



```
                // setting SKColor and reading values works.
                var color = new SKColor(1,2,3, 4);
                var r = color.Red;
                // 1
                var g = color.Green;
                // 2
                var b = color.Blue;
                // 3
                var a = color.Alpha;
                // 4

               // setting the Color of skPaint
               // I cannot read back the values as is done in the SkiaSharp.Extended.Svg library 
               // so the colors
                // get changed
                var skPaint = new SKPaint();
                skPaint.Color = color;

                var pr = skPaint.Color.Red;
                // 86 !!
                var pg = skPaint.Color.Green;
                // 48 !!
                var pb = skPaint.Color.Blue;
                // 140 !!
                var pa = skPaint.Color.Alpha;
                // 203 !!
```
So it seems to be a memory layout \ mapping issue on x86  Code

**Comment by Gillibald** [comment]
Are you sure that you are not working with premultiplied alpha values here? What is the PixelFormat of your Surface?

**Comment by inforithmics** [comment]
var pixelGeometry = args.Surface.SurfaceProperties.PixelGeometry;
SkiaSharp.SKPixelGeometry.RgbHorizontal

**Comment by inforithmics** [comment]
The strange part is when I make new SKPaint there is already a Value in skPaint.Color and the returned value seems for me random. 
```
var skPaint = new SKPaint();
var dColor = skPaint.Color;
```
I isn't Corleated to the Accent Color. So I think the property reads somewhere from the Memory it shouldn't because it doesn't return the same value as is set.

Looking at them implementation (in. Net interop) SkiaApi.sk_paint_get_color(this.Handle)
Is used to read the SKColor and I think in Android x86 this is broken it reads from the wrong Memory Adress,
```
/// <summary>Gets or sets the paint's foreground color.</summary>
    /// <value />
    /// <remarks>The color is a 32-bit value containing ARGB. This 32-bit value is not premultiplied, meaning that its alpha can be any value, regardless of the values of R, G and B.</remarks>
    public SKColor Color
    {
      get
      {
        return SkiaApi.sk_paint_get_color(this.Handle);
      }
      set
      {
        SkiaApi.sk_paint_set_color(this.Handle, value);
      }
    }
```
I don't know x86 Assembler so I cannot investigate further.

**Comment by Gillibald** [comment]
A float is 4 bytes on both architectures so there should be no difference. The paint's color is stored as 4 float values.

**Comment by mattleibow** [comment]
This is getting weird now, the original issue said x64 was not work. But seems it is now and x86 is not?

What happens if you set the paint color to a red and then read it out? Does it still happen? SKColors.Red

**Comment by mattleibow** [comment]
Thanks for your patience with this. I think I figured it out. Just need to confirm and try a few things. I'll make sure this is fixed before we release.

**Comment by inforithmics** [comment]
I thought I execute the x64 Android Emulator, but I was really executing the x86 Emulator so the Title was wrong in the First place, so I corrected it to x86

**Comment by mattleibow** [comment]
Ah, that makes sense. I think I got a fix. It was the managed-native interop that was doing things wrong. I fixed that in #1023.

**Comment by inforithmics** [comment]
Are the Tests executed on every platform (x86, x64, Arm, Arm64) \ (Windows, Android ...) , because this only occured on x86 Android

**Comment by mattleibow** [comment]
There is a problem in that I only have tests for mac x64, win x64/x86 and linux x64. I have no other platforms yet. I am working on getting that going, but the tests are a bit more complex to write. Usually the 2 windows platforms pick this up, but for some reason my tests around colors are bad. I got a test there now that I want to check really breaks CI.

**Comment by mattleibow** [comment]
Well, that was disappointing. All the Windows tests just passed. Looks like Windows gets it right for some reason. The only thing I can think of is that the mono runtime on android does the interop slightly differently.

I will have to talk to those folks and find out.

**Comment by inforithmics** [comment]
The difference in the IL is in 1.68 the value is fetched in the following manner

1.68
  return (SKColor) SkiaApi.sk_paint_get_color(this.Handle);
 sk_paint_get_color is defined public and as return type uint.

1.68.1-rc170
  return SkiaApi.sk_paint_get_color(this.Handle);
  sk_paint_get_color is internal and as return Type SKColor
  so maybe interop layer converts uint correctly but not when it is in a struct.

**Comment by inforithmics** [comment]
I had a quick look with Ghidra at the assembly code and the assembler was the same, so it is definitly an interop thing.

1.68.1-rc-170
```
undefined4 sk_paint_get_color(int param_1)
{
  return *(undefined4 *)(param_1 + 0x28);
}
```
1.68.0
```
undefined4 sk_paint_get_color(int param_1)
{
  return *(undefined4 *)(param_1 + 0x28);
}
```

**Comment by Gillibald** [comment]
`typedef uint32_t SkColor;`

**Comment by Gillibald** [comment]
https://github.com/mono/SkiaSharp/blob/master/binding/Binding/SkiaApi.generated.cs#L2816 I guess we need to change that parameter to uint instead of `SKColor`
What is sizeof(SKColor)?

**Comment by inforithmics** [comment]
I made a test and specified the interop in my test program as uint

        [DllImport("libSkiaSharp", CallingConvention = CallingConvention.Cdecl)]
        internal static extern uint sk_paint_get_color(IntPtr param0);
        
        and then I castet it o SKColor like in the Version 1.68 and the values are
        now valid.

         var test = (SKColor)sk_paint_get_color(skPaint.Handle);
         var r = test.Red;
                // 1
                var g = test.Green;
                // 2
                var b = test.Blue;
                // 3
                var a = test.Alpha;
                // 4

**Comment by inforithmics** [comment]
var size1 = sizeof(SKColor);
    // 4
    var size2 = sizeof(uint);
    // 4

**Comment by mattleibow** [comment]
This was the interesting thing. I previously had the parameters as `SKColor` and the return types as `uint`.

Seems the value is fine when it is a parameter, but when it is a return, it can't just be forced. But I changed everything to be `uint` in the PR and do the work manually in the managed side now. 

It broke because i switched to the generator and did not take into account the return vs parameter. But now, it is just like the C code and it is cast. Should be back to normal.

**Comment by mattleibow** [comment]
@inforithmics thanks for all the research and opening this issue. It would have been pretty bad for this to get out to the stable release.

**Comment by inforithmics** [comment]
You're welcome and thanks for the fixed nuget package.

**Comment by makstraw** [comment]
Hey guys, had same issue working with my android application, information about windows theme affecting emulator output by @inforithmics gave me a clue on how to fix this issue.
If you remove **skin.path** and replace **skin.name** with something like 1080x1920 it will display emulator without physical device sprite around window and it will not be affected by windows theme.
