### ISSUE TITLE
[QUESTION] Click or touch listener for paths in svg

### ISSUE THREAD

**Issue by Almis90** [mono/SkiaSharp#1018]
I followed [this tutorial](https://www.pshul.com/2018/02/01/xamarin-forms-interactive-svg-image-using-skiasharp-with-pan-and-zoom/) and managed successfully to load svg with pan and zoom. My svg image consists of many `<path>` elements with `data-*` attributes. I need to know which path was clicked and get their attribute, or at least just get the id attribute. Is there any way to do that?

**Comment by charlesroddie** [comment]
SkiaSharp.Extended does have an SVG parser. https://github.com/mono/SkiaSharp.Extended/blob/master/SkiaSharp.Extended.Svg/source/SkiaSharp.Extended.Svg.Shared/SKSvg.cs
You can use adapt this code to parse svgs to your own structured format which will allow you to do what you want.

**Comment by charlesroddie** [comment]
SkiaSharp.Extended is here: https://github.com/mono/SkiaSharp.Extended

**Comment by FoggyFinder** [comment]
There is also [Svg.Skia](https://github.com/wieslawsoltes/Svg.Skia) library

**Comment by mattleibow** [comment]
@Almis90  I would totally have a look at Svg.Skia that @FoggyFinder posted. I don't think that SkiaSharp.Extended.Svg is going to get much love anytime soon - and it doesn't support understanding the image - it just draws it out. I think Svg.Skia probably has some APIs that you would want to use.

**Comment by Almis90** [comment]
Okay thank you guys, I will go with Svg.Skia then, closing the issue.
