### ISSUE TITLE
missing methods "SKMatrix.mapRect/mapPoints/mapVectors"

### ISSUE THREAD

**Issue by gentledepp** [mono/SkiaSharp#102]
hi!
these methods are missing in SkiaSharp.SKMatrix:

`
bool SkMatrix::mapRect(SkRect* dst, const SkRect& src) 
void SkMatrix::mapVectors(SkPoint dst[], const SkPoint src[], int count)
void SkMatrix::mapPoints(SkPoint dst[], const SkPoint src[], int count)
`

which would be really really handy.
see: https://github.com/google/skia/blob/master/src/core/SkMatrix.cpp
and: https://github.com/google/skia/blob/78d58d1084f0390c1c0f9123ac6e48efcd226f39/include/core/SkMatrix.h
I am using 1.49.4-beta

**Comment by gentledepp** [comment]
I now implemented it in C# and it seems this works, however I do not know if the native call could be faster?
`

        public RectangleF TransformRectangle(SKMatrix m, SKRect bound)
        {
            var start = new SKPoint(bound.Left, bound.Top);
            var end = new SKPoint(bound.Right, bound.Bottom);
            var pts = new[] { start, end };

            TransformPoints(m, pts);

            return new SKRect(start.X, start.Y, end.X, end.Y);
        }

        public void TransformVectors(SKMatrix m, SKPoint[] points)
        {

            foreach (var point in points)
            {
                // see http://math.stackexchange.com/questions/29257/find-2d-point-given-2d-point-and-transformation-matrix
                // transformvectors needs to IGNORE the translation! (see: http://stackoverflow.com/questions/3265169/matrix-transformpoints-vs-transformvectors)
                point.X = (m.ScaleX * point.X) + (m.SkewX * point.X); 
                point.Y = (m.SkewY * point.Y) + (m.ScaleY * point.Y); 
            }
        }

        public void TransformPoints(SKMatrix m, SKPoint[] points)
        {
            foreach (var point in points)
            { 
                // see http://math.stackexchange.com/questions/29257/find-2d-point-given-2d-point-and-transformation-matrix
                point.X = (m.ScaleX*point.X) + (m.SkewX*point.X) + m.TransX;
                point.Y = (m.SkewY*point.Y) + (m.ScaleY*point.Y) + m.TransY;
            }
        }
`

**Comment by migueldeicaza** [comment]
Implemented.
