### ISSUE TITLE
[BUG] `SKImage.FromBitmap(someBitmap)` returns null (on macOS) with SkiaSharp 1.68.0 and 1.68.1

### ISSUE THREAD

**Issue by knocte** [mono/SkiaSharp#1027]
**Description**

`SKImage.FromBitmap(someBitmap)` returns null, on macOS (with a someBitmap variable that is not null). Strangely enough, this happens when upgrading Xamarin.Forms from 3.0 (3.0.0.446417) to the latest 4.3 (4.3.0.991211). [Been bisecting this, and regression seems to happen somewhere between 3.6.709228, the last v3.6.x, and 4.0.0.425677, the first v4.0.x]

**Code**

https://github.com/knocte/geewallet/blob/b0dcca50c1fab8010e8376afea566763a1b5b8ec/src/GWallet.Frontend.XF/Controls/DonutChartView.fs#L252

**Expected Behavior**

This method shouldn't return null (it doesn't with XamarinForms 3.6).

**Actual Behavior**

It returns null, so my app ends up crashing with a NullReferenceException.

**Basic Information**

- Version with issue:  1.68.0 (tried upgrading to SkiaSharp.1.68.1 but it doesn't fix it).
- Last known good version:  1.68.0 along with Xamarin.Forms 3.6
- IDE:  Visual Studio for Mac 8.3.9.2
- Platform Target Frameworks: 
  - macOS:  Catalina 10.15.1
- Target Devices:  macBook

**Reproduction Link**

Run the macOS app in this branch: https://github.com/knocte/geewallet/commits/experiments/xf4

**Comment by knocte** [comment]
Updated to 1.68.1 and Catalina, still broken.

**Comment by mattleibow** [comment]
This is interesting that it happens with an update of form as this is a totally separate library. I'll have a look and see if I can spot anything. If you create a console app, or any other type of app that is not forms, does this still happen?

As a workaround, you can create a SKSurface use the canvas on that and then call Snapshot to get an SKImage https://docs.microsoft.com/en-us/dotnet/api/skiasharp.sksurface.snapshot?view=skiasharp-1.68.0

**Comment by knocte** [comment]
> As a workaround, you can create a SKSurface 

Have had a brief look around this and couldn't figure out what overload to use to create the SKSurface, can you elaborate?

> If you create a console app, or any other type of app that is not forms, does this still happen?

Good question I'll test that and report back.

**Comment by Gillibald** [comment]
https://docs.microsoft.com/en-us/dotnet/api/skiasharp.sksurface.create?view=skiasharp-1.68.0#SkiaSharp_SKSurface_Create_SkiaSharp_SKPixmap_

**Comment by knocte** [comment]
> https://docs.microsoft.com/en-us/dotnet/api/skiasharp.sksurface.create?view=skiasharp-1.68.0#SkiaSharp_SKSurface_Create_SkiaSharp_SKPixmap_

I know how to find the API, I just don't know which of those overloads to use in my particular case, to transform the code (I didn't write that code in the first place so it's a bit harder for me to wrap my head around it).

**Comment by mattleibow** [comment]
You are probably looking for the

```csharp
var info = new SKImageInfo(width, height) ;
var surface = new SKSurface.Create(info);
```

**Comment by knocte** [comment]
> You are probably looking for the

Thanks! Just tested this and I can verify that this workaround works.

**Comment by knocte** [comment]
> Thanks! Just tested this and I can verify that this workaround works.

Spoke too soon, the new Surface approach works on XF3.0 but still throws a NRE with XF4.3. So maybe what's happening is that the width and height values are 0 somehow with the latter, will continue investigating...

**Comment by knocte** [comment]
> So maybe what's happening is that the width and height values are 0 somehow with the latter

I was right about this hunch, and these values come from a SkSvg object (https://github.com/knocte/geewallet/blob/b0dcca50c1fab8010e8376afea566763a1b5b8ec/src/GWallet.Frontend.XF/Controls/DonutChartView.fs#L234), so maybe it's a bug in `SkiaSharp.Svg`?

**Comment by knocte** [comment]
Sorry for the noise, it's the Xamarin.Forms.DeviceInfo.ScalingFactor property which somehow in v4.3 is returning 0.0. Closing here so I'll open in XF repo.

**Comment by knocte** [comment]
In case you're curious I filed this as github issue number 8652 in XF repo.

**Comment by mattleibow** [comment]
Ah, OK. Thanks.  Issue: https://github.com/xamarin/Xamarin.Forms/issues/8652
