### ISSUE TITLE
missing SKImageEncoder (want to store SKBitmap to stream)

### ISSUE THREAD

**Issue by gentledepp** [mono/SkiaSharp#103]
Hi!

I am currently developing an SVG editor for Android (but very likely also for iOS, UWP, etc.)
My problem now is, that I would like to store an SKBitmap to a file as PNG.
I saw that there is a SKImageEncoder which does the job, but it is not mapped yet.
Any chances this will change in the near future? (I do not like workarounds)

https://github.com/google/skia/blob/master/src/images/SkImageEncoder.cpp

**Comment by JimSEOW** [comment]
SkImageEncoder is important for debugging SKBitmap. It will be great to include that. 
`bool success = SkImageEncoder::EncodeFile("myimage.png", bitmap, SkImageEncoder::kPNG_Type,100); `

**Comment by migueldeicaza** [comment]
If you have an SKBitmap, you can call:
```
var data = bitmap.Encode (SKImageEncodeFormat.Png, quality: 100);
using (var f = File.Create ("foo.png"))
   data.SaveTo (f);
```

**Comment by gentledepp** [comment]
Unfortunately this is not true:
SKBitmap (at last in version 1.49.4-beta) does not have a method "Encode" :-|

**Comment by JimSEOW** [comment]
@migueldeicaza Is it possible that your version of SkiaSharp with bitmap.Encode functionality in your e.g. laptop has not been uploaded to github. It will be great if you can do so to allow us to keep testing SKBitmap or SKImage. 

Currently, I have problem converting byte array to SKBitmap. The same Byte array can be converted to WPF WriteableBitmap without problem.

Any suggestion appreciate.

**Comment by gentledepp** [comment]
AAAH! Now I think I see what the problem is!
You meant "**SKImage**" but wrote "**SKBitmap**", right? Because SKImage has an "Encode" method :)
So if I have some "SKBitmap" that I'd like to store, I'd do the following (please correct me if I'm wrong):
`

            SKBitmap bitmap = ... I get it from somewhere - trust me;
            using(var img = SKImage.FromPixels(bitmap.Info, bitmap.Handle, si.Width * 4))
            {
                var data = img.Encode(SKImageEncodeFormat.Png, quality: 100);
                data.SaveTo(stream);
            }
`

**Comment by gentledepp** [comment]
I always get a SIGSEGV so I am doing something wrong, although it seems correct to me:
`
            SKBitmap bitmap = Image;
            try
            {
                bitmap.LockPixels();
                IntPtr p;
                bitmap.GetPixels(out p);
                using (var img = SKImage.FromPixels(bitmap.Info, p, bitmap.Width * bitmap.BytesPerPixel))
                {
                    var data = img.Encode(SKImageEncodeFormat.Png, quality: quality);
                    data.SaveTo(stream);
                }
            }
            finally
            {
                bitmap.UnlockPixels();
            }
`

**Comment by gentledepp** [comment]
I just saw, that there is a static "SKImage MakeFromBitmap(SKBitmap bitmap)" function in SKIA

see SKImage.h
https://chromium-skia-gm.commondatastorage.googleapis.com/doxygen/doxygen/html/SkImage_8h_source.html

**Comment by mattleibow** [comment]
@gentledepp Is this still an issue?

**Comment by mattleibow** [comment]
I am thinking that you are passing the wrong `IntPtr` to ``:

```csharp
    SKBitmap bitmap = Image;
    try
    {
        bitmap.LockPixels();
        IntPtr p;
        IntPtr pixels = bitmap.GetPixels(out p); // this line and the next
        using (var img = SKImage.FromPixels(bitmap.Info, pixels, bitmap.Width * bitmap.BytesPerPixel))
        {
            var data = img.Encode(SKImageEncodeFormat.Png, quality: quality);
            data.SaveTo(stream);
        }
    }
    finally
    {
        bitmap.UnlockPixels();
    }
```

You should never have to reference the `object.Handle` from outside the SkiaSharp library. If you have to, you can never know what the underlying native type will be.
