### ISSUE TITLE
[BUG] Uses of ArrayPool need to be checked

### ISSUE THREAD

**Issue by mattleibow** [mono/SkiaSharp#1031]
**Description**

@Gillibald usage of the array pool need to be checked because the arrays are not actually cleared.

In this example, the second buffer still has the values from the first Rent.

```
var buffer = ArrayPool<char>.Shared.Rent (NameBufferLength);
for (int i = 0; i < buffer.Length; i++) {
	buffer[i] = (char)i;
}
ArrayPool<char>.Shared.Return (buffer);

buffer = ArrayPool<char>.Shared.Rent (NameBufferLength);
````

This is used in 2 places so far (`TryGetGlyphName` and `GlyphToString`):

```csharp
fixed (char* first = buffer) {
	if (!HarfBuzzApi.hb_font_get_glyph_name (Handle, glyph, first, buffer.Length)) {
		name = string.Empty;
		return false;
	}
	name = new string (first);
	return true;
}
```

The issue might actually be in the usage of `name = new string (first);` as that creates a string from the full array, and does not stop at the `\0` character.

**Comment by mattleibow** [comment]
Looking a bit, I think it is because we are not writing a `\0` in the managed delegate in `GlyphNameProxyImplementation`

**Comment by mattleibow** [comment]
Something like this:

```csharp
var len = Math.Min (realName.Length, size - 1);
var bufferSpan = new Span<char> (nameBuffer, size);
var nameSpan = realName.AsSpan ();
nameSpan.CopyTo (bufferSpan);
bufferSpan[len] = '\0';
```

**Comment by Gillibald** [comment]
We can check for the termination. I kind of expected the termination in all results because that's what HarfBuzz should produce. We can go the safe way. Non terminated strings should throw.

**Comment by mattleibow** [comment]
I think harfbuzz is getting it right, it is our delegate when we copy the string: `nameSpan.CopyTo (bufferSpan);` I don't think it is adding the `\0` to the span.

**Comment by mattleibow** [comment]
@Gillibald I figured out what was happening with the name. It was the marshalling from a C `char` to a C# `char`. C has 1 byte, C# has 2 bytes.

I fixed this by actually passing a `byte[]` to the functions, and then copying into a string:
https://github.com/mono/SkiaSharp/pull/1034/files#diff-6b5300eff3e894978921b22e164317ceL209-L217
