### ISSUE TITLE
[BUG] Possible Leak with static Dictionary SKObject.instances

### ISSUE THREAD

**Issue by Knuddlbaer** [mono/SkiaSharp#1032]
SKObject holds Handled to WeakReferences in an static Dictionary bit never removes entries.

In RegisterHandle a new Entry is created with the handle ob object to an WeakReference. In DeregisterHandle, the Entry will only updates with WeakReference(null) but never deleted. This leads to tons of entries with tons of  WeakReferences.

**Expected Behavior**

On Dispose the handle need to be removed from SKObject.instances

**Actual Behavior**

- Version with issue:  1.68.1
- Last known good version:  N/A
- Platform Target Frameworks: Xamarin.Android
  - Android: 29
- Target Devices:   Pixel 2 XL

**Screenshot**

![skia](https://user-images.githubusercontent.com/58169312/69532581-6ac3dd00-0f76-11ea-922f-a1d1ae68aae9.png)

**Comment by MarchingCube** [comment]
I've noticed this in Avalonia (https://github.com/AvaloniaUI/Avalonia) as well, when we redraw we end up with a lot of `ConcurrentDictionary` allocations coming from SkiaSharp.

**Comment by Gillibald** [comment]
I think the AddOrUpdate call is wrong in the method that is responsible for the unregister. Should be easy to fix but haven't found time yet.

**Comment by Knuddlbaer** [comment]
AddOrUpdate do not remove the entry in the dictionary. If the SKObject is detroyed, the entry in dictionary is simple replaced by new weakreference. Instead the handle have to removed.

**Comment by FoggyFinder** [comment]
@Knuddlbaer Why issue was closed?

**Comment by mattleibow** [comment]
Reopening so we can get this fixed.

**Comment by mattleibow** [comment]
Closed in #1039

**Comment by mattleibow** [comment]
I just pushed the NuGets to the preview feed:
https://nugetized.blob.core.windows.net/skiasharp-eap/index.json

1.68.2-preview.5
