### ISSUE TITLE
Design: sk_matrix_t, should it contain fTypeMask?

### ISSUE THREAD

**Issue by migueldeicaza** [mono/SkiaSharp#104]
The C++ `SkMatrix` type contains an optimization, whenever a new `SkMatrix` is created, or modified, the value of fTypeMask is updated to reflect the contents of the Matrix.  This helps quickly decide if a matrix for example only contains translation, or if the matrix represents the identity.   This speeds up various operations in the stack.

The `sk_matrix_t` data type that is surfaced on the C API does not include this information.  This means that the code is unable to use the optimizations built into `SkMatrix`, and instead for some operations, the type of the matrix must be computed at runtime.

Perhaps we should extend `sk_matrix_t` to include this flag, and additionally, we could add assertions to the runtime to ensure that `SkMatrix` and `sk_matrix_t` are toll-free bridged, to prevent extra copying of the matrices at runtime (this can also be done for a few other things as well).

> VS bug [#738681](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/738681)

**Comment by mattleibow** [comment]
Google has started working on a new matrix type `SkM44` that does not have this feature. Based on their research, keeping track of the mask was reducing performance.
