### ISSUE TITLE
[BUG] Use the buildTransitive folder

### ISSUE THREAD

**Issue by mattleibow** [mono/SkiaSharp#1041]
Make sure all projects with a .targets and/or .props file also use the `buildTransitive` folder.

https://github.com/NuGet/Home/wiki/Allow-package--authors-to-define-build-assets-transitive-behavior

**Comment by mattleibow** [comment]
Just bringing in a comment from @vijayasurya20: https://github.com/mono/SkiaSharp/issues/1050#issuecomment-561184570

> As you have mentioned, while installing the SkiaSharp into the test project works fine.
>
> Since we have added the .Net Standard library project which has "SkiaSharp" as dependent package is added as dependency of Test project, then please let me know why should we need to add "SkiaSharp" package individually into the test project. Because the Library project itself should have every dependency it needs.

**Comment by mattleibow** [comment]
@vijayasurya20 raises a good point - why should the test project need it to be specified. But this is not as straight forward as it may seem.

For .NET Core and all the platforms other than the full .NET Framework, the platform has the understanding that it should only reference the native libraries at the end of the chain. If I create a netcoreapp with a long dependency chain with only the last referencing SkiaSharp, the app still works. This is because the SkiaSharp reference is bubbled all the way up, and the final app project also includes the native binaries in the runtimes folder. As a result, everything works.

For the full .NET Framework, it does not have this idea of the runtimes folder, so I have to manually copy the files to the output directory. Right now, all this logic is in a build target. That build target is only referenced by the project that pulls in SkiaSharp. As a result, the MANAGED reference to SkiaSharp get bubbled up as it is a reference, but not the native binaries.

This is obviously not the best. But, if we make the targets file bubble up as well, then EACH project will have the native binaries in the output. Is this desirable?

We _could_ make the native binaries only copy when the project is an app project (Exe or WinExe). This would work, but what about test projects (which is one of the reasons for this issue)?

After all this, we are at a place where .NET Core works fine and .NET Framework is a little dodgy. But, all we have to do is install SkiaSharp into the top-level project. 

I am moving this to v1.68.2 until I can decide what the best thing to do is.

**Comment by dotMorten** [comment]
> if we make the targets file bubble up as well, then EACH project will have the native binaries in the output

I used to limit this based on the output type (ie don't do it for class libraries). However that caused problems for people building plugins for other products, as they were now missing the native assemblies. So yes I'd say deploy it regardless.

**Comment by vijayasurya20** [comment]
Hi @mattleibow ,

I have checked in latest 1.68.1.1 release version, but still i am facing the same issue as raised in the following forum.
https://github.com/mono/SkiaSharp/issues/1050

Please let me know whether it is fixed? If not so when can I expect the fix for this issue?

Regards,
Vijayasurya A

**Comment by mattleibow** [comment]
I just tried your sample project attached to the other issue and upgraded. The tests ran in the IDE. All I did was unzip, open and upgrade.

**Comment by hafner** [comment]
> I just tried your sample project attached to the other issue and upgraded. The tests ran in the IDE. All I did was unzip, open and upgrade.

so I'm having the same problem in my personal project. I also downloaded vijayasuya20's project and it's still having the same error I'm having. I unzipped, opened and upgraded and still get the same error. What can I try next? If I knew we could solve multiple people's issue at once.

**Comment by vijayasurya20** [comment]
Hi @mattleibow ,

As @hafner said, I am also still facing the same error in my end.

Please let me know what should i need to do from my end to resolve this issue.

Regards,
Vijayasurya A

**Comment by hafner** [comment]
What I don't get is both projects seem to have all of the dlls copied to the output directory yet it still doesn't work.

**Comment by bender2k14** [comment]
My experience is similar to @mattleibow's; his description below is also true for me.
> I just tried your sample project attached to the other issue and upgraded. The tests ran in the IDE. All I did was unzip, open and upgrade.

In particular, instead of the test failing with a `TypeInitializationException` it now fails with a `FileLoadException`.

I poked around a bit further and figured the following out.  Maybe it is helpful.

I have a simple WPF application with a dependency on the latest prerelease of SkiaSharp (version 1.68.2 (Preview Build 17)).  The application works when targeting .NET Core 3.0 and throws a `TypeInitializationException` (c.f. #1050) when targeting .NET Framework 4.7.2.

I also found three workarounds:
1. Change platform from "Any CPU" to "64-bit";
2. Change platform from "Any CPU" to "32-bit"; and
3. Leave platform as "Any CPU" but then copy `netcoreapp3.0\runtimes\win-x64\native\libSkiaSharp.dll` to `net472`.

In case three (when platform is set to "Any CPU"), it seems like the 32-bit version of `libSkiaSharp.dll` is copied into the output directory.  In particular,
- `netcoreapp3.0\runtimes\win-x86\native\libSkiaSharp.dll` and
- `net472\libSkiaSharp.dll`

have the same MD5 hash.

**Comment by mattleibow** [comment]
Ah, very good catch. That is often the case. The main issue here is that I think the test is built as 32-bit and then run as 64-bit (or vice versa). Switching to a specific architecture usually fixes that as @bender2k14 found. But, I believe you can ALSO switch the CPU that the tests run in in VS to control the runner.

**Comment by hafner** [comment]
So my whole 4.7.2, ten project solution (including libraries and tests) were all targeting "Any CPU." After spending hours and hours on it what @bender2k14 said got me going, so thank you. I switched everything over to 32-bit. Although I need to research what the implications of doing this vs Any CPU are. Is an official fix coming?

**Comment by loketha** [comment]
Hi @mattleibow 

As per @bender2k14 suggestion, I checked the project with different configurations. But Still i am facing the same FileLoadException issue.

Please let me know what should i need to do from my end to resolve this issue.

Regards,
Loketha E

**Comment by mattleibow** [comment]
Does anyone have a repro project of this? Also, remember that MSBuild may detect that it needs to copy a 32/64 bit assemblies, and then VS will run the other platform. There is a option in the test explorer setting to pick what CPU arch to use.

Also, it might be the case that you have selected the "prefer 32-bit" in the project options. So, even though the runner is selecting 64-bit, the runtime actually thinks it is 32-bit.

What I usually do is make sure the "prefer 32-bit" is OFF in the project settings, build Any CPU and then make sure that my test explorer is running 64-bit. This way, MSBuild copies the 64-bit, and the runner is 64-bit.

> Also note, the p[refer 32-bit option is just for Windows. I believe it is ignored on macos/linux. I might be wrong, but it is usually safe to disable.

**Comment by vijayasurya20** [comment]
Hi @mattleibow ,

First of all, Thank you for all your efforts.

As you have mentioned, we have checked our project and ensured that the "Prefer 32 bit" option is disabled both in our Library and also in the Test project. In both of our projects, we set the build target platform as "x86" only, but still, we are facing the same issue in our end. Can you please check this in your end using the project shared by us in the following link.

https://github.com/mono/SkiaSharp/issues/1050 

Please let us know if you have any questions.

Regards,
Vijayasurya A

**Comment by mattleibow** [comment]
I just did that and it worked. Steps:
 - download zip
 - update SkiaSharp to v1.68.1.1
 - switch to x86
 - right click the project and select "Run Tests"
 - observe the green wave

I also notice this on both projects:
```csharp
    <Platforms>AnyCPU;x86</Platforms>
    ....
    <PropertyGroup Condition=" '$(Configuration)' == 'Debug' ">
      <PlatformTarget>x86</PlatformTarget>
    </PropertyGroup>
```

You probably should not need that. 

I removed them and the test was red. This is because the test runner now was using x86, but the compiler was optimizing for x64. To fix this, I just selected x64 from the test runner's settings:
![image](https://user-images.githubusercontent.com/1096616/74646233-18afe380-5182-11ea-8755-524086037820.png)

But this last option is up to you.

**Comment by vijayasurya20** [comment]
Hi @mattleibow,

Thank you for your suggestion.

We have tried both of your suggestions in our end, but still, the persists in our end. For your reference, please find the video illustration below as follows.
[Video.zip](https://github.com/mono/SkiaSharp/files/4255723/Video.zip)


Can you please check this and provide us solution? 

Regards,
Vijayasurya A

**Comment by vijayasurya20** [comment]
Hi @mattleibow ,

Can you please share your suggestion on this as requested earlier.

Regards,
Vijayasurya A

**Comment by ManishSync** [comment]
Hi @mattleibow,

Can you please share your suggestion on this as requested earlier.

Regards,
Manish Ravichandran

**Comment by mattleibow** [comment]
@vijayasurya20 @ManishSync Sorry for the delay in getting back to you. I had a look at your screen capture and I think I see what is going on. All the features for supporting your scenario are not supported in VS2017. It is recommended to use VS2019.

The feature for `buildTransitive` folders in NuGets are only supported in NuGet v5. VS2017 only has NuGet v4.6.

Another issue that is sort of contributing to this not working is the fact that the `office-processing` is `netstandard` (which is a good thing). The .NET Standard projects do not make use of the .targets files that copy files because they make use of a new feature in NuGet - the `runtimes` folder. However, this is not coming into play right now because the test project is net471 - which does not support the `runtimes` feature.

There are a few solutions:
 - Switch the `office-processing` project to `net471` so that the .targets files start to come into play.
 - Multi-target the `office-processing` project so the tests can use net471 and the apps can use netstandard: `<TargetFrameworks>netstandard2.0;net471</TargetFrameworks>`.
 - Switch to netcoreapp2.2 for the tests: `<TargetFramework>netcoreapp2.2</TargetFramework>`. For this I did have to remove the platform things (all the x86). The .NET Core runtime will handle the native files
 - Install the SkiaSharp NuGet into the test project.

Let me know if any of these things help.
