### ISSUE TITLE
[BUG] SKImageSourceHandler not found in 1.68.1 for iOS project

### ISSUE THREAD

**Issue by pmahend1** [mono/SkiaSharp#1042]
**Description**
SKImageSourceHandler not found in 1.68.1 for iOS projecct

**Code**

**Expected Behavior**
Should be found

**Actual Behavior**
Compile error

**Basic Information**

- Version with issue:   1.68.1
- Last known good version:  1.68.0
- IDE:   Visual Studio / Visual Studio for Mac
- Platform Target Frameworks: iOS 
  - Android: NA
  - iOS:  13.2
  - Linux: NA
  - macOS:  NA
  - Tizen:  NA
  - tvOS:  NA
  - UWP:  NA
  - watchOS:  NA
  - Windows Classic: NA
- Target Devices:  NA
  - 
  - 

**Screenshots**

![image](https://user-images.githubusercontent.com/21352870/69986445-69148f00-150b-11ea-83e9-cbcf340545e8.png)

**Reproduction Link**

[SkiaImageSourceHandlerIssue](https://github.com/pmahend1/XamarinFormsIssues/tree/master/SkiaImageSourceHandlerIssue)

**Comment by mattleibow** [comment]
Just checking that you have installed the SkiaSharp.Views.Forms NuGet into the iOS project? That type should be in that package.

I can see it there: https://www.fuget.org/packages/SkiaSharp.Views.Forms/1.68.1/lib/xamarin.ios/SkiaSharp.Views.Forms.dll/SkiaSharp.Views.Forms/SKImageImageSource

**Comment by pmahend1** [comment]
This is what we are getting on iOS project  
![image](https://user-images.githubusercontent.com/21352870/69985513-54cf9280-1509-11ea-9ab8-c481e2efba4a.png)

**Comment by pmahend1** [comment]
@is it because of this change in nuspec?

![image](https://user-images.githubusercontent.com/21352870/69988670-1689a180-1510-11ea-83e8-d998d82bdcd0.png)

**Comment by mattleibow** [comment]
It shouldn't be since iOS is .NET Standard 2.0 and the type should be in THAT nuget, not the dependencies.

Let me have a look at your repo.

**Comment by mattleibow** [comment]
I had a look and I see what is happening here. I moved the netstandard library into the ref folder in the nuget so that it won't actually run. But, it appears that the ref folder overrides ALL the platforms.

This typically is fine if the APIs are the same, but because we have more public types (such as SKImageSourceHandler) in the iOS (and the others) this doesn't work.

**Comment by mattleibow** [comment]
@pmahend1 Thanks for reporting this issue. I have pushed out a fix to the preview feed:
    https://aka.ms/skiasharp-eap/index.json

Try version `1.68.1.1-preview.2` as that should have the fix. _(there is a 1.68.2 series, but that is actually older because I decided to get .1.1 out first with this fix)_

**Comment by pmahend1** [comment]
I checked ,it seem to have fixed the issue. @mattleibow Please let me know once you release into nuget org.

**Comment by mattleibow** [comment]
Awesome. Will do.
