### ISSUE TITLE
[QUESTION] Latest `libSkiaSharp.so`

### ISSUE THREAD

**Issue by NotOfficer** [mono/SkiaSharp#1046]
Hello, where can i find the latest `libSkiaSharp.so` file as its not attached to the github release?

**Comment by mattleibow** [comment]
Just want to check why you are looking for the .so directly?

If you are using .NET and just want to use it, it is actually available on nuget:
 - https://www.nuget.org/packages/SkiaSharp.NativeAssets.Linux
 - https://www.nuget.org/packages/HarfBuzzSharp.NativeAssets.Linux

There is also one with out the fontconfig dependency:
 - https://www.nuget.org/packages/SkiaSharp.NativeAssets.Linux.NoDependencies

**Comment by NotOfficer** [comment]
Ah thanks, i didn't know there was a package for the linux dependencies.

**Comment by mattleibow** [comment]
Closing this as you should be able to use the NuGet. Feel free to reopen (or a new one) if there are issues.
