### ISSUE TITLE
SkiaSharp from NuGet not work with UWP

### ISSUE THREAD

**Issue by tower120** [mono/SkiaSharp#105]
This line
`var canvas = SKSurface.Create(100, 100, SKColorType.N_32, SKAlphaType.Premul);`

throws 
`'System.BadImageFormatException' in Unknown Module.`

Steps to reproduce:
-  Update to VS 2015 update 3.
- Make Blank UWP project
- Install SkiaSharp from NuGet
- add button and onclick handler:
```
button.Click += delegate (object sender, RoutedEventArgs e){
     var canvas = SKSurface.Create(100, 100, SKColorType.N_32, SKAlphaType.Premul);
};
```
- launch in Debug x86 / x64 mode

**Comment by mattleibow** [comment]
This should be fixed in the 1.53.0 release

**Comment by eladgol** [comment]
Problem still exists on 1.53.0 and 1.54.1.

**Comment by mattleibow** [comment]
@eladgol Can you please provide more info? Probably most important is what version of Windows you are running and if you are using an emulator or not. 

I have not been able to reproduce this at all. You can also try out the new SkiaSharp Views for Xamarin.Forms: http://forums.xamarin.com/discussion/80325/announcing-skiasharp-v1-54-1-and-skiasharp-views
