### ISSUE TITLE
[QUESTION] How to crop image using SKPixmap and SKImage?

### ISSUE THREAD

**Issue by jvhgamer** [mono/SkiaSharp#1059]
**Description**
I'm using Skiasharp to crop a screenshot. Currently I'm seeing an issue with the image after cropping it. The image is all black as if it is completely blank. However before cropping, if we save the image, it returns okay.

Please could you suggest how to properly save a cropped image?

NOTE*: The code commented out under headers "crop image/bounds of cropped image/size" is what we are using to crop the image. Currently it is cropped out to show where the problem appears to be. As is the code will return the screenshot successfully and unmodified.

Thanks
-j

**Code**
```
// Use this function to crop a screen shot to a specific element.  
public byte[] test(byte[] screenshotData, View element)
{
    //  locate IntPtr to byte[] of uncropped screenshot
    GCHandle gch = GCHandle.Alloc(screenshotData, GCHandleType.Pinned);
    IntPtr addr = gch.AddrOfPinnedObject();

    //  assign initial bounds
    SKImageInfo info = new SKImageInfo((int)App.Current.MainPage.Width,
        (int)App.Current.MainPage.Height);

    //  create initial pixel map
    using SKPixmap pixmap = new SKPixmap(info, addr);
    //  Release
    gch.Free();

    //  create bitmap
    using SKBitmap bitmap = new SKBitmap();
    //  assign pixel data
    bitmap.InstallPixels(pixmap);

    //  create surface
    using SKSurface surface = SKSurface.Create(info);
    //  create a canvas for drawing
    using SKCanvas canvas = surface.Canvas;
    //  draw
    canvas.DrawBitmap(bitmap, info.Rect);

    //  get an image subset to save
    SKImage image = surface.Snapshot();
    SKRectI rec = new SKRectI((int)element.Bounds.Left, (int)element.Bounds.Top,
        (int)element.Bounds.Right, (int)element.Bounds.Bottom);

    //  crop image
    //image = image.Subset(rec);

    //  bounds of cropped image
    //SKImageInfo info2 = new SKImageInfo(rec.Width, rec.Height);

    //  size
    //int size = info2.RowBytes * info2.Height;
    int size = info.RowBytes * info.Height;

    using SKPixmap pmap = image.PeekPixels();
    IntPtr ptr = Marshal.AllocHGlobal(size);
    pmap.ReadPixels(pmap.Info, ptr, pmap.RowBytes);

    byte[] managedArray = new byte[size];
    Marshal.Copy(ptr, managedArray, 0, size);
    image.Dispose();

    return managedArray;
}
```

Expected Behavior
Save the cropped image

Actual Behavior
Image is blank (all black)

Basic Information
Version : 1.68.1
IDE: Visual Studio
Platform Target Frameworks:
Android: 8 and above
iOS: 9 and above

**Comment by jvhgamer** [comment]
EDIT: Believe this simpler code can replace the latter. Still the cropped result image is all black, however.
```
byte[] bytes = SKBitmap.FromImage(image).Bytes;
image.Dispose();
return bytes;
```

Can replace
```
//  bounds of cropped image
//SKImageInfo info2 = new SKImageInfo(rec.Width, rec.Height);

//  size
//int size = info2.RowBytes * info2.Height;
int size = info.RowBytes * info.Height;

using SKPixmap pmap = image.PeekPixels();
IntPtr ptr = Marshal.AllocHGlobal(size);
pmap.ReadPixels(pmap.Info, ptr, pmap.RowBytes);

byte[] managedArray = new byte[size];
Marshal.Copy(ptr, managedArray, 0, size);

return managedArray;
```

**Comment by jvhgamer** [comment]
Am I allowed to bump? ... If not I apologize and will delete this comment. Thanks for reading.

**Comment by mattleibow** [comment]
Sorry about the delay. I thought I responded. Looks like I just opened the tab :)

Looking at your code, you may be doing `gch.Free();` too soon as `new SKPixmap(info, addr);` does not actually copy the pixels, it just references them. I also see a few more native operations as well that are maybe not needed. Also, there are a few good members on `SKPixmap` that you can use directly.

Here, I have created a short method that you should be able to use - just using `SKPixmap.ExtractSubset`. The subset actually references the source image as well, so make sure to not dispose/free the data until the subset is encoded. Encoding makes a copy of the data, so afterwards it is fine to dispose the source.

```csharp
public static byte[] CreateSubset(byte[] screenshotData, SKRectI viewBounds)
{
    var info = new SKImageInfo(1600, 1200);

    // pin the bytes
    var gch = GCHandle.Alloc(screenshotData, GCHandleType.Pinned);
    try
    {
        // create a pixmap from the bytes
        var addr = gch.AddrOfPinnedObject();
        using var pixmap = new SKPixmap(info, addr);

        // get the subset
        var subset = pixmap.ExtractSubset(viewBounds);

        // encode to a data object
        using var data = subset.Encode(SKPngEncoderOptions.Default);

        // convert data to bytes
        return data.ToArray();
    }
    finally
    {
        // release bytes
        gch.Free();
    }
}
```
