### ISSUE TITLE
[BUG] Unable to load DLL 'libHarfBuzzSharp' during WPF "Text Shaping" sample

### ISSUE THREAD

**Issue by bender2k14** [mono/SkiaSharp#1061]
**Description**

Unable to load the DLL `libHarfBuzzSharp` from the `Text Shaping` sample in the `Gallery` solution for WPF.

**Steps to Reproduce**

1. Clone repo
2. Open the `master` branch
3. Open the WPF `Gallery` sample at `C:\Code\ThirdParty\SkiaSharp\samples\Gallery\WPF\SkiaSharpSample.sln` using Visual Studio
4. Set `SkiaSharpSample` as the StartUp project*
5. Start debugging in Visual Studio
6. Click `Text Shaping`
![2019-12-13_08-07-48_8](https://user-images.githubusercontent.com/34664007/70806518-252e4f00-1d81-11ea-85fb-822fc7335e78.png)

*This step would not be necessary if this project appeared first in the `sln` file.  All other projects are library projects (so they are not executable projects), so this is the only project that ever needs to be the startup project.

**Expected Behavior**

Some sample is displayed.

**Actual Behavior**

An unhandled exception on line
https://github.com/mono/SkiaSharp/blob/975b47a913bf849276e40358ba577245d0f86de3/binding/HarfBuzzSharp.Shared/Blob.cs#L90
with message

> System.DllNotFoundException: 'Unable to load DLL 'libHarfBuzzSharp': The specified module could not be found. (Exception from HRESULT: 0x8007007E)'

![2019-12-13_08-07-59_9_devenv](https://user-images.githubusercontent.com/34664007/70806560-3bd4a600-1d81-11ea-8119-23ab8428ff35.png)

**Basic Information**

- Version with issue: current commit on `master`, which is https://github.com/mono/SkiaSharp/commit/ff7cc7823c3fe9d68d2977c75bbeb51cc0c1c94a
- Last known good version: Unknown (didn't try any other commits)
- IDE:  Visual Studio 2019 Enterprise 16.4.1 (which is currently the latest)
- Platform Target Frameworks:
  - Windows Classic:
    - Name: Microsoft Windows 10 Enterprise
    - Version: 10.0.18362 Build 18362

**Comment by mattleibow** [comment]
This should be working again.
