### ISSUE TITLE
Add support for the SkSVG canvas backend

### ISSUE THREAD

**Issue by zone117x** [mono/SkiaSharp#107]
We're currently using [NGraphics](https://github.com/praeclarum/NGraphics) for exporting vector images for the various platforms. We'd really like to be able to output an SVG file and Skia looks promising. We'd give SkiaSharp a try if this feature ever makes it. 

https://skia.org/user/api/canvas#sksvg

**Comment by Emasoft** [comment]
I think that full SVG support should be added to th SkiaSharp library, including SVG Animations ( https://svgwg.org/specs/animations/ ). 

If SkiaSharp is going to be the engine behind Xamarin.Forms (and the whole WPF crossplatform), then SVG support is as necessary as PNG or JPG support. 
You cannot treat SVG as a external option, something that you can delegate to a secondary framework made by amateurs.
It is the main vector image format around. 90% of all vector graphic resources (icons, graphic elements, UI skins, animations, backgrounds, etc...) are made in SVG, exported in SVG and distributed in SVG. Artists and designers are used to save their vector images in SVG format. App design tools like Sketch or AdobeXD export the app design storyboards as SVG files, ready to be imported in the app. Popular mobile apps like Viber use SVG SMIL animations extensively for ALL their awesome animated stickers. With the advent of the modern high density display jungle, everybody is dropping bitmap assets for SVG assets.
Intro animations for the "Onboarding" phase of new apps are now often made with SVG SMIL animated clips. The new popular SVG morphing algorithms are now used by many design tools to create animated visual transitions easily between UI states, just by choosing a start and an end SVG image. From those two inbetweens are automatically generated at 60 fps, for a smooth and modern UI.
No vector framework is going to succeed with developers without SVG support, no more than a bitmap imaging framework without PNG or JPG support. Other crossplatform 2D libraries like NGraphics for example already support SVG.
This is very urgent, otherwise Xamarin.Forms is going to be more and more detached from the needs of modern app development.

**Comment by mattleibow** [comment]
I don't think this is going to be done at all anytime soon. 

Here is my code (it binds all that there is to bind):
 - Managed Branch: https://github.com/mono/SkiaSharp/tree/xamarin-svg-canvas
 - Native Branch: https://github.com/mono/skia/tree/xamarin-svg-canvas

I did a check to see what's what and this is what I found:
 - `SkSVGCanvas` is a thing, but it is very limited:
    - basically just paths, shapes, text and images
    - linear gradients are supported, but no others
    - effects and filters are not

Unless I get a go-ahead from @bholmes or @migueldeicaza, I will not be merging these changes into the main branch anytime soon. We have to wait for SVG to become something in Skia.

**Comment by mattleibow** [comment]
A `SKSvgCanvas` can be created on the fly, requiring only a bounds and an `SKXmlWriter`:

```csharp
// create a writeable stream
// SKFileWStream skStream = ...
// SKDynamicMemoryWStream skStream = ...
System.IO.Stream stream = ...
SkiaSharp.SKManagedWStream skStream = new SKManagedWStream(stream);

// now create the xml writer and the canvas
using (var writer = new SKXmlStreamWriter(skStream))
using (var canvas = SKSvgCanvas.Create(SKRect.Create(0, 0, (int)Bounds.Width, (int)Bounds.Height), writer))
{
    // draw as normal since "canvas" is just a "SKCanvas"
}

// you may have to:
//skStream.Flush();
```

**Comment by zone117x** [comment]
Awesome job on getting those bindings. 

> basically just paths, shapes, text and images

That's basically all I need for what we are using NGraphics for. Hopefully we'll get a chance to try it out soon. Thanks!

**Comment by mattleibow** [comment]
@zone117x Make sure you use the svg betas as they haven't been merged into master/stable yet

**Comment by wieslawsoltes** [comment]
I have run some tests using `Version 1.53.2 (SVG Beta 1)` and generally works great!

Found one bug when drawing paths with multiple figure.

The following path is not drawn correctly in Svg:
```
M210,150L330,150L330,210L210,210z M225,165L315,165L315,195L225,195z
```

Below is the `Svg` output using `SkiaSharp`:
```SVG
<?xml version="1.0" encoding="utf-8" ?>
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="840" height="600">
	<rect fill="rgb(255,255,255)" stroke="none" width="840" height="600"/>
	<path fill="rgb(0,0,0)" fill-opacity="0.3137255" stroke="none" d="M210 150L330 150L330 210L210 210L210 150ZM225 165L315 165L315 195L225 195L225 165Z"/>
	<path fill="none" stroke="rgb(0,0,0)" stroke-width="2" stroke-linecap="round" stroke-miterlimit="4" d="M210 150L330 150L330 210L210 210L210 150ZM225 165L315 165L315 195L225 195L225 165Z"/>
</svg>
```

In above `Svg` you can see that there are two paths, one with fill and one with stroke only, but they do not combine as they should.

Code:
```
var presenter = new ContainerPresenter(); // MY DRAWING  CODE

using (SKFileWStream stream = new SKFileWStream(path))
using (var writer = new SKXmlStreamWriter(stream))
using (var canvas = SKSvgCanvas.Create(SKRect.Create(0, 0, (int)container.Width, (int)container.Height), writer))
{
    presenter.Render(canvas, renderer, container, 0, 0); // MY DRAWING CODE
}
```

I use same drawing code for creating Pdf's using SkiaSharp and output is correct.

Pdf:
![2016-08-27_23-38-51](https://cloud.githubusercontent.com/assets/2297442/18030253/95a274e0-6caf-11e6-9953-88a3217e29ea.png)

Svg:
![2016-08-27_23-38-46](https://cloud.githubusercontent.com/assets/2297442/18030258/a12066d8-6caf-11e6-8d70-0d4b28bcd283.png)

**Comment by wieslawsoltes** [comment]
I found the issue, the svg canvas backend does not set proper fill-rule, this is fixed version as it should be (the only difference is ` fill-rule="evenodd"`):
```SVG
<?xml version="1.0" encoding="utf-8" ?>
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="840" height="600">
    <rect fill="rgb(255,255,255)" stroke="none" width="840" height="600"/>
    <path fill-rule="evenodd" fill="rgb(0,0,0)" fill-opacity="0.3137255" stroke="none" d="M210 150L330 150L330 210L210 210L210 150ZM225 165L315 165L315 195L225 195L225 165Z"/>
    <path fill="none" stroke="rgb(0,0,0)" stroke-width="2" stroke-linecap="round" stroke-miterlimit="4" d="M210 150L330 150L330 210L210 210L210 150ZM225 165L315 165L315 195L225 195L225 165Z"/>
</svg>
```

This is related to the fact that to use different color for fill and stroke using `SKPaint` you have to issue two separate draw calls:
```C#
private void DrawPathInternal(SKCanvas canvas, SKPaint brush, SKPaint pen, bool isStroked, bool isFilled, SKPath path)
{
    if (isFilled)
    {
        canvas.DrawPath(path, brush);
    }

    if (isStroked)
    {
        canvas.DrawPath(path, pen);
    }
}
```

**Comment by zone117x** [comment]
The fix should probably be implemented in Skia?

**Comment by mattleibow** [comment]
@wieslawsoltes I think @zone117x is correct. If you look here: https://github.com/google/skia/blob/589a39eb81d25fa7af95e7366db17ac7a70a7d03/src/svg/SkSVGDevice.cpp#L348 they only do a few things. 

I would suggest opening an issue on http://bugs.skia.org and maybe creating a fiddle (https://fiddle.skia.org/) showing what you are trying to do.

https://bugs.chromium.org/p/skia/issues/detail?id=5596

**Comment by wieslawsoltes** [comment]
@mattleibow Opened issue https://bugs.chromium.org/p/skia/issues/detail?id=5712

**Comment by mattleibow** [comment]
That is awesome! 

Just repo-ing the C# code for "testing" purposes:

```csharp
using (var stream = new SKFileWStream("test.svg"))
using (var streamWriter = new SKXmlStreamWriter(stream))
using (var canvas = SKSvgCanvas.Create(new SKRect(0, 0, 100, 100), streamWriter))
{
	var p1 = new SKPaint();
	p1.Color = SKColors.Red;
	p1.IsAntialias = true;
	p1.Style = SKPaintStyle.Fill;
	p1.StrokeWidth = 1;

	var p2 = new SKPaint();
	p2.Color = SKColors.Black;
	p2.IsAntialias = true;
	p2.Style = SKPaintStyle.Stroke;
	p2.StrokeWidth = 2;

	var path = new SKPath();
	path.FillType = SKPathFillType.EvenOdd;
	path.MoveTo(10.0f, 10.0f);
	path.LineTo(90.0f, 10.0f);
	path.LineTo(90.0f, 90.0f);
	path.LineTo(10.0f, 90.0f);
	path.Close();
	path.MoveTo(20.0f, 20.0f);
	path.LineTo(80.0f, 20.0f);
	path.LineTo(80.0f, 80.0f);
	path.LineTo(20.0f, 80.0f);
	path.Close();

	canvas.DrawPath(path, p1);
	canvas.DrawPath(path, p2);
}
```

**Comment by wieslawsoltes** [comment]
@mattleibow https://bugs.chromium.org/p/skia/issues/detail?id=5712#c2

**Comment by daniel-luberda** [comment]
## Opacity - Not working:
```XML
<svg width='50' height='50' viewBox='0 0 50 50'><rect width='50' height='50' fill='#000' opacity='0.5' /></svg>
```
## Fill-Opacty - Working
```XML
<svg width='50' height='50' viewBox='0 0 50 50'><rect width='50' height='50' fill='#000' fill-opacity='0.5' /></svg>
```

More here: https://github.com/luberda-molinet/FFImageLoading/issues/436

**Comment by mattleibow** [comment]
@daniel-luberda I have added support for "opacity" in this commit: https://github.com/mono/SkiaSharp/commit/cfe6afbf8aece4a2d4b835b727073cc50a0015da

**Comment by mattleibow** [comment]
I have merged the svg branch into the master, but please note that this area (svg canvas) is still very much in beta on the native side. Thus, it is a beta state in SkiaSharp.

**Comment by zone117x** [comment]
@mattleibow Thanks for committing to this and getting it done. Great work!
