### ISSUE TITLE
[FEATURE] Define HAVE_FREETYPE to support fonts loaded by FreeType

### ISSUE THREAD

**Issue by warappa** [mono/SkiaSharp#1070]
### Problem
For loading **Adobe Type 1 fonts** I need to load them with **FreeType** first and hand the loaded font over to **HarfBuzz** for layout. HarfBuzz has built-in support for it - if enabled at compile time.

Currently `libHarfBuzzSharp.dll` is built without `HAVE_FREETYPE` so the function `hb_ft_font_create` is not available.

### Desired Change
* Update the config.h files to define `HAVE_FREETYPE` (like in https://github.com/mono/SkiaSharp/blob/dc9b306e283dcb1eef21458a6fe69d5294ceb369/native/windows/libHarfBuzzSharp/config.h)
* C# bindings to `hb_ft_*` functions
* An additional `SKShaper` constructor to directly provide a `HarfBuzzSharp.Font` instead of just `SKTypeface`

**Describe alternatives you've considered**
`SharpFont.HarfBuzz` would actually provide such functionality but doesn't integrate with `HarfBuzzSharp` and therefore SkiaSharp.
Also it is not compatible with .NET Core 3/.NET Standard.

**Comment by Gillibald** [comment]
Freetype is only available on Linux so this wouldn't be xplat. You can still use Freetype in combination with HarfBuzzSharp. You can load a face with https://github.com/mono/SkiaSharp/blob/master/binding/HarfBuzzSharp.Shared/Face.cs#L35 and construct a font. Just implement the needed interop code to get the required tables from freetype.

**Comment by warappa** [comment]
@Gillibald Thanks for the fast response!
I struggled using this constructor - is there any sample/further documentation about this?

Overload: 👍

**Comment by Gillibald** [comment]
This is the Skia version: https://github.com/AvaloniaUI/Avalonia/blob/master/src/Skia/Avalonia.Skia/GlyphTypefaceImpl.cs#L21

**Comment by warappa** [comment]
This looks promising, thank you!

**Comment by warappa** [comment]
@Gillibald I fiddled around with it and ... failed, because the font I'm using **doesn't provide _any_ sfnt data** for sfnt tags.
As far as I understand my code would have to "calculate" the various sfnt tables and provide it via the GetTableDelegate, but that ... overwhelmed me.

For testing purpose I replaced `libHarfBuzzSharp.dll` with the version from [SharpFont.Dependencies](https://www.nuget.org/packages/SharpFont.Dependencies/) (FreeType support enabled) and defining **my own** `DllImport` statement - and **it worked**!

### For your Reconsideration
Even if FreeType is not xplat, as in my case there is a benefit of providing the **HarfBuzz's actually _built-in_ functions** for users like me relying on FreeType to read fonts _not supported_ by SkiaSharp's SKTypeFace.
There doesn't have to be any C# bindings for `hb_ft_*`, and therefore it would still mean **no 'official' support** for FreeType integration, just the chance for users with advanced use cases.

**Comment by Gillibald** [comment]
Just implement this in C# https://github.com/harfbuzz/harfbuzz/blob/master/src/hb-ft.cc

**Comment by Gillibald** [comment]
It is totally normal that a font is missing some tables

**Comment by warappa** [comment]
I'm sorry but after a few hours I'm stuck - at an very early stage. I don't think I'm able to convert this C code to C# as C's and C#'s memory- and data-management and -access paradigms are too far apart for my skills to translate.

I will try to solve my problem in another way.

But thanks for your support Gillibald!

**Comment by Gillibald** [comment]
I will have a look at this in the near future
