### ISSUE TITLE
Instead of SKPoint, can't we use Vector2 everywhere?

### ISSUE THREAD

**Issue by MuziburRahman** [mono/SkiaSharp#1072]
`System.Numerics.Vector2` is .NetStandard struct and is super usable. It has all the functionality of `SKPoint` plus a lot of cool functionality. Why invent a new struct if `Vector2` is already available?

**Comment by mattleibow** [comment]
SKPoint was around for a very only time, before Vector2. Changing that will break everything.

What we can do is pull in all the features from Vector2 and add it to SKPoint and SKPoint3. Or, for later versions of .NET (or if the nuget works) add some implicit conversions between the two.

**Comment by MuziburRahman** [comment]
Other .NetStandard libraries have `Vector2`, while SkiaSharp uses SKPoint.
It's annoying to convert it Vector 2 and vice versa every time.
