### ISSUE TITLE
[FEATURE] Split the SkiaSharp package into separate NativeAssets packages

### ISSUE THREAD

**Issue by mattleibow** [mono/SkiaSharp#1073]
**Is your feature request related to a problem? Please describe.**
The download and install of SkiaSharp is potentially an issue with about 100MB of native files to pull down.

**Describe the solution you'd like**
The installation of SkiaSharp should only pull down the native assets that are actually required. If I install a package into Xamarin.iOS, don't pull down macOS, UWP, Android, and all the rest. 8MB is better than 100MB

**Comment by mattleibow** [comment]
I have been thinking about this and was all ready to go with some work, but then it occurred to me... Is this really worth it?

Pros:
 - smaller NuGet package
 - faster download

Cons:
 - extra work / maintenance
 - more packages
 - potential for mismatched package versions
 - potential for duplicated assets (macOS is both used on netcoreapp and xamarinmac)

Size is just a download number and has no relevance to the final app, or any relevance at all.

Any opinions?

**Comment by acuntex** [comment]
The big Nuget Package might be a problem.

But normally this nuget package gets loaded on a developer machine with internet access and is cached.

I would rather put energy in somehow reducing the size of the native libraries (e.g. libSkiaSharp.so). libSkiaSharp.so on Android is 6.6MB which is very much on a mobile device.

If only a small feature is used, you still have to include the whole library.

**Comment by mattleibow** [comment]
Finally reached a point where the package got too big to be viable. Now we got smaller packages with SkiaSharp at <5MB (mostly xml docs) and <15MB for each asset package. UWP is a bit bigger at 18MB because it has ANGLE adn watchOS has bitcode which is pretty huge at 25MB
