### ISSUE TITLE
missing method SKImage.CreateFromBitmap(SKBitmap b)

### ISSUE THREAD

**Issue by gentledepp** [mono/SkiaSharp#108]
Hi!

I am trying to store SKBitmaps that I created with SkiaSharp as PNG files.

Miguel pointed out that:

> If you have an SKBitmap, you can call:
> 
> var data = bitmap.Encode (SKImageEncodeFormat.Png, quality: 100);
> using (var f = File.Create ("foo.png"))
>    data.SaveTo (f);

However, SKBitmap has no such "Encode" method.
Only SKImage has.

So I need this method either in SKBitmap, or a conversion method as the one that exists in Skia:

` static sk_sp<SkImage> MakeFromBitmap(const SkBitmap&);`

see SKImage.h
https://github.com/google/skia/blob/master/include/core/SkImage.h 

I tried to do the conversion in C# code, but failed miserably - you can see a documentation of my attempts in this closed issue:
https://github.com/mono/SkiaSharp/issues/103

**Comment by migueldeicaza** [comment]
You are correct, my bad.

This code is from a newer version of Skia, so we need to wait for the Skia upgrade for adding this.   Or alternatively, we can add the method with the current API, and then upgrade the API.

**Comment by migueldeicaza** [comment]
Added an implementation.

**Comment by gentledepp** [comment]
@migueldeicaza  - I am sorry for bothering you, but I cannot find your "implementation" :-|
Is it in the master branch?

**Comment by gentledepp** [comment]
ah.... now I see.
Seems you forgot to add the C# code to SKImage in the binding projects
