### ISSUE TITLE
[QUESTION] why nuget shows skiasharp size is 87.51 mb?

### ISSUE THREAD

**Issue by EmilAlipiev** [mono/SkiaSharp#1081]
https://www.nuget.org/packages/SkiaSharp/
it shows here size of the package is 87.51 mb? where is this coming from?

**Comment by mattleibow** [comment]
That, my fine friend is the sheer power of .NET demonstrated! SkiaSharp is about 4-6MB, but if you have enough platforms it reaches that big number.
 - Android (x4)
 - iOS (x4)
 - macOS (x1)
 - Windows (x2)
 - UWP (x4)
 - tvOS (x2)
 - watchOS (x2)
 - Tizen (x2)

And that is just in the MAIN package - we have additional packages for 2 Linux versions and Nano Server!

We build for and support all those platforms.

The big package is a bit of a pain, so we are thinking of splitting the package (transparently) in #1073

**Comment by EmilAlipiev** [comment]
This sounds cool. I love to use skiasharp and now trying to integrate in tizen wearable apps using xamarin.forms. I was concerned about size issue. because on phones it is acceptable any big megabytes but on watches it should be as small as possible :)
