### ISSUE TITLE
[FEATURE] SKCanvas.DrawText support Span<byte>/Memory<byte>

### ISSUE THREAD

**Issue by JaggerJo** [mono/SkiaSharp#1084]
**Is your feature request related to a problem? Please describe.**
Performance improvement. Drawing a line of a document would allocate (because a sub array/string is needed).

This can be avoided by passing `Span<byte/char>` or `Memory<byte/char>`.

**Describe the solution you'd like**
add overloads for Span and Memory where appropriate.

**Describe alternatives you've considered**
using the TextBlobBuilder seems to be a lot more complicated. If there is a better way to do what I want please let me know. 

**Additional context**
I'm trying to build a simple text editor control that utilises Skia as a rendering backend.

**Comment by JaggerJo** [comment]
https://github.com/mono/SkiaSharp/blob/247569e0954bb8dfb078ed180cf7b8d7cfe702bf/binding/Binding/SKCanvas.cs#L512

**Comment by JaggerJo** [comment]
https://github.com/mono/SkiaSharp/pull/865

**Comment by Gillibald** [comment]
You should use SKTextBlob to draw your text and that already has what you want.

**Comment by JaggerJo** [comment]
Wow, that was quick 😄. Thanks for the link!

**Comment by Gillibald** [comment]
Here I am drawing the filled blob 
 https://github.com/AvaloniaUI/Avalonia/blob/master/src/Skia/Avalonia.Skia/DrawingContextImpl.cs#L236

**Comment by Gillibald** [comment]
Just let me know if you need more assistance 👍

**Comment by JaggerJo** [comment]
Thanks! It's a lot more complicated than I thought.

**Comment by Gillibald** [comment]
The thing is for Latin text text editing and rendering is trivial. Anything else requires a lot of work.

**Comment by mattleibow** [comment]
I just started using https://github.com/toptensoftware/RichTextKit

![](https://raw.githubusercontent.com/toptensoftware/RichTextKit/master/docsrc/sandbox%402x.png)

**Comment by JaggerJo** [comment]
@mattleibow Have you used it on Mac/Linux ?

Cloned it a few day ago and noticed it uses WinForms to host Skia, but it should be super simple to use Avalonia instead I think.

Avalonia uses the same Line Break detection I think.

https://github.com/Gillibald/Avalonia/blob/6b50a41e6af2605a73ad57e72d71a370008b16d3/src/Avalonia.Visuals/Media/Text/Unicode/LineBreaker.cs

**Comment by Gillibald** [comment]
I think my approach will be more pluggable and is xplat as well. My next refactoring will introduce some line services that can be used to build your own text layout. So in the end it will be possible to produce lines on demand. This is an requirement for large documents.
