### ISSUE TITLE
How to Edit Polygon (bitmap) on top of a Google Map but still allow to move the map with swipe gestures?

### ISSUE THREAD

**Issue by AlonRom** [mono/SkiaSharp#1085]
Hi,

I want to use this library in a Xamarin.Forms project.
I'm trying to put a bit map in a polygon shape (like your example: Show Non-Affine Matrix)
but this way I'm losing the swipe gestures on the map itself.
Is it possible to achieve both (maybe with absolut layout somehow)?
+ When a release the finger when finished to move one of the vertices, is there a way to convert the screen location to a longitude, latitude coordinate?

**Comment by mattleibow** [comment]
I am not too sure about the maps. I would ask on the Xamarin.Forms repo. I also think they have/should have the ability to make the pins / polygons on the actual map using the map framework. The effort to draw polygons over a map is not going to be worth it - also there will always be some lag and offsets. Most mapping controls have the ability to do fairly complex things.
