### ISSUE TITLE
[FEATURE] Add missing SKRegion features

### ISSUE THREAD

**Issue by N-Olbert** [mono/SkiaSharp#1088]
**Is your feature request related to a problem? Please describe.**
Compared to the original Skia SKRegion, SkiaSharps implementation is very basic and lots of methods are missing (Compare to https://skia.org/user/api/SkRegion_Reference).

Most of the missing Methods are very easy to implement (f. e. translate(int, int), quickReject(SKRect), …), but I think it would be nice if they are available by default.
Most notable should be the absence of support for multiple rects within a SKRegion (skia calls this "complex" mode). For example the "setRects"-Method is missing.

**Describe the solution you'd like**
Add missing Methods to SKRect to match functionality of original skia.

**Describe alternatives you've considered**
As I said, most things are easy and can be hotfixed in managed code by using extensions. An exception is the complex mode which I think is very hard to handle right outside of Skia.

**Comment by mattleibow** [comment]
Work has been done, features been added, previews published. Check out the brand new preview (1.68.2-preview.29) that just left the gates! https://github.com/mono/SkiaSharp/releases/tag/v1.68.2-preview.29

**Comment by N-Olbert** [comment]
@mattleibow I was able to test it today. The methods i use work as expected :). Thank you very much.

**Comment by mattleibow** [comment]
Thanks for the feedback!
