### ISSUE TITLE
[BUG] Assigning Bitmap.Pixels changes pixel value

### ISSUE THREAD

**Issue by N-Olbert** [mono/SkiaSharp#1092]
**Description**

See attachted unit test: If a assign an array of SKColors to the SKBitmaps "Pixel"-Property the values arent the values I assigned.

**Code**
```

        [TestMethod]
        public void TestBitmapCreation()
        {
            using (var bitmap = new SKBitmap(1, 1, SKColorType.Bgra8888, SKAlphaType.Unpremul))
            {
                var newPixels = new SKColor[] {new SKColor(208, 208, 129, 13)};
                bitmap.Pixels = newPixels;
                Assert.AreEqual(bitmap.Pixels[0], newPixels[0]);
            }
        }
```

Output: Assert.AreEqual failed. Expected:<#0dd8d889>. Actual:<#0dd0d081>.

**Expected Behavior**

Assigned values should not be modified.

**Basic Information**

- Version with issue:  1.68.1.
- Last known good version:  ?
- IDE:  Visual Studio 2017 Professional
- Platform Target Frameworks: 
  -  I could reproduce it as a unit test, so it should be plattform indepentent (Originally observed in WPF and UWP).

**Comment by mattleibow** [comment]
Just having a look at the snippet here, it might be because the alpha type is unpremultiplied. SKColor is premultiplied. It most likely some bug that is not converting and all that, but switching to Premul should fix this.

I'll investigate this, and see exactly what is and should be happening.

**Comment by N-Olbert** [comment]
@mattleibow Changing to Premul does not change the behaviour for me.

This is actually a bit weired. It's not that way for all colors. In fact it works as expected for most of the colors, and only a few - like the one i picked for this bug report - are changed when assigned.

**Comment by mattleibow** [comment]
That is interesting. Thanks for this. I'll try a few things and see what's up.

**Comment by Gillibald** [comment]
https://skia.org/user/api/SkBitmap_Reference#SkBitmap_getColor

This always returns a unpremultiplied color and potentially loses some information in the conversion. So I guess slightly different results are expected.

**Comment by N-Olbert** [comment]
Thanks @Gillibald, this seems to be the explanation. I only looked up Microsoft's documentation, where this behaviour isn't mentioned (at least not for the "Pixels"-Property, for GetPixel it is in fact mentioned vaguely).

I just came across this when trying to verify the image creation process with unit tests.
If anyone else dicovers this: If the pixels where actually installed to the bitmap, you can use the Bytes-Property, which, in this case, contains unmodified values.
Sample:

```
            using (var bitmap = new SKBitmap(1, 1, SKColorType.Bgra8888, SKAlphaType.Premul))
            {
                var newPixels = new[] {(uint)new SKColor(208, 208, 129, 13)};
                var h = GCHandle.Alloc(newPixels, GCHandleType.Pinned);
                bitmap.InstallPixels(bitmap.Info, h.AddrOfPinnedObject(), bitmap.RowBytes, delegate { h.Free(); }, null);

                Assert.AreNotEqual(bitmap.Pixels[0], newPixels[0]); //Still a missmatch
                CollectionAssert.AreEqual(new byte[] {129, 208, 208, 13}, bitmap.Bytes); //This works
            }
```

@mattleibow Should I close this or do you still want to investigate something on this?

**Comment by mattleibow** [comment]
Let's just leave it open for now. This will be the starting point for any docs hat need updating or anything along those lines.

**Comment by mattleibow** [comment]
Just an FYI, this can also be demonstrated by converting from/to `SKColor` and `SKPMColor`:

```csharp
var a = new SKColor(208, 208, 129, 13);
var b = (SKPMColor)a;
var c = (SKColor)b;

// expected: a == c
// actual: a != c
```

I believe this is purely do to loss of information, but I will have a closer look.

**Comment by mattleibow** [comment]
Closing this as there is nothing we can do. This is just due to the way premultiplication works, and, well, division.

Unpremultipled: A: 127, R: 255, G: 0, B: 0
Premultiplied: A: 127, R: 127, G: 0, B: 0

Calculations:
```
PM = (byte)(UPM * Alpha / 255)
UPM = (byte)(PM * 255 / Alpha)
```

EG:
```
RED: 208 😊

PM = (byte)(208 * 13 / 255)
   = (byte)(10.60392156862745)
   = 10
UPM = (byte)(10 * 255 / 13)
    = (byte)(196.1538461538462)
    = 196

RED: 196 😢
```
