### ISSUE TITLE
[BUG] SKPaint.GetGlyphWidths returns wrong size array

### ISSUE THREAD

**Issue by N-Olbert** [mono/SkiaSharp#1093]
**Description**

According to https://docs.microsoft.com/en-us/dotnet/api/skiasharp.skpaint.getglyphwidths?view=skiasharp-1.68.1 the return value of SKPaint.GetGlyphWidths is equal to the length of the input string

> Returns
Single[]
Returns the text advances **for each glyph**

In the given code sample this is not true, input string length and result length missmatch.
Also this seems to be a real bug, because if each char of the string is performed separately GetGlyphWidths works as expected.

**Code**

```
        [TestMethod]
        public void TestGlyphWidths()
        {
            //All ISO 10646 chars 
            const int maxChar = (char)65534;
            var builder = new StringBuilder(maxChar);
            for (var c = (char)0; c <= maxChar; c++)
            {
                builder.Append(c);
            }

            var s = builder.ToString();
            using (var newPaint = new SKPaint())
            {
                var glyphWidths = newPaint.GetGlyphWidths(s);

                //Assert below already fails: Assert.AreEqual failed. Expected:<65535>. Actual:<65534>. 
                Assert.AreEqual(s.Length, glyphWidths.Length);
            }

            //But the following works:
            foreach (var c in s)
            {
                using (var newPaint = new SKPaint())
                {
                    var glyphWidths = newPaint.GetGlyphWidths(c.ToString());
                    Assert.AreEqual(1, glyphWidths.Length);
                }
            }
        }
```
**Basic Information**

- Version with issue: 1.68.1.1
- Last known good version:  ?
- IDE:  Visual Studio 2017
- Platform Target Frameworks: 
I could reproduce it as a unit test, so it should be plattform indepentent (Originally observed in WPF and UWP).

**Comment by mattleibow** [comment]
Thanks for reporting this. I'll investigate.

**Comment by mattleibow** [comment]
So, I had a look at this and I believe I have figured out what is happening.

You might be confusing C# characters with Unicode glyphs. For example, this is a single glyph `􏰀`, but in actual fact, it is made up of **2** C# characters: `0xdbff` and `0xdc00`. Both of these characters are actually not real characters, but parts of a [surrogate pair](https://unicodebook.readthedocs.io/unicode_encodings.html#utf-16-surrogate-pairs). As a result, they are actually rendered as a **single** glyph.

So, if you take this string `�􏰀��`, it is 5 C# characters, but 4 glyphs. This is why you are "missing" some widths, as two are actually a single one.

> If you are trying to render text, this library is pretty good: [RichTextKit](https://github.com/toptensoftware/RichTextKit). It is still under development, but is working and has many, many more features. Some folks from AvaloniaUI are [working with parts of this library](https://github.com/AvaloniaUI/Avalonia/pull/3438) and are busy making performance improvements.
