### ISSUE TITLE
[BUG] RasterImage has no Pixmap

### ISSUE THREAD

**Issue by gregsn** [mono/SkiaSharp#1097]
**Description**

In version 1.68.1.1 PeekPixels() returns `null` on raster-images.

**Code**

            using (var image = SKImage.FromEncodedData(path))
            using (var rasterImage = image.ToRasterImage())
            {
                Debug.Assert(rasterImage.PeekPixels() != null);
            }
**Expected Behavior**

`image.ToRasterImage()` should return a raster image.
` PeekPixels()` should then return the pixmap of the raster-based image.

**Actual Behavior**

` PeekPixels()` returns null as if the image returned by ` image.ToRasterImage()` wouldn't be raster-based.

**Basic Information**

- Version with issue:  1.68.1.1
- IDE: Visual Studio
- Platform Target Frameworks: 
  - Windows Classic:  Windows 10

**Reproduction Link**
[PeekPixels.zip](https://github.com/mono/SkiaSharp/files/4048258/PeekPixels.zip)

**Comment by mattleibow** [comment]
So, I had a look at this and this is sort of working as expected, kinda.

`SKImage.FromEncodedData` technically creates a raster image, but a "lazy" raster. You can check this using the `IsLazyGenerated` property. So, when you do `ToRasterImage`, you are actually just getting the same image.

Now, how do we do what you want to do? Basically, copy the image to a new image:

```csharp
// original
var image = SKImage.FromEncodedData(path);

// create a new image
using var copy = SKImage.Create(new SKImageInfo(image.Width, image.Height));
using var pix = copy.PeekPixels();

// copy the image
image.ReadPixels(pix, 0, 0);
```

This _will work_. But it is code - and we are developers. Developers are known to hate code (it contains bugs). So I just exposed a new overload that does all this for you in #1126:

```csharp
using var image = SKImage.FromEncodedData(path);
using var rasterImage = image.ToRasterImage(preserveLazy: false);
```
