### ISSUE TITLE
New SKTypeface from an existing one but with different style settings

### ISSUE THREAD

**Issue by neodynamic** [mono/SkiaSharp#1100]
Using an old version of SkiaSharp v1.60 here... I want to create a new SKTypeface from an existing one but with a different Style. The code `SKTypeface.FromTypeface` worked just fine in Windows but sadly, it fails on macOS and Linux. Analyzing the new version of SkiaSharp, I see that method is now also obsolete. The only way I can see to create a new SKTypeface with a new style from an existing one is through the `SKTypeface.FromFamilyName` but the problem here is that the SKTypeface we want to "copy" with a new Style is loaded through `SKTypeface.FromStream` instead

So, is there any way to create a new SKTypeface from an existing one with a different style?

Thanks in advance

**Comment by mattleibow** [comment]
Would the `SKFontManager.MatchTypeface` be what you are looking for:
https://docs.microsoft.com//dotnet/api/skiasharp.skfontmanager.matchtypeface

Usage:

```csharp
SKTypeface tf = ...
SKFontStyle style = ...
var newTypeface = SKFontManager.Default.MatchTypeface(tf, style);
```
