### ISSUE TITLE
Is there an “inset” alignment for a SkiaSharp stroke?

### ISSUE THREAD

**Issue by Drise13** [mono/SkiaSharp#1107]
When using GDI I was able to set the Pen::Alignment to Inset, which drew the stroke on the inside of the path. Does SkiaSharp have a similar concept? I've scoured all the SKPaint documentation and haven't found what I'm looking for.

**Comment by mattleibow** [comment]
Unfortunately, I do not believe there is.
You could ask on the actual engine forums and they may give more info as to why or any workarounds:
https://groups.google.com/forum/#!forum/skia-discuss

**Comment by BigBadaboom** [comment]
It's easy enough to reproduce the effect.  Stroke the path using double the desired stroke width, but mask it with a filled version of the path.

**Comment by mattleibow** [comment]
Yeah @BigBadaboom is right. And they also said this on the other side: https://groups.google.com/forum/#!topic/skia-discuss/fE7qzKejMng

**Comment by Drise13** [comment]
I ended up drawing two rectangles of opposing colors (my purpose is only monochrome images) with the second rectangle inset X pixels.
