### ISSUE TITLE
Add .Net Core support (.Net Standard target)

### ISSUE THREAD

**Issue by arkadiuszwojcik** [mono/SkiaSharp#111]
Would be nice to port this package to .Net Standard so it could be reusable across .Net Framework, .Net Core and Mono. I guess the main difficulty here is to deal with native libraries for so many platforms (do all .Net core targets have to be supported ?). Any thoughts on this ?

**Comment by migueldeicaza** [comment]
You correctly identified the problem.

We have talked about it, but have not officially requested the feature, I have now done so:

https://github.com/NuGet/Home/issues/3114

Once that is done, we will add the missing support for these platforms across the board (not only SkiaSharp)

**Comment by mattleibow** [comment]
This is now available with .NET Standard 1.3 support and .NET Core support on `osx`, `win7` and `win10`
