### ISSUE TITLE
Can I use C API directly?

### ISSUE THREAD

**Issue by Reon90** [mono/SkiaSharp#1110]
I ask, because I can't find function prototypes in libskia.so which are defined in include/c/*.h

**Comment by mattleibow** [comment]
You can, but the C APIs are not in libskia but in libSkiaSharp. libskia is an intermediate library file that is then linked with the C bits to create a smaller libSkiaSharp library.

Did you build the libskia from somewhere? Or are you just trying to use the one that comes with SkiaSharp?

**Comment by Reon90** [comment]
I built one on my machine. I also try libSkiaSharp, but there are only few functions. A lot of functions are lost.

**Comment by mattleibow** [comment]
If you build the libskia, it just contains all the C++ members. The libSkiaSharp is specifically meant to link out all but the required pieces used by SkiaSharp. If you build skia using the build scripts in the SkiaSharp repo, you should be getting all the required bits. Did you build the bits from the mono fork of skia? What did you actually build?

**Comment by Reon90** [comment]
@mattleibow I built libs from the mono fork of skia. Is it not ok?

**Comment by Reon90** [comment]
I have built SkiaSharp repo and got correct C API. thank you.
