### ISSUE TITLE
[QUESTION] SVG Export

### ISSUE THREAD

**Issue by juanp3053** [mono/SkiaSharp#1111]
Hello,

I have been reading the documentation on SkiaSharp and I have seen a lot of information on how to read an SVG file and render it to the canvas but I haven't been able to find concrete information about saving/exporting a rendered image (or canvas) to an SVG file. Is this functionality supported or is there any plans to be supported in the future?

Thanks a lot for the help in advance,

**Comment by mattleibow** [comment]
Right now there is experimental support for this with `SKSvgCanvas`:
https://docs.microsoft.com/dotnet/api/skiasharp.sksvgcanvas.create

You can have a try with that and see if covers your needs.

**Comment by juanp3053** [comment]
Thank you @mattleibow for the info. I believe it is exactly what I was looking for.
