### ISSUE TITLE
[BUG] Weird error when i try to instantiate a SKBitmap

### ISSUE THREAD

**Issue by weierstrass1** [mono/SkiaSharp#1112]
**Description**

When i instantiate a SKBitmap send me this error: 

System.TypeInitializationException: 'Se produjo una excepción en el inicializador de tipo de 'SkiaSharp.SKImageInfo'.'

BadImageFormatException: Se ha intentado cargar un programa con un formato incorrecto. (Excepción de HRESULT: 0x8007000B)

**Code**

![image](https://user-images.githubusercontent.com/5378163/72958143-fa261a80-3d84-11ea-8b10-c0a68b56078f.png)

width and height are 256.

**Basic Information**

I am using Eto.forms on Windows.
IDE Visual Studio Community 2019 16.5 Preview
netstandar2.0
SkiaSharp 1.68.0

![image](https://user-images.githubusercontent.com/5378163/72958225-4bcea500-3d85-11ea-80bd-4ebeb130e97e.png)

**Comment by mattleibow** [comment]
Ah, the `BadImageFormatException` typically means you are building for x64 and somehow got the x86 version of libSkliaSharp.dll. Or, vice versa.

Maybe try installing the SkiaSharp NuGet into the WPF app? This may be related to #1057 or #1041.

**Comment by mattleibow** [comment]
Closing this as this should be fixed.

If this is still an problem, please open another issue. It might be helpful to provide a minimal sample.
