### ISSUE TITLE
[FEATURE] Add SKShader.CreateColor() with SKColor and SKColorSpace parameters

### ISSUE THREAD

**Issue by wieslawsoltes** [mono/SkiaSharp#1115]
**Is your feature request related to a problem? Please describe.**

I need to draw colors in `linear RGBA color space` using `SKShader`.

The  `SKShader.CreateColor` method only has color parameter. Skia has another method with additional parameter `color space`.
```C++
static sk_sp<SkShader> SkShader::MakeColorShader(const SkColor4f&, sk_sp<SkColorSpace>)	
```
https://skia-doc.commondatastorage.googleapis.com/doxygen/doxygen/html/classSkShader.html#afd992112ce7187bf67c22a16fa337c33

**Describe the solution you'd like**

Add new API for SKShader:
```C#
public static SkiaSharp.SKShader CreateColor (SkiaSharp.SKColor color, SKColorSpace colorSpace);
```

**Comment by wieslawsoltes** [comment]
Also gradient shaders take `SKColorSpace` as additional parameter. So adding those API's is also requested.

https://skia-doc.commondatastorage.googleapis.com/doxygen/doxygen/html/classSkGradientShader.html

```C++
static sk_sp< SkShader > 	MakeLinear (const SkPoint pts[2], const SkColor4f colors[], sk_sp< SkColorSpace > colorSpace, const SkScalar pos[], int count, SkShader::TileMode mode, uint32_t flags, const SkMatrix *localMatrix)

static sk_sp< SkShader > 	MakeLinear (const SkPoint pts[2], const SkColor4f colors[], sk_sp< SkColorSpace > colorSpace, const SkScalar pos[], int count, SkShader::TileMode mode)

static sk_sp< SkShader > 	MakeRadial (const SkPoint &center, SkScalar radius, const SkColor4f colors[], sk_sp< SkColorSpace > colorSpace, const SkScalar pos[], int count, SkShader::TileMode mode, uint32_t flags, const SkMatrix *localMatrix)

static sk_sp< SkShader > 	MakeRadial (const SkPoint &center, SkScalar radius, const SkColor4f colors[], sk_sp< SkColorSpace > colorSpace, const SkScalar pos[], int count, SkShader::TileMode mode)

static sk_sp< SkShader > 	MakeTwoPointConical (const SkPoint &start, SkScalar startRadius, const SkPoint &end, SkScalar endRadius, const SkColor4f colors[], sk_sp< SkColorSpace > colorSpace, const SkScalar pos[], int count, SkShader::TileMode mode, uint32_t flags, const SkMatrix *localMatrix)

static sk_sp< SkShader > 	MakeTwoPointConical (const SkPoint &start, SkScalar startRadius, const SkPoint &end, SkScalar endRadius, const SkColor4f colors[], sk_sp< SkColorSpace > colorSpace, const SkScalar pos[], int count, SkShader::TileMode mode)

static sk_sp< SkShader > 	MakeSweep (SkScalar cx, SkScalar cy, const SkColor4f colors[], sk_sp< SkColorSpace > colorSpace, const SkScalar pos[], int count, uint32_t flags, const SkMatrix *localMatrix)

static sk_sp< SkShader > 	MakeSweep (SkScalar cx, SkScalar cy, const SkColor4f colors[], sk_sp< SkColorSpace > colorSpace, const SkScalar pos[], int count)
```

**Comment by mattleibow** [comment]
I can do that :)

**Comment by wieslawsoltes** [comment]
This API proposal comes from this article [Best Practices for Color Correct Skia](https://skia.org/user/sample/color?cl=9919).

**Comment by mattleibow** [comment]
So PR #1116 adds all the cases where `SKColorF` is used - which just seems to be `SKShader` and the `Erase` method of `SKPixmap`.

**Comment by wieslawsoltes** [comment]
@mattleibow Great! I will try to test changes if that possible.

**Comment by mattleibow** [comment]
Just merged the things and I will get a release out ASAP.

**Comment by wieslawsoltes** [comment]
> Just merged the things and I will get a release out ASAP.

That was quick. Thanks!

**Comment by mattleibow** [comment]
Work has been done, features been added, previews published. Check out the brand new preview (1.68.2-preview.29) that just left the gates! https://github.com/mono/SkiaSharp/releases/tag/v1.68.2-preview.29

**Comment by wieslawsoltes** [comment]
Now I need to figure out how to do `Color Correct Skia`, I am experimenting with `1.68.2-preview.29` but getting correct `SKColorSpace` to work and achieving  `Color Correct Skia` is not yet straightforward.

https://skia.org/user/sample/color?cl=9919

**Comment by wieslawsoltes** [comment]
And now I discovered this (actually read again the doc):

SkShaders (also stored on SkPaint) can be used to create more complex colors. Color and gradient shaders typically accept SkColor4f (float colors). **These high precision colors can be in any gamut, but must have a linear transfer function.**
