### ISSUE TITLE
Please expose SkEncoder and derived classes

### ISSUE THREAD

**Issue by Ziriax** [mono/SkiaSharp#1128]
In Skia, we can use the [`SkJpegEncoder`](https://cs.chromium.org/chromium/src/third_party/skia/include/encode/SkJpegEncoder.h) and other `SkEncoder` derived classes to tweak the options of the image encoders.

For example, we need to disable chroma subsampling when exporting high quality JPEGs.

However, these classes are not exposed in SkiaSharp.

Now it seems they are not exposed in the official Skia C API either, so maybe convincing Google to make these part of the C API would be a first step?

Thanks,
Peter

**Comment by Ziriax** [comment]
Ouch, this is already exposed through https://docs.microsoft.com/en-us/dotnet/api/skiasharp.skjpegencoderoptions?view=skiasharp-1.68.1

Closing

**Comment by mattleibow** [comment]
Have fun! Thanks for opening the issue and letting me know you are using this cool library!

**Comment by Ziriax** [comment]
Thanks! I'm actually evaluating SkiaSharp for a customer, a major player in the customized photo product printing business. We will be using SkiaSharp in the cloud (CPU rendering), using a linear colorspace rendering workflow (16-bit float per channel). So far so good!

**Comment by mattleibow** [comment]
That's good to hear! Feel free to open any issues when you find you need a feature or find some problems. I am going to make the the BEST library for all things graphics!
