### ISSUE TITLE
DrawText method should accept a Rect

### ISSUE THREAD

**Issue by gplumb** [mono/SkiaSharp#113]
I'm trying to ween myself off of WPF and have noticed that when rendering text, I can't render to a fixed set of bounds (which I would expect to then wrap the text within those bounds and eventually auto-ellipsis).

Ideally there'd be a MeasureText override that allows bounds to be passed in so that text may be measured in the same way.

**Comment by migueldeicaza** [comment]
This does not seem like something Skia supports, please file that request upstream with Google, and we can bind the API if they make it available.
