### ISSUE TITLE
[QUESTION] How to create content views and layouts?

### ISSUE THREAD

**Issue by MhAllan** [mono/SkiaSharp#1134]
I can't find anything online about this. How to add a canvas on another canvas? so one will be the control and the other will be the layout. Also how can I draw a Xamarin View on a canvas?

**Comment by mattleibow** [comment]
You could use a Grid or AbsoluteLayout.

```xaml
<Grid>
    <Grid>
        <!-- content below -->
    </Grid>
    <SKCanvasView />
    <Grid>
        <!-- content above-->
    </Grid>
</Grid>

**Comment by MhAllan** [comment]
Thank @mattleibow, I was hoping it is possible wihtout using XF.

**Comment by mattleibow** [comment]
@MhAllan, what platform are you targeting? We have views for all platforms - I just assumed you were using Forms. But, this is pretty much the same for all platforms, just put the views above or below the canvas.

**Comment by MhAllan** [comment]
I was thinking of the possibility to ditch Xamarin Forms as their bugs backlog is growing over the years than shrinking. So I thought why can't we make Skia Ui. But there are things we can't make, like an entry, so I need to be able to host entry inside my Skia content/layout views. I was just wondering nothing serious.

**Comment by mattleibow** [comment]
You could try and see what comet is doing. They are actually looking at this https://github.com/Clancey/Comet

But just to let you know, the number of issues on repos is also not an indication of stagnation but just the number of issues op. I know that team is closing/fixing large numbers of issues and adding new features rapidly. They also just got support for new form factors like the dual screen devices.

If you feel they are falling behind or you don't have a feature you need, chat to David https://twitter.com/davidortinau

**Comment by MhAllan** [comment]
Yes the number of issues is not an indicator, but the issues themselves are disappointing. I reported more than 5 issues in 2 weeks in 2020 they are supposed to be solved at the early days of the framework (for example button turn gray when hover on it!! How come this is an issue in 2020?). Thanks for the link of Comet I will definitely check it out.
