### ISSUE TITLE
EncodedOrigin reporting incorrect value

### ISSUE THREAD

**Issue by smillershout** [mono/SkiaSharp#1145]
**Description**

As a result of all pictures captured on iPhone being in the camera's natural landscape orientation, I'm attempting to rotate these images in order to correct the appearence of non-landscape images. In order to do this, I'm evaluating the EncodedOrigin property on an instance of SKCodec which is associated with the image. Based on the result of the EncodedOrigin, for example, if the result is 'BottomRight' or 'RightTop', I'm rotating the image apporpriately to 'correct' the orientation. Oddly, this worked very well on iOS prior to 13.3. Since 13.3 however, the EncodedOrigin is now returning 'Default' for all images regardless of their orientation. 

I was wondering if anybody else had encountered this issue and whether or not there is a resolution?

Thanks,
Sam.

**Code**

`using (var stream = new SKManagedStream(fileStream))`
`using (var codec = SKCodec.Create(stream))`
`{`
`	Console.WriteLine("EncodedOrigin = " + codec.EncodedOrigin);`
`}`

**Expected Behavior**

EncodedOrigin should return correct value based on image orientation on all versions of iOS

**Actual Behavior**

EncodedOrigin is returning 'Default' regardless of image orientation on iOS 13.3 and above

**Basic Information**

- Version with issue:  SkiaSharp 1.68.0 and iOS 13.3.1
- Last known good version:  SkiaSharp 1.68.0 and prior to iOS 13.3 
- IDE:  Visual Studio 8.4
- Platform Target Frameworks: Xcode Version 11.3.1
  - iOS:  13.3.1
  - macOS:  10.15.2
- Target Devices:   iPhone plus device. eg. iPhone 7+ and iPhone 8+

**Comment by mattleibow** [comment]
iOS 13.3.1 has been interesting recently. I think it may be that the camera is leaving things out. Can you take a photo and check to see where the origin is on a laptop? Maybe in photoshop or similar?

**Comment by smillershout** [comment]
Hi @mattleibow, thank you for the response. I will double check this. I figured it might be something that Apple has changed. I will take more pictures and check out the metadata through other means. Never thought of this. I have some other things on today but I will get back ASAP. 

Thanks again,
Sam.

**Comment by TamasRemenyi** [comment]
This [thread](https://github.com/jamesmontemagno/MediaPlugin/issues/760#issuecomment-553359143) may have useful information related to this iOS bug.
https://github.com/jamesmontemagno/MediaPlugin/issues/760#issuecomment-553359143

**Comment by smillershout** [comment]
Hi all, just to confirm that this was indeed related to the Media Plugin. I will close this issue now.

Thanks,
Sam.

**Comment by mattleibow** [comment]
@smillershout thanks for the update
