### ISSUE TITLE
[QUESTION] Is there a way to set the font height in pixels?

### ISSUE THREAD

**Issue by Drise13** [mono/SkiaSharp#1147]
I've been given a picture to recreate and the font height is specified in pixels. Is there a way to set up an SKPaint object to draw text to a pixel height instead of a point height?

**Comment by mattleibow** [comment]
You could use the ratio... formula:

```
points = pixels * 72 / 96
```

where 96 is the pixels per inch on a 100% DPI

**Comment by Ziriax** [comment]
I actually think the API documentation is wrong, at least that's the information I got from the [Skia mailing list](https://groups.google.com/d/msg/skia-discuss/Rk9nkPFBmk0/nBZFHIdlBgAJ)

The `SkPaint.textSize` is actually the height, **in pixels**, that a glyph with height `1 em` would get when rendered on the canvas (length #13 in this image) ![90e9dea4](https://user-images.githubusercontent.com/2389359/74731580-87f00b00-5248-11ea-93c7-0e949a7c8467.gif)

**_The documentation incorrectly states `SkPaint.TextSize` is the height in points._**

To verify this, I made a [test program](https://github.com/smartphoto-group/skia-text-size/blob/master/SkiaTextSize/Program.cs) that uses this [font from the Google Skia repo](https://github.com/google/skia/raw/master/resources/fonts/Em.ttf) that has glyphs designed to have a height of 1 em units.

Here's the output of the program, the `SkPaint.TextSize` is 64 pixels, as is the height of the rectangle.

![output](https://user-images.githubusercontent.com/2389359/74731336-13b56780-5248-11ea-9ca1-902b78456ae2.png)

**Comment by mattleibow** [comment]
Good to know. Is this our docs that are wrong? I was not able to find any references to points with regards to text.

**Comment by Ziriax** [comment]
The pleasure is all mine, SkiaSharp rocks!

Only the Skia docs are wrong it seems, but the SkiaSharp doc is so brief that it is hard to understand the meaning :-)

`Gets or sets the text size` is not that useful for most users I guess? IMHO `size` could refer to width, height, line height, em height, etc...

**Comment by mattleibow** [comment]
Ah, yes. Heh, we need to improve that...

Would you like to open a PR ;)

https://github.com/mono/SkiaSharp-API-docs/blob/57ae4a903e9cba1627d0a7362d359a3d6ede80a9/SkiaSharpAPI/SkiaSharp/SKPaint.xml#L2987

**Comment by Ziriax** [comment]
Sure!

**Comment by mattleibow** [comment]
Fixed the docs.

**Comment by robloo** [comment]
I discovered this issue today and went to the docs wondering if text size used points or pixels. I don't think the docs were updated:

https://docs.microsoft.com/en-us/dotnet/api/skiasharp.skpaint.textsize?view=skiasharp-1.68.2

Additionally, SKFont (where I'm setting this) isn't documented at all.
