### ISSUE TITLE
[BUG] SKTextBlobBuilder.AddHorizontalRun requires SKPaint.TextEncoding to be set to SKTextEncoding.GlyphId

### ISSUE THREAD

**Issue by Ziriax** [mono/SkiaSharp#1151]
**Description**

A similar issues #1094 was reported and closed, but I would like to discuss this again.

Calling `SKTextBlobBuilder.AddHorizontalRun` throws a `NullReferenceException` unless the `SKPaint.TextEncoding` is set to `SKTextEncoding.GlyphId`.

IMO this doesn't make sense, since the text encoding is not needed, as the glyph ids are already known when calling this method?

This is caused by the [following old Skia m68 code](https://github.com/mono/skia/blob/2411fe768b0e3d16a1e59839f65b4d802b74499a/src/core/SkTextBlob.cpp#L631) (that doesn't use `SKFont` yet) in `SKTextBlob.cpp`:

```cpp
void SkTextBlobBuilder::allocInternal(const SkPaint &font,
                                      SkTextBlob::GlyphPositioning positioning,
                                      int count, int textSize, SkPoint offset,
                                      const SkRect* bounds) {
    if (count <= 0 || textSize < 0 || font.getTextEncoding() != SkPaint::kGlyphID_TextEncoding) {
        fCurrentRunBuffer = { nullptr, nullptr, nullptr, nullptr };
        return;
    }
```

The `getTextEncoding` check was [removed by Google in this commit](https://github.com/google/skia/commit/b3f4aac0ba02d13af8fa85a33e856d09ab7855b0), where `SKFont` is used instead. 

I'm not sure if the check is actually required?

Personally the imperative API of setting `TextEncoding` on the `SKPaint` feel errors prone, in the latest version Skia the text encoding has to be passed as an argument, and was removed from `SKFont`. But I guess SkiaSharp wants to maintain backwards compatibility? Maybe a major version bump could use a newer version of Skia, where `SKFont` is used? It seems you are already planning this in #711 ?

**_Maybe a simple patch for now could be to validate the `SKPaint.TextEncoding` and throw an exception? Not ideal, but at least the user wouldn't have to dig into the source code to find why the call crashed 😉_** 

**Code**

```CS
  var glyphIds = paint.GetGlyphs("X");
  var glyphXs = new float[] {0};
  var builder = new SKTextBlobBuilder();
  builder.AddHorizontalRun(paint, 0, glyphIds, glyphXs);
```

**Expected Behavior**

A horizontal text run is added to the builder

**Actual Behavior**

A `NullReferenceException` is thrown

**Basic Information**

- Version with issue:  `1.68.2-preview.29`
- Last known good version:  none
- IDE: any
- Platform Target Frameworks: all
- Target Devices:   all

**Workaround**

```CS
  var glyphIds = paint.GetGlyphs("X");
  var glyphXs = new float[] {0};
  var builder = new SKTextBlobBuilder();
  paint.TextEncoding = SKTextEncoding.GlyphId;
  builder.AddHorizontalRun(paint, 0, glyphIds, glyphXs);
```

**Comment by Gillibald** [comment]
Y checking the TextEncoding on the paint doesn't make sense. Is the paint even used when a buffer is allocated? Probably just an oversight during the transition to SKFont. We might want to remove that check. Also the font parameter itself shouldn't be needed. What am I missing here?

**Comment by mattleibow** [comment]
We can always copy the paint object, and then set the encoding to glyph when allocating.

Let me do that and get a preview out.

**Comment by mattleibow** [comment]
@Ziriax thanks for taking the time to open the issue and collect the info. I have this PR which will make things way easier: https://github.com/mono/SkiaSharp/pull/1152
