### ISSUE TITLE
Can SkSvg display an SVG with custom fonts?

### ISSUE THREAD

**Issue by jameslavery** [mono/SkiaSharp#1154]
We're using SkSvg successfully to display our SVGs, but need to display an SVG which has text with a custom font.

However, SkSvg is not displaying with the correct font - it's using the nearest font it can find.

Is it possible to use SKFontManager to register our custom fonts with SkiaSharp so that SkSvg can access it? Or am I misunderstanding how SKFontManager is meant to work?

**Comment by mattleibow** [comment]
The font manager looks at the fonts that are installed on the device. You can manually load fonts using `SKTypeface`, but there will be no way to tell the parser to use them.

At this point, if you really want to use SKSvg, I would suggest converting the text to paths. 

Another option would be to check out a far better SVG implementation that has many more features: https://github.com/wieslawsoltes/Svg.Skia. @wieslawsoltes has been hard at work on this and probably has support for custom typefaces by now.

**Comment by wieslawsoltes** [comment]
Svg.Skia supports custom fonts via registering custom typeface provider (which can use any font related SkiaSharp option e.g. SKFontManager with custom fonts registered on manually loading fonts from know directories etc.).

https://github.com/wieslawsoltes/Svg.Skia/blob/5c6a32c73837b54b228cbaf048f936af19fa160d/src/Svg.Skia/SvgTextExtensions.cs#L10

https://github.com/wieslawsoltes/Svg.Skia/blob/5c6a32c73837b54b228cbaf048f936af19fa160d/src/Svg.Skia/Text/FontManagerTypefacerovider.cs#L13

**Comment by jameslavery** [comment]
Thanks - I'll look at Svg.Skia.
