### ISSUE TITLE
[BUG] [UWP] Canvas is blank after PopAsync() from Navigation in Forms

### ISSUE THREAD

**Issue by pauldendulk** [mono/SkiaSharp#1155]
**Description**

Canvas is blank after PopAsync() from Navigation in Forms

**Code**

This shows nothing after moving away and back
```csharp
        private void Mv_PaintSurface(object sender, SkiaSharp.Views.Forms.SKPaintGLSurfaceEventArgs e)
        {
            e.Surface.Canvas.DrawRect(100, 100, 500, 500, new SKPaint { Color = SKColors.Pink });
        }
```

**Expected Behavior**

A pink square is shown.

**Actual Behavior**

Screen stays blank.

**Basic Information**

- Version with issue:  
  - ❌ 1.68.2-preview.50
  - ❌ 1.68.2-preview.29
  - ❌ 1.68.1.1 (latest stable)
  - ❌ 1.68.1
  - ✔️ 1.68.0

- IDE:  Visual Studio 
- Platform Target Frameworks: UWP with SKGLView
- UWP: 16299

**Reproduction Link**

Here a sample to reproduce it. Instructions in the readme.
https://github.com/pauldendulk/skiasharp-uwp-blank-screen
Thanks to @spaddlewit for providing the original one submitted for Mapsui.

**Comment by pauldendulk** [comment]
Here is the original Mapsui issue:
https://github.com/Mapsui/Mapsui/issues/838

**Comment by pauldendulk** [comment]
Did some further tests. 
- GRContext is not null (an issue we saw somewhere else).
- IsDisposed is false on Surface and Canvas in all cases.
- Other parameters of Surface and Canvas (like OwnHandle, DeviceClipBounds) seem correct.
- PaintSurface is called after going back. That is not the problem
- If InvalidateSurface() is called seconds later, which triggers a PaintSurface, it is still blank. So it is not a timing issue.

**Comment by pauldendulk** [comment]
@mattleibow We will release a new version of Mapsui using preview 50 later today. Thanks for the fixes! This issue however is not fixed yet. I just updated the minimal repro to preview 50 and it has the same behavior.

@spaddlewit Could you explain a bit more about your use case?

**Comment by spaddlewit** [comment]
The use case is that you tap on something on the map, or press a Button, or perform some other action on the screen that PushAsync()s a new ContentPage in Xamarin.Forms. Then at some point you will go Back to the ContentPage with the Mapsui map on it. This is a very basic operation and likely is used in nearly all apps. Not sure how to explain it further.

**Comment by mattleibow** [comment]
I'll have a look. Maybe the GL context is getting killed under the hood. Thanks for the testing and feedback.

**Comment by mattleibow** [comment]
Awesome news folks. I managed to locate what was happening. It seems with v1.68.1+ the GL context was freed, but not the skia links to them. I'm not quite sure exactly what was happening as I could still access the properties of the old context...

But anyways, I now clean up properly and all seems to be good in https://github.com/mono/SkiaSharp/pull/1213

Thanks to the folks keeping this thread updated and a special thanks to @spaddlewit for getting that nice repro that really helped me get to the bottom of this quickly. @pauldendulk, I'll get a preview out ASAP and update to the mapsui issue as well when it is done.

**Comment by charlenni** [comment]
@mattleibow I assume, that this also solves the problem with the Android device, that screen wents off and than when go on again, the canvas doesn't get updated anymore. Seems for me the same reason.

Problem was described [here](https://github.com/Mapsui/Mapsui/issues/746).

**Comment by charlenni** [comment]
@mattleibow We have this problem in different flavours. One is on iOS, that the canvas doesn't work correct, if you create it with IsVisible and than later set it IsVisible to true. Or when you leave the app and come back (could see this by myself with lower versions of Android but not with newer ones). Or as in this issue. So perhaps all this is solved with your efforts.

**Comment by mattleibow** [comment]
Might not be... The PR was just for UWP.
I'll reopen this issue for now and do some testing on other platforms.

If you have a platform sample or a specific set of instructions to repro then just throw them in here.

**Comment by pauldendulk** [comment]
As far as I know it was only seen on UWP. Maybe my original report was not clear enough, it is when using Forms on UWP. We have way more Android and iOS users than UWP. If the problem was there too we would have heard that.

**Comment by mattleibow** [comment]
Ok, thanks for the confirmation. @charlenni might have been experiencing another issue?

**Comment by charlenni** [comment]
@mattleibow I encountered, that if you leave the app by using the power off switch and come back, then the canvas isn't drawn again until you call a InvalidateSurface by your own. And this looks for me very similar to the above problem. I use a Huawei P8 lite 2017 with Android 8 for tests.

**Comment by mattleibow** [comment]
The Android issue is in #1232
