### ISSUE TITLE
[BUG] macOS Native library libSkiaSharp.dylib is not signed with a Developer ID

### ISSUE THREAD

**Issue by Odirb** [mono/SkiaSharp#1156]
Apple has refused the notarization of my application with an error message "The binary is not signed with a valid Developer ID certificate." on the libSkiaSharp.dylib.

This command line "codesign -dv --verbose=4 libSkiaSharp.dylib" show that the native skia library shipped inside the SkiaSharp nuget is signed with an adoc signature.

The same command executed on a Mono native library indicates "Developer ID Application: Xamarin Inc (7V723M9SQ5)" as code signing authority.

Is it possible to sign macOS native library with a valid Developer ID to pass apple notarization process?
Thanks

**Comment by mattleibow** [comment]
Did you ever resolve this? Sorry for not responding sooner, but when you publish the app, the dylibs are resigned with your ID.

**Comment by Odirb** [comment]
Hello Matthew,
The solution I have fount at the moment is actually to resign the libSkiaSharp.dylib binary, but it would be nice if the nugget have an already signed dylib.

For example, the native library provided by mono framework are already with a Xamarin developper ID:

codesign -dv --verbose=4 libmono-native.dylib

Identifier=libmono-native-unified
Format=Mach-O thin (x86_64)
CodeDirectory v=20500 size=7714 flags=0x10000(runtime) hashes=232+5 location=embedded
VersionPlatform=1
VersionMin=658432
VersionSDK=659200
Hash type=sha256 size=32
CandidateCDHash sha256=f3f1212dbc9b01655d6a203c3a308f07438926af
CandidateCDHashFull sha256=f3f1212dbc9b01655d6a203c3a308f07438926aff4b463048b08e31d687fd395
Hash choices=sha256
CMSDigest=f3f1212dbc9b01655d6a203c3a308f07438926aff4b463048b08e31d687fd395
CMSDigestType=2
Page size=4096
CDHash=f3f1212dbc9b01655d6a203c3a308f07438926af
Signature size=8958
**Authority=Developer ID Application: Xamarin Inc (7V723M9SQ5)
Authority=Developer ID Certification Authority**
Authority=Apple Root CA
Timestamp=26 May 2020 at 23:17:05
Info.plist=not bound
**TeamIdentifier=7V723M9SQ5**
Runtime Version=10.15.0
Sealed Resources=none
Internal requirements count=1 size=184

The command operation with SkiaSharp show an adhoc certificate:

codesign -dv --verbose=4  libSkiaSharp.dylib

Executable=/Users/christophe/.nuget/packages/skiasharp/1.68.3/runtimes/osx/native/libSkiaSharp.dylib
Identifier=libSkiaSharp-555549446aa5c4f305c83fd48e87e5198b514178
Format=Mach-O universal (x86_64)
CodeDirectory v=20100 size=61926 flags=0x2(adhoc) hashes=1930+2 location=embedded
VersionPlatform=1
VersionMin=657152
VersionSDK=659200
Hash type=sha256 size=32
CandidateCDHash sha1=f5145a3e919bbd8736a534993310185fbc9c3b96
CandidateCDHashFull sha1=f5145a3e919bbd8736a534993310185fbc9c3b96
CandidateCDHash sha256=4559234613c1f913ff714e029b47962a7854910e
CandidateCDHashFull sha256=4559234613c1f913ff714e029b47962a7854910e633e46843643bc01b986e8fe
Hash choices=sha1,sha256
CMSDigest=5640e9aab24035e31f8ed0d7becb241a6f5a252d75efc8f831ce89b111ecf56f
CMSDigestType=2
Page size=4096
CDHash=4559234613c1f913ff714e029b47962a7854910e
**Signature=adhoc**
Info.plist=not bound
**TeamIdentifier=not set**
Sealed Resources=none
Internal requirements count=0 size=12

**Comment by MohanaselvamJ** [comment]
I am also facing the similar problem. Any suggestion will be really helpful?

**Comment by rolfbjarne** [comment]
> but it would be nice if the nugget have an already signed dylib

Why does it matter? The dylib will be resigned when building your app.

**Comment by mattleibow** [comment]
I suppose this matters if you are making a console app?

**Comment by mattleibow** [comment]
Building a macOS app will always require codesigning and it should be on by default, but I have now started signing the dylib for macOS: https://github.com/mono/SkiaSharp/pull/2932
