### ISSUE TITLE
[BUG] Could not load file or assembly 'libSkiaSharp' or one of its dependencies. The module was expected to contain an assembly manifest.

### ISSUE THREAD

**Issue by Drise13** [mono/SkiaSharp#1157]
Using SkiaSharp from NuGet, version 1.68.1.1, I was getting a BadImageFormat exception when running my ASP.NET (standard) server, which referenced a PCL using SkiaSharp. I added at one point 

```
  <Target Name="CopyRequiredNativeAssets" AfterTargets="_FunctionsPostPublish">
    <ItemGroup>
      <NativeAssetToCopy Include="$(PublishDir)runtimes\win-x64\native\libSkiaSharp.dll" />
    </ItemGroup>
    <Copy SourceFiles="@(NativeAssetToCopy)" DestinationFolder="$(PublishDir)bin" />
  </Target>
```

which came from another bug report here. I now get this assembly manifest error, and I'm out of ideas and things to search for. In my unit test project, I had no issues loading and using SkiaSharp in the PCL. Everything is set to `AnyCPU`, which I thought was fixed in the targets file.

What am I missing, and is there more I can try to fix this?

**Comment by Drise13** [comment]
I've also tried 
```
 <PropertyGroup>
    <PreferredNativeSkiaSharp>x64</PreferredNativeSkiaSharp>
  </PropertyGroup>
```

**Comment by mattleibow** [comment]
What is the server you are deploying on? It looks to be Azure Functions?

I think you got the code from here? https://github.com/mono/SkiaSharp/issues/1001

From that, I see you are using `x64`. I believe Azure Functions is `x86` - which is resulting in the `BadImageFormatException`.

**Comment by Drise13** [comment]
The server is a typical IIS server run on Windows. Build should be in `x64`.

**Comment by mattleibow** [comment]
It may be that the server is running as x86. The `BadImageFormatException` means that the dll was found, but not correct. Try `x86`.

**Comment by mattleibow** [comment]
Did you manage to resolve this issue?
