### ISSUE TITLE
Is there a way to translate canvas without invalidation of surface ?

### ISSUE THREAD

**Issue by SeRgI1982** [mono/SkiaSharp#1162]
Hi, 

When I press right button and move I do canvas translation.
When I scroll up/down I do canvas scale.

Elements placed on the canvas have fixed position (on the video we have images but it can be any type of shapes (rectangles, circles, lines, paths etc.)).

[sample video](https://drive.google.com/file/d/1C59gB0GyxhJIFsDanSvtncdIY_Irqg7n/view)

Is there a way to translate/scale canvas without invalidating surface ?
Currently, each time when mouse move is handled, the surface is invalidated and I need to re-draw whole elements. Performance suffers according to number of elements on the canvas.

I would be glad for any suggestions how to improve it.

**Comment by mattleibow** [comment]
There are 2 basic things. Either use the GL views, and this looks like a case for that, or use a cache. For example, draw the bits to separate images and then just draw the images. For example, draw the actual image to a cached image, and then just blit it to the screen. Then, all the mouse does is update text, and draw a single image.

**Comment by SeRgI1982** [comment]
Currently, I use a few levels of caching. 
When the image is taken from server it is cached in local storage (I wasn't cached before).

Then, I decode original image and create 3 different copies (quality: High - original size, Medium - half of the original size, Low - quarter of the original size). 

Bits of those image copies are stored in memory cache, so I don't need to decode the image each time when InvalidateSurface is raised. Of course those quality copies are applied according to zoom level. 

Without those operations there was a problem to even open the project. Application hangs for long minutes or goes down.

I will try with SKGLView.

**Comment by mattleibow** [comment]
Did you manage to resolve this?

**Comment by SeRgI1982** [comment]
With SKGLView is far more better but still needs to be investigated by my in a near future. 
There is an option to do a screenshot of a whole canvas and show only this screen but complexity of such solution increase, so I postponed this task

**Comment by mattleibow** [comment]
I am going to close this as the feature of a "dirty rect" is not native to SkiaSharp. However, this is possible to be done in your code - Mapsui uses this to basically render entire maps.
