### ISSUE TITLE
[BUG] Using source bitmap for CreateMerge image filter throws NullReferenceExceptions

### ISSUE THREAD

**Issue by Ziriax** [mono/SkiaSharp#1163]
**Description**

Passing `null` for any filter argument to [`SKImageFilter.CreateMerge`](https://docs.microsoft.com/en-us/dotnet/api/skiasharp.skimagefilter.createmerge?view=skiasharp-1.68.1#SkiaSharp_SKImageFilter_CreateMerge_SkiaSharp_SKImageFilter___SkiaSharp_SKImageFilter_CropRect_) will throw a `NullReferenceException`

The Skia documentation for the [merge image filter](https://api.skia.org/classSkImageFilters.html#ae4968f3a314d892e22b89dd50d24781f) is:

```C++
/**
     *  Create a filter that merges the 'count' filters together by drawing their results in order
     *  with src-over blending.
     *  @param filters  The input filter array to merge, which must have 'count' elements. Any null
     *                  filter pointers will use the source bitmap instead.
     *  @param count    The number of input filters to be merged.
     *  @param cropRect Optional rectangle that crops all input filters and the output.
     */
    static sk_sp<SkImageFilter> Merge(sk_sp<SkImageFilter>* const filters, int count,
                                      const SkIRect* cropRect = nullptr);
```

Note the comment `Any null filter pointers will use the source bitmap instead`.

So it should be allowed to pass `null` for any input filter.

Changing [this line](https://github.com/mono/SkiaSharp/blob/ee0e6682356fa8b27967a9327eda269f6b7a4291/binding/Binding/SKImageFilter.cs#L171) into

```
handles[i] = filters[i]?.Handle ?? IntPtr.Zero;
```

seems to fix this

**Comment by Ziriax** [comment]
Would you like me to make a PR for this? I got approval to spend time on this.

**Comment by mattleibow** [comment]
@Ziriax sorry for the dely. Yes please! Thanks for looking into this already. As soon as there is a PR, I'll merge. 

And for future reference, feel free to open any PRs if you think there is a bug or some issue. We can always close the PR if it turns out that is is a "feature". And, with a PR, we can talk code!

**Comment by mattleibow** [comment]
Merged! Thanks for the PR and tests!
