### ISSUE TITLE
[BUG] Unable to load DLL 'libSkiaSharp' Exception occurs in Azure function while publishing the application through Visual studio 2019 (not occurs in VS2015)

### ISSUE THREAD

**Issue by ManishSync** [mono/SkiaSharp#1165]
**Description**

Unable to load DLL 'libSkiaSharp' Exception occurs in Azure function while publishing the application through Visual studio 2019 (not occurs in VS2015)

**Code**

We have created a .Net core test project referencing the .Net Standard library where the Library has "SkiaSharp" as one of its dependency packages. While running the test project, we are facing the above-mentioned exception

**Expected Behavior**

There should not be an exception

**Actual Behavior**

 Unable to load DLL 'libSkiaSharp' exception occurs

**Basic Information**

- Version with issue:  1.59.3
- Last known good version:  1.59.3
- IDE:  
- Platform Target Frameworks: Windows

**Screenshots**

**Reproduction Link**

**Comment by ManishSync** [comment]
Please find the sample which causes an issue. 
[AzureFunction.zip](https://github.com/mono/SkiaSharp/files/4294570/AzureFunction.zip)

Build and publish the application in the Azure environment through Visual studio 2019.

**Comment by ManishSync** [comment]
Hi Team,

Any update on this?

Regards,
Manish R

**Comment by mattleibow** [comment]
Duplicate of #1001
