### ISSUE TITLE
[BUG] Error Converting SKData

### ISSUE THREAD

**Issue by seoduda** [mono/SkiaSharp#1166]
**Description**
I am using SkiaSharp to generate an image that represent a transaction receipt that can be shared via my Xamarin app.  When I try to convert the SKData to array I get an error message:
{System.MethodAccessException: Method `System.ReadOnlySpan`1[System.Byte]..ctor(void*,int)' is inaccessible from method `SkiaSharp.SKData.AsSpan()'
 The code bellow works fine with the Android version of the app, both not with iOS.

**Code**

        public static byte[] GenerateImage(ImageReceipt imageReceipt)
        {
            FontFamilyName = ImageReceipt.FontFamilyName;
            SKBitmap bitmap = GetReceiptBitmap(imageReceipt);
            using (SKImage image = SKImage.FromBitmap(bitmap))
            using (SKData data = image.Encode(SKEncodedImageFormat.Png, 80))
            {
                return data.ToArray();
            }
        }

*Expected Behavior**

Return the Byte Array 

Exception : {System.MethodAccessException: Method `System.ReadOnlySpan`1[System.Byte]..ctor(void*,int)' is inaccessible from method `SkiaSharp.SKData.AsSpan()'

**Basic Information**

- Version with issue:  1.68.1.1
- Last known good version:  N/A
- IDE:   Visual Studio 
  - Android:8.1
  - iOS:  12.4.0.64

**Comment by mattleibow** [comment]
Sorry for the very late response. Is this still an issue? It may have been related to an incompatibility of the Xamarin/.NET/.NET Standard versions?

**Comment by seoduda** [comment]
Hello there,


This is no longer an issue for me.
Using updated versions and now it works fine.


Thanks for your help!

**Comment by mattleibow** [comment]
Awesome! Glad to hear the updates fixed things.
