### ISSUE TITLE
[BUG]  Random segfaults on Android

### ISSUE THREAD

**Issue by hajmajeboss** [mono/SkiaSharp#1168]
**Description**

I use a mapping library Mapsui, which uses SkiaSharp 1.68.1.1 in my Xamarin.Android app. When zooming in/out or moving around the map, or sometimes even doing nothing, the app crashes. I was able to recover following report from Logcat. 

My app is using AOT compilation.

I was wondering, if you could decode the message using addr2line and find the problem. I'm not entirely sure that it's SkiaSharp error, but I don't know, how to know for sure anyway. I'm using only mono .so libraries besides Skia. 

**Code**

```
03-06 10:45:44.549 10828 11427 F libc    : Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x1130 in tid 11427 (GLThread 25266), pid 10828 (proplamobilenet)

03-06 10:45:44.777 11508 11508 I crash_dump64: obtaining output fd from tombstoned, type: kDebuggerdTombstone
03-06 10:45:44.781  1067  1067 I /system/bin/tombstoned: received crash request for pid 11427
03-06 10:45:44.784 11508 11508 I crash_dump64: performing dump of process 10828 (target tid = 11427)
03-06 10:45:44.807 11508 11508 F DEBUG   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
03-06 10:45:44.808 11508 11508 F DEBUG   : Build fingerprint: 'xiaomi/jasmine/jasmine_sprout:9/PKQ1.180904.001/V10.0.17.0.PDIMIXM:user/release-keys'
03-06 10:45:44.808 11508 11508 F DEBUG   : Revision: '0'
03-06 10:45:44.808 11508 11508 F DEBUG   : ABI: 'arm64'
03-06 10:45:44.808 11508 11508 F DEBUG   : pid: 10828, tid: 11427, name: GLThread 25266  >>> eu.pds.proplamobilenet <<<

signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x1130
x0  0000000000000000  x1  0000000000000001  x2  00000078d1e32d38  x3  00000078d401d678
x4  00000078dbc00000  x5  00000078ce2a2e00  x6  00000078d939b770  x7  00000000038a4ae8
x8  00000000ffffffff  x9  0000000000000001  x10 0000000000000001  x11 00000078e1e70238
x12 0000000000000361  x13 0000000000000001  x14 0000000000000000  x15 00000078efbedd68
x16 00000078ec27d000  x17 000000797c8a7894  x18 00000078d0b21208  x19 0000000000000000
x20 00000078d4638da0  x21 0000000012f81ba8  x22 00000078d9958410  x23 0000000000000000
x24 0000000000000000  x25 0000000000000000  x26 00000078dc400470  x27 0000000000000000
x28 0000000000000000  x29 00000078d939c3b0
sp  00000078d939c380  lr  00000078d08821b4  pc  00000078d1e40a78
```

- Version with issue:  1.68.1.1
- Last known good version:  probably 1.60.3 (but they made a switch from SKCanvas to SKGL recently)
- IDE:   Visual Studio
- Platform Target Frameworks: 
  - Android:  

- Target Devices:  
  - Xiaomi Mi A2

**Comment by hajmajeboss** [comment]
I used addr2line and it found the address is only in libxamarin-debug-app-helper.so. So it's probably not related to SkiaSharp.

**Comment by hajmajeboss** [comment]
Confirmed, it's stable in release config, where the problematic library is not present.

**Comment by mattleibow** [comment]
That is good news (for SkiaSharp at least). Thanks for the update.

**Comment by hajmajeboss** [comment]
Well, this segfault might be related to Skia though - can't find the method with 0x1130 address by addr2line, but I can't find it for any other Skia related error (as there is skia .so library path in the stack trace), I reported it in another thread with another two errors.

**Comment by mattleibow** [comment]
Let me know what you find. I do have another issue that looks suspicious with GL: https://github.com/mono/SkiaSharp/issues/1121

There are a few other "random crashes" that have been occurring as well. I am not sure if this is a bug in the SkiaSharp native memory management, the skia code or just somewhere else. I have been working to get the #986 PR ready for actual use so I can test many of these things with the latest skia. I was hoping for a few releases of things this month, but I keep getting distracted. But, we still have a few weeks left. Maybe a preview this month, I will try to get something going ASAP so we can get rid of the "random" bugs. They are the worst!

**Comment by hajmajeboss** [comment]
What makes it the worst is, that there are times when nothing crashes for half an hour and you start to believe it's stable, only to get 5 crashes in 5 minutes then. That makes it so hard to test. 1.68.0 is probably most stable version, preview39 the least.

**Comment by mattleibow** [comment]
Yeah. The 1.68.0 was the old memory management model, which was actually pretty bad and leaked everything. The v1.68.1+ are the new memory model, which should have been better. I have been looking at a couple of issues, but yeah, the times when you are 30 mins into a test and no issues? That thing you tried must be the fix, then boom, nope. I'm still looking at these and I was hoping to get it resolved this month. But, still a few weeks left for some serious multi-threaded, OpenGL, native debugging! Wee!

**Comment by mattleibow** [comment]
This might be a duplicate of #1121

**Comment by mattleibow** [comment]
I have just published the PR (https://github.com/mono/SkiaSharp/pull/1180) NuGet (**1.68.2-pr.1180.4**) to the preview feed: https://aka.ms/skiasharp-eap/index.json
This contains the fixes for macOS, iOS and Android. More platforms coming soon.

Give that a go and let me know if it fixes the crashes.

**Comment by mattleibow** [comment]
Just pushed all the packages (preview 45) to NuGet.org.

**Comment by mattleibow** [comment]
Hey folks, it has been a long time coming and thanks to all the folks with your repros, samples and stack traces I think we have finally managed to fix those pesky crashes - at least the ones we know about. I have just pushed **1.68.2-preview.50** to NuGet so let me know if this fixes all the crashes you have ever had 😄
