### ISSUE TITLE
System.DllNotFoundException: libskia_osx.dylib

### ISSUE THREAD

**Issue by calder** [mono/SkiaSharp#117]
It looks like the NuGet package of SkiaSharp is failing to copy `libskia_osx.dylib` to Mac applications during the build. To repro:

1. Create a MonoMac (Open Source) Cocoa Project.
2. Add the SkiaSharp Nuget package.
3. Add some code that uses SkiaSharp.
4. Run the application.
5. Application crashes with `System.DllNotFoundException: libskia_osx.dylib`.

After manually copying `SkiaSharp.1.49.1.0/build/net45/mac/libskia_osx.dylib` to `bin/Debug/MyApp.app/Contents/MonoBundle/` the app runs perfectly.

I was able to reproduce in both SkiaSharp.1.49.1.0 and SkiaSharp.1.49.4-beta.

**Comment by migueldeicaza** [comment]
MonoMac is no longer maintained, and this is one of those side effects, it has not caught up with the various developments in the space.

Migrate your application to Xamarin.Mac, which is the evolved version of Xamarin.Mac and is also fully open source now.
