### ISSUE TITLE
Does SKColorType support BGR888 type?

### ISSUE THREAD

**Issue by srasool** [mono/SkiaSharp#1176]
I can only see BGRA888

**Comment by mattleibow** [comment]
Unfortunately not at this point. 

There is a `RGB 888x`, but that is still 32-bit pixels. This is entirely dependent on the underlying skia. All color information is either 8, 16, 32 or 64-bits of information, so I do not see a case of 24-bit colors.

However... If this is some encoded image file that you are trying to load, then it most probably can - just that it will be converted to an opaque BGRA8888 or RGBA8888 (depending on the platform)
