### ISSUE TITLE
[BUG] Gtk sample [Basic\Gtk\SkiaSharpSample] in [Version 1.68.1.1] crashes in Visual Studio 16.5.0

### ISSUE THREAD

**Issue by sergeyDoroshenko** [mono/SkiaSharp#1182]
The GTK sample crashes on the first line of code:

`Application.Init();`

Should it run in VisualStudio on Windows, or only in MonoDevelop on Linux?

**Comment by mattleibow** [comment]
You might not have the GTK# v2 installed. You can download it from https://www.mono-project.com/download/stable (the blue "Download Gtk#" button). Or use this [direct link](https://xamarin.azureedge.net/GTKforWindows/Windows/gtk-sharp-2.12.45.msi)

Also, you can just use the Gtk3 sample and everything is on NuGet and it works nicely with .NET Core.

**Comment by sergeyDoroshenko** [comment]
I have it installed. Other samples I have work well. Gtk3 sample crashes the same way for me. Would any logs be helpful?

**Comment by sergeyDoroshenko** [comment]
I guess I found why it didn't run. 
`    <Prefer32Bit>false</Prefer32Bit>` picks x64 platform, but according to the link you shared (https://www.mono-project.com/download/stable/) GTK# for x64 might be not available for Windows. 

According to the Gtk3 sample: Increasing GtkSharp to 3.22.25.56 in the project settings fixed the problem. Now it runs.

**Comment by mattleibow** [comment]
Closing this as the problems appear to be addressed. Please open a new issue if there are any further issues.
