### ISSUE TITLE
Cannot deploy libSkiaSharp when copy libSkiaSharp from  runtimes\win10-x86\native location in SkiaSharp NuGet package into published folder.

### ISSUE THREAD

**Issue by ManishSync** [mono/SkiaSharp#1184]
**Description**

Cannot deploy libSkiaSharp when copy libSkiaSharp from the runtimes\win10-x86\native location in SkiaSharp NuGet package into the published folder.

**Code**

- Create an asp.net core 2.0 web project (any template).
- Reference a NuGet package that has a native library, in my particular case it was SkiaSharp 1.6.0.
- Create publish profile
- In publish, profile settings change deployment mode to self-contained, and target runtime to win-x86
- Publish the project
- Copy libSkiaSharp from the runtimes\win10-x86\native location in the SkiaSharp NuGet package into the published folder.

**Expected Behavior**

It should works

**Actual Behavior**

Cannot deploy

**Comment by mattleibow** [comment]
Is there an error or exception?

Also, you probably have to use 'runtimes\win-x86\native'

**Comment by mattleibow** [comment]
Did you manage to resolve this?

**Comment by mattleibow** [comment]
Closing this as the correct artifact is the on in `runtimes\win-x86\native` And, when you publish the web app, the files are not in the root, but rather in he runtimes folder that gets copied. The .NET Core runtime system will automatically load the correct architecture depending on the OS and CPU.
