### ISSUE TITLE
[BUG] Passing null to SkPathMeasure results in AccessViolationException

### ISSUE THREAD

**Issue by Ziriax** [mono/SkiaSharp#1187]
**Description**

`var pathMeasure = new SKPathMeasure(null);`

causes `System.AccessViolationException: 'Attempted to read or write protected memory. This is often an indication that other memory is corrupt.`

**Code**

`var pathMeasure = new SKPathMeasure(null);`

**Expected Behavior**

Either an `ArgumentNullException`, or an empty path measure instance.

**Actual Behavior**

`AccessViolationException` is thrown.

**Basic Information**

- Version with issue:  b2ccb97636e7b42ff97413a76efa1b2bd7c729ce (branch `dev/update-skia`)
- Last known good version:  not sure
- IDE: independent
- Platform Target Frameworks:  .NET Standard 2.0

The fix is very simple, it is caused by [this line](https://github.com/mono/SkiaSharp/blob/73bfe5595489ab2b1f3b525712983baefaf58417/binding/Binding/SKPathMeasure.cs#L22), but I'm not sure what the expected behavior is: throw an `ArgumentNullException`, or create an empty path measure? If the latter is allowed, it would make more sense to provide a ctor without args. I'll make a PR once we agree on this 🎉

**Comment by mattleibow** [comment]
I think an exception is good here. If there is no path, then the default constructor can be used.

What do you think?

**Comment by Ziriax** [comment]
I totally agree :+1:

**Comment by mattleibow** [comment]
This is now out on NuGet as **1.68.2-preview.50**
