### ISSUE TITLE
[BUG] Unused SKString instance in SKTextBlobBuilder

### ISSUE THREAD

**Issue by Gillibald** [mono/SkiaSharp#1189]
**Description**

This line is an unnecessary performance hit. We should reuse a dummy instance because we don't use it anyways.

https://github.com/mono/SkiaSharp/blob/master/binding/Binding/SKTextBlob.cs#L265

Also passing a language only makes sense when `TextEncoding != GlyphId`

Creating and destructing this SKString instance takes about 6% of processing time in my current test. So I consider this a major issue.

**Code**

**Expected Behavior**

**Actual Behavior**

**Basic Information**

- Version with issue:  
- Last known good version:  
- IDE:  
- Platform Target Frameworks: 
  - Android:  
  - iOS:  
  - Linux:  
  - macOS:  
  - Tizen:   
  - tvOS:  
  - UWP:   
  - watchOS:  
  - Windows Classic:  
- Target Devices:   
  - 
  - 

**Screenshots**

**Reproduction Link**

**Comment by Gillibald** [comment]
@mattleibow

**Comment by mattleibow** [comment]
Let me get on that for you :)

**Comment by mattleibow** [comment]
Looking at the code, the lang is never actually referenced. And, it is removed in the next version of skia... So I am removing it. That is the power I wield in this project!

**Comment by mattleibow** [comment]
This is now out on NuGet s **1.68.2-preview.50**
