### ISSUE TITLE
[QUESTION] Code does not adhere to editorconfig

### ISSUE THREAD

**Issue by Ziriax** [mono/SkiaSharp#1197]
When making PRs, I noticed that some of the code gets formatted according to the `.editorconfig`  rules, but the original file wasn't. This can cause a lot of merge conflicts.

For example, it seems the following two formatting options in the `.editorconfig` are not followed in the source code:

```cs
		public SKPaint ()
			: this (SkiaApi.sk_compatpaint_new (), true)
		{
			if (Handle == IntPtr.Zero) {
				throw new InvalidOperationException ("Unable to create a new SKPaint instance.");
			}
		}
```

Notice the space after the `SKPaint` method declaration and the `sk_paint_new` method call.

The rules in the `.editorconfig` file however are

```
csharp_space_between_method_call_name_and_opening_parenthesis = false
csharp_space_between_method_declaration_name_and_open_parenthesis = false
```

Also the `csharp_new_line_before_open_brace = all` is not followed in the above code.

Unfortunately, not all files are wrong, some indeed follow the rules...

Reformatting the code using Resharper changes a lot of files.

Not sure what the best approach would be? Should a PR reformat the whole file, applying the editorconfig rules?

**Comment by Gillibald** [comment]
I had the impression the convention would be to have a space after the method name.

`SkiaApi.sk_compatpaint_new ()` vs `SkiaApi.sk_compatpaint_new()` always getting anoyed of it while editing code.

**Comment by Ziriax** [comment]
I have been doing software consulting for 35 years for various companies, each of them having their own (sometimes almost religious) opinions about what coding rules to follow. Today I just don't care anymore, but I want my editor to do the dirty work for me 😉 

Microsoft's Visual Studio default is no space for both `csharp_space_between_method_call_name_and_opening_parenthesis`  and `csharp_space_between_method_declaration_name_and_open_parenthesis`, but most of the SkiaSharp code doesn't seem to follow that.

Anyway, IMHO if one decides to add an `.editorconfig`, one should reformat each modified code file, unless one is brave enough to reformat all code in one gigantic commit...

**Comment by mattleibow** [comment]
Hi folks, some of the code was written before following standards was strict-ish. So there are some mismatches. Also, some parts of the project are different 😬 
We are mostly following the .NET Foundation style, except for the `binding` folder which is more mono 😬 

Basically, try keep to the surrounding code, and if you spot a bad thing, look away 😆 . If you are working on that code, then feel free to correct. This helps keep the history working.

**Comment by mattleibow** [comment]
Closing this as there is a general hope of conformance over time while preserving history...
