### ISSUE TITLE
Enable stylus features with Forms Touch events [FEATURE] 

### ISSUE THREAD

**Issue by mscherotter** [mono/SkiaSharp#1201]
**Is your feature request related to a problem? Please describe.**
Add pressure, orientation, and button/eraser identification to SKCanvasView Touch events.

**Describe the solution you'd like**
Change the code in the SKTouchHandler to pass the pressure, button, and orientation of touch events coming from stylus.

**Describe alternatives you've considered**
None known

**Additional context**

**Comment by mattleibow** [comment]
This looks like a duplicate of #1186?

Closing this one.
