### ISSUE TITLE
[FEATURE] Include libSkiaSharp.dll PDB files to the nuget package

### ISSUE THREAD

**Issue by Mikolaytis** [mono/SkiaSharp#1202]
It would be super helpful for performance profiling. Is it possible?

**Comment by Gillibald** [comment]
I am against this because the current package is already gigantic.

**Comment by mattleibow** [comment]
There are 2 types of pdb files, the debug which is several hundred MB each and the release which is also pretty size-y (somehow a 80-90MB comes to mind...). We could use a symbols package that you opt into - like with snupkg or symbols.nupkg (whatever the new trend is) - but I am not sure if that applies to native code (I'll have to check).

But this has been on my mind for some time though. What/how does the other projects in the community deal with this?

**Comment by Gillibald** [comment]
For the native bits, we would need a special build that includes debugging symbols. Currently, these are excluded.

**Comment by Mikolaytis** [comment]
Maybe you can configure your pipeline to somehow upload these pdb files to the microsoft symbol server. It would be perfect.

**Comment by mattleibow** [comment]
I think this is what will work: https://github.com/mono/SkiaSharp/pull/1797

The symbols are actually available via the preview feed in a custom package, but this makes it a bit better.
