### ISSUE TITLE
[BUG]  The type initializer for 'SkiaSharp.SKImageInfo' threw an exception in .NET Core 3.1 nanoserver docker container

### ISSUE THREAD

**Issue by djarvis** [mono/SkiaSharp#1204]
**Description**

In a .NET Core 2.2 project that includes SkiaSharp, SkiaSharp.NativeAssets.NanoServer, building and running on mcr.microsoft.com/dotnet/core/sdk:2.2-nanoserver-1803 worked fine.

In a .NET Core 3.1 project that includes SkiaSharp, SkiaSharp.NativeAssets.NanoServer, building and running on mcr.microsoft.com/dotnet/core/sdk:3.1-nanoserver-1803 does not work.  The exception is:

_The type initializer for 'SkiaSharp.SKImageInfo' threw an exception.
Unable to load DLL 'libSkiaSharp' or one of its dependencies: The specified module could not be found. (0x8007007E)
Unhandled exception. System.TypeInitializationException: The type initializer for 'SkiaSharp.SKImageInfo' threw an exception.
 ---> System.DllNotFoundException: Unable to load DLL 'libSkiaSharp' or one of its dependencies: The specified module could not be found. (0x8007007E)
   at SkiaSharp.SkiaApi.sk_colortype_get_default_8888()
   at SkiaSharp.SKImageInfo..cctor()
_

**Code**

Just this one line will do it:

var bitmap = new SKBitmap(100, 100);

**Expected Behavior**

No exception

**Actual Behavior**

This exception:  _The type initializer for 'SkiaSharp.SKImageInfo' threw an exception.
Unable to load DLL 'libSkiaSharp' or one of its dependencies: The specified module could not be found. (0x8007007E)
Unhandled exception. System.TypeInitializationException: The type initializer for 'SkiaSharp.SKImageInfo' threw an exception.
 ---> System.DllNotFoundException: Unable to load DLL 'libSkiaSharp' or one of its dependencies: The specified module could not be found. (0x8007007E)
   at SkiaSharp.SkiaApi.sk_colortype_get_default_8888()
   at SkiaSharp.SKImageInfo..cctor()_

**Basic Information**

- Version with issue:  1.68.1.1
- IDE: .NET Core 3.1 SDK on mcr.microsoft.com/dotnet/core/sdk:3.1-nanoserver-1803

**Comment by djarvis** [comment]
The newer 1809 tags of just 3.1 and 2.2 show the same result.

I tried comparing both containers' forward DLLs and using NanoServerApiScan.exe but got the same results for both (FONTSUB.dll - CreateFontPackage).  Tried to dig deeper into the nativeassets and how that all worked but couldn't quite piece it together.

**Comment by djarvis** [comment]
The sample does work, however, using the Windows ServerCore container (mcr.microsoft.com/windows/servercore:ltsc2019).  

Seems they stripped out some key component from the 3.1 nanoserver (which is only ~737MB versus ~1.68GB for 2.2 nanoserver).

**Comment by djarvis** [comment]
Ok.  I just now came across this in the main description:

ExcludeAssets="native"

Which seems to fix it. 

Somehow I failed to stumble upon this sooner!

**Comment by mattleibow** [comment]
Ah, that is good news! Glad you were able to solve it. Maybe I should make things more obvious. I really need a Getting Started with explicit directions for each platform - and any caveats or things of note...
