### ISSUE TITLE
Cannot build on OS X - bootstrapper.sh script is for windows

### ISSUE THREAD

**Issue by Emasoft** [mono/SkiaSharp#121]
I tried to download and build the SkiaSharp library, and run the Xamarin.Forms demo project ( `Skia.Forms.Demo.sln` ), but when I open it in Xamarin Studio I get this error:

```
Restoring packages...
Unable to find version '1.53.0-beta' of package 'SkiaSharp'.
```

It seems that there is no up to date Nuget package. 

I tried to build the SkiaSharp package myself then.

I followed the Readme, but without success.

The following are the instructions from the Readme file:

```
## Building SkiaSharp

First clone the repository:

    $ git clone https://github.com/mono/SkiaSharp.git

Next, set up the submodules:

    $ cd SkiaSharp
    $ git submodule init && git submodule update
    
Then follow the platform-specific instructions below.

### Mac OS X

Run from Bash

    $ ./bootstrapper.sh -t libs

This runs the build process by using the `libs` build target.
```

The first steps worked, but the third one gives error:

```
bash-3.2$ ./bootstrapper.sh -t libs
./bootstrapper.sh: line 42: [: too many arguments
./bootstrapper.sh: line 47: [: too many arguments
./bootstrapper.sh: line 57: [: too many arguments
./bootstrapper.sh: line 84: pushd: /Users/Admin/Projects/XAMARIN: No such file or directory
Cannot open assembly '/Users/Admin/Projects/XAMARIN': No such file or directory.
Could not restore NuGet packages.
bash-3.2$ 
```

I checked inside the `bootstrapper.sh` file, and it seems to me that the script is for Windows, not for OS X as reported in the docs!  There is NO documentation on how to build it on OS X! 

Please help.

**Comment by mattleibow** [comment]
@Emasoft Sorry about that. We are busy releasing this version right now. It should be up very soon.
