### ISSUE TITLE
[BUG] Crash bug in SKTouchHandler.OnTouch 

### ISSUE THREAD

**Issue by mscherotter** [mono/SkiaSharp#1211]
**Description**

https://github.com/mscherotter/SkiaSharp/blob/master/source/SkiaSharp.Views.Forms/SkiaSharp.Views.Forms.Android/SKTouchHandler.cs

    var toolType = evt.GetToolType(id); 

in line 50 incorrectly passes the pointerID, not the pointer index and causes an exception: pointerIndex out of range

**Code**
The line should be 

    var toolType = evt.GetToolType(pointer);

**Expected Behavior**

No exception

**Actual Behavior**

An exception when touching the canvas
**Basic Information**

- Version with issue:  1.68.2-preview.50
- Last known good version:  1.68.2-preview.45
- IDE:   Visual Studio 
- Platform Target Frameworks: Android
  - Android: 9.0 
- Target Devices:   
  - 
  - 

**Screenshots**

**Reproduction Link**

**Comment by pauldendulk** [comment]
@mattleibow This is also a serious issue for Mapsui. Saturday we released rc.2 with 1.68.2-preview.50. Every time a user starts panning in the Android Forms sample it crashes.

To reproduce: 
1. Start Mapsui.Samples.Forms.Android
2. Select "1 MBtiles" sample
3. Place first finger on map
4. Place second finger on map
5. Lift first finger from map
6. See exception

**Comment by mattleibow** [comment]
I got a fix in, will release ASAP with the other one. I was just waiting for a build to complete.

The interesting thing is that getting the bad index did not fail on my Pixel 2 with Android 10. I tried with 3 finders and the pointers still worked. Pointer 2 with ID 0....
What devices did it actually crash on.

**Comment by pauldendulk** [comment]
- I tested on an Samsung Galaxy A70 with Android 10. 
- @jenssmeds reported it on a Huawei P20 Pro with Android 9. 
- Not sure what @charlenni used.

**Comment by mattleibow** [comment]
Just tested on a Razer (v1) with Android 9 and it crashed... Very interesting.

**Comment by mattleibow** [comment]
Well, it will be fixed and release as soon as that CI is done.
