### ISSUE TITLE
App using SkiaSharp fails validation with error "libSkiaSharp contains incomplete bitcode"

### ISSUE THREAD

**Issue by jgold6** [mono/SkiaSharp#122]
Reported in Xamarin desk case: https://kb.xamarin.com/agent/case/362730

<img width="701" alt="screen shot 2016-07-26 at 09 21 01" src="https://cloud.githubusercontent.com/assets/4606509/17226221/07dbd872-54a4-11e6-9a4c-66bbcaa9c31e.png">

XS Version info, build output, and Application Loader logs are attached.

[ApplicationLoaderViewLog.txt](https://github.com/mono/SkiaSharp/files/389190/ApplicationLoaderViewLog.txt)
[BuildOutput.txt](https://github.com/mono/SkiaSharp/files/389191/BuildOutput.txt)
[XS_Version_Info.txt](https://github.com/mono/SkiaSharp/files/389192/XS_Version_Info.txt)

**Comment by mattleibow** [comment]
This should be fixed in master and will be in the next release (very soon)
