### ISSUE TITLE
[BUG] Xamarin Forms - xunit - Could not load file or assembly 'SkiaSharp.Views.Forms

### ISSUE THREAD

**Issue by programmingworld1** [mono/SkiaSharp#1225]
**Description**

I have a xamarin forms project where I make use of this library in a ContentPage. When I create the ContentPage within a xunit test project (like: new DamagePage()), I get the following error: "Could not load file or assembly 'SkiaSharp.Views.Forms". The error is given when the Initializecomponent method is called in the codebehind of the ContentPage.

I have installed SkiaSharp.Views.Forms and SkySharp.svg in both the xamarin forms project and the test project, why do I still get this error?

**Code**

        
        <skia:SKCanvasView Grid.Row="0" HorizontalOptions="FillAndExpand" VerticalOptions="FillAndExpand">
            
            <skia:SKCanvasView.Behaviors>
                <behaviour:PaintSurfaceCommandBehavior Command="{Binding ShowDamageScreenCommand}" />
            </skia:SKCanvasView.Behaviors>

            
            <skia:SKCanvasView.GestureRecognizers>
                <TapGestureRecognizer Command="{ Binding OpenSetDamageCommand, Mode=TwoWay }" />
            </skia:SKCanvasView.GestureRecognizers>
        </skia:SKCanvasView>

**Expected Behavior**

When I create a the ContentPage from within my test project, I don't want it to fail because of the error.

**Actual Behavior**

When I delete the code in the view, the unit tests passes. When I put the code in there and I run a unit tests which creates the particular contentpage, the error arrises..

**Basic Information**

- Version with issue:  1.68.1.1
- Last known good version:  
- IDE:  Visual Studio
- Platform Target Frameworks: 
Xamarin Forms

**Comment by mattleibow** [comment]
Do you have the full stack trace?

Also, I would very strongly recommends a much better SVG processing library: 
 - source: https://github.com/wieslawsoltes/Svg.Skia
 - nuget: https://www.nuget.org/packages/svg.skia

This library has so many more features that SkiaSahrp.Svg. This is based on the almost feature complete https://github.com/vvvv/SVG library.

I would consider the SkiaSharp.Svg package deprecated and probably will not receive many, if any, updates in the near future.

**Comment by LuckyDucko** [comment]
@mattleibow I just ran into this issue myself, adding the GTK package resolved it.

**Comment by mattleibow** [comment]
Thanks for the feedback @LuckyDucko.

**Comment by mattleibow** [comment]
Based on the feedback, closing this.

**Comment by ibocon** [comment]
I am having same issue.
I added GTK package, but it does not work.
![image](https://user-images.githubusercontent.com/9730869/129995429-b7b2ce3f-177c-41c8-a27a-87d440fafda1.png)

Why SkiaSharp.Views.Forms.GTK is not restored using .NET Core? 
Is there something I am missing?
