### ISSUE TITLE
[BUG] Skiasharp breaks Edit And Continue functionality in Xamarin Forms UWP application

### ISSUE THREAD

**Issue by MathieuJack** [mono/SkiaSharp#1230]
As soon as a <SKCanvasView/> is added in a empty Xamarin Forms UWP Application, Edit And continue does not work any more

**Step to reproduce:**
Create a Mobile App (Xamarin.Forms) project.
Select UWP platform.
Add reference to SkiaSharp Nugets : SkiaSharp 1.68.1.1 SkiaSharp.View.Forms 1.61.1.1
In the Page xaml, add a <forms:SKCanvasView></forms:SKCanvasView>
Select UWP project
Put a breakpoint at first line of App constructor.
Hit F5.
When execution is breaked on breakpoint, add a dummy line of code in App Constructor.
Hit F5 to continue execution.

**Expected Behavior:**
Code change is well applied by "Edit And Continue" feature;
Code execution continues normally.

**Actual Behavior:**
Dialog box appear s: "Edits were made which cannot be compiled; Execution cannot continue unitl compile erros are fixed."
Error panel shows following error : "Failed to emit module 'App6': Changing the version of an assembly reference is not allowed during debugging: 'System.Runtime, Version=4.0.20.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' changed version to '4.1.2.0'.

**Conditions**
- Version with issue:  1.68.1.1; also reproduced with 1.68.0
- IDE:  Microsoft Visual Studio Community 2019 Version 16.5.3 
- UWP:  Microsoft.NETCore.UniversalWindowsPlatform v6.2.10

Notes : 
If <SKCanvas/> is removed from xaml but references to Skia# nugets kepts, then Edit and continue works again.

**Comment by MathieuJack** [comment]
Could you tell me if you feel I should post to Xamarin Github instead? 

Not having Edit and continue is a pity, especially when working with "Drawing" where it is common to make dozen of small code change to adjust graphics design. That's why Edit and Continue is essential for me when working with Skia#.

**Comment by MathieuJack** [comment]
Could you give a status to this bug please?

**Comment by mattleibow** [comment]
Let me have a look. Not sure why this would be happening... SkiaSharp is basically a netstandard library...

**Comment by mattleibow** [comment]
I tried a few things, but I can't seem to repro this.

I am using VS 2019 16.6.5 and I tried both the v1.68 and v2.80 versions of SkiaSharp. I also edited both the UWP app and the shared project. I was able to edit constructors and the paint method.

You might just need to update your VS. 🤞

**Comment by mattleibow** [comment]
Closing this issue due to a lack of response as well as not being reproducible. If this still occurs, please open a new issue.
