### ISSUE TITLE
[BUG] Forms.Android: GPU backed canvas is blank after power off and on 

### ISSUE THREAD

**Issue by charlenni** [mono/SkiaSharp#1232]
**Description**

If you use a GPU backed canvas (SKGLView) and power off the device and again on, the canvas is blank. If you than call an `InvalidateSurface()` or go to home and come back again, the canvas is redrawn correct.

**Code**

You could use my [SkiaTest](https://github.com/charlenni/SkiaTest), where a GPU and a CPU backed canvas could used beside each other.

**Expected Behavior**

GPU backed canvas should be redrawn as the CPU backed canvas.

**Actual Behavior**

GPU backed canvas isn't redrawn.

**Basic Information**

- Version with issue:  1.68.2-preview.60
- Last known good version:  Didn't saw any
- IDE:  Visual Studio 16.5.4
- Platform Target Frameworks: In this case Android
  - Android: 9.0 
  - Target Devices:  Huawei P8 lite 2017
  - Target Devices:  Simulator Nexus 4 with Android 5.0 (there even if a go to home and come back)
  - Target Devices:  Simulator Pixel 2 with Android 9.0

**Screenshots**

Looks like
<img src="https://user-images.githubusercontent.com/4381223/79455230-d58cb800-7fec-11ea-85de-206e1fd64a78.png" width="300" />
but should look like
<img src="https://user-images.githubusercontent.com/4381223/79455268-e9381e80-7fec-11ea-9efb-066f2ed5db48.png" width="300" />
Second image is created after changing to home and back again

**Reproduction Link**

See [SkiaTest](https://github.com/charlenni/SkiaTest).

**Comment by charlenni** [comment]
A short describtion, what to do in SkiaTest:
1. Press "Start" button at the bottom
2. Let it run for a second
3. Press "Stop" button at the bottom
4. Turn off your device
5. Turn it on again
6. GPU backed canvas is empty, CPU backed canvas is correct
7. Press "Home" button of device
8. Come back to SkiaTest
9. On some devices the GPU backed canvas is redrawn. Not on all.

**Comment by mattleibow** [comment]
@charlenni thanks for this issue with repro. I _just_ managed to repro it. And I have a fix. I think this was just happening on the older devices so I didn't notice. Thanks for the issue.

**Comment by mattleibow** [comment]
More info for other things: I was able to repro on Android 6.0 emulator.

**Comment by charlenni** [comment]
@mattleibow Thank you very much for your fast and reliable work.
