### ISSUE TITLE
[FEATURE] Allow SKColorF on SKPaint

### ISSUE THREAD

**Issue by Ziriax** [mono/SkiaSharp#1239]
**Is your feature request related to a problem? Please describe.**

In the `dev/update-skia`, `SKPaint` only has a `Color` property, of type `SKColor` (8-bit per channel)

In the [C++ Skia](https://source.chromium.org/chromium/chromium/src/+/master:third_party/skia/include/core/SkPaint.h;l=270?q=SKPaint&ss=chromium%2Fchromium%2Fsrc:third_party%2Fskia%2F&originalUrl=https:%2F%2Fcs.chromium.org%2F), one can also use floating point colors `ColorF`. Furthermore in the C++ API one can tell the paint what the colorspace of the color is... 

When using Skia's [linear rendering workflow](https://skia.org/user/sample/color?cl=9919), it is important to allow all colors to be specified in higher precision, with a linear transfer function
 
**Describe the solution you'd like**

Somehow expose this linear rendering stuff, still keeping C#'s handy property syntax?

Maybe create a `PhysicalColor` struct that holds both a `SKColorF` and `SKColorSpace`, and add properties like `SKPaint.PhysicalColor`?

**Additional context**

I guess in general supporting all the  [linear rendering workflow](https://skia.org/user/sample/color?cl=9919) features in Skia will be a lot of work?

**Comment by wieslawsoltes** [comment]
You can use shaders: 
```C#
public static SKShader CreateColor (SKColorF color, SKColorSpace colorspace)
```

> SkColor (stored on SkPaint) is assumed to be in the sRGB color space - meaning that it is in the sRGB gamut and encoded with the sRGB transfer function.
> 
> SkShaders (also stored on SkPaint) can be used to create more complex colors. Color and gradient shaders typically accept SkColor4f (float colors). These high precision colors can be in any gamut, but must have a linear transfer function.

`https://github.com/mono/SkiaSharp/blob/cef01f15e6018bee663e20961a0622bde122f15d/binding/Binding/SKShader.cs#L40

**Comment by Ziriax** [comment]
Perfect! Closing this then

**Comment by mattleibow** [comment]
Actually, opening this again. This did not exist in m68, but does in m80. I think it will be good to add to properly support `SKColorF` all over the show.

**Comment by Ziriax** [comment]
Yes, it would be easy to copy the Skia SDK exactly, so adding `SetColor(SkColorF, SkColorSpace)` and `GetColor(out, out)` but that feels shaky, non-CLR like.

That's why I proposed the `PhysicalColor` struct so that the user can specify unambiguous source colors, just like a target surface also has a color space. 

An extension method could be added to `SkColorSpace` to make physical colors in that space.

But I understand this would deviate too much from the original API...

**Comment by Gillibald** [comment]
setColor: https://github.com/google/skia/blob/master/include/core/SkPaint.h#L272
getColor: https://github.com/google/skia/blob/master/include/core/SkPaint.h#L244

So they store the color as `SKColor4f` this should be matched in the binding casting from SKColor to SKColor4f will be possible but should give a warning because conversion is involved.

**Comment by Ziriax** [comment]
> setColor: https://github.com/google/skia/blob/master/include/core/S
> So they store the color as `SKColor4f` this should be matched in the binding casting from SKColor to SKColor4f will be possible but should give a warning because conversion is involved.

SkColor holds 8-bit channels, so could be converted to SkColorF without any loss?

**Comment by Gillibald** [comment]
SKColor to SKColor4f has lo loss but SKColor4f to SKColor has a los. Internally it is stored as SKColor4f

**Comment by mattleibow** [comment]
@Ziriax I see they don't actually have a `getColor` that returns a colorspace. It is just used when setting. The colorspaces is just used for setting the color. You basically provide a "base" color and a colorspace.

https://github.com/google/skia/blob/chrome/m83/src/core/SkPaint.cpp#L116-L123

**Comment by Ziriax** [comment]
Ouch, indeed! My bad
