### ISSUE TITLE
[QUESTION] Is SKPixMap.GetPixelSpan supposed to be readonly?

### ISSUE THREAD

**Issue by Ziriax** [mono/SkiaSharp#1240]
`SKPixMap.GetPixelSpan` returns a  `ReadOnlySpan<byte>`, not a `Span<byte>`

So one can't use that for direct pixel manipulation.

Is this by design? I believe a pix-map is writable no?

Skia itself also has `void* SKPixMap::writable_addr() `.

It would also be useful to have a generic version, to avoid having to call `MemoryMarshal` methods

**Comment by mattleibow** [comment]
Technically yes... It uses the "readonly" version. But that pointer is also returned for the writeable. So there is actually no real difference.

I think it is good to add both the writeable version and the generic.

**Comment by mattleibow** [comment]
A "workaround" right now is to just create your own span:

```cs
var span = new Span<T> ((void*)pixmap.GetPixels (), pixmap.BytesSize);
```

That is almost exactly what I do under the hood. In fact, that is what this feature will be.

**Comment by Ziriax** [comment]
Thanks, did that, and also added the unmanaged constraint.

I just discovered that .net core 3 now has native SIMD intristics...

C# is now exciting even for low level hackers ;-)

**Comment by mattleibow** [comment]
Thanks for the tip on the unmanaged constraint!

**Comment by mattleibow** [comment]
Just be aware that skia flips the bits depending on the CPU endian-ness.

**Comment by mattleibow** [comment]
Let me know what you think of #1242
