### ISSUE TITLE
[QUESTION] Will SkiaSharp support SKParagraph

### ISSUE THREAD

**Issue by charlenni** [mono/SkiaSharp#1248]
Hello,

will SkiaSharp support [SKParagraph](https://github.com/google/skia/tree/master/modules/skparagraph) or stay with [RichTextKit](https://github.com/toptensoftware/RichTextKit) for rendering texts or aren't both related and I have understand it completely wrong?

Thank you for your answer.

Best regards,
Dirk

**Comment by taublast** [comment]
And if not, why..

**Comment by jgcodes2020** [comment]
Can someone triage this please?

**Comment by cr4yz** [comment]
Can someone triage this please?

**Comment by Gillibald** [comment]
This can't be part of the main package because it relies on ICU

**Comment by mattleibow** [comment]
> This can't be part of the main package because it relies on ICU

And also if there are bugs in there, we have to wait for the next major skia update once a year or two. RichTextKit is pretty good and can iterate much faster than this engine project.

**Comment by HppZ** [comment]
any update?
