### ISSUE TITLE
SKImage.FromBitmap does not work

### ISSUE THREAD

**Issue by gentledepp** [mono/SkiaSharp#125]
When using "SKImage.FromBitmap", the resulting image is always completely filled black.
I added the Binding myself, however I doubt that the problem lies there.

In order to quickly reproduce this issue, open the "Skia.WindowsDesktop.Demo" application and add the following code to "SkiaView.cs"

```csharp
protected override void OnPaint(PaintEventArgs e)
{
    base.OnPaint(e);

    if (sample == null)
        return;

    var width = Width;
    var height = Height;

    using (var bitmap = new Bitmap(width, height, PixelFormat.Format32bppPArgb))
    {
        var data = bitmap.LockBits(new Rectangle(0, 0, width, height), ImageLockMode.WriteOnly, bitmap.PixelFormat);
        using (var surface = SKSurface.Create(width, height, SKImageInfo.PlatformColorType, SKAlphaType.Premul, data.Scan0, width * 4))
        {
            var skcanvas = surface.Canvas;
            // works
            sample.Method(skcanvas, width, height);
            SaveBitmap("SKSurface.Snapshot() => works", surface.Snapshot());

            // does NOT work
            using (var b = new SKBitmap(width, height))
            using (var s = SKSurface.Create(b.Info))
            {
                sample.Method(s.Canvas, width, height);
                SaveBitmap("SKImage.FromBitmap => empty png file", SKImage.FromBitmap(b));
            }
        }
        bitmap.UnlockBits(data);

        e.Graphics.DrawImage(bitmap, new Rectangle(0, 0, Width, Height));
    }
}

private void SaveBitmap(string title, SKImage snapshot)
{
    var dlg = new SaveFileDialog();
    dlg.Title = title;
    dlg.Filter = "Png Files|*.png;";
    var res = dlg.ShowDialog();

    if (res == DialogResult.OK)
    {
        using (var stream = File.OpenWrite(dlg.FileName))
        using (snapshot)
        {
            var data = snapshot.Encode(SKImageEncodeFormat.Png, quality: 100);
            data.SaveTo(stream);
        }
    }
}
```

This results in two "SaveFileDialogs" being opened.
The first one creates the correct PNG as it uses SKSurface.Snapshot();
The second one creates the empty (completely transparent) PNG using SKImage.FromBitmap();
So I am assuming that "SKImage.FromBitmap" has some bug?

**Comment by mattleibow** [comment]
@gentledepp Thanks for reporting this. I'll have a look

**Comment by gentledepp** [comment]
Any guesses where I should look at, @mattleibow ?
I need to fix this until thursday if possible :-|

**Comment by mattleibow** [comment]
I am looking now. `FromBitmap` can load a bitmap and save it fine, so I think that works. What is blank in your screen? The image or the screen?

**Comment by gentledepp** [comment]
The resulting png is empty.

Am 02.08.2016 18:22 schrieb "Matthew Leibowitz" <notifications@github.com>:

**Comment by mattleibow** [comment]
Ah, this is not correct:

```csharp
using (var b = new SKBitmap(width, height))
using (var s = SKSurface.Create(b.Info))
```

`b.Info` has no reference to the bitmap itself, just the size/color. That `SKSurface.Create` is actually creating a new bitmap under the hood.

There are two ways to do this:
1. `s.Snapshot()`
2. `SKSurface.Create` with the bytes to the image

Let me see if I can get some code here...

**Comment by mattleibow** [comment]
```csharp
IntPtr length;
using (var b = new SKBitmap(width, height, SKImageInfo.PlatformColorType, SKAlphaType.Premul))
using (var s = SKSurface.Create(b.Info, b.GetPixels(out length), b.RowBytes))
{
    sample.Method(s.Canvas, width, height);
    SaveBitmap("FromBitmap", SKImage.FromBitmap(b));
}
```

OR

```csharp
// no need to the bitmap
using (var s = SKSurface.Create(b.Info))
{
    sample.Method(s.Canvas, width, height);
    SaveBitmap("FromBitmap", s.Snapshot());
}
```

**Comment by mattleibow** [comment]
@gentledepp does this work for you?

**Comment by gentledepp** [comment]
I am already out of the office. will try tomorrow. Thank you for helping me
out!

Am 02.08.2016 19:08 schrieb "Matthew Leibowitz" <notifications@github.com>:

**Comment by gentledepp** [comment]
Your suggestions both work like a charm!
Thank you so much. Indeed, in the SVG library, I made the same mistake that you pointed out:
`using (var b = new SKBitmap(width, height))
using (var s = SKSurface.Create(b.Info))`

Thank you so much!
