### ISSUE TITLE
[BUG] Upgrade to 1.68.2: Could not load file or assembly 'SkiaSharp' or one of its dependencies. Strong name signature could not be verified

### ISSUE THREAD

**Issue by AndersMad** [mono/SkiaSharp#1267]
**Description**

Error on run after upgrade: `HttpException (0x80004005): Could not load file or assembly 'SkiaSharp, Version=1.68.0.0, Culture=neutral, PublicKeyToken=0738eb9f132ed756' or one of its dependencies. Strong name signature could not be verified.  The assembly may have been tampered with, or it was delay signed but not fully signed with the correct private key. (Exception from HRESULT: 0x80131045)]`

I have upgraded a few times before without problems. Choosing nuget package 1.68.1.1 again and it works. Target is x64 only.

I cleaned solution, deleted .suo file, uninstalled nuget etc. but i can't get it to work.

**Basic Information**

- Version with issue:  1.68.2
- Last known good version:  1.68.1.1
- IDE: Visual Studio 2019
- Platform Target Frameworks: .NET FrameWork 4.8 - x64

**Comment by mattleibow** [comment]
Whoah. Thanks for reporting this!

I'm having a look right now and for some reason MSBuild is no longer strong naming... Nothing has changed on my side. Will release a fix ASAP.

**Comment by mattleibow** [comment]
@AndersMad thanks for reporting this so quickly. 

I am busy waiting on a build to finish and then I'll push to the preview feed. Once it is out, you can confirm that it works and then I'll push to NuGet.

I have added build tests so this should not happen again.

**Comment by AndersMad** [comment]
thanks! I look forward to that (not there yet).. I'll just pop a side question here: I got several issue that i think is linked to the raather "old" Skia version.. ETA on > v68? (maybe I should create a new topic for this)

**Comment by mattleibow** [comment]
We got previews already! Check out the preview feed: https://aka.ms/skiasharp-eap/index.json

We are just waiting on more feedback for this before we push to NuGet. There are 2 APIs that need another look, but not many people use them. So, go ahead and start testing!

**Comment by AndersMad** [comment]
thanks! I just tried that - but I'm afraid that I got the same strong name issue on the `2.80.0-alpha.3` build :)

**Comment by mattleibow** [comment]
Ah, yeah. That will happen. Almost done here. All good on my machine and CI is just not going to let it go. sn.exe is hard to find haha

**Comment by mattleibow** [comment]
The packages are pushed to the preview feed as **1.68.2.1-preview.2**

 https://aka.ms/skiasharp-eap/index.json

**Comment by AndersMad** [comment]
confirmed working! thanks.. also tested bad images and they are still bad - so I look forward to test the 2.80 alpha build \o/

**Comment by mattleibow** [comment]
Awesome, I'll push to NuGet.

**Comment by mattleibow** [comment]
And the new v2.80 is also up! Check out alpha 4 on the preview feed.

**Comment by AndersMad** [comment]
the v2.80 sign ok!
and seems to fix this: https://github.com/mono/SkiaSharp/issues/932
and this is a bit better but color is still a bit off: https://github.com/mono/SkiaSharp/issues/931
but not this: https://github.com/mono/SkiaSharp/issues/719

**Comment by mattleibow** [comment]
Awesome! I added those issues to the list of things to figure out for v2.80.

**Comment by AndersMad** [comment]
all above (https://github.com/mono/SkiaSharp/issues/1267#issuecomment-622988787) is now closed with v2.80 in my opinion.. 

and as this topic/issue is a bit twisted anyways now - can I ask how you would consider v2.80 (alpha - I know) safe to use? stomach feeling? :) cause in my world its way better already..

**Comment by mattleibow** [comment]
Well, the tests pass and things are looking good. So yeah, if it works now then it should be OK. I did lots of tests before it went out, so I am 50% confident. Your feedback moves it to a nice 75%. I have a few APIs to add in, such as DrawTextOnPath. I may tweak some APIs, but the native skia part is now done.
