### ISSUE TITLE
When use SKPaint.GetTextPath(strText,0f,0f), if strText="👨‍👩‍👧‍👦"  or "ยู่", the result is not correct.

### ISSUE THREAD

**Issue by XMTei** [mono/SkiaSharp#1275]
Regarding SKPaint.GetTextPath(strText,0f,0f)
If the strText is a Ligature, such as "👨‍👩‍👧‍👦" or "ยู่", it can not get correct SKPath.

In this case
👨‍👩‍👧‍👦:an Emoji combined from U+1F468, U+200D, U+1F469, U+200D, U+1F467, U+200D, U+1F466
ยู่: a Thai character combined from ย + ู + ่
If SKPaint.GetTextPath() full support those cases, it will be powerful tool.

More details
We can use StringInfo.GetTextElementEnumerator() to split string to grapheme clusters.
👨‍👩‍👧‍👦 could be a grapheme cluster.
P.S.  .NET standard 2.1 does not support Emoji, but .NET 5 will support all the Emoji we have.

I use SKPaint.GetTextPath on a Lettering tool (see https://infbjlettering.azurewebsites.net). Everything
is OK but the combined character.

**Comment by Gillibald** [comment]
That is expected. Please use SkiaSharp.HarfBuzz to shape the text.

**Comment by mattleibow** [comment]
There are also 2 great libraries for drawing text:
 - https://github.com/wouterst79/SkiaSharp.TextBlocks
 - https://github.com/toptensoftware/RichTextKit
