### ISSUE TITLE
Unable to create "Gotham Book" TypeFace using SkiaSharp

### ISSUE THREAD

**Issue by Jack-Paul** [mono/SkiaSharp#1278]
**Description**

We are unable to create "Gotham Book" Typeface with exact font family name and font weight.

**Code**

SKTypeface skTypeFace = SKTypeface.FromFamilyName("Gotham Book", SKFontStyleWeight.Normal, SKFontStyleWidth.Normal, SKFontStyleSlant.Upright);

**Expected Behavior**

skTypeFace.FamilyName = "Gotham"

**Actual Behavior**

skTypeFace.FamilyName = "DejaVu Sans"

**Basic Information**

- Version with issue:  1.59.3 
- IDE:   Visual Studio 2019
- Platform Target Frameworks: .Net Standard 2.0 

**Reproduction Link**

Please install Gotham Book font and use the above code to Replicate this issue.

**Comment by ManishSync** [comment]
Hi @Redth 

Any update on this?


Regards,
Manish R

**Comment by mattleibow** [comment]
Is the font installed? I think that is the default font. Not all platforms have all the same fonts.

 Also, is there a reason why you are using the older versions of SkiaSharp and not the newer 1.68.3?
