### ISSUE TITLE
How do I load the OCR-B font family by name?

### ISSUE THREAD

**Issue by Drise13** [mono/SkiaSharp#1290]
I've used variants of `SKTypeface.FromFamilyName("OCRB", SKFontStyleWeight.Normal, SKFontStyleWidth.Normal, SKFontStyleSlant.Upright);` such as `OCR B` and `OCR-B` and I always get back `Segoe UI`. How do I load the correct font by name?

**Comment by mattleibow** [comment]
Is the font installed into the OS? Also, what platform is this? Finally, the best way to check things is to load the font by filename and then see what it is called using the `FamilyName` property.

**Comment by Drise13** [comment]
Font is installed on the Windows 10 OS.
