### ISSUE TITLE
[BUG] XPS creation silently fails on Linux

### ISSUE THREAD

**Issue by Jonesie** [mono/SkiaSharp#1291]
**Description**

Creation of an XPS document fails on Linux with no exception.  Just a null result.
Works fine on windows.

**Code**

`            var outputStream = File.Create("./xpstest.xps");
            var managedStream = new SKManagedWStream(outputStream);
            var document = SKDocument.CreateXps(managedStream);
`

**Expected Behavior**

Document should not be null or an exception raised.

**Actual Behavior**

Document is null.

**Basic Information**

netcoreapp3.1

- Version with issue:  1.68.2.1
- Last known good version:  ??
- IDE:  Visual Studio Code 
- Platform Target Frameworks:  
  - Linux:  Ubuntu 18.04 LTS
  - Windows Classic:  Windows 7+
- Target Devices:   

**Screenshots**

**Reproduction Link**

https://gist.github.com/Jonesie/0ce0e93d541c92516429fa205fc6319b

**Comment by Jonesie** [comment]
Oh.
Just found this:
https://github.com/mono/SkiaSharp/blob/fc9f030a08eb158fb934774cdf54f8df939088c7/tests/Tests/SKDocumentTest.cs#L136

Only supported on windows.  Fair enough, but it would be more useful if an exception was raised.

**Comment by mattleibow** [comment]
Yeah, this is sadly a bad choice in the past. Changing it now will be breaking.

However, I think if we do reach a stage where we have a whole bunch of APIs that need changing, then we might do that. But for now, the places with this are very few. I think it is just XPS.
