### ISSUE TITLE
[FEATURE] Metal/Vulkan support

### ISSUE THREAD

**Issue by zhuah** [mono/SkiaSharp#1295]
**Is your feature request related to a problem? Please describe.**
I'm using the `dev/update-m80` branch of `mono/skia` library directly, without C#, but doesn't found metal/vulkan related apis in `include/c/gr_context.h`, 
and i knows that there is vulkan binding landed in `xamarin-develop` branch recently, will it be merged to `dev/update-*` branch? or i should just use `xamarin-develop` branch?

**Describe the solution you'd like**
I'd like the `mono/skia` library supports both vulkan and metal.

**Describe alternatives you've considered**
I currently using opengl on all platforms, and also `google/angle` library on windows.

**Additional context**

**Comment by mattleibow** [comment]
Thanks for asking this. Actually, the skia `xamarin-develop` is the later branch and that should be used instead of `dev/update-m80` (which is going to be deleted soon). This goes with the SkiaSharp `develop` branch.

Metal is coming soon, I think it is just a few APIs to add.

Vulkan has landed and is available on Win32, Linux and Android.

For use of ANGLE on Windows, we currently create views just for UWP, but do you also use it on Win32?

**Comment by mattleibow** [comment]
If you are interested in trying out code without building, check out the v2.80 alphas on https://aka.ms/skiasharp-eap/index.json

**Comment by zhuah** [comment]
I got it, thanks for your reply, and also your great works😀.
i'm not so familiar with cpp, the mono/skia's c binding is so awesome.

And another issue, i don't needs skias cpp api, so i added `"-DSK_API"` for msvc and `"-DSK_API=__attribute__((visibility("hidden")))"` for clang/gcc to extra_cflags,
it saves some binary size, it may also useful for SkiaSharp.

**Comment by Gillibald** [comment]
We have this version script https://github.com/mono/SkiaSharp/blob/master/native/linux/libSkiaSharp/libSkiaSharp.map

**Comment by zhuah** [comment]
ok, thank you, i'm closing this issue.

**Comment by nor0x** [comment]
thanks for the latest release 2.80.0 which has Vulkan support 🙌 . I wanted to check in on the Metal APIs for macOS. Are they still under construction, just wondering because this issue is closed already

**Comment by mattleibow** [comment]
Ah, missed it in this issue. Opened a new one https://github.com/mono/SkiaSharp/issues/1391

I'll see what it takes and start a PR.
