### ISSUE TITLE
[BUG][iOS] Could not initialize an instance of the type 'OpenGLES.EAGLContext': the native 'initWithAPI:' method returned nil

### ISSUE THREAD

**Issue by MKnoski** [mono/SkiaSharp#1303]
**Description**

SKGLView fails to initialise with the error "**Could not initialize an instance of the type 'OpenGLES.EAGLContext': the native 'initWithAPI:' method returned nil**"

StackTrace:

`NSObject.InitializeHandle (System.IntPtr handle, System.String initSelector)
OpenGLES.EAGLContext..ctor (OpenGLES.EAGLRenderingAPI api) <0x100a9c820 + 0x0005b> in <79170d3ca0a34f20a27c5ea33d79161f#cb7c80be70a7684816046182eab111ad>:0
SKGLView.Initialize ()
SkiaSharp.Views.iOS.SKGLView..ctor () <0x101575dc0 + 0x0001b> in <1dff7dabaada4d38b0d12baee26f046c#cb7c80be70a7684816046182eab111ad>:0`

**Code**

`				var view = new SKGLView
				{
					TranslatesAutoresizingMaskIntoConstraints = false,
					BackgroundColor = UIColor.Clear
				};`

**Expected Behavior**

The GL view works as normal.

**Actual Behavior**

The above exception

**Basic Information**

- Version with issue:  1.68.0
- Last known good version:  
- IDE:  Visual Studio for Mac
- Platform Target Frameworks: 
  - iOS:  13.4.1
- Target Devices:   
  - iPad Air (3rd gen)

**Comment by mattleibow** [comment]
This is a bit concerning... Does the app run on an older OS? 13.3?

I know Apple was depreciating GL, but I don't thing they were removing it. Especially not in a minor update.

**Comment by MKnoski** [comment]
Most affected OS is 13.3.1

**Comment by mattleibow** [comment]
Are you able to update to the later versions of SkiaSharp: 1.68.3? I have not seen this happen locally. What happens if you try another device?

**Comment by mattleibow** [comment]
Closing due to no response. However, if this issue still persists, feel free to reopen.
