### ISSUE TITLE
[BUG] Not linking correctly

### ISSUE THREAD

**Issue by chrisfoulds** [mono/SkiaSharp#1304]
**Description**

After a full rebuild the app works, only subsequent builds with 

**Code**

N/A , happens regardless

**Expected Behavior**

No crash
**Actual Behavior**

Crash - see attached screenshot

**Basic Information**

- Version with issue:  1.68.3 , VS Mac 8.6 Build 4520
- Last known good version:  This version until latest VS update
- IDE:  8.6 4520 - Mac
- Platform Target Frameworks:  Xamarin forms 4.6.0.800
  - iOS:  12
- Target Devices:   iPhone SE 2020 Simulator

**Screenshots**

<img width="1469" alt="Screenshot 2020-05-22 at 11 13 08" src="https://user-images.githubusercontent.com/16035209/82657579-7cccc280-9c1d-11ea-93cb-8c5785584ba8.png">

**Reproduction Link**

**Comment by chrisfoulds** [comment]
For info it is showing as loaded assembly when you run the app.
Loaded assembly: /Users/chrisfoulds/Library/Developer/CoreSimulator/Devices/286AE6C2-3029-4B45-B91E-07CA4464325B/data/Containers/Bundle/Application/8326DBC9-DB11-40B3-8A93-6CB04C68C5A1/MyApp.iOS.app/SkiaSharp.Views.Forms.dll [External]
Loaded assembly: /Users/chrisfoulds/Library/Developer/CoreSimulator/Devices/286AE6C2-3029-4B45-B91E-07CA4464325B/data/Containers/Bundle/Application/8326DBC9-DB11-40B3-8A93-6CB04C68C5A1/MyApp.iOS.app/SkiaSharp.Views.iOS.dll [External]
Loaded assembly: /Users/chrisfoulds/Library/Developer/CoreSimulator/Devices/286AE6C2-3029-4B45-B91E-07CA4464325B/data/Containers/Bundle/Application/8326DBC9-DB11-40B3-8A93-6CB04C68C5A1/MyApp.iOS.app/SkiaSharp.dll [External]

Simulator is iOS13.5

**Comment by chrisfoulds** [comment]
same happens with 13.4 simulator

**Comment by chrisfoulds** [comment]
Tested on real device (13.5) - also experienced exact same issue. Will gather logs

**Comment by chrisfoulds** [comment]
Crash on real device 
<img width="1603" alt="Screenshot 2020-05-25 at 10 29 30" src="https://user-images.githubusercontent.com/16035209/82799889-acc0d380-9e72-11ea-95b1-b8c35988634c.png">

**Comment by chrisfoulds** [comment]
Ran on iOS12 simulators and devices with same issues. All other components are loading and linking correctly on quick rebuilds, it is just skiasharp failing.

**Comment by chrisfoulds** [comment]
Also occurs on new 8.6.1 (build 26)

**Comment by chrisfoulds** [comment]
Did some more investigation,  I have a second Mac not quite so updated. It has the latest XCode but not everything new.
I synced the project it worked no matter what, all good.
I then ran Visual studio updater and updated all the components (see attached screenshots) and not I get the exact same issue.
Kinda annoyed I wiped out a second machine but it is reproducible. 
<img width="599" alt="Screenshot 2020-05-28 at 20 20 22" src="https://user-images.githubusercontent.com/16035209/83185361-c12af780-a122-11ea-8e05-b30dd3730116.png">
<img width="598" alt="Screenshot 2020-05-28 at 20 20 30" src="https://user-images.githubusercontent.com/16035209/83185365-c38d5180-a122-11ea-8c8f-d5bf1bf848ab.png">

**Comment by chrisfoulds** [comment]
Looking at logs 
On first build 
/reference:/Users/chrisfoulds/.nuget/packages/skiasharp/1.68.3/lib/xamarinios1.0/SkiaSharp.dll /reference:/Users/chrisfoulds/.nuget/packages/skiasharp.svg/1.60.0/lib/netstandard2.0/SkiaSharp.Extended.Svg.dll /reference:/Users/chrisfoulds/.nuget/packages/skiasharp.views.forms/1.68.3/ref/xamarinios1.0/SkiaSharp.Views.Forms.dll /reference:/Users/chrisfoulds/.nuget/packages/skiasharp.views/1.68.3/lib/xamarinios1.0/SkiaSharp.Views.iOS.dll

change one line of code and the build log has
/reference:/Users/chrisfoulds/.nuget/packages/skiasharp/1.68.3/lib/netstandard2.0/SkiaSharp.dll /reference:/Users/chrisfoulds/.nuget/packages/skiasharp.svg/1.60.0/lib/netstandard2.0/SkiaSharp.Extended.Svg.dll /reference:/Users/chrisfoulds/.nuget/packages/skiasharp.views.forms/1.68.3/ref/netstandard2.0/SkiaSharp.Views.Forms.dll

So that is the reason, but what is the cause?

**Comment by chrisfoulds** [comment]
On same machine
Downgraded MonoDroid, MonoiOS, Mono Framework & Visual Studio and it all works
So either one of them is broke or you have serious incompatibility with it.

Now running
VS 8.5.6 - build 11
MonoDroid - 10.2
MonoIOS - 13.16

**Comment by chrisfoulds** [comment]
On Second machine downgraded VS but left everything else as latest
(Mono, MonoDroid,MonoIOS) 
Still breaks, so it's not VS
It is a build issue when being used with one of the later MonoBuilds

**Comment by chrisfoulds** [comment]
FYI : I narrowed it down to Xamarin.iOS 
I am on 13.16.0.13
If I upgrade that it stops working straight away

**Comment by mattleibow** [comment]
Thanks for the continuous stream of info. Sorry I couldn't respond quicker.

You say that it breaks on updating Xamarin... Very weird. If you crack open the iOS app package, can you see the libSkiaSharp.framework?

Also, I _just_ pushed out a new preview package v2.80 (preview 12) that uses a new way of packaging the native parts in the nuget. What happens if you give that version a go? Try with the old version of X.iOS and see if that still works, and then upgrade and see if it breaks. It should work in both cases.

Also, I believe the most common issue with this native bit is that there is a bad caching on the device, so make sure you delete the obj and then app off the phone/sim.

Let me know if that changes anything. I am hoping the v2 way of packaging fixes a few annoying iOS issues.

**Comment by chrisfoulds** [comment]
I've updated and I am getting this build error - which may point to the source of all the problems.
Not sure how to fix it though :-)

`/Users/chrisfoulds/workspace/runtorace/RunToRace/RunToRace.iOS/error MT0099: Error: 'can't process a mix of dylibs and frameworks: /Users/chrisfoulds/.nuget/packages/skiasharp/2.80.0-preview.12/build/xamarinios1.0/../../runtimes/ios/native/libSkiaSharp.framework, /Users/chrisfoulds/workspace/runtorace/RunToRace/RunToRace.iOS/obj/iPhoneSimulator/Debug/device-builds/iphone 6 plus-12.4/mtouch-cache/libSkiaSharp.framework'. Please file a bug report with a test case (https://github.com/xamarin/xamarin-macios/issues/new). (RunToRace.iOS) Internal`

**Comment by chrisfoulds** [comment]
First I removed
[assembly: ObjCRuntime.LinkWith("libSkiaSharp.framework", SmartLink = true)]

xamarin.ios 13.16.013
Clean build works
Make one line change, build and run - works

installed
xamarin 13.18.2.1
 Deleted all obj/bin directories
Uninstall the app and reboot
Full build - works
Make one line change, build and run - still fails

Is there any build logs etc. that could help ?

**Comment by chrisfoulds** [comment]
build logs show this, surely this is not the right library it is linking ....

`/reference:/Users/chrisfoulds/.nuget/packages/skiasharp/2.80.0-preview.12/lib/netstandard2.0/SkiaSharp.dll /reference:/Users/chrisfoulds/.nuget/packages/skiasharp.svg/1.60.0/lib/netstandard2.0/SkiaSharp.Extended.Svg.dll /reference:/Users/chrisfoulds/.nuget/packages/skiasharp.views.forms/2.80.0-preview.12/ref/netstandard2.0/SkiaSharp.Views.Forms.dll `

**Comment by mattleibow** [comment]
What happens if you create a brand new project, Add SkiaSharp and then draw a red block? Like totally fresh.

If it happens, then send that project to me and I'll try and reproduce it. If it is not, then maybe send the iOS csproj file (remove any secrets/passwords) Maybe there is something weird there...

**Comment by mattleibow** [comment]
Maybe you could attach the binlog for this project: `msbuild /r /bl`

You can rebuild, make a change, and then run msbuild with `/bl` and attach that when it fails.

But also share the list of packages you have installed in the iOS project - should be in the `obj/project.assets.json` file. Just attach that as well.
