### ISSUE TITLE
[BUG] Can we create TimesNewRoman font similar to GDI+ ?

### ISSUE THREAD

**Issue by VijayRM** [mono/SkiaSharp#1305]
By using below code GDI+, creates TimesNewRoman font but if we specified the name as "Times" then SkiaSharp not gives TimesNewRoman.

GDI+ :
`Font font = new Font("Times", 10);`

SkiaSharp:

`SKTypeface typeFace = SKTypeface.FromFamilyName("Times", SKFontStyleWeight.Normal, SKFontStyleWidth.Normal, SKFontStyleSlant.Upright);`

Expected Typeface name is  "Times New Roman", very similar to GDI+ font.Name property.

**Comment by Gillibald** [comment]
What do you expect when you write `SKTypeface.FromFamilyName("T")`? Should it also load a typeface named `Times New Roman`? The font family is called `Times New Roman` and just writing `Times` is a mistake.

**Comment by VijayRM** [comment]
you are correct but unfortunately GDI+ returns correct font family name. As we using SkiaSharp, as a alternate to  GDI+ our customer reported as defect.

So, do we need to implement some mapping to get similar to GDI+ result.

**Comment by mattleibow** [comment]
@VijayRM this might be something that you might have to do. For example, you can first try the direct lookup, and if that fails use the `SKFontManager.FontFamilies` property to get all the available families. This could give you more control on all the platforms to find fonts that match what you are looking for - for example do a "starts with" search as well.
