### ISSUE TITLE
[BUG] / [QUESTION] Disposing a SKTypeface instance can break other instances

### ISSUE THREAD

**Issue by Jonarw** [mono/SkiaSharp#1306]
Over at oxyplot we are facing a kind of strange [issue](https://github.com/oxyplot/oxyplot/issues/1573) with our `SkiaRenderContext`, which is based on SkiaSharp 1.68.1.1.

### High-Level Issue

Basically, inside `SkiaRenderContext`, we are [caching](https://github.com/oxyplot/oxyplot/blob/7329013d6f48331e42b81c4315cd13fb5a82bb8f/Source/OxyPlot.SkiaSharp/SkiaRenderContext.cs#L845) instances of `SKTypeface` to reuse them during the rendering operation. This works fine in general. The problem arises when we create and dispose a second instance of `SkiaRenderContext`, which during its disposal will [dispose](https://github.com/oxyplot/oxyplot/blob/7329013d6f48331e42b81c4315cd13fb5a82bb8f/Source/OxyPlot.SkiaSharp/SkiaRenderContext.cs#L473) all the cached fonts it used. From that point on, the text rendering of the first `SkiaRenderContext` will be broken, even though this was never disposed itself.

_(The use case here could be: export a plot using one of the SkiaSharp-based exporters while displaying the plot in a SkiaSharp-based PlotView)_

### Repro

I managed to reproduce the issue using the following minimized example:

        public void TestTypefaceDisposal()
        {
            using var bitmap = new SKBitmap(100, 60);
            using var canvas = new SKCanvas(bitmap);
            canvas.Clear(SKColors.White);

            var minimumRenderContext = new MinimumRenderContext();

            // this draws correctly
            minimumRenderContext.DrawText(new SKPoint(20, 20), "OxyPlot", canvas);

            // create and dispose a completely unrelated SKTypeface instance
            SKTypeface.FromFamilyName("Courier New").Dispose();

            // this does NOT render correctly
            minimumRenderContext.DrawText(new SKPoint(20, 40), "OxyPlot", canvas);

            using var fileStream = File.OpenWrite("test.png");
            using var skStream = new SKManagedWStream(fileStream);
            SKPixmap.Encode(skStream, bitmap, SKEncodedImageFormat.Png, 0);
        }

        private class MinimumRenderContext
        {
            private SKTypeface cachedTypeFace;

            public void DrawText(SKPoint point, string text, SKCanvas canvas)
            {
                this.cachedTypeFace ??= SKTypeface.FromFamilyName("Courier New");
                using var paint = new SKPaint() { Typeface = this.cachedTypeFace };
                canvas.DrawText(text, point, paint);
            }
        }

### Expected Result

I would expect both lines to be identically rendered in Courier New. 

### Actual Result

This code above gives the following output in `test.png`:
![test](https://user-images.githubusercontent.com/18097859/82657436-a558ba80-9c25-11ea-886c-9bbbcb4b7694.png)

Obviously the second line is rendered in a different font. Depending on the circumstances, this can have more serious effects including missing glyphs.

It seems that disposing a `SKTypeface` instance can break other existing instances that share the same font family, weight etc.

Is this a bug? Or am I just not supposed to cache `SKTypeface` instances? I did not find any documentation suggesting that, and I read somewhere that caching is recommended for performance, though I can't find the source atm...

**Comment by Gillibald** [comment]
SKTypeface is cached by the font manager if you use `SKTypeface.FromFamilyName`. To avoid this you have to create a font manager per RenderContext. There might be some related fix in the current master that makes Dispose a no-op for these kinds of typefaces.

**Comment by Jonarw** [comment]
Ahh that makes a lot more sense to me now, thank you!

So I guess this also means that we don't really need to cache fonts ourselves, as the font manager does this anyway?

And by the way, updating to 1.68.3 totally seems to fix the issue.

**Comment by mattleibow** [comment]
Yep, this was fixed in #1224
