### ISSUE TITLE
System.DllNotFoundException: Unable to load shared library 'libSkiaSharp' or one of its dependencies error while publish the application throw azure app service on Linux 

### ISSUE THREAD

**Issue by ManishSync** [mono/SkiaSharp#1312]
**Description**

System.DllNotFoundException: Unable to load shared library 'libSkiaSharp' or one of its dependencies error while publishing the application throw azure app service on Linux. But the same sample doesn't produce any issues while publishing through azure app service. 

**Code**

**Expected Behavior**

There should not be an exception

**Actual Behavior**

System.DllNotFoundException: Unable to load shared library 'libSkiaSharp' or one of its dependencies error 

**Reproduction Link**
https://www.syncfusion.com/downloads/support/directtrac/general/ze/WebApplication1_(2)-1689441087

**Comment by mattleibow** [comment]
I am not sure what package that is, but it is not the correct package. The correct ID is "SkiaSharp.NativeAssets.Linux".

In addition, that package requires that `fontconfig` be installed.

![image](https://user-images.githubusercontent.com/1096616/83470131-c3be8180-a481-11ea-87cc-3c7332c3dd17.png)

**Comment by ManishSync** [comment]
Hi,

We have added the mentioned skiasharp packages in the same application, we have faced the same issue. And we have installed the libfontconfig package as mentioned below.

1. Under Development Tools Menu, Open the SSH and Click the go link.
2. From the terminal window, you can install the dependency packages. Use the following single command to install all dependencies packages.
apt-get update && apt-get -y install xvfb && apt-get -y install fontconfig && apt-get -y install libssl1.0-dev && apt-get -y install libx11-dev libx11-xcb-dev libxcb-icccm4-dev libxcb-image0-dev libxcb-keysyms1-dev libxcb-randr0-dev libxcb-render-util0-dev libxcb-render0-dev libxcb-shm0-dev libxcb-util0-dev libxcb-xfixes0-dev libxcb-xkb-dev libxcb1-dev libxfixes-dev libxrandr-dev libxrender-dev

After installing the packages, we have faced another exception like below.
System.TypeInitializationException: The type initializer for 'SkiaSharp.SKObject' threw an exception. ---> System.TypeInitializationException: The type initializer for 'SkiaSharp.SKTypeface' threw an exception. ---> System.EntryPointNotFoundException: Unable to find an entry point named 'sk_typeface_ref_default' in shared library 'libSkiaSharp'. at SkiaSharp.SkiaApi.sk_typeface_ref_default() at SkiaSharp.SKTypeface..cctor() --- End of inner exception stack trace --- at SkiaSharp.SKTypeface.EnsureStaticInstanceAreInitialized() at SkiaSharp.SKObject..cctor() --- End of inner exception stack trace --- at SkiaSharp.SKObject..ctor(IntPtr handle, Boolean owns) at SkiaSharp.SKWStream..ctor(IntPtr handle, Boolean owns) at SkiaSharp.SKFileWStream..ctor(String path) at WebApplication1.Controllers.HomeController.SkiaCreatePdf() 

Check the modified sample
https://www.syncfusion.com/downloads/support/directtrac/general/ze/WebApplication1-1451586919

**Comment by mattleibow** [comment]
Having a look at the project, you _just_ need the `SkiaSharp` (the managed part for .NET) and `SkiaSharp.NativeAssets.Linux` (the actual native engine) packages. `SkiaSharp.Linux` is not part of the SkiaSharp project and is managed by another individual - which has been superseded with `SkiaSharp.NativeAssets.Linux`. Also, no need for the `SkiaSharp.NativeAssets.Linux.NoDependencies` package either.

All you need is:

```xml
<PackageReference Include="SkiaSharp" Version="1.68.3" />
<PackageReference Include="SkiaSharp.NativeAssets.Linux" Version="1.68.3" />
```
