### ISSUE TITLE
[FEATURE] Nullable reference types

### ISSUE THREAD

**Issue by Ziriax** [mono/SkiaSharp#1316]
Currently SkiaSharp doesn't always throw exceptions, it maps closely to the native Skia library.

If that behavior is desired, it would be nice to annotate all possible null return values using C#'s nullable reference type feature.

Like this the user would get warnings when de-referencing potential null objects.

**Comment by mattleibow** [comment]
This is 100% something we should do. I am looking at doing this sometime soon-ish.

Not sure if a partial rollout will be more confusing, but this library is large enough for me to say that I am sure that some things may be missed or wrong. Hopefully, folks in the community could help out with some PRs just to annotate members/types.

**Comment by Ziriax** [comment]
I can certainly provide PRs for this,  in small steps, but I guess the code generator should also be modified for this?

**Comment by mattleibow** [comment]
The generator is mostly dumb, and is just used to generate the externs as some of the structs. But yes, the generator should probably be updated as well.

**Comment by Ziriax** [comment]
I was mentioning the generator, because the Skia docs in the C++ headers often have something like:

```
@return         created SkImage, or nullptr
```

So a generator could automatically annotate this by parsing the `@return` doc?

**Comment by mattleibow** [comment]
@Ziriax potentially, but it might be more work to actually write and verify than to just check and add manually.

There are a lot of members in SkiaSharp, but there are a significant set of overloads so this work is mainly manual.

**Comment by mattleibow** [comment]
But, this really needs to get done soon. I think I need to start with one file at a time.

**Comment by mattleibow** [comment]
Closing this in favor of #2055 to track each library and file in each.
