### ISSUE TITLE
[QUESTION] How to generate a native debug build?

### ISSUE THREAD

**Issue by Ziriax** [mono/SkiaSharp#1317]
I can't find any information on how to generate a debug build? 

Since Skia doesn't have a debug layer like DirectX, Vulkan or OpenGL, sometimes it is insanely hard to track down why a function returns `false` or `null`.  So having a debug build can be very handy.

Is it just a matter of passing `-c Debug` to `./bootstrapper.ps1`? That didn't seem to work for me, but maybe something else went wrong.

**Comment by Gillibald** [comment]
You need to set `is_official_build=false` https://github.com/mono/SkiaSharp/blob/master/native/windows/build.cake#L26

**Comment by Ziriax** [comment]
Thanks for that.

Would it make sense to have these set to `false` automatically when passing `Debug` to the `-c|--configuration` arg? The latter seems to specify the MSBuild configuration, somehow it feels logical that the .NET debug build would use native debug bits too?

**Comment by Ziriax** [comment]
Just in case other people need this, I also had to add the `clang` `cflag`  `-Wno-everything` in `externals\skia\gn\BUILD.gn`, otherwise the compiler choked on various warnings that were promoted to errors.

And instead of wasting hours to get this done, good advise might also be to read the Skia comments, in my case the reason for `ReadPixels` returning `false` was trying to convert from `kPremul` to `kOpaque`  , something that no-one asked for it seems, see below. Oh boy, now I realize how spoiled I was with the DirectX debug layer 😉 

```
/**
 *  Returns true if Skia has defined a pixel conversion from the |src| to the |dst|.
 *  Returns false otherwise.  Some discussion of false cases:
 *      We will not convert to kIndex8 unless it exactly matches the src, since color tables
 *      are immutable.
 *      We do not convert to kGray8 when the |src| is not kGray8 in the same color space.
 *      We may add this feature - it just requires some work to convert to luminance while
 *      handling color spaces correctly.  Currently no one is asking for this.
 *      We will not convert from kAlpha8 when the |dst| is not kAlpha8.  This would require
 *      inventing color information.
 *      We will not convert to kOpaque when the |src| is not kOpaque.  This could be
 *      implemented to set all the alpha values to 1, but there is still some ambiguity -
 *      should we use kPremul or kUnpremul color values with the opaque alphas?  Or should
 *      we just use whatever the |src| alpha is?  In the future, we could choose to clearly
 *      define this, but currently no one is asking for this feature.
 *      We will not convert to a particular color space if |src| is nullptr.  The color space
 *      conversion is not well-defined.
 */
static inline bool SkImageInfoValidConversion(const SkImageInfo& dst, const SkImageInfo& src) {
```

**Comment by mattleibow** [comment]
@Ziriax 

> Would it make sense to have these set to false automatically when passing Debug to the -c|--configuration arg? The latter seems to specify the MSBuild configuration, somehow it feels logical that the .NET debug build would use native debug bits too?

Thanks for the feedback, I'll update the cake tasks.

**Comment by Ziriax** [comment]
@mattleibow  Super! Please note that I also had to tweak the clang compiler settings, see my other comment (this might be because I'm using a newer version of LLVM than the M68 branch on which master is based)

**Comment by mattleibow** [comment]
Closing as this was added in #1418
