### ISSUE TITLE
SKTypeface.FromFamilyName throws ArgumentNullException when "familyNam

### ISSUE THREAD

**Issue by gentledepp** [mono/SkiaSharp#132]
In the documentation, it is written that the parameter "familyName" of the method SKTypeface.FromFamilyName may be null:
https://developer.xamarin.com/api/member/SkiaSharp.SKTypeface.FromFamilyName/p/System.String/SkiaSharp.SKTypefaceStyle/

However, calling

`var typeface = SKTypeface.FromFamilyName(null)`
results in an ArgumentNullException.

This happened on Windows.Forms version of SkiaSharp 1.53.0

When passing "string.Empty" it works just fine - that is our current workaround

**Comment by mattleibow** [comment]
@gentledepp Thanks for reporting this.

**Comment by mattleibow** [comment]
Fixed in https://github.com/mono/SkiaSharp/commit/4e67ffde755fc527296389a6d538c7a6e1c502c9
