### ISSUE TITLE
MeasureText works in UWP but causes Function Not Found exception in Android

### ISSUE THREAD

**Issue by joebustard** [mono/SkiaSharp#1324]
Calling  an SKPaint.MeasureText(mystring) or SKPaint.MeasureText( mystring, ref myrect)
works fine in a  UWP project, but switching to an Android build, an exception is raised saying that these functions can't be found.

There are some suggestions on Google that this general exception can be caused by cached versions of the packages being present. But I've tried clearing the caches, removing and restoring all the packages etc. It consistently comes back.

**Comment by mattleibow** [comment]
Closing this as this should not be happening anymore. The almost-recent updates to v2 should have done away with the potential "caching" of assemblies.
