### ISSUE TITLE
[QUESTION] How to add and deploy (lib)SkiaSharp to WPF .NET Framework project

### ISSUE THREAD

**Issue by Hylke-Atmos** [mono/SkiaSharp#1327]
Hi SkiaSharp team,

I have the following situation/problem.
We are trying to deploy a standalone Windows WPF desktop application based on .NET Framework 4.7.2. Which has a (indirect) dependency on SkiaSharp (developed in Visual Studio 2019). 
We have added/installed SkiaSharp using NuGet.

When we're deploying (using ClickOnce) the libSkiaSharp.dll is not being "published" nor is it added to the application manifest file.

We've tried deploying the application in many configuration including setting specific PlatformTarget settings, such as x86 and x64, both on the project as well as on the solution (as mentioned in many threads and issue reports). But non of the settings result in having the libSkiaSharp.dll in the deployment folder (default ClickOnce target being "app.publish") or being mentioned in the manifest file.

During development everything works fine since the libSkiaSharp.dll does exist in the "bin/Debug" (also in the "bin/Release") folder and no manifest file is used.

How do we properly add/setup SkiaSharp to a project in such a way that we can deploy our project with a native (Windows) ShiaSharp library (preferably using ClickOnce)?

Thank you for your help

**Comment by mattleibow** [comment]
Fixed in #1342 and on the preview feed as v2.80.0-preview.20
