### ISSUE TITLE
Canvas rotation does not work correctly

### ISSUE THREAD

**Issue by mihai-iancu** [mono/SkiaSharp#133]
I just started working with SkiaSharp and I have a problem with canvas rotation.
The code below generates the attached image:
```
using (SKSurface surface = SKSurface.Create(816, 1056, SKColorType.Bgra8888, SKAlphaType.Premul))
{
    SKCanvas canvas = surface.Canvas;
    SKMatrix m = SKMatrix.MakeTranslation(300, 400);
    canvas.Concat(ref m);

    m = SKMatrix.MakeScale(400, 200);
    canvas.Concat(ref m);

    using (SKPaint redPaint = new SKPaint())
    {
        redPaint.Color = new SKColor(255, 0, 0);
        canvas.DrawRect(SKRect.Create(0, 0, 1, 1), redPaint);
    }

    m = SKMatrix.MakeRotationDegrees(45);
    canvas.Concat(ref m);

    using (SKPaint bluePaint = new SKPaint())
    {
        bluePaint.Color = new SKColor(0, 0, 255);
        canvas.DrawRect(SKRect.Create(0, 0, 1, 1), bluePaint);
    }
}
```
![image-816x1056x4-red-blue](https://cloud.githubusercontent.com/assets/20994796/17629430/f85c8b1e-60c2-11e6-9bfa-36326a7f1a93.png)
The blue rectangle instead of being scaled like the red one, it is skewed and scaled equally on both axis.
I'm using the latest version 1.53.0.

**Comment by mattleibow** [comment]
I had a look at this and I think that you might be going about this wrong. The matrix transformations are applied to the entire canvas, not the next drawing. With this in mind, you should rotate the canvas and then scale it. 

That way, when you stretch the block horizontally, the horizontal-ness is actually rotated in line with the block.

```csharp
SKMatrix m = SKMatrix.MakeTranslation(300, 100);
canvas.Concat(ref m);

using (new SKAutoCanvasRestore(canvas, true))
{
    m = SKMatrix.MakeScale(400, 200);
    canvas.Concat(ref m);

    using (SKPaint redPaint = new SKPaint())
    {
        redPaint.Color = new SKColor(255, 0, 0);
        canvas.DrawRect(SKRect.Create(0, 0, 1, 1), redPaint);
    }
}

using (new SKAutoCanvasRestore(canvas, true))
{
    m = SKMatrix.MakeRotationDegrees(45);
    canvas.Concat(ref m);

    m = SKMatrix.MakeScale(400, 200);
    canvas.Concat(ref m);

    using (SKPaint bluePaint = new SKPaint())
    {
        bluePaint.Color = new SKColor(0, 0, 255);
        canvas.DrawRect(SKRect.Create(0, 0, 1, 1), bluePaint);
    }
}
```

I would also suggest that you use the `SKAutoCanvasRestore` type to auto-rollback transformations:

```csharp
using (new SKAutoCanvasRestore(canvas, true))
{
    // do you matrix transformations
}
```

The equivalent `Save`/`Restore code is:
```csharp
canvas.Save();
// do you matrix transformations
canvas.Restore();
```

**Comment by mattleibow** [comment]
The same thing happens with HTML Canvas: http://jsbin.com/soqigozule/edit?html,output
