### ISSUE TITLE
[FEATURE]  Add a few bindings...

### ISSUE THREAD

**Issue by AnarchyMob** [mono/SkiaSharp#1334]
Pleace add binding for method **SKImageFilter.CreateBlur** with TileMode argument, currently by default using ClampToBlack (Decal) tile mode, and also add binding for **SKSurface.Snapshot** with bounding rectangle. Thank you!

**Comment by Gillibald** [comment]
Contributions are welcome 😉

**Comment by mattleibow** [comment]
Moving this to v2.80 because it overlapped with a needed change.

**Comment by mattleibow** [comment]
Fixed in #1356 and #1357 

Thanks for the issue!
