### ISSUE TITLE
[BUG] SKCanvasView ignores WidthRequest?

### ISSUE THREAD

**Issue by LegendaryB** [mono/SkiaSharp#1335]
**Description**

It seems like the canvas view always use all of the horizontal space which is available. It seems like WidthRequest is ignored. Is this by design? So I need custom logic to work around it?

**Expected Behavior**

WidthRequest is honored.

**Actual Behavior**

WidthRequest is not honored

**Comment by mattleibow** [comment]
This all depends on the container. If it is in a `StackLayout`, then yes it fills the width. Unless you also set the `HorizontalOptions` to `Center`, `Start` or `End`. The default is to stretch.

Do you have an example of how you are using the canvas in the layout?

**Comment by LegendaryB** [comment]
Yeah seems correct. And also makes Sense. Was Not thinking about that

**Comment by mattleibow** [comment]
Has your issue been resolved? Cane we close this?

**Comment by LegendaryB** [comment]
Yeah it was resolved. I close it. Thank you
