### ISSUE TITLE
[BUG] SKBitmap.Copy and SKBitmap.ScalePixels are not working properly

### ISSUE THREAD

**Issue by MhAllan** [mono/SkiaSharp#1336]
**Description**
I am trying to scale a bitmap in and out multiple times. I wanted to keep quality so the successive scale operations will not accumulate bad quality as each scale will be generated from the original bitmap.

So I used SKBitmap.Copy to get the original bitmap, and SKBitmap.ScalePixels to scale it. but aparently SKBitmap.Copy is shallow and **SKBitmap.ScalePixels affects both the source and destination, both bitmaps will have the new size and quality!!**

**Code**
Attached Xamarin Forms Simple Demo

**Expected Behavior**
Successive scales not to cause accumulated bad quality

**Actual Behavior**
Original bitmap, it's copy, and the destination bitmap, all of them will get the same width and height of the destination in **ScalePixels** method, also accumulate bad quality as if any scaling is originated from a previous scale and applied to all bitmaps

**Basic Information**
Xamarin Forms 4.6.0.847
Android 9 and 10, Pixel Emulator
Windows 10 

[SkiaTest.zip](https://github.com/mono/SkiaSharp/files/4776780/SkiaTest.zip)

**Comment by MhAllan** [comment]
Apparently they share underlying arrays

**Comment by mattleibow** [comment]
Reoping this just in case it is a skia issue. The pixels should not be the same and it should be a full copy. I'll have a look and see what is happening.

**Comment by MhAllan** [comment]
great! I am happy this is not by design.

**Comment by Ziriax** [comment]
Yes, this is certainly a bug, writing to a bitmap should not alter the internally shared memory buffer, that is actually an implementation detail, conceptually each bitmap/image acts as a copy IMHO

**Comment by mattleibow** [comment]
I had a look at the code and I think I see what is happening here:

The `Bitmap` property setter overwrites both the `_original` _and_ the "working" `_bitmap`. When you then create the new bitmap with `Bitmap = new SKBitmap(newWidth, newHeight);`, you are actually overwriting everything.

You might be wanting to do this instead?

```csharp
_bitmap = new SKBitmap(newWidth, newHeight);
originalCopy.ScalePixels(_bitmap, SKFilterQuality.None);
```

Original source:

```csharp
public class ImageEditor : SKCanvasView
{
    SKBitmap _original;
    SKBitmap _bitmap;

    public SKBitmap Bitmap
    {
        get => _bitmap;
        set => _bitmap = _original = value;
    }

    protected override void OnPaintSurface(SKPaintSurfaceEventArgs e)
    {
        var canvas = e.Surface.Canvas;

        canvas.Clear();
        canvas.DrawBitmap(Bitmap, 0, 0);
    }

    public void Resize()
    {
        using (var originalCopy = _original.Copy())
        {
            var width = originalCopy.Width;
            var height = originalCopy.Height;

            var newWidth = width / 10;
            var newHeight = height / 10;

            Bitmap = new SKBitmap(newWidth, newHeight);

            originalCopy.ScalePixels(Bitmap, SKFilterQuality.None);

            InvalidateSurface();
        }
    }
}
```

**Comment by MhAllan** [comment]
😑 .. was long time, that moment when you get blank, sorry for bothering :(

**Comment by mattleibow** [comment]
No prob at all.
