### ISSUE TITLE
Could not AOT the assembly

### ISSUE THREAD

**Issue by roceh** [mono/SkiaSharp#134]
Minor issue which may not be SkiaSharps fault. But the Android AOT fails when processing the SkiaSharp assembly.

**Comment by migueldeicaza** [comment]
Android aot currently has a few limitations and bugs that we are working on (in Xamarin.android itself)

**Comment by mattleibow** [comment]
As this is a Xamarin.Android AOT bug, I have created a relevant issue here: https://bugzilla.xamarin.com/show_bug.cgi?id=43879

@roceh I am closing this one now, but if you wish to track the issue's progress, you can add yourself to the bugzilla CC list
