### ISSUE TITLE
[QUESTION] how to build static .a library for linux?

### ISSUE THREAD

**Issue by dotaheor** [mono/SkiaSharp#1340]
The page of building on Linux is helpful, but it only shows how to build dynamic libraries.
It looks the official arg `is_official_build` doesn't work for mono/skia.

**Comment by mattleibow** [comment]
What version are you looking to build? For the v1.68 series, this will involve you updating this file and change it to `static_library`
https://github.com/mono/skia/blob/v1.68.3/BUILD.gn#L1024

For the new v2.80 series (which I will recommend you using), this just involves the normal build, but additionally passing `is_static_skiasharp=true` to `args`.

**Comment by dotaheor** [comment]
sorry, I meant `is_component_build=false` doesn't work.

I checked out v2.80.0-preview.3, but it looks `is_static_skiasharp` is not recognized, and `is_component_build=false` still doesn't work.

**Comment by mattleibow** [comment]
That is correct, `is_component_build=false` will not work as that is just for the parts that make up libSkiaSharp. You will have to modify this line: https://github.com/mono/skia/blob/v1.68.3/BUILD.gn#L1024

But, try the preview 12 of skia, that should do it. You will also need to use the new managed files as well - on NuGet today.

**Comment by mattleibow** [comment]
The reason that I have separate build type for the SkiaSharp target is because if I do `is_component_build=true`, then all the variaous libraries are separate files and you will have to include all of them into the app.

**Comment by dotaheor** [comment]
Thanks very much the help.

I'm a little confused now. For the "the preview 12", I didn't find the "the preview 12" tag in the `mono/skia` project. Do you mean it is a tag in this `mono/SkiaSharp` project? However, I haven't found how to build `mono/SkiaSharp` on Linux.

What's the relation of the two projects? Do I need build `mono/skia` firstly, then build `mono/SkiaSharp`? If don't care about C#, then do I need to build the `mono/SkiaSharp` project?

Modifying the BUILD.gn file, from `shared_library` to `static_library`, works. Thanks!

**Comment by mattleibow** [comment]
I meant the preview 12 as in the tag: https://github.com/mono/skia/releases/tag/v2.80.0-preview.12
The reason being that I actually did just what you were trying to do in this commit, but with a option to do either: https://github.com/mono/skia/commit/a697b65c4ceedea7934a914cf66ad9c4552d6bd2

But, if changing the type on the gn works, then that should do it. 

The relationship between the two projects is that the SkiaSharp bit builds the native skia bit first, then the managed code. But, yes, if you aren't needing the C#, then just building skia is good.

What are you doing with the static library? Are you just using the headers in a C++ app?

**Comment by dotaheor** [comment]
Many thanks for the new information!

I misused the git command so that I failed to pull the preview.12 and preview.14 to local.

It looks when `is_component_build` is set `false`, both `libSkiaSharp.a` and `libSkiaSharp.so` are outputted. When `is_component_build` is set `false` and `is_static_skiasharp` is set `true`, then a `libskia.a` and a `libSkiaSharp.a` files are outputted. Are these expected behaviors? Should I use both of the two args?

> What are you doing with the static library? Are you just using the headers in a C++ app?

I plan to make a binding for another language.

**Comment by mattleibow** [comment]
Things may have changed, but I use `is_component_build` to make sure that all the intermediate libraries are `.a`, and then control the final `libSkiaSharp` with `is_static_skiasharp`. Even though `libskia.a` is there, that is not the real thing because it only has the bits from Google - although that might just be all you need. `libSkiaSharp.a` is all the extra APIs that are added to help with interop (https://github.com/mono/skia/tree/xamarin-mobile-bindings/include/xamarin)

**Comment by dotaheor** [comment]
Thanks very much for the valuable information!
Fell free to close this thread.
