### ISSUE TITLE
[BUG] Sweep Gradient doesn't honor caps when added to an arc

### ISSUE THREAD

**Issue by GrumpyCockatiel** [mono/SkiaSharp#1348]
**Description**

Sweep Gradient doesn't honor caps when added to an arc

			// set up the gradient colors
			SKColor[] colors = new SKColor[2] { this.ArcColor1.ToSKColor(), this.ArcColor2.ToSKColor() };

			float sweep = (this.Value1 % this.Value2 / 100F) * 360.0F;

			// draw the arc
			using (SKPath path = new SKPath())
			{
				using (SKPaint arcPaint = new SKPaint { Style = SKPaintStyle.Stroke, Color = this.ArcColor1.ToSKColor() })
				{
					arcPaint.StrokeWidth = this.ArcLineWidth;
					arcPaint.StrokeCap = SKStrokeCap.Round;
					arcPaint.IsAntialias = true;
					arcPaint.Shader = SKShader.CreateSweepGradient( this.Origin, colors, new Single[] {0, 1}, SKShaderTileMode.Clamp, 0, sweep );

					// create an arc to sweep along
					path.AddArc( this.OuterRect, 0, sweep );
					canvas.DrawPath( path, arcPaint );
				}
			}

The cap at the start of the arc should be the color of the starting color defined at position 0

Starting cap is the color at the ending position. Play around with cap styles and TileMode and there is no good solution.

**Basic Information**

- Version with issue:  1.68.3
- Last known good version:  none
- IDE:  isual Studio for Mac
- Platform Target Frameworks: 
  - Android:  
  - iOS:  
- Target Devices:   
  - iPhone 11 
**Screenshots**

![Screen Shot 2020-06-23 at 4 44 48 PM](https://user-images.githubusercontent.com/17300872/85468028-88d7d700-b571-11ea-9185-d1ad1de6c67e.png)

Or allow setting caps on both start and end independent of the other

**Comment by mattleibow** [comment]
I think this is because the cap extends past the angles. Your angle is from 0, which is directly up - the "line" the bad gradient makes. One solution is to make it start at -10 or something, but that is not so great. I would suggest making the tile mode be `SKShaderTileMode.Repeat` which will "stretch" the color to the cap.

**Comment by GrumpyCockatiel** [comment]
Yea 2 minutes after I posted this I had that thought about that. Sadly it didn't work either - stayed the same. Looks like the sweep gradient can't handle starting negative angles correctly?
arcPaint.Shader = SKShader.CreateSweepGradient( this.Origin, colors, new Single[] { 0, 1 }, SKShaderTileMode.Clamp, -45, 45 );
Thanks. I'll keep looking

**Comment by mattleibow** [comment]
Does `SKShaderTileMode.Repeat` not work either?

**Comment by GrumpyCockatiel** [comment]
Yea I tried all the combinations of the cap styles and tile mode. Nothing worked unless I missed it. However, with A LOT more code, I was get pretty close to what I needed EXCEPT rotations greater than 2Pi that end in the first quadrant (eg 114 below) have a minor issue which is where the negative start angle would be nice. But still able set caps end independent of each other would be awesome too - for now just have to draw over them.
Thanks

![Simulator Screen Shot - iPhone 8 - 2020-06-24 at 12 35 19](https://user-images.githubusercontent.com/17300872/85608162-6b127c80-b61a-11ea-8871-afadcf72b0ee.png)
![Simulator Screen Shot - iPhone 8 - 2020-06-24 at 12 36 16](https://user-images.githubusercontent.com/17300872/85608193-72d22100-b61a-11ea-89e4-3c9e1bc069b7.png)
![Simulator Screen Shot - iPhone 8 - 2020-06-24 at 12 36 46](https://user-images.githubusercontent.com/17300872/85608211-7796d500-b61a-11ea-88fa-caa854825658.png)
![Simulator Screen Shot - iPhone 8 - 2020-06-24 at 12 37 19](https://user-images.githubusercontent.com/17300872/85608231-7c5b8900-b61a-11ea-9181-29855139937e.png)
![Simulator Screen Shot - iPhone 8 - 2020-06-24 at 12 37 43](https://user-images.githubusercontent.com/17300872/85608275-85e4f100-b61a-11ea-8301-f34c2bdcfdb0.png)

**Comment by mattleibow** [comment]
Not sure why negative numbers are supported for the angles, but there is a way to draw an arc like you want. Just rotate the canvas and then draw.

```cs
canvas.Clear(SKColors.DarkGray);

// set up the gradient colors
SKColor[] colors = new SKColor[2] {  SKColors.LightGreen , SKColors.Green };

float sweep = 0.3f * 360.0F;
var r = SKRect.Create(50, 50, 500, 500);
// draw the arc
using (SKPath path = new SKPath())
{
	using (SKPaint arcPaint = new SKPaint { Style = SKPaintStyle.Stroke, Color = SKColors.Blue })
	{
		arcPaint.StrokeWidth = 50;
		arcPaint.StrokeCap = SKStrokeCap.Round;
		arcPaint.IsAntialias = true;
		arcPaint.Shader = SKShader.CreateSweepGradient(new SKPoint(200, 200), colors, new Single[] { 0, 1 }, SKShaderTileMode.Clamp, 0, sweep);

		// ROTATE BACK 90*
		canvas.RotateDegrees(-90, r.MidX, r.MidY);

		// create an arc to sweep along
		path.AddArc(r, 0, sweep);
		canvas.DrawPath(path, arcPaint);
	}
}
```

**Comment by GrumpyCockatiel** [comment]
Eiiiie yea, I got blinded by having already rotated the canvas once, forgot I can keep doing it as needed.
Thanks, this will probably get me there.
