### ISSUE TITLE
[BUG] Ascent value is changed while compare in Windows and Linux Docker environment

### ISSUE THREAD

**Issue by MadhanKumarasamy** [mono/SkiaSharp#1350]
**Description**

I have checked ascent value Calibri font in Windows environment is 10.9 pt and then checked ascent value in Linux Docker environment is 9 pt. Well, the difference is 1.9 pt and I have checked with lastest skiasharp version but the issue is not resolved. Kindly let me know how to get the same ascent value for both Windows and Linux Docker environment.

**Code**

```
SKPaint sKPaint = new SKPaint();
sKPaint.Typeface = SKTypeface.FromFamilyName("Calibri", SKFontStyleWeight.Normal, SKFontStyleWidth.Normal, SKFontStyleSlant.Upright);
System.Diagnostics.Debug.WriteLine(sKPaint.FontMetrics.Ascent);
```

**Expected Behavior**

10.9

**Actual Behavior**

9

**Basic Information**

- Version with issue:  1.59.3
- IDE:  Visual Studio 2019
- Platform Target Frameworks: .NET Core 3.0
  - Windows OS:  Linux Docker

**Comment by Gillibald** [comment]
You are just not using the same physical font. Better load the typeface via stream.

**Comment by MadhanKumarasamy** [comment]
> You are just not using the same physical font. Better load the typeface via stream.

Hi @Gillibald ,

But I have physical copy the Calibri font to the Linux container.

**Comment by Gillibald** [comment]
Is it properly registered with Fontconfig? Otherwise, it will not be found. Also, make sure that `sKPaint.Typeface.Name` matches the right name.

**Comment by MadhanKumarasamy** [comment]
> Is it properly registered with Fontconfig? Otherwise, it will not be found. Also, make sure that `sKPaint.Typeface.Name` matches the right name.

Hi @Gillibald ,

I am properly copying the font to Linux Docker and I have checked the `sKPaint.Typeface.Name`. please find the screenshot below. 
<img width="234" alt="fontName" src="https://user-images.githubusercontent.com/48026813/85704801-44c60d00-b6fe-11ea-9fb9-544c0d3df2ae.png">

**Comment by mattleibow** [comment]
I also saw this, almost all the values are the same except that one. When measuring characters, I also notice a 1px width difference in some characters.

However, this might just be the case of different engines for text. Windows uses DirectWrite and Linux uses FontConfig.

**Comment by MadhanKumarasamy** [comment]
Hi,

I have checked the `sKPaint.FontMetrics.Leading` value for Calibri font in both environment.
**In Windows:**
- Ascent value - 10.47. 
- Leading value - 0.

**In Linux Docker** 
- Ascentvalue - 8.25.
- Leading value - 2.42.

Then added the leading value and ascent value from the Linux docker and it is equal to the windows ascent value. All I want is the same ascent value as Windows. So, I just want to know, can we add the leading value to the ascent value?

**Comment by Gillibald** [comment]
Just use `HarfBuzzSharp` and you get consistent results

**Comment by mattleibow** [comment]
This seems very much related to #1390 

> I am having a look at this and it appears that v1.68.3 did not have floating point widths on Windows either. Seems the new functionality is to use floating points on Windows, but kept the original logic on Linux.

However, the reverse is true for the Ascent. Seems Windows had the Ascent of only integers, and Linux used floating points ¯\_(ツ)_/¯

But, seems setting `IsLinearText = true` makes everyone work?

**Comment by mattleibow** [comment]
Seems some logic changed from sub-pixel to linear logic in a few places...

m68: https://github.com/google/skia/blob/chrome/m68/src/ports/SkFontHost_win.cpp#L718
m80: https://github.com/google/skia/blob/chrome/m80/src/ports/SkFontHost_win.cpp#L742

**Comment by Gillibald** [comment]
Thanks for having a look at this. Will try that out. Fine for me if it is just a flag that has to be set for better customization.

**Comment by VijayRM** [comment]
@mattleibow & @Gillibald - Still this issue exist in v2.80.2 version. Could you please let me know whether this issue has resolved or any changes required in our side?

**Comment by VijayRM** [comment]
@mattleibow & @Gillibald - Could you please look into this ?

**Comment by mattleibow** [comment]
@VijayRM could you create a new issue?

Also, could you mention the fonts you are using, the platform versions, and anything else that will help.

In addition, could you let us know of a few things in this issue you have tried? Maybe some code that you are using to load the font. Is the font leading correctly?

**Comment by VijayRM** [comment]
@mattleibow - The original issue reported in this thread was not resolved. Do we want to create new one ?
https://github.com/mono/SkiaSharp/issues/1350#issue-644666536

The ascent value for Calibri font is differs between Windows & Linux Docker environment. Could you please check this ?

Code Snippet:

```
SKPaint sKPaint = new SKPaint();
sKPaint.Typeface = SKTypeface.FromFamilyName("Calibri", SKFontStyleWeight.Normal, SKFontStyleWidth.Normal, SKFontStyleSlant.Upright);
System.Diagnostics.Debug.WriteLine(sKPaint.FontMetrics.Ascent);
```


The below code is what we are exactly using in our product:

```

    public class SkPaintExtension : SKPaint
    {
        public SkPaintExtension(Stream stream, float fontSize) : base()
        {
            this.TextSize = fontSize;
            this.IsAntialias = true;
            this.TextEncoding = SKTextEncoding.Utf8;
            //As per the SkiaSharp team suggestion, enabled SubpixelText property to get valid size in Linux.
            this.SubpixelText = true;
            MemoryStream tempStream = new MemoryStream();
            stream.CopyTo(tempStream);
            stream.Position = 0;
            tempStream.Position = 0;
            this.Typeface = SKTypeface.FromStream(tempStream);
        }
    }

 class Program
    {
        
        static void Main(string[] args)
        {
            SkPaintExtension skExtension = new SkPaintExtension(new MemoryStream(File.ReadAllBytes(basePath + @"Fonts\calibri.ttf")), 12);
            Console.WriteLine("Ascent - " + skExtension.FontMetrics.Ascent);
            Console.WriteLine("Descent - " + skExtension.FontMetrics.Descent);
            Console.WriteLine("Leading - " + skExtension.FontMetrics.Leading);
}
}
```

**I am using same font file in both platforms.**

If you required more details, please let me know. I will share all the possible details.

**Comment by VijayRM** [comment]
Could you please provide update on this ?

**Comment by ManishSync** [comment]
Any update on this
