### ISSUE TITLE
[BUG] Invalid dependency

### ISSUE THREAD

**Issue by VladislavAntonyuk** [mono/SkiaSharp#1353]
**Description**

Severity	Code	Description	Project	File	Line	Suppression State
Warning	NU1603	SkiaSharp.Views.Forms.GTK 2.84.0-pr.1321.3 depends on Xamarin.Forms (>= 4.6.0.772-pr.1321.3) but Xamarin.Forms 4.6.0.772-pr.1321.3 was not found. An approximate best match of Xamarin.Forms 4.6.0.772 was resolved.	1	

The same happens for WPF

**Comment by mattleibow** [comment]
Thanks for reporting this. I noticed it a few versions back and fixed it, but have not released it since it wasn't too critical. But, I think it is now time to update that feed with all the versions.

**Comment by VladislavAntonyuk** [comment]
> Are you using the `SKRuntimeEffect`?

no

**Comment by mattleibow** [comment]
Ah, in that case it might be better to use the v2.80 series.

The v2.84 is still early, and the `-pr.xxxx` series are the PR builds. For normal use, it is better to stick to the `-preview`, `-alpha`, `-beta` and `-rc` versions. Use the `-pr.xxxx` when you actually want that version.

I'll be pushing the latest versions of all the things soon, so it is likely going to be a `2.80.0-preview.17` or a bit later

**Comment by mattleibow** [comment]
I wrote a quick wiki describing the version numbers just in case the future world needs it: https://github.com/mono/SkiaSharp/wiki/Versioning

**Comment by mattleibow** [comment]
OK, so this is still happening... Because I fixed the _samples_ not the actual packaging. Thanks for opening this, and I'll fix it now 🤦
