### ISSUE TITLE
DrawImage on Alpha8 surface

### ISSUE THREAD

**Issue by mihai-iancu** [mono/SkiaSharp#137]
I create a surface with SKColorType.Alpha8. I can draw vector graphics on it just fine but if I try to draw an image with SKColorType.Gray8 nothing is displayed. 
If I change the surface type to SKColorType.Bgra8888 the image shows ok.
The code to draw the image (Windows Forms app):
```
int imageWidth = 100;
int imageHeight = 100;

// A black square
byte[] imageData = new byte[imageWidth * imageHeight];
GCHandle imageHandle = GCHandle.Alloc(imageData, GCHandleType.Pinned);
IntPtr imageDataPtr = Marshal.UnsafeAddrOfPinnedArrayElement(imageData, 0);

SKImageInfo imageInfo = new SKImageInfo(imageWidth, imageHeight, SKColorType.Gray8, SKAlphaType.Opaque);
using (SKImage img = SKImage.FromPixels(imageInfo, imageDataPtr, imageWidth))
{
    canvas.DrawImage(img, new SKRect(0, 0, imageWidth, imageHeight));
}

imageHandle.Free();

```
Is this a limitation of the Alpha8 surface?

**Comment by mattleibow** [comment]
@mihai-iancu I may not me doing this right, but I think I can draw the image. Maybe your canvas and the image are the same color?

Here is what I did: created a Alpha8 surface, painted it a light, translucent blue (which is translucent gray) and then draw a black image on it. Seems to work.

```csharp
using (var surface = SKSurface.Create(200, 200, SKColorType.Alpha8, SKAlphaType.Premul))
{
    var canvas = surface.Canvas;

    // draw a translucent blue, which should translate into translucent black
    canvas.DrawColor(new SKColor(0, 127, 255, 127));

    int imageWidth = 100;
    int imageHeight = 100;

    // A black square
    byte[] imageData = new byte[imageWidth * imageHeight];
    GCHandle imageHandle = GCHandle.Alloc(imageData, GCHandleType.Pinned);
    IntPtr imageDataPtr = Marshal.UnsafeAddrOfPinnedArrayElement(imageData, 0);

    SKImageInfo imageInfo = new SKImageInfo(imageWidth, imageHeight, SKColorType.Gray8, SKAlphaType.Opaque);
    using (SKImage img = SKImage.FromPixels(imageInfo, imageDataPtr, imageWidth))
    {
        canvas.DrawImage(img, new SKRect(0, 0, imageWidth, imageHeight));
    }

    imageHandle.Free();

    // save the image
    using (var stream = File.OpenWrite(@"C:\Users\mattl\Documents\Snapshot.png"))
        surface.Snapshot().Encode().SaveTo(stream);
}
```

**Comment by mihai-iancu** [comment]
My mistake, my Alpha8 surface was initialized to 255 in my particular situation, so obviously nothing else could be added to it.
But in your code above if you add this part (create a pixel checkers board):
```
byte[] imageData = new byte[imageWidth * imageHeight]; 
for (int i = 0; i < imageData.Length; i++)
{
    imageData[i] = (byte)i;
}

```
The output will still be a solid black square. Is there something that I'm missing?

**Comment by mattleibow** [comment]
@mihai-iancu I had a look and this is expected. The surface is a set of alpha values (0-255) and no color. The image is a set of gray values (0-255) with no alpha. The image has no alpha, or rather an alpha of opaque (255). Thus when you draw that image onto the surface, it just draws the alpha component - a solid block. 

You can test this by changing the surface to a RGB version and then the image will be a solid block of some set of gray.
