### ISSUE TITLE
[BUG] SKCanvas.DrawText seems different than text in XAML elements.

### ISSUE THREAD

**Issue by roonius** [mono/SkiaSharp#1372]
**Description**

SKCanvas.DrawText seems rendering text slightly different than text in XAML elements.

![image](https://user-images.githubusercontent.com/7190183/86263941-86f1c180-bbca-11ea-9218-f80d9376df69.png)

Upper 'EURUSD' is xaml control
Lower EURUSD is SKCanvas.DrawText output

if zoomed in - one can see different shading/coloring of pixels.
Same Font, Height, Color is used in both cases

**Expected Behavior**

Text would appear the same

- Version with issue:  2.80

   - UWP:   16299  

**Screenshots**

![image](https://user-images.githubusercontent.com/7190183/86264429-2f078a80-bbcb-11ea-90fa-0df212e7ed80.png)

**Comment by Gillibald** [comment]
You simply can't expect that two different font rendering stacks produce the same results.

**Comment by mattleibow** [comment]
Also, SkiaSharp has several properties on the SKPaint object, such as hinting, lcd, and others to control the style.

It is highly likely that UWP has its own combination.

But, @Gillibald is correct. They may not be exactly the same due to the rendering process.

**Comment by mattleibow** [comment]
Closing tis as SkiaSkarp uses a different rendering engine on most platforms and also uses different drawing configurations by default.

To get exact matches, you may have to use different shaping and paint properties. I am not sure offhand what they are.
