### ISSUE TITLE
[BUG] Windows App Certification process failed while publishing UWP app in X64 architecture

### ISSUE THREAD

**Issue by VijayRM** [mono/SkiaSharp#1373]
**Description**

We are using SkiaSharp in our application as a dependent. While publishing the package created with X64 architecture, the app failed in Windows Certification due to libSkiaSharp.dll. The same app passed test, if it is created with x86 architecture.

**Expected Behavior**

Should pass Windows Certification test.

**Actual Behavior**

Shows below error.
![MicrosoftTeams-image](https://user-images.githubusercontent.com/50352419/86319548-5fded280-bc52-11ea-97cf-fbd55f47d77f.png)

**Basic Information**

- Version with issue:  1.68.3 & 2.80.0-preview.3

**Comment by mattleibow** [comment]
That is just a bug in the Windows SDK:

> **Known Issues**
> Not quite an issue, but still something to be aware of: https://github.com/microsoft/microsoft-ui-xaml/issues/1446
> > API __CxxFrameHandler4 in vcruntime140_1_app.dll is not supported for this application type. libGLESv2.dll calls this API.
> > API __CxxFrameHandler4 in vcruntime140_1_app.dll is not supported for this application type. libSkiaSharp.dll calls this API.

**Comment by mattleibow** [comment]
Closing this as this is an issue with the WACK tool and will be fixed in newer SDKs. This error can safely be ignored as the online portal does not have this issue.
