### ISSUE TITLE
[BUG] SKBitmap.Decode(codec)  return  null

### ISSUE THREAD

**Issue by 3400442579** [mono/SkiaSharp#1378]
**Description**

SKCodec codec = SKCodec.Create(@"C:\Users\jxw\Desktop\png\1.png");
SKBitmap sKBitmap = SKBitmap.Decode(codec);

sKBitmap 的值等于null

System.Drawing
Bitmap bitmap = new Bitmap(@"C:\Users\jxw\Desktop\png\1.png");
bitmap 的值是正常的

**Code**

 SKCodec codec = SKCodec.Create(@"C:\Users\jxw\Desktop\png\1.png");
 SKBitmap sKBitmap = SKBitmap.Decode(codec);

Bitmap bitmap = new Bitmap(@"C:\Users\jxw\Desktop\png\1.png");
            

**Expected Behavior**

**Actual Behavior**

**Basic Information**

- Version with issue: SkiaSharp  1.68.3
- Last known good version:  
- IDE:  Visual Studio
- Platform Target Frameworks: Windows  10
  

**Screenshots**

**Reproduction Link**

 
[1.zip](https://github.com/mono/SkiaSharp/files/4867606/1.zip)

**Comment by mattleibow** [comment]
Did you figure out what was wrong?
