### ISSUE TITLE
[BUG]  Unable to add SKiaSharp to the GAC

### ISSUE THREAD

**Issue by brianlagunas** [mono/SkiaSharp#1379]
**Description**

I am trying to install SkiaSharp into the CAG for an internal WPF application.  However, libSkiaSharp cannot be added to the GAC becuase it does not have an assembly manafest.

**Code**

![image](https://user-images.githubusercontent.com/835562/86440925-93f4da80-bcc8-11ea-8975-6b162d87f530.png)

**Expected Behavior**

Add SkiaSharp to the GAC

**Actual Behavior**

Cannot be added to the GAC

**Basic Information**

- Version with issue:  1.68.3
- IDE: Windows CLI
- Platform Target Frameworks: 
  - Windows Classic:  Windows 10 - .NET 7.2

**Comment by mattleibow** [comment]
libSkiaSharp is a native C++ library. I don't think it is meant to be able to go there?

**Comment by brianlagunas** [comment]
Well, I'm not sure if embedding the native code in an assembly would be considered

https://docs.microsoft.com/en-us/cpp/dotnet/how-to-add-native-dll-to-global-assembly-cache?view=vs-2019

**Comment by brianlagunas** [comment]
I found a work-around.
