### ISSUE TITLE
[BUG] Invalid measuring width for Cambodian text

### ISSUE THREAD

**Issue by MadhanKumarasamy** [mono/SkiaSharp#1380]
**Description**

I am using SkiaSharp for measuring the given text. so I have given the Cambodian text as input but it measuring width is higher than the GDI measuring width. How to get the same GDI measuring width. 

**Code**

              
               string text = "លិខិតស្ថានភាពពាក្យបណ្តឹង";
                float fontsize = 12;

                //SkiaSharp Measurement
                SKImageInfo info = new SKImageInfo(120, 120);
                float skiaMeasurement = 0;
                using (SKSurface surface = SKSurface.Create(info))
                {
                    SKCanvas canvas = surface.Canvas;
                    canvas.Clear(SKColors.White);
                    using (SKPaint paint = new SKPaint())
                    {
                        paint.Typeface = SKTypeface.FromFile(@"C:\Users\MadhanKumarasamy\Downloads\Khmer.ttf");
                        paint.Color = SKColors.Black;
                        paint.IsAntialias = true;
                        paint.TextSize = fontsize;
                        paint.SubpixelText = true;
                        paint.TextAlign = SKTextAlign.Left;
                        paint.TextEncoding = SKTextEncoding.Utf8;
                        SKRect rect = new SKRect();
                        skiaMeasurement = paint.MeasureText(text, ref rect);
                        Console.WriteLine("SKia Width = " + rect.Width);
                    }
                }

                //GDI Measurement
                Bitmap bitmap = new Bitmap(540, 720);
                Graphics graphics = Graphics.FromImage(bitmap);
                // Create string to draw.
                String drawString = text;
                graphics.FillRectangle(Brushes.White, new System.Drawing.Rectangle(0, 0, (int)540, (int)720));
                // Create font and brush.
                Font drawFont = new Font("Khmer", fontsize, FontStyle.Regular, GraphicsUnit.Point);
                SolidBrush drawBrush = new SolidBrush(Color.Black);
                StringFormat drawFormat = new StringFormat(StringFormat.GenericTypographic);
                //remove the linelimit flag from create stringformat object.
                //The behavior of the linelimit flag is “only entire lines are laid out in the formatting rectangle”, 
                //By default layout continues until the end of the text, or until no more lines are visible as a result of clipping”.
                drawFormat.FormatFlags &= ~StringFormatFlags.LineLimit;
                drawFormat.FormatFlags |= StringFormatFlags.MeasureTrailingSpaces;
                drawFormat.FormatFlags |= StringFormatFlags.NoClip;
                graphics.PageUnit = GraphicsUnit.Point;

                drawFormat.Trimming = StringTrimming.Word;
                // Set format of string.
                float width = graphics.MeasureString(drawString, drawFont, new PointF(0, 0), drawFormat).Width;
                Console.WriteLine("GDI Width = " + width);

**Expected Behavior**

SKia Width = 145.3125
GDI Width = 145.3125

**Actual Behavior**

SKia Width = 170.4766
GDI Width = 145.3125

**Basic Information**

- Version with issue:  1.68.1
- IDE:  Visual Studio 2017
- Platform Target Frameworks: .Net core 2.1

**Comment by Gillibald** [comment]
Skia isn't performing any text shaping that is required by many non Latin writing systems. To get the expected result you have to shape the text via HarfBuzzSharp.

@mattleibow What can we do to avoid these reportings?

**Comment by mattleibow** [comment]
We probably need a bit better docs on text or a better issue template. I'll get things together for this so at least we can reduce the issues of this type.

However, I think I also need to probably promote/suggest the use of https://github.com/toptensoftware/RichTextKit which is by far the best text layout option that we have. Not only basic text, but it supports all the actual feature of text drawing. Wrapping, styles, font, layout, BiDi and far more.

So I think the default recommendation would be to use RichTextKit?
