### ISSUE TITLE
[BUG] System.EntryPointNotFoundException: Unable to find an entry point named 'sk_managedstream_set_delegates'

### ISSUE THREAD

**Issue by Mikhailkour** [mono/SkiaSharp#1385]
**Description**
Avalonia UI application is failed at start with an error:
Unhandled exception. System.TypeInitializationException: The type initializer for 'SkiaSharp.SKAbstractManagedStream' threw an exception. ---> System.EntryPointNotFoundException: Unable to find an entry point named 'sk_managedstream_set_delegates' in shared library libSkiaSharp.

The library libSkiaSharp was built for the aarch64 platform accoring to the next recipes: 
https://gist.github.com/jclapis/d907127dc031ad351b943df7917cd753
https://github.com/mono/SkiaSharp/issues/453#issuecomment-450497754

**Expected Behavior**
Avalonia UI application is started successfully.

**Basic Information**

- Version with issue:  v1.68.3, v1.68.2.1
- Platform Target Frameworks: .Net Core 3.1
- Linux:  Embedded Linux imx8mmevk 4.19.35 aarch64 GNU/Linux
- Target Devices:   imx8m

**Comment by mattleibow** [comment]
Those instructions seem to be missing the tag number. You must make sure to check out the correct tag for the version you are using.

However, if you are not restricted, you can check out the brand new builds that will soon be released: https://github.com/mono/SkiaSharp/pull/1382

This makes use of the new v2 preview packages which are available in the preview feed right now. It will not work with the older v1 versions. The exact package version to use is in the description.

You can also talk to "jmacato" in https://github.com/mono/SkiaSharp/pull/1382 as he confirmed the packages are working.

**Comment by mattleibow** [comment]
Closing this issue as ARM64 support will be in v2.80 stable. Just waiting for CI to finish up and then I'll be releasing to NuGet.
