### ISSUE TITLE
SKBitmap.GetPixels method returns invalid pointer

### ISSUE THREAD

**Issue by mihai-iancu** [mono/SkiaSharp#139]
I need access to the bytes of an SKBitmap.
The code below always returns width * height * 4 as the value of pixelsPtr:
```
using (SKBitmap bmp = new SKBitmap(width, height, SKColorType.Bgra8888, SKAlphaType.Premul))
{
    IntPtr pixelsPtr = IntPtr.Zero;
    bmp.LockPixels();
    bmp.GetPixels(out pixelsPtr);
    bmp.UnlockPixels();
}

```

**Comment by mattleibow** [comment]
@mihai-iancu That is correct, the `out` parameter is the length. The return value is the actual pointer to the image data.

The bitmap also has several other properties and methods that may be useful:
 - `SKColor[] Pixels { get; set; }`
 - `byte[] Bytes { get; }`
 - `IntPtr GetPixels (out IntPtr)`
 - `SKColor GetPixel (int, int)`

**Comment by mattleibow** [comment]
The `GetPixels` method and `Bytes` property return just the image data. In order to make use of the data for saving as image files, `SKImage.FromBitmap` and then `SKImage.Encode` needs to be used instead.
