### ISSUE TITLE
[FEATURE] Metal APIs

### ISSUE THREAD

**Issue by mattleibow** [mono/SkiaSharp#1391]
**Is your feature request related to a problem? Please describe.**
We need to add the metal APIs available on Apple hardware.

**Comment by mattleibow** [comment]
Looking at the APIs, it appears there are 2 ways to use Metal, from a `CAMetalLayer`:
https://github.com/google/skia/blob/chrome/m85/include/core/SkSurface.h#L304

And a `MTKView`:
https://github.com/google/skia/blob/chrome/m85/include/core/SkSurface.h#L331

The `CAMetalLayer` part was added in m80, and `MTKView` (sadly) in m81. Just one away.

I will bind the layer one and see how that goes. I want to get m84 /m85 finished soon (#1321) and then we can add the view one.

**Comment by sparkie108** [comment]
Will this enable screen drawing using the Display P3 color space?  The current OpenGL view only seems to support sRGB.

**Comment by mattleibow** [comment]
Looking at the implementation, support for tvOS was not thought of. 

What I will do is merge this with iOS and macOS support. Then I need to create a PR upstream with tvOS support and then cherry pick that down. There are a few places that need some work, and I do not want to delay this any longer.

**Comment by mattleibow** [comment]
I opened an issue to see what the upstream reception of tvOS bits are: https://bugs.chromium.org/p/skia/issues/detail?id=11250

**Comment by mattleibow** [comment]
Opened an issue to track the feature and demand: https://github.com/mono/SkiaSharp/issues/1601
