### ISSUE TITLE
SKBitmap.Decode on ios optimized png images

### ISSUE THREAD

**Issue by roceh** [mono/SkiaSharp#140]
1.49.x used to work ok on optimized png images on ios - i.e. reading pngs from the bundle. 1.53.x does not, it appears the new SKCodec does not like these images. Disabling the png optimization works around the issue.

**Comment by mattleibow** [comment]
@roceh Thanks for reporting this. It appears to be a Skia bug, since Chrome can't even load the images. I have [asked on the forums](https://groups.google.com/forum/#!topic/skia-discuss/nbRQI7pfqbw), and we might have to wait for a fix.

As soon as I know, I will update this issue. I can't "roll back" since the old way of loading has been totally removed from the code. It used to use `SKImageDecoder`, but that was replaced with a supposedly better `SKCodec`.

**Comment by roceh** [comment]
Reading a little more I think the optimizations make the png non standard, but I think the android build process does similar things so that's probably why it worked at all in the past.

I found this somewhat old article on what happens:
http://iphonedevelopment.blogspot.co.uk/2008/10/iphone-optimized-pngs.html

**Comment by mattleibow** [comment]
@roceh From Google:

> The file that you've labeled as compressed.png is an "Apple optimized png".  It's a proprietary png format only supported by iOS.  We don't have plans to support this - Chrome and Firefox also don't support it.
> 
> A few major differences between "Apple optimized png" and regular png is that Apple pngs are stored BGRA (instead of RGBA) and are premultiplied.  This is to optimize the speed of decoding/loading of the image on iOS.  As far as I can tell, this doesn't really have anything to do with compression size.  Are the two images you sent identical (I can't open compressed.png)?  If so, it's worth mentioning that compressed.png is actually a larger file.
> 
> Below is a good resource explaining the iOS png.  And there's a lot more information out there if you search "Apple optimized png".
> http://iphonedevwiki.net/index.php/CgBI_file_format
> 
> And here's a guide for how to convert Apple pngs to regular pngs:
> https://developer.apple.com/library/ios/qa/qa1681/_index.html

I will close this issue on the reason that we can't do anything until Google does something.

**Comment by mattleibow** [comment]
Just for reference, PNG compression is disabled by:

 - unchecking the "Optimize PNG images" in the "iOS Build" section of the project options
 - unchecking the "Optimize" item in the "iOS Optimizations" section of the file properties in the IDE

<img width="300" src="https://user-images.githubusercontent.com/1096616/29880011-fdc3fe54-8da6-11e7-8ee9-70d112fee1dd.png">
<img width="600" src="https://user-images.githubusercontent.com/1096616/29880012-fe3192b6-8da6-11e7-8dd1-e38485f90884.png">

**Comment by ylatuya** [comment]
Hi,
This just happened to me and I couldn't  find anything in the docs, it could be nice to have it properly documented in t[he platform specific documentation](https://docs.microsoft.com/en-us/xamarin/graphics-games/skiasharp/platform)
