### ISSUE TITLE
[FEATURE] Allow building just a single external

### ISSUE THREAD

**Issue by Ziriax** [mono/SkiaSharp#1403]
For testing, I often build just a single external, e.g. Windows.

Instead of listing all externals that should be skipped, it would be handy to specify just the externals to build.

E.g. in the `externals.cake`:

```CS
    if (JUST_EXTERNALS.Length > 0)
        return JUST_EXTERNALS.Contains(platform);
```

On could then build with 

`./bootstrapper.ps1 --target=libs --justExternals=windows`

**Comment by Ziriax** [comment]
Oh btw, it seems `--skipExternals` doesn't accept multiple tokens anymore, this now gives the error:

```
 ./bootstrapper.ps1 --target=libs --skipExternals="linux,macos"
Preparing to run build script...
Running build script...
More than one build script specified.
For usage, use parameter --help
```

Changing the cake code to split by semicolon instead of comma, makes it work again.

**Comment by mattleibow** [comment]
This is already there with the format `--target=externals-<native>`. Where `<native>` matches the name of the "native" folder.

For example, to build just iOS, do `externals-ios`. 

This is generated from the folder names:
https://github.com/mono/SkiaSharp/blob/master/cake/externals.cake#L7-L18

**Comment by mattleibow** [comment]
But the semicolon issue might break macos. I would have it split on both `;` and `,`. Then i should work everywhere.

**Comment by Ziriax** [comment]
Oh nice. Didn't think of that. Then please ignore my PR.

**Comment by mattleibow** [comment]
No prob. Thanks for the issues and general seconds set of eyes.
