### ISSUE TITLE
Wrap SkPaint.setSubpixelText

### ISSUE THREAD

**Issue by tdenniston** [mono/SkiaSharp#141]
It'd be nice to wrap `SkPaint::setSubpixelText()` and/or `SkPaint::setLCDRenderText()` (I don't actually know the difference between these two). Without setting these flags to true to enable subpixel rendering, text rendered by SkiaSharp will appear slightly blurry.

Here's a side-by-side comparison of how text with greyscale antialiasing (the Skia default) compares with Windows ClearType subpixel rendering. The top text "No Subpixel" is rendered with SkiaSharp. The bottom text "Subpixel" is rendered with WPF, which by default uses ClearType (a subpixel rendering technique).

![subpixel](https://cloud.githubusercontent.com/assets/934815/17828270/efbe97d4-665a-11e6-882a-651fcc9804c8.png)

With my LCD monitor, the "Subpixel" text appears sharper than the "No Subpixel" text. You may have to right click and view the image in full size to see the difference, as Github scales down the preview to fit within the issue text, and the relevant detail may be lost in the raster scaling process.

**Comment by mattleibow** [comment]
@tdenniston I added a few extra members to `SKPaint`: https://github.com/mono/SkiaSharp/commit/fc5e7f04d74144da025e953c79b07143d14fb007

I am doing a build and hope to get it out soon. To be really honest, I wasn't able to spot a difference with these options, but maybe it is just my combination of features.

**Comment by charlesroddie** [comment]
@tdenniston Does this work for you?
