### ISSUE TITLE
[QUESTION] SetScaleTranslate is obsolete

### ISSUE THREAD

**Issue by wegascee** [mono/SkiaSharp#1415]
On building with SkiaSharp v. 2.80.1 I get the following warning:

>Warning	CS0612	'SKMatrix.SetScaleTranslate(float, float, float, float)' is obsolete
 
This is also written in the [docs](https://docs.microsoft.com/en-us/dotnet/api/skiasharp.skmatrix.setscaletranslate?view=skiasharp-1.68.1), but it is still used in the [cropping example](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/graphics/skiasharp/bitmaps/cropping):

    // Calculate a matrix transform for displaying the cropping rectangle
    SKMatrix bitmapScaleMatrix = SKMatrix.MakeIdentity();
    bitmapScaleMatrix.SetScaleTranslate(scale, scale, x, y);

Is there a replacement and which one is it?

**Comment by mattleibow** [comment]
Thanks for raising this. It should have been a Create* variant. Just like you see in the docs, people create a new object and then call set. It was to reduce that into a single create.

I think I forgot to add it.
