### ISSUE TITLE
Easy to implement improvements in SKCanvasViewRenderer and SKGLViewRenderer

### ISSUE THREAD

**Issue by lothargrieb** [mono/SkiaSharp#1423]
Please overwrite the CreateNativeControl methods in the derived classes and create the native control without reflection.
Applications with many controls on slow devices will be thankful for this. Reflection on Android for example costs time.

**Comment by mattleibow** [comment]
Are you talking about the `Activator`. We can do that.

**Comment by lothargrieb** [comment]
Perfect Matthew, thx

**Comment by lothargrieb** [comment]
![image](https://user-images.githubusercontent.com/7022575/88258921-8cba5e80-ccc1-11ea-8ba8-ffa00cced8ff.png)
![image](https://user-images.githubusercontent.com/7022575/88259232-2da91980-ccc2-11ea-9485-1c2f2f30ea6c.png)
Just for your information. Each single element in the screenshots is an SKCanvasView implementation with a decoupled drawing model for the user interface using fluent syntax...The SkiaSharp team did a good job to be able to implement performant xamarin applications. We currently support Windows and Android....
