### ISSUE TITLE
[QUESTION] Where to find methods from SkiaApi

### ISSUE THREAD

**Issue by matibak** [mono/SkiaSharp#1428]
Xamarin Developer here. I am trying to figure out why `M187.64 365.39a223.41 223.41 0 01-28.95-1.89 10 10 0 012.62-19.92 203.26 203.26 0 0052.39 0 10 10 0 012.6 19.93 222.59 222.59 0 01-28.66 1.88z` svg path results in null pointer exception when using FFImageLoading library for drawing SVGs. During the debugging process I stopped at call to this line in `SkiaApi.cs`:

```
[DllImport("@rpath/libSkiaSharp.framework/libSkiaSharp", CallingConvention = CallingConvention.Cdecl)]
[return: MarshalAs(UnmanagedType.I1)]
internal static extern bool sk_path_parse_svg_string(IntPtr cpath, [MarshalAs(UnmanagedType.LPStr)] string str);
```
Where can I find the name of the method called in underlying Skia library when `sk_path_parse_svg_string` is called?

Thank you in advance

**Comment by mattleibow** [comment]
The code for the extern are found in this library
https://github.com/mono/skia

Specifically:
https://github.com/mono/skia/blob/xamarin-mobile-bindings/src/c/sk_path.cpp#L244

**Comment by mattleibow** [comment]
A bull will be returned if there was an error parsing the path.

I also see a rogue "a" at position 14, or near there if I could wrong.

**Comment by matibak** [comment]
Thank you for your answer! Indeed deleting `365.39a223.41 223.41` solves the problem - do you know why does it break the code?

**Comment by mattleibow** [comment]
The `a` is invalid SVG path data.

Check out this for lots more info: https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/d#Path_commands
