### ISSUE TITLE
SKPaint.Color property on Android emulators

### ISSUE THREAD

**Issue by ollira** [mono/SkiaSharp#143]
All the examples, I have checked, appear to draw the correct graphics colors on an Android emulator. However, Visual Studio shows strange values on SKPaint Color property.

Sample code

        public static void TestPaintColor(SKCanvas canvas, int width, int height)
        {
            SKColor color = SKColors.Red;
            SKPaint paint = new SKPaint();
            paint.Color = color;

            if (!paint.Color.Equals(color))
            {
                System.Diagnostics.Debug.WriteLine("SKPaint.Color issue (" + paint.Color + " != " + color + ")");
            }
        }

VIsual Studio output:
 
[0:] SKPaint.Color issue (#a3c3f220 != #ffff0000)

Regards,
Olli Raisa

**Comment by mattleibow** [comment]
Hi @ollira, thanks for taking the time to report this.
I have resolved the issue, which was us trying to marshal a uint32 from C++ as a struct in C#.

**Comment by leonardors** [comment]
I am having the same problem with version 1.5.8, on simulator and device.

var paint = new SKPaint();
var color = SKColor.Parse("#ff0000");

System.Diagnostics.Debug.WriteLine("CurrentColor: {0}", paint.Color);
System.Diagnostics.Debug.WriteLine("NewColor: {0}", color);
paint.Color = color;
System.Diagnostics.Debug.WriteLine("Result: {0}", paint.Color);

Result:
CurrentColor: #8ef0eee8
NewColor: #ffff0000
Result: #955dfae4

**Comment by mattleibow** [comment]
This was fixed again in #284 
The did seemed to have been Odeon in another commit.
