### ISSUE TITLE
[BUG] Exception occurs while try to measure the Unicode Text

### ISSUE THREAD

**Issue by MadhanKumarasamy** [mono/SkiaSharp#1432]
**Description**

I am using a SkiaSharp library for measuring the text and I have recently upgraded the SkiaSharp library version [2.80.0]. Then exception occurs while measuring the Unicode text and this exception are not comes from the older version [1.59.3].
kindly provide your suggestion to resolve this issue.

**Code**
```
string text1 = "\ud83c";
                string text2 = "\ud835";
                float fontsize = 12;
                float skiaMeasurement = 0;
                using (SKPaint paint = new SKPaint())
                    {
                        paint.Typeface = SKTypeface.FromFamilyName("Arial");
                        paint.Color = SKColors.Black;
                        paint.IsAntialias = true;   
                        paint.TextSize = fontsize;
                        paint.SubpixelText = true;
                        paint.TextAlign = SKTextAlign.Left;
                        paint.TextEncoding = SKTextEncoding.Utf8;
                        SKRect rect = new SKRect();
                        skiaMeasurement = paint.MeasureText(text2, ref rect);
                        Console.WriteLine("SKia Width = " + skiaMeasurement);
                    }
```

**Expected Behavior**

SKia Width = 9

**Actual Behavior**

Exception occurs.

**Basic Information**

- Version with issue:  2.80.0
- Last known good version:  1.59.3
- IDE:  Visual Studio 2017
- Platform Target Frameworks: .NET Core 2.1
  

**Exception Screenshots**

![image](https://user-images.githubusercontent.com/48026813/88637704-2033cb00-d0d8-11ea-9b18-80b4466ad959.png)

**Comment by mattleibow** [comment]
Thanks for reporting this, I'll have a look.

What happens if you measure an ascii character such as "a"?

**Comment by MadhanKumarasamy** [comment]
> Thanks for reporting this, I'll have a look.
> 
> What happens if you measure an ascii character such as "a"?

I have checked for ascii character and it's measuring are working properly like older version.

**Comment by mattleibow** [comment]
Thanks for reporting this. I see there was a fix just after the version we are using. I have cherry picked it and will be in the next release.

I also want to mention, you may already know, that is an invalid character. It is part of a surrogate pair, and you only have the one. 

https://github.com/google/skia/commit/5da8e55bf4f399bd1c5b8378dcdbfb197b85d16c
