### ISSUE TITLE
[BUG] Font issue

### ISSUE THREAD

**Issue by DawidBester** [mono/SkiaSharp#1433]
**Description**
I upgraded my app to 2.80.1 and then to 2.80.2-preview.9, and the way fonts work on Android seem to have changed. 
Also tested on iOS 13.6 and fonts work as expected.

**Code**

I determine the typeface as follows:

                var sampleChar = 'A';
                var fontManager = SKFontManager.Default;
                var typeface = fontManager.MatchCharacter(sampleChar);

                if (typeface == null)
                {
                    foreach (var font in fontManager.FontFamilies)
                    {
                        if (font.ToLower().Contains("helvetica"))
                        {
                            typeface = fontManager.MatchFamily(font, SKFontStyle.Normal);
                            break;
                        }
                    }
                }
                
                _textPaint.Typeface = typeface;

And then drawtext as follows:

```csharp
canvas.DrawText(textString,
    -info.Width / (float) _canvasScale /
    2 + offset, // + textString.Length * _textPaint.TextSize/2 /(float)scale ,
    -info.Height / (float) _canvasScale / 2 + _textPaint.TextSize * 1.1f,
    _textPaint);
```

**Expected Behavior**

Text should display the same as on 1.68.3

**Actual Behavior**
Typeface on Android change and text no longer displays as intended

**Basic Information**

- Version with issue:  2.80.1 and then to 2.80.2-preview.9 
- Last known good version: 1.68.3 
- IDE:  Microsoft Visual Studio 2019 Version 16.6.5 
- Platform Target Frameworks: 
  - Android: Android 10 API Level 29   

- Target Devices: 

Pixel 2 Emulator running Android 10 
Samsung S8 running Android 9  
  
<details>
  <summary>Detailed IDE/OS information (click to expand)</summary>
  
```

Xamarin   16.6.000.1064 (d16-6@b03f31e)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer   16.6.0.318 (remotes/origin/d16-6@66afc5421)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin Templates   16.6.40 (1f1466f)
Templates for building iOS, Android, and Windows apps with Xamarin and Xamarin.Forms.

Xamarin.Android SDK   10.3.1.4 (d16-6/3a10de9)
Xamarin.Android Reference Assemblies and MSBuild support.
    Mono: 165f4b0
    Java.Interop: xamarin/java.interop/d16-6@2cab35c
    ProGuard: xamarin/proguard/master@905836d
    SQLite: xamarin/sqlite/3.31.1@49232bc
    Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-6@bfb66f3


Xamarin.iOS and Xamarin.Mac SDK   13.18.3.2 (ce0cc74)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.

```
</details>

**Screenshots**

Android Text display on 2.80.1 and then to 2.80.2-preview.9
![image](https://user-images.githubusercontent.com/33708055/88864891-6f096e00-d25a-11ea-9f69-abf58ae37c66.png)

Android Text display on 1.68.3
![image](https://user-images.githubusercontent.com/33708055/88865113-0969b180-d25b-11ea-80d2-182128b99d2f.png)

**Reproduction Link**

**Comment by mattleibow** [comment]
I am not able to reproduce this... I tried a few strings and all the fonts, but no luck.

Are you able to attach an app with this happening? 

| Emulator (Pixel 2 v10) | Razor Phone (9.0) |
| :---------: | :------------: |
| ![image](https://user-images.githubusercontent.com/1096616/88974216-92630600-d2b8-11ea-9ab9-8176ed42c6ed.png) | ![image](https://user-images.githubusercontent.com/1096616/88974531-0e5d4e00-d2b9-11ea-97ca-b7547b927d69.png) |

**Comment by DawidBester** [comment]
Sample app attached.
[PlotTextTest.zip](https://github.com/mono/SkiaSharp/files/5004374/PlotTextTest.zip)

With 2.80.2-preview.9 sample app output as follows on Pixel 2 Emulator running Android 10 and Samsung S8 running Android 9:
![image](https://user-images.githubusercontent.com/33708055/88986871-4c458b00-d328-11ea-8e77-0dc7f19e6b81.png)

With 1.68.3 sample app output as follows on Pixel 2 Emulator running Android 10 and Samsung S8 running Android 9:
![image](https://user-images.githubusercontent.com/33708055/88987684-d5f65800-d32a-11ea-99d5-074e02e26dcc.png)


FYI: While creating the attached sample also experience [https://github.com/mono/SkiaSharp/issues/1395](url) and had to install SkiaSharp package in addition to SkiSharp.View.Forms for 2.80.2-preview.9 to function without crashing. Crash as follows:


**System.DllNotFoundException:** 'libSkiaSharp.so assembly:<unknown assembly> type:<unknown type> member:(null)'

07-31 12:36:17.577 E/mono    ( 8291): 
07-31 12:36:17.577 E/mono    ( 8291): Unhandled Exception:
07-31 12:36:17.577 E/mono    ( 8291): System.DllNotFoundException: libSkiaSharp.so assembly:<unknown assembly> type:<unknown type> member:(null)
07-31 12:36:17.577 E/mono    ( 8291):   at (wrapper dynamic-method) Android.Runtime.DynamicMethodNameCounter.7(intptr,intptr,intptr)
07-31 12:36:17.577 E/mono    ( 8291):   at (wrapper native-to-managed) Android.Runtime.DynamicMethodNameCounter.7(intptr,intptr,intptr)
07-31 12:36:17.578 E/mono-rt ( 8291): [ERROR] FATAL UNHANDLED EXCEPTION: System.DllNotFoundException: libSkiaSharp.so assembly:<unknown assembly> type:<unknown type> member:(null)
07-31 12:36:17.578 E/mono-rt ( 8291):   at (wrapper dynamic-method) Android.Runtime.DynamicMethodNameCounter.7(intptr,intptr,intptr)
07-31 12:36:17.578 E/mono-rt ( 8291):   at (wrapper native-to-managed) Android.Runtime.DynamicMethodNameCounter.7(intptr,intptr,intptr)

**Comment by mattleibow** [comment]
I am looking at the issue, and I think it _cause_ is due to the small font size and the new way skia calculates things.

Google has this problem too: https://fiddle.skia.org/c/de373b99b78721d7fb64461f695ffd0b

I will communicate with them and see what the fix is.

**Comment by mattleibow** [comment]
I started a discussion about this: https://groups.google.com/g/skia-discuss/c/Qx7brrWyv9Y

Seems to be just Android and Linux - or FreeType.

**Comment by daltonks** [comment]
@DawidBester I came across this same issue. Switching to HarfBuzzSharp and using `canvas.DrawShapedText` fixed it for me. Maybe it'll help in your case too?

https://www.nuget.org/packages/HarfBuzzSharp

**Comment by DawidBester** [comment]
@daltonks Thanks, your workaround works! 

Just added SkiaSharp.HarfBuzz 2.80.2-preview.9 with canvas.DrawShapedText to the sample app, and the text displays correctly on an Android 10 Emulator. 

The preference is to try to avoid adding another NuGet with code changes in the production app, but this will be my fallback.

![image](https://user-images.githubusercontent.com/33708055/89087341-1c5dbc80-d3e8-11ea-9ee0-ea066077c288.png)
