### ISSUE TITLE
Missing method "SKPath.Contains(x, y)"

### ISSUE THREAD

**Issue by Majchrzak** [mono/SkiaSharp#144]
The following method is missing on SKPath "SKPath.Contains(x, y)". 

See: `bool SkPath::contains(SkScalar x, SkScalar y) const` https://github.com/google/skia/blob/44df651ebefc284acc2f66425dff3ea0b0e14b36/src/core/SkPath.cpp#L3146

**Comment by mattleibow** [comment]
Thanks for creating an issue. I have added this in 2293db42a8a990ac38addf9058a0ba625c8ce1eb
