### ISSUE TITLE
[BUG] SKSwapChainPanel not working with Uno WASM

### ISSUE THREAD

**Issue by MakanWG** [mono/SkiaSharp#1444]
**Description**

When trying to use SKSwapChainPanel in both my own app and the Uno samples on this repo, nothing is displayed and we get an error in the browser console.

***Repro Steps***
- Open SkiaSharp\samples\Gallery\Uno\SkiaSharpSample.sln
- Replace the project dependencies by nuget dependencies in the Wasm project
- Set the wasm project as starter project
- Run the samples
- Swith to OpenGL using the top right icon

**Expected Behavior**

Using the GPUView shouldn't crash, and produce the same results as UWP.

**Actual Behavior**

The sample panel becomes blank and the following error is displayed in the console

```
Uncaught Error: System.NullReferenceException: Object reference not set to an instance of an object.
  at :63559/SkiaSharp.Vie…ilename unknown>:0 
  at :63559/SkiaSharp.Vie…ilename unknown>:0 
  at SkiaSharp.Views.UWP.SKSwapChainPanel+SKSwapChainPanelJsInterop.Uno.Foundation.Interop.IJSObjectMetadata.InvokeManaged (:63559/System.Object…m.String parameters) <0x6e7bf20 + 0x00026> in <filename unknown>:0 
  at Uno.Foundation.Interop.JSObject.Dispatch (:63559/System.String…m.String parameters) [0x0009b] in D:\a\1\s\src\Uno.Foundation\Interop\JSObject.wasm.cs:47 
    at Object.call_method (dotnet.js:12321)
    at Function.dispatchMethod (dotnet.js:12395)
    at Function.dispatch (Uno.UI.js:2421)
    at SkiaSharp.Views.Uno.Wasm.js:62
```

**Basic Information**

- Version with issue:  2.80.2-preview.18
- Last known good version:  
- IDE:  Visual Studio
- Platform Target Frameworks: 
  - WebAssembly (Uno)
- Target Devices:   
  - Browser (Firefox and Chredge)

**Screenshots**

**Reproduction Link**

We can reproduce the issue using the Uno Samples.

**Comment by mattleibow** [comment]
Thanks for reporting this. I just noticed this last night when I tried to use the view. It was working...

**Comment by mattleibow** [comment]
Pushed this out as preview 19. Thanks for reporting.
