### ISSUE TITLE
[BUG] Android SKCanvas DrawTextOnPath kerning different/wrong in 2.80 compared to 1.68

### ISSUE THREAD

**Issue by IainS1986** [mono/SkiaSharp#1448]
Upgrading from 1.68.3 to 2.80 is showing text not rendering right when using DrawTextOnPath in Android.

**Skia Sharp 2.80.1 in Core project**
**Skia Sharp Viws 2.80.1 in Android project**

I'm not using a custom font/typeface, i'm just generating a SKPaint for the text like so...

    LabelText = new SKPaint() 
    { 
        Style = SKPaintStyle.Fill, 
        Color = TextColor, 
        TextSize = LabelTextSize, 
        IsAntialias = true, 
        TextAlign = SKTextAlign.Center 
    };

Normal **canvas.DrawText(text, p, paint);** works fine, but **canvas.DrawTextOnPath(text, path, offset, paint);** is coming out with wrong kerning on the text and the font appears different too.

Below is a screen shot. All the text is rendering with the same paint above, the text in the top left using **canvas.DrawText()** and the rest of the text using **canvas.DrawTextOnPath()**. Note the decimal points and the uniform spacing of all characters

![Screenshot_20200806-114807](https://user-images.githubusercontent.com/16193452/89525322-eb153000-d7dd-11ea-998b-5e2a69dc46b5.png)

iOS renders fine.
Android used to render fine in 1.68.3 (can try and get a screenshot if you'd want of the before).

Do I now need to load a typeface in properly?

**Comment by mattleibow** [comment]
Can you try the latest preview? I believe this was a bug that was fixed in there.

**Comment by IainS1986** [comment]
Awesome 👍  thanks for the fast response.

Upgraded Droid only to have **SkiaSharp.Views 2.80.2-preview.19** and thats resolved the issue!

**Comment by mattleibow** [comment]
Awesome right back! Thanks for the feedback.
