### ISSUE TITLE
[BUG] SKMatrix values are changed in the SkiaSharp higher version

### ISSUE THREAD

**Issue by MadhanKumarasamy** [mono/SkiaSharp#1451]
**Description**

I am using SkiaSharp library to translate the text from the SKMatrix values and I have recently upgraded the SkiaSharp library version [2.80.2-preview.19]. Then I try to translate the text in the Higher version and its text width different from the older version[2.80.0]. kindly provide your suggestion to resolve this issue.

**Code**

```
SKMatrix tempMatrix = SKMatrix.MakeIdentity();
                tempMatrix.Values = new float[] { 1, 0, 0,0, 1, 0, 0, 0, 1 };
                SKMatrix.RotateDegrees(ref tempMatrix, 0);
                tempMatrix.SetScaleTranslate(1.2f, 1.0f, 0, 0);
                Console.WriteLine(tempMatrix.Values[0]);
```

**Expected Behavior**

1.2

**Actual Behavior**

1

**Basic Information**

- Version with issue:  2.80.2-preview.19
- Last known good version:  2.80.0
- IDE:  Visual Studio 2017
- Platform Target Frameworks: .NET Core 2.1

**Comment by mattleibow** [comment]
Thanks for reporting this, I have a fixing building and I will ensure it reaches the next preview: #1452

**Comment by mattleibow** [comment]
Thanks for this issue. I have fixed the issue and merged the changes. I will update NuGet as soon as CI is done.
