### ISSUE TITLE
Unable to load DLL libSkiaSharp the specified module could not be found.

### ISSUE THREAD

**Issue by SampleCoordinator** [mono/SkiaSharp#1459]
**Description**

Win Forms Application
Debug/Build Any/CPU
I installed DYMO.Connect.SDK v1.3.1.115. It auto installs SkiaSharp & SkiaSharp.Views v1.68.0 and other dependicies.
When I debug i can print labels just fine. However when I build the program and run it, i get the following error.

"Error
Unable to load DLL 'libSkiaSharp': the specified module could not be
found.(Exception from HRESULT: 0x8007007E)"

**Code**

                        Imports DymoSDK.Implementations
                        Dim dymoSDKLabel As DymoSDK.Implementations.DymoLabel

                        Private Sub PrintLabelButton_Click(sender As Object, e As EventArgs) Handles PrintLabelButton.Click
                        Dim gen As New QRCodeGenerator
                        Dim data = gen.CreateQrCode(sid, QRCodeGenerator.ECCLevel.Q)
                        Dim qrCode As New Base64QRCode(data)
                        Dim base64qrcode As String = qrCode.GetGraphic(20)
                        Dim LabelTextObject As DymoSDK.Interfaces.ILabelObject
                        Dim LabelQRObject As DymoSDK.Interfaces.ILabelObject
                        Dim SelectedPrinter As String = "DYMO LabelWriter 450"
                        Dim copies As Integer = 1
                        Dim barcodeGraphsQuality As Boolean = True
                        dymoSDKLabel = New DymoLabel()
                        dymoSDKLabel.LoadLabelFromFilePath("C:\Users\" & WindowsUsername &"\Documents\DOCS\test.dymo")
                        LabelTextObject = dymoSDKLabel.GetLabelObject("TextObject")
                        dymoSDKLabel.UpdateLabelObject(LabelTextObject, rowID)
                        LabelQRObject = dymoSDKLabel.GetLabelObject("ImageObject")
                        dymoSDKLabel.UpdateLabelObject(LabelQRObject, base64qrcode)
                        DymoPrinter.Instance.PrintLabel(dymoSDKLabel, SelectedPrinter, copies, barcodeGraphsQuality)
                        End Sub

**Basic Information**

- Version with issue:  
- IDE:  
- Platform Target Frameworks: 

  

  

**Screenshots**
![image](https://user-images.githubusercontent.com/67664572/89848744-c4d3f500-db3b-11ea-88d8-c0c7fa76eb3d.png)

**Reproduction Link**

**Comment by mattleibow** [comment]
Can you try upgrading SkiaSharp to v2? It should have a whole bunch of improvements for this.

**Comment by SampleCoordinator** [comment]
I upgraded to V2.80.0. 

I got the following error when attempting to install the Build application"+ Strong name signature not valid for this assembly OpenTK.GLControl.dll."

**Comment by mattleibow** [comment]
I am unable to reproduce.

I created a new VB forms app, added the nuget and ran some SkiaSharp code. Ran just fine for me.

**Comment by SampleCoordinator** [comment]
Looks like error is coming from DYMO then.
