### ISSUE TITLE
[QUESTION] Is there a generic way to create a list of items to draw?

### ISSUE THREAD

**Issue by hansmbakker** [mono/SkiaSharp#1462]
I see there are different types of renderable objects in SkiaSharp like SKBitmap, SKTextBlob and SKVertices but I don't see them inheriting from a base class or interface that represents something that can be displayed on screen. I see they inherit from SKObject but that seems to also represent non-display objects.

I'm wondering whether there is a way to reference some basic properties or methods of SkiaSharp renderable objects in a generic way.

What I am looking for is types like `SKBitmap` and `SKTextBlob` having some basic methods like `GetBounds()` or `ApplyTransformation()` on a common base class, so that you could mix them and iterate over them.

The usecase for this is that I'm trying to create an "image composer" with several image layers (1 renderable item per layer) which allows the user to select the active layer and drag the renderable item of the active layer around.

The MVVM viewmodel for the page would contain a collection of image layers, like:
```csharp
ObservableCollection<LayerModel> Layers {get;set;}
LayerModel SelectedLayer {get;set;}
```

The `LayerModel` class could then have
```csharp
string Name {get;set;}
ISKRenderable RenderItem {get;set;}
```

**Comment by hansmbakker** [comment]
My workaround would be to use the anonymous `object` type for the `RenderItem` on the `LayerModel` class and checking its type using e.g. [pattern matching](https://docs.microsoft.com/en-us/archive/msdn-magazine/2019/may/csharp-8-0-pattern-matching-in-csharp-8-0#the-evolution-of-pattern-matching-in-c-80) to decide how to process each item.

**Comment by mattleibow** [comment]
This is quite an interesting topic. I don't think there is a way to do this now, however, this might be something that you can do with an implicit operators to convert from any types you are interesting in to a container type.

This should be good because the actual type are classes, so object is fine and there is no boxing. I am using a struct because I can avoid an allocation. Maybe this gives some ideas?

I could have gone with inheritance and all that, but this is quite simple and does not add overhead. You can even add additional implicit/explicit conversions back to the skia objects if you need to access them. But, at least you only have this switch and drawing code in a single location.

```csharp
public readonly struct SKRenderable
{
    private readonly object skiaObject;
    private readonly Action<SKRenderable, SKCanvas, float, float, SKPaint> renderImpl;

    public SKRenderable(SKBitmap bmp)
    {
        skiaObject = bmp;
        renderImpl = RenderBitmap;
    }

    public SKRenderable(SKImage img)
    {
        skiaObject = img;
        renderImpl = RenderImage;
    }

    public SKRenderable(SKTextBlob text)
    {
        skiaObject = text;
        renderImpl = RenderTextBlob;
    }

    public float Width =>
        skiaObject switch
        {
            SKBitmap bmp => bmp.Width,
            SKImage img => img.Width,
            SKTextBlob text => text.Bounds.Width,
            _ => 0
        };

    public float Height =>
        skiaObject switch
        {
            SKBitmap bmp => bmp.Height,
            SKImage img => img.Height,
            SKTextBlob text => text.Bounds.Height,
            _ => 0
        };

    public void Render(SKCanvas canvas, float x, float y, SKPaint paint = null) =>
        renderImpl(this, canvas, x, y, paint);

    public static implicit operator SKRenderable(SKBitmap bmp) =>
        new SKRenderable(bmp);

    public static implicit operator SKRenderable(SKImage img) =>
        new SKRenderable(img);

    public static implicit operator SKRenderable(SKTextBlob text) =>
        new SKRenderable(text);

    private static void RenderBitmap(SKRenderable renderable, SKCanvas canvas, float x, float y, SKPaint paint) =>
        canvas.DrawBitmap((SKBitmap)renderable.skiaObject, x, y, paint);

    private static void RenderImage(SKRenderable renderable, SKCanvas canvas, float x, float y, SKPaint paint) =>
        canvas.DrawImage((SKImage)renderable.skiaObject, x, y, paint);

    private static void RenderTextBlob(SKRenderable renderable, SKCanvas canvas, float x, float y, SKPaint paint) =>
        canvas.DrawText((SKTextBlob)renderable.skiaObject, x, y, paint);
}
```

**Comment by hansmbakker** [comment]
Thanks so much for thinking along!

Inheritance might make this easier but with what is available now this looks really helpful!

**Comment by mattleibow** [comment]
I did think about inheritance, but was considering the additional allocation for each type. This might not be too bad, and might make the code less "big switch".
However, there are only like 5 different drawables (surface, drawable, image, bitmap and picture), so all the extra plumbing is just a waste.

But again, totally up to how you work - there is no right way.

**Comment by hansmbakker** [comment]
out of interest: why would implementing a common interface or base class require additional allocation? Do you mean that adding "alias" properties /methods to the existing classes would cause the object size to be larger?

**Comment by mattleibow** [comment]
Ah, I might have said it wrong. I mean using a class to wrap the objects in the case of my snippet - so I went for a struct.

In the case of a base interface inside the SkiaSharp library, that has popped into my mind from time to time, but I thought it wasn't really useful/needed.
However, it seems that it is. Maybe we should reopen this issue and update the title/description in the form of a request for some API that would be useful. What properties, what features. Adding an interface with 2 properties might be useful, but not particularly so. But, if we get a decent API set of a few properties and methods, then maybe this becomes a feature.

Or, you can create a new issue so we can start again, linking to this one. Then we can flesh out a decent API set.

**Comment by hansmbakker** [comment]
Sounds good; however I'm going on vacation soon; I can think along when I am back.

I got a prototype of an "image composer" working yesterday with lasers of [`TouchManipulationBitmap`](https://github.com/xamarin/xamarin-forms-samples/blob/master/SkiaSharpForms/Demos/Demos/SkiaSharpFormsDemos/Transforms/TouchManipulationBitmap.cs).

I'm using a `ListView` control bound to the layers (`ObservableCollection<TouchManipulationBitmap>`) and the selected layer gets the touch input. In the Paint event I render the layers on top of each other.

Ideally, that class would be generic so that you could also manipulate other items (SVG or something else).
I modified the class (and related classes) so that they accept UWP `PointerPressed` etc events.

**Comment by hansmbakker** [comment]
I'm back, but not sure where to start?

**Comment by mattleibow** [comment]
Thanks for that. I re-read it and see if I can get you some feedback/solutions that will make things easier to work with.
