### ISSUE TITLE
[BUG] When deploying on Azure, error MSB4066: The attribute "Kind" in element <NativeReference> is unrecognized.

### ISSUE THREAD

**Issue by jsgoupil** [mono/SkiaSharp#1466]
**Description**
When deploying on Azure, WebApp, git deploy (windows machine), the following error shows up:

```
MSBuild auto-detection: using msbuild version '14.0'
packages\SkiaSharp.2.80.1\build\net462\SkiaSharp.targets(12,109): error MSB4066: The attribute "Kind" in element &lt;NativeReference> is unrecognized.
```

This is the line.
```
<NativeReference Include="$(MSBuildThisFileDirectory)..\..\runtimes\osx\native\libSkiaSharp*.dylib" Kind="Dynamic" Visible="false" />
```

This is strange to happen on Azure?
Should I be setting the `ShouldIncludeNativeSkiaSharp` property to `false`?

Last person who changed this file is @mattleibow 

**Basic Information**

- Version with issue:  2.80.1
- Last known good version:  Never deployed before
- IDE:  Visual Studio
- Platform Target Frameworks: My framework is 4.7.1. It uses the targets 4.6.2.

**Comment by mattleibow** [comment]
I think this is probably related to this issue:
https://developercommunity.visualstudio.com/content/problem/1142283/elements-still-appear-in-the-ide-even-though-they.html

The actual code for this is: https://github.com/mono/SkiaSharp/blob/master/binding/SkiaSharp/nuget/build/net462/SkiaSharp.targets#L11-L13

```xml
    <ItemGroup Condition=" '$(ShouldIncludeNativeSkiaSharp)' != 'False' and '$(_AppIsFullMac)' == 'True' ">
        <NativeReference Include="$(MSBuildThisFileDirectory)..\..\runtimes\osx\native\libSkiaSharp*.dylib" Kind="Dynamic" Visible="false" />
    </ItemGroup>
```

As you can see, there are 2 conditions on that element, the `ShouldIncludeNativeSkiaSharp` which you don't want to set because you _do_ want to copy the native files, and then `_AppIsFullMac` which _should_ be false or unset... It is a bit annoying that MSBuild is ignoring these conditions and pulling all the `NativeReference` elements out. I think it started with a recent-ish version of msbuild.

One thing you can try is setting the `UseXamMacFullFramework`  to `false` in your csproj and see if that does something. Maybe also set `_AppIsFullMac` to `False` just in case something...

Also is it not possible to use .NET Core instead of .NET Framework? This will solve all the other deployment issues .NET Framework has.

**Comment by jsgoupil** [comment]
My goal is to go towards .NET Core for sure, but it's not as simple as expected. I am moving slowly my .NET framework dependencies into .NET Standard or something that supports .NET Core and .NET Framework.
So it will have to stay with .NET Framework right now.

```
    <UseXamMacFullFramework>false</UseXamMacFullFramework>
    <_AppIsFullMac>False</_AppIsFullMac>
```

It doesn't work.

```
MSBuild auto-detection: using msbuild version '14.0' from 'D:\Program Files (x86)\MSBuild\14.0\bin\amd64'.
All packages listed in packages.config are already installed.
D:\home\site\repository\Portal\hbti-web-master\packages\SkiaSharp.2.80.1\build\net462\SkiaSharp.targets(12,109): error MSB4066: The attribute "Kind" in element <NativeReference> is unrecognized. [D:\home\site\repository\Portal\hbti-web-master\HBTI.ServiceTech.Common\HBTI.ServiceTech.Common.csproj]
Failed exitCode=1, command="D:\Program Files (x86)\MSBuild\14.0\Bin\MSBuild.exe" "D:\home\site\repository\Portal\hbti-web-master\HBTI.ServiceTech.Web2\HBTI.ServiceTech.Web2.csproj" /nologo /verbosity:m /t:Build /t:pipelinePreDeployCopyAllFilesToOneFolder /p:_PackageTempDir="D:\local\Temp\8d840b5a8294a2a";AutoParameterizationWebConfigConnectionStrings=false;Configuration=Release;UseSharedCompilation=false /p:SolutionDir="D:\home\site\repository\Portal\hbti-web-master\\"
```

**Comment by jsgoupil** [comment]
I'm not the most verse in MSBuild here, maybe it should not pick it up.
But `Kind` doesn't seem to be a valid attribute.
https://docs.microsoft.com/en-us/visualstudio/msbuild/common-msbuild-project-items?view=vs-2019

**Comment by jsgoupil** [comment]
OK. It worked with the following setting on Azure Configuration

```
MSBUILD_PATH = %MSBUILD_16_DIR%\msbuild.exe
```

Since I use Kudu, it was using the MSBuild 14, and it seems like it was not liking the custom attribute.

Maybe a documentation has to be written or a check earlier to warn for this problem when building Skiasharp.

I'll let you handle the bug as you wish now :)

**Comment by mattleibow** [comment]
Very interesting... What image are you using?

I think what is happening here is that the older MSBuild did not like attributes and only had sub-elements.

But still, it is more weird that MSBuild is so old, v14 is VS 2015?

**Comment by jsgoupil** [comment]
I don't use any VM Images. On Azure this is called an App Service (Azure Websites), and I'm doing a Web App Deployment. I picked Windows. I have very little control over this.
I use Kudu deployment. It's the git flow deployment on Azure Web Apps. It's before DevOps existed.
Which is also quite old and not maintained much. By default, it uses MSBuild 14 if not overridden in the Configuration.
https://github.com/projectkudu/kudu

Good luck with the project!
