### ISSUE TITLE
iOS: Draw directly on GLKView

### ISSUE THREAD

**Issue by Majchrzak** [mono/SkiaSharp#147]
Hello, 

Anyone can explain how to directly draw SKCanvas on GLKView? My code is based on _Skia.OSX.GLDemo_ sample, but I can't figure out why there is nothing on the screeen.

Here is my code:
[https://gist.github.com/Majchrzak/f9b2cb68df84d644a00c432e8ba13787](https://gist.github.com/Majchrzak/f9b2cb68df84d644a00c432e8ba13787)

**Comment by migueldeicaza** [comment]
Let us use the forums to discuss support issues.

http://forums.xamarin.com/categories/cross-platform

**Comment by mattleibow** [comment]
@Majchrzak I am busy working on a set of Views/Layers to help speed up drawing with SkiaSharp. Right now I am busy getting everything together so the code is a quicksand, but here is the branch: https://github.com/mono/SkiaSharp/tree/skiasharp-views

Check out the `views` folder in the root. Right now, the GL bits aren't there yet for Mac (I need to go to sleep, but when I wake... that is what I am going to do next). But, everything seems to be "working" for iOS/tvOS (both raster and GL) and the raster stuff is there for Mac. As I said, it is still very much a work-in-progress.
