### ISSUE TITLE
[QUESTION] Am I using the correct FillType for the SKPath?

### ISSUE THREAD

**Issue by leonbohmann** [mono/SkiaSharp#1482]
Hello all,

I am currently creating a 2D Library which uses SkiaSharp. It generates an interactive control in which you can click, drag and select several shapes. While the simplest shape is a line, one can also create circles. Their rotation (i.e. mathematically negative -1 or positive 1). Positive circles add area to the path, while negative circles remove area.

The drawing of the shapes works just fine. The hatching of the path, however, doesnt work that well. 

In this example there is just a square with a hole in it. As seen, the path gets hatched even though the circles rotation is set to -1 (which should create a hole in the path).

![grafik](https://user-images.githubusercontent.com/13386367/91457952-41c5d500-e885-11ea-9ba7-ae095b36de26.png)

Once I translate the circles center a slight bit off the 0 and 90° angles, it suddenly works.
![grafik](https://user-images.githubusercontent.com/13386367/91458048-5f933a00-e885-11ea-9561-fdd5c005915a.png)

For the filling of the path I simply use:
```
     Canvas.Save();
     Canvas.ClipPath(path);
     Canvas.DrawRect(path.Bounds, hatchPaint);
     Canvas.Restore();
```

To create the `path` I iterate through all lines, using `path.LineTo(destination)`, while for circles I use `path.ArcTo( , , , false)`.

Is there anything I am missing? Thanks for your help, if more information is needed, I'm happy to provide it.
Thanks in advance!

**Comment by leonbohmann** [comment]
To explain this a little further, here is the complete creation of the path. I truncated the `new SKPoint(x,y)` to just `x,y`.
```

path.MoveTo(0,0);
path.LineTo(100,0);
path.LineTo(100,100);
path.LineTo(0,100);
path.LineTo(0,50);
path.LineTo(40,50);
path.ArcTo( ... , false); // creates the correct arc around (50,50)
path.LineTo(0,50);
path.LineTo(0,0);
```

I tried closing the path, as well as simplifying it. No success..

**Comment by leonbohmann** [comment]
I think I already found a solution for my problem.

I have to catch, if the angle for the `ArcTo(...)` Function equals to 360. If that happens, I need to use:

```
Path.MoveTo(origin);
Path.Circle(center.X, center.Y, radius, ...);
Path.MoveTo(next);
```

This way I get the desired cut-out!

**Comment by mattleibow** [comment]
Yu could also try closing the path before drawing the arc. 

There very well might be an optimization that incorrectly closes the path if you add an arc that is 360 degrees and is rotated. The math may be to first check to see if it can be replaced with a circle - which is closed. But an arc is not technically closed.

**Comment by leonbohmann** [comment]
Hi Matthew!

Thanks for your answer!

Unfortunately, my approach only works, if there is only one circle added to the path. When adding multiple circles, I get weird connections between the start-points of the circles and the origin, see following:

![grafik](https://user-images.githubusercontent.com/13386367/91489798-aeef5f80-e8b1-11ea-9b50-fa352a35038e.png)


I tried your approach as well, calling `path.Close()` right before drawing the arc. That doesnt fix the issue. Any idea, where these lines may come from?

**Comment by leonbohmann** [comment]
Another thing I did to locate this issue is drawing the points of the path in their respective order with a leading "k". So "k0" is the first point in path.Points.

![grafik](https://user-images.githubusercontent.com/13386367/91498237-ba498780-e8bf-11ea-82f3-19df219c7ec3.png)

As you can see in the bottom left corner, the first three points are correct. Then, when the circle starts, we see a jump from k3 to k6. In the top right corner we see a jump from k15 on the right outer edge to k16 and k17 on the circle start point. Here is where I dont understand what is going on? Why do we see the connection to the last circle start-point AND the origin? This does not occur when using only one circular hole in the rectangle!

Another workaround I found, is to create the circle on my own, by rotating a vector by an angle around a circle center using `path.LineTo(center + rotatedRadiusVector)`. To create a smooth circle I used a 5° increment on the angle, which gives quite a bunch of point overhead. I'm not sure if this affects performance in any way, when the drawing gets (a lot) more complicated, with possibly thousands of points.
