### ISSUE TITLE
[QUESTION] Tradeoffs around SkSwapChainPanel's DrawInBackground property?

### ISSUE THREAD

**Issue by hansmbakker** [mono/SkiaSharp#1485]
@mattleibow would you be able to comment on https://stackoverflow.com/questions/63678311/tradeoffs-around-skswapchainpanels-drawinbackground-property

**Comment by mattleibow** [comment]
Thanks for bringing that to my attention. I answered there with some info.

I'll close this issue so as to avoid a split answer. There are some good comments already, so I'll be answering/responding on SO.
