### ISSUE TITLE
SkiaSharp 1.54.0: MissingMethodException thrown "Method 'SKRect.get_Left' not found."

### ISSUE THREAD

**Issue by bruzkovsky** [mono/SkiaSharp#149]
I got this error right after updating from 1.53 to 1.54.0

**Comment by DanWBR** [comment]
I also had this error because I was referencing 1.53 from a PCL in my project. After I've updated the PCL reference to 1.54 too, it worked correctly.

**Comment by bruzkovsky** [comment]
I updated the package for all project, but I will double-check that.

Thanks for the hint!

**Comment by bruzkovsky** [comment]
Ok, reverting the update and doing it again fixed it for me.

**Comment by mattleibow** [comment]
Hi @bruzkovsky @DanWBR, I am glad you figured this out. Just so you know WHY you got the error. We changed from a field-based structure to a property-based one.
