### ISSUE TITLE
[QUESTION] [GPU] [Angle] [WPF] Any safe way to FlushAsync() or Flush in other thread?

### ISSUE THREAD

**Issue by Mikolaytis** [mono/SkiaSharp#1494]
Canvas.Flush() is taking a lot of time (up to 2 seconds) in my scenarios with huge amount of elements on a canvas, blocking my render thread.
I want to draw next frame, while i'm waiting for previous frame render. Some kind of double buffer render.
Is anyone faced this type issue and found a good solution?

I'm trying to launch Flush() in another thread. It works for a while, works perfectly(huge lag reduce), but unsafe, has random crashes on flush and image draw skia calls.

AFAIK All Flush() is do - is just an endless loop wait for GPU response. So I think I'm doing something wrong and cannot find an obvious solution.

**Comment by Mikolaytis** [comment]
I've found, that the reason of the long flush() calls in a most of scenarios is just a small ResourceCacheLimit in GrContext. 
If skia needs more then a cache limit to draw a frame - it will create and delete textures from cache on each frame to draw it. It takes a lot of time. 

After enlarging it the problem do not exist anymore, so I don't need to find a way to run flush in other thread.

**Comment by mattleibow** [comment]
Thanks for the update on this. Why are there so many textures? Is it related to what you are drawing?

**Comment by Mikolaytis** [comment]
Yes. In our app users can make really big files with thousands of small textures and some huge textures. Small ResourceCacheLimit is a real sneaky bottleneck. Was really hard to find.
