### ISSUE TITLE
[FEATURE] Please re-add support for GRContextOptions

### ISSUE THREAD

**Issue by danwalmsley** [mono/SkiaSharp#1499]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
It would be super nice if we could access some of the properties from:

https://github.com/google/skia/blob/master/include/gpu/GrContextOptions.h

particularly:

`fAvoidStencilBuffers`
`fRuntimeProgramCacheSize`
`fGlyphCacheTextureMaximumBytes`
`fAllowPathMaskCaching`
`fDoManualMipmapping`
`fBufferMapThreshold`

**Describe alternatives you've considered**

**Additional context**

This is part of my investigation into high memory usage when using skia with gpu backend.

**Comment by danwalmsley** [comment]
https://bugs.chromium.org/p/chromium/issues/detail?id=713854

this bug seems to be related to what we are seeing...

```
Here are some options to mitigate the leak:

A) Add a workaround to Skia which avoids using stencils:
Currently, we use stencils for some non-AA masks/clipping, and for some path rasterization. We could move path rasterization to use other approaches (we already have a number of fallbacks). We have a non-stencil AA mask path, we could probably use this for non-AA masks as well.

B) Use real GL contexts (rather than virtualized ones):
This would mean that GL contexts would get cleaned up more regularly as renderers were created/destroyed, preventing leaks in these contexts from building up over time.

C) Cause Skia to never purge stencil resources on problem systems:
Currently, the leak is made worse by the way the Skia cache purges unused resources after a short duration. This means we may allocate/release a stencil a number of times, rather than just keeping it cached. While this makes sense if the stencil is actually freed, in this case we are just making the leak worse.

I think that either option (A), or a combination of options (B) and (C) would work. (B) is probably good to investigate anyway, as it also mitigates any other leaks we haven't found.
```

**Comment by mattleibow** [comment]
Sorry it took so long, but `2.80.3-pr.1529.5` should be on the preview feed. As soon as we know this is actually useful, I'll merge the PR.
