### ISSUE TITLE
[QUESTION] System font recall problem

### ISSUE THREAD

**Issue by ChanYoung-Ko** [mono/SkiaSharp#1504]
Hello, I am a developer using xamarin.forms.
I have a question about a problem while drawing text through skiasharp.
First of all, I apologize for my lack of English skills.

I'm currently using 1.68.3 version.

`string[] skFontFamily = SkiaSharp.SKFontManager.Default.GetFontFamilies();`

Use the code at the top to load the Default font.
The uwp and android normally produce a default font string[].
However, for ios, the number of strings[] is always returned to zero.
What kind of mistake am I making?

**Comment by mattleibow** [comment]
Not gonna lie, this was actually pretty unexpected... I started digging and then found that iOS just has no implementation and always returns an empty list.

https://groups.google.com/g/skia-discuss/c/FBVhoy8pJ8Q

I started a discussion with Google, but I will also try and get something in for SkiaSharp.

**Comment by mattleibow** [comment]
Seems the fonts API just was never used in skia. But, I added it to our fork, so the next release should have the list of fonts.

**Comment by ChanYoung-Ko** [comment]
> Seems the fonts API just was never used in skia. But, I added it to our fork, so the next release should have the list of fonts.

Thank you for your reply.
I'm looking forward to the next version update.
