### ISSUE TITLE
[BUG] WPF SKElement does not call PaintSurface when inside a Panel

### ISSUE THREAD

**Issue by ldematte** [mono/SkiaSharp#1506]
WPF under Windows 10.

I have this layout

Window -> WrapPanel -> UserControl -> SKElement.

With this hiearchy, the PaintSurface event attached to the SKElement never gets called.

If I pull the SKElement "one level up" (i.e. get rid of the WrapPanel)
Window -> UserControl -> SKElement

The PaintSurface event is called again.
I expected it to work, instead it is never called. Calling InvalidateVisual on the SKElement does not help either: when outside the panel it triggers a call to PaintSurface, when inside a panel it does nothing.

**Comment by ldematte** [comment]
My bad, I was not setting dimensions! Sorry for the noise.

**Comment by mattleibow** [comment]
No prob. You will never guess how often that happens to me. And then I also forget to add the view to the window as well...
