### ISSUE TITLE
[BUG] SKTypeface.GetGlyphs problems...

### ISSUE THREAD

**Issue by Ziriax** [mono/SkiaSharp#1507]
**Description**

To determine the number of glyphs in text, the following code is used in SkiaSharp 1.68.3:

```CS
var n = SkiaApi.sk_typeface_chars_to_glyphs (Handle, (void*)text, encoding.ToEncoding (), null, length);
```

`length` is number of bytes in the `text`.

`sk_typeface_chars_to_glyphs` passes the `length` as-is to `SkTypefaceXXX::charsToGlyphs` as the `glyphCount` parameter...

This can result in an access violation before the `charsToGlyphs` native code can read beyond the data boundary:

```C
        EncodingProc next_ucs4_proc = find_encoding_proc(encoding);
        for (int i = 0; i < glyphCount; ++i) {
            const SkUnichar c = next_ucs4_proc(&chars);
            BOOL exists;
            fDWriteFont->HasCharacter(c, &exists);
            if (!exists) {
                return i;
            }
        }
        return glyphCount;
```

PS: Another problem with this Skia code is that this stops counting at the first unsupported character... I was expecting it to count all characters, and just return 0 as the glyph id for unsupported chars?

**Code**

```cs
var data= Encoding.UTF32.GetBytes("X");
var slice= new Span<byte>(testData, 0, 4);
var glyphs = _typeface.GetGlyphs(testSlice, SKTextEncoding.Utf32);
```

**Expected Behavior**

One glyph id should be returned.

**Actual Behavior**

Four glyph ids are be returned, or an access violation is raised.

**Basic Information**

- Version with issue:  1.68.3
- Last known good version:  none
- Platform Target Frameworks:  all

**Comment by mattleibow** [comment]
Does this still happen with v2?

I think I recall something about this on v2 and I had to manually do something in the native code for this.

**Comment by Ziriax** [comment]
in v2, it seems that

```
var data= Encoding.UTF32.GetBytes("X");
var slice= new Span<byte>(data, 0, 4);
var glyphs = _typeface.GetGlyphs(slice, SKTextEncoding.Utf32);
```

indeed returns just a single glyph id
