### ISSUE TITLE
[FEATURE] Reduce heap allocation on SKManagedStream.OnReadManagedStream

### ISSUE THREAD

**Issue by Mikolaytis** [mono/SkiaSharp#1509]
I've found a big heap allocation on images decode at `SKManagedStream.OnReadManagedStream`. 
![Screenshot 2020-09-25 at 23 50 48](https://user-images.githubusercontent.com/4997065/94314864-20dac780-ff8a-11ea-8f89-4821d18f7aec.png)
Maybe it would be better to use a 81920 bytes length buffer to copy a managed stream data to unmanaged pointer? I hope Marshal.Copy cost is not huge.
<img width="544" alt="Screenshot 2020-09-25 at 23 54 03" src="https://user-images.githubusercontent.com/4997065/94315030-66979000-ff8a-11ea-9826-bd0926ada8a3.png">

**Comment by mattleibow** [comment]
Thanks for this. We might be able to use better copying here. Maybe spans or marshal as you said. I'll check it out.
