### ISSUE TITLE
missing method: "SKPathOps::TightBounds"

### ISSUE THREAD

**Issue by gentledepp** [mono/SkiaSharp#151]
In our app, we need to calculate the exact bounding box (we call it "visible bounding box" as it should only enclose all visible paths) of an SKPath.
However, in skia, the SKPath.getBounds() method returns a rectangle that encompasses also the control points of curves (e.g. cubic bezier curve), which returns a "wrong" result for our use case.

We filed a bug for this here: https://bugs.chromium.org/p/skia/issues/detail?id=5751

and got the response, that we should consider using SKPathOps "TightBounds"
see: 
    /** Set the resulting rectangle to the tight bounds of the path.
    @param path The path measured.
    @param result The tight bounds of the path.
    @return True if the bounds could be computed.
    /
    bool SK_API TightBounds(const SkPath& path, SkRect result);

https://github.com/google/skia/blob/master/include/pathops/SkPathOps.h

The following **skia.fiddle** shows how to use it:
https://fiddle.skia.org/c/5a69132d6477821d124b75d8ec4ee949

Could you bind that to "SKPath" somehow, please?
As it is a static method, I do not know how you'd like to bind it to SkiaSharps API (from a design point of view)

**Comment by mattleibow** [comment]
I added this method, and others, into master: 6c498072888749bdba00ed8943f47b146ab18095 and 46fe808f7d4a76e139dd00f2ec1d951e44977515

I hope to release this today once CI has finished running what it runs

**Comment by gentledepp** [comment]
WOW! That would be awesome! Thanks man!
