### ISSUE TITLE
[QUESTION] FontSpacing seems to be too small

### ISSUE THREAD

**Issue by MichaelRumpler** [mono/SkiaSharp#1516]
This is a follow up to the [twitter discussion](https://twitter.com/BeneStebner/status/1311310716578693121) I had with @mattleibow  and @Gillibald  as Twitter is the wrong medium for this.

I want to use SkiaSharp to render a console. So I use a monospace font and I get character positions which I need to translate into pixels for SkiaSharp. I used `SKPaint.FontSpacing` for the height and `SKPaint.MeasureText("W")` for the width of a character.

This works fine with `Courier New`, but when I use the font `Cascadia Mono PL`, then `SKPaint.FontSpacing` is not high enough. [Oh-my-posh (blog by shanselman)](https://www.hanselman.com/blog/HowToMakeAPrettyPromptInWindowsTerminalWithPowerlineNerdFontsCascadiaCodeWSLAndOhmyposh.aspx) uses some glyphs in that font, which go higher up than `SKFontMetrics.Ascent`.

I wrote a repro project which shows that. The output looks like this:
![image](https://user-images.githubusercontent.com/8309363/94916934-db4d5b80-04af-11eb-9347-436431ece38d.png)

As you can see the arrow is higher than `Ascent`. If I use `Ascent` and `FontSpacing` to position things, then this does not work. This is the code I use for drawing text, but it is wrong:

	// clear background with height FontSpacing
	canvas.DrawRect(x, y, text.Length * charWidth, foreground.FontSpacing, background);
	// DrawText needs the baseline and Ascent is the (negative) offset
	canvas.DrawText(text, x, y - foreground.FontMetrics.Ascent, foreground);

Is this a bug in SkiaSharp, Skia or the Cascadia font? I can easily workaround when I use `Top` instead of `Ascent` for the distance to the baseline and `Descent - Top` for the line height. But is this really the intended solution? What are `Top` and `Bottom` intended for anyway and why are they different than `Ascent/Descent`?

`Top` also does not seem to be 100% correct. You can see that the glyphs don't go all the way to `Top`. They are a bit shorter. Can I somehow measure how tall the highest glyph in the font is? Even if I use `Top`, the arrows don't look as good as in the Windows Terminal. You can see that in the following screenshot at the top right corner of every second arrow.
![image](https://user-images.githubusercontent.com/8309363/94918725-6da32e80-04b3-11eb-9771-16eccaacd8b0.png)

[Skia_Cascadia.zip](https://github.com/mono/SkiaSharp/files/5317517/Skia_Cascadia.zip)

**Comment by Gillibald** [comment]
This explains those properties pretty well: https://stackoverflow.com/a/27631737

**Comment by mattleibow** [comment]
You can also check out values in the `SKPaint.MeasureText` and see what that rect contains.

@Gillibald I think what you are saying is that those values in the metrics are more a guide and maybe defined by the font? OR are the actually calculated?

**Comment by Gillibald** [comment]
They are defined by the font author

**Comment by MichaelRumpler** [comment]
Thanks, that SO article is the best documentation I found so far.

That means there is some glyph which is even higher than that arrow or at least the font authors claimed so.

I'll take a look at [the source of the Windows Terminal](https://github.com/microsoft/terminal) and see if I can find how they handle this. Because somehow their line seems to be as high as the arrow, starting at neither `Top` nor `Ascent`.

**Comment by MichaelRumpler** [comment]
I didn't find any properties which resemble the values I need, so I measure how big the biggest chars are which may be used. This works best in what I tested so far.

	// check the maximum sizes of those chars:
	// a Powerline Arrow, Unicode Full Block and Ö and y as fallback
	var bigChars = "\uE0B0\u2588Öy";
	var cellSize = new SKRect();
	for (int i = 0; i < bigChars.Length; i++)
	{
		var s = bigChars.Substring(i, 1);
		if (Paint.ContainsGlyphs(s))	// if the font does not contain the glyph, then skip it
		{
			var rect = new SKRect();
			Paint.MeasureText(s, ref rect);
			cellSize.Union(rect);
		}
	}

	CharWidth = Paint.MeasureText("W");     // cellSize.Width is too big
	LineHeight = cellSize.Height;
	Ascent = cellSize.Top;

It's really a shame that even in a monospace font not all glyphs have the same size. This is only trial and error what I'm doing here. And I only tested with Courier New and Cascadia Mono PL. For other fonts it might not work at all.
