### ISSUE TITLE
[BUG] Y axis is inverted

### ISSUE THREAD

**Issue by EmilAlipiev** [mono/SkiaSharp#1520]
**Description**

I saw this existing issue https://github.com/mono/SkiaSharp/issues/231 but not sure if it is related. Basically when I draw a simple Path, the more increase the Y axis, path is moving down not to the upper direction as i would expect. Here is the code sample.

```

   var  indicatorStrokePaint = new SKPaint
            {
                Style = SKPaintStyle.Stroke,
                StrokeWidth = 6,
                Color = strokeColor,
                IsAntialias = true
            };

               var start = new SKPoint(500, 70);
                var end = new SKPoint(500, 100);

                canvas.DrawLine(start, end, indicatorStrokePaint);

```

Screenshot for above code red line is the path I am drawing

![image](https://user-images.githubusercontent.com/10422347/95019861-172b2100-0668-11eb-99e9-f8528dd18f5b.png)

if i increase those numbers like 

```
   var start = new SKPoint(500, 100);
                var end = new SKPoint(500, 130);
```

you can see below that red path was drawn more below than the gauge. 
![image](https://user-images.githubusercontent.com/10422347/95019925-7ee16c00-0668-11eb-8769-7aeb813b535a.png)

**Expected Behavior**

I would expect that the more i increase the y axis, it should draw more upper.

**Actual Behavior**

goes down

**Basic Information**

- Version with issue:   skiasharp.views.forms 2.80.1
 
- Platform Target Frameworks: 
  - Android: 9.0

**Comment by mattleibow** [comment]
SkiaSharp uses the top-left origin. Positive X is to the right, positive Y is down.

This is counter to macOS coordinates and GPU. However, it is pretty common with 2D screen-based rendering engines.

**Comment by EmilAlipiev** [comment]
oh ok good to know. I thought that there is a bug :) thanks for making it clear for me.
