### ISSUE TITLE
[BUG] SKMatrix IsInvertible property crashes the debugger silently on trying to peek an variable values

### ISSUE THREAD

**Issue by Mikolaytis** [mono/SkiaSharp#1526]
1. Open visual studio
2. Write a simple console app that creates an `SKMatrix` into a variable and prints it in a second row.
3. Launch app with debugging and try to peek values of `SKMatrix`.
4. App is crashed.

Source of a crash is `IsInvertible` property.

Me and 2 other devs has this issue. I hope you can repro it too. This issue is critical, because it disables any matrix calculation debugging scenarios.

**Comment by Mikolaytis** [comment]
@mattleibow This issue is not unit-testable. Here is a screenshot of a problem:

![Screenshot 2020-10-11 at 21 19 28](https://user-images.githubusercontent.com/4997065/95686609-98099000-0c07-11eb-91e5-6c67e07d41ca.png)

Here is a bit detailed steps:
1. create empty project in the visual studio and write next thing:
```
            var matrix = SkiaSharp.SKMatrix.CreateIdentity();
            Console.WriteLine("Hello World!" + matrix);
```
2. set breakpoint to the second line with writeLine.
3. launch app with debugger attached
4. hover mouse over matrix property declaration and expand properties list
5. observe crash from screenshot above

**Comment by Mikolaytis** [comment]
Disabling property evaluation is not a fix of a problem, because this option is essential for debugging.

**Comment by Mikolaytis** [comment]
I think marking the IsInvertible property with  [DebuggerBrowsable(DebuggerBrowsableState.Never)] should do the trick. I'll check this and will provide a PR.

**Comment by mattleibow** [comment]
@Mikolaytis sorry I didn't ping you over the weekend. But thought you would have seen my pr I merged.

That should fix it and the bits are already out on the preview feed. Unless you saw that already and it didn't fix the issue?

It should be fixed in preview 9. You can check out the actual fix https://github.com/mono/skia/commit/a7b3674c74e3b0b5252cc8cc3e41168c5b6b7492

Basically, the managed code was passing null as the dest matrix, but then I didn't check it.

**Comment by Mikolaytis** [comment]
@mattleibow I've missed your mono/skia commit. I've seen only unit test. Thought that you did not understand my bug and just added unit test, and closed the issue. It turns out I was wrong :)

**Comment by mattleibow** [comment]
☺

Let me know if the preview works for you! I think I am reaching the first preview of 2.80.3 very soon. A nice bunch of fixes and features.

**Comment by Mikolaytis** [comment]
preview 9 - issue fixed! thanks

**Comment by mattleibow** [comment]
Thanks for the feedback!
