### ISSUE TITLE
[Win7]: Runtime failure due to native dependencies

### ISSUE THREAD

**Issue by prasannavl** [mono/SkiaSharp#153]
I was testing an application in Win 7 for backward compatibility. So, freshly booted clean install of the latest Win 7 64-bit build 7601 (with SP1) from MSDN. However, I ended up with a strange exception that said `libSkiaSharp.dll could not be found` even though it was right by the executable. 

So, I had a hunch it was likely that the module couldn't be loaded successfully, which I was able to confirm after poking into it. Turns out `libSkiaSharp.dll` that's packaged with nuget is dynamically linked to the VC++ runtime 2015 - which a clean install of 7 doesn't have. I guess, this is kind of the usual problems we run into working with native libraries. However, is it possible to statically link, or use a MinGW compilation of Skia that can be done with the nuget? 

Also, it might make sense to document this behavior somewhere that the VC++ 2015 runtime is required, since the `nuget` version of the build is from the VC2015 compiler.

Or it will fail with a not very helpful `DllNotFoundException` that may not make much sense right away for people who don't work with native code.

**Comment by prasannavl** [comment]
Oh damn. I just realized it is already right on the README file. My apologies. Closing this.

**Comment by mattleibow** [comment]
@prasannavl, no prob. It was also discussed a bit here https://github.com/mono/SkiaSharp/issues/136
