### ISSUE TITLE
[BUG]  Error while loading assemblies

### ISSUE THREAD

**Issue by blmiles** [mono/SkiaSharp#1530]
Hello, (I was asked to start a new thread on this topic)

Occurs in any update after updating SkiaSharp from 1.60.3 to 2.80.2
Solution is Xamarin.Forms (shared) and an iOS project and Android project. Android works just fine.

Also posted in this thread: #855

Here's the error in iOS build:
Severity Code Description Project File Line Suppression State
Error Error while loading assemblies: /Users/[user]/Library/Caches/Xamarin/mtbs/builds/[mycompany].iOS/2b8bb42efaa82e056d0923743e8a2829/bin/iPhoneSimulator/Debug/libSkiaSharp.dll. [mycompany].iOS

2> /Library/Frameworks/Xamarin.iOS.framework/Versions/Current/bin/mtouch @/Users/[user]/Library/Caches/Xamarin/mtbs/builds/[mycompany].iOS/2b8bb42efaa82e056d0923743e8a2829/obj/iPhoneSimulator/Debug/response-file.rsp "--gcc_flags=-Xlinker -sectcreate -Xlinker __TEXT -Xlinker __entitlements -Xlinker /Users/[user]/Library/Caches/Xamarin/mtbs/builds/[mycompany].iOS/2b8bb42efaa82e056d0923743e8a2829/obj/iPhoneSimulator/Debug/Entitlements.xcent"
2>C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets(885,3): error MT0009: Error while loading assemblies: /Users/[user]/Library/Caches/Xamarin/mtbs/builds/[mycompany].iOS/2b8bb42efaa82e056d0923743e8a2829/bin/iPhoneSimulator/Debug/libSkiaSharp.dll.

I have tried removing this from the iOS .proj file: `<PlatformTarget>x86</PlatformTarget>`

And I've tried adding this to the .proj file: `ExcludeAssets="runtimes"` in the skiaSharp reference(s).

Wondering if there's something lingering in my Mac as its looking for something that is no longer there...

If I regress to 1.60.3 it works just fine.

EDIT: More info. Just updated the SkiaSharp packages again. I was only installing SkiaSharp and SkiaSharp.Views.Forms and getting the error above. Installed SkiaSharp.Views too (looking at dependencies, SkiaSharp.Views is listed under the iOS list).

I get the same error.

Looked at the Dependencies/Packages and I see this on the SkiaSharp.Views package:
Package 'SkiaSharp.Views 2.80.2' was restored using '.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8' instead of the project target framework '.NETStandard,Version=v2.1'. This package may not be fully compatible with your project.

Is there an upgrade sequence (if skiasharp is already installed) - like 1.60.3 to 1.68.x to 2.80.x ? Silly question but I'll try anything right now :)

Any other potential fixes?

Thanks

**Comment by blmiles** [comment]
Un-installed everything again, cleaned, reinstalled ShiaSharp and ShiaSharp.Views.Forms ONLY. v2.80.2. NO SkiaSharp.Views installed.
And as for the path/folder - /Users/[user]/Library/Caches/Xamarin/mtbs - finally got it, deleted it AND emptied trash on the Mac.

Still seeing same error on fresh build. No errors in Android solution and the app on that platform works just fine.

This is similar to this #855

Thanks

**Comment by mattleibow** [comment]
Hey there, if you create a binlog:  https://www.meziantou.net/exploring-the-msbuild-log-using-the-binary-log-viewer.htm
You can send it to me at maleib [at] microsoft.com

**Comment by blmiles** [comment]
Sent binlog. Pls let me know if what I've sent is right.
Thx

**Comment by mattleibow** [comment]
Thanks! I'll have a look.

**Comment by blmiles** [comment]
FIXED! For those who might run into a similar issue, try this:

In the iOS  .csproj inside the first _`<PropertyGroup>`_ element, add:
_```
RuntimeIdentifiers>osx;osx-x86;osx-x64</RuntimeIdentifiers
NuGetRuntimeIdentifier>osx</NuGetRuntimeIdentifier
```_

All compiled after that. Passed smoke-testing.

Hope that helps!

**Comment by blmiles** [comment]
TOO GOOD TO BE TRUE

FYI, this error builds just fine targeting the latest emulator and iOS 14.0, however, just cleaned/rebuilt for hard device iphone X, iOS 13.7 and get these errors:
_Severity	Code	Description	Project	File	Line	Suppression State
Error		linker command failed with exit code 1 (use -v to see invocation)	[mycompany].iOS	C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets	885_	

AND

_Severity	Code	Description	Project	File	Line	Suppression State
Error		Native linking failed for '/Users/[user]/Library/Caches/Xamarin/mtbs/builds/[mycompany].iOS/2b8bb42efaa82e056d0923743e8a2829/obj/iPhone/Debug/device-builds/iphone11.2-13.7/mtouch-cache/arm64/libSkiaSharp.dll.dylib'. Please file a bug report at https://github.com/xamarin/xamarin-macios/issues/new	[mycompany].iOS	C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets	885_	

AND

AND

_Severity	Code	Description	Project	File	Line	Suppression State
Error		Native linking failed for '/Users/[user]/Library/Caches/Xamarin/mtbs/builds/[mycompany].iOS/2b8bb42efaa82e056d0923743e8a2829/obj/iPhone/Debug/mtouch-cache/arm64/libSkiaSharp.dll.dylib'. Please file a bug report at https://github.com/xamarin/xamarin-macios/issues/new	[mycompany].iOS	C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets	885_

**Comment by mattleibow** [comment]
Booooo!

Try removing the PlatforTarget elements. Also, try installing SkiaSharp into the iOS project itself. I heard rumors that there is a bug with transitive dependencies from netstandard/SDK to classic projects.

**Comment by blmiles** [comment]
Ok, will do. Sent you the csproj file to take another look.

**Comment by blmiles** [comment]
Removed the PlatformTarget elements, installed SkiaSharp and SkiaHarp.Views.Forms into the iOS proj.
Get same error(s)
Builds and runs just fine going to the sim though.

**Comment by blmiles** [comment]
For anyone watching this bug, latest fix is setting these in the Debug|iPhone section:

<MtouchNoSymbolStrip>true</MtouchNoSymbolStrip>
    <MtouchFastDev>false</MtouchFastDev>
I also removed the <PlatformTarget> entry in that same section.

That allowed a build/deploy to the hard device.
Hope that helps!

**Comment by mattleibow** [comment]
After talking to the iOS team, it appears the issue is with the fast dev. This is sometimes unable to work properly.

There also seems to be a push to remove this and replace it with the even better interpreter.
