### ISSUE TITLE
[FEATURE] Telegram share button

### ISSUE THREAD

**Issue by leonbohmann** [mono/SkiaSharp#1531]
**Is your feature request related to a problem? Please describe.**

Ideally one should be able to directly use the share-function to share to Telegram as well.

**Describe the solution you'd like**

A simple telegram icon in the "Share" Popup.
In detail there may be an API to directly access the Telegram-Application, so the desired chat to share with can be chosen.

**Describe alternatives you've considered**

/

**Additional context**

/

**Comment by leonbohmann** [comment]
Omg. That was the wrong repo. I'm sorry :D

**Comment by mattleibow** [comment]
Lol 😂
