### ISSUE TITLE
[QUESTION] Unable to load shared library 'libHarfBuzzSharp' or one of its dependencies

### ISSUE THREAD

**Issue by saimmm** [mono/SkiaSharp#1533]
I am using Aspcore(dotnet core) under Ubuntu 18, i try to render images adding right-to-left text, for that purpose, i am using SkiaSharp, and HarfBuzzSharp, when the exception is raised mentioned in the title, i try to expect the missing shared libraries, in the /lib, i found that the library exist, but when run ldd /lib/libHarfBuzzSharp.so, the response is 'not a dynamic executable', when i run 'readelf -d' command, the result is:

Dynamic section at offset 0x9f938 contains 27 entries:
 Tag        Type                         Name/Value
 0x00000001 (NEEDED)                     Shared library: [libpthread.so.0]
 0x00000001 (NEEDED)                     Shared library: [libstdc++.so.6]
 0x00000001 (NEEDED)                     Shared library: [libc.so.6]
 0x00000001 (NEEDED)                     Shared library: [libgcc_s.so.1]

I think the so library is for other architecture or linux base sys, any ideas?

**Comment by mattleibow** [comment]
Did you install the Harfbuzzsharp.nativeassets.linux package? Linux is separate to accommodate all the various distributions.

**Comment by saimmm** [comment]
Yes of course, Here is my project file

        <PackageReference Include="HarfBuzzSharp" Version="2.6.1.7" />
	<PackageReference Include="SkiaSharp" Version="2.80.2" />
	<PackageReference Include="SkiaSharp.HarfBuzz" Version="2.80.2" /> 
	<PackageReference Include="SkiaSharp.NativeAssets.Linux.NoDependencies" Version="2.80.2" />

**Comment by Gillibald** [comment]
You did not install the HarfBuzz native bits you only installed the Skia bits.

**Comment by saimmm** [comment]
apt-get install -y libharfbuzz-dev
the latest library is installed

**Comment by saimmm** [comment]
#http://biography.univ-tiaret.dz/edit/print1

**Comment by Gillibald** [comment]
https://www.nuget.org/packages/HarfBuzzSharp.NativeAssets.Linux/

**Comment by saimmm** [comment]
wow that work, but i have run restore couple of time,
thank you very much.

**Comment by mattleibow** [comment]
Thanks @Gillibald!
