### ISSUE TITLE
SKSurface.Create returns null on Android

### ISSUE THREAD

**Issue by mihai-iancu** [mono/SkiaSharp#154]
I created a new Xamarin.Android application using Visual Studio 2015 (the Blank App template) and added the SkiaSharp nuget package to it (latest version 1.54).
I modified the Button_Click handler as below:
```
[Activity(Label = "AndroidTestApp2", MainLauncher = true, Icon = "@drawable/icon")]
public class MainActivity : Activity
{
    protected override void OnCreate(Bundle bundle)
    {
        base.OnCreate(bundle);

        // Set our view from the "main" layout resource
        SetContentView(Resource.Layout.Main);

        // Get our button from the layout resource,
        // and attach an event to it
        Button button = FindViewById<Button>(Resource.Id.MyButton);

        button.Click += Button_Click;
    }

    private void Button_Click(object sender, EventArgs e)
    {
        SKSurface surface = SKSurface.Create(1000, 1000, SKColorType.Bgra8888, SKAlphaType.Premul);
        SKCanvas canvas = surface.Canvas;
    }
}
```
In the project References section the SkiaSharp entry points to the lib\MonoAndroid\SkiaSharp.dll (the 20MB dll).
The SKSurface.Create method (the overloads without GRContext parameter) always returns null when running on a Samsung Galaxy S5 with Android 6.0.
Is there anything else that needs to be added to the project?

**Comment by mattleibow** [comment]
Hi @mihai-iancu, Thanks for using SkiaSharp. I think your issue is that you are using `SKColorType.Bgra8888`, which is for Windows-based systems (Windows/WPF/UWP) The correct value to use is `SKColorType.Rgba8888`.

For cross-platform support, you can also use the `SKImageInfo.PlatformColorType` property. This will automatically return the correct type for each platform.

**Comment by mihai-iancu** [comment]
Thank you very much for all your support.
