### ISSUE TITLE
[BUG] Memory leak when create and dispose SKBitmap and SKCanvas using SkiaSharp

### ISSUE THREAD

**Issue by Jack-Paul** [mono/SkiaSharp#1541]
Description
I have create a SKBitmap and SKCanvas and then i call dispose for both SKBitmap and SKCanvas but the memory is not released. I have the checked the memory usage using Visual Studio. I have compare the third and first snapshot after the dispose method but it holds some bytes. Attached screenshots shows that memory is not released after disposing the object.

Code

        static void Main(string[] args)
        {
            Console.WriteLine("Starting");
            Console.ReadLine(); // Starting snapshot
            MemoryCheck();
            Console.WriteLine("disposed");
            Console.ReadLine(); // Final snapshot
        }
        static void MemoryCheck()
        {
            SKBitmap bitmap = new SKBitmap(10, 10);
            SKCanvas sKCanvas = new SKCanvas(bitmap);
            bitmap.Dispose();
            sKCanvas.Dispose();
            bitmap = null;
            sKCanvas = null;
        }

Expected Behavior
Second snapshot Memory Should be downed to first snapshot. 

Actual Behavior
Second snapshot holding extra memory which is not released even after calling dispose.

I have ensured this with 1.59.3 And latest version, still issue is not resolved in latest version,
this issue is created with the follow up with the following issue - https://github.com/mono/SkiaSharp/issues/1009

Basic Information

Version with issue: 1.59.3 And 2.80.2
IDE: Visual Studio 2017
Platform Target Frameworks: .NET Core 2.0

Skia sharp version - 1.59.3
<img width="960" alt="Skia Sharp - 1 59 3" src="https://user-images.githubusercontent.com/34718301/97434740-787fa080-1945-11eb-89c1-f08919aeba58.PNG">

Skia sharp version - 2.80.2
<img width="957" alt="SkiaSharp - 2 80 2" src="https://user-images.githubusercontent.com/34718301/97434744-7a496400-1945-11eb-962a-30d20e4c116d.PNG">

Here is the project to reproduce the issue:

[Memory checking.zip](https://github.com/mono/SkiaSharp/files/5451756/Memory.checking.zip)

**Comment by mattleibow** [comment]
It is not always the cases that doing something results in an exact return to the same memory usage. This is especially the case after the first run, several things may need to be cached. I think that is what is happening, but not with skia, in the .NET runtime.

For example, I split the steps into a few parts:
 1. before anything
 2. after warmup that loads SkiaSharp and sets up the static fields
 3. after first run loads types and delegates
 4. after second run that returns to same memory

![image](https://user-images.githubusercontent.com/1096616/97488492-fef8aa00-1966-11eb-97f7-2ac506819d68.png)


```csharp
static void Main(string[] args)
{
    Console.WriteLine("Warmup");
    Console.ReadLine(); // Warmup snapshot

    Warmup();

    Console.WriteLine("Starting");
    Console.ReadLine(); // Starting snapshot

    MemoryCheck();

    Console.WriteLine("Repeat");
    Console.ReadLine(); // Repeat snapshot

    MemoryCheck();

    Console.WriteLine("disposed");
    Console.ReadLine(); // Final snapshot
}

private static void Warmup()
{
    var info = SKImageInfo.PlatformColorType;
    var data = SKData.Empty;
}

static void MemoryCheck()
{
    SKBitmap bitmap = new SKBitmap(10, 10);
    SKCanvas sKCanvas = new SKCanvas(bitmap);
    bitmap.Dispose();
    sKCanvas.Dispose();
    bitmap = null;
    sKCanvas = null;
}
```
