### ISSUE TITLE
Wrap SkPath.ConvertConicToQuads

### ISSUE THREAD

**Issue by tdenniston** [mono/SkiaSharp#155]
The SkPath class supports the `conic` verb, which can be trickier to deal with than normal Bezier segments. It'd be nice to wrap the [`SkPath.ConvertConicToQuads()`](https://github.com/mono/skia/blob/885431314fcbd2833483cf77d7fc3309e217b53f/include/core/SkPath.h#L635) static function to allow users of SkPath to convert those conic segments to quadratic segments.

**Comment by mattleibow** [comment]
Added in 2850a94f910bd8789f30a15c7acd6dca90ccf0ae
