### ISSUE TITLE
[BUG] Another build error in Windows 10 host, VS 2019 Community Edition (Preview)

### ISSUE THREAD

**Issue by mediabuff** [mono/SkiaSharp#1559]
**Have clang installed by VS 2010 CE Installer**
And the location is
C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\VC\Tools\Llvm\bin\clang-cl.exe

**Error Message**
[12/1101] compile ../../../src/xamarin/SkManagedDrawable.cpp
FAILED: obj/src/xamarin/libSkiaSharp.SkManagedDrawable.obj
cmd /c set __VSCMD_ARG_NO_LOGO=1 && set VSCMD_START_DIR=%CD% && "/Auxiliary/Build/vcvarsall.bat" amd64 10.0.18362.0 -vcvars_ver=14.2 &&   "C:/Program Files/LLVM/bin/clang-cl.exe" /nologo /showIncludes /FC -DSKIA_C_DLL -D_CRT_SECURE_NO_WARNINGS -D_HAS_EXCEPTIONS=0 -DWIN32_LEAN_AND_MEAN -DNOMINMAX -DNDEBUG -DSK_GAMMA_APPLY_TO_A8 -DSKIA_IMPLEMENTATION=1 -DSK_GL -DSK_VULKAN -DSK_SUPPORT_PDF -DSK_HAS_JPEG_LIBRARY -DSK_USE_LIBGIFCODEC -DSK_HAS_PNG_LIBRARY -DSK_CODEC_DECODES_RAW -DSK_HAS_WEBP_LIBRARY -DSK_XML -I../../.. -I../../.. -I../../../third_party/externals/libgifcodec /bigobj /utf-8 -fms-compatibility-version=19 -imsvc /Tools/MSVC//include -imsvc "C:\Program Files (x86)\Windows Kits\10/Include/10.0.18362.0/shared" -imsvc "C:\Program Files (x86)\Windows Kits\10/Include/10.0.18362.0/ucrt" -imsvc "C:\Program Files (x86)\Windows Kits\10/Include/10.0.18362.0/um" -imsvc "C:\Program Files (x86)\Windows Kits\10/Include/10.0.18362.0/winrt" /O2 /Zc:inline -Wno-unused-parameter -DSKIA_C_DLL /MT /EHsc /Z7 -D_HAS_AUTO_PTR_ETC=1 -DSK_BUILD_FOR_NANOSERVER  /std:c++17 /GR- /c ../../../src/xamarin/SkManagedDrawable.cpp /Foobj/src/xamarin/libSkiaSharp.SkManagedDrawable.obj /Fd"obj/SkiaSharp_c.pdb"
The system cannot find the path specified.
[14/1101] stamp obj/fontmgr_custom_empty.stamp
ninja: build stopped: subcommand failed.
An error occurred when executing task 'libSkiaSharp'.
Error: One or more errors occurred.
        Process 'C:/MyDevProjects/MyGitHub/SkiaSharp/externals/depot_tools/ninja.exe' failed with error: 1
An error occurred when executing task 'libSkiaSharp'.
Error: One or more errors occurred.
        Cake: Process returned an error (exit code 1).
An error occurred when executing task 'externals-nanoserver'.
Error: One or more errors occurred.
        Cake: Process returned an error (exit code 1).
PS C:\MyDevProjects\MyGitHub\SkiaSharp>

**Comment by mattleibow** [comment]
VS 2010 is not supported. Currently, only 2019 is supported for building skiasharp itself. It may be usable in that IDE, however, it probably is best update if possible.

But, if you want to build skiasharp, you might even be better off not building the native bits (unless you want to) and just download them before opening the sln: https://github.com/mono/SkiaSharp/wiki/Building-SkiaSharp
