### ISSUE TITLE
Wrap SkTextToPathIter

### ISSUE THREAD

**Issue by tdenniston** [mono/SkiaSharp#156]
Skia supports converting text (with a specified paint) to a series of SkPaths, which would be useful for me. The functionality is implemented in [`SkTextToPathIter`](https://github.com/mono/skia/blob/885431314fcbd2833483cf77d7fc3309e217b53f/src/core/SkTextToPathIter.h#L35).

**Comment by mattleibow** [comment]
@tdenniston This functionality is "already there" in the sence that it is accessed via `SKPaint`. That type is a private type (it only exists in the src folder). This type is used internally by [`SKPaint.GetTextPath`](https://github.com/mono/SkiaSharp/blob/master/binding/Binding/SKPaint.cs#L395) and it's overloads. If you really need the iterator, you can access it from the path [`SKPath.CreateIterator`](https://github.com/mono/SkiaSharp/blob/master/binding/Binding/SKPath.cs#L306)

**Comment by tdenniston** [comment]
@mattleibow Oh great, I didn't see that! Thanks :+1:
