### ISSUE TITLE
[QUESTION] is it possible export SKCanvas to SVG?

### ISSUE THREAD

**Issue by PieroCastillo** [mono/SkiaSharp#1560]
Hi there, Now I would want to make a drawing-app, I wonder, is it possible export SKCanvas(or SKImage) to SVG?  I'd be grateful for any help 👍🏻

**Comment by charlesroddie** [comment]
Strange idea. If the question is "can bitmaps be embedded in SVGs" the answer is yes, but one would want to do this as little as possible.

**Comment by wieslawsoltes** [comment]
https://docs.microsoft.com/en-us/dotnet/api/skiasharp.sksvgcanvas?view=skiasharp-1.68.2

https://github.com/mono/SkiaSharp/blob/bc2b0a2ace1e21754c3aeb4ba581a17df87dd9bb/tests/Tests/SKCanvasTest.cs#L437-L476

**Comment by PieroCastillo** [comment]
Thanks you, @wieslawsoltes ! :D
