### ISSUE TITLE
SkiaSharp.Views.Forms.WPF does not target .Net Core / .Net 5

### ISSUE THREAD

**Issue by deviousasti** [mono/SkiaSharp#1561]
The `SkiaSharp.Views.Forms.WPF` [package](https://www.nuget.org/packages/SkiaSharp.Views.Forms.WPF/2.80.3-preview.18) only targets .NETFramework 4.6.2.

https://github.com/mono/SkiaSharp/blob/b43c95f604040246229828ccd9a9537991600b26/nuget/SkiaSharp.Views.Forms.WPF.nuspec#L30

However, the components they depend on all support .Net Core or .Net standard.

   - OpenTK (>= 3.1.0)
   - OpenTK.GLControl (>= 3.1.0)
   - SkiaSharp (>= 2.80.3-preview.18)
   - SkiaSharp.Views.Desktop.Common (>= 2.80.3-preview.18)
   - SkiaSharp.Views.Forms (>= 2.80.3-preview.18)
   - SkiaSharp.Views.WindowsForms (>= 2.80.3-preview.18)
   - SkiaSharp.Views.WPF (>= 2.80.3-preview.18)
   - Xamarin.Forms (>= 4.6.0.772)
   - Xamarin.Forms.Platform.WPF (>= 4.6.0.772)
   
It should be possible to release a .net core or .net 5 target.
I'd be willing to submit a PR if someone could point me to the build files that need updating.

**Comment by xperiandri** [comment]
Any response? @mattleibow

**Comment by TechInterMezzo** [comment]
Are there any news about this? Or is there an alternative package?

**Comment by mattleibow** [comment]
I did not realise that forms was now running on netcore, so I can do that.

**Comment by mattleibow** [comment]
I have updated to the latest v4.x of Forms. v5.0 is out, but I don't need that and also I can let people update if need be.

The next preview on the preview feed should now be .NET Core friendly :)
