### ISSUE TITLE
[QUESTION] Is this library compatible with Xamarin HotRestart (iOS)?

### ISSUE THREAD

**Issue by omatrot** [mono/SkiaSharp#1562]
I'm using this package in a Xamarin.Forms project tageting iOS.

I have a native crash on startup, running on a local device.
I'm afraid it is because of a [limitation](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/deploy-test/hot-restart#limitations) around static libraries comming with this package.

Can you confirm?

**Comment by mattleibow** [comment]
Are you using HarfBuzz or just SkiaSharp. SkiaSharp should be working just fine as it is a dynamic framework.

**Comment by omatrot** [comment]
I'm just using SkiaSharp. Thanks for your answer.
