### ISSUE TITLE
[QUESTION] SKCanvas.DrawText on Synology fails to draw text

### ISSUE THREAD

**Issue by jsavell** [mono/SkiaSharp#1564]
I have an issue that seems similar to #1131 but the particular Linux flavor is Synology's DSM platform version 6.2.3 armv7l build.

In Windows, and Ubuntu, SKCanvas.DrawText renders text correctly when called from my dll, which is run as a plugin in a parent application. Running the same build on the Synology, there's nothing. No evidence of drawing text on the image and no errors that I can find.

Other operations like SKBitmap.Resize and SKCanvas.DrawCircle are working fine under the Synology.

I've tried the solution of copying a font over to /usr/share/fonts (the directory didn't exist on the Synology) to reference directly, but there was no change.

Here's an example of what I'm trying:

``` 
                    using (SKCanvas canvas = new SKCanvas(resizedImage))
                    {
                          var paint = new SKPaint
                            {
                                Color = SKColors.Blue,
                                IsAntialias = true,
                                Style = SKPaintStyle.Fill,
                                TextAlign = SKTextAlign.Center,
                                TextSize = 90,
                                Typeface = SKTypeface.CreateDefault()
                            };
                            var coord = new SKPoint(resizedImage.Width / 2, (resizedImage.Height + paint.TextSize) / 2);
                            canvas.DrawText("TEST", coord, paint);
                            canvas.Flush();

                            using (var image = SKImage.FromBitmap(resizedImage))
                            {
                                using (var data = image.Encode())
                                {
                                    using (var stream = new FileStream(outputFile, FileMode.Create, FileAccess.Write))
                                        data.SaveTo(stream);
                                }
                            }
                        }
```

I've tried this with no declared typeface, CreateDefault() like the above example, and various ones by familyname, but nothing changes.

Is there anything else I can try here?

Thanks

**Comment by Gillibald** [comment]
Load a Typeface via stream. That should work.

**Comment by jsavell** [comment]
Embedding a font file with my dll and loading that as a stream as you suggested worked great. Thank you so much.
