### ISSUE TITLE
SkiaSharp warning when generate ipa file

### ISSUE THREAD

**Issue by semi07** [mono/SkiaSharp#157]
When I build ipa file there are a lot of warning in output window. (more the 700 for each architecture)

How to reproduce:
1. Download SkiaSharp sample from https://github.com/mono/SkiaSharp/tree/master/samples
2. Open in VS properties of project SkiaSharp.Demo.Forms.iOS -> iOS IPA Option ->check "Build Ad-hoc/enterprise package (IPA)"
3. Run build of iOS project and go to output windows. There are more 1000 warnings:

```
1> warning: (armv7) /Users/builder/Jenkins/workspace/Components-SkiaSharp/native-builds/libSkiaSharp_ios/build/libSkiaSharp.build/Release-iphoneos/libSkiaSharp.build/Objects-normal/armv7/sk_xamarin.o unable to open object file: No such file or directory
1> warning: (armv7) /Users/builder/Jenkins/workspace/Components-SkiaSharp/native-builds/libSkiaSharp_ios/build/libSkiaSharp.build/Release-iphoneos/libSkiaSharp.build/Objects-normal/armv7/SkiaKeeper.o unable to open object file: No such file or directory
1> warning: (armv7) /Users/builder/Jenkins/workspace/Components-SkiaSharp/native-builds/libSkiaSharp_ios/build/libSkiaSharp.build/Release-iphoneos/libSkiaSharp.build/Objects-normal/armv7/sk_managedstream.o unable to open object file: No such file or directory
...
```

**Comment by mattleibow** [comment]
Thanks for reporting this. I will look into this and get back to you soon.

**Comment by mattleibow** [comment]
I am closing this as I don't get any warnings with this release. I was able to build, packang, publish and install the ipa without any warnings.
