### ISSUE TITLE
SkRect: Location done incorrectly

### ISSUE THREAD

**Issue by prasannavl** [mono/SkiaSharp#162]
Currently, the binding for `SkRect.Location` [here](https://github.com/mono/SkiaSharp/blob/5b1d054f88288d9532d91d1639b9c1099d589650/binding/Binding/Definitions.cs#L1668) is given as

```
public SKPoint Location {
            get { return new SKPoint (left, top); }
            set {
                left = value.X;
                top = value.Y; 
            }
        }
```

However, this doesn't just change just the location but also changes the size. So, the ideal one should be offset the bottom and right negatively to make sure the size is the same. 

~~The same also applies to `Offset` by position [here](https://github.com/mono/SkiaSharp/blob/5b1d054f88288d9532d91d1639b9c1099d589650/binding/Binding/Definitions.cs#L1798)~~

~~Because the above should be `Offset(pos.X, pos.Y, -pos.X, -pos.Y)` . That would be the correct way to offset a rectangle, semantically.~~

Both of the above are highly misleading currently, and fixing that are breaking changes. So, I'm opening an issue instead of a PR.

**Comment by mattleibow** [comment]
Hi @prasannavl Thanks for bringing this up. You are correct that `Location` is done incorrectly. We need to look at that, but about `Offset`, that does just move the rect.
https://github.com/mono/SkiaSharp/blob/5b1d054f88288d9532d91d1639b9c1099d589650/binding/Binding/Definitions.cs#L1790

    var rect = new SKRect(0, 0, 100, 100);
    rect.Offset(30, 30);
    
    // rect still has a width/height of 100

**Comment by prasannavl** [comment]
@mattleibow, `Offset` has two overloads. One that takes a `SKPoint`. I'm guessing you missed the code piece in my above post.

https://github.com/mono/SkiaSharp/blob/5b1d054f88288d9532d91d1639b9c1099d589650/binding/Binding/Definitions.cs#L1798

That doesn't just move the Rect - It should use `Offset(pos.X, pos.Y, -pos.X, -pos.Y)`

**Comment by mattleibow** [comment]
@prasannavl I am not sure exactly what you mean about `Offset`... The `Offset(SKPoint)` is just an overload for `Offset(float, float)`. The point version does not set the location, but rather moves the whole rect by X and Y.

Your snippet will both move the origin AND shrink the rect two-fold. For example a rect at `{X=10, Y=10, Width=10, Height=10}`. If you offset with `SkPoint(2, 2)` the new rect will be `{12, 12, 6, 6}`. Maybe you are mixing the fact that rectangles in SkiaSharp are left-top-right-bottom, not width-height?

**Comment by prasannavl** [comment]
@mattleibow, you're correct. My bad. Sorry about that. `Offset` is correct. I was working with a lot of `Rect` in my own raw WinApi (https://github.com/prasannavl/WinApi/) wrappers, where I had manipulated the width and height. Seemed like I just needed some sleep! 

I'm striking out the original Offset related things from the post to keep things in perspective.

**Comment by mattleibow** [comment]
@prasannavl Great! Thanks for the issue, I'll look at it soon.

**Comment by mattleibow** [comment]
All right. Did some thinking. I am going to close this issue because there is nothing that I can really do now.

If I change the way it works, I am changing released behavior and I am being inconsistent with the way changing the Top or Left (those move the point and change the size). If I remove it, I am removing released behavior. The only thing really to do is leave it as is and just add documentation for it.

**Comment by prasannavl** [comment]
@mattleibow, I take it there isn't much I can do for you to reconsider? 

SkiaSharp is still in its infancy. I think this is the perfect time to fix semantic changes, bumping the version. The later it is, the more difficult it is. I think its a bad idea to leave bugs like this unfixed, just because its a breaking change. 

I don't think there are an enormous amount of project that are based off SkiaSharp today. So, the other libraries basing on this behavior should not have too much difficulty catching up today.

**Comment by mattleibow** [comment]
@prasannavl I'll see what I can do... discuss with manager and all that.

**Comment by prasannavl** [comment]
Great. Appreciate having an open mind. :)

Sent from Outlook for Android



On Mon, Nov 7, 2016 at 10:26 AM +0530, "Matthew Leibowitz" <notifications@github.com<mailto:notifications@github.com>> wrote:


@prasannavl<https://github.com/prasannavl> I'll see what I can do... discuss with manager and all that.

-

**Comment by mattleibow** [comment]
I had a look, and I think you are right in all accounts:
 - young framework, so change "OK"
 - more consistent, with other frameworks
 - more intuitive, the location should move, not resize

Thanks for your support!

**Comment by prasannavl** [comment]
Great! Nice to see that feedback is taken well :)
