### ISSUE TITLE
[QUESTION] Radial gradient with different axis points like Inkscape

### ISSUE THREAD

**Issue by wstaelens** [mono/SkiaSharp#1623]
![skiasharp radial](https://user-images.githubusercontent.com/7447285/107530800-7c65c480-6bbc-11eb-8682-dd0715820c15.PNG)

In SkiaSharp (C#) How do you draw a radial gradient with different axis points like we can do in Inkscape. (see image)?

**Comment by mattleibow** [comment]
You probably want to do a normal radial gradient, but with a local matrix?
