### ISSUE TITLE
Extracting PathEffect information

### ISSUE THREAD

**Issue by tdenniston** [mono/SkiaSharp#163]
Currently, once you assign a PathEffect to a paint via one of the `SKPathEffect.Create*()` methods, there's no way to later tell what type of path effect is applied to a paint, or to extract its information (e.g. for dash effects, I'd like to be able to fetch the interval data from the paint's path effect property).

I'm not sure if this functionality exists directly on the native Skia side. Certainly there are different subclasses for the different path effect types, so if nothing else the functionality exists via RTTI (though I don't know if native Skia is built with RTTI enabled). Perhaps the different subclasses could be exposed with managed subclasses, with the various fields exposed as well.

It's fine if you decide this issue is out-of-scope for SkiaSharp, just thought it was worth raising.

**Comment by mattleibow** [comment]
@tdenniston I had a look at this case, and I don't see a way to get this information from the shader/effect/filter. Right now, even the C++ API just returns the base type.

Until this information is actually on a public API, we will all have to suffer :)

**Comment by tdenniston** [comment]
@mattleibow Ok, thanks for looking into it!
