### ISSUE TITLE
SKTypeface.FromFamilyName() not working with generic fonts

### ISSUE THREAD

**Issue by tdenniston** [mono/SkiaSharp#166]
I can't seem to get `SKTypeface.FromFamilyName()` to recognize the generic font family names. For example, the following should render the text with a serif font:

```
using (var paint = new SKPaint()) {
    paint.IsStroke = false;
    paint.Typeface = SKTypeface.FromFamilyName("serif", SKTypefaceStyle.Normal);
    paint.TextSize = 24;
    paint.Color = SKColors.Black;
    paint.IsAntialias = true;

    canvas.Translate(5, 50);
    canvas.DrawText("This should be serif", 0, 0, paint);
}
```

But on my system, it renders like this:

![serif-bug-1](https://cloud.githubusercontent.com/assets/934815/19601541/c4c4af02-9777-11e6-8b46-cdaf348f7611.png)

Using the same code in a [Skia Fiddle](https://fiddle.skia.org/c/2c8e94fe13f751bca5cd2c75dc37cb6d):

```
void draw(SkCanvas* canvas) {
    canvas->drawColor(SK_ColorWHITE);
    canvas->translate(5, 50);

    SkPaint paint;
    paint.setStyle(SkPaint::kFill_Style);
    paint.setTypeface(SkTypeface::MakeFromName("serif", SkFontStyle()));
    paint.setTextSize(24);
    paint.setColor(0xff000000);
    paint.setAntiAlias(true);

    std::string str("This should be serif");
    canvas->drawText(str.c_str(), str.size(), 0, 0, paint);
}
```

It renders with a serif font like this:

![serif-bug-2](https://cloud.githubusercontent.com/assets/934815/19601592/f21c07c0-9777-11e6-9ae0-b465f1d6a4da.png)

I am using SkiaSharp 1.54.1 on Windows 7.

**Comment by mattleibow** [comment]
@tdenniston I had some more looks at this. I think it is actually a feature of the OS rather than skia that makes it work. DirectWrite tries, and fails, to find the font named "serif". Then just falls back to the default platform font: Segoe UI.

I created an issue on skia to confirm this: https://bugs.chromium.org/p/skia/issues/detail?id=5893

**Comment by tdenniston** [comment]
It looks like they are saying "not a bug" which is fine. Interestingly, they will have to solve this problem somehow in a cross-platform way when they implement SVG parsing (which is currently planned, according to their roadmap).

**Comment by tdenniston** [comment]
I was going to use that same list myself, but I wondered: are those actually part of the spec? Or are they just examples?

**Comment by mattleibow** [comment]
I see what you mean. I think every platform might be totally different. I wonder how this is done in reality - lots of docs and specs, but who is the actual mainstream SVG implementation that we should be looking at? is there a libsvg or something?

**Comment by tdenniston** [comment]
I don't believe there is a reference implementation. There is librsvg (https://wiki.gnome.org/Projects/LibRsvg) which I haven't used, but have heard is ok but lacking some features. We could also take a look at Mozilla's SVG renderer or Inkscape. Not sure what license difficulties there might be in examining their code though.

**Comment by mattleibow** [comment]
Closing this as this is not really a skia feature, and implementing this is not as straight-forward as picking a font from a list. More thought has to go into this and can be re-opened.
