### ISSUE TITLE
SkiaSharp Views - Touch Events

### ISSUE THREAD

**Issue by rac146** [mono/SkiaSharp#167]
With Xamarin Forms, we can hook into 3 built-in Gesture Recognizers: Pan, Pinch, and Tap. Pan and Pinch are working wonderfully, but unfortunately the Tap gesture does not return X and Y coordinates of the touch, which renders it basically useless for anything Skia-related. Would it be possible to create a custom touch event in the new SkiaSharp Views that would return X and Y coordinates back to the Xamarin Forms code? Or perhaps there's a way to extend these new views and do that our self?

Thanks,
Robert

**Comment by mattleibow** [comment]
@rac146 Good question... I think this has been asked a few times in the Xamarin.Forms world... Before I add this, I want to find out why the X.F guys actually left that info out.

Also, I would strongly suggest you have a look at what other devs have done with regards to X.F... Maybe check the forums (http://forums.xamarin.com/categories/xamarin-forms) or chat (https://gitter.im/xamarin/Xamarin.Forms) and see - maybe there is something, or a better way to get touch co-ordinates.

If you find anything, be sure to share so that we can do this properly inside SkiaSharp.

This is something I am considering since I am making a small 2D game on the side... touch is required for buttons and things like that...

**Comment by rac146** [comment]
Thanks Matt!

For now, I'm able to get the coordinates by extending the ContentPage across the Native Platforms. From here, you can override the touch events and send the coordinate info back to the PCL. The same principal could be applied directly to the SKNativeViews as one way to solve the problem. Would be better if the built-in gestures for Xamarin Forms could support the coordinates though.

Android Example:

```
    public class ClickPageRenderer : PageRenderer
    {
        public IClickPageController iClickView;
        
        protected override void OnElementChanged(ElementChangedEventArgs<Page> e)
        {
            base.OnElementChanged(e);

            if (e.OldElement != null || Element == null)
            {
                return;
            }

            if(e.NewElement != null)
            {
                iClickView = (IClickPageController) e.NewElement;
            }

        }

        public override bool OnInterceptTouchEvent(MotionEvent e)
        {
            if (e.PointerCount == 1)
            {
                switch (e.Action)
                {
                    case MotionEventActions.Down:

                        iClickView.SendTap(e.GetX(), e.GetY(), false);

                        break;
                    case MotionEventActions.Up:

                        iClickView.SendTap(e.GetX(), e.GetY(), true);

                        break;
                    default:

                        break;
                }
            }

            return base.OnInterceptTouchEvent(e);
        }

    }
```

**Comment by MisterWilde** [comment]
I was trying to extend the SkiaCanvasView / SkiaCanvasViewRenderer to intercept touch events on iOS, Android and UWP. Unfortunately, I can't do that using the nuget package as the classes and interfaces required to write your own implementation of SkiaCanvas, or extending the SKCanvasViewRenderer, are inaccessible. But I will try the Content Page customization.

**Comment by mattleibow** [comment]
I am closing this as I won't be adding touch events to the SkiaSharp views. This is primarily a forms question, so it might be better to ask the Forms guys. However, I will be making the forms renderers public in a future release (probably v1.56 since that just became a thing)
