### ISSUE TITLE
SKRect constructor with width/height broken

### ISSUE THREAD

**Issue by joreg** [mono/SkiaSharp#17]
according to https://developer.xamarin.com/api/member/SkiaSharp.SKRect.Create/p/System.Single/System.Single/System.Single/System.Single/

this constructor should take: x, y, width, height
but apparently it is more like: left, top, right, bottom#

(using libskia_windows.dll x86)

**Comment by migueldeicaza** [comment]
I agree, i was writing this documentation today, and I found this to be confusing.

**Comment by mattleibow** [comment]
@migueldeicaza @joreg That is the `Create` method. There is a constructor that is TLRB: https://developer.xamarin.com/api/constructor/SkiaSharp.SKRect.SKRect/p/System.Single/System.Single/System.Single/System.Single/

I can't overload the constructor, but I wanted to do that as a helper method in case you are coming from some other rect object. I didn't want to force the user to calculate the TLRB when he had the XYWH coordinates.

**Comment by mattleibow** [comment]
This is the SKRect definition:

    public struct SKRect { 
        public float Left, Top, Right, Bottom; 
        public SKRect (float left, float top, float right, float bottom) { 
            Left = left; 
            Right = right; 
            Top = top; 
            Bottom = bottom; 
        } 
        public static SKRect Create (float width, float height) { 
            return new SKRect (0, 0, width, height); 
        } 
        public static SKRect Create (float x, float y, float width, float height) { 
            return new SKRect (x, y, x + width, y + height); 
        } 
    } 


https://github.com/mono/SkiaSharp/blob/master/binding/Binding/Definitions.cs#L402-L421https://github.com/mono/SkiaSharp/blob/master/binding/Binding/Definitions.cs#L402-L421

**Comment by mattleibow** [comment]
Note from Miguel:

 > The problem with the other method is this, what direction is the coordinate system?
 > Because the math on that factory method is wrong
 > Depends if you consider “Y” going up or down
 > Hence, I would rather eliminate the confusion by removing the helper method

**Comment by mattleibow** [comment]
Before removing, just want to check if any platforms have a Y as down...

**Comment by mattleibow** [comment]
I had a look some more at the Skia API and see this:
https://github.com/mono/skia/blob/xamarin-mobile-bindings/include/core/SkRect.h

    static SkRect SK_WARN_UNUSED_RESULT MakeWH(SkScalar w, SkScalar h);
    static SkRect SK_WARN_UNUSED_RESULT MakeIWH(int w, int h);
    static SkRect SK_WARN_UNUSED_RESULT MakeSize(const SkSize& size);
    static SkRect SK_WARN_UNUSED_RESULT MakeLTRB(SkScalar l, SkScalar t, SkScalar r, SkScalar b);
    static SkRect SK_WARN_UNUSED_RESULT MakeXYWH(SkScalar x, SkScalar y, SkScalar w, SkScalar h);

The `SKRect` type does not have a constructor, but rather several overloads of the Make (or Create) methods

I think we need to decide what we want for the constructor. Or even no constructor. I am in favour of XYWH as the constructor and LTRB as the Create as this is what .NET usually does.

**Comment by mattleibow** [comment]
So we have several options:

1. No constructor (just the default)
2. XYWH constructor (with CreateLTRB)
3. LTRB constructor (with CreateXYWH)

I vote 2.

**Comment by joreg** [comment]
i'd vote for no constructor and all helpers called: From...
- no constructor because then there are not 2 different ways to create a rect
- From.... because FromXYWH, FromLTRB,... reads more suitable than Make.. or Create..

**Comment by tebjan** [comment]
I also vote for no constructor to have everything in one place.
The same might be true for other basic shapes as well for consistency.

**Comment by migueldeicaza** [comment]
I do not see an advantage on making the change, so let us keep the code as is for now.
