### ISSUE TITLE
[FEATURE] HEIF decoder and encoder  

### ISSUE THREAD

**Issue by MichalJan008** [mono/SkiaSharp#1700]
Since iPhone 11 the default image format for pictures taken is HEIF (HEIC), not JPEG anymore (unless the user changes the 'compatibility setting' in the camera settings). For my app this is a blocker, as no picture can be decoded. 

I wish the SkiaSharp had built-in support for HEIF, so that I could decode and encode SKBitmap directly. 

I've tried to add support for HEIF decoding using external libs (I've tried ImageMagick), but it appears that bindings are for this library available only for Windows and Mac (but not iOS, Android).  (Project Magick.NET).
Even If .Net bindings were available for these platforms, I would still need to use extra library, and apply conversion between formats (from SkiaBitmap to ImageMagick and back). 

HEIF/HEIC support is inevitable, as more and more software will use it. But even if not, the sole Apple move towards HEIF is in my humble opinion enough to consider expediting the support.

**Comment by Ziriax** [comment]
I guess the reason why this isn't in Skia yet (and hence SkiaSharp) is licensing?

Actually, I believe that on some Android devices, Skia does support HEIF, because they already pay a license for the HEVC encoder.

Technically supporting HEIF is actually a no-brainer, just use https://github.com/strukturag/libheif, or its .NET Standard wrapper, https://www.nuget.org/packages/LibHeifSharp

**Comment by softlion** [comment]
I agree with MichalJan008.
HEIF is at least half the size of JPG with a much better quality.

And it starts to be an issue in the picture picker.

**Comment by mattleibow** [comment]
I'll have to see. The licence is special :)

**Comment by fmnamado** [comment]
Hello, has been any update? When can we count on this? Thank you.

**Comment by SrejonKhan** [comment]
Hello, is there any update on this?

**Comment by mattleibow** [comment]
I think this is all licensing. Right now, I see this in the skia headers:

```cpp
#if __has_include("HeifDecoderAPI.h")
    #include "HeifDecoderAPI.h"
#else
    #include "src/codec/SkStubHeifDecoderAPI.h"
#endif
```

I assume it just needs to be present for it to be enabled, the trick is that enabling it may be as legally free as we want it.

The license is `GNU Lesser General Public License version 3.0`

However, as @ziriax mentions, you can actually decode using https://www.nuget.org/packages/LibHeifSharp and decode to a `HeifImage` and then get the `HeifPlaneData` which gives you a pointer to the memory. You can then create a `SKImage` around that data.

**Comment by mattleibow** [comment]
I am going to close this issue for now unless a new library appears that can load HEIF with a better license. But for now, the actual usage is pretty simple and SkiaSharp provides easy ways to use it.
