### ISSUE TITLE
[QUESTION] [iOS] XCode 12.5 not signing app as libSkiaSharp.framework is not signed

### ISSUE THREAD

**Issue by taublast** [mono/SkiaSharp#1701]
Hi, 

Had no problems at all before upgraded XCode to 12.5, now just cannot sign any iOS app containing SkiaSharp nuget. 
It throws a nice

> MessagingRemoteException: An error occurred on client Build169000292 while executing a reply for topic xvs/build/execute-task/XamarinTestApp.iOS/31c782e002fCodesign
> AggregateException: One or more errors occurred.
> DirectoryNotFoundException: Could not find a part of the path '/Users/Airboom/Library/Caches/Xamarin/mtbs/builds/XamarinTestApp.iOS/31c782e90715fd993ed01e15963fc6f699e2dc9661442e7b92edfc01c6ad08cb/bin/iPhoneSimulator/Debug/XamarinTestApp.iOS.app/Frameworks/libSkiaSharp.framework/_CodeSignature'.	XamarinTestApp.iOS			
> 

As you can see the `libSkiaSharp.framework` is not containing a `_CodeSignature ` subfolder as it is not signed. I cannot understand does this come from a new apple move requiring third-party libs to be signed, or it is a VS or Xcode bug not signing the lib with same keys as the containing app. 

Any help would be much appreciated, totally blocked.

**Comment by taublast** [comment]
Well what tricked me into thinking it was SKiaSharp in cause that apps were signed ok for simulator. But for real device it throws a 

> Failed to codesign 'bin/iPhone/Debug/XamarinTestApp.iOS.app': Warning: unable to build chain to self-signed root for signer "Apple Development: TOTO (HW3HM3UBCO)"
> /Users/Airboom/Library/Caches/Xamarin/mtbs/builds/XamarinTestApp.iOS/31c782e90715fd993ed01e15963fc6f699e2dc9661442e7b92edfc01c6ad08cb/bin/iPhone/Debug/XamarinTestApp.iOS.app: errSecInternalComponent

Will dig further must be some certificates related error..

**Comment by taublast** [comment]
Would open this again, but cannot: i finally managed to recompile and sign for real device without SkiaSharp, but it fails after adding skia nuget with the above error.. Another bug was submitted by @Pequeno0 let's stick to that thread:
https://github.com/mono/SkiaSharp/issues/1702

**Comment by KaeTar** [comment]
If you are chasing this problem it is likely that you created a certificate after January 28, 2021 when apple changed over to their new Apple Worldwide Developer Relations Intermediate Certificate (intermediate certificate).   See [Here](https://developer.apple.com/support/expiration/) for details.   Download and install the new certificate on your mac and this error should go away.   Get the new cert [here](https://www.apple.com/certificateauthority/AppleWWDRCAG3.cer)
