### ISSUE TITLE
[BUG] SkiaSharp 2.80.2 upgrade throws TypeInitializationException in SkiaSharpNative.CheckNativeLibraryCompatible

### ISSUE THREAD

**Issue by Mindfulplays** [mono/SkiaSharp#1715]
**Description**
I upgraded SkiaSharp (nuget) for a console .NET (Windows 10) project from 1.x to 2.80.2.

Calling `Sk* methods` results in:

```
Unhandled Exception: System.TypeInitializationException: The type initializer for 'SkiaSharp.SKObject' threw an exception. ---> System.InvalidOperationException: The version of the native libSkiaSharp library is incompatible with this version of SkiaSharp. Supported versions of the native libSkiaSharp library are in the range [80.2, 81.0).
   at SkiaSharp.SkiaSharpVersion.CheckNativeLibraryCompatible(Version minSupported, Version current, Boolean throwIfIncompatible)
   at SkiaSharp.SkiaSharpVersion.CheckNativeLibraryCompatible(Boolean throwIfIncompatible)
   at SkiaSharp.SKObject..cctor()

```

I added `($"SkiaSharp version: {SkiaSharpVersion.Native}; minimum required: {SkiaSharpVersion.NativeMinimum}");` to my logging and that prints:

```
SkiaSharp version: 0.0; minimum required: 80.2
```

It looks like libSkiaSharp.dll is not being copied.
Wild conjecture: Using the SkiaSharp sample project as an example, it looks like there needs to be an explicit reference to libSkiaSharp (?).

**Code**

Any SkObject code should suffice, here is an example that I am using:

```
          using (var encodedData = skImage.Encode(SKEncodedImageFormat.Webp, webpQuality))
          using (var webpOutStream = File.OpenWrite(outFile))
```

**Expected Behavior**

No TypeInitializationException should be thrown.

**Actual Behavior**

TypeInitializationException should not be thrown.

**Basic Information**

- Version with issue: 2.80.2
- Last known good version:  1.68.2.1
- IDE:  Visual Studio Community
- Platform Target Frameworks: 
  - Windows Classic: Windows 10 Pro x64 10.0.19042 
- Target Devices:   Desktop PC
  
EDIT: Updated actual exception (`TypeInitializationException`).

**Comment by mattleibow** [comment]
This was fixed in a later version. Either try the 2.80.4 patch or even better the new 2.88.x versions.
