### ISSUE TITLE
Does the drawing string support Hindi language?

### ISSUE THREAD

**Issue by e-jlion** [mono/SkiaSharp#1719]
Hi :
    I use the DrawTextmethod to draw Hindi, such as "परीक्षण भेजें" After drawing by Paint, the result of drawing on the Linux system and on the windows system  is "[][][][][][][]; Help to see if you need a font library or how to solve it

Core Code：

                using (var paint = new SKPaint())
                {
                    paint.TextSize = 64.0f;
                    paint.IsAntialias = true;
                    paint.Color = new SKColor(0x42, 0x81, 0xA4);
                    paint.IsStroke = false;

                    canvas.DrawText(sendText, new SKPoint(20, 40), paint);
                }

**Comment by mattleibow** [comment]
SkiaSharp does support drawing any character, however, not directly. The skia engine rather just does the operation of taking shaped text and rendering them.

To get this shaped text, I would suggest using https://github.com/toptensoftware/RichTextKit as that is a brilliant library that allows you to do pretty much anything with text. And it supports all sorts of formatting and layout.
