### ISSUE TITLE
UWP - SkiaSharp to draw editable shapes

### ISSUE THREAD

**Issue by Goldstrike** [mono/SkiaSharp#172]
Sorry for my second question, that is not an issue...
But I'm looking for an easy way that allowing a user to add basic shapes (rectangle, ellipse, ...) on a area (like canvas) that contains a photo.
Then the shape must be moved on the area, resizable and customizable (foreground color).
I have looked to samples but I didn't found a similar case: is it feasable through SkiaSharp?

**Comment by mattleibow** [comment]
Hi again @Goldstrike, SkiaSharp is not really a editor so probably the answer is no. However, SkiaSharp can be used as the actual visualization/drawing engine. 

Basically, you will have to write the logic to handle the draw, create and resizing of shapes via touch/mouse. Then SkiaSharp can do the simple drawing. Think of SkiaSharp as the `canvas.DrawRect(x, y, w, h);` bit - it draws a rectangle, but you will still have to do the work to translate swipes into a drag/resize operation.
