### ISSUE TITLE
[QUESTION] libSkiaSharp not being deployed.

### ISSUE THREAD

**Issue by giovani-luigi** [mono/SkiaSharp#1726]
I have just created a new Windows Forms .NET Framework 4.6.1 project, added SkiaSharp nuget package (2.80.2), and the native bins (libSkiaSharp.dll) are not deployed to the output directory. 

I have tested with this small project to check why I could not get it to work in my other project, which is a .NET Framework Windows Forms that depends on a .NET Standard 2.0 class library that then depends on the SkiaSharp.

I am compiling as AnyCPU. I assume this issue was solved...

I am using Visual Studio 2019, 16.10.0

[SkiaDemo.zip](https://github.com/mono/SkiaSharp/files/6706216/SkiaDemo.zip)

**Comment by mattleibow** [comment]
This should now be fixed in 2.80.3 or the 2.88.0 previews.

Previously, the libSkiaSharp.dll might not have been copied if it was a library project. However, it is now always copied.
