### ISSUE TITLE
[BUG]The type initializer for 'SkiaSharp.SKImageInfo' threw an exception while using SkiaSharp in alpine3.13-amd64 docker

### ISSUE THREAD

**Issue by HemalathaChiranjeevulu** [mono/SkiaSharp#1727]
**Description**

Facing error while using SkiaSharp library in Alpine docker

**Code**

        SKBitmap bitmap = new SKBitmap(100, 100, SKImageInfo.PlatformColorType, SKAlphaType.Premul);
        var surface = SKSurface.Create(bitmap.Info);
        SKCanvas canvas = surface.Canvas;
        canvas.Clear(SKColors.White);
        var paint = new SKPaint();
        paint.IsAntialias = true;
        paint.Color = SKColors.Red;
        paint.StrokeWidth = 3;
        string fontName = SKTypeface.Default.FamilyName;
        canvas.DrawCircle(50, 50, 25, paint);
        var image = SKImage.FromBitmap(bitmap);
        var data = surface.Snapshot().Encode(SKEncodedImageFormat.Jpeg, 80);
        MemoryStream outputStream = new MemoryStream();
        data.SaveTo(outputStream);
        outputStream.Position = 0;
**Expected Behavior**

Should draw the circle as expected.

**Actual Behavior**

Below exception thrown 
System.TypeInitializationException
  HResult=0x80131534
  Message=The type initializer for 'SkiaSharp.SKImageInfo' threw an exception. 

Inner Exception 1:
DllNotFoundException: Unable to load shared library 'libSkiaSharp' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: Error loading shared library liblibSkiaSharp: No such file or directory

**Basic Information**

Version with issue: SkiaSharp 2.80.2
IDE: Microsoft Visual Studio Professional 2019, Version 16.9.0
Platform Target Frameworks: ASP.NET Core 5.0 targeted application with Alpine docker
Note: Already we have **tried to resolve this issue by installing SkiaSharpNativeAssets.Linux, SkiaSharpNativeAssets.NoDependencies** packages. But nothing helps.

Please find the sample to replicate the issue:
[DockerApplication.zip](https://github.com/mono/SkiaSharp/files/6710409/DockerApplication.zip)

**Comment by nesc58** [comment]
Hi,
your Dockerfiles seems to be incorrect.

```
> [internal] load metadata for mcr.microsoft.com/dotnet/sdk:5.0.6-alpine3.13-amd64:
------
failed to solve with frontend dockerfile.v0: failed to create LLB definition: mcr.microsoft.com/dotnet/sdk:5.0.6-alpine3.13-amd64: not found
```

I have changed the SDK and added some packages like libpng, libjpeg, fontconfig and very importend: libc6-compat for linking `ld-linux-x86-64.so.2`. There are no more exceptions on my machine

```
FROM mcr.microsoft.com/dotnet/aspnet:5.0.6-alpine3.13-amd64 AS base
RUN apk update && apk add --no-cache bash libc6-compat libbsd-dev fontconfig libpng libjpeg libjpeg-turbo
RUN ln -s /lib64/ld-linux-x86-64.so.2 /lib/ld-linux-x86-64.so.2
```

**Comment by mattleibow** [comment]
Thanks @nesc58 for helping with this!
