### ISSUE TITLE
[QUESTION] Support for RGB/BGR 24 bytes per pixel format?

### ISSUE THREAD

**Issue by romen-h** [mono/SkiaSharp#1735]
I am trying to get some pixel data into an `SKImage` or `SKBitmap` for drawing it to a canvas without having to perform an expensive copy to a 4 channel format or encoding/decoding the image. This pixel data is the same format that a `System.Drawing.Bitmap` with `PixelFormat.Format24bppRgb` uses. It seems that `SKImageInfo` is not able to represent this pixel format though.

Here is the line I'm using to make my SKImageInfo:
```csharp
SKImageInfo info = new SKImageInfo(myImage.Width, myImage.Height, SKColorType.Rgb888x, SKAlphaType.Opaque);
```

This results in an SKImageInfo that has `BytesPerPixel = 4`.  
I can't find any other color type that would match this pixel format with 3 bytes per pixel, even though this is a very common format that .bmp files store internally. (BGR vs RGB aside)

Are 24bpp RGB/BGR bitmaps not supported?  
Is there a way to construct an SKImageInfo that has `BytesPerPixel = 3` and its other properties with the specific values I need?

**Comment by romen-h** [comment]
Upon reviewing my question I noticed the "32-bit color" in the description for `SKColorType.Rgb888x`.
Clearly that's not the color type I need, so my question still stands; Is it possible to make an `SKImageInfo` that describes this 24-bit RGB pixel data?

**Comment by mattleibow** [comment]
I do not believe skia supports a 24-bit color type. It supports reading 8-bit, 16-bit and 32-bit colors and a few floating point colors.

I believe pixel sizes are for optimizing memory operations with either 1, 2 or 4 bytes. 3 bytes are a bit harder to copy and things like that. You might find that you get better performance with a single load and then faster operations vs a quick load and then all operations need additional math.

I would suggest asking on the skia engine discussion site for details on this: https://groups.google.com/g/skia-discuss
