### ISSUE TITLE
[FEATURE] Views for Uno WinUI 3 target

### ISSUE THREAD

**Issue by anpin** [mono/SkiaSharp#1742]
**Is your feature request related to a problem? Please describe.**

Please add Views for Uno WinUI 3 target. As of now I can't use SkiaSharp.Views.Uno in project created with unoapp-winui, nor can I install the SkiaSharp.Views.WinUI into the platform implementations.

**Describe the solution you'd like**

Add SkiaSharp.Views.UnoWinUI nuget which will depend on Uno.WinUI rather then Uno.UI

**Comment by jeromelaban** [comment]
@anpin We (uno team) were waiting on the WinUI on Windows support for SkiaSharp to land, which is now the case. We'll be able to do so now that it's done!

**Comment by anpin** [comment]
@jeromelaban thank you for you effort, can't wait to try it out

**Comment by jeromelaban** [comment]
We can keep this issue opened until this will be done :)
