### ISSUE TITLE
[ISSUE] Xamarin Forms - Reference to "libSkiaSharp.framework" in the iOS project with yellow exclamation mark

### ISSUE THREAD

**Issue by Auto72** [mono/SkiaSharp#1744]
**Description**

I have a Xamarin Forms project (iOS and Android) where I use the "SkiaSharp.Views.Forms" library (ver. 2.80.3 and before 2.80.2).
In the iOS project I get the following reference added, every time I open the project.
"C:\Users\username\\.nuget\packages\skiasharp\2.80.3\buildTransitive\xamarinios1.0\..\..\build\xamarinios1.0\libSkiaSharp.framework"

To compile and run the App, this reference needs to be removed.

**Expected Behavior**

No exclamation mark in the reference or no reference at all to:

"C:\Users\username\\.nuget\packages\skiasharp\2.80.3\buildTransitive\xamarinios1.0\..\..\build\xamarinios1.0\libSkiaSharp.framework"

**Actual Behavior**

The following reference is present every time the project is opened and needs to be removed manually to comple and run:

"C:\Users\username\\.nuget\packages\skiasharp\2.80.3\buildTransitive\xamarinios1.0\..\..\build\xamarinios1.0\libSkiaSharp.framework"

**Screenshots**
![1](https://user-images.githubusercontent.com/52780377/125769621-dc96b42c-82be-46f1-a60e-f9b60bacdb7f.png)

Is there a solution to this problem?
Thanks.

**Comment by mattleibow** [comment]
This was a bug in VS that has recently been fixed:
https://developercommunity.visualstudio.com/t/why-NativeReference-cannot-recoginze-msb/1251187?space=8&q=NativeReference

**Comment by Auto72** [comment]
I am now with Visual Studio 2022, same project, and I get the same error, without seeing the reference with the yellow mark.

![2](https://user-images.githubusercontent.com/52780377/145079831-4c92d8af-c6db-4006-9fd0-c52758188dfe.png)
![3](https://user-images.githubusercontent.com/52780377/145079849-5118a86c-249d-4230-aec0-36a4cc73a60d.png)

If I try to run the project on iOS device I get the following:
![4](https://user-images.githubusercontent.com/52780377/145080216-0b988d76-755f-41b6-9cae-7c804e8b59ff.png)

Is there a solution for this issue?
Thanks.
