### ISSUE TITLE
[QUESTION] Why does SKFontStyleWidth not work correctly with some fonts?

### ISSUE THREAD

**Issue by washamdev** [mono/SkiaSharp#1763]
I am using SkiaSharp 2.80.2 on Windows 10 with a .NET Core project.

I am running into a weird issue where it appears that `SKFontStyleWidth` does not change a font's width at all once it's written out on a canvas. I am attempting to write using the Century Gothic font, and I noticed this issue when I used `SKTypeface.FromFamilyName` to create a `SKTypeface` using `SKFontStyleWidth.UltraCondensed` first, then `SKFontStyleWidth.UltraExpanded` after, and both times, the `FontWidth` property is set to 5 (which if that maps to the `SKFontStyleWidth` enum, would be `Normal`, instead of what I specified):

```
fontFamily = SKTypeface.FromFamilyName("Century Gothic", SKFontStyleWeight.Bold, SKFontStyleWidth.UltraCondensed, SKFontStyleSlant.Italic);
{SkiaSharp.SKTypeface}
    FamilyName: "Century Gothic"
    FontSlant: Italic
    FontStyle: {SkiaSharp.SKFontStyle}
    FontWeight: 700
    FontWidth: 5
    GlyphCount: 666
    Handle: 0x000002b080612d50
    IgnorePublicDispose: true
    IsBold: true
    IsDisposed: false
    IsFixedPitch: false
    IsItalic: true
    OwnsHandle: true
    Style: BoldItalic
    TableCount: 18
    UnitsPerEm: 2048
fontFamily = SKTypeface.FromFamilyName("Century Gothic", SKFontStyleWeight.Bold, SKFontStyleWidth.UltraExpanded, SKFontStyleSlant.Italic);
{SkiaSharp.SKTypeface}
    FamilyName: "Century Gothic"
    FontSlant: Italic
    FontStyle: {SkiaSharp.SKFontStyle}
    FontWeight: 700
    FontWidth: 5
    GlyphCount: 666
    Handle: 0x000002b080612d50
    IgnorePublicDispose: true
    IsBold: true
    IsDisposed: false
    IsFixedPitch: false
    IsItalic: true
    OwnsHandle: true
    Style: BoldItalic
    TableCount: 18
    UnitsPerEm: 2048
```

I also tried using the Arial font. In that font's case, `SKFontStyleWidth.UltraCondensed` resulted in a `FontWidth` of 3, while `SKFontStyleWidth.UltraExpanded` resulted in 5. I would have expected a much wider variance between 3 and 5.

Can someone help me understand what's going on here, or if I'm doing something wrong in my attempt to change letter spacing for a font?

**Comment by Gillibald** [comment]
Are you sure a ultra condensed variant of `Century Gothic` is installed on your system?

**Comment by washamdev** [comment]
@Gillibald Forgive me, I don't 100% understand how fonts work in this regard. I have been using Inkscape to generate SVGs that include text, and in their GUI, you can specify the "letter spacing" for any font:

![image](https://user-images.githubusercontent.com/4692325/128725657-8a2a1e5a-6bd3-4451-aa4f-0f03bb0ebd6c.png)

In the case of Arial, I can set letter spacing to -6px to make it look nice and condensed. I was trying to do the same thing with SkiaSharp, and all I could find to duplicate that kind of reduction in letter spacing was to use `SKFontStyleWidth`, but it's not working the same. Am I just misunderstanding something to expect SkiaSharp to have the same capabilities as Inkscape? Or is there a different way to achieve different letter spacing for all fonts in SkiaSharp?

**Comment by Gillibald** [comment]
That feature isn't something that works out of the box. Inkscape probably adjusts the spacing between glyphs. To achieve the same with SkiaSharp you need to manually adjust the glypg layout. That is something that needs more work.

**Comment by washamdev** [comment]
@Gillibald Interesting, didn't realize that. Thank you very much for the information! Very helpful.

Is there a better library to use for writing text onto an image that supports more features, like adjusting letter spacing? Or is SkiaSharp the best there is right now?

**Comment by Gillibald** [comment]
I suggest using https://github.com/toptensoftware/RichTextKit that works on top of SkiaSharp

**Comment by washamdev** [comment]
You've been very helpful, @Gillibald, thank you for your quick answers and tips!
