### ISSUE TITLE
How to detect whether the source JPEG image has CMYK color space with SkiaSharp?

### ISSUE THREAD

**Issue by AlexNosk** [mono/SkiaSharp#1768]
I have a requirement to detect whether the input image has CMYK color space. How can I achieve this with SkiaSharp.

I tried to check `SKbitmap.ColorSpace`, but is is always null.
Then I tried to use `SKCodec.ColorSpace`, it is initialized, but even for CMYK `SKCodec.ColorSpace.Type` images it returns `SKColorSpaceType.Rgb`. 

Is there a way to to detect CYMK images with SkiaSharp?

**Comment by mattleibow** [comment]
I believe skia may actually implicitly convert the color spaces.

I would definitely as on the skia forums for this as they will know the engine details: https://groups.google.com/g/skia-discuss
