### ISSUE TITLE
[QUESTION]  exception @rpath/libSkiaSharp.framework/libSkiaSharp assembly:<unknown assembly> type:<unknown type> member:(null)

### ISSUE THREAD

**Issue by Aleksey1555** [mono/SkiaSharp#1770]
Hello
Sorry for english...
I want to use SkiaSharp in Xamarin project. I decided to compile SkiaSharp from sources.

My steps:
1)I clone project:  git clone https://github.com/mono/SkiaSharp
2) Open in VS 2019 CE and build projects:
   SkiaSharp/SkiaSharp
   SkiaSharp.Views/SkiaSharp.Views.iOS
   SkiaSharp.Views.Forms/SkiaSharp.Views.Forms
   SkiaSharp.Views.Forms/SkiaSharp.Views.Forms.iOS
3) Then i add this ( SkiaSharp.dll, SkiaSharp.Views.Forms.dll and SkiaSharp.Views.Forms.iOS ) dll files as reference in my projects:
  Xamarin project:
  ![image](https://user-images.githubusercontent.com/32514002/129094654-ce972103-4162-4f86-833c-9257eb9092ec.png)
  and Xamarin.iOS project:
  ![image](https://user-images.githubusercontent.com/32514002/129094711-00bbfdb0-d508-4c4a-aa48-d581fe5fd209.png)
4) Then i start debugging with my iPhone SE (iOS 14.7.1). 
    Build successed
    But, in my project i have code:
  ```
   try
        {
            SKBitmap bmp = new SKBitmap(100, 100);
            bmp.Dispose();
         }
        catch (Exception exp)
         {
            //exp=DllNotFoundException
            //exp.inner=@rpath/libSkiaSharp.framework/libSkiaSharp assembly:<unknown assembly> type:<unknown type> member:(null)
         }
```
   
Look's like some dll missing, but which?
I don't understand, look's like missing some lib file. but how to compile it?
Somebody please help me.

My configuration:
1) VS 2019 CE
2) Iphone SE
3) Xamarin :

Xamarin   16.10.000.234 (d16-10@ecaf29b)
Xamarin Designer   16.10.0.115 (remotes/origin/c750fbf1bde3c720d077f51640fe197c6dac7cbe@c750fbf1b)
Xamarin Templates   16.10.5 (355b57a)
Xamarin.Android SDK   11.3.0.4 (d16-10/ae14caf)
    Mono: b4a3858
    Java.Interop: xamarin/java.interop/d16-10@f39db25
    ProGuard: Guardsquare/proguard/v7.0.1@912d149
    SQLite: xamarin/sqlite/3.35.4@85460d3
    Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-10@c5732a0
Xamarin.iOS and Xamarin.Mac SDK   14.20.0.24 (c4b89cddb)

**Comment by mattleibow** [comment]
Ah yeah. You need to make sure that you have the native dependencies built. However you can't do this from one OS, gut I got a wiki to help get you started. I have a target to download the latest bits

https://github.com/mono/SkiaSharp/wiki/Building-SkiaSharp#managed-only-building

**Comment by Aleksey1555** [comment]
Look's like, this is not easy((
ok, can i get native builds from somewhere?

**Comment by mattleibow** [comment]
Yes you can. Have a look at https://github.com/mono/SkiaSharp/wiki/Building-SkiaSharp#managed-only-building
