### ISSUE TITLE
[QUESTION] Build iOS libSkiaSharp.framework For Native App Use Only Rather Than Xamarin

### ISSUE THREAD

**Issue by yipingw** [mono/SkiaSharp#1785]
Hi,
I have build libSkiaSharp.framework successful on local machine, but I can't find any header file in order to invoked by native app rather than xamarin.forms application , and I find a blank libSkiaSharp.h file in this project, how can I resolved this? Thank you!

**Comment by Gillibald** [comment]
https://github.com/mono/skia/tree/xamarin-mobile-bindings/include/c

**Comment by yipingw** [comment]
> https://github.com/mono/skia/tree/xamarin-mobile-bindings/include/c

Hi, 
Thank you for your reply, is there a simple way to use these libriaries such as libSkiaSharp.framework, libSkiaSharp.so etc. I've tried to extract skiasharp.nupkg and got library binaries but I can't use it in native project (rather than xamarin.forms project).

**Comment by Gillibald** [comment]
Why can't you use the SkiaSharp binding? If you want to p/invoke the native bits on your own you need to manage object creation on your own.

**Comment by yipingw** [comment]
> Why can't you use the SkiaSharp binding? If you want to p/invoke the native bits on your own you need to manage object creation on your own.

Ok, Thank you. I'll give it a try.
