### ISSUE TITLE
how to get the libSkiaSharp.so file

### ISSUE THREAD

**Issue by rxjhfmf** [mono/SkiaSharp#1799]
I have a web Api using SkiaSharp;

It works well in windows system, but not works in docker  with the image mcr.microsoft.com/dotnet/core/aspnet:3.1;

so, how to get the libSkiaSharp.so  v2.80.3

**Comment by rxjhfmf** [comment]
I have resolved

**Comment by Alex-YZ** [comment]
> 我已经解决了
如何操作的

**Comment by rxjhfmf** [comment]
> 



> > 我已经解决了
> > 如何操作的

项目中把下面2个引用加上

	  <PackageReference Include="SkiaSharp.NativeAssets.Linux" Version="2.80.3" />
	  <PackageReference Include="SkiaSharp.NativeAssets.Linux.NoDependencies" Version="2.80.3" />

**Comment by Alex-YZ** [comment]
> 

好的感谢~

我昨天也看到了官方的说明~
