### ISSUE TITLE
Setting Pixel of SKBitmap with color type of Gray8 fails

### ISSUE THREAD

**Issue by Tylerflick** [mono/SkiaSharp#181]
When setting a pixel in an SKBitmap with a color type of Gray8, the value is never updated.

I've traced the bug to [Mono's fork of Skia](https://github.com/mono/skia/blob/xamarin-mobile-bindings/src/c/sk_bitmap.cpp#L147).

```
void sk_bitmap_set_pixel_color(sk_bitmap_t* cbitmap, int x, int y, sk_color_t color)
{
    SkBitmap* bmp = AsBitmap(cbitmap);

    SkAutoLockPixels alp(*bmp);

    switch (bmp->colorType()) {
    case kAlpha_8_SkColorType:
        copyAlpha8FromColor(1, &color, (uint8_t*)bmp->getAddr8(x, y));
        break;
    case kRGB_565_SkColorType:
        copyRgb565FromColor(1, 1, &color, (uint16_t*)bmp->getAddr16(x, y));
        break;
    case kBGRA_8888_SkColorType:
    case kRGBA_8888_SkColorType:
        copy8888FromColor(1, &color, (uint32_t*)bmp->getAddr32(x, y));
        break;
    default:
        break;
    }
}
```

There is no case for handling kIndex_8_SkColorType or kGray_8_SkColorType.

I've tried to work around this issue by copying the bitmap to an Alpha8 colorspace, but that copies the alpha channel (always 255) and discards the actual pixel data.

**Comment by mattleibow** [comment]
@Tylerflick I had a look at your code, and I was wondering why you chose to calculate the values.

I was thinking that you should be using the color table of the bitmap (`SkBitmap::getColorTable()`) as well as the index (`SkBitmap::getIndex8Color(int,int)`).

With this you can actually just look up the color. Setting the color may involve searching the table. I am having a look if there is a function to find the correct/nearest index for a color.

**Comment by mattleibow** [comment]
I asked the skia guys here: https://groups.google.com/forum/#!topic/skia-discuss/Jk4mpDPBZEo

**Comment by mattleibow** [comment]
Also not this: https://groups.google.com/forum/#!topic/skia-discuss/2RORN6klVwg

> **Can we remove support for colortable bitmaps (kIndex8_Config)?**
> Skia's bitmap config includes kIndex8, which is an 8-bit bitmap with an associated array of colors (SkColorTable). There is some burden in supporting this. Is there any value?

**Comment by Tylerflick** [comment]
@mattleibow You're completely right about the index color type. 
I'll update the pull request to target the gray8 color type.

Concerning index8, I'll do a bit more research around the color table.

**Comment by mattleibow** [comment]
If you are doing gray, then they have a inline method you can use (`SkComputeLuminance`):
https://github.com/mono/skia/blob/xamarin-mobile-bindings/include/core/SkColorPriv.h#L166-L174

Another thing is that the bitmap is premultiplied, but color is not. So when you set the color, you need to premultiply it:
https://github.com/mono/skia/blob/xamarin-mobile-bindings/src/core/SkPixmap.cpp#L144-L149

And then when you get that color, you need to unpremultiply it: `SkUnPreMultiply::PMColorToColor`. Also, the gray appears to be a premultiplied gray, so you need to get that first: `SkPackARGB32(0xFF, src8[x], src8[x], src8[x])'.

I was using this file for my reference:
https://github.com/mono/skia/blob/xamarin-mobile-bindings/src/core/SkConfig8888.cpp#L129-L168

**Comment by mattleibow** [comment]
I am thinking, based on the forum answer and the issue, `Index8` is not really supported for drawing, but rather decoding.

**Comment by Tylerflick** [comment]
I think the issues dealing with index8 can be resolved by extending the SKBitmap API to support `void SkBitmap::setPixels(void* p, SkColorTable* ctable)`.

**Comment by mattleibow** [comment]
@Tylerflick, this is looking good. I was wondering what your plans for the rest of the issue? The title is Index8, but we are doing Gray8, Maybe we should rename the issue and do them separately? Unless you have already done code for Index8.

Are you able to add the get_pixel variants for the Gray8? I can merge that and then you can do a new PR for the Index8.

**Comment by Tylerflick** [comment]
> The title is Index8, but we are doing Gray8, Maybe we should rename the issue and do them separately? 

I'll refocus this issue to dealing with gray8 and then open a new issue to deal with the changes necessary for index8.

> Are you able to add the get_pixel variants for the Gray8?

I'll add gray8 support to those API's for the above PR now.
