### ISSUE TITLE
[BUG] SKRuntimeEffect doesn't work on Bitmap Canvas

### ISSUE THREAD

**Issue by substanc3-dev** [mono/SkiaSharp#1822]
**Description**

When attempting to use SKSL effects on bitmap canvases, there is a native exception raised.

**Code**

```cs
var bitmap = new SKBitmap(100, 100, false);
using var canvas = new SKCanvas(bitmap);

var src = @"
half4 main(float2 fragCoord) {
  return half4(0.5, 0.5, 0.5, 1);
}";

using var effect = SKRuntimeEffect.Create(src, out var error);

using (SKPaint bgPaint = new SKPaint { IsAntialias = true, Shader = effect.ToShader(false) })
    canvas.DrawRoundRect(0, 0, 100, 100, 15, 15, bgPaint); // This raises an exception
```

**Expected Behavior**

SKSL runtime effect is successfully used on drawing operation.

**Actual Behavior**

An exception occurs on attempting a draw operation:
``An unhandled exception of type 'System.Runtime.InteropServices.SEHException' occurred in SkiaSharp.dll``
``External component has thrown an exception.``

**Basic Information**

- Version with issue: 2.88.0-preview.145
- Last known good version: None that I'm aware of
- IDE: Visual Studio
- Platform Target Frameworks: 
  - Windows 10 (21H1 19043.1237) running .NET 6.0.0-rc.1.21451.13

**Comment by AnarchyMob** [comment]
SkVM is not integrated (for official build) into Skia 88th milestone.

**Comment by mgood7123** [comment]
specifically the issue is the `SK_ENABLE_SKSL_INTERPRETER` is undefined when skia is being compiled

```cpp
std::unique_ptr<ByteCode> Compiler::toByteCode(Program& program) {
#if defined(SK_ENABLE_SKSL_INTERPRETER)
    AutoSource as(this, program.fSource.get());
    std::unique_ptr<ByteCode> result(new ByteCode());
    ByteCodeGenerator cg(fContext.get(), &program, this, result.get());
    bool success = cg.generateCode();
    if (success) {
        return result;
    }
#else
    ABORT("ByteCode interpreter not enabled");
#endif
    return nullptr;
}
```

**Comment by mgood7123** [comment]
enabling this in the CPP file directly enables SKSL to work on CPU

**Comment by mgood7123** [comment]
specifically
```c
 // required to enable CPU support for SKSL, this enables SKSL to work bot a CPU canvas
#define SK_ENABLE_SKSL_INTERPRETER
```

**Comment by xtu** [comment]
@mgood7123 did those changes work for you? I am still seeing the exception after applying those changes. Could you please help? Here are my changes.

![image](https://user-images.githubusercontent.com/264364/220595586-ab62d4fc-1d2a-4ff0-8a08-9366a38dc727.png)

**Comment by mgood7123** [comment]
it should work

**Comment by xtu** [comment]
I used the same `azure-pipelines.yml` from this repo to create an Azure pipeline, so I think it is recompiling from scratch.

I cannot debug yet. It would take some time to setup the build environment.

Do you have a copy of the `libSkiaSharp.dll` that have these changes for me to try?

**Comment by mattleibow** [comment]
Just been testing this in the new Skia update and it is looking so good. This shaders thing looks like a game changer. GPU and CPU surfaces are all fast!

**Comment by Gobra** [comment]
@mattleibow Is there any documentation and/or samples about this update that brings custom shaders support? I've been trying a piece of simplest code with `SkiaSharp 2.88.5`, which is the latest one available, and it still crashes the same way.

I've tried both bitmap canvas and rendering onscreen through `SKCanvasView`, both crash.

**Comment by mattleibow** [comment]
Have you tried the v3 alphas? The v2 is still using the same version of skia that does not yet support this.

**Comment by Gobra** [comment]
> Have you tried the v3 alphas? The v2 is still using the same version of skia that does not yet support this.

I'm a bit lost here, which `v3 alphas` are you referring to? `NuGet` offset not pre-release versions and `2.88.5` is the freshest one, I've checked tags and branches within this project to no result and I've googled around for both `SkiaSharp` and more general MAUI alpha builds to no avail again.

What am I missing?

**Comment by mattleibow** [comment]
They are on the preview feed: https://aka.ms/skiasharp-eap/index.json

However, I am hoping to release a preview of v3 to nuget soon.
