### ISSUE TITLE
[BUG] On Apple Silicon (M1 Mac/ARM64) use of SkiaSharp.dylib or libHarfBuzzSharp.dylib causes immediate crash due to problem with codesigning

### ISSUE THREAD

**Issue by HarlanHugh** [mono/SkiaSharp#1829]
**Description**

On Apple Silicon (M1 Mac/ARM64), App using libSkiaSharp.dylib causes crash with the following info:

```
Exception Type:        EXC_BAD_ACCESS (Code Signature Invalid)
Exception Codes:       0x0000000000000032, 0x000000010174c000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    Namespace CODESIGNING, Code 0x2

kernel messages:

VM Regions Near 0x10174c000:
    __LINKEDIT                  101378000-10174c000    [ 3920K] r--/r-- SM=COW  /Users/*/AS Native Test.app/Contents/MacOS/AS Native Test
--> mapped file                 10174c000-101750000    [   16K] r--/r-x SM=PRV  Object_id=4bbae3b
    __TEXT                      101990000-101a10000    [  512K] r-x/r-x SM=COW  /usr/lib/dyld

Application Specific Information:
dyld: launch, loading dependent libraries
DYLD_FALLBACK_LIBRARY_PATH=/Applications/Visual Studio.app/Contents/Resources/lib/monodevelop/bin:/Applications/Visual Studio.app/Contents/Resources/lib:/Library/Developer/CommandLineTools/usr/lib:/Applications/Xcode.app/Contents/Developer/usr/lib:/Library/Frameworks/Mono.framework/Libraries:/usr/lib:/usr/local/lib
@executable_path/../MonoBundle/libSkiaSharp.dylib
```

**Code**

To reproduce, create a new solution using the Cocoa App template. Edit the .csproj file to enable a universal app by adding 

    <XamMacArch>x86_64,ARM64</XamMacArch>

inside the first <PropertyGroup> tag as per https://docs.microsoft.com/en-us/xamarin/mac/release-notes/7/7.13

You can now build and run successfully and verify that the .app file is of Kind: Application (Universal) via Finder's Get Info command.

Add the SkiaSharp 2.88.0-preview.150 Nuget package.

The build will still succeed but will crash when running.

I was able to fix this by using Apple's codesign utility to sign the libSkiaSharp.dylib file inside of the .app/Contents/MonoBundle folder and then running again.

This also affects libHarfBuzzSharp.dylib.

**Expected Behavior**

.dylib files should be codesigned so the app will run without crashing

**Actual Behavior**

Crashes due to an issue related to codesigning

**Basic Information**

- Version with issue:  2.88.0-preview.150
- Last known good version:  None
- IDE:  Visual Studio for Mac
- Platform Target Frameworks:
  - macOS:  11.4
- Target Devices:
  - MacBook Air (M1, 2020)
  
<details>
  <summary>Detailed IDE/OS information (click to expand)</summary>
</details>

**Screenshots**

NA

**Reproduction Link**

See above instructions in Code section

**Comment by HarlanHugh** [comment]
I have discovered that if you enable codesigning on the project (Options > Build > Mac Signing > Sign the application bundle), this prevent the crash from happening. However, it seems strange that this is necessary to avoid a crash only for SkiaSharp and this issue does not affect other libraries.

**Comment by mattleibow** [comment]
Building a macOS app will always require codesigning and it should be on by default, but I have now started signing the dylib for macOS: https://github.com/mono/SkiaSharp/pull/2932
