### ISSUE TITLE
[BUG] Blazor-wasm Shader compilation error

### ISSUE THREAD

**Issue by beto-rodriguez** [mono/SkiaSharp#1833]
**Description**

I have not detected when, but sometimes I get this error when using linear gradients, this issue do not happens in any other view (tested in wpf, winforms, xamarin and uno views).

**Code**

I do not have a minimal reproducible snippet, but you can easily reproduce it at this commit:

https://github.com/beto-rodriguez/LiveCharts2/pull/239/commits/7e0a2ff1697d6bded0a9162b039c97df4b784297

it do not happens always, see gif attached bellow.

Sadly the full log is hard to copy from the edge console, so I attach it as image:

![image](https://user-images.githubusercontent.com/10853349/137529805-7b6f1ed1-c518-4fbd-96d6-64f54bdbd063.png)

![image](https://user-images.githubusercontent.com/10853349/137529853-154d59e2-66ac-4c22-9aff-b5da9942ed4e.png)

**Expected Behavior**

No throw.

**Actual Behavior**

Throws.

**Basic Information**

- Version with issue: 2.88.0-preview.150
- Last known good version:  none
- IDE:  Visual Studio
- Platform Target Frameworks:
  - Windows Classic:  Windows 10
- Target Devices:  
  - WebAssembly, Microsoft Edge Version 94.0.992.47 (Official build) (64-bit)
 
**Screenshots**

![blazor-lineal-gradient](https://user-images.githubusercontent.com/10853349/137529472-d27157e5-835b-440e-ba92-78cf1f917c0d.gif)

**Reproduction Link**

At this commit is easier to reproduce.
https://github.com/beto-rodriguez/LiveCharts2/pull/239/commits/7e0a2ff1697d6bded0a9162b039c97df4b784297

**Comment by danwalmsley** [comment]
@beto-rodriguez this was closed without a solution?

**Comment by beto-rodriguez** [comment]
@danwalmsley I closed it because the issue is no present when using the `SKCanvasView`, it only happens in the `SKGLView`, for me I changed to the canvas view.

I have faced a couple of new issues so I think there is still some work to do in the blazor view

**Comment by mattkanwisher** [comment]
seems like a major performance issue to remove using the GLCanvas? Is this not a skia or is it a Blazor issue? any pointers to help me track this down

**Comment by erichiller** [comment]
@beto-rodriguez I am having this same issue on the newer LiveCharts2 2.0.0-beta.101 - If you need any more information or logs I can provide them.
