### ISSUE TITLE
[QUESTION] Could anybody please tell if there is any documentation on how to build skia native for wasm?

### ISSUE THREAD

**Issue by dr-vij** [mono/SkiaSharp#1844]
Hi, I am really sorry for asking, but I dont know where can I ask about it.

The problem: I am trying to use skia native for wasm, but I get errors like this:

wasm-ld: error: duplicate symbol: jsimd_can_rgb_ycc
>>> defined in /var/folders/18/99jndmds6px_w52xph7yfc_h0000gn/T/tmp86_sx22cWebGLSupport_ImageConversionModule_Dynamic.a(External_libjpeg-turbo_src_0_j00uw.o)
>>> defined in Assets/Scenes/Plugins/WebGL/libSkiaSharp.a(libjpeg.jsimd_none.o)

wasm-ld: error: duplicate symbol: jsimd_can_rgb_gray
>>> defined in /var/folders/18/99jndmds6px_w52xph7yfc_h0000gn/T/tmp86_sx22cWebGLSupport_ImageConversionModule_Dynamic.a(External_libjpeg-turbo_src_0_j00uw.o)
>>> defined in Assets/Scenes/Plugins/WebGL/libSkiaSharp.a(libjpeg.jsimd_none.o)

wasm-ld: error: duplicate symbol: jsimd_can_ycc_rgb
>>> defined in /var/folders/18/99jndmds6px_w52xph7yfc_h0000gn/T/tmp86_sx22cWebGLSupport_ImageConversionModule_Dynamic.a(External_libjpeg-turbo_src_0_j00uw.o)
>>> defined in Assets/Scenes/Plugins/WebGL/libSkiaSharp.a(libjpeg.jsimd_none.o)

and so on... And yes, I am using Unity3d and trying to make it work in wasm. I think that unity already has some of libraries from libSkiaSharp.a (libjpeg as I can see). So maybe there is any way to exclude libjpeg.jsimd_none.o on build? Or maybe I can rebuild native skia without them. Thanks for any advice :)

**Comment by dr-vij** [comment]
Sorry for stupid questions, found cake files for natives.

**Comment by mattleibow** [comment]
No stupid questions. You are one of the lucky few trying to build the native bit and I do not have the greatest docs.

Glad to see you managed to move forward. Loving the fact that skia could run in unity!!!

**Comment by dr-vij** [comment]
It works in Unity, thank you so much for this great work. I will upload something like fork with same MIT licenses with adaptation of SkiaSharp for work in Unity :)
