### ISSUE TITLE
[BUG] ArgumentNullException is thrown when decode an image from stream on Linux Docker

### ISSUE THREAD

**Issue by AlexNosk** [mono/SkiaSharp#1846]
**Description**

ArgumentNullException is thrown when decode an image from stream. The same image can be successfully decoded from file.

**Code**

```cs
using (MemoryStream ms = new MemoryStream(File.ReadAllBytes("/temp/problem.Jpeg")))
{
    SkiaSharp.SKBitmap bmp = SkiaSharp.SKBitmap.Decode(ms);
}
```

**Basic Information**

- Version with issue:  The issue is reproducible starting from 2.80.3 version.
- Last known good version:  2.80.2
- IDE:   Visual Studio
- Platform Target Frameworks: 
  - Linux:  checked in docker.
 
Sample project with dockerfile and image are in the attachment.
[Temp.zip](https://github.com/mono/SkiaSharp/files/7441251/Temp.zip)
one more problematic image
[out_0.zip](https://github.com/mono/SkiaSharp/files/7441372/out_0.zip)
and one more
[problem_1.zip](https://github.com/mono/SkiaSharp/files/7441439/problem_1.zip)

**Comment by Azkarell** [comment]
I have a similar issue, I found out if I first use SKData.Create(ms) and then create the bitmap it works. On the other hand if i use SKCodec.Create(ms) i get the exception as well, so it seems the SKCodec implementation has an issue with (probably) very specific pictures.

**Comment by mmcmasterd3** [comment]
I have the same issue when passing in a stream from HttpResponseMessage.Content.ReadAsStream()

**Comment by jpatte** [comment]
We've had this exact same issue in production for a few days. Here is the problematic image we came across.
[killer image.zip](https://github.com/mono/SkiaSharp/files/7637432/killer.image.zip)

**Comment by jpatte** [comment]
@Azkarell gave a pretty nice workaround: in our case we only needed to replace
`var bitmap = SKBitmap.Decode(theStream);`
with
`var skData = SKData.Create(theStream);
var bitmap = SKBitmap.Decode(skData);`
to avoid the issue entirely.

**Comment by rctec-at** [comment]
@jpatte thanks for saving my monday!

General question:
Is there another issue thats not linked here that fixes this problem or is this workaround the way we should decode images always?

**Comment by mattleibow** [comment]
This may have been fixed in the latest nuget. Are you able to check?

**Comment by rctec-at** [comment]
@mattleibow  the new nuget 2.88.3 on Xamarin.Forms 5.0.0.2196 seems to work and has fixed this issue.

**Comment by mattleibow** [comment]
Fixed in https://github.com/mono/SkiaSharp/pull/2265
