### ISSUE TITLE
Android Bootstrap on Mac - Fails with Import of GYT in Python

### ISSUE THREAD

**Issue by czenzel** [mono/SkiaSharp#185]
Tonight I was wondering how my Android compiles kept failing with SkiaSharp. I found that when running the command

```./bootstrapper.sh -t externals-android```

That python was coming back with an error in regards to the gyt module. 

To start to fix this issue I pulled the latest master branch of Skia and the depot_tools into the proper directories, overwriting the current submodule versions, and found that a command in the bootstrapper script might not be running.

When I went back to the directory that contains the Skia code I ran:

```python bin/fetch-gn```

Now the bootstrapper successfully runs the NDK compiles. I actually now have the CXX program running where as before it would error out and not say about it until all the attempts were made on each architecture.

Sorry for the messy response (late night). If you need any additional help or information let me know.

It looks like the bootstrapper.sh is not running the ```fetch-gn``` to generate the compile files correctly for Skia causing the build to error out for Android.

Thanks,
Christopher Zenzel (@CZenzel)
https://linkedin.com/in/chriszenzel

**Comment by czenzel** [comment]
Spoke too soon. I am now receiving this error for x86:

Android NDK: Could not find platform files (headers and libraries)
Android NDK: Please run build/tools/gen-platforms.sh to build the corresponding directory.
/Users/[]/Library/Developer/Xamarin/android-ndk/build/core/init.mk:467: *** Android NDK: Aborting    .  Stop.

**Comment by czenzel** [comment]
I used the process of the import like above with a fresh pull of the GIT source for SkiaSharp. I found another issue were the Android NDK/SDK installed with Xamarin was not working with the SkiaSharp build.

To fix it I used the following after installing the latest of Android Studio, opening the program, and installing the SDKs and NDK Bundle.

My next error was just about a version of the SDK the compiler wishes to use but I can fix that.

So my steps to sync are still required for me to prevent the ```ImportError```.

To compile (bootstrap):

```ANDROID_SDK_HOME=/Users/[User]/Library/Android/sdk ANDROID_NDK_HOME=/Users/[User]/Library/Android/sdk/ndk-bundle ./bootstrapper.sh -t libs```

**Comment by mattleibow** [comment]
@czenzel Have you managed to get things going yet?

Just some things that might help:
 - make sure to check out the `master` of SkiaSharp
 - make sure to clone submodules: `git submodule update --init --recursive`
 - the skia branch will be the `mono` fork `xamarin-mobile-bindings`
 - you may have to set the env vars for the Android and skia tools:
    - Android SDK: `ANDROID_HOME` = `/Users/[User]/Library/Developer/Xamarin/android-sdk-macosx`
    - Android SDK: `ANDROID_SDK_ROOT` = `/Users/[User]/Library/Developer/Xamarin/android-sdk-macosx`
    - Android NDK: `ANDROID_NDK_HOME` = `/Users/[User]/Library/Developer/Xamarin/android-ndk`

The environment variables are used internally by the skia build process.

Let me know if there are any issues that you couldn't resolve.

**Comment by czenzel** [comment]
Hi @mattleibow,

I did manage to get things to work on my iMac. It seems that my Xamarin install of the Android SDK is not working with the SkiaSharp build process. I have to always use the Android Studio version of the tools for the NDK and SDK.

One other thing to note is that even with the submodule update the only way I can get this to build is doing the ```bin/fetch-gn``` process. I don't know if it has something to do with macOS 10.12 Public Beta; however, using the Android Studio (```/Users/[User]/Library/Android```) does work after ```fetch-gn```.

I am waiting to test the compiled libraries. I might freshly grab the source tonight on my macOS 10.12 notebook (without Public Beta) and try again.

Thanks for helping.
Chris Z
