### ISSUE TITLE
[QUESTION] Mangling error when trying to connect wasm .a library

### ISSUE THREAD

**Issue by dr-vij** [mono/SkiaSharp#1850]
Hi, I am still trying to build wasm to make it available in Unity3d.
First I hade some conflicts with function namings, cause Unity3d had the same (libjpg, libpng, freetype). I fixed it by renaming them with regex. Now wasm builds, but it gives error on linking:

Library/Bee/artifacts/WebGL/build/debug_WebGL_wasm/build.js: undefined symbol: _ZNSt3__212basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEE17__assign_externalEPKcm (referenced by top-level compiled C/C++ code)
UnityEditor.BuildPlayerWindow:BuildPlayerAndRun () (at /Users/bokken/buildslave/unity/build/Editor/Mono/BuildPlayerWindow.cs:179)

Library/Bee/artifacts/WebGL/build/debug_WebGL_wasm/build.js: undefined symbol: _ZNSt3__212basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEE17__assign_no_aliasILb0EEERS5_PKcm (referenced by top-level compiled C/C++ code)
UnityEditor.BuildPlayerWindow:BuildPlayerAndRun () (at /Users/bokken/buildslave/unity/build/Editor/Mono/BuildPlayerWindow.cs:179)

Library/Bee/artifacts/WebGL/build/debug_WebGL_wasm/build.js: undefined symbol: _ZNSt3__212basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEE25__init_copy_ctor_externalEPKcm (referenced by top-level compiled C/C++ code)
UnityEditor.BuildPlayerWindow:BuildPlayerAndRun () (at /Users/bokken/buildslave/unity/build/Editor/Mono/BuildPlayerWindow.cs:179)

Can OS be the reason of it? I switched off .WithCriteria(IsRunningOnLinux())
Maybe I should try it on linux? I will be grateful for any help

**Comment by dr-vij** [comment]
UPD: I've built wasm version on Ubunto 20.4 and got same errors :(

**Comment by dr-vij** [comment]
```
Building Library/Bee/artifacts/WebGL/build/debug_WebGL_wasm/build.js failed with output:
```

```
error: undefined symbol: _ZNSt3__212basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEE17__assign_externalEPKcm (referenced by top-level compiled C/C++ code)
warning: Link with -s LLD_REPORT_UNDEFINED to get more information on undefined symbols
warning: To disable errors for undefined symbols use -s ERROR_ON_UNDEFINED_SYMBOLS=0
warning: __ZNSt3__212basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEE17__assign_externalEPKcm may need to be added to EXPORTED_FUNCTIONS if it arrives from a system library
```

```
error: undefined symbol: _ZNSt3__212basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEE17__assign_no_aliasILb0EEERS5_PKcm (referenced by top-level compiled C/C++ code)
warning: __ZNSt3__212basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEE17__assign_no_aliasILb0EEERS5_PKcm may need to be added to EXPORTED_FUNCTIONS if it arrives from a system library
```

```
error: undefined symbol: _ZNSt3__212basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEE17__assign_no_aliasILb1EEERS5_PKcm (referenced by top-level compiled C/C++ code)
warning: __ZNSt3__212basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEE17__assign_no_aliasILb1EEERS5_PKcm may need to be added to EXPORTED_FUNCTIONS if it arrives from a system library
```

```
error: undefined symbol: _ZNSt3__212basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEE25__init_copy_ctor_externalEPKcm (referenced by top-level compiled C/C++ code)
warning: __ZNSt3__212basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEE25__init_copy_ctor_externalEPKcm may need to be added to EXPORTED_FUNCTIONS if it arrives from a system library

```
error: undefined symbol: _ZNSt3__215basic_stringbufIcNS_11char_traitsIcEENS_9allocatorIcEEE3strERKNS_12basic_stringIcS2_S4_EE (referenced by top-level compiled C/C++ code)
warning: __ZNSt3__215basic_stringbufIcNS_11char_traitsIcEENS_9allocatorIcEEE3strERKNS_12basic_stringIcS2_S4_EE may need to be added to EXPORTED_FUNCTIONS if it arrives from a system library
```

```
Error: Aborting compilation due to previous errors
emcc2: error: '/Applications/Unity/Hub/Editor/2021.2.0f1/PlaybackEngines/WebGLSupport/BuildTools/Emscripten/node/node /Applications/Unity/Hub/Editor/2021.2.0f1/PlaybackEngines/WebGLSupport/BuildTools/Emscripten/emscripten/src/compiler.js /var/folders/18/99jndmds6px_w52xph7yfc_h0000gn/T/tmp95iw9h4c.txt' failed (1)
UnityEditor.BuildPlayerWindow:BuildPlayerAndRun () (at /Users/bokken/buildslave/unity/build/Editor/Mono/BuildPlayerWindow.cs:179)
```

**Comment by dr-vij** [comment]
Looks like it wants std::basic_string<CharT,Traits,Allocator>, am I on a right way? I see EXPORTED_FUNCTIONS file but dont understand how to use it yet

**Comment by dr-vij** [comment]
i found them in 

namespace glslang {

    //
    // Pool version of string.
    //
    typedef pool_allocator<char> TStringAllocator;
    typedef std::basic_string <char, std::char_traits<char>, TStringAllocator> TString;

} // end namespace glslang

looks like linker cant find it

**Comment by dr-vij** [comment]
I removed all dllimports and found two where 1 gives this errors and one does not.

this one gives error:
[DllImport(SKIA, CallingConvention = CallingConvention.Cdecl)]
 internal static extern sk_image_t sk_image_make_raster_image(sk_image_t cimage);

this one does not:
[DllImport (SKIA, CallingConvention = CallingConvention.Cdecl)]
internal static extern sk_image_t sk_image_make_subset (sk_image_t cimage, SKRectI* subset);

I also have noticed that wasm tests from utils folder do not work :(

**Comment by dr-vij** [comment]
So I fixed this error by downgrading from emscripten 2.0.32 to 2.0.21, it compiles now, but does not work.

**Comment by dr-vij** [comment]
So I moved forward, now I build skia sharp on Ubuntu 20.04 on emcc 2.0.19 (Same version as unity). And Unity project compiles, but the new error is runtime:

exception thrown: RuntimeError: null function or function signature mismatch,RuntimeError: null function or function signature mismatch
    at http://localhost:49782/Build/skia.wasm.gz:wasm-function[35775]:0xa659b0
    at http://localhost:49782/Build/skia.wasm.gz:wasm-function[3667]:0x122e5f
    at http://localhost:49782/Build/skia.wasm.gz:wasm-function[3668]:0x122f78
    at http://localhost:49782/Build/skia.wasm.gz:wasm-function[9093]:0x34de83
    at http://localhost:49782/Build/skia.wasm.gz:wasm-function[35429]:0xa3fcfe
    at http://localhost:49782/Build/skia.wasm.gz:wasm-function[16989]:0x632db5
    at http://localhost:49782/Build/skia.wasm.gz:wasm-function[2786]:0xcab5e
    at http://localhost:49782/Build/skia.wasm.gz:wasm-function[16979]:0x63298d
    at http://localhost:49782/Build/skia.wasm.gz:wasm-function[20165]:0x782c31
    at http://localhost:49782/Build/skia.wasm.gz:wasm-function[26785]:0x923f3b
    at http://localhost:49782/Build/skia.wasm.gz:wasm-function[5737]:0x20ca83
    at http://localhost:49782/Build/skia.wasm.gz:wasm-function[21613]:0x7a9dd7
    at invoke_iiii (http://localhost:49782/Build/skia.framework.js:2:389202)
    at http://localhost:49782/Build/skia.wasm.gz:wasm-function[1390]:0x5c05a
    at http://localhost:49782/Build/skia.wasm.gz:wasm-function[3848]:0x13a31c
    at http://localhost:49782/Build/skia.wasm.gz:wasm-function[687]:0x25741
    at http://localhost:49782/Build/skia.wasm.gz:wasm-function[34354]:0xa2350d
    at http://localhost:49782/Build/skia.wasm.gz:wasm-function[26785]:0x923f3b
    at http://localhost:49782/Build/skia.wasm.gz:wasm-function[5737]:0x20ca83
    at http://localhost:49782/Build/skia.wasm.gz:wasm-function[21613]:0x7a9dd7
    at invoke_iiii (http://localhost:49782/Build/skia.framework.js:2:389202)
    at http://localhost:49782/Build/skia.wasm.gz:wasm-function[1390]:0x5c05a
    at http://localhost:49782/Build/skia.wasm.gz:wasm-function[3848]:0x13a31c
    at http://localhost:49782/Build/skia.wasm.gz:wasm-function[687]:0x25741
    at http://localhost:49782/Build/skia.wasm.gz:wasm-function[12641]:0x55cc09
    at http://localhost:49782/Build/skia.wasm.gz:wasm-function[3866]:0x13acb1
    at http://localhost:49782/Build/skia.wasm.gz:wasm-function[12823]:0x5620be
    at http://localhost:49782/Build/skia.wasm.gz:wasm-function[3001]:0xe3a28
    at http://localhost:49782/Build/skia.wasm.gz:wasm-function[28620]:0x945350
    at http://localhost:49782/Build/skia.wasm.gz:wasm-function[27463]:0x92f9a0
    at http://localhost:49782/Build/skia.wasm.gz:wasm-function[5737]:0x20ca83
    at http://localhost:49782/Build/skia.wasm.gz:wasm-function[21613]:0x7a9dd7
    at invoke_iiii (http://localhost:49782/Build/skia.framework.js:2:389202)
    at http://localhost:49782/Build/skia.wasm.gz:wasm-function[1390]:0x5c05a
    at http://localhost:49782/Build/skia.wasm.gz:wasm-function[17433]:0x67009c
    at http://localhost:49782/Build/skia.wasm.gz:wasm-function[959]:0x32eb5
    at http://localhost:49782/Build/skia.wasm.gz:wasm-function[3326]:0x106663
    at http://localhost:49782/Build/skia.wasm.gz:wasm-function[25951]:0x8f772c
    at http://localhost:49782/Build/skia.wasm.gz:wasm-function[24919]:0x89d6b6
    at http://localhost:49782/Build/skia.wasm.gz:wasm-function[23583]:0x7ecc60
    at http://localhost:49782/Build/skia.wasm.gz:wasm-function[12154]:0x54768f
    at http://localhost:49782/Build/skia.wasm.gz:wasm-function[12154]:0x5476fe
    at http://localhost:49782/Build/skia.wasm.gz:wasm-function[10676]:0x458824
    at http://localhost:49782/Build/skia.wasm.gz:wasm-function[21608]:0x7a9d99
    at browserIterationFunc (http://localhost:49782/Build/skia.framework.js:2:257698)
    at callUserCallback (http://localhost:49782/Build/skia.framework.js:2:131767)
    at Object.runIter (http://localhost:49782/Build/skia.framework.js:2:133027)
    at Browser_mainLoop_runner (http://localhost:49782/Build/skia.framework.js:2:131302)

**Comment by dr-vij** [comment]
So after investigation, I found an error inside Unity3d. The wasm skiasharp works in development mode of engine. I will report them a bug

**Comment by dr-vij** [comment]
https://forum.unity.com/threads/null-function-or-function-signature-mismatch-error-and-please-contact-customer-support-message.1192075/#post-7624297

**Comment by mattleibow** [comment]
Oh wow. I look away and you are moving forward. This is really awesome.

I would love to see what you are doing so maybe we can get an extra nuget or something out so you don't have to worry about building it.

**Comment by dr-vij** [comment]
https://forum.unity.com/threads/null-function-or-function-signature-mismatch-error-and-please-contact-customer-support-message.1192075/#post-7633822

I created the new thread, I will create port of SkiaSharp working with Unity with same MIT license. But we found some bugs in Unity right now. I am waiting for them to fix it :) Your repository is wonderfull. I saw C# wrappers and .generated files, that is fantastic and difficult job.
