### ISSUE TITLE
An exception of type 'System.DllNotFoundException' occurred in SkiaSharp.dll

### ISSUE THREAD

**Issue by jaladaGmbH** [mono/SkiaSharp#187]
This exception occurs always  when e.g. calling  'SKBitmap bitmap = new SKBitmap(frame.Size.Width, frame.Size.Height, SKColorType.Rgb565, SKAlphaType.Premul);' within an UWP Xamarin project and using any  Windows 10 Mobile Emulator or a XBox One as device while running a debug session in Visual Studio.

Any help is welcome. Thank you.

**Comment by mattleibow** [comment]
Hi @jaladaGmbH, thanks for trying out SkiaSharp.

Does it work in Release? Also, did you install the SkiaSharp NuGet into all the relevant projects (PCL/iOS/Android/UWP)? 

Finally, are you able to check if the samples build for v1.54.1: 
https://github.com/mono/SkiaSharp/releases/tag/v1.54.1
For this, you should download the source using the "Source code (zip)" link at the bottom of the page. v1.55.0 is still in development.

**Comment by mattleibow** [comment]
Closing this as it appears to be the result of not installing the NuGet into the app project as well as the PCL.
