### ISSUE TITLE
[QUESTION] Is there a way to calculate SKPath.Area?

### ISSUE THREAD

**Issue by leonbohmann** [mono/SkiaSharp#1876]
After searching the web for quite some time now, I can't find appropriate answers, for which the questions are quite simple:

a) Is there a method to calculate the area of an SKPath?
b) Is there a way I can iterate through the SKPath and calculate the area on my own? With Gauss, maybe?

**Comment by AnarchyMob** [comment]
You can do this: 

```csharp
var pathMeasure = new SKPathMeasure(path);
float length = pathMeasure.Length;
float side = length / 4f;
float area = side * side;
```

**Comment by leonbohmann** [comment]
Sure, but that is only valid for rectangles. What if I add a beziers?

**Comment by AnarchyMob** [comment]
In theory, it should work with any curves. Need to test with closed curves.

**Comment by leonbohmann** [comment]
See below picture. There, I don't even have 4 'sides'. 
![grafik](https://user-images.githubusercontent.com/13386367/144382315-49d195d5-b9b1-461c-931e-bd3ff6bed897.png)
I can't calculate that using (side)², can I?

Of course I need some kind of abbreviation since a bezier can't be integrated easily. What I could do is using triangles to approximate curves.

**Comment by AnarchyMob** [comment]
We just interpret the length of the curve as a square, that's all.

**Comment by AnarchyMob** [comment]
Yes, I was wrong, the algorithm is somewhat more complicated. you need to split the curve into polygons and calculate their total area.

[StackOverflow](https://stackoverflow.com/questions/10039679/how-can-i-calculate-the-area-of-a-bezier-curve/55533770)

**Comment by AnarchyMob** [comment]
You can try using SKRegion with CreateRectIterator...

**Comment by leonbohmann** [comment]
That is an awesome idea!
I tried it with SkiaSharpFiddle:
![grafik](https://user-images.githubusercontent.com/13386367/144411904-2372506a-9502-45d2-9731-7b753c7efa62.png)
I will iterate over the rectangles and calculate their area and just sum it up.

Thanks a lot!
