### ISSUE TITLE
[BUG]-"libSkiaSharp.framework" in item list "NativeReference" does not define a value for metadata "FrameworkFilename". 

### ISSUE THREAD

**Issue by MohanaselvamJ** [mono/SkiaSharp#1879]
**Description**

libSkiaSharp.framework" in item list "NativeReference" does not define a value for metadata "FrameworkFilename".  In order to use this metadata, either qualify it by specifying %(NativeReference.FrameworkFilename), or ensure that all items in this list define a value for this metadata.

**Code**

Simple Maui Sample

**Expected Behavior**

SkiaSharp.Harfbuzz should work in ios

**Actual Behavior**

Throws error while deploying in iOS

**Basic Information**

NuGets used:
![image](https://user-images.githubusercontent.com/41197331/144792285-711e3cbb-8e89-4f84-9850-5d5a132a8460.png)

- IDE:   Microsoft Visual Studio Professional 2022 (64-bit) - Preview, Version 17.1.0 Preview 1.1
- Platform Target Frameworks:  Maui sample targetting iOS
  - Android:  
  - iOS:  iphone 13 iOS 15.0 Simulator. (XCode 13.1 is installed in Mac machine)
  - Linux:  
  - macOS:  macOS 11.5.2
  
  
<details>

  **Replication steps:**
1. Create simple Maui sample 
2. Add SkiaSharp.Harfbuzz 2.88.0-preview.155
3. Deploy in iOS Simulator or device.

It shows below error while deploying.

**Error list:**

![image](https://user-images.githubusercontent.com/41197331/144792311-572f1ae6-02d3-426c-997c-989220c7b226.png)

**Build window:**
![image](https://user-images.githubusercontent.com/41197331/144792305-139571b6-a88c-4a6e-910f-4d29415dcbce.png)
  
```

**Note: This issue not occurs while using SkiaSharp alone https://www.nuget.org/packages/SkiaSharp/2.88.0-preview.155**

**Comment by MohanaselvamJ** [comment]
@mattleibow , could you please have a look on this.

Does SkiaSharp.HarfBuzz not compatible for Maui?

**Comment by slarti-zak** [comment]
We are also experiencing this with the `preview.179`

Navigating to the error source, it opens the `HarfBuzzSharp.NativeAssets.iOS.targets` file, which references issue https://github.com/xamarin/xamarin-macios/issues/11667 for iOS.

**Comment by maxkatz6** [comment]
Seems to be fixed with latest SkiaSharp version and .NET 6.0.200 SDK installed (including latest workloads).
After https://github.com/mono/SkiaSharp/pull/1958

**Comment by dotMorten** [comment]
We also hit this. When using our nuget package `Esri.ArcGISRuntime.Maui` with yours, this error comes up.
> Error	MSB4096	The item "C:\Users\mn\.nuget\packages\esri.arcgisruntime.runtimes.ios\100.14.1\buildTransitive\net6.0-ios13\..\..\framework\iossimulator-x64\native\ArcGIS-simx64.framework" in item list "NativeReference" does not define a value for metadata "FrameworkFilename".  In order to use this metadata, either qualify it by specifying %(NativeReference.FrameworkFilename), or ensure that all items in this list define a value for this metadata.	MauiSignin	C:\Users\mn\.nuget\packages\skiasharp.nativeassets.ios\2.88.0\buildTransitive\net6.0-ios13.6\SkiaSharp.NativeAssets.iOS.targets	6

**Comment by epsmae** [comment]
Same happens with:
```
SkiaSharp.Views.Maui.Controls
SkiaSharp.Views.Maui.Controls.Compatibility
```
Commenting out the workaround from "skiasharp.nativeassets.ios\2.88.0\buildTransitive\net6.0-ios13.6\SkiaSharp.NativeAssets.iOS.targets" allows the build and runs successful in debug and release.
