### ISSUE TITLE
Error when building SkiaSharp

### ISSUE THREAD

**Issue by charlenni** [mono/SkiaSharp#188]
Hello,

first let's say thank you for your incedible work.

I forked SkiaSharp and trying to compile it. Did everything like described on the README.md. When running the bootstrap I get an error:

```Executing task: externals-uwp
Adding C:/Entwicklung/SkiaSharp/externals/depot_tools to Environment Variable PATH
Setting Environment Variable PATH to C:/Entwicklung/SkiaSharp/externals/depot_tools;...
Setting Environment Variable GYP_GENERATORS to msvs
Setting Environment Variable GYP_DEFINES to skia_arch_type='x86_64' skia_gpu=1
Running 'sync-and-gyp'...
        GYP_GENERATORS = msvs
        GYP_DEFINES = skia_arch_type='x86_64' skia_gpu=1
An error occured when executing task 'externals-uwp'.
Error: System could not find the given file
```

What do I wrong here? Missed I something?

Best regards,
Dirk

**Comment by charlenni** [comment]
The above is what I getting, if I try to compile SkiaSharp on Windows.

When I try the same on Mac OSX, I get the following error:

```
Installing NuGet package Cake.FileHelpers...
Error downloading 'Cake.FileHelpers.1.0.3.2 : Cake.Core [0.7.0, )' from 'https://www.nuget.org/api/v2/package/Cake.FileHelpers/1.0.3.2'.
The UTC time represented when the offset is applied must be between year 0 and 10,000.
Parameter name: offset
Error downloading 'Cake.FileHelpers.1.0.3.2 : Cake.Core [0.7.0, )' from 'https://www.nuget.org/api/v2/package/Cake.FileHelpers/1.0.3.2'.
  The UTC time represented when the offset is applied must be between year 0 and 10,000.
  Parameter name: offset
Error: Cake.Core.CakeException: Failed to install addin 'Cake.FileHelpers'.
  at Cake.Core.Scripting.ScriptProcessor.InstallAddins (Cake.Core.Scripting.Analysis.ScriptAnalyzerResult analyzerResult, Cake.Core.IO.DirectoryPath installPath) [0x000ed] in <1abf81795771408db3eac07a98d2cbc1>:0 
  at Cake.Core.Scripting.ScriptRunner.Run (Cake.Core.Scripting.IScriptHost host, Cake.Core.IO.FilePath scriptPath, System.Collections.Generic.IDictionary`2[TKey,TValue] arguments) [0x000c9] in <1abf81795771408db3eac07a98d2cbc1>:0 
  at Cake.Commands.BuildCommand.Execute (Cake.CakeOptions options) [0x00026] in <fe9c776dd69a43a28368cc7f3cdd3a28>:0 
  at Cake.CakeApplication.Run (Cake.CakeOptions options) [0x00027] in <fe9c776dd69a43a28368cc7f3cdd3a28>:0 
  at Cake.Program.Main () [0x00086] in <fe9c776dd69a43a28368cc7f3cdd3a28>:0 
```

It seems, that I have no luck with SkiaSharp :)

**Comment by mattleibow** [comment]
@charlenni thanks for trying this out.

On Windows, did you init the submodules? The `externals` folder should have two large folders: `skia` and `depot_tools`. I think it can't actually find skia to build.

On Mac, that is a problem that I am trying to solve. Although I don't have this issue with that part of the build script, mine occurs when building the source. It appears Microsoft changed something with NuGet and there was a bug in mono. These two together create issues for some packages when you restore in a +# timezone: https://github.com/NuGet/Home/issues/3089 (there are a few others).

To get around this issue, you can either drop your timezone to a -#. Or, you can manually download and extract the https://www.nuget.org/packages/Cake.FileHelpers/ NuGet into the `/tools/Addins/Cake.FileHelpers` directory. A real pain, but at least you only have to do it once. (I just drop the TZ)

I am using mono v4.6.1:

```
$ mono --version

Mono JIT compiler version 4.6.1 (mono-4.6.0-branch-c8sr0/ef43c15 Mon Oct  3 14:35:32 EDT 2016)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
	TLS:           normal
	SIGSEGV:       altstack
	Notification:  kqueue
	Architecture:  x86
	Disabled:      none
	Misc:          softdebug 
	LLVM:          yes(3.6.0svn-mono-master/8b1520c)
	GC:            sgen
```

And NuGet v3.4.4 (in the `/tools/nuget.exe`):

```
$ mono ./tools/nuget.exe

NuGet Version: 3.4.4.1321
```

**Comment by charlenni** [comment]
Am 08.11.2016 um 19:35 schrieb Matthew Leibowitz:
>
> @charlenni <https://github.com/charlenni> thanks for trying this out.
>
> On Windows, did you init the submodules? The |externals| folder should 
> have two large folders: |skia| and |depot_tools|. I think it can't 
> actually find skia to build.
>

Yes, I init the submodules. And both folders are present and filled. 
depot_tools has a size around 10 MB, skia has a size of around 50 MB.

> On Mac, that is a problem that I am trying to solve. Although I don't 
> have this issue with that part of the build script, mine occurs when 
> building the source. It appears Microsoft changed something with NuGet 
> and there was a bug in mono. These two together create issues for some 
> packages when you restore in a +# timezone: NuGet/Home#3089 
> <https://github.com/NuGet/Home/issues/3089> (there are a few others).
>
> To get around this issue, you can either drop your timezone to a -#. 
> Or, you can manually download and extract the 
> https://www.nuget.org/packages/Cake.FileHelpers/ NuGet into the 
> |/tools/Addins/Cake.FileHelpers| directory. A real pain, but at least 
> you only have to do it once. (I just drop the TZ)
>

I will try this. Very strange problem :)

**Comment by mattleibow** [comment]
@charlenni Just remembered... Do you have Python 2.x installed and available in your `PATH` variable. On Windows.
