### ISSUE TITLE
libSkiaSharp.dll not deploying if referenced in a Class Library

### ISSUE THREAD

**Issue by jakelange** [mono/SkiaSharp#190]
In a desktop windows application, if SkiaSharp is installed via nuget to a class library then building this project will only deploy SkiaSharp.dll to the bin folder.  libSkiaSharp.dll will be missing in the bin folder.  If I change the class library project to be a windows application project, then the dll will get deployed to my bin folder along side SkiaSharp.dll.  This seems to only affect versions greater than 1.53.1.2 (I was testing with 1.55.0).  With 1.53.1.2 referenced in my class library, the libSkiaSharp.dll will deploy along side SkiaSharp.dll.

I also noticed that with 1.53.1.2 I will get an error in the SkiaSharp.targets file telling me to set the platform to either x64 or x86 to support Skia.  I do not get this error when building the class library with 1.55.0 under an anycpu config.  (setting to my desired architecture doesn't work with 1.55.0).

I have the C++ redistributable installed as noted in the Readme.  I'm building with VS2015 Pro update 3.

I was able to reproduce this by creating an empty wpf project, adding a class library, installing the 1.55.0 from nuget to the class library, and creating a canvas in a static method called by the startup project.

**Comment by mattleibow** [comment]
@JakeLange Thanks for giving SkiaSharp a go! 

This is working as designed. The reason for this is because some class libraries may be built as AnyCPU, and there is no SkiaSharp for this.

Current (designed) functionality:
 - only include the native library in the app builds
 - to force a copy, add `<ShouldIncludeNativeSkiaSharp>False</ShouldIncludeNativeSkiaSharp>` to the csproj

The main reason for not copying by default is that typically the app will install the NuGet as well, and the fact that the actual managed assembly is AnyCPU. If you were building an AnyCPU assembly, you would get a compile error saying that it can't copy the native bit.

I do admit that there is room for improvement. Maybe we can copy the native bits for ARM/x86/x64 and do nothing for AnyCPU?

All this logic is in the targets file:
https://github.com/mono/SkiaSharp/blob/master/binding/SkiaSharp.Desktop/SkiaSharp.Desktop.targets

Any feedback is welcome!

**Comment by tdctaz** [comment]
@mattleibow I really think that for AnyCPU it should copy both and keep them in subfolders, something like what `System.Data.SQLite` does. Also instead of `$(Platform)` it should check `$(PlatformTarget)` instead because that is where the final platform is assigned for the project.

**Comment by johnslaby** [comment]
Thanks for the info. I was having a similar problem with an integration test project. By changing the platform to x86 and adding <ShouldIncludeNativeSkiaSharp>True</ShouldIncludeNativeSkiaSharp> I was able to run my integration tests again. BTW, in you notes above, you suggested setting the ShouldIncludeNativeSkiaSharp property to False. I think you meant True.

**Comment by mattleibow** [comment]
I have changed the rules for this as @tdctaz suggested. Thanks!

This is the commit: 8ecf8370eadea17e0690207e3714ab16d1fa498c  (@jonhslaby, not the same mistake in the commit message)

This should go out with the next release.

**Comment by dylanvdmerwe** [comment]
I'm using 1.56.1 with Any CPU and I keep on getting a DLLNotFoundException on net461. Unit tests also not happy and throw this exception. Tried to get this to work and used `ShouldIncludeNativeSkiaSharp` but it didn't help. 

I like this library and was excited to use based on some awesome things I've heard, but will wait until this works properly.

**Comment by mattleibow** [comment]
@dylanvdmerwe You need to test with x86/x64. The current nuget does not have the bits for AnyCPU, or rather selects no native library for AnyCPU. Your libraries can be AnyCPU, but the test needs to be one or the other.

**Comment by mattleibow** [comment]
This will be in the next release v1.56.2. I am cleaning up and prepping for release as we type.

**Comment by amirvenus** [comment]
I have this issue as well

App.iOS/MTOUCH: Error MT0009: Error while loading assemblies: /Users/amir/.nuget/packages/skiasharp/1.68.0-preview28/runtimes/win-x64/native/libSkiaSharp.dll (MT0009) 

Tried with pre-release and stable to no avail

**Comment by mattleibow** [comment]
@amirvenus your issue is another is a bug in the way mono builds mac/ios. https://github.com/xamarin/xamarin-macios/issues/5265

What platform are you building for? is it mac? When I had this issue, I either build for Any CPU or remove the `PlatformTarget` elements in the csproj.

**Comment by mattleibow** [comment]
@renzska I would ask on that iOS issue just so there are more numbers.

But, Is there a `PlatformTarget` property in the csproj? Maybe see if removing that helps.
