### ISSUE TITLE
An exception of type 'System.DllNotFoundException' occurred in SkiaSharp.dll

### ISSUE THREAD

**Issue by jaladaGmbH** [mono/SkiaSharp#193]
An exception of type 'System.DllNotFoundException' occurred in SkiaSharp.dll

The issue is releated to #187. Unfortunately I wasn't fast enough to response and the case was closed. I am sorry about my delay. 

Original message:
This exception occurs always when e.g. calling 'SKBitmap bitmap = new SKBitmap(frame.Size.Width, frame.Size.Height, SKColorType.Rgb565, SKAlphaType.Premul);' within an UWP Xamarin project and using any Windows 10 Mobile Emulator or a XBox One as device while running a debug session in Visual Studio.

Does it work in Release? 

No it fails also.

Also, did you install the SkiaSharp NuGet into all the relevant projects (PCL/iOS/Android/UWP)? 

Of course.

Finally, are you able to check if the samples build for v1.54.1: 
https://github.com/mono/SkiaSharp/releases/tag/v1.54.1
 For this, you should download the source using the "Source code (zip)" link at the bottom of the page. v1.55.0 is still in development.

The UWP sample don't work also in both debug and release mode when using a Mobile Emulator or a XBox One as device.

Moreover v1.54.1 uses eglGetProcAddress  in Binding/GRGlInterface.cs, what causes your app fails to pass the Windows Store certification process.

Any help is welcome. Thank you and sorry again.

**Comment by mattleibow** [comment]
@jaladaGmbH Sorry about that. You were right, there was an issue.
Basically, I was linking the Kernel32.lib (which is not needed) and I think that was causing issues on the emulator and Xbox. I uploaded a fixed version here: https://1drv.ms/f/s!AtbUuIrDNX_5acTHJGWlH8FYzeM

Let me know if this deploys to the Xbox. I was on the Xbox preview program, and it appears that I can't use dev program if I have the preview. I am waiting for it to in-enrol me (if it ever decides to). If it works on the Xbox, please let me know. It works on my 10586 and 14393 Windows 10 Mobile Emulators.

About the `eglGetProcAddress` and certification. I haven't had any issues - I actually have an app on the store that passed. Right now I updated the SkiaSharp sample app on the store to use the v1.55.0 NuGet. It passed my local certification test, and I am waiting on a response from the store.

**Comment by jaladaGmbH** [comment]
Hello @mattleibow, thank you very much for your support. I will check it and will give you a feedback afterwards.

**Comment by mattleibow** [comment]
@jaladaGmbH Just to confirm, the v1.55 release was accepted by the Windows Store:
https://www.microsoft.com/en-za/store/p/skiasharp-for-xamarinforms/9nblggh51856

**Comment by jaladaGmbH** [comment]
Hello @mattleibow, your fixed version works great on Xbox One. Thank you very much.

Also, we will try v1.55 for our next Windows Store release. However, we use v1.54 at the moment, so if it is possible, please add your fix to that version as well.

**Comment by mattleibow** [comment]
@jaladaGmbH Thanks for the great news! I will se about getting a fix in for v1.54.

**Comment by mattleibow** [comment]
@jaladaGmbH Here is the build for v1.54.1.1 with the fix: https://1drv.ms/u/s!AtbUuIrDNX_5p6l2Z-sJluo56Q4UfQ

**Comment by czanbaka** [comment]
Hi Gents. I'm running into this issue on UWP as well only when using an emulator and I'm using the latest nuget (v.1.55.0). Any ideas? Here is the exception I was able to dig up:
```
System.DllNotFoundException: Unable to load DLL 'libSkiaSharp.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
   at SkiaSharp.SkiaApi.sk_surface_new_raster_direct(SKImageInfo& info, IntPtr pixels, IntPtr rowBytes, IntPtr propsZero)
   at SkiaSharp.SKSurface.Create(SKImageInfo info, IntPtr pixels, Int32 rowBytes)
   at SkiaSharp.Views.UWP.SKXamlCanvas.Invalidate()
   at SkiaSharp.Views.UWP.SKXamlCanvas.OnSizeChanged(Object sender, SizeChangedEventArgs e)
```

**Comment by mattleibow** [comment]
@czanbaka The fix was in the update v1.55.1. I just released that right now: https://github.com/mono/SkiaSharp/releases/tag/v1.55.1

If you have any issue with the update, please let me know.

**Comment by mchiz** [comment]
Hi!

I have to reopen this, because I found this problem in version 1.59.1. The same exception is raising on my Windows 10 Mobile, but is working perfectly in Desktop.

I have installed version 1.55.1, and it works fine in my phone!

If you need something to thelp you track this down, please, tell me! :)

Thank you!

**Comment by mchiz** [comment]
I just realized that I had to mention @mattleibow. I'm new to this :)

**Comment by mattleibow** [comment]
Hi @mchiz, are you able to provide the full stack trace?

Also, if you run SkiaSharpDemo or SkiaSharpNativeDemo from this repo, does it run at all?
https://github.com/mattleibow/SkiaSharpDemo

**Comment by mchiz** [comment]
Both projects are working correctly in my mobile, using Visual Studio 2017 Community. I'm using Visual Studio 2015 in my project, which is where I'm seeing the error. I will try my project using Visual Studio 2017, just in case.

How can I get a full stack trace that I can send to you?

Thanks for your help!

**Comment by mchiz** [comment]
@mattleibow I can confirm that my project works with Visual Studio 2017, but not with Visual Studio 2015.

Do you have any clue about it or can you point me to some resources to help me find the problem?

Thanks a lot!
