### ISSUE TITLE
[QUESTION] Images cannot be saved in SkiaSharp

### ISSUE THREAD

**Issue by devenv2** [mono/SkiaSharp#1948]
Hi,
I created android application using Xamarin forms and SkiaSharp
I've tested the app on some devices,
Some reviews say: The image cannot be saved.

 
This is my code from [SkiaSharp doc][1]:

            private async Task SaveImageAsync()
            {
                using (SKImage image = SKImage.FromBitmap(bitmap))
                {
                    SKData snap = image.Encode();
                    SKData data = image.Encode();
                    DateTime dt = DateTime.Now;
    
                    string filename = String.Format("imag-{0:D4}{1:D2}{2:D2}-{3:D2}{4:D2}{5:D2}{6:D3}.png",
                                                   dt.Year, dt.Month, dt.Day, dt.Hour, dt.Minute, dt.Second, dt.Millisecond);
                    IPhotoLibrary photoLibrary = DependencyService.Get<IPhotoLibrary>();
                    bool result = await photoLibrary.SavePhotoAsync(snap.ToArray(), "folder name‏", filename);
    
                    if (!result)
                    {
                        infoLabel.Text = "....";
                    }
                    else
                    {
                        infoLabel.Text = "....";
    
                    }
    
                }
    
            }
    
One user wrote that he was able to save the image by creating the folder in the image folder

Thanks

  [1]: https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/graphics/skiasharp/bitmaps/saving

**Comment by mattleibow** [comment]
I am not sure what you mean by:

> The image cannot be saved

Is there a crash, and error or saves a blank image?

Also, the logic for getting the data seems to be correct: `image.Encode().ToArray()`

Maybe the user is using an older/newer device that has different restrictions on what needs to be done. But, if you can get the byte array from the image, then I am not sure if I can help as I can't see the implementation for `IPhotoLibrary`

**Comment by mattleibow** [comment]
Closing this as it appears to be an issue with the logic that saves the photo as all skia does is get provide the image data. Please re-open with a repro/sample demonstrating the issue.

Please also include platform/OS and version information.
