### ISSUE TITLE
External Communications and Outgoing Traffic from SkiaSharp 

### ISSUE THREAD

**Issue by Mushtaq123** [mono/SkiaSharp#1951]
We are using the SkiaSharp library in our Xamarin.Forms application. We identified the below site address and IP address hardcoded in the framework while performing the Static mobile application security test which revealed the following remote hosts in the application where the mobile application may send or receive data.

**Host 1:** purl.org:80 & **Ip address:** 207.241.239.242:80
**Host 2:** www.aiim.org:80 & **Ip address:** 199.60.103.225:80

Kindly let us know the purpose of those IPs and links used in the control to get approval from Security Testing.

**Comment by mattleibow** [comment]
This is the namespace for the xml files in the pdf.

https://github.com/google/skia/blob/1f193df9b393d50da39570dab77a0bb5d28ec8ef/src/pdf/SkPDFMetadata.cpp#L295

It is not used for communication.
