### ISSUE TITLE
[QUESTION] Build on FreeBSD

### ISSUE THREAD

**Issue by alucryd** [mono/SkiaSharp#1952]
Hi guys, I'm trying to build libSkiaSharp for FreeBSD, but I hit a roadblock. Had to modify a check in the DNG SDK to make it build, but I'm getting strange errors when the static archives are linked:

`ar: warning: can't open file: @libzlib_x86.a.rsp: No such file or directory`

The end result is unusable as the archive is basically empty, I'm guessing there's an issue with BSD's `ar`. I have yet to try `llvm-ar`, but if you have any pointers that would be great.

**Comment by alucryd** [comment]
And the built files work! Closing this.

**Comment by mattleibow** [comment]
Awesome! Do you have a repo up with scripts or things?

**Comment by alucryd** [comment]
The build scripts are hosted in a private repo with a lot of stuff I can't share. However, this is basically what I did:

-  build google's gn from source (you'll need a recent one for FreeBSD 13 support, I used the latest git head)
- patch BUILD.gn to support latest gn
```
diff --git a/BUILD.gn b/BUILD.gn
index c00bfa8daa..045b57b73e 100644
--- a/BUILD.gn
+++ b/BUILD.gn
@@ -69,7 +69,11 @@ config("skia_public") {
 
 # Skia internal APIs, used by Skia itself and a few test tools.
 config("skia_private") {
-  visibility = [ ":*" ]
+  visibility = [
+    ":*",
+    "//modules/*",
+    "//experimental/*",
+  ]
 
   defines = [ "SK_GAMMA_APPLY_TO_A8" ]
   if (skia_enable_gpu) {
@@ -878,11 +878,6 @@ component("skia") {
     ":xml",
   ]
 
-  # This file (and all GN files in Skia) are designed to work with an
-  # empty sources assignment filter; we handle all that explicitly.
-  # We clear the filter here for clients who may have set up a global filter.
-  set_sources_assignment_filter([])
-
   public = skia_core_public
   public += skia_utils_public
   public += skia_effects_public
@@ -1068,11 +1063,6 @@ static_library("pathkit") {
     ":ssse3",
   ]
 
-  # This file (and all GN files in Skia) are designed to work with an
-  # empty sources assignment filter; we handle all that explicitly.
-  # We clear the filter here for clients who may have set up a global filter.
-  set_sources_assignment_filter([])
-
   sources = []
   sources += skia_pathops_sources
   sources += skia_pathops_public
@@ -2527,8 +2517,6 @@ skiasharp_build("SkiaSharp") {
     ":skia",
   ]
 
-  # clear the sources and add explicitly
-  set_sources_assignment_filter([])
   sources = [
     "src/xamarin/sk_compatpaint.cpp",
     "src/xamarin/sk_manageddrawable.cpp",
diff --git a/third_party/libsdl/BUILD.gn b/third_party/libsdl/BUILD.gn
index 2232acb44e15..fa24ef27fa6c 100644
--- a/third_party/libsdl/BUILD.gn
+++ b/third_party/libsdl/BUILD.gn
@@ -187,7 +187,7 @@ third_party("libsdl") {
       "SDL_VIDEO_RENDER_OGL=1",
       "SDL_VIDEO_OPENGL_CGL=1",
     ]
-    libs += [
+    frameworks = [
       "Carbon.framework",
       "Cocoa.framework",
       "Foundation.framework",
```
- follow the SkiaSharp build procedure for linux, making sure to use `llvm-ar` in place of FreeBSD's `ar`, and force python2 to be used
- if you want DNG, you need to hack it a bit after syncing the deps `gsed s/__linux__/__unix__/ -i third_party/externals/dng_sdk/source/RawEnvironment.h` (sorry for the GNU command, I'm a linux guy :/)
- if you use the bundled expat you'll need an additional cflag `-DXML_DEV_URANDOM`
- and freetype detection is borked on every platform, freebsd being no exception you'll need to point to its includedir manually (`-I/third_party/externals/freetype/include` if using the bundled library)

**Comment by mattleibow** [comment]
Awesome! Thanks for sharing.
