### ISSUE TITLE
Method 'CreatePlatformView' in type 'SkiaSharp.Views.Maui.Handlers.SKCanvasViewHandler' from assembly 'SkiaSharp.Views.Maui.Core, Version=2.88.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.

### ISSUE THREAD

**Issue by inforithmics** [mono/SkiaSharp#1964]
**Description**

Method 'CreatePlatformView' in type 'SkiaSharp.Views.Maui.Handlers.SKCanvasViewHandler' from assembly 'SkiaSharp.Views.Maui.Core, Version=2.88.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.

**Code**

Maui App that uses SkiaSharp and crashes during Startup

**Expected Behavior**

Application works

**Actual Behavior**

Application Crashes

**Basic Information**

It seems in Maui preview 14 (which is installed on my computer, don't know how this happend because Maui is still in Preview 13)
The base Class of 

https://github.com/mono/SkiaSharp/blob/main/source/SkiaSharp.Views.Maui/SkiaSharp.Views.Maui.Core/Handlers/SKCanvasView/SKCanvasViewHandler.Windows.cs
Was changed so that a CreatePlatformView method is necessary.
Because this is not implemented Maui Crashes on Startup.

**Screenshots**

**Reproduction Link**

**Comment by inforithmics** [comment]
The workaround I found was to install Maui Preview 13

 1. download the Manifest with nuget
     https://www.nuget.org/packages/Microsoft.NET.Sdk.Maui.Manifest-6.0.200/6.0.200-preview.13.2865
  2. install the manifest into the sdk-manifest folder
     C:\Program Files\dotnet\sdk-manifests\6.0.200\microsoft.net.sdk.maui
  3. Install maui
     dotnet workload install maui --skip-manifest-update 

Or ist there an offical way to install specific sdk-manifests Versions

**Comment by inforithmics** [comment]
Fixed in
https://github.com/mono/SkiaSharp/pull/1965/files

**Comment by mattleibow** [comment]
preview.232 on the skiasharp-eap feed should now work with the latest. As soon as p14 is released, I will release that build. Or a later one if need be.
