### ISSUE TITLE
[QUESTION] 1 pixel wide border

### ISSUE THREAD

**Issue by mgood7123** [mono/SkiaSharp#1972]
is it normal for 1 pixel wide borders to not be drawn?

this is what i get on MacOS

https://imgur.com/a/b6ZqeE2

and this is what i get on android

https://imgur.com/a/X3zE9rt

**Comment by mgood7123** [comment]
i wonder if this could be related to subpixel rendering (eg, needing to add 0.5 to the drawing coordinates)

**Comment by mgood7123** [comment]
hmm apparently this works if i use an SKPictureRecorder and draw it into SKCanvas

i do not know why but it works without needing to add 0.5 to my coordinates

**Comment by artemiusgreat** [comment]
This may be completely unrelated, but you may take a look at these discussions. 

Different frameworks, like Avalonia and WPF, may use different Skia settings by default. 
https://github.com/AvaloniaUI/Avalonia/discussions/7061 

Web GL is not expected to be as pixel perfect as Canvas. 
https://github.com/d3fc/d3fc/issues/1623

**Comment by mgood7123** [comment]
> This may be completely unrelated, but you may take a look at these discussions.
> 
> Different frameworks, like Avalonia and WPF, may use different Skia settings by default. [AvaloniaUI/Avalonia#7061](https://github.com/AvaloniaUI/Avalonia/discussions/7061)
> 
> Web and Open GL are not expected to be as pixel perfect as Canvas. [d3fc/d3fc#1623](https://github.com/d3fc/d3fc/issues/1623)

alright :)
