### ISSUE TITLE
[BUG] SKCanvas.DrawText does not properly handle newlines.

### ISSUE THREAD

**Issue by jonko0493** [mono/SkiaSharp#1973]
**Description**

When given text that has newlines in it, SKCanvas.DrawText fails to render the newlines and instead renders them as unknown characters.

**Code**

```csharp
string _version = "0.1.\n20220309.\n1";
string _fontFile = "Nunito-Black.ttf"

SKBitmap splashScreenVersionless = new(128, 128, isOpaque: true);

using SKCanvas canvas = new(splashScreenVersionless);
SKPoint point = new(0, 50);
canvas.DrawText(_version, point, new SKPaint(new SKFont(SKTypeface.FromFile(_fontFile))) { Color = SKColors.White });
```

**Expected Behavior**

The text is over three lines appropriately.

**Actual Behavior**

The "unknown character box" appears where the newline break should occur.

**Basic Information**

- Version with issue:  2.80.3
- Last known good version:  Unknown
- IDE:  Visual Studio
- Platform Target Frameworks: 
  - .NET 6.0
  - Windows Classic:  Windows 10
- Target Devices:
  - Windows 10

**Screenshots**

![image](https://user-images.githubusercontent.com/69772986/157549249-72ad7190-bfad-449e-905c-5f24347e807e.png)

**Comment by robloo** [comment]
I don't think this is a bug. It appears Skia itself doesn't support this. DrawText is fairly primitive and the caller needs to account for multi-line text strings. You'll have to adjust the Y coordinate yourself based on the previous line's text bounds.

**Comment by mgood7123** [comment]
i feel like this should be closed

**Comment by mattleibow** [comment]
The official recommendation is to use RichTextKit for all things text related for an amazing experience: https://github.com/toptensoftware/RichTextKit
