### ISSUE TITLE
[BUG] SKCanvas.DrawRect incorrectly draws a rectangle via (int, int, int, int) overload

### ISSUE THREAD

**Issue by mgood7123** [mono/SkiaSharp#1974]
**Description**

SKCanvas.DrawRect incorrectly draws a rectangle via `int, int, int, int` overload

**Code**

```
// correctly draws
SKRect rect = new(x1, y1, x2, y2);
canvas.DrawRect(rect, paint);
```

```
// incorrectly draws
canvas.DrawRect(x1, y1, x2, y2, paint);
```

**Expected Behavior**
```
// correctly draws
SKRect rect = new(x1, y1, x2, y2);
canvas.DrawRect(rect, paint);
```

![image](https://user-images.githubusercontent.com/26642847/157590790-a4c37a93-70e5-4a65-aa6f-de515e45d4aa.png)

**Actual Behavior**

```
// incorrectly draws
canvas.DrawRect(x1, y1, x2, y2, paint);
```

![image](https://user-images.githubusercontent.com/26642847/157590876-c6b4609f-c086-4dda-8d77-e2f8f030a6a9.png)

**Basic Information**

- Version with issue:  2.80.3
- Last known good version:  unknown
- IDE: Visual Studio for Mac
- Platform Target Frameworks: 
  - Android: API 31 Android 12  
  - macOS:  10.15.7 Catalina 
- Target Devices:   
  - Samsung S8 
  
<details>
  <summary>Detailed IDE/OS information (click to expand)</summary>
  
```

=== Visual Studio Community 2019 for Mac ===

Version 8.10.19 (build 2)
Installation UUID: 6f03fb95-39ce-4c84-befd-bdd262030983
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 6.18.0.23 (d16-6 / 088c73638)

	Package version: 612000162

=== Mono Framework MDK ===

Runtime:
	Mono 6.12.0.162 (2020-02/2ca650f1f62) (64-bit)
	Package version: 612000162

=== Roslyn (Language Service) ===

3.10.0-4.21269.26+029847714208ebe49668667c60ea5b0a294e0fcb

=== NuGet ===

Version: 5.9.0.7134

=== .NET SDK (x64) ===

SDK: /usr/local/share/dotnet/sdk/6.0.201/Sdks
SDK Versions:
	6.0.200
	6.0.102
	5.0.405
	3.1.416
MSBuild SDKs: /Applications/Visual Studio.app/Contents/Resources/lib/monodevelop/bin/MSBuild/Current/bin/Sdks

=== .NET Core Runtime ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	6.0.2
	5.0.14
	3.1.22

=== .NET Core 3.1 SDK ===

SDK: 3.1.416

=== .NET 5.0 SDK ===

SDK: 5.0.405

=== Xamarin Designer ===

Version: 16.11.0.60
Hash: 56f9b80b0
Branch: remotes/origin/d16-11
Build date: 2021-12-15 02:44:16 UTC

=== Xamarin.Profiler ===

Version: 1.7.0.0
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Updater ===

Version: 11

=== Apple Developer Tools ===

Xcode 12.4 (17801)
Build 12D4e

=== Xamarin.Mac ===

Version: 8.6.0.3 (Visual Studio Community)
Hash: caa899d24
Branch: d17-1
Build date: 2022-01-16 21:16:56-0500

=== Xamarin.iOS ===

Xamarin.iOS not installed.
Can't find mtouch or the Version file at /Library/Frameworks/Xamarin.iOS.framework/Versions/Current.

=== Xamarin.Android ===

Version: 12.0.0.3 (Visual Studio Community)
Commit: xamarin-android/d16-11/f0e3c2d
Android SDK: /Users/smallville7123/Library/Android/sdk
	Supported Android versions:
		None installed

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 31.0.3
SDK Build Tools Version: 31.0.0

Build Information: 
Mono: c633fe9
Java.Interop: xamarin/java.interop/d16-11@476bb5b
ProGuard: Guardsquare/proguard/v7.0.1@912d149
SQLite: xamarin/sqlite/3.35.4@85460d3
Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-11@87af37b

=== Eclipse Temurin JDK ===

Java SDK: Not Found

=== Android SDK Manager ===

Version: 16.10.0.13
Hash: 1b81df5
Branch: remotes/origin/d16-10
Build date: 2021-11-12 01:17:32 UTC

=== Android Device Manager ===

Version: 16.10.0.15
Hash: 89dcc0b
Branch: remotes/origin/d16-10
Build date: 2021-11-12 01:17:52 UTC

=== Build Information ===

Release ID: 810190002
Git revision: 632b6ca654e2733a685bfc9c6a0686e0a317092b
Build date: 2022-02-09 13:38:14-05
Build branch: release-8.10

=== Operating System ===

Mac OS X 10.15.7
Darwin 19.6.0 Darwin Kernel Version 19.6.0
    Thu Oct 29 22:56:45 PDT 2020
    root:xnu-6153.141.2.2~1/RELEASE_X86_64 x86_64

=== Enabled user installed extensions ===

Xamarin.Forms HotReload extension 1.4.0
Xamarin.AndroidStudio 0.7.0



```
</details>

**Screenshots**

**Reproduction Link**

**Comment by mgood7123** [comment]
the following method serves as an alternative to fix this

```
public void DrawRectCoords(float x1, float y1, float x2, float y2, SKPaint paint)
{
	DrawRect(new SKRect(x1, y1, x2, y2), paint);
}
```

**Comment by FoggyFinder** [comment]
Read docs first:

```cs
public void DrawRect (float x, float y, float w, float h, SkiaSharp.SKPaint paint);
```

https://docs.microsoft.com/en-us/dotnet/api/skiasharp.skcanvas.drawrect?view=skiasharp-2.80.2#skiasharp-skcanvas-drawrect(system-single-system-single-system-single-system-single-skiasharp-skpaint)

**Comment by mattleibow** [comment]
yeah, this was an unfortunate design decision a while back :(

`SKRect.Create` is what you want.

:(

And SKRect is a struct, so no allocations/GC.

**Comment by mattleibow** [comment]
Closing this as this method is working as designed.

The gotcha may be that the ctor of SKRect is Left, Top Right, Bottom and all other APIs use the X, Y, W, H order. Very unfortunate, but nothing we can do as this is a breaking change without an ABI break, which means it is impossible to do.

**Comment by mgood7123** [comment]
> Closing this as this method is working as designed.
> 
> The gotcha may be that the ctor of SKRect is Left, Top Right, Bottom and all other APIs use the X, Y, W, H order. Very unfortunate, but nothing we can do as this is a breaking change without an ABI break, which means it is impossible to do.

even if you introduce a new API to account for this?

**Comment by mgood7123** [comment]
> Read docs first:
> 
> ```cs
> public void DrawRect (float x, float y, float w, float h, SkiaSharp.SKPaint paint);
> ```
> 
> https://docs.microsoft.com/en-us/dotnet/api/skiasharp.skcanvas.drawrect?view=skiasharp-2.80.2#skiasharp-skcanvas-drawrect(system-single-system-single-system-single-system-single-skiasharp-skpaint)

i have, which is why `DrawRect(x1, y1, x2 - x1, y2 - y1, paint);` to account for the `w` and `h` requirements of the method
