### ISSUE TITLE
Sometimes PNG files cannot be decoded

### ISSUE THREAD

**Issue by inforithmics** [mono/SkiaSharp#1981]
**Description**

Skia Sharp 2.88.0-preview.232 does not display a png fully - in 2.88.0-preview.209 it works

**Code**

```
private void OnPaintSurface(object sender, SKPaintSurfaceEventArgs e)
		{
			// the the canvas and properties
			var canvas = e.Surface.Canvas;

			// make sure the canvas is blank
			canvas.Clear(SKColors.White);

			using var stream = File.Open(@"osm-liberty.png", FileMode.Open, FileAccess.Read, FileShare.Read);
			var data = SKData.Create(stream);
			var image = SKImage.FromEncodedData(data);

			// draw image
			canvas.DrawImage(image, new SKRect(0, 0, image.Width, image.Height));
		}
```

This should be displayed

![image](https://user-images.githubusercontent.com/2290863/160253403-f39d0d4d-0962-44ec-8c6c-32195f71e9d4.png)

But this is displayed

![image](https://user-images.githubusercontent.com/2290863/160253466-1e6f638a-f7f3-4626-9c40-d545e577eccb.png)

**Basic Information**

- Version with issue:  2.88.0-preview.232
- Last known good version:  2.88.0-preview.209
- IDE:  Visual Studio 2022 17.1.2
- Platform Target Frameworks: .Net Framework 4.8  
  - Windows Classic:  Windows 11  
 
**Reproduction Link**

[WPF.zip](https://github.com/mono/SkiaSharp/files/8356177/WPF.zip)

**Comment by inforithmics** [comment]
I tried 2.88.0-preview.254 the issue is still there

**Comment by Ziriax** [comment]
I also noticed corruption of PNGs loaded with SkiaSharp 2.88 (in my case these were 16-bit PNGs)

**Comment by inforithmics** [comment]
I played a bit around (Resaving it with Paint.net, when i Saved it as 8-bit image it worked 24 Bit or 32 Bit showed artefacts)

**Comment by inforithmics** [comment]
The workaround won't work on mobile Platforms, because Image is there not available

**Comment by inforithmics** [comment]
I checked the png Image with pngcheck and it seems to be valid.

Not working:

File: osm-liberty.png (48207 bytes)
  chunk IHDR at offset 0x0000c, length 13
    512 x 248 image, 32-bit RGB+alpha, non-interlaced
  chunk IDAT at offset 0x00025, length 32768
    zlib: deflated, 32K window, default compression
    row filters (0 none, 1 sub, 2 up, 3 avg, 4 paeth):
      0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
      0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
      0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
      0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
      0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
      0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
      0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
      0 0 0 0 0 0 0 0 (183 out of 248)
  chunk IDAT at offset 0x08031, length 15370
    row filters (0 none, 1 sub, 2 up, 3 avg, 4 paeth):
      0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
      0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
      0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 (248 out of 248)
  chunk IEND at offset 0x0bc47, length 0
No errors detected in osm-liberty.png (4 chunks, 90.5% compression).

working:

File: osm-liberty.png (52355 bytes)
  chunk IHDR at offset 0x0000c, length 13
    512 x 248 image, 32-bit RGB+alpha, non-interlaced
  chunk sRGB at offset 0x00025, length 1
    rendering intent = perceptual
  chunk gAMA at offset 0x00032, length 4: 0.45455
  chunk IDAT at offset 0x00042, length 52269
    zlib: deflated, 32K window, fast compression
    row filters (0 none, 1 sub, 2 up, 3 avg, 4 paeth):
      0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
      0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
      0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
      0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
      0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
      0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
      0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
      0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
      0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
      0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 (248 out of 248)
  chunk IEND at offset 0x0cc7b, length 0
No errors detected in osm-liberty.png (5 chunks, 89.7% compression)

What I see is that the compression method is different so maybe it is a bug in the zlib used for decompressing.

**Comment by geckomx** [comment]
Same or similar problem when moving from .NET 5 to .NET 6 . ( Nuget packet 2.80.2 and 2.80.3 )

using SKImage:

`byte[] rawData = Load();`
`SKImage img = SKImage.FromEncodedData(rawData);`

**i get corrupted image**

using SKBitmap

`SKBitmap bmp = SKBitmap.Decode(rawData);`

**i get null**

With .NET 5 both variants work.

**Comment by mattleibow** [comment]
Just compiled a debug version of skia and it loads fine. Building release now to see if that is the thing, or maybe my computer is the fix.

 If it breaks in release, I'll try step through and see where it goes. I'll also update libpng and see.

Hopefully I can see why it works in some cases. I also wonder if other platforms work, or is everyone broken.

**Comment by mattleibow** [comment]
I tried updating to the very latest of libpng and this still happens, so I think it may either have to do with something that is excluded in a release build - or something to do with the optimizations by the compiler.

I am going to test some other platforms and then try reduce the optimization level.

**Comment by mattleibow** [comment]
I tried with `SKBitmap.Decode` and it returns null. Something is happening, but at least it fails consistently across all image types.

**Comment by geckomx** [comment]
ImageSharp had a very similar issue (1704) solved by stephentoub with (1707)

**Comment by mattleibow** [comment]
Thanks @inforithmics for the research and tip, I think it was a bug in zlib so updating to a later version fixes the issue. Ad there appears to be a few fixes in the SSE bits, so looks very related.
