### ISSUE TITLE
[QUESTION] SKBitmap.GetGenerationId()

### ISSUE THREAD

**Issue by mgood7123** [mono/SkiaSharp#1995]
how would i obtain or call the SKBitmap.GetGenerationId() for the skia SkBitmap ?

i am porting https://cs.android.com/android/platform/superproject/+/master:frameworks/base/graphics/java/android/graphics/Bitmap.java to C# https://github.com/mgood7123/AndroidUI

however it requires access to the SKBitmap GetGenerationId method

```C++
    uint32_t getGenerationID() const {
        if (mBitmap) {
            return mBitmap->getGenerationID();
        }
        return mGenerationId;
    }
```

```C++
static jint Bitmap_getGenerationId(JNIEnv* env, jobject, jlong bitmapHandle)
{
    LocalScopedBitmap bitmap(bitmapHandle);
    return static_cast<jint>(bitmap->getGenerationID());
}
```

`{   "nativeGenerationId",       "(J)I", (void*)Bitmap_getGenerationId}, `

```Java
/**
    * Returns the generation ID of this bitmap. The generation ID changes
    * whenever the bitmap is modified. This can be used as an efficient way to
    * check if a bitmap has changed.
    *
    * @return The current generation ID for this bitmap.
    */
public int getGenerationId()
{
    if (mRecycled)
    {
        Log.w(TAG, "Called getGenerationId() on a recycle()'d bitmap! This is undefined behavior!");
    }
    return nativeGenerationId(mNativePtr);
}
```

**Comment by mattleibow** [comment]
Seems the binding for `SkBitmap::getGenerationID()` is pretty simple so I think I will merge a PR with that.

**Comment by mgood7123** [comment]
> Seems the binding for `SkBitmap::getGenerationID()` is pretty simple so I think I will merge a PR with that.

yea, i will see what else i can get working before i create a PR

**Comment by mgood7123** [comment]
added in my build
