### ISSUE TITLE
[BUG] Apple App Store reject Upload Xamarin Ios app containing V2.80.3 Outdated Certificate

### ISSUE THREAD

**Issue by enny1170** [mono/SkiaSharp#1998]
**Description**

When I try to Upload my Xamarin Forms Ios App to Apple App Store the upload will be rejected because of a Certificate issue. Transporter give me fallowing Messages:
ERROR ITMS-90165: "Invalid Provisioning Profile Signature. The provisioning profile included in the bundle 'net.strube.BeetControl' (Payload/BeetControl.iOS.app) cannot be used to submit apps to the iOS App Store until it has a valid signature from Apple. (Expired profile signing certificate.) For more information, visit the iOS Developer Portal."
 
ERROR ITMS-90165: "Invalid Provisioning Profile Signature. The provisioning profile included in the bundle 'xamarin.libskia-ios' (Payload/BeetControl.iOS.app/Frameworks/libSkiaSharp.framework) cannot be used to submit apps to the iOS App Store until it has a valid signature from Apple. (Expired profile signing certificate.) For more information, visit the iOS Developer Portal."

I guess the certificate used for this component is out of time. because it has worked in same configuration 10 days ago.

**Code**

**Expected Behavior**

The Upload will be work 

**Actual Behavior**

See Messages above

**Basic Information**

- Version with issue:  2.80.3
- Last known good version:  2.80.3 has worked last week
- IDE:  Visual Studio 2022
- Platform Target Frameworks: 
  - iOS:  
  
<details>
  <summary>Detailed IDE/OS information (click to expand)</summary>
  
```

PASTE ANY DETAILED VERSION INFO HERE

ERROR ITMS-90165: "Invalid Provisioning Profile Signature. The provisioning profile included in the bundle 'net.strube.BeetControl' (Payload/BeetControl.iOS.app) cannot be used to submit apps to the iOS App Store until it has a valid signature from Apple. (Expired profile signing certificate.) For more information, visit the iOS Developer Portal."
 
ERROR ITMS-90165: "Invalid Provisioning Profile Signature. The provisioning profile included in the bundle 'xamarin.libskia-ios' (Payload/BeetControl.iOS.app/Frameworks/libSkiaSharp.framework) cannot be used to submit apps to the iOS App Store until it has a valid signature from Apple. (Expired profile signing certificate.) For more information, visit the iOS Developer Portal."
</details>


**Screenshots**

<!-- if the issue is a visual issue, please include screenshots showing the problem if possible -->

**Reproduction Link**

<!-- please upload or provide a link to a reproduction case -->

**Comment by mattleibow** [comment]
I believe this error means that your certificate expired and is just complaining about the first framework it got to.

**Comment by enny1170** [comment]
This was also my first idea, but i check the certificate and the provisioning files 10 times all Dates are correct and true til march 2023.

Also i try to move back from 2.80.3 to 2.80.2 that has worked 2 weeks ago. Results in the same error.

I’m not an expert for Apple and don’t know exaclty what the Transporter App Checks during upload to the App-Store. May by somebody has a tip how to find the real reason.

A deployment to Appcenter.ms was possible and a Installation on a registered device was successfully.
This is signed with the same certificate. So i believe this is ok.

Any Idea ?

Von: Matthew ***@***.***>
Gesendet: Dienstag, 19. April 2022 15:10
An: ***@***.***>
Cc: ***@***.***>; ***@***.***>
Betreff: Re: [mono/SkiaSharp] [BUG] Apple App Store reject Upload Xamarin Ios app containing V2.80.3 Outdated Certificate (Issue #1998)


I believe this error means that your certificate expired and is just complaining about the first framework it got to.

**Comment by enny1170** [comment]
Sorry,
Seems to be an app store problem. Or the Easter Bunny repaired it. Just now I was able to upload exactly the packages that were rejected on 12 and 13.4. Thanks for the support, I close the bug.
