### ISSUE TITLE
Handler not found for view SkiaSharp.Views.Maui.Controls.SKCanvasView. 

### ISSUE THREAD

**Issue by pgmariotti** [mono/SkiaSharp#2013]
**Description**

I am developing a NetMaui app using Google Maps, and I was planning to use skiaSharp to draw the maps on the screen.
I have installed the latest version of SkiaSharp, and created the necessary code from the Maui examples.
I have a ContentView page using the CanvasView control, and in the creation of the ContentView page I set up the eventfor the control as follows:
iMap.PaintSurface += OnCanvasViewPaintSurface;

On exiting the page creation the error occurs.

        <ContentView x:Name="MapView" Background="White" VerticalOptions="FillAndExpand" HorizontalOptions="FillAndExpand"
                     Loaded="MapView_Loaded">
            <skia:SKCanvasView  x:Name="iMap" VerticalOptions="FillAndExpand" HorizontalOptions="FillAndExpand" 
                   HeightRequest="500" WidthRequest="340"/>
        </ContentView>

    public SearchPage()
	{
		InitializeComponent();
        iMap.PaintSurface += OnCanvasViewPaintSurface;
        Shell.SetNavBarIsVisible(this, false);
	}

**Expected Behavior**

No errors

The app crashes with message **Handler not found for view SkiaSharp.Views.Maui.Controls.SKCanvasView.** 

**Basic Information**

- Version with issue:  2.88.0-preview.256
- Last known good version:  
- IDE:  VS2022 Preview Version 17.2.0 Preview 5.0
- Platform Target Frameworks: NeyMaui Release Candidate 2
  - Android: 30 
- Target Devices:   Android emulator (Pixel 5)>
  
<details>

**Comment by mattleibow** [comment]
Did you add the UseSkiaSharp method to the appBuilder in MauiProgram.cs? We are working on a way to not have to do this, but for now, you need to indicate to the app that you are using SkiaSharp.

**Comment by mattleibow** [comment]
This is the issue to track these hidden failures: https://github.com/dotnet/maui/issues/7258
