### ISSUE TITLE
[BUG] Avif is not present in SKEncodedImageFormat enum

### ISSUE THREAD

**Issue by mgood7123** [mono/SkiaSharp#2017]
AVIF support was added to SkHeifCodec in Skia milestone 88

also in SkEncodedImageFormat enum - https://github.com/google/skia/blob/chrome/m88/include/core/SkEncodedImageFormat.h

**Comment by mgood7123** [comment]
added in my build

**Comment by LukePulverenti** [comment]
@mgood7123 since you added that, has it worked well?

**Comment by mgood7123** [comment]
> @mgood7123 since you added that, has it worked well?

have not got a chance to test it yet a i dont have any AVIF encoded images

https://github.com/mono/skia/pull/92

https://github.com/mono/SkiaSharp/pull/2154

**Comment by mattleibow** [comment]
Thanks for the issue and the work to get all the PRs up. I have merged and it will appear in the preview feed shortly as well as in the next SkiaSharp release.
