### ISSUE TITLE
[QUESTION] How to pack  SkiaSharp.NativeAssets.Linux.nupkg  and   HarfBuzzSharp.NativeAssets.Linux.nupkg  in  native Linux environment?

### ISSUE THREAD

**Issue by LuckyXu-HF** [mono/SkiaSharp#2027]
Hello! 
    I want to pack SkiaSharp.NativeAssets.Linux.nupkg  and  HarfBuzzSharp.NativeAssets.Linux.nupkg  on my  native Linux environment.
    But  I  don't  know  the  pack  step  of  how  to  generate  these  two  nupkg.  Could you please give me some advice on how to generate  these  two  nupkg  on Linux environment? 

Thanks!

**Comment by mattleibow** [comment]
There is a cake target. `dotnet cake --target=nugets`

 I may have used singular nuget... Afk now, but basically cake. Or the bootstrapper.sh --target=nugets
