### ISSUE TITLE
SKCanvas.DrawPicture does not respect paint's color?

### ISSUE THREAD

**Issue by Capt-Nemo-** [mono/SkiaSharp#203]
Hey guys, awesome project you got here! NGraphics and XamSVG now feel obsolete :))
Anyways during playing with SkiaSharp I noticed I cannot get my svg's (imported via the prerelease SkiaSharp.Svg) painted in any other color than default black (on UWP, didn't try other platforms yet). The DrawPicture call completely ignores the color I set for the paint object. Is this a bug or am I doing something wrong?

**Comment by Capt-Nemo-** [comment]
To clarify, I'm trying to set a default color for picture rendering (that comes from svg file) ie. my svg files don't have any colors set and are rendered black which is not very flexible, I can of course set color in svg source file but I was hoping I can achieve same result programatically (without messing with source files).

**Comment by mattleibow** [comment]
You can do this by painting the picture with a color filter:

```csharp
using (var paint = new SKPaint()) {
    paint.ColorFilter = SKColorFilter.CreateXferMode(SKColors.Red, SKXferMode.SrcIn);
    canvas.DrawPicture(svg.Picture, paint);
}
```

**Comment by hwd71** [comment]
This works great for Android, but doesn't work on Desktop for me. Or the newer
paint.ColorFilter = SKColorFilter.CreateBlendMode(SKColor.Red, SKBlendMode.SrcIn);
I'm using an fa.solid SVG.

**Comment by hwd71** [comment]
Apologies, having moved up versions, confirmed working on desktop and android.
