### ISSUE TITLE
PNG Image Load Corruption [BUG] 

### ISSUE THREAD

**Issue by toptensoftware** [mono/SkiaSharp#2043]
**Description**

Some (not all) PNG images loaded in SkiaSharp 2.88.0-preview.224 and later are corrupted.

**Code**

See simple demo project [here](https://github.com/toptensoftware/SkiaSharpImageLoadIssue/)

Relevant code [here](https://github.com/toptensoftware/SkiaSharpImageLoadIssue/blob/main/Program.cs).

**Expected Behavior**

Image shouldn't be corrupted

**Actual Behavior**

Image is corrupted

**Basic Information**

- Version with issue:  2.88.0-preview.224 and later
- Last known good version:  2.88.0-preview.223
- IDE:  dotnet command line
- Platform Target Frameworks:
  - Windows Classic:  Windows 10
  
<details>
  <summary>Detailed IDE/OS information (click to expand)</summary>
  
```

dotnet --version
6.0.300

```
</details>

**Screenshots**

Ignore the blue squiggles, that was us testing trying to narrow this down.

Original:

![Original](https://github.com/toptensoftware/SkiaSharpImageLoadIssue/raw/main/testimage.png)

Corrupted:

![Corrupted](https://github.com/toptensoftware/SkiaSharpImageLoadIssue/raw/main/testimage_resave.png)

**Reproduction Link**

See [here](https://github.com/toptensoftware/SkiaSharpImageLoadIssue/)

**Comment by mattleibow** [comment]
Possibly related to #1981

**Comment by mattleibow** [comment]
Yup, #2045 fixes this issue.
