### ISSUE TITLE
SKGLView on .NET MAUI is missing a handler

### ISSUE THREAD

**Issue by praeclarum** [mono/SkiaSharp#2050]
I can’t use SKGLView because its handler is missing. SKCanvasView works fine.

```csharp
new SKGLView();
```

**Expected Behavior**

A working OpenGL view.

**Actual Behavior**

Runtime error saying no handler found.

**Basic Information**

- Version with issue:  latest
- Last known good version:  none 
- IDE:  VSMPreview
- Platform Target Frameworks:
  - macCatalyst:
- Target Devices:
  - Mac

**Comment by mattleibow** [comment]
Yeah... Seems the iOS team deleted that. There is no GL view for mac cat. Not sure what to do. Might need to use metal, but this is slightly different.

**Comment by praeclarum** [comment]
Tell them to put it back. Mac Cat supports OpenGL.

**Comment by praeclarum** [comment]
OK, looks like Apple has removed GL from Catalyst. FML :-) 

So… How about that MAUI `SKGpuView` That uses Metal on Apple and GL everywhere else? :-)

**Comment by xtuzy** [comment]
Hope Skiasharp can have more perfect support😊
|platform |ios|android|winui3|maccatalyst|
|--|--|--|--|--|
|cpu|SKCanvasView|SKCanvasView|SKXamlCanvas|SKCanvasView|
|gpu|SKGLVIew,SKMetalView|SKGLSurfaceView,SKSurfaceView,SKGLTextureView|✗|SKMetalView|

|platform |ios|android|winui3|maccatalyst|
|--|--|--|--|--|
|maui cpu SKCanvasView|✓|✓|✓|✓|
|maui gpu SKGLVIew|✓|✓|✗|✗|

**Comment by marcojak** [comment]
Does it mean that for MAUI we don't have gpu support on WinUI3 and MacCatalyst?
Is it something that is going to change?

**Comment by charlesroddie** [comment]
Agreed the SkGpuView is a good idea.

On the subject of ios/maccatalyst naming, ios seems to include maccatalyst which is a bit confusing. Perhaps SkiaSharp.Views.Uikit would be more accurate.

Currently this is regulated by:
https://github.com/mono/SkiaSharp/blob/b8efe44ae79614d7c0c0739e7144427912fd166a/source/SkiaSharp.Views/SkiaSharp.Views.Apple/SKMetalView.cs#L18
```
#if __IOS__
namespace SkiaSharp.Views.iOS
#elif __MACOS__
namespace SkiaSharp.Views.Mac
#endif
```
And catalyst seems to be _IOS_. For example https://github.com/mono/SkiaSharp/blob/b8efe44ae79614d7c0c0739e7144427912fd166a/samples/Gallery/Uno.WinUI/SkiaSharpSample.Mobile/SkiaSharpSample.Mobile.csproj#L33

```
<PropertyGroup Condition="'$(TargetFramework)'=='net6.0-ios' or '$(TargetFramework)'=='net6.0-maccatalyst'">
```
