### ISSUE TITLE
Doesn't work on Windows 10 Mobile with OpenGL backend

### ISSUE THREAD

**Issue by MxNxP** [mono/SkiaSharp#207]
Both the official sample app (https://www.microsoft.com/en-ca/store/p/skiasharp-for-windows/9nblggh51856) and our own SkiaSharp based application shows only a white screen on Windows 10 Mobile with OpenGL backend.

**Comment by mattleibow** [comment]
Interesting... Could you share device specs? And what versions of DX are on those devices?

**Comment by mattleibow** [comment]
I think I managed to find a device that has the same issue: Lumia 435. I get a blank white screen.

I am having a look to see what is going on, but it appears to be an issue with the way the context is initialized.

**Comment by mattleibow** [comment]
Some more investigation: There appears to be a problem with my offscreen buffer with the lower-end devices. The Lumia 435 appears to use DX9.3. If I force the drawing to FBO 0, then the image is visible, but if I draw to FBO 1, and then blit that to FBO 0, nothing appears. 

Because it works on both my Lumia 950XL and SurfaceBook, I think the fallback to DX9 may cause some change somewhere that results in the buffers not working as expected.

**Comment by MxNxP** [comment]
Thank your for your response and for all the great work you're doing!

We are using the following devices for testing, because these are cheap, but popular phones and i think DX9.3 capable devices still have a high market share.

Unfortunately i don't have experience with directx development..

__test device #1__
type: Miscrosoft Lumia 550
OS: Windows 10 Mobile
OS build: 10.0.14393.448
Qualcomm Adreno 304
DirectX11 Feature level 9.3

__test device #2__
type: Miscrosoft Lumia 435
OS: Windows 10 Mobile
OS build: 10.0.14393.448
Qualcomm Adreno 305
DirectX11 Feature level 9.3

**Comment by Azmarel** [comment]
Hi
I have the same problem with: 
Nokia Lumia 735
Windows 10 Mobile

Did you find a solution for this problem ??

**Comment by MxNxP** [comment]
No, we couldn't find any workaround, so we are waiting for a bug fix.

**Comment by imregazdag** [comment]
Hi! Is there an approximate date when will be fixed this issue? (we would like to use SkiaSharp in our project and Windows Phone is one of our main platforms)

**Comment by entdark** [comment]
Hello.
I have the same problem on Lumia 550.
It works fine on the emulator and desktop.

**Comment by entdark** [comment]
It also happens on Lumia 640 XL LTE.

**Comment by mattleibow** [comment]
I am closing this as this is no longer something that is going to be supported in the future. Windows 10 Mobile is really no more.

I believe that I have "fixed" the real cause of he underlying GL issue with the rewrite of the UWP views, but I have also changed the way libSkiaSharp.dll builds for UWP. As a result, it no longer runs on the old Windows Phones. It still works on my Lumia 950 XL, so it is nothing to do with the ARM component, but rather somewhere it id causing one of the dependencies not to be loaded.

If someone really needs UWP for Windows 10 Mobile, we need to open a new issue and hopefully the community can help out. From the side of the SkiaSharp team, we feel that the deprecated Mobile platform is not a priority at this point in time.
