### ISSUE TITLE
[BUG] ArgumentNullException when loading this jpeg

### ISSUE THREAD

**Issue by MartinDemberger** [mono/SkiaSharp#2076]
**Description**

When I load the attached image a `ArgumentNullException` is thrown:

**Code**

```csharp
using (var inputStream = new FileStream("#2804.jpg"))
using (var image = SKBitmap.Decode(inputStream))
{
    return (image.Width, image.Height);
}
```

**Expected Behavior**

The file is loaded and the correct size (2215/1772) is returnde.

**Actual Behavior**

This exception is thrown.
```
Message: 
System.ArgumentNullException : Value cannot be null. (Parameter 'buffer')

  Stack Trace: 
SKManagedStream.OnReadManagedStream(IntPtr buffer, IntPtr size)
SKManagedStream.OnRead(IntPtr buffer, IntPtr size)
SKAbstractManagedStream.ReadInternal(IntPtr s, Void* context, Void* buffer, IntPtr size)
SkiaApi.sk_codec_new_from_stream(IntPtr stream, SKCodecResult* result)
SKCodec.Create(SKStream stream, SKCodecResult& result)
SKCodec.Create(Stream stream, SKCodecResult& result)
SKCodec.Create(Stream stream)
SKBitmap.Decode(Stream stream)
```

**Basic Information**

- Version with issue: 2.88.0 
- Last known good version: 2.80.2 
- IDE: VS 17.3.0 Preview 1 
- Platform Target Frameworks: 
  - Windows Classic: Windows 10 
  
**Screenshots**

The Image to reproduce the error.

![#2804](https://user-images.githubusercontent.com/3066149/169712798-f7a7c8f0-ecd1-4c5a-8d49-5d2a20a85a61.jpg)

**Reproduction Link**

**Comment by Poolitzer80** [comment]
Hi Martin, 

i could resolve the bug with the following workaround 
https://github.com/mono/SkiaSharp/issues/1551

**Comment by MartinDemberger** [comment]
Thank you very much.
