### ISSUE TITLE
[BUG] Image artifacts after > 2.88.0-preview.209 

### ISSUE THREAD

**Issue by adirh3** [mono/SkiaSharp#2084]
**Description**

Somewhere after version 2.88.0-preview.209 (not including), strange artifacts show in some images.

**Code**

Here is an Avalonia project that repros the issue (including the image) -
[Image Artifacts SkiaSharp Avalonia.zip](https://github.com/mono/SkiaSharp/files/8791519/Image.Artifacts.SkiaSharp.Avalonia.zip)

**Expected Behavior**

![image](https://user-images.githubusercontent.com/27368554/170835868-221d95f3-39c2-4e09-8805-9e16d0d15abc.png)

**Actual Behavior**

![image](https://user-images.githubusercontent.com/27368554/170835604-aa6a3332-76f3-42ab-a763-f41a7b9c7e92.png)

**Basic Information**

- Version with issue:  > 2.88.0-preview.209 (checked with stable and preview.254)
- Last known good version:   2.88.0-preview.209
- Platform Target Frameworks: 
  - Windows Classic: checked with Windows 11 only

**Comment by mattleibow** [comment]
Can you try the latest SkiaSharp preview? It might have been fixed in #2045

**Comment by adirh3** [comment]
> Can you try the latest SkiaSharp preview? It might have been fixed in #2045

It's fixed with `2.88.1-preview.1`, sorry haven't noticed there is already a new preview.
Closing, thanks!
