### ISSUE TITLE
[BUG] Decode PNG image problem

### ISSUE THREAD

**Issue by KyungtackKim** [mono/SkiaSharp#2095]
**Description**

When decoding a PNG image, some areas of the image crack.

**Code**

```
// path = PNG image file path
// get bitmap
using (var bitmap = SKBitmap.Decode(path))
{
    // check image size
    if (bitmap.Info.Width <= 4096 || bitmap.Info.Height <= 4096)
    {
        // get scale information
        var scale = Math.Min(1280.0f / bitmap.Width, 800.0f / bitmap.Height);
        var x = (1280 - scale * bitmap.Width) / 2;
        var y = (800 - scale * bitmap.Height) / 2;
        var rect = new SKRect(x, y, x + scale * bitmap.Width, y + scale * bitmap.Height);
        // draw image
        canvas.DrawBitmap(bitmap, rect,
            new SKPaint { IsAntialias = true, FilterQuality = SKFilterQuality.High });
    }
}
```

**Expected Behavior**

**Actual Behavior**

**Basic Information**

- Version with issue:  SkiaSharp.Views.WindowsForms v2.88.0
- Last known good version:  SkiaSharp.Views.WindowsForms v2.80.4
- IDE:  Visual studio 2019
- Platform Target Frameworks:  WinForm .NetFramework 4.8
- Target Devices:  Windows 11
  
<details>
  <summary>Detailed IDE/OS information (click to expand)</summary>
  
```

PASTE ANY DETAILED VERSION INFO HERE

```
</details>

**Screenshots**

![2022-06-02 11_45_04-Position](https://user-images.githubusercontent.com/36721725/171542291-d41a5b55-45f8-40cb-b43e-03931b491632.png)
( v2.80.4 )

![2022-06-02 11_45_49-Position](https://user-images.githubusercontent.com/36721725/171542313-545884f7-5789-4116-b238-7a40da2f2ed3.png)
( v2.88.0 )

**Reproduction Link**

image file download : https://hantas-my.sharepoint.com/:i:/g/personal/kyungtack_kim_hantas_kr/EX0xZOqr7TlDv6NVZOs4rcYB2i1jZHhxte9U6CfGoweCkg?e=7y0T3X

**Comment by mgood7123** [comment]
0.0

**Comment by miszu** [comment]
Noticed similar issues with jpg - interesting fact is that it works fine when running in Xamarin.iOS iPhone simulator environment, but doesn't work in a unit test env (MacBook M1, NET 6.0) - sometimes these random artefacts appear, as posted by @KyungtackKim.

**Comment by AkulaKirov** [comment]
this should be fixed at 2.88.1-pre1. have you try it?

**Comment by miszu** [comment]
@AkulaKirov I checked and it fixed my issues, thanks a lot! 🙌🏻 Hopefully worked for @KyungtackKim as well.

**Comment by KyungtackKim** [comment]
@miszu

Thank you for the update. I am also using 2.88.1-peview.1 and this problem no longer appears.
