### ISSUE TITLE
[BUG] Pointer-Events not working on SKXamlCanvas on iOs and Android

### ISSUE THREAD

**Issue by TopperDEL** [mono/SkiaSharp#2106]
**Description**
I have a control inherited from SKXamlCanvas and attach event-handlers there for these events:

- PointerPressed
- PointerMoved
- PointerReleased
- PointerExited
- PointerCaptureLost
- Tapped
- DoubleTapped

But none of those gets triggered on iOs and Android. On Windows/WinUI it is working as expected.

**Expected Behavior**
The events should get raised.

**Actual Behavior**
The events don't get raised.

**Basic Information**

- Version with issue:  SkiaSharp.Views.Uno.WinUI 2.88.1-preview.63
- IDE:  Visual Studio

**Comment by jeromelaban** [comment]
The canvas does not propagate events at this time by default, because it's not hit-testable by default. You can set the background to "Transparent" to get pointer events. See this sample: https://github.com/unoplatform/Uno.Samples/tree/master/UI/SkiaSharpTest

**Comment by TopperDEL** [comment]
Oh, that is nice! Simply setting the background to transparent should do it? But will I receive the events within SKXamlCanvas still?

**Comment by jeromelaban** [comment]
Try the sample and see if it does what you need.

**Comment by TopperDEL** [comment]
It works by setting ``Background="transparent"``. Thanks!
