### ISSUE TITLE
[BUG] SKXamlCanvas reports only half for ActualWidth and ActualHeight on iOs

### ISSUE THREAD

**Issue by TopperDEL** [mono/SkiaSharp#2107]
**Description**
If I draw something using the ActualWidth and ActualHeight of the SKXamlCanvas on iOs, it reports half of the size the canvas actually is. If e.g. I draw a rectangle like this:

``
e.Surface.Canvas.DrawRect(new SKRect(0, 0, (float)ActualWidth, (float)ActualHeight), new SKPaint(SKColors.Red) });
``

it only occupies one quarter of the whole canvas. I'm not sure if there is any Scaling factor in place or some DPI-issue. It might be related to [this](https://github.com/unoplatform/uno/issues/7255) issue, where the underlying Bitmap is also rendered smaller on iOs and Android then it should be.

Is there any scaling/DPI-setup happening in SkiaSharp?

I may provide a sample if necessary - just running out of time for the moment.

**Expected Behavior**
The ActualSize is correct

**Actual Behavior**
The ActualSize is reported wrong.

**Comment by TopperDEL** [comment]
@jeromelaban Do you have an idea on this one? The size reported from SKXamlCanvas on iOs is wrong - it is only 1/2 of the real size.

**Comment by jeromelaban** [comment]
This is likely expected if your screen is using a scale of 200%. `ActualWith` and `ActualHeight` are DPI independent. You'll need to use the canvas size to do your computations.

**Comment by mattleibow** [comment]
Depending on what Uno does, you can either use the `XamlRoot.RasterizationScale` or the `DisplayInformation.GetForCurrentView().LogicalDpi / 96.0`.

That is what I do for UWP/WinUI things: https://github.com/mono/SkiaSharp/blob/main/source/SkiaSharp.Views/SkiaSharp.Views.UWP/SKXamlCanvas.cs#L100-L113

**Comment by TopperDEL** [comment]
Thanks! That did the trick. I've used the Canvas-Size for the basic calculations and used the Dpi-Value to adjust touch points.
Thank you both!
