### ISSUE TITLE
[BUG] The type initializer for 'SkiaSharp.SKData' threw an exception in Blazor WebAssembly

### ISSUE THREAD

**Issue by aung-ko-zan** [mono/SkiaSharp#2124]
**Description**

I'm trying to resize image using SkiaSharp on different platform. This code work in Xamarin Forms and WindowForm. I'm confusing that SkiaSharp does not support Blazor WebAssembly or a bug.

**Code**

`
var skImage = SKImage.FromEncodedData(imageStream);
`

**Expected Behavior**

Exception should describe details.

**Actual Behavior**

Exception: The type initializer for 'SkiaSharp.SKData' threw an exception.

**Basic Information**

- Version with issue:  2.88.0
- IDE: Visual Studio 2022 Version 17.2.4
- Platform Target Frameworks: .Net6 Blazor WebAssembly
- Target Devices: Windows 10 Pro Build 19043.1766
Google Chrome Version 102.0.5005.115 (Official Build) (64-bit)

**Screenshots**

![Screenshot 2022-06-22 161255](https://user-images.githubusercontent.com/106807647/174998340-5c2ab922-c20c-48a3-89c4-2df9dd046b59.png)

**Comment by mattleibow** [comment]
I think this is a duplicate of #2109.

As a workaround you can just install the SkiaSharp.Views.Blazor package. Let me know if this fixes it and I can get a fix in for the next release.

**Comment by aung-ko-zan** [comment]
The issue was fixed by installing SkiaSharp.Views.Blazor.
