### ISSUE TITLE
SKCanvasView (in Forms) does not resize correctly when in a StackLayout on iOS.

### ISSUE THREAD

**Issue by xeterixon** [mono/SkiaSharp#215]
First: Thanks for a great library. We are in the process of replacing our old implementation for sketching on images with SkiaSharp. So far, works like a charm. 

When having a Forms SKCanvasView in a StackLayout, the canvas view does not seem to resize as it should when rotating the device, at least not on iOS. 
Say we have a simple page like this:
```
public class MainPage : ContentPage
{
   public MainPage()
   {
      BackgroundColor = Color.Red;
      Padding = new Thickness(10, 10, 10, 10);
      var canvas = new SkiaSharp.Views.Forms.SKCanvasView {
         HorizontalOptions = LayoutOptions.FillAndExpand,
         VerticalOptions = LayoutOptions.FillAndExpand
      };
      canvas.PaintSurface += PaintSurface;
      Content = new StackLayout {
         HorizontalOptions = LayoutOptions.FillAndExpand,
         VerticalOptions = LayoutOptions.FillAndExpand,
         BackgroundColor = Color.Blue,
         Padding = new Thickness(10, 10, 10, 10),
         Children = { canvas }
      };
   }
   void PaintSurface(object sender, SkiaSharp.Views.Forms.SKPaintSurfaceEventArgs e)
   {
      e.Surface.Canvas.Clear(SkiaSharp.SKColors.AliceBlue);
      e.Surface.Canvas.DrawText(
         "This is the Skia View", 100, 100,
         new SkiaSharp.SKPaint {
            IsStroke = false,
            IsAntialias = true,
            TextSize = 30,
            Color = SkiaSharp.SKColors.Black
         });
   }
}
```
It looks ok in portrait, but when rotating the device to landscape the skia view stretches outside the bounds of the layout, even outside the bounds of the page.
Sample images:
Portrait:
![portrait](https://cloud.githubusercontent.com/assets/7112456/21853077/ec7b83fc-d815-11e6-9999-94d2e8d46959.png)

Landscape:
![landscape](https://cloud.githubusercontent.com/assets/7112456/21853052/cc943066-d815-11e6-998b-5c0e257dcff6.png)

As far as I know, it's an iOS issue. It seems to work fine on Droid. I haven't tried it on UWP. 

Wrapping the canvas in a Grid instead of StackLayout does work as intended. I haven't tried any other layouts. 

Regards...

**Comment by bugadani** [comment]
Also, SKGLView does not scale automatically in UWP as well, it only works with fixed size requests.

**Comment by mattleibow** [comment]
Closing this as this is not really an issue with SkiaSharp per se, but rather the particular layout combinations. A SkiaSharp surface has no intrinsic size, or a way to calculate a size since it is not a container of any kind.

The correct way to control the surface size is to either use a container that manages the size of the surface, or to set a specific size for the surface.

**Comment by xeterixon** [comment]
It migth not be an issue for SkiaSharp but it is for SkiaSharp.View.Forms, IMHO, since the view doesn't  behave in the same way as any aother Forms view.

**Comment by mattleibow** [comment]
By providing a "default" size, the correct size can be correctly calculated.

**Comment by bugadani** [comment]
Oh so this is why my view has a fixed 40 height now... I've spent an hour looking for why... Problem is, it broke my previous sizing method :( Back to my drawing board, I guess.
