### ISSUE TITLE
visual studio 2022 crashes when loading my solution

### ISSUE THREAD

**Issue by vsfeedback** [mono/SkiaSharp#2161]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/visual-studio-2022-crashes-when-loading-/10010478)._

---
visual studio 2022 crashes when loading my solution  
when i load visual studio without my solution, (or another solution) it does not crash.

I had this problem before, but it went away when upgrading visual studio 2022.  
I have been working in this solution - VS version just yesterday and everything was fine.  
Now it crashes on open.

Using the latest vs version 17.1.3

the solution loads without crashing in VS 2019

---
#### Feedback Bot on 4/11/2022, 03:21 AM: 

(private comment, text removed)
#### Kaylee Xu [MSFT] on 4/11/2022, 11:18 PM: 

(private comment, text removed)
#### sjors miltenburg on 4/20/2022, 06:44 AM: 

(private comment, text removed)
#### sjors miltenburg on 4/11/2022, 11:34 PM: 

(private comment, text removed)
#### Kaylee Xu [MSFT] on 4/13/2022, 01:35 AM: 

(private comment, text removed)
#### sjors miltenburg on 4/13/2022, 03:26 AM: 

(private comment, text removed)
#### Kaylee Xu [MSFT] on 4/13/2022, 08:42 PM: 

(private comment, text removed)
#### Feedback Bot on 4/20/2022, 08:38 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by mattleibow** [comment]
I believe it was this issue: https://github.com/Redth/ResizetizerNT/commit/9e0defbd4bb5366d3f3b5d2526765a1d5c3dccd4
