### ISSUE TITLE
[BUG] SkiaSharp unable to load library libSkiaSharp or one of its dependencies after update alpine

### ISSUE THREAD

**Issue by pkrittikorn** [mono/SkiaSharp#2169]
**Description**

The version of SkiaSharp is 2.80.3. It's work fine at mcr.microsoft.com/dotnet/aspnet:3.1-alpine3.13 but after I update to alpine3.15, I got this error message.

System.TypeInitializationException: The type initializer for 'SkiaSharp.SKImageInfo' threw an exception.\n ---> System.DllNotFoundException: Unable to load shared library 'libSkiaSharp' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: Error loading shared library liblibSkiaSharp: No such file or directory\n   at SkiaSharp.SkiaApi.sk_colortype_get_default_8888()\n   at SkiaSharp.SKImageInfo..cctor()\n   --- End of inner exception stack trace ---\n   at SkiaSharp.SKImageInfo..ctor(Int32 width, Int32 height, SKColorType colorType, SKAlphaType alphaType)\n   at SkiaSharp.SKSurface.Create(Int32 width, Int32 height, SKColorType colorType, SKAlphaType alphaType)

**Basic Information**

- Version with issue:  
     - SkiaSharp: 2.80.3
     - SkiaSharp.AssetNative.Linux.NoDependencies: 2.80.3
- Last known good version:  2.80.3

**Comment by mattleibow** [comment]
Might be related to this issue:

https://github.com/dotnet/core/issues/6985

**Comment by mattleibow** [comment]
Seems that they added alpine 3.15 and 3.16 to the hierarchy: https://github.com/dotnet/corefx/blob/v3.1.28/pkg/Microsoft.NETCore.Platforms/runtime.json#L80

But in the actual docker image (which is 3.1.28) it is not there...

**Comment by mattleibow** [comment]
I added this to my docker image and it works... who knows what will break:

```Dockerfile
RUN sed -i 's/alpine.3.14/alpine.3.15/g' /usr/share/dotnet/shared/Microsoft.NETCore.App/3.1.28/Microsoft.NETCore.App.deps.json
```

**Comment by mattleibow** [comment]
Unfortunately, this is a .NET bug so it would be better to open an issue on the [dotnet/runtime](https://github.com/dotnet/runtime) repo.

I did mention it to folks on the SDK team, but have yet to get a reply since it is probably bedtime/hometime/lunchtime there depending on where in the world this part of the team works. Hopefully the workaround gets you going again, and the issue that you file gets the real issue fixed.

**Comment by mattleibow** [comment]
Filed this issue to hopefully get it fixed: https://github.com/dotnet/sdk/issues/27156
