### ISSUE TITLE
[BUG] SkiaSharp crashes on Google Pixel 6 Pro in certain cases (works on other phones)

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [mono/SkiaSharp#2211]
**Description**

We have a mobile game that draws its screen using Xamarin.Forms and SKGLView. The game has a zoom-in and zoom-out feature. The Android version of the game works on other Android phones but crashes on Google Pixel 6 Pro (which is using Google Tensor).

Steps to reproduce:
1. Install GnollHack on Google Pixel 6 Pro: https://play.google.com/store/apps/details?id=com.soundmindentertainment.gnollhack
2. Start the game with any character.
3. Click the world icon in the top-right corner to zoom out.
4. The game immediately crashes.

The stack trace in Google Play Console is the following (in Crashes and ANRs):
```
  #00  pc 0x000000000004b840  /apex/com.android.runtime/lib64/bionic/libc.so (__memcpy)
  #00  pc 0x0000000000761304  /vendor/lib64/egl/libGLES_mali.so
  #00  pc 0x00000000007886f8  /vendor/lib64/egl/libGLES_mali.so
  #00  pc 0x000000000076880c  /vendor/lib64/egl/libGLES_mali.so
  #00  pc 0x000000000070d5c8  /vendor/lib64/egl/libGLES_mali.so
  #00  pc 0x00000000002a04f0  /data/app/~~oTNqPNewwEuNK1kY9zcycA==/com.soundmindentertainment.gnollhack-0Tl1bC3mrLN6t3tiD-Qkmw==/split_config.arm64_v8a.apk!libSkiaSharp.so
```

You can deactivate GPU Acceleration in the settings, and then the game uses SKCanvasView for drawing. It works perfectly. So, the problem is apparently the GPU drivers of Google Pixel 6 Pro.

**Code**

The game is open source. You can find its code here:
https://github.com/hyvanmielenpelit/GnollHack

Android build instructions are here:
https://github.com/hyvanmielenpelit/GnollHack/wiki/Build-Instructions-for-Android-Version-on-Windows

**Expected Behavior**

The game will not crash, when zooming out.

**Actual Behavior**

The game crashes, when zooming out.

**Basic Information**

- Version with issue:  2.80.3 and 2.80.4
- Last known good version:  -
- IDE:  Visual Studio 2022 Community (Windows) 17.3.0
- Platform Target Frameworks: 
  - Android: 11.0 (R)
- Target Devices:  Google Pixel 6 Pro

**Comment by mattleibow** [comment]
Are you able to try v2.88.1-preview.*?

I wonder if there were bug fixes in skia that solve this...

**Comment by TommiGustafsson-HMP** [comment]
We tested it with 2.88.1-preview104 but it was 10000 times slower than 2.80.4 and could not draw the main screen well. Maybe it's because our sprite sheet is 10000x10000? Because of this slowness we could not test if it worked with Google Pixel 6 Pro. The slowness was there with both SKGLView and SKCanvasView.

**Comment by mattleibow** [comment]
The slowdown is maybe this issue: https://github.com/mono/SkiaSharp/issues/2188?

I hope to look into that next week.

**Comment by TommiGustafsson-HMP** [comment]
> The slowdown is maybe this issue: #2188?
> 
> I hope to look into that next week.

That workaraund certainly helped, but SkiaSharp 2.88 has still severe performance issues, especially in MAUI. Please see #2555.
