### ISSUE TITLE
DecodeGifFramesSample not working with the OpenGL Backend

### ISSUE THREAD

**Issue by DeanClaes** [mono/SkiaSharp#222]
It seems that the gif is showing but it's not being animated. However, it does work when using the 'Memory' backend. I'm not really sure whats causing the issue.

This test was on a real Android device.

**Comment by mattleibow** [comment]
I also noticed that, and I think it has to do with the way the GPU is handled. I need to confirm, but I think the bitmap is only passed once to the GPU, so when the next frame is decoded into the bitmap, it is not pushed to the GPU.

I was able to get it going when I created multiple bitmaps, and drew each one.

**Comment by DeanClaes** [comment]
Thanks for your reply.

Before, I used to make multiple bitmaps as well but I found your solution to be more elegant (and it's probably more performant as well).

**Comment by mattleibow** [comment]
Did the animation play when you had separate bitmaps? I must ask on the Google skia forums to see how to do this properly.

**Comment by DeanClaes** [comment]
Well it was only me messing around but instead of directly playing the gif I had made 10 seperate images (I had them saved as heart1.png heart2.png). Next I just put them all in a list and I looped over them. I had the RefreshSamples method on a loop and in the onDrawSample it would just call canvas.DrawBitmap. This did work but it's not a proper solution.

**Comment by mattleibow** [comment]
"Fixed" in a3979a262fa87ab54962d5236bb7a6302226853c

Basically, the bitmap has no way of knowing that the pixels have changed, and when drawing to the GPU, the bitmap is cached. So to tell the GPU that it needs to get the new pixel data, we invoke the `NotifyPixelsChanged()` method.

**Comment by DeanClaes** [comment]
Hello @mattleibow 

First of all thanks for having taken a look at this. I have just tested the new changes but I was a little bit suprised to find out that the OpenGL backed was showing the frames slower than the memory backend.
When testing I found out that the memory backend interval between each DrawSample() call was about 100 ms, whereas it was about 160-180ms for the OpenGL backend. 
Even when not drawing anything the AnimatedSampleBase takes quite a chunck of cpu. The thing that seems to be causing this are the repeated calls to {CanvasForBackend}.InvalidateSurface in the AnimatedSampleBase.

So I was just wondering if this is expected behavior? If so would you suggest using the Memory backend instead for displaying gifs?

Thank you

**Comment by mattleibow** [comment]
This may be the case since the bitmap has to be copied to the GPU for each frame. What you may want to do is either create multiple images for each frame, which can be copied once to the GPU. 

Also, you might want to actually use a `SKImage` that is backed by the GPU, thus nothing has to be copied when drawing.
