### ISSUE TITLE
[BUG] corner radius isnt rendering on skia svg's

### ISSUE THREAD

**Issue by gsgou** [mono/SkiaSharp#2220]
**Description**

corner radius isnt rendering on skia svg's

**Expected Behavior**

corner radius is rendering

**Actual Behavior**

corner radius isnt rendering

**Basic Information**

- Version with issue:  2.88.1
- Last known good version:  not known
- IDE:  Visual Studio for Mac
- Platform Target Frameworks:
  - Android: 12.1
  - iOS:  15
  
This renders correct
![de](https://user-images.githubusercontent.com/911534/185456931-44ca0e14-2298-46f0-b751-8b3fedd9a9e2.svg)

This does not render correct
![de-de](https://user-images.githubusercontent.com/911534/185456947-7576278a-4aa4-4c0d-969b-770a3df459f8.svg)

**Comment by mattleibow** [comment]
Svg.Skia is a separate project so closing this one so they can track it there.

**Comment by gsgou** [comment]
@mattleibow does Skia.Svg library has still a more complete implementation of Svg document model then [SkiaSharp.Extended.Svg](https://github.com/mono/SkiaSharp.Extended)? 

The issue is also reproduced with SkiaSharp.Extended. Should i open the issue there also instead of here?

**Comment by mattleibow** [comment]
Far more complete. Also, the SkiaSharp.Extended.Svg has been abandoned in favour of Svg.Skia for just this reason.

**Comment by gsgou** [comment]
Tks for the quick feedback @mattleibow
