### ISSUE TITLE
canvas.Clear(SKColors.Transparent) does not work on XF/Android when I use SKGLView.

### ISSUE THREAD

**Issue by allbdeveloper** [mono/SkiaSharp#223]
SkiaSharp ver : 1.56.0
tested on Xamarin.Forms 

"canvas.Clear(SKColors.Transparent);" does not work when I use SKGLView on XF/Android.

It's working fine on XF/iOS.
And both are working fine when I use SKCanvasView.

and I set already View's backgroud color as "transparent" as well.

**Comment by mattleibow** [comment]
I think Android is a bit limited (http://stackoverflow.com/questions/2034822/android-opengl-es-transparent-background) in that you can either have an opaque GL surface below everything, or a transparent GL surface above everything. Nothing in between.

There are suggestions to use a [`TextureView`](https://developer.android.com/reference/android/view/TextureView.html), but I will need to first create a renderer.

**Comment by allbdeveloper** [comment]
Hi Matthew. 

Thanks for your research and answer.

**Comment by mattleibow** [comment]
Closing this as I will have to use a `TextureView` to support transparency.

**Comment by mattleibow** [comment]
@allbdeveloper I have reached what I think is good to go...

 - [SkiaSharp.1.60.0-beta.nupkg](https://jenkins.mono-project.com/view/Components/job/Components-SkiaSharp/lastSuccessfulBuild/Azure/processDownloadRequest/ArtifactsFor-319/eb629db98be18a73870fcab33b677512ec6bc02a/output/SkiaSharp.1.60.0-beta.nupkg)
 - [SkiaSharp.Views.1.60.0-beta.nupkg](https://jenkins.mono-project.com/view/Components/job/Components-SkiaSharp/lastSuccessfulBuild/Azure/processDownloadRequest/ArtifactsFor-319/eb629db98be18a73870fcab33b677512ec6bc02a/output/SkiaSharp.Views.1.60.0-beta.nupkg)
 - [SkiaSharp.Views.Forms.1.60.0-beta.nupkg](https://jenkins.mono-project.com/view/Components/job/Components-SkiaSharp/lastSuccessfulBuild/Azure/processDownloadRequest/ArtifactsFor-319/eb629db98be18a73870fcab33b677512ec6bc02a/output/SkiaSharp.Views.Forms.1.60.0-beta.nupkg)

Give that a whirl and let me know what happens. The Xamarin.Forms view should now be using the TextureView under the hood.
