### ISSUE TITLE
Could not load file or assembly 'SkiaSharp.Views.Desktop, Version=1.68.0.0

### ISSUE THREAD

**Issue by DJK-GIT** [mono/SkiaSharp#2233]
Are there any known issues regarding this?  I'm working in a .NET 4.7.2 project and using Version=1.68.0.0 of Skia.  We are using this version because it has to integrate with a powerbuilder app and we have everything working correctly with Skia except when we try to invoke the following method:

DymoPrinter.Instance.PrintLabel(dymoSDKLabel, "", copies, barcodeGraphsQuality);

The exception thrown is:
Could not load file or assembly 'SkiaSharp.Views.Desktop, Version=1.68.0.0, Culture=neutral, PublicKeyToken=0738eb9f132ed756' or one of its dependencies.

Obviously I checked and this package does indeed exist in the project so I'm not sure what is missing.  I tried uninstalling/reinstalling several times and that did not work.

**Comment by mattleibow** [comment]
Are you able to reproduce this in a console app? Is it possible to attach a repro project for bower builder?
