### ISSUE TITLE
Cannot create the PDF document using the SkiaSharp-related library

### ISSUE THREAD

**Issue by mukeshanand123** [mono/SkiaSharp#2234]
We are using Quest pdf for generate pdf and working fine in local directory. but when deploy in  GKE
there is some dependency issue .
Note:- I have installed all dependecy packages like linux, mac, dependecy , but getting same error in google cloud.
Cannot create the PDF document using the SkiaSharp-related library. This exception usually means that, on your operating system where you run the application, SkiaSharp-related requires installing additional dependencies. Such dependencies are available as additional nuget packages, for example *.NativeAssets.Linux.NoDependencies. Some operating systems may require installing multiple nugets, e.g. MacOS may need both *.NativeAssets.macOS.NoDependencies and *.NativeAssets.Linux.NoDependencies.Please refer to the SkiaSharp-related documentation for more details. Also, please consult the inner exception that has been originally thrown by the dependency library.",
    "StatusCode": 500

**Comment by mattleibow** [comment]
Are you able to attach a repro sample of this?

Also, please attach any information about the operating system and hardware of the cloud instance - like OS name/version along with any CPU information.

**Comment by mukeshanand123** [comment]
hi mattlebow,
please find details.
OS Name:     debian
OS Version:  11
OS Platform: Linux

**Comment by mattleibow** [comment]
Could you attach a sample repro.

**Comment by mattleibow** [comment]
Please open an issue on the QuestPdf repository.
