### ISSUE TITLE
[BUG] Skottie Animation not created when running MAUI targeting Android

### ISSUE THREAD

**Issue by bluechiperic** [mono/SkiaSharp#2237]
**Description**

I am creating a Lottie animation in my MAUI app, and it works correctly targeting Windows, but when I target Android, I get the exception:  "Method not found: System.TimeSpan SkiaSharp.Skottie.Animation.get_Duration()'"

**Code**

var stream = await FileSystem.OpenAppPackageFileAsync(Source);
string data = (new System.IO.StreamReader(stream)).ReadToEnd();
// load Lottie animation
SkiaSharp.Skottie.Animation.TryParse(data, out animation);

// Read important values
var duration = animation.Duration.TotalSeconds;

**Expected Behavior**

Work the same on Android as it does Windows

**Actual Behavior**

When I remove the reference to animation.Duration, I don't get the exception, but the app crashes when it tries to parse the animation json data.

**Basic Information**

- Version with issue:  2.88.1
- IDE:  Visual Studio
- Platform Target Frameworks: 
  - Android:  
  - Target Devices:   Samsung S21 Ultra

**Comment by mattleibow** [comment]
I am wondering if you potentially have a bad nuget from a preview or something. What are your nuget feeds? Do you have a nuget.config and maybe go clear your nuget cache.

I don't think I made any stable versions public, but if you open the net6.0-android dll in the skottie nuget, what is the git has embedded... Or maybe zip up the SkiaSharp dlls in your bin folder and attach it here.

I know at one point the properties were double or long, but then we changed it to TimeSpan to make things less ambiguous.
