### ISSUE TITLE
`skia_use_fontconfig=false` causing problems?

### ISSUE THREAD

**Issue by simendsjo** [mono/SkiaSharp#2248]
I notice that `SkiaSharp.NativeAssets.Linux.NoDependencies` is unable to locate my system fonts. Could it be because of this setting? I'm running Guix System, so I don't have an `/usr/share/fonts` or similar. I guess NixOS users will have the same issue.

**Comment by Gillibald** [comment]
NoDependencies means Skia is using a font manager that is only loading fonts via some specific file system location. You can still load your fonts via stream.

**Comment by simendsjo** [comment]
I'm using `SkiaSharp.NativeAsserts.Linux` instead, and patchelf to set rpath to my library folder which contains fontconfig and other necessary libraries.
