### ISSUE TITLE
[BUG] SkiaSharp does not work in Blazor of Asp.Net 7 RC1

### ISSUE THREAD

**Issue by jjzhang12** [mono/SkiaSharp#2258]
**Description**

SkiaSharp does not work in Blazor of Asp.Net 7 RC1

**Code**

@page "/"

@using SkiaSharp
@using SkiaSharp.Views.Blazor

<SKCanvasView OnPaintSurface="OnPaintSurface"/>

@code {

    void OnPaintSurface(SKPaintSurfaceEventArgs e)
    {

        var canvas = e.Surface.Canvas;

        using var paint = new SKPaint { Color = new SKColor(0xEB000000) };
        canvas.DrawLine(0, 0, 300, 300, paint);
    }
}

**Expected Behavior**

A line will be drawn

**Actual Behavior**

Got exception:
System.TypeInitializationException: The type initializer for 'SkiaSharp.SKImageInfo' threw an exception.
        ---> System.DllNotFoundException: libSkiaSharp

**Basic Information**

- Version with issue:   2.88.2
- Last known good version:   .net 6
- IDE:   VS 2022 17.4.0 preview2
- Platform Target Frameworks: 
  - Android:  
  - iOS:  
  - Linux:  
  - macOS:  
  - Tizen:   
  - tvOS:  
  - UWP:   
  - watchOS:  
  - Windows Classic:  
- Target Devices:   
  - 
  - 
  
<details>
  <summary>Detailed IDE/OS information (click to expand)</summary>
  
```

Install VS 2022 17.4.0 Preview2 and .Net SDK 7.0 RC
Create a Blazor WebAssembly Empty project targeting to .net 7.0 preview
Add Nugets to SkiaSharp and SkiaSharp.View.Blazor 2.88.2
Replace the index.razor with above code

```
</details>

**Screenshots**

**Reproduction Link**

**Comment by RChrisCoble** [comment]
Hello @mattleibow, I sent an email to you last week on this request.  Do you have any feedback?  Thanks.

**Comment by jjzhang12** [comment]
This seems to be the Visual Studio V17.4 Preview 2 issue. I just updated to V17.4 Preview 2.1 and my above sample works fine.
