### ISSUE TITLE
[BUG] Upgrading to 2.88.3 crashed .NET (7.0) MAUI SKCanvas on Windows

### ISSUE THREAD

**Issue by TRSkillman** [mono/SkiaSharp#2271]
**Description**

Upgrading to 2.88.3 on a basic .NET MAUI (.NET 7.0) SKCanvas causes an unhandled exception [36176/57572] on Windows
Please note this bug does not occur on .net 6.0.

**Code**
1. Create a .NET MAUI app (using .net 7.0)
2. Add SkiaSharp (2.88.3), SkiaSharp.Views.Maui.Controls (2.88.3) & SkiaSharp.Views.Maui.Core (2.88.3) packages
3. Add .UseSkiaSharp() in MauiProgram.cs builder
4. Clear demo code from MainPage and code-behind
5. Add an SKCanvas in MainPage.xaml

```
<?xml version="1.0" encoding="utf-8" ?>
<ContentPage xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             xmlns:skia="clr-namespace:SkiaSharp.Views.Maui.Controls;assembly=SkiaSharp.Views.Maui.Controls"
             x:Class="SkiaCanvasSetup.MainPage">

    <Grid RowDefinitions="*" >
        <skia:SKCanvasView Grid.Row="0" x:Name="skiaView" 
                PaintSurface="OnPaintSurface"
                EnableTouchEvents="True" Touch="OnTouch" 
                IgnorePixelScaling="True">
        </skia:SKCanvasView>
    </Grid>

</ContentPage>
```
    
6. Add in events handler for OnTouch and OnPaintSurface
 

**Expected Behavior**

No unhandled exceptions

**Actual Behavior**

Run the project for Windows - unhandled exception [36176, 57572, 47724]

**Basic Information**

- Version with issue:  2.88.3 
- Last known good version:  2.88.2 
- IDE:  VS 2022 Community (17.4.0 Preview 2.1)
- Platform Target Frameworks: net7.0-windows10.0.19041.0
  - Windows 11 Pro (21H2) 
- Target Devices:   
  - Windows Machine
  
<details>
  <summary>Detailed IDE/OS information (click to expand)</summary>
  
```

PASTE ANY DETAILED VERSION INFO HERE

```
</details>

**Screenshots**

![Screenshot 2022-10-04 101500](https://user-images.githubusercontent.com/109348188/193782317-f28ea98c-7a91-4bdf-ba31-2517a7f794e1.png)

**Reproduction Link**

https://github.com/TRSkillman/Maui/tree/master/SkiaCanvasSetup

**Comment by mattleibow** [comment]
Does this happen on any other platform? I will have to try debug windows' incredibly dodgy exception handling... Literally could be anything. Any other platform. Will help if you are able to test.

I'll also test your repo here and see.

**Comment by TRSkillman** [comment]
> Does this happen on any other platform? I will have to try debug windows' incredibly dodgy exception handling... Literally could be anything. Any other platform. Will help if you are able to test.
> 
> I'll also test your repo here and see.

I've tried on Android only and it works fine (haven't got Mac setup).  .NET6.0 also works OK.  
I'll do some more digging and tests for specific errors.

**Comment by mattleibow** [comment]
I think I found it and is also just logged here an hour ago #2272

Try adding this to your csproj:

```xml
<ItemGroup>
    <FrameworkReference Update="Microsoft.Windows.SDK.NET.Ref" 
        RuntimeFrameworkVersion="10.0.19041.27" 
        TargetingPackVersion="10.0.19041.27" />
</ItemGroup>
```

I will try reduce the version I build with. I wonder if the net6 sdk has a later windows runtime than net7...

**Comment by TRSkillman** [comment]
Yes, that worked :)
Thanks
