### ISSUE TITLE
[BUG] SkiaSharp.Views.WinUI doesn't work with .Net 7

### ISSUE THREAD

**Issue by Summpot** [mono/SkiaSharp#2272]
**Description**

> Assembly 'SkiaSharp.Views.Windows' with identity 'SkiaSharp.Views.Windows, Version=2.88.0.0, Culture=neutral, PublicKeyToken=0738eb9f132ed756' uses 'WinRT.Runtime, Version=2.0.0.0, Culture=neutral, PublicKeyToken=99ea127f02d97709' which has a higher version than referenced assembly 'WinRT.Runtime' with identity 'WinRT.Runtime, Version=1.6.0.0, Culture=neutral, PublicKeyToken=99ea127f02d97709'

**Code**

**Expected Behavior**

**Actual Behavior**

**Basic Information**

<details>
  <summary>Detailed IDE/OS information (click to expand)</summary>
  
```

PASTE ANY DETAILED VERSION INFO HERE

```
</details>

**Screenshots**

**Reproduction Link**
[App1.zip](https://github.com/mono/SkiaSharp/files/9705366/App1.zip)

**Comment by mattleibow** [comment]
Booo. I literally got this right now and I am trying to figure this out.

Try adding this to your csproj:

```xml
<FrameworkReference Update="Microsoft.Windows.SDK.NET.Ref" RuntimeFrameworkVersion="10.0.19041.27" TargetingPackVersion="10.0.19041.27" />
```

**Comment by mattleibow** [comment]
@Summpot  updating WASDK here: https://github.com/mono/SkiaSharp/pull/2276
