### ISSUE TITLE
[FEATURE] set alpha to 'ff' by default in SKColor(UInt32) constructor 

### ISSUE THREAD

**Issue by beto-rodriguez** [mono/SkiaSharp#2274]
**Is your feature request related to a problem? Please describe.**

Based on https://github.com/beto-rodriguez/LiveCharts2/issues/602

When a SKColor is created using the `uint` constructor the alpha channel is 0 by default.

```
var a = new SKColor(0xD65282);
var b = new SKColor(0xFFD65282);

var alphaEquals = a.Alpha == b.Alpha ;
// should be true by default?
```

**Describe the solution you'd like**

It would be more intuitive that the alpha channel is `255` instead of zero when it is not specified.

**Describe alternatives you've considered**

Set the alpha channel manually.

**Additional context**

none.

**Comment by mattleibow** [comment]
This is an interesting one.

One of the issues with this is how would you represent a color that has no alpha? (not sure if that is something that people do)

This is also a breaking change, so not sure how possible if people are doing things with 0 alpha...

Maybe the unexpectedness of this warrants a change.

**Comment by beto-rodriguez** [comment]
I am not sure if there is a standard, but on HTML colors this is really common. The alpha channel is by default 'ff' unless you specify it, there are multiple color tables on hexadecimal format, like [material colors](https://material.io/resources/color/#!/?view.left=0&view.right=0&primary.color=9575CD) or [fluent colors](https://developer.microsoft.com/en-us/fluentui#/styles/web/colors/shared).

If this is implemented it would more intuitive to get a color from any color table on the web:


![skiacolor](https://user-images.githubusercontent.com/10853349/194145073-ef0ddce8-08ce-4290-8329-3878ed375c51.gif)

**Comment by themcoo** [comment]
`SKColor.Parse(string) ` does exactly that. It actually provides the same rules as you would expect from setting a hex color in CSS:
```
        foreach (var str in new [] { "123", "123456", "aabbccdd", "#112233" })
	{
		Console.WriteLine(SKColor.Parse(str).ToString());
	}
```
	
outputs:
```
#ff112233
#ff123456
#aabbccdd
#ff112233
```

I would be sad if the current behaviour for uint based constructor was changed.
