### ISSUE TITLE
Android skia canvas.DrawImage has no effect with SkiaBitmapExportContext

### ISSUE THREAD

**Issue by rmarinho** [mono/SkiaSharp#2283]
---
**Issue moved from dotnet/maui#10575**
- Please respond to @philipag.

---

_From @philipag on Sunday, October 9, 2022 1:50:52 PM_

### Description

When using SKCanvasView, one can use canvas.DrawImage and image is displayed.
However, when using SkiaBitmapExportContext.Canvas.DrawImage, nothing is rendered into the canvas.

Please see the attached sample for details.  It saves the file badOutputWithoutImage.png which should contain the Android robot image but does not.  It only shows the white background which was rendered into the canvas.

[skiaBug.zip](https://github.com/dotnet/maui/files/9741717/skiaBug.zip)

### Steps to Reproduce

1. Build the attached sample, build and run on an emulator.
2. Use Android Studio to navigate to and view the output file "badOutputWithoutImage.png"
3. The file does not contain the android robot image that was painted into the canvas (it should).

### Link to public reproduction project repository

attached

### Version with bug

6.0.486 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android, I was *not* able test on other platforms

### Affected platform versions

Android 12

### Did you find any workaround?

no

**Comment by philipag** [comment]
Hi @mattleibow Could you provide more information what "not planned" means or an alternative way that this could be done?  Minimally it seems that if bitmaps cannot be rendered like this then a NotSupportedException should be thrown.

**Comment by mattleibow** [comment]
Ah sorry. I moved it back into the Maui issue as this is a maui graphics issue as far as I can tell. I should have updated this.
