### ISSUE TITLE
[BUG] Drawing a pattern with a path effect is not clipping to the points

### ISSUE THREAD

**Issue by gktval** [mono/SkiaSharp#2284]
**Description**

I am drawing a path of points with an inner hatch pattern. However, the pattern is not getting clipped to the interior of the points. Note ( I have also tried g.ClipPath(gp), but it did not affect the results). Below is the path drawn with the inner path and later with the outline of the points in the path. The green hatch is the path effect. (Notice that the hatch is getting drawn beyond the path points.)

![image](https://user-images.githubusercontent.com/7605046/194938976-12c658e7-01bb-482b-94d5-a7226509cfc6.png)

**Code**

```
        Dim hatchMatrix As SKMatrix = SKMatrix.CreateScale(10, 10)
        Dim hatchWidth As Single = 20

        ' create the path (diagonal hatch) with the center at 0,0
        Dim hatchPath = New SKPath()
        hatchPath.MoveTo(0, hatchWidth)
        hatchPath.LineTo(hatchWidth, 0)
        hatchPath.LineTo(0, -hatchWidth)
        hatchPath.LineTo(-hatchWidth, 0)
        hatchPath.LineTo(0, hatchWidth)

        Using hatchPaint As New SKPaint
            hatchPaint.PathEffect = SKPathEffect.Create2DPath(hatchMatrix, hatchPath)
            hatchPaint.Color = SKColors.LimeGreen
            hatchPaint.Style = SKPaintStyle.Stroke
            hatchPaint.StrokeWidth = 1

            g.DrawPath(gp, hatchPaint)
        End Using
 ```

**Expected Behavior**
I would expect that the hatch is getting clipped to the polygon itself, not the outer extents of the polygon.

**Actual Behavior**

The hatch pattern is getting clipped to the extents of the polygon.

**Basic Information**
 net6.0-windows10.0.19041.0
SkiaSharp version 2.88.2

**Comment by themcoo** [comment]
I used your code to generate the same effect and with ClipPath before DrawPath I achieved the desired effect:

	g.Save() ' this is to be able to restore clipping path
        g.ClipPath(gp)
	g.DrawPath(gp, hatchPaint)
	g.Restore()

Before clip:

![image](https://user-images.githubusercontent.com/2964157/203776077-4e75e89a-63d4-40c7-b18c-63447422632d.png)

After clip applied:
![image](https://user-images.githubusercontent.com/2964157/203776031-8319b8b1-8ceb-4ccf-b75b-d100fd2c4cc5.png)
