### ISSUE TITLE
Text measurement support

### ISSUE THREAD

**Issue by kekekeks** [mono/SkiaSharp#23]
To draw text layout properly one needs [SkPaint::breakText](https://people.mozilla.org/~bgirard/doxygen/gfx/classSkPaint.html#a2f67d6bc4440396adb50af367ee08b85) and [SkPaint::measureText](https://people.mozilla.org/~bgirard/doxygen/gfx/classSkPaint.html#a4892a1b1fd671acc9d99b5ccd8ff92d8)

**Comment by toehead2001** [comment]
I just updated to the v1.49.1 Nuget package, but when I try to use `BreakText(string, maxWidth)` I get an exception:
`Unable to find an entry point named 'sk_paint_break_utf16_text' in DLL 'libskia_windows.dll'.`
