### ISSUE TITLE
[BUG] Build fails for iossimulator-arm64

### ISSUE THREAD

**Issue by spouliot** [mono/SkiaSharp#2307]
**Description**

SkiaSharp's native assets for iOS ships as a `.framework`. This only allow an arch, like `arm64`, to be included a single time. This is a problem now that iOS (phones) and iOS simulators both needs `arm64` _slices_ to build.

Apple's solution is to use `.xcframework`. This allows a single distribution to cover all (Apple) platforms. This allows shipping arm64 support for both iOS and iOS simulators (and many more) from a single package.

**Code**

Build any app using SkiaSharp for the iOS simulator running on arm64 (Apple Silicon)

**Expected Behavior**

A successful build

**Actual Behavior**

```
 DebugMyApp.Mobile -> /Users/poupou/git/uno/uno-debug-test/DebugMyApp/DebugMyApp.Mobile/bin/Debug/net6.0-ios/iossimulator-arm64/DebugMyApp.Mobile.dll
  Optimizing assemblies for size, which may change the behavior of the app. Be sure to test after publishing. See: https://aka.ms/dotnet-illink
  Tool xcrun execution finished (exit code = 1).
          
  ld: building for iOS Simulator, but linking in dylib built for iOS, file '/Users/poupou/.nuget/packages/skiasharp.nativeassets.ios/2.88.3/runtimes/ios/native/libSkiaSharp.framework/libSkiaSharp' for architecture arm64
  clang: error: linker command failed with exit code 1 (use -v to see invocation)
  
/usr/local/share/dotnet/packs/Microsoft.iOS.Sdk/16.0.523/targets/Xamarin.Shared.Sdk.targets(1222,3): error : clang++ exited with code 1: [/Users/poupou/git/uno/uno-debug-test/DebugMyApp/DebugMyApp.Mobile/DebugMyApp.Mobile.csproj]
/usr/local/share/dotnet/packs/Microsoft.iOS.Sdk/16.0.523/targets/Xamarin.Shared.Sdk.targets(1222,3): error : ld: building for iOS Simulator, but linking in dylib built for iOS, file '/Users/poupou/.nuget/packages/skiasharp.nativeassets.ios/2.88.3/runtimes/ios/native/libSkiaSharp.framework/libSkiaSharp' for architecture arm64 [/Users/poupou/git/uno/uno-debug-test/DebugMyApp/DebugMyApp.Mobile/DebugMyApp.Mobile.csproj]
/usr/local/share/dotnet/packs/Microsoft.iOS.Sdk/16.0.523/targets/Xamarin.Shared.Sdk.targets(1222,3): error : clang: error: linker command failed with exit code 1 (use -v to see invocation) [/Users/poupou/git/uno/uno-debug-test/DebugMyApp/DebugMyApp.Mobile/DebugMyApp.Mobile.csproj]
```

**Workaround**

Build as x86_64 and use Rosetta at runtime. Still, it's inefficient, slower and might not work if some other dependencies are not available on x86_64.

**Basic Information**

- Version with issue: 2.88.3 (and previous versions)
- Last known good version:  none, not a regression
- IDE:  all
- Platform Target Frameworks:
  - iOS:  simulator builds / arm64 target

**Comment by wieslawsoltes** [comment]
Facing similar issue
```

  Xamarin.Shared.Sdk.targets(1230, 3): clang++ exited with code 1:
ld: building for iOS Simulator, but linking in dylib built for iOS, file '/Users/wieslawsoltes/.nuget/packages/harfbuzzsharp.nativeassets.ios/2.8.2.1-preview.108/runtimes/ios/native/libHarfBuzzSharp.framework/libHarfBuzzSharp' for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by roubachof** [comment]
same here, I think there is no x86_64 flavor included in the lib.

> Application\/1F18FC2E-105F-4ED4-8216-5D476FFDBE27\/MauiSample.app\/Frameworks\/libSkiaSharp.framework\/libSkiaSharp' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64'))

**Comment by mlancione** [comment]
Any update on this issue?

**Comment by Yves-Be** [comment]
@mattleibow 
I'm still seeing the issue with 2.88.4-preview.76
The build is running on a Windows machine that remotes to an ARM Mac, maybe this matters.
`
2>Tool xcrun execution finished (exit code = 1).
2>ld: building for iOS Simulator, but linking in dylib built for iOS, file '/Users/me/Library/Caches/Xamarin/mtbs/builds/Niko.Ui.Maui.Demo/6f5be72ad50f5863a2024f136fde45cd089cd74037e55700cf6471bf0860db59/C:/Users/me/.nuget/packages/skiasharp.nativeassets.ios/2.88.4-preview.76/runtimes/ios/native/libSkiaSharp.framework/libSkiaSharp' for architecture arm64
2>clang: error: linker command failed with exit code 1 (use -v to see invocation)
2>C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk\16.4.8525-net8-p5\targets\Xamarin.Shared.Sdk.targets(1306,3): error : clang++ exited with code 1:
2>C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk\16.4.8525-net8-p5\targets\Xamarin.Shared.Sdk.targets(1306,3): error : ld: building for iOS Simulator, but linking in dylib built for iOS, file '/Users/me/Library/Caches/Xamarin/mtbs/builds/Niko.Ui.Maui.Demo/6f5be72ad50f5863a2024f136fde45cd089cd74037e55700cf6471bf0860db59/C:/Users/me/.nuget/packages/skiasharp.nativeassets.ios/2.88.4-preview.76/runtimes/ios/native/libSkiaSharp.framework/libSkiaSharp' for architecture arm64
2>C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk\16.4.8525-net8-p5\targets\Xamarin.Shared.Sdk.targets(1306,3): error : clang: error: linker command failed with exit code 1 (use -v to see invocation)
`

**Comment by Yves-Be** [comment]
@mattleibow 
I'm still seeing the issue with 2.88.4-preview.76
The build is running on a Windows machine that remotes to an ARM Mac, maybe this matters.
```
2>Tool xcrun execution finished (exit code = 1).
2>ld: building for iOS Simulator, but linking in dylib built for iOS, file '/Users/me/Library/Caches/Xamarin/mtbs/builds/Niko.Ui.Maui.Demo/6f5be72ad50f5863a2024f136fde45cd089cd74037e55700cf6471bf0860db59/C:/Users/me/.nuget/packages/skiasharp.nativeassets.ios/2.88.4-preview.76/runtimes/ios/native/libSkiaSharp.framework/libSkiaSharp' for architecture arm64
2>clang: error: linker command failed with exit code 1 (use -v to see invocation)
2>C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk\16.4.8525-net8-p5\targets\Xamarin.Shared.Sdk.targets(1306,3): error : clang++ exited with code 1:
2>C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk\16.4.8525-net8-p5\targets\Xamarin.Shared.Sdk.targets(1306,3): error : ld: building for iOS Simulator, but linking in dylib built for iOS, file '/Users/me/Library/Caches/Xamarin/mtbs/builds/Niko.Ui.Maui.Demo/6f5be72ad50f5863a2024f136fde45cd089cd74037e55700cf6471bf0860db59/C:/Users/me/.nuget/packages/skiasharp.nativeassets.ios/2.88.4-preview.76/runtimes/ios/native/libSkiaSharp.framework/libSkiaSharp' for architecture arm64
2>C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk\16.4.8525-net8-p5\targets\Xamarin.Shared.Sdk.targets(1306,3): error : clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by filipnavara** [comment]
@Yves-Be That's a different error - mismatch between iOS Device and iOS Simulator build. AFAIK Visual Studio doesn't even support deploying to ARM64 iOS Simulator yet.

**Comment by Yves-Be** [comment]
Deploying to an ARM64 iOS Simulator has been working since 2021 here (both with Xamarin and .NET 6)
Building, deploying and running a clean .NET 8 app works fine on the simulator.
As soon as SkiaSharp is added, I'm getting the issue that was being discussed here.

**Comment by filipnavara** [comment]
> Deploying to an ARM64 iOS Simulator has been working since 2021 here (both with Xamarin and .NET 6)

I think you are mistaken. It was never supported in legacy Xamarin and on .NET 6+ it was not supported in the IDE without hacks either (https://github.com/xamarin/xamarin-macios/issues/15393).

**Comment by RobGibbens** [comment]
For anybody using .NET MAUI and coming across this issue: As of this writing, the SkiaSharp.Extended.UI.MAUI Nuget package is at version 2.0.0-preview.61, and has not been updated since August 30, 2022. This package has an implicit dependency on SkiaSharp >= 2.88.1, which doesn't include the merged fixes from @mattleibow. I was able to fix this compiler error by explicitly referencing the SkiaSharp Nuget package of 2.88.4-preview.84, which does include this fix.

cc: @Yves-Be @m1ksoftware @mlancione @roubachof @wieslawsoltes
