### ISSUE TITLE
[BUG] Cleartype / subpixel text rendering still broken?

### ISSUE THREAD

**Issue by AquilaAbriel** [mono/SkiaSharp#2308]
**Description**

Cleartype / subpixel text rendering seems to (still) be broken.
Last Update I've seen is #830 from August, but the issue was already brought up in January.
As far as I can tell the entire 2.88.p1 - 2.88.3 version of SkiaSharp is affected.
Is there any news on if / when this issue might get fixed?

**Very simple WPF Desktop example**
```
using System.Windows;
using SkiaSharp;
using SkiaSharp.Views.Desktop;

namespace ClearType
{
    /// <summary>
    /// Interaction logic for MainWindow.xaml
    /// </summary>
    public partial class MainWindow : Window
    {
	public MainWindow()
	{
		InitializeComponent();
	}

	private void OnPaintSurface(object sender, SKPaintSurfaceEventArgs e)
	{
		// the the canvas and properties
		var canvas = e.Surface.Canvas;

		// get the screen density for scaling
		var scale = 1f;
		var scaledSize = new SKSize(e.Info.Width / scale, e.Info.Height / scale);

		// handle the device screen density
		canvas.Scale(scale);

		// make sure the canvas is blank
		canvas.Clear(SKColors.White);

		// draw some text
		var paint = new SKPaint
		{
			Color = SKColors.Black,
			IsAntialias = true,
			Style = SKPaintStyle.Fill,
			TextAlign = SKTextAlign.Center,
			TextSize = 24
		};

		var font = new SKFont
		{
			Edging = SKFontEdging.SubpixelAntialias,
			Size = 24
		};

		canvas.DrawText(
			"SkiaSharp",
			scaledSize.Width / 2,
			(scaledSize.Height + paint.TextSize) / 2,
			font,
			paint);
	}
    }
}
```

**Expected Behavior**

When I'm running the old UWP example posted by @cilliemalan #830 
(Or if I downgrade my SkiaSharp version to 2.80.4)
Subpixel AA text rendering works as expected. (zoomed in):
![Expected](https://user-images.githubusercontent.com/7701826/201118236-7f474afb-68f6-4bc6-9fe8-6e4d8f43aecd.png)

**Actual Behavior**

When I'm running my ported WPF example (using the same code above)
Text ist rendered using standard AA (zoomed in):
![Result](https://user-images.githubusercontent.com/7701826/201117803-ba5f8e69-faec-4eaa-a501-1a2c9840c51f.png)

**Basic Information**

- Version with issue: 2.88.3
- Last known good version: 2.80.4
- IDE: Visual Studio 2022
- Platform Target Frameworks: Windows 10

**Comment by themcoo** [comment]
The change was actually done in google/skia, related to https://bugs.chromium.org/p/skia/issues/detail?id=3934

So in short words the `PixelGeometry` on created surface is now defaulting to `Unknown` instead of `RgbHorizontal`. To bring back the default behaviour the `SKSurface` ctor must be provided `SKSurfaceProperties` with `SKPixelGeometry`, e.g.:
`using var surface = SKSurface.Create(imageInfo, new SKSurfaceProperties(SKPixelGeometry.RgbHorizontal));`

**Comment by themcoo** [comment]
Well I haven't used any skiasharp views, but just going through the code I don't see a possibility currently to hook up with different pixel geometry. Glad that at least you could find a workaround

**Comment by themcoo** [comment]
Indeed vertial geometry is somewhat ignored. But that's too deep in glyph rendering engine in google/skia for me to find time to investigate. For another workaround you could render everything on you offscreen canvas rotated -90 degrees and then render the canvas rotated 90 degrees back :)

**Comment by michaldobrodenka** [comment]
It would be nice if I could set for WPF SKElement (and also on other platforms) Pixel geometry other than unknown
