### ISSUE TITLE
SK3dView y axis inverted?

### ISSUE THREAD

**Issue by KingSora** [mono/SkiaSharp#231]
Hi!

My code looks like:

```csharp
SK3dView v = new SK3dView();
v.Translate(10, 10, 0); //x10, y10, z0
using (SKCanvas canvas = surface.Canvas) {
  canvas.SetMatrix(v.Matrix);
  canvas.DrawRect(new SKRect(0, 0, 100, 100), new SKPaint() { 
    Color = new SKColor(255, 0, 0), 
    IsAntialias = true, });
}
```

Now the painted rectangle is not on the position x[10], y[10] (as I would expect it), its is on the position x[10], y[-10].
Is this a correct behavior?

EDIT:
The Z-Axis has the same behavior. A negative value makes the rectangle appear greater and a positive value makes the rectangle appear smaller.

Best regards,
Sora

**Comment by mattleibow** [comment]
I think this is the desired/correct functionality.
Here is a fiddle: https://fiddle.skia.org/c/1554299ac982bee3eb824a4b1985a87b

![image](https://cloud.githubusercontent.com/assets/1096616/22620749/f9337b26-eb2b-11e6-8cf2-eba685b7e814.png)

There are 4 rectangles:
1. GRAY - initial/base
2. GREEN - moved +50 pixels along the X axis
3. BLUE - moved +50 along the Y axis
4. RED - moved +200 pixels along the Z axis

As you can see, the origin is the bottom, left (typical in 3D spaces) and the Z direction is away from the screen.

It is important to remember that this transformation doesn't change the actual canvas matrix origin. It is still the top left.
