### ISSUE TITLE
Not able resize image on Unix OS

### ISSUE THREAD

**Issue by Manish082007** [mono/SkiaSharp#2315]
I am not able to resize images using SkiaSharp. It is working fine on windows and ubuntu (using Visual studio remote debugging). I am using Amazon ECS Services and deploying a docker image on ECS Service. I am using `SkiaSharp.NativeAssets.Linux.NoDependencies` library file version `2.88.3`. I tried a different solution & code from the internet but no luck. I have mentioned my code & error below.

>**I have below questions**
>1. Does `SkiaSharp` support Unix operating system?
>2. Why is it not able to find the codec? 
>3. What am I doing wrong & how can I solve it?

**Below is OS information from Aws ECS Service.**
Shell command output: PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
4.14.294-220.533.amzn2.x86_64 kernel version

### Attempt 1
```
Error: Value cannot be null. (Parameter 'codec') at SkiaSharp.SKBitmap.Decode(SKCodec codec)

using (SKBitmap originalImage = SKBitmap.Decode(attachment))
{
    (int desiredWidth, int desiredHeight) = GetImageResizeSize(originalImage.Width, originalImage.Height);

    using (SKBitmap resizedImage = originalImage.Resize(new SKImageInfo(desiredWidth, desiredHeight, originalImage.ColorType, originalImage.AlphaType, originalImage.ColorSpace), SKFilterQuality.None))
    {
        using (SKImage image = SKImage.FromBitmap(resizedImage))
        {
            MemoryStream outputImageStream = new();

            image.Encode(SKEncodedImageFormat.Jpeg, 80).SaveTo(outputImageStream);

            return outputImageStream.ToArray();
        }
    }
}
```

### Attempt 2
```
Error: System.NullReferenceException: Object reference not set to an instance of an object.

MemoryStream inputAttachmentStream = new(attachment)
{
    Position = 0
};

SKManagedStream skiaManagedStream = new(inputAttachmentStream);
SKData imageInputData = SKData.Create(skiaManagedStream);
using (SKBitmap originalImage = SKBitmap.Decode(imageInputData))
{
    (int desiredWidth, int desiredHeight) = GetImageResizeSize(originalImage.Width, originalImage.Height);

    using (SKBitmap resizedImage = originalImage.Resize(originalImage.Info.WithSize(desiredWidth, desiredHeight), SKFilterQuality.None))
    {
        using (SKImage image = SKImage.FromBitmap(resizedImage))
        {
            MemoryStream outputImageStream = new();

            image. Encode(SKEncodedImageFormat.Jpeg, 80).SaveTo(outputImageStream);

            return outputImageStream.ToArray();
        }
    }
}
```

### Attempt 3
```
Error: System.ArgumentNullException: Value cannot be null. (Parameter 'image') at SkiaSharp.SKBitmap.FromImage(SKImage image)

MemoryStream inputAttachmentStream = new(attachment)
{
    Position = 0
};

using SKManagedStream stream = new SKManagedStream(inputAttachmentStream, false);
SKImage img = SKImage.FromEncodedData(stream);
SKBitmap? bitmap = SKBitmap.FromImage(img);

(int desiredWidth, int desiredHeight) = GetImageResizeSize(bitmap. Width, bitmap. Height);

using (SKBitmap resizedImage = bitmap.Resize(bitmap.Info.WithSize(desiredWidth, desiredHeight), SKFilterQuality.None))
{
    using (SKImage image = SKImage.FromBitmap(resizedImage))
    {
        MemoryStream outputImageStream = new();

        image.Encode(SKEncodedImageFormat.Jpeg, 80).SaveTo(outputImageStream);

        return outputImageStream.ToArray();
    }
}
```

**Please, let me know, if anyone required more information from my side.
Thank You.**

**Comment by themcoo** [comment]
what does attachment contain? are you sure it's raw image data? could you dump its the contents to a file?

**Comment by Manish082007** [comment]
@themcoo - I have issue with every PNG file. You can try it with the attached URL. I pass the image as `multipart/form-data` as content type. 
[Png Image](https://www.gstatic.com/webp/gallery3/3.png)

**Comment by themcoo** [comment]
I understand, but are you sure `attachment` array content is exactly equal to the png file content? That's why I asked if you can dump this array to a file to compare with actual png file

**Comment by Manish082007** [comment]
@themcoo - I have same doubt that it is getting changed by Aws Api Gateway. It may need `image/png` content-type or I need to convert it to `image/png` content-type. 
Another doubt I have is skiasharp supports Debian 11 OS? 
I will dump png file content in few hours. 
Thanks for your reply

**Comment by Manish082007** [comment]
I am able to resolve this issue. The problem was Aws Api Gateway was converting base64 string. I just need to specify the `multipart-data` as binary type & re-deploy the API stage.
