### ISSUE TITLE
[BUG] SKImage.Encode quits the app without any exception or error

### ISSUE THREAD

**Issue by kedare** [mono/SkiaSharp#2328]
**Description**

I was trying to use SkiaSharp with some very simple code (draw a rectangle) and after investigation, it looks like somehow SkiaSharp exit the application when trying to call `SKImage.Encode()` without throwing any exception or giving any error message

**Code**

```csharp
using SkiaSharp;

namespace Kedare.NotifPrinter;

public static class ImageService
{
    private const int Width = 200;
    private const int Height = 120;
    
    static SKImage CreateBox()
    {
        var imageInfo = new SKImageInfo(Width, Height);
        using var surface = SKSurface.Create(imageInfo);
        var canvas = surface.Canvas;
        using var paint = new SKPaint();
        
        canvas.Clear(SKColors.White);
        
        paint.Color = SKColors.Black;
        paint.IsAntialias = true;
        paint.StrokeWidth = 3;
        paint.Style = SKPaintStyle.Stroke;

        var rectangle = new SKRoundRect(new SKRect(1, 1, Width-1, Height-1), 5);
                
        canvas.DrawRoundRect(rectangle, paint);

        using var image = surface.Snapshot();
        return image;
    }

    public static void SaveImage()
    {
        Console.WriteLine("Saving image");
        using var stream = File.OpenWrite("image.gif");
        Console.WriteLine(stream.Name);
        using var box = CreateBox();
        Console.WriteLine("CreateBox done");
        var encoded = box.Encode(SKEncodedImageFormat.Gif, quality: 95);
        Console.WriteLine("Encode done");
        encoded.SaveTo(stream);
        Console.WriteLine("SaveTo done");
        stream.Flush();
        stream.Close(); 
        Console.WriteLine("Done");
    }
}
```

**Expected Behavior**

I expect all the `Console.WriteLine` to be executed and the present

**Actual Behavior**
No file is created and the console output is the following
```
❯ dotnet run
Building...
Saving image
/Users/mpoussin/code/repositories/kedare/Kedare.NotifPrinter/image.gif
CreateBox done
```

**Basic Information**

- Version with issue:   2.88.3
- Last known good version:   None
- IDE:   Rider
- Platform Target Frameworks: 
  - macOS:   13.0

  
<details>
  <summary>Detailed IDE/OS information (click to expand)</summary>
  
```

dotnet --version
7.0.100

```
</details>

**Screenshots**

**Reproduction Link**

**Comment by themcoo** [comment]
There are 2 issues in your code:
1. You return disposed SKImage from CreateBox() method:
        using var image = surface.Snapshot();
You should remove using keyword and leave disposing to the consumer of this method.

2. Skia can only encode PNG, JPEG and WEBP images, gif can only be decoded.

**Comment by kedare** [comment]
Thank you very much, indeed it looks like that was this issue, I'm not very familiar with the using statement yet.

It's working now, thank you again :)
