### ISSUE TITLE
[FEATURE] Please wrap SkImage::makeRawShader (milestone 98)

### ISSUE THREAD

**Issue by Costigan** [mono/SkiaSharp#2338]
**Is your feature request related to a problem? Please describe.**

Custom shaders are extremely useful in some situations but are hampered by the inability to supply large amounts of non-image data to them.  (My specific use case is using a shader to tweak raster map data as its rendered with the rest of skiasharp drawing text and vectors on top of the map.)  SkImage::makeRawShader is Skia's mechanism for doing this by disabling color processing and 

**Describe the solution you'd like**

I'm hoping SkiaSharp will move ahead to milestone 98, which provides this new public API.

I'm also hoping that a description of the SkiaSharp's approach to keeping up with versions of the underlying Skia library would be added to the wiki along with roadmap or timetable that indicates when/if updates to later milestones might occur.

**Describe alternatives you've considered**

I'm grateful that custom shaders are supported, and it may be possible to implement some of my use cases using the existing features for processing textures by encoding data as colored pixels but not all of them.  I'm trying to figure out how to do that, currently.

**Additional context**

n/a

**Comment by bmitc** [comment]
> I'm also hoping that a description of the SkiaSharp's approach to keeping up with versions of the underlying Skia library would be added to the wiki along with roadmap or timetable that indicates when/if updates to later milestones might occur.

I don't think there is an approach. The current milestone supported by `SkiaSharp` is 88, which, as far as I can tell, is over two years old now.
