### ISSUE TITLE
Encode multiple SKBitmap objects as a GIF

### ISSUE THREAD

**Issue by TypicalFooBar** [mono/SkiaSharp#237]
Hello.

Is there a way to encode a bunch of SKBitmap objects as a GIF? Alternatively, is it possible to make a GIF out of a directory full of PNG files on disk using this library? It is possible I am just missing something online and maybe you can point me in the right direction.

As an aside - I have been using this library for the last few days with .net core and I have to say that it is extremely awesome! I've worked with the Skia in C++ as well, but these C# bindings truly save me a lot of time and are so simple to use. Thanks! :)

**Comment by mattleibow** [comment]
Right now, I don't think you can. I had a look and they even stopped using giflib, and are using a custom gif decoder.
You could try any .NET-based gif libraries out there.

I asked a question on the forums which may be interesting: https://groups.google.com/forum/#!topic/skia-discuss/R99fiu-tYNU

**Comment by TypicalFooBar** [comment]
Okay, well thank you so much for the help! :)
