### ISSUE TITLE
[QUESTION] Can SkiaSharp draw to an OpenGL buffer?

### ISSUE THREAD

**Issue by sirgru** [mono/SkiaSharp#2370]
Can SkiaSharp draw to an OpenGL buffer created from .NET? It seems that it can, if the surface is constructed using the correct SKSurface.Create method. However, there are many overloads, and this process is not very straightforward. It would be useful to clarify which API to use. Additionally, a sample project in the samples directory using an easy library such OpenTK would be helpful to demonstrate the capability.

**Comment by RedyG** [comment]
I agree. Here's a sample project that uses OpenTK: https://github.com/NogginBops/ImGui.NET_OpenTK_Sample

**Comment by sirgru** [comment]
Thanks, in the meantime I found another example which demonstrates the capability. Closing the issue.
