### ISSUE TITLE
When will the latest code be pull from google/skia? 

### ISSUE THREAD

**Issue by Dogwei** [mono/SkiaSharp#2371]
Now I can't deserialize SKPicture from skp file generated by my current version of chrome browser, but old version of chrome browser can.

![image](https://user-images.githubusercontent.com/14845492/216240149-db8e8dfa-7721-47c9-8134-8826ec0ce495.png)

The attached files is the skp files generated by my current version browser and the old version browser.

[7c16dc73eb214d11afc63617970ebcde.zip](https://github.com/mono/SkiaSharp/files/10565177/7c16dc73eb214d11afc63617970ebcde.zip)

**Comment by mattleibow** [comment]
Duplicate of #2543
