### ISSUE TITLE
[BUG] Unable to load shared library 'libSkiaSharp' or one of its dependencies on M1 Mac

### ISSUE THREAD

**Issue by michaelhahn-doka** [mono/SkiaSharp#2379]
**Description**

Using SkiaSharp on a M1 Max MacBook Pro is not possible because the runtime isn't able to load the shared library 'libSkiaSharp'.

**Code**

```csharp
using var sourceBitmap = SKBitmap.Decode(imageStream);
```

**Expected Behavior**

Using SkiaSharp on the M1 Mac works as expected without throwing that error.

**Actual Behavior**

A TypeInitializationException is thrown because the libSkiaSharp.dylib isn't found, probably because it isn't copied to the bin/debug/net6.0/runtimes

System.DllNotFoundException: Unable to load shared library 'libSkiaSharp' or one of its dependencies. In order to help diagnose loading problems, consider setting the DYLD_PRINT_LIBRARIES environment variable: dlopen(liblibSkiaSharp, 0x0001): tried: 'liblibSkiaSharp' (no such file), '/System/Volumes/Preboot/Cryptexes/OSliblibSkiaSharp' (no such file), '/usr/lib/liblibSkiaSharp' (no such file, not in dyld cache), 'liblibSkiaSharp' (no such file), '/usr/local/lib/liblibSkiaSharp' (no such file), '/usr/lib/liblibSkiaSharp' (no such file, not in dyld cache)
   at SkiaSharp.SkiaApi.sk_managedstream_set_procs(SKManagedStreamDelegates procs)
   at SkiaSharp.SKAbstractManagedStream..cctor()

The type initializer for 'SkiaSharp.SKAbstractManagedStream' threw an exception.
 ---> System.DllNotFoundException: Unable to load shared library 'libSkiaSharp' or one of its dependencies. In order to help diagnose loading problems, consider setting the DYLD_PRINT_LIBRARIES environment variable: dlopen(liblibSkiaSharp, 0x0001): tried: 'liblibSkiaSharp' (no such file), '/System/Volumes/Preboot/Cryptexes/OSliblibSkiaSharp' (no such file), '/usr/lib/liblibSkiaSharp' (no such file, not in dyld cache), 'liblibSkiaSharp' (no such file), '/usr/local/lib/liblibSkiaSharp' (no such file), '/usr/lib/liblibSkiaSharp' (no such file, not in dyld cache)
   at SkiaSharp.SkiaApi.sk_managedstream_set_procs(SKManagedStreamDelegates procs)
   at SkiaSharp.SKAbstractManagedStream..cctor()
   --- End of inner exception stack trace ---
   at SkiaSharp.SKAbstractManagedStream..ctor(Boolean owns)
   at SkiaSharp.SKManagedStream..ctor(Stream managedStream, Boolean disposeManagedStream)
   at SkiaSharp.SKCodec.WrapManagedStream(Stream stream)
   at SkiaSharp.SKCodec.Create(Stream stream, SKCodecResult& result)
   at SkiaSharp.SKCodec.Create(Stream stream)
   at SkiaSharp.SKBitmap.Decode(Stream stream)

**Basic Information**

- Version with issue: 2.88.3
- Last known good version:  N/A
- IDE:  JetBrains Rider
- Platform Target Frameworks: 
  - macOS: latest
  - dotnet: 6
- Target Devices: MacBook Pro M1 Max

**Comment by Rudazzle** [comment]
If you manually copy the 'libSkiaSharp' dependency does it work?  I ask because I'm having a similar issue via a Linux deployment but the library is copied there.  However, I'm still getting an error that it was unable to load.

**Comment by michaelhahn-doka** [comment]
@Rudazzle The question is where exactly I have to copy the dependency to?

**Comment by Rudazzle** [comment]
@michaelhahn-doka you can try copying it to the root directory where your application is running.  You shouldn't have to do that as the Runtime directory structure should pick up the appropriate DLL.

**Comment by carolzbnbr** [comment]
Having the same issue here on same machine (Architecture)
Where does the  libSkiaSharp resides so I can find and copy it?

**Comment by mattleibow** [comment]
I just tested with .NET 7 and `net7.0-macos` and ARM64 seems to be working for me:

<img width="1393" alt="Screenshot 2023-06-18 at 8 20 40 PM" src="https://github.com/mono/SkiaSharp/assets/1096616/fd0f3f7e-27a0-4d26-b8d9-134ba94c073a">

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net7.0-macos</TargetFramework>
    <OutputType>Exe</OutputType>
    <Nullable>enable</Nullable>
    <ImplicitUsings>true</ImplicitUsings>
    <SupportedOSPlatformVersion>10.14</SupportedOSPlatformVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="SkiaSharp.Views" Version="2.88.3" />
  </ItemGroup>

</Project>
```

**Comment by mattleibow** [comment]
Duplicate of https://github.com/mono/SkiaSharp/issues/2307
