### ISSUE TITLE
[QUESTION] SkiaSharp WASM - SKCanvasView vs SKGLView - fill colors with alpha render differently

### ISSUE THREAD

**Issue by darenm** [mono/SkiaSharp#2381]
In experimenting with rendering a semi-transparent fill over the top of content, I see markedly different results when using the SKCanvasView vs the SKGLView. 

In the following image, the top two squares are rendered on an SKCanvasView, the bottom two squares are rendered on the SKGLView.

![image](https://user-images.githubusercontent.com/1674843/218372651-0379811e-0339-4900-ae09-e6b94ba470cd.png)

The color for both of the semi-transparent squares is `SKColor(255, 255, 0, 128)`. Why is there such a difference and am I missing a configuration step? It appears the first is being rendered as if it was on top of a black background, whereas the second is being rendered as if over a white background,

The following is the Blazor WebAssembly view:
```csharp
@page "/"
@using SkiaSharp
@using SkiaSharp.Views.Blazor

<PageTitle>Index</PageTitle>

<SKCanvasView OnPaintSurface="@OnPaintSurface" style="width:1000px;height:500;" />
<SKGLView OnPaintSurface="@OnPaintSurface" style="width:1000px;height:500;" />

@code {
    protected override Task OnInitializedAsync()
    {
        return base.OnInitializedAsync();
    }

    private void OnPaintSurface(SKPaintSurfaceEventArgs e)
    {
        // SKCanvasView seems to use black as the basis for transparency

        var canvas = e.Surface.Canvas;
        canvas.Clear();
        canvas.DrawRect(400, 0, 300, 300, new SKPaint() { Color = new SKColor(255, 0, 0, 255) });     
        canvas.DrawRect(50, 50, 300, 300, new SKPaint() { Color = new SKColor(255, 255, 0, 128) });
    }

    private void OnPaintSurface(SKPaintGLSurfaceEventArgs e)
    {
        // SKGLView seems to use white as the basis ofr the transparency 

        var canvas = e.Surface.Canvas;
        canvas.Clear();
        canvas.DrawRect(400, 0, 300, 300, new SKPaint() { Color = new SKColor(255, 0, 0, 255) });
        canvas.DrawRect(50, 50, 300, 300, new SKPaint() { Color = new SKColor(255, 255, 0, 128) });
    }
}
```

I am using SkiaSharp in an Uno WebAssembly project and I am seeing the same results with the `SKXamlCanvas`.

**Comment by darenm** [comment]
@mattleibow Hi there - can you give me any insight regarding this question?  Am I missing a configuration setting? Thanks.

**Comment by cwhitlatch** [comment]
Has there been any progress on this issue?

**Comment by darenm** [comment]
Looks like this is addressed in the latest release.
