### ISSUE TITLE
[QUESTION] Are there plans to support .Net 7?

### ISSUE THREAD

**Issue by cake-escape** [mono/SkiaSharp#2399]
Apologies if this has been asked elsewhere. 

I noticed that SkiaSharp currently only lists support up to .Net 6. Were there any plans to add .Net7 support (and beyond)?

My main reason for asking is that we in the process of migrating away from `System.Drawing.Common` and want to identify the most suitable replacement. We are currently thinking SkiaSharp, but wanted to confirm current future plans for the project.

We also noticed that `MAUI.Graphics` is being pushed quite heavily at the moment in certain spheres. Is there any intention for that project to eventually supersede this one?

Thank you for all the hard work maintaining this repo.

**Comment by mattleibow** [comment]
This issue has a few things, so I will go through them:

* The list of support is more a minimum, so basically .NET 6 and later - including 7, 8, and 9
* Support for SkiaSharp will still go on as it is used by platforms that do not have a native graphics engine or as an alternative - Tizen and the GPU accelerated on desktop
* Maui.Graphics is an alternative implementation that sits above SkiaSharp. Some platforms have their own graphics engine (eg iOS and Android) so Maui.Graphics is the recommended way to use if you are building graphics things. On iOS, it will use CoreGraphics, Android will use Android Graphics, Windows it will use Win2D and on Tizen it will SkiaSharp. But! It also supports you swapping out the graphics engine so if you WANT to use SkiaSharp on Android, then you can swap out the Maui.Graphics backend without having to rewrite your code.

**Comment by charlesroddie** [comment]
Maui.Graphics has a LOGO inspired, imperative API (MOVE HERE, SET THIS PAINT, DRAW) whereas SkiaSharp has a higher-level structure (DRAW(HERE, THIS PAINT)). Not sure about this exact example but certainly things are more global and imperative in Maui.Graphics. That makes it hard to use Maui.Graphics for large scale projects. We investigated it for potential deployment-size savings but did not find it usable.

Avalonia is dependent on SkiaSharp, as is Uno, and it deploys on the web via either blazor or NativeAOT. We are moving all of our UI graphics to SkiaSharp (migrating from Xamarin.Forms to drawn controls), and we are not the only ones to be doing this. In other words 100% of the non-buggy dotnet cross-platform UI frameworks out there are SkiaSharp drawn! If you do a GitHub issues search, you will find many projects are adopting SkiaSharp as a way to go cross-platform.

The state of the repo is unfortunate (it doesn't build and it's not clear who the maintainers are now that @mattleibow is involved in MAUI or even who has the rights to decide who the maintainers are or which group to discuss that with). But the projects involving SkiaSharp are so large and essential to dotnet that in my opinion this is bound to be resolved in the near future, and the current nuget packages are good enough to work well in the interim.
