### ISSUE TITLE
On-screen rendering and ganesh backend support

### ISSUE THREAD

**Issue by kekekeks** [mono/SkiaSharp#24]
Do you plan to add hardware acceleration support? I have some native code for win/linux/ios/android that we use in Perspex for hw-accelerated drawing using Skia. For Windows it will add dependency on [ANGLE](https://github.com/google/angle), but performance improvements are worth of adding such dependency.

**Comment by kekekeks** [comment]
Since opengl-related calls are too platform-dependent and complex for a user it's better to keep Garesh backend initialization and surface-flipping in the native lib. I also can see that currently your bindings don't have built-in on-screen rendering support and you leave the task of blitting image to screen to the user.

In [Perspex](https://github.com/Perspex/Perspex) we have a concept of a render target that allows to create a [rendering session](https://github.com/Perspex/Perspex/blob/master/src/Perspex.SceneGraph/Media/IDrawingContext.cs) which, when disposed, is flipped back to screen. It may be worth to do the same.

```csharp
interface IRenderTarget
{
     IRenderingContext CreateContext();
}


interface IRenderingContext : IDisposable
{
      SkCanvas Canvas { get; }
}

```

To end user it will look like this:

```csharp
var target = new OSWindowRenderTarget(hWnd/xid/nswindow);
...

using(var ctx = target.CreateContext())
{
     ctx.Canvas.DrawRectangle(...);
}

```

That render target will manage everything required to initialize ganesh-backend using ANGLE/EGL/GLX/AGLX/whatever or fall back to sw rendering.


Currently I have some code for that in Perspex

https://github.com/Perspex/libperspesk/blob/master/src/gl.cpp - EGL/ANGLE hw-accel (Win/Linux/Android)
https://github.com/Perspex/libperspesk/blob/master/src/win32.cpp - win32 window (SetDIBitsToDevice)
https://github.com/Perspex/libperspesk/blob/master/src/linux.cpp - X11 (XPutImage)
https://github.com/Perspex/libperspesk/blob/master/src/pview.mm - iOS using GLKView

**Comment by mattleibow** [comment]
@kekekeks I will be looking into this soon. I have got most of the GPU bits building for all platforms right now. The next step is to get ANGLE for Windows added, then wrap all the necessary types. 

As the GPU bits are building already, initial wrapper can be created for OpenGL right now, except the UWP will have to wait for ANGLE. Win32 can have initial GL support until ANGLE arrives - giving it more options for devs.

**Comment by mattleibow** [comment]
@kekekeks Hardware support is here (-ish)
I have started with getting all the bits together and I think it is working quite well. Right now All the platforms should have OpenGL support (DirectX is coming in a few). This means all the platforms, except UWP, can draw with hardware acceleration.

The global issue for hardware / GPU is here: https://github.com/mono/SkiaSharp/issues/138
Please leave comments and suggestions so we can get the best product out.

There is also a preview NuGet: https://www.nuget.org/packages/SkiaSharp/1.53.2-gpu1
Please try that out and be sure to comment on how it went - if there are any features needed, just let us know!
