### ISSUE TITLE
[QUESTION] why picture will lose color?

### ISSUE THREAD

**Issue by 3egirlsdream** [mono/SkiaSharp#2422]
- this is my code, is any place can set color config?
- saved picture will become lighter，why?
````
var _img = SKBitmap.Decode(selectedImagePath)
SKImage image = SKImage.FromBitmap(_img);
SKData data = image.Encode(SKEncodedImageFormat.Jpeg, 100);
var stream = data.AsStream(false);
using (FileStream rs = new FileStream(savePath, FileMode.Create, FileAccess.Write))
{
	data.SaveTo(rs);
}
````

**Comment by themcoo** [comment]
Washed away colors are usually related with color profiles. Can you post the original image?

**Comment by 3egirlsdream** [comment]
> Washed away colors are usually related with color profiles. Can you post the original image?

- this is zip path : http://cdn.thankful.top/images.zip    
- smaller is original image

**Comment by themcoo** [comment]
So indeed the file you provided contains Adobe RGB color space profile. And apparently using SKBitmap omits the color space embedded in file.
If you use SKImage to load the file the ColorSpace property is populated and skia color management works. You can either re-save the file using the same color profile or convert to a common sRGB one:

```

	using var img = SKImage.FromEncodedData("DSC04207.jpg");

// -- conversion to sRGB using intermediate surface
	using var surf = SKSurface.Create(new SKImageInfo(img.Width, img.Height, img.ColorType, img.AlphaType, SKColorSpace.CreateSrgb()));

	surf.Canvas.DrawImage(img, 0,0);
	
	using var drawn = surf.Snapshot();
	using var encoded = drawn.Encode(SKEncodedImageFormat.Jpeg, 100);
// -- end of conversion

// encoding the image directly will preserve original color space:
	//using var encoded = img.Encode(SKEncodedImageFormat.Jpeg, 100);

	using var file = File.Create("saved_DSC04207.jpg");
	encoded.SaveTo(file);
```

**Comment by 3egirlsdream** [comment]
thank you
