### ISSUE TITLE
[BUG] Missing upstream repo: https://skia.googlesource.com/common.git

### ISSUE THREAD

**Issue by alucryd** [mono/SkiaSharp#2427]
**Description**

Trying to build 2.88.3, the git-sync-deps runs into an error, it seems an upstream repo no longer exists: https://skia.googlesource.com/common.git. I'm not sure whether it's important or not since the build succeeds, but we have issues using the managed skia component with the resulting library.

**Code**

N/A

**Expected Behavior**

The DEPS file should list an existing repository.

**Actual Behavior**

The DEPS file contains a phantom repository.

**Basic Information**

- Version with issue:  2.88.3
- Last known good version:  2.80.2

**Screenshots**

N/A

**Reproduction Link**

N/A

**Comment by mattleibow** [comment]
Lol 

![image](https://github.com/mono/SkiaSharp/assets/1096616/d0e3698b-0b73-4d78-a9fd-2c9613870227)
