### ISSUE TITLE
[BUG] .NET 7 MAUI iOS DllNotFoundException: @rpath/libSkiaSharp.framework/libSkiaSharp

### ISSUE THREAD

**Issue by denhaandrei** [mono/SkiaSharp#2437]
**Description**
Instal SkiaSharp using Nuget package manager:
```PackageReference Include="SkiaSharp" Version="2.88.3"```

.NET 7 MAUI Android:
Works fine

.NET 7 MAUI IOS:
System.TypeInitializationException: The type initializer for 'SkiaSharp.SKAbstractManagedStream' threw an exception.
 ---> System.DllNotFoundException: @rpath/libSkiaSharp.framework/libSkiaSharp
   at SkiaSharp.SKAbstractManagedStream..cctor()
   --- End of inner exception stack trace ---
   at SkiaSharp.SKManagedStream..ctor(Stream managedStream, Boolean disposeManagedStream)
   at SkiaSharp.SKCodec.WrapManagedStream(Stream stream)
   at SkiaSharp.SKCodec.Create(Stream stream, SKCodecResult& result)
   at SkiaSharp.SKCodec.Create(Stream stream)
   at SkiaSharp.SKBitmap.Decode(Stream stream)
   at HHS.MemberZone.UserControl.UploadFilesView.SaveCompressImageToStorage(FileResult file) 

**Code**
```
            FileResult photo = await MediaPicker.Default.PickPhotoAsync();
            using System.IO.Stream sourceStream = await photo.OpenReadAsync();
            using var originalBitmap = SKBitmap.Decode(sourceStream);
```
**Expected Behavior**
No Exception
**Actual Behavior**
Exception

**Basic Information**
- Version with issue:  2.88.3
- Last known good version: -
- IDE: 17.5.1
- Platform Target Frameworks: .NET 7 MAUI
  - iOS:  16.3.1
- Target Devices:   iPhone 11

**Comment by davefxy** [comment]
I am also seeing this exact problem. Same error code. App runs fine on the Android.
I am using VS Community 2022 (64-bit) Preview Version 17.6.0 Preview 5.0
SkiaSharp.Extended.UI.Maui  Version="2.0.0-preview.61"
The iOS device is an iPad running latest iOS : 16.4.1.

**Comment by heytherewill** [comment]
I stumbled upon this as well and it seems like the linker is stripping the framework away. Adding `<MtouchLink>None</MtouchLink>` is a simple way of making it go away, though for releasing you want to set an exception for the linker instead of not linking at all.

**Comment by Moro890** [comment]
If you're using a Windows machine and Hot Restart, this is the issue: https://github.com/Mapsui/Mapsui/issues/1872
