### ISSUE TITLE
Use static version of C runtime for Windows builds

### ISSUE THREAD

**Issue by kekekeks** [mono/SkiaSharp#244]
Visual Studio 2015 C++ Redistributable isn't always installed on the target machine. And you can't bundle it with self-contained app, so Skia# basically can't be used without admin rights.

**Comment by mattleibow** [comment]
@kekekeks This has been discussed a couple of times: https://github.com/mono/SkiaSharp/issues/109 and https://github.com/mono/SkiaSharp/issues/136 

I am closing this issue as a duplicate, but feel free to re-open https://github.com/mono/SkiaSharp/issues/136 if you can provide any insights or suggestions.
