### ISSUE TITLE
[BUG] In Blazor, Dispose() of SkCanvasView throws NullReferenceException when parent component shows and hides multiple skia canvas views

### ISSUE THREAD

**Issue by jjzhang12** [mono/SkiaSharp#2441]
**Description**

In Blazor, Dispose() of SkCanvasView throws exception when parent component shows and hides multiple skia canvas views

**Code**

**Expected Behavior**

No exception when the SkCanvasView is disposed

**Actual Behavior**

Exception in runtime:
blazor.webassembly.js:1 crit: Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: Object reference not set to an instance of an object.
System.NullReferenceException: Object reference not set to an instance of an object.
   at SkiaSharp.Views.Blazor.SKCanvasView.Dispose()
   at Microsoft.AspNetCore.Components.Rendering.ComponentState.TryDisposeInBatch(RenderBatchBuilder batchBuilder, Exception& exception)

**Basic Information**

- Version with issue:   2.88.3
- Last known good version:   n/a
- IDE:   VS 2022 17.5
- Platform Target Frameworks: 
  - Chrome / Edge
  
<details>
  <summary>Detailed IDE/OS information (click to expand)</summary>
  
```

PASTE ANY DETAILED VERSION INFO HERE

```
</details>

**Reproduction Link**

**Comment by RChrisCoble** [comment]
@mattleibow, is there any chance we can get this on your radar?  We are using SkiaSharp inside Blazor WASM and hit this issue easily.  Thanks.

CC: @danroth27

**Comment by RChrisCoble** [comment]
Thanks much @mattleibow!  Are we able to get a build of the repo which contains this fix?  

CC: @danroth27

**Comment by mattleibow** [comment]
You can get the 2.88.4-preview builds from https://aka.ms/skiasharp-eap/index.json

I am just merging a few more arm64 and some small fixes then will push out a new version. But since the last release was almost a year ago, I would suggest giving the preview a try to make sure there are no other issues. CI should be the same, but Xcode and .NET SDKs have been updated.

**Comment by sofkhene** [comment]
@mattleibow hi how can i do this? i need this fix for my project BLAZOR 2.88.3

**Comment by jjzhang12** [comment]
@mattleibow : did a preliminary testing on 2.88.4-preview.66 & 71, they are working fine for us.
