### ISSUE TITLE
[BUG] Newer build for emsdk 3.1.30+ needed for .net 8

### ISSUE THREAD

**Issue by radical** [mono/SkiaSharp#2447]
**Description**
.net8 previews use emscripten 3.1.34 . A newer build of the library is needed to work with that.

related: https://github.com/dotnet/runtime/issues/82725
cc @radekdoulik

**Comment by mattleibow** [comment]
Fixed in https://github.com/mono/SkiaSharp/pull/2457
Super fixed in https://github.com/mono/SkiaSharp/pull/2495
