### ISSUE TITLE
How to automatically include "libSkiaSharp.dll" when publishing a "Self-contained" console application?

### ISSUE THREAD

**Issue by UweKeim** [mono/SkiaSharp#2451]
Having a .NET 7 Console application that runs on Windows, I publish it in Visual Studio 2022 as "Deployment mode: Self-contained".

While this produces a large single executable (as expected), the executable fails to run as soon as accessing SkiaSharp functions:

> The type initializer for 'SkiaSharp.SKImageInfo' threw an exception.        
> System.TypeInitializationException: The type initializer for 'SkiaSharp.SKImageInfo' threw an exception. The type initializer for 'SkiaSharp.SKImageInfo' threw an exception.    at SkiaSharp.SKBitmap..ctor(Int32 width, Int32 height, Boolean isOpaque)
> Dll was not found.    at SkiaSharp.SkiaApi.sk_colortype_get_default_8888()        
>    at SkiaSharp.SKImageInfo..cctor()           
>    at SkiaSharp.SKBitmap..ctor(Int32 width, Int32 height, Boolean isOpaque)

If I not only ship my executable but also the file "**libSkiaSharp.dll**", the error goes away and my application runs as expected.

Since I explicitly configured my publish in Visual Studio to produce a single executable, I do not want to ship an additional DLL file.

### My question

Is there any way to tell the build/publish system to also include "libSkiaSharp.dll" in the single-executable assembly?

**Comment by Webreaper** [comment]
Have you tried the `IncludeNativeLibrariesForSelfExtract` option? 

https://learn.microsoft.com/en-us/dotnet/core/deploying/single-file/overview?tabs=cli#native-libraries

**Comment by UweKeim** [comment]
Awesome, that did the trick, thank you very much, @Webreaper!

For anyone coming here, you have to add `IncludeNativeLibrariesForSelfExtract` to your CSPROJ file, inside a `PropertyGroup`, e.g.:

```xml
<PropertyGroup>
    <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract> 
</PropertyGroup>
```
