### ISSUE TITLE
adding SkiaSharp.Views.Uno Nuget package to a Uno Platform app

### ISSUE THREAD

**Issue by proficad** [mono/SkiaSharp#2459]
VisualStudio 2022 on Windows 11
I am trying to add the SkiaSharp.Views.Uno Nuget package to a Uno project and getting errors like:
Severity	Code	Description	Project	File	Line	Suppression State
Error	NU1603	Warning As Error: Uno.UI 4.0.8 depends on Xamarin.AndroidX.AppCompat (>= 1.2.0.7-net6preview02.4535000) but Xamarin.AndroidX.AppCompat 1.2.0.7-net6preview02.4535000 was not found. An approximate best match of Xamarin.AndroidX.AppCompat 1.2.0.7 was resolved.	UnoApp3	D:\projects\pokusy\UnoApp3\UnoApp3\UnoApp3\UnoApp3.csproj	1	

Does that mean I have to install Xamarin first?

**Comment by jeromelaban** [comment]
Thanks for the report.

It looks like you're trying to add SkiaSharp to an uno project that does not already have a Uno.* reference, or is using an Uno version older than 4.0. Which one is it?

**Comment by proficad** [comment]
I am using VS 17.7.2. Today I created a new UNO project. I did not write a single line of code.
When I tried to add nuget packages, I got the error message in the screenshot.[](url)
![uno-nuget](https://github.com/mono/SkiaSharp/assets/1932632/eaa4a186-bc02-4cd5-912b-4195802d8dcd)

**Comment by jeromelaban** [comment]
Thanks for the update! Looks like there's a bug in VS that prevents it from showing the right error message... and the original error is https://github.com/unoplatform/uno.templates/issues/248. We'll fix it in uno, but you can fix this in two ways:
- Remove the two test projects for your testing
- Or add the following lines to the Directory.Packages.props:
   ```
	<PackageVersion Include="FluentAssertions" Version="6.12.0" />
	<PackageVersion Include="Microsoft.NET.Test.Sdk" Version="17.7.1" />
	<PackageVersion Include="coverlet.collector" Version="6.0.0" />
	<PackageVersion Include="NUnit" Version="3.13.3" />
	<PackageVersion Include="NUnit3TestAdapter" Version="4.5.0" />
  ```
  then do a restore.

**Comment by proficad** [comment]
Thank you that helped!
Could you please advise how to add a Skisharp view to the project?
I tried to add SkiaSharp.Views.Uno 2.88.5 nuget package
and the response is
Assets file has not changed. Skipping assets file writing. Path: D:\pokusy\UnoApp5\UnoApp5.Mobile\obj\project.assets.json

**Comment by jeromelaban** [comment]
Thanks for the update!

To use skiasharp, you can take a look at [this sample](https://github.com/unoplatform/Uno.Samples/tree/master/UI/SkiaSharpTest).

Uno Platform apps are now WinUI, so you'll need to add `SkiaSharp.Views.Uno.WinUI`.

**Comment by proficad** [comment]
Problem solved.
Thank you very much!

**Comment by jeromelaban** [comment]
Thanks! Feel free to close the issue.
