### ISSUE TITLE
[BUG] SKBitmap.GetPixels crashes in Release mode, unless called often

### ISSUE THREAD

**Issue by Vercidium** [mono/SkiaSharp#2462]
**Description**

Accessing data returned by `SKBitmap.GetPixels()` causes an `AccessViolationException`, unless it is called often. The image used in the example below is [available here](https://www.dropbox.com/s/u49yd6retbs6f3f/skybox.png?dl=0).

I am unable to reproduce this in Debug mode, only in Release mode (i.e. optimised .NET builds)

**Code**
This code returns how many unique colours are in an image. Removing the line starting with `var test =` causes the program to crash.

```cs
using SkiaSharp;

namespace SkiaCrash;

internal unsafe class Program
{
    static void Main(string[] args)
    {
        var bitmap = SKBitmap.Decode(File.OpenRead("skybox.png"));
        var skiaPtr = (uint*)bitmap.GetPixels();


        // Ensure there are 4 bytes per pixel
        if (bitmap.ColorType != SKColorType.Bgra8888)
            return;


        // Get every colour in the PNG
        var colours = new HashSet<uint>();

        var read = skiaPtr;
        var end = read + bitmap.Width * bitmap.Height;

        while (read < end)
        {
            // Remove this line to cause the crash
            var test = (uint*)bitmap.GetPixels();

            colours.Add(*read++);
        }


        // Use the result in some way so the compiler doesn't remove any code
        Console.WriteLine(colours.Count);
    }
}
```

**Expected Behavior**
The program does not crash

**Actual Behavior**
The program crashes with this exception:

```
An unhandled exception of type 'System.AccessViolationException' occurred in SkiaCrash.dll
Attempted to read or write protected memory. This is often an indication that other memory is corrupt.

The program '[31788] SkiaCrash.exe' has exited with code 4294967295 (0xffffffff).
```

**Basic Information**
- .NET version: 6.0
- Version with issue:  2.88.3
- Last known good version:  Unsure
- IDE:  Microsoft Visual Studio Community 2022 (64-bit) - Current - Version 17.4.3
- Platform Target Frameworks:
  - Windows Classic:  Windows 10

**Comment by dubiousconst282** [comment]
I think that the SKBitmap object is being freed by the GC while the unmanaged pointer is still being used, since there are no other references to it after the GetPixels() call.

Adding either an using block or accessing some property of the bitmap afterwards seems to fix the issue:

```diff
+        using var bitmap = SKBitmap.Decode(File.OpenRead("test.jpg"));
         ...
+        Console.WriteLine(bitmap.Count);
```

**Comment by Vercidium** [comment]
Changing from `var bitmap` to `using var bitmap` does fix it, thank you for the workaround!

**Comment by mattleibow** [comment]
Closing this issue as @dubiousconst282 is correct. The GC will collect the bitmap because there are no more references to it. Once you access the pixels as a pointer, there is no connection from that pointer to the bitmap.

I also think you could use the `GC.KeepAlive` if you did not want to dispose the bitmap - ie: you are some method that does not control the bitmap.
