### ISSUE TITLE
How to do image Cropping with movable cropping Box in canvas paint Surface?

### ISSUE THREAD

**Issue by RasikaTandel** [mono/SkiaSharp#247]
In XAML SkCanvas View allow Gesture Recognizer but how to add gesture recognizer on layer(draw in same canvas surface)  which is under the SkCanvas view

**Comment by mattleibow** [comment]
This may be more of an issue for Xamarin.Forms, but I don't think that is easily possible. Because the canvas is intercepting the touch events, the views below won't receive them.

Is it possible to move the view that should be receiving the events above the canvas?
