### ISSUE TITLE
DllNotFoundException for libHarfBuzzSharp in Blazor WebAssembly

### ISSUE THREAD

**Issue by pauldendulk** [mono/SkiaSharp#2473]
**Description**

DllNotFoundException for libHarfBuzzSharp in Blazor WebAssembly when rendering a text using Topten.RichTextKit in a project referencing SkiaSharp, HarfBuzzSharp, Topten.RichTextKit and HarfBuzzSharp.NativeAssets.WebAssembly.

**Code**

It crashes on the first call that depends on libharfBuzzSharp. In our case this is
` Topten.RichTextKit.TextBlock.Update()`

**Expected Behavior**

I expect libHarfBuzzSharp to be deployed. I guess the responsible nuget package should be HarfBuzzSharp.NativeAssets.WebAssembly. 

**Actual Behavior**

Crashing with DllNotFoundException and "libHarfBuzzSharp" as message.

**Basic Information**

- We are working with Blazor WebAssembly
- This problem always existed as far as we know
- We work with the latest versions on the date of this posting:
  - SkiaSharp 2.88.3
  - HarfBuzzSharp 2.8.2.3
  - Topten.RichTextKit 0.4.165,
  - HarfBuzzSharp.NativeAssets.WebAssembly 2.8.2.3

**Reproduce**
Clone the [Mapsui project](https://github.com/Mapsui/Mapsui) and run Mapsui.Sample.Blazor with the line referencing libHarfBuzzSharp.a removed from the csproj. The select category 'tests' and then 'callouts'. It will not show callouts. 

**Screenshots**

![image](https://github.com/mono/SkiaSharp/assets/963462/ca3e5f3f-baa9-4bce-a267-e03dce9f3faa)

**Workaround**

We got this to work for our sample project using this solution by @Gillibald https://github.com/mono/SkiaSharp/issues/1725#issuecomment-978843629. We applied this in this PR:  https://github.com/Mapsui/Mapsui/pull/2015

The solution proposed in the [last comment](https://github.com/mono/SkiaSharp/issues/1725#issuecomment-988044531) in that thread did not work for Blazor but it did work for Uno WebAssembly (where we had the same problem).

**Why is this important**

Although we got this working for our sample project our users will run into this same problem as soon as they want to show a popup. If they manage to fix this it will be because of a remark on a closed thread that is about a different topic.

**Comment by mattleibow** [comment]
Fixed in https://github.com/mono/SkiaSharp/pull/2497

**Comment by inforithmics** [comment]
I fixed it with a pull request in mapsui 
https://github.com/Mapsui/Mapsui/pull/2103

for really fixing it 
`SkiaSharp.Views.Blazor.Local.props
`
Needs to include the `$(HarfBuzzSharpStaticLibraryPath)` libraries because currently only the $(SkiaSharpStaticLibraryPath) are included, that's whey graphics work but not text. (needs harfbuzz sharp).
