### ISSUE TITLE
[non-issue] SKGLView does not draw anything on Windows 10 hacked onto a Lumia 820

### ISSUE THREAD

**Issue by bugadani** [mono/SkiaSharp#249]
I have a Lumia 820 that has Windows 10 build 15031. The code that works well on a Lumia 950XL does not draw anything on the hacked phone. I realize that this is a non-issue but it still would be nice if I could use my old phone as a low-end developer device. Is there anything that can be done in SkiaSharp?

Canvas size and other stuff look normal in debugger, SKCanvasView works just fine.

**Comment by mattleibow** [comment]
This is most probably the same things as #207.
The issue is probably with the way I am setting up the GLES context. This is not my strong area, so I have been pushing pack on that for a bit.

I will get it fixed, and hopefully soon. Any PRs or fixes are totally welcome.
