### ISSUE TITLE
[BUG] Custom shader in SKCanvasView crashes .NET MAUI App

### ISSUE THREAD

**Issue by LFLumirithmic** [mono/SkiaSharp#2496]
I am building a .NET MAUI app that's designed to run on iOS, specifically on an iPad Pro. In it I need to be be able to sample sections of an image based on a number of parameters and display that on screen, so I thought the best way to do that would be through a shader and the SkiaSharp SKRuntimeEffect and SKShader classes seemed like a good way to do it. I made a custom control that inherits from SKCanvasView and wrote an SkSL shader. However, whenever the code reaches the DrawRect() call in the OnPaintSurface method of the class, the app crashes immediately.

I have made a bare bones app that has only a custom control that inherits from SKCanvasView with a trivial shader that just sets each pixel colour to red and the crash still happens, which can be found here: https://github.com/LFLumirithmic/SkiaShaderTest

The most relevant part of the code is this section in the OnSurfacePaint method:

```
var src = @"
    float4 main(float2 fragCoord) {
        return float4(1,0,0,1);
    }";
using var effect = SKRuntimeEffect.Create(src, out string error);
using var shader = effect.ToShader(true);

using (SKPaint paint = new SKPaint() { Shader = shader })
{
    try
    {
        canvas.DrawRect(info.Rect, paint);
    }
    catch (Exception e)
    {
        Debug.WriteLine($"Exception {e.GetType()}: {e.Message}");
    }
}
```

The call to canvas.DrawRect() instantly crashes the app. I ran it on an iPad Pro and in an iPad simulator, where it crashes with no exception thrown and no console output provided. I ran it on the Mac Mini used to build to the iPads and there it crashes without throwing an exception, but gives me the following output: https://github.com/LFLumirithmic/SkiaShaderTest/blob/main/mac-console-output.rtf

I also ran it on a Windows 11 laptop, where it crashes in the same place, but throws the following exception:

```
System.Runtime.InteropServices.SEHException
  HResult=0x80004005
  Message=External component has thrown an exception.
  Source=<Cannot evaluate the exception source>
  StackTrace:
<Cannot evaluate the exception stack trace>
```

If I create one of the default shader effects as an SKShader object using the provided C# API, e.g.:

```
using (SKPaint paint = new SKPaint())
{
    SKShader shader = SKShader.CreateLinearGradient(
        new SKPoint(0, 0),
        new SKPoint(1000, 1000),
        new SKColor[]
        {
            new SKColor(0,0,255),
            new SKColor(0,255,0)
         },
         null,
         SKShaderTileMode.Repeat
     );
     paint.Shader = shader;
     canvas.DrawRect(info.Rect, paint);
}
```

That works perfectly. But even the trivial custom shader shown above doesn't work.

I am using version 2.88.3 of SkiaSharp inside Visual Studio through the NuGet package manager, which is the latest as far as I can tell.

I see that issue #2230 mentions the same problem, but it's phrased as a feature request suggesting a specific solution, so I figured I would open this as a broader question.

Am I doing something wrong here and, if so, what? Or is this an issue in SkiaSharp with .NET MAUI? In a few other issues, I've seen mentions of SKSL not being able to run on CPU in the current version of SkiaSharp, but I want it to run on GPU. Is there some sort of flag or setting or registration step I'm missing?

**Comment by mattleibow** [comment]
As of today, `SKRuntimeEffect` is not supported on a raster/bitmap canvas and only on the GPU.

**Comment by ggolda** [comment]
@mattleibow do you have plans to add support in near future? Or it's out of the scope currently?

**Comment by mattleibow** [comment]
You should be able to run shaders with a GPU view, but I have not yet ported them over to Maui as the new versions of the various platforms seem to have dropped OpenGL support. Adding the new versions will probably only happen once I finish the update of the skia native library.
