### ISSUE TITLE
.NET conform xml documentation file for SkiaSharp.dll

### ISSUE THREAD

**Issue by tebjan** [mono/SkiaSharp#25]
It would be great to have such a file to get help texts in the IDE when working with the SkiaSharp.dll.

I was not able to find such a file in the nuget distribution. Can i find it somewhere else? If not, is it planned?

**Comment by mattleibow** [comment]
It is planned. I should be there in the next release

**Comment by tebjan** [comment]
That's good news, thx. Looking forward to it...

**Comment by bholmes** [comment]
I believe this is is the latest NuGet.
