### ISSUE TITLE
How does one trigger a repaint for the SKGLView in Blazor WASM?

### ISSUE THREAD

**Issue by Webreaper** [mono/SkiaSharp#2523]
I have an async image load and want to render/paint it when the load completes, but it's unclear as to how to manually trigger a repaint to happen. Is there an example of how to do this? 

I can turn on `EnableRenderLoop=true` but that then means I'm burning CPU with constant repainting, which seems a waste. For now I have something like this: 

```
private void OnPaintSurface(SKPaintGLSurfaceEventArgs e)
    {
        if (changeNeeded == false)
            return;

        changeNeeded = false;
 
        // Do the actual painting onto the canvas here
```
which means that my paint method does nothing if I haven't made any changes. When I'm ready to paint a change I set it up and then set `changeNeeded = true`. It works, but feels like a hack. 

I thought `StateHasChanged` in the control might trigger a repaint, but it doesn't appear to do so.

**Comment by ojb500** [comment]
`Invalidate` is the method you seek

**Comment by Webreaper** [comment]
Of course. Thank you!
