### ISSUE TITLE
[BUG] SKBitmap.CopyTo leaking memory?

### ISSUE THREAD

**Issue by omatrot** [mono/SkiaSharp#2527]
**Description**

I have the following code in a Xamarin.iOS application that appears to leak memory according to the Profiler:

```
        public void Render(SKCanvas canvas, float x, float y, float width, float height)
        {
            if (this.disposed)
            {
                throw new ObjectDisposedException(nameof(SmartButton));
            }

            this.SetRenderArea(x, y, width, height);
            if (this.IsEmpty)
            {
                return;
            }

            using (SKBitmap renderedBitmap = this.RenderButton(this.bitmap.Copy()))
            {
                // Rendered button is a shadow bitmap buffer to allow overloading.
                canvas.DrawBitmap(renderedBitmap, new SKRect(this.x, this.y, this.x + this.width, this.y + this.height), SmartButton.HighQualiyPaint);
            }
        }
```

**Expected Behavior**

I expect that SBBitmaps are not leaked because there should be no remaining reference in my code.

**Basic Information**

- Version with issue:  SkiaSharp.Views.Forms 2.88.3
- Last known good version:  NA
- IDE:  Visual Studio for Mac
- Platform Target Frameworks:
  - iOS:  16
- Target Devices:   all devices supporting iOS 16.

Here is the profiler results on an iPhone 6S: There are more than 76100 SKBitamp objects in memory.

<img width="1083" alt="Screenshot 2023-07-18 at 16 50 12" src="https://github.com/mono/SkiaSharp/assets/4366356/4df3c52a-024b-4e17-b532-3b1a0cf826fd">

Any help appreciated.

**Comment by TommiGustafsson-HMP** [comment]
There's no full code to be seen, but do you dispose `this.bitmap.Copy()` at some point?

**Comment by omatrot** [comment]
In this case, RenderButton is simply returning the copy, so it is supposed to be disposed after the call to DrawBitmap. Is DrawBitamp keeping a reference to the bitmap?
