### ISSUE TITLE
View Renderer PointerPressed Event issue

### ISSUE THREAD

**Issue by RasikaTandel** [mono/SkiaSharp#253]
In SKCanvasViewRenderers Event is not properly working on the Canvas draw surface.
I am doing a project using Custom renderer and  Draw rectangle on canvas Surface But Using SkCanvasViewRenderers  create a pointer pressed event  but this event is  not proper work on the Draw rectangle. some time event is not occur on press Action.

**Comment by mattleibow** [comment]
@RasikaTandel I see you closed this. Did you resolve your problem?
