### ISSUE TITLE
[BUG] SkiaSharp Managed-Only Building does not work, because there is a mix of .NET 7 and .NET 6 assembly references

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [mono/SkiaSharp#2534]
**Description**

I tried building SkiaSharp according to these instructions (Managed-Only Building): https://github.com/mono/SkiaSharp/wiki/Building-SkiaSharp
but I get 4 build errors using `dotnet cake --target=everything --skipExternals=all` and VS2022 17.7 Preview 4.0.

Example:

```
"C:\repos\mono\SkiaSharp\source\SkiaSharpSource.Windows-net.slnf" (Build target) (1:2) ->
       "C:\repos\mono\SkiaSharp\binding\SkiaSharp\SkiaSharp.csproj" (default target) (2:59) ->
       "C:\repos\mono\SkiaSharp\binding\SkiaSharp\SkiaSharp.csproj" (Build target) (2:66) ->
       (CoreCompile target) ->
         CSC : error CS1705: Assembly 'Microsoft.iOS' with identity 'Microsoft.iOS, Version=16.4.0.0, Culture=neutral, PublicKeyToken=84e04ff9cfb79065' uses 'System.Runtime, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' which has a higher version than referenced assembly 'System.Runtime' with identity 'System.Runtime, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' [C:\repos\mono\SkiaSharp\binding\SkiaSharp\SkiaSharp.csproj::TargetFramework=net6.0-ios]
```

Based on dotnet cake output, CoreCompile is indeed using `/reference:"C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\6.0.20\ref\net6.0\System.Runtime.dll"`
Which is clearly net6.0.

And this is used for Microsoft.iOS: `/reference:C:\repos\mono\SkiaSharp\externals\package_cache\microsoft.ios.ref\16.4.7090\ref\net7.0\Microsoft.iOS.dll`
Which is clearly net7.0.

**Expected Behavior**

SkiaSharp will compile using dotnet cake.

**Actual Behavior**

SkiaSharp does not compile using dotnet cake.

**Basic Information**

- Version with issue:  2.88.4-preview, latest code on 24th July 2023. Windows 11.
- Last known good version:  ?
- IDE:  Visual Studio 2022 17.7 Preview 4.0 _(installed)_ but I'm using `dotnet cake` from the command line prompt.

_Any way to fix this issue?_

Also, it is strange that the target framework is `xamarinios1.0`. I cannot find it here: https://learn.microsoft.com/en-us/dotnet/standard/frameworks.

**Comment by mattleibow** [comment]
This should no longer be an issue as the `main` branch now is almost entirely net7.0+. There are a few netstandards and net472. But, now you can use `dotnet build` everywhere too.
