### ISSUE TITLE
Create a "simple" picture view

### ISSUE THREAD

**Issue by mattleibow** [mono/SkiaSharp#255]
This view should be able to just have a setter:

```csharp
var view = new SKImageView();
view.Bitmap = SKBitmap.Decode(myImagePath);
```

Also, another option would be to create extension methods to convert images to platform images:

```csharp
// bitmaps
SKBitmap bitmap = ...;
var uiImage = bitmap.ToUIImage();

// pictures
SKPicture picture = ...;
var cgImage = picture.ToCGImage(new SKSizeI(100, 100));
```

**Comment by mattleibow** [comment]
I decided against creating a custom image view just for SkiaSharp for several reasons:
 - re-doing the work of every platform out there
 - too many features, for too many platforms
 - existing infrastructure/extensions (loaders/effects) won't work

However... I have provided a way to convert from SkiaSharp types (`SkBitmap`, `SKPicture`, `SKImage` and `SKPixmap`) into platform types (`CGImage`, `CIImage`, `UIImage`, `NSImage`, `System.Drawing.Bitmap`, `Android.Graphics.Bitmap`, `WriteableBitmap`).

These are basic extension methods that take a copy of the pixels and hand it over to the OS. Then, these can be used in any UI picture view on the platform - and any custom ones that are in use.

I am closing this now as I think I have something that will help everyone :) But, feel free to re-open if you need/prefer something else:
 - you really need a custom image view...
 - you want some extension method that does NOT copy the pixels (you will have to manage the lifetime of the SkiaSharp instance) - this is also not always possible on some of the platforms
 - another idea based on displaying a SkiaSharp image in some native way

**Comment by nathanielcook** [comment]
I see here and also [here](https://forums.xamarin.com/discussion/comment/235304/#Comment_235304) that there is a way to use SkiaSharp from XAML (Xamarin Forms), but what about AXML (native Android) layouts?

**Comment by mattleibow** [comment]
You can use:

    <skiasharp.views.android.SKCanvasView
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:id="@+id/canvasView" />

https://github.com/mattleibow/SkiaSharpDemo/blob/master/SkiaSharpNativeDemo/SkiaSharpNativeDemo.Android/Resources/layout/main.axml
