### ISSUE TITLE
[PERFORMANCE] SKCanvasView (Android) is considerably slower in MAUI than in Xamarin.Forms (over 7 times slower!)

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [mono/SkiaSharp#2555]
## **Description**

We tested SkiaSharp performance in **.NET MAUI (.NET 7) vs. Xamarin.Forms** using the [GnollHack](https://github.com/hyvanmielenpelit/GnollHack) game. We used the same saved game and the same screen for tests. The code was exactly the same in MAUI and Xamarin.Forms. We used **Google Pixel 6a Android device** for tests. The tested versions of SkiaSharp were 2.80.3 and 2.88.3. The tests were run using **SkCanvasView**, that is, GPU Acceleration was disabled.

The test results were:

### Xamarin.Forms with SkiaSharp 2.80.3 _(=situation now)_
- Normal zoom: 60+ FPS (max)
- Minimap zoom: 31.0 FPS

### Xamarin.Forms with SkiaSharp 2.88.3 _(=upgraded SkiaSharp)_
- Normal zoom: 40.7 FPS
- Minimap zoom: 17.0 FPS

### MAUI with SkiaSharp 2.88.3 _(=upgraded SkiaSharp and XF to MAUI)_
- Normal zoom: 22 FPS
- Minimap zoom: 4.2 FPS

## **Expected Behavior**

- MAUI is faster than Xamarin.Forms.
- SkiaSharp 2.88.3 is faster than 2.80.3.

## **Actual Behavior**

- MAUI is **4 times slower** than Xamarin.Forms when using the minimap zoom _(SkiaSharp 2.88.3: MAUI 4.2 FPS vs XF 17.0 FPS)_.
- SkiaSharp 2.88.3 is **1.82 times slower** than SkiaSharp 2.80.3 using the minimap zoom _(17.0 FPS vs 31.0 FPS)_.

In total, MAUI using SkiaSharp 2.88.3 is **7.38 TIMES SLOWER** than Xamarin.Forms using SkiaSharp 2.80.3 using the minimap zoom _(4.2 FPS vs 31.0 FPS)_.

## Conclusion

Needless to say, 7.38x drop in FPS is not fine for the game. Is there anything that we can do to get FPS back to XF 2.80.3 levels in MAUI?

We have already implemented the immutable fix (#2188), without which SkiaSharp 2.88.3 did not work at all.

**Comment by janne-hmp** [comment]
@mattleibow Based on some comments in #2112 and #2188 and I tested this further with GnollHack by changing most SKBitmaps to SKImages, and the FPS dropped to 0.2 even in normal zoom in 2.80.3. So drawing SKImages seems to be terribly much slower than that of SKBitmaps, which is probably the reason (along with possibly allocating more memory to SKImages on every draw in the  wrapper) for the performance drop if somebody wrapped SKBitmaps with SKImages before drawing. If this is in fact the problem, would it be possible to get the direct non-wrapped SKBitmap drawing routines back to SkiaSharp?

**Comment by TommiGustafsson-HMP** [comment]
@mattleibow  We were able to resolve the performance degradation by:
- Increasing GPU Resource Cache to 1 GB – 2 GB on Android devices, dynamically based on available RAM.
- Using SKImages instead of SKBitmaps.

We are not sure why Android requires a huge GPU Resource Cache. On iOS, things work well with a smaller cache.
