### ISSUE TITLE
[Need Help] XF Image Cropper

### ISSUE THREAD

**Issue by AiCraft** [mono/SkiaSharp#256]
Hi Guys

I have create Xamarin Forms cross platform ImageCroper using skiasharp customrenderer .
Which works properly in UWP(Desktop). But having many issue in IOS, Andorid and UWP mobile.
Like performance, UI lags too much. 
And touch is not working properly.

Plz just look at once. 
https://github.com/AiCraft/XFImageCroper

Thanks And Regards

**Comment by mattleibow** [comment]
Hi @AiCraft, I had a look, and I think the main "issue" is that you are doing too much in the paint method.

https://github.com/AiCraft/XFImageCroper/blob/master/CustomRendererDemo/CustomRendererDemo/MainPage.xaml.cs#L226-L228
```csharp
Stream FileStream = DependencyService.Get<ImageFile>().readFile("Assets/flower.jpg");
using (var stream = new SKManagedStream(FileStream))
using (var _bitmap = SKBitmap.Decode(stream))
```

Basically, on each paint, you are doing I/O and accessing the file on disk. And then, you decode and render. I would strongly suggest moving this to a startup place - maybe on appearing? Then you can even do this async.

**Comment by mattleibow** [comment]
Also, I notice in your draw method, you are using the same paint all over - and re-setting the same values. What you could do is to construct the paint object once in the startup, and then just reuse them. Although this is not going to be a bit performance boost, this will reduce any overhead that there might be.

**Comment by mattleibow** [comment]
I see you also init twice:
https://github.com/AiCraft/XFImageCroper/blob/master/CustomRendererDemo/CustomRendererDemo/MainPage.xaml.cs#L38-L39

**Comment by AiCraft** [comment]
@mattleibow Hi Sir,
I have done that changes but improvements are not much on Phone(WinPhone).
I fount the issue regrading touch also. Problem was with the Canvas Scaling. I was touching somewhere and point was appearing some where else.
