### ISSUE TITLE
The project file can not resolve the class reference path in the csproj file.

### ISSUE THREAD

**Issue by kwcoffee1** [mono/SkiaSharp#257]
I ran into two errors when attempting to compiling the wpf skiasharp solution project.

The nugget restore file for the skiasharp.* objects  version is not one of the revisions on the server. 

The skia and framework libraries are being resolve the wrong path on VS 2015 community and windows 10.

**Comment by mattleibow** [comment]
Closing this as I have released the latest NuGets.
