### ISSUE TITLE
large apk size with xamarin C9

### ISSUE THREAD

**Issue by roceh** [mono/SkiaSharp#259]
This might purely be a C9 related issue, or it might be some interaction with how skiasharp is built. But the APK size is much larger with C9 with skiasharp than it was with C8. Looking at the APK the skiasharp assembly DLL is 9mb which i assume includes the embedded native library,.  So is the native part is included in the APK twice?

**Comment by mattleibow** [comment]
This is interesting since the SkiaSharp.dll should be less that 100KB in the APK... 
This might be an issue with the build not removing the native libs.

Is it possible to send me your APK? And what are you using VS on Windows or XS on macOS?

**Comment by roceh** [comment]
[com.david.skiaapktest.apk.zip](https://github.com/mono/SkiaSharp/files/827745/com.david.skiaapktest.apk.zip)

Attached an example apk, but its basically just a build of the XF template project with skiasharp added from the latest stable build of xamarin studio.

**Comment by mattleibow** [comment]
Thanks for reporting this issue. I am closing this as this in not directly related to the SkiaSharp project.

I have opened an issue with the Android team: https://bugzilla.xamarin.com/show_bug.cgi?id=53250

At this time, I am unaware of a workaround, so rolling back to the latest C8 release appears to be the  only option. However, hopefully that team can help with a workaround, or at least a solution very soon.
