### ISSUE TITLE
[BUILD] Building Android Native Assets for libHarfBuzzSharp fails in an error

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [mono/SkiaSharp#2595]
### Description

When I try to build Android native assets in `native\android` folder using `dotnet cake` **libSkiaSharp** builds ok, but **libHarfBuzzSharp** fails with the following error:

```
========================================
libHarfBuzzSharp
========================================
make: *** No rule to make target 'C:/repos/mono/SkiaSharp/externals/skia/third_party/externals/harfbuzz/src/harfbuzz-subset.cc', needed by 'obj/local/x86/objs/HarfBuzzSharp/C_/repos/mono/SkiaSharp/externals/skia/third_party/externals/harfbuzz/src/harfbuzz-subset.o'.  Stop.
An error occurred when executing task 'libHarfBuzzSharp'.
Error: Process 'C:/Microsoft/AndroidNDK/android-ndk-r23c/ndk-build.cmd' failed with error: 2
```

Any idea how to resolve this error?

I am using the latest code in the SkiaSharp repository (as of 2nd Sep 2023).

### Code

No code.

### Expected Behavior

libHarfBuzzSharp native assets will build.

### Actual Behavior

libHarfBuzzSharp does not build.

### Version of SkiaSharp

Other (Please indicate in the description)

### Last Known Good Version of SkiaSharp

Other (Please indicate in the description)

### IDE / Editor

Visual Studio (Windows)

### Platform / Operating System

Android

### Platform / Operating System Version

Windows 11

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by janne-hmp** [comment]
@mattleibow This seems to be caused by ../../../externals/skia/third_party/externals/harfbuzz/src directory missing from the SkiaSharp repository (or more precisely, its linked mono/Skia repository). Would it be possible to add this src directory along with its source files to the repository, or is the idea to download the sources somehow separately?

**Comment by mattleibow** [comment]
How did you clone this? You need to make sure submodules are also pulled and then skia goes and pulls additional dependencies in the `git-sync-deps` cake task.

Basically, SkiaSharp uses submodules, and skia uses a manually pull on top.

**Comment by TommiGustafsson-HMP** [comment]
I think I used Visual Studio's Clone Repository with `https://github.com/mono/SkiaSharp.git`. Is there a better way to do it?

**Comment by mattleibow** [comment]
I suppose it is fine to use, you just need to run `git submodule update --init --recursive` in the directory after the clone.

Or just use the GitHub desktop app as it will do it automatically. Not sure why VS does not clone submodules...

**Comment by TommiGustafsson-HMP** [comment]
Thanks! I will try that out!

**Comment by TommiGustafsson-HMP** [comment]
It's working now.
