### ISSUE TITLE
Issue with ICC Profile Loss in .Resize() Function - Version 2.88.0

### ISSUE THREAD

**Issue by IAMManuel** [mono/SkiaSharp#2629]
### Description

We have encountered an issue with the `.Resize()` function in our software. It appears that, starting from version `2.88.0`, images lose their ICC profile after passing through this function. Prior to version 2.88.0, this functionality was working as expected, including in version `2.80.4` and earlier.

### Code

We're using images on this [site](https://displaycal.net/icc-color-management-test/). All the test cases were negatives using the "newer" versions

```cs
using SkiaSharp;

try
{
    // Load an image with an ICC profile
    using SKBitmap originalImage = SKBitmap.Decode("pathToImage.jpg");

    // Resize the image
    int newWidth = 200;
    int newHeight = 200;

    // Resize the original image using SkiaSharp
    using SKBitmap skiaResizedBitmap = originalImage.Resize(new SKImageInfo(newWidth, newHeight), SKFilterQuality.High);

    var ms = new MemoryStream();
    skiaResizedBitmap.Encode(ms, SKEncodedImageFormat.Png, 100);
    ms.Position = 0;
    File.WriteAllBytes("resized_image.jpg", ms.ToArray());
}
catch (Exception ex)
{
    Console.WriteLine("An error occurred: " + ex.Message);
}
```

### Expected Behavior

All ICC tests cases should be positives when resizing with SkiaSharp.

### Actual Behavior

All ICC test cases are actually negatives when using `.Resize()` with SkiaSharp

### Version of SkiaSharp

2.88.3 (Current)

### Last Known Good Version of SkiaSharp

2.80.x (Deprecated)

### IDE / Editor

Other (Please indicate in the description)

### Platform / Operating System

Windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by TommiGustafsson-HMP** [comment]
Here's a duplicate of this issue, which was resolved and closed:
https://github.com/mono/SkiaSharp/issues/2784

**Comment by IAMManuel** [comment]
After adding the color space, like mention in the issue #2784, I still got an image not respecting the ICC profile again.

**Comment by IAMManuel** [comment]
Since we still got the same issues, I've prepared 4 solutions ( 2 with .png and 2 with .jpg images). One used the 2.80.2 version and the other used the 2.88.8 version ( it could be any version later than 2.80.4). They both use the same code expressed in the following issue #2784. 

Here are the result images:
- For the .png using the the 2.80.2 version
![result-picture-icc-embedded-matrix](https://github.com/mono/SkiaSharp/assets/2425292/a731e846-ad6e-42af-bcd0-9e409023dedd)
- For the .png using the the 2.88.8 version
![result-picture-icc-embedded-matrix](https://github.com/mono/SkiaSharp/assets/2425292/99ece539-5405-4024-8cf3-e566bfafea41)
- For the .jpg using the the 2.80.2 version
![result-picture-icc-embedded-matrix](https://github.com/mono/SkiaSharp/assets/2425292/11afc0ea-50cb-4b6d-b5f5-fdc17c40239c)
- For the .jpg using the the 2.88.8 version
![result-picture-icc-embedded-matrix](https://github.com/mono/SkiaSharp/assets/2425292/43520f56-c79a-4717-b90e-5b3a9522b2af)


For reference, here's the original images:
- png
![picture-icc-embedded-matrix](https://github.com/mono/SkiaSharp/assets/2425292/a9c370bd-beba-431e-a2b2-774121067686)
- jpg
![picture-icc-embedded-matrix](https://github.com/mono/SkiaSharp/assets/2425292/a47853fc-a268-4778-a440-2ce50d639794)

And the code that test these cases: 
[SkiaWorkingPngSample.zip](https://github.com/user-attachments/files/15516069/SkiaWorkingPngSample.zip)
[SkiaNonWorkingPngSample.zip](https://github.com/user-attachments/files/15516070/SkiaNonWorkingPngSample.zip)
[SkiaWorkingJpegSample.zip](https://github.com/user-attachments/files/15516077/SkiaWorkingJpegSample.zip)
[SkiaNonWorkingJpegSample.zip](https://github.com/user-attachments/files/15516080/SkiaNonWorkingJpegSample.zip)

**Comment by IAMManuel** [comment]
After more verification on our part, we found that the issue was on our end. Sorry again for the time taken !
