### ISSUE TITLE
Implement a SkiaSharp TextureView for Android

### ISSUE THREAD

**Issue by mattleibow** [mono/SkiaSharp#263]
See information from #228 and #223 

Basically there are currently 2 main issues:
 - Transparency is not supported with the Android `GLSurfaceView`
 - Xamarin.Forms (and any Android) uses a `Fragment` for navigation, and any view above is overlayed

**Comment by DeanClaes** [comment]
Hello @mattleibow 

Do you have any idea on when this might be implemented?
I have a feeling that this will perform better than the current underlying View when doing animations of any sort (like animated frame images). Right now simply calling InvalidateSurface (without rendering anything) in a loop seems to strain the CPU quite a bit. I supsect that this would not be the case with a TextureView.

**Comment by michaelstonis** [comment]
I assume this will need an implementation like this https://raw.githubusercontent.com/romannurik/muzei/master/main/src/main/java/com/google/android/apps/muzei/render/GLTextureView.java? Do you know if this was ported, it it would be a drop-in kind of replacement? I am willing to give it a shot

**Comment by mattleibow** [comment]
@michaelstonis thanks for the offer. I managed to find a port already: [GLTextureView.cs](https://github.com/pikkart-support/Pikkart-AR-SDK-ARLogo-Xamarin.Android-Sample/blob/master/PikkartSample/PikkartSample.Droid/GLTextureView.cs) (I went on a GitHub search for GLTextureView and C# - you can find everything on GitHub nowadays) 

I had to make a few tweaks to fix a bug and some Java-to-C# not-quite-rights, but I am mostly done. Just got to clean up the code, remove bad things and make sure I conform to the (attempt) at code styling. I threw up the code here so long: https://github.com/mono/SkiaSharp/pull/426 

You can have a look, and give any feedback. As soon as this is "stable" I am going to switch out the `SKGLView` for the forms renderer and use this instead. Hopefully I don't break every app out there, but I shall test! This will fix the two original issues that started this thread.

Let me know what you think, and a very special thanks to @pikkart-support or [@Pikkart_AR](https://twitter.com/Pikkart_AR) for doing all the hard work!

**Comment by michaelstonis** [comment]
Is this by chance available via the jenkins builds? For whatever reason, I can't get it to compile locally.

**Comment by mattleibow** [comment]
I am still working on getting CI to build this - there are a few changes happing to the bots. But, you should be able to just take the 3 files and add them to your project. This just uses the public APIs - I actually worked on this in a small sample app using v1.59.3

**Comment by mattleibow** [comment]
@michaelstonis Have you had an opportunity to try out the texture view? Any feedback?

**Comment by michaelstonis** [comment]
Unfortunately not yet. I am primarily using the Android components via Xamarin.Forms and it looks like there will need to be some underneath the sheets switching to get the TextureView registered as the default GL Surface. I will try to take a look into this soon though.

**Comment by mattleibow** [comment]
Ah, I will try and get that working too so you can just swap out the dll

**Comment by mattleibow** [comment]
Just merged the changes. I have switched the default platform renderer for android to the texture view - this should fix all issues :)

**Comment by mattleibow** [comment]
@michaelstonis I have reached what I think is good to go...

 - [SkiaSharp.1.60.0-beta.nupkg](https://jenkins.mono-project.com/view/Components/job/Components-SkiaSharp/lastSuccessfulBuild/Azure/processDownloadRequest/ArtifactsFor-319/eb629db98be18a73870fcab33b677512ec6bc02a/output/SkiaSharp.1.60.0-beta.nupkg)
 - [SkiaSharp.Views.1.60.0-beta.nupkg](https://jenkins.mono-project.com/view/Components/job/Components-SkiaSharp/lastSuccessfulBuild/Azure/processDownloadRequest/ArtifactsFor-319/eb629db98be18a73870fcab33b677512ec6bc02a/output/SkiaSharp.Views.1.60.0-beta.nupkg)
 - [SkiaSharp.Views.Forms.1.60.0-beta.nupkg](https://jenkins.mono-project.com/view/Components/job/Components-SkiaSharp/lastSuccessfulBuild/Azure/processDownloadRequest/ArtifactsFor-319/eb629db98be18a73870fcab33b677512ec6bc02a/output/SkiaSharp.Views.Forms.1.60.0-beta.nupkg)

Give that a whirl and let me know what happens. The Xamarin.Forms view should now be using the TextureView under the hood.
