### ISSUE TITLE
[BUG] SKCanvasView control crashes in .NET 7 and 8 MAUI

### ISSUE THREAD

**Issue by soyfrien** [mono/SkiaSharp#2648]
### Description

When navigating to a **ContentPage** with an **SKCanvasView** the app will crash. In Windows there is no error message, but debugger throws to the highlighted in `app.g.i.cs`:
<img width="750" alt="Unhandled exception when DEBUG and !DISABLE_XAML_GENERATED_BREAK_ON_UNHANDLED_EXCEPTION" src="https://github.com/mono/SkiaSharp/assets/3385925/cc3aff31-25a0-4950-a6ea-c9b95909f186">

And when launching into the Android emulator, I get the following Unhandled Exception:
`Microsoft.Maui.Platform.HandlerNotFoundException: 'Handler not found for view SkiaSharp.Views.Maui.Controls.SKCanvasView.'`

### Code

The best way to share code for larger projects is a link to a GitHub repository: https://github.com/user/repo/tree/bug-123

But, you can also share a short block of code here:
```cs
using SkiaSharp;
using SkiaSharp.Views.Maui;

namespace SkiaSharpMaui8;

public partial class MainPage : ContentPage
{
	public MainPage() => InitializeComponent();


	private void OnPaintSurface(object sender, SKPaintSurfaceEventArgs e)
	{
		SKSurface surface = e.Surface;
		SKCanvas canvas = surface.Canvas;
		canvas.Clear(SKColors.White);
		
		SKPaint paint = new()
		{
			Style = SKPaintStyle.Stroke,
			Color = SKColors.Black,
			StrokeWidth = 2
		};
		SKRect sKRect = new(20, 20, 360, 360);
		canvas.DrawRect(sKRect, paint);
	}
}
```
You can also share some XAML:
```xaml
<?xml version="1.0" encoding="utf-8" ?>
<ContentPage xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             xmlns:skviews="clr-namespace:SkiaSharp.Views.Maui.Controls;assembly=SkiaSharp.Views.Maui.Controls"
             x:Class="SkiaSharpMaui8.MainPage">

    <VerticalStackLayout >
        <skviews:SKCanvasView PaintSurface="OnPaintSurface"
                              HeightRequest="400" 
                              WidthRequest="400"/>
    </VerticalStackLayout>
</ContentPage>
```

### Expected Behavior

I expected to have a canvas with a rectangle drawn on it.

### Actual Behavior

The application crashed upon loading a page with an SKCanvasView.

### Version of SkiaSharp

2.88.3 (Current)

### Last Known Good Version of SkiaSharp

2.88.2 (Previous)

### IDE / Editor

Visual Studio (Windows)

### Platform / Operating System

Android, Windows

### Platform / Operating System Version

- Windows 11

### Devices

- Android API 33

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by FoggyFinder** [comment]
try to add `.UseSkiaSharp()`

**Comment by soyfrien** [comment]
Thank you.

If someone can, please remove the bug label.
