### ISSUE TITLE
[BUG] SKRuntimeEffect doesn't work on Bitmap Canvas

### ISSUE THREAD

**Issue by workgroupengineering** [mono/SkiaSharp#2657]
### Description

When attempting to use SKSL effects on bitmap canvases, there is a native exception raised.

Same of https://github.com/mono/SkiaSharp/issues/1822

### Code

```cs
var bitmap = new SKBitmap(100, 100, false);
using var canvas = new SKCanvas(bitmap);

var src = @"
half4 main(float2 fragCoord) {
  return half4(0.5, 0.5, 0.5, 1);
}";

using var effect = SKRuntimeEffect.Create(src, out var error);

using (SKPaint bgPaint = new SKPaint { IsAntialias = true, Shader = effect.ToShader(false) })
    canvas.DrawRoundRect(0, 0, 100, 100, 15, 15, bgPaint); // This raises an exception
```
You can also share some XAML:
```xaml
<!-- xaml code here -->
```

### Actual Behavior

An exception occurs on attempting a draw operation:
An unhandled exception of type `System.Runtime.InteropServices.SEHException` occurred in SkiaSharp.dll
External component has thrown an exception.

### Version of SkiaSharp

**2.88.3**  and **2.88.6**

### Last Known Good Version of SkiaSharp

Other (Please indicate in the description)

### IDE / Editor

Visual Studio (Windows)

### Platform / Operating System

Windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by taublast** [comment]
Works with not round DrawRect?  Could potentially use clipping with circle path if needed.

**Comment by Siydge** [comment]
Same issue here, hoping this issue gets resolved soon, as using SKRuntimeEffect would be greatly beneficial for me.

**Comment by taublast** [comment]
Found out this is due to the fact that computed shaders will just not work in skiasharp v2 with non-hardware accelerated views. The closest looking resolution could be the (soon?) release of skiasharp v3 where shaders could also use cpu, or less "soon-looking" gpu support on windows implementation. Basically let's way for skiasharp 3.0 which is actually in closed prerelease state.
