### ISSUE TITLE
XPS Support

### ISSUE THREAD

**Issue by jotab123** [mono/SkiaSharp#266]
Hi team,
Do you have any plan to support the XPS backend??

Thanks!

**Comment by mattleibow** [comment]
2 things:
 1. Yes 😄 
 2. It is still experimental from skia side - https://skia.org/user/api/canvas#skxps

Right now I am in the process of updating the underlying skia to the next version (m57) and this uses a new build system. So the first v1.57.0 release may or may not have XPS, but I think the next version (v1.57.1) should have.

The build changes are fairly large as they don't really have great support for non macOS/Android devices. Thus, I have been adding iOS/tvOS and doing quite a bit for UWP.

**Comment by mattleibow** [comment]
Well, that was easy :) Should be there in the next release.
