### ISSUE TITLE
[FEATURE] Include `SkiaSharp.Views.WinUI` in `SkiaSharp.Views.Uno.WinUI`

### ISSUE THREAD

**Issue by MartinZikmund** [mono/SkiaSharp#2665]
### Is your feature request related to a problem?

Currently it seems that to use SkiaSharp in a Uno Platform WinUI project, we need to do something like:

```xml
<Choose>
	<When Condition="$(IsWinAppSdk)">
		<ItemGroup>
			<PackageReference Include="SkiaSharp.Views.WinUI" />
		</ItemGroup>
	</When>
	<Otherwise>
		<ItemGroup>
			<PackageReference Include="SkiaSharp.Views.Uno.WinUI" />
		</ItemGroup>
	</Otherwise>
</Choose>
```

### Describe the solution you would like

It would be best if the SkiaSharp.Views.Uno.WinUI also included the WinUI target, so that this wouldn't be needed.

### Describe alternatives you have considered

Installing separate packages

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mattleibow** [comment]
You can have adummy fine in the winui TFM `_._` and then that can just be dependencies.

I think I did that with v3.0 here: https://github.com/mono/SkiaSharp/blob/a424d81f8e73e92d956eb9a149c9a7e71338e869/source/SkiaSharp.Views.Uno/SkiaSharp.Views.Uno.WinUI/SkiaSharp.Views.Uno.WinUI.csproj#L116C1-L129
