### ISSUE TITLE
SKGLView Blend Mode problems

### ISSUE THREAD

**Issue by sdenowh** [mono/SkiaSharp#268]
I have run into an issue with SKGLView when trying to use BlendMode.Darken to highlight some text in a bitmap. When using SKCanvasView, the output is blended as expected.

I've drawn a bitmap into a SKCanvasView (canvas) using canvas.DrawBitmap:
<img width="286" alt="bitmap_on_screen" src="https://cloud.githubusercontent.com/assets/53743/24204352/34391ee6-0ee6-11e7-878d-568d0928c9b1.png">

I've then drawn some boxes over that on the canvas using canvas.DrawRect. These are set to colors with no alpha transparency. I'm using a paint object with the blend mode set to BlendMode.Darken.
<img width="244" alt="skcanvasview_darken" src="https://cloud.githubusercontent.com/assets/53743/24204522/c3fd0dee-0ee6-11e7-899e-304182bf9f31.png">

Upon changing to a SKGLView (which runs much better in my use case), the output changes significantly.
<img width="243" alt="skglview_darken" src="https://cloud.githubusercontent.com/assets/53743/24204576/ea9b032a-0ee6-11e7-8137-79e04a0ef3d1.png">

I've also found that if I set my colors used in the DrawRect calls to have some alpha transparency, that is not reflected if the blend mode is set to darken (again, on SKGLView) (I've expended the size of the rects during testing here)
<img width="235" alt="skglview_darken_with_alpha" src="https://cloud.githubusercontent.com/assets/53743/24204725/561538be-0ee7-11e7-8a98-d3e6cf832f9d.png">

If I change the blend mode back to the default, SrcOver, then my alpha is applied and I can at least see through the boxes. Not ideal, but a passable workaround for the moment.
<img width="236" alt="skglview_srcover_with_alpha" src="https://cloud.githubusercontent.com/assets/53743/24204789/855e1ab4-0ee7-11e7-9c49-f096246afe94.png">

This testing was done on SkiaSharp 1.56.1 using Xamarin.Forms.

**Comment by mattleibow** [comment]
I am having a look at this and I can't seem to repro it:

```csharp
canvas.Clear(SKColors.White);

var text = new SKPaint
{
	TextSize = 50,
	IsAntialias = true
};
canvas.DrawText("Hello World!", 100, 100, text);

var darken = new SKPaint
{
	Color = SKColors.Blue,
	Style = SKPaintStyle.Fill,
	IsAntialias = true,
	BlendMode = SKBlendMode.Darken
};
canvas.DrawRect(SKRect.Create(150, 50, 100, 100), darken);
```

Are you able to share some code or sample?
