### ISSUE TITLE
Unable to load library 'libSkiaSharp'

### ISSUE THREAD

**Issue by leliksan1234** [mono/SkiaSharp#2685]
### Description

Project .NET 4.8.  
SkiaSharp, SkiaSharp.NativeAssets.Linux, SkiaSharp.NativeAssets.Linux.NoDependencies, SkiaSharp.NativeAssets.macOS, SkiaSharp.NativeAssets.WebAssembly, SkiaSharp.NativeAssets.Win32, SkiaSharp.Views.Desktop.Common, SkiaSharp.Views.WindowsForms Nuget packages installed.
Project works on Windows machine.  Version of Nuget 2.88.6

Unable to load library 'libSkiaSharp' throwed. Any ideas?

### Code

```
public byte[] Resize(byte[] fileContents, int maxWidth, int maxHeight, Quality quality = Quality.High)
{
    using (var ms = new MemoryStream(fileContents))
    {
        using (var sourceBitmap = SKBitmap.Decode(ms)) - exception here
        {
            /////
        }
    }
}
```

### Version of SkiaSharp

2.88.3 (Current)

### Last Known Good Version of SkiaSharp

2.88.2 (Previous)

### IDE / Editor

Visual Studio (Windows)

### Platform / Operating System

Windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mattleibow** [comment]
You say "Project works on Windows machine" so which platform is failing?
