### ISSUE TITLE
[BUG] MAUI SKCanvasView.CanvasSize is zero on MacCatalist, and OnPaintSurface not called

### ISSUE THREAD

**Issue by npdwc** [mono/SkiaSharp#2704]
### Description

When I call `PaintCanvas?.InvalidateSurface();` `OnPaintSurface` not called.
When I looking on `PaintCanvas.CanvasSize` is `{{Width=0, Height=0}}`.

### Code

```C#
public partial class Plot : ContentView
{
    private readonly Timer _invalidateTimer;

    public Plot()
    {
        InitializeComponent();
        PaintCanvas.PaintSurface += OnPaintSurface;
        _invalidateTimer = new Timer(OnInvalidateWatchdog, null, 50, 50);
    }

    private void OnPaintSurface(object sender, SKPaintSurfaceEventArgs args)
    {
        //    Not called on MacCatalyst
    }

    private void OnInvalidateWatchdog(object state)
    {
        Dispatcher.Dispatch(() =>
        {
            PaintCanvas?.InvalidateSurface();
        });
    }
}
```

```xaml
<ContentView xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             x:Class="Mcs.Maui.EmgPlot.Plot"
             xmlns:skiaSharp="clr-namespace:SkiaSharp.Views.Maui.Controls;assembly=SkiaSharp.Views.Maui.Controls">
    <Grid>
        <skiaSharp:SKCanvasView x:Name="PaintCanvas"/>
        <Grid
            x:Name="Names"
            HorizontalOptions="Start" />
    </Grid>
</ContentView>
```

### Expected Behavior

`OnPaintSurface` is working
`CanvasSize` has good size

### Actual Behavior

I think it is because CanvasSize is zero

### Version of SkiaSharp
2.88.6

### IDE / Editor

Visual Studio (macOS)

### Platform / Operating System

Mac Catalyst

### Platform / Operating System Version

macOS Sonoma 14.2.1

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mattleibow** [comment]
What happens if you set the `HorizontalOptions` and `VerticalOptions` to `Fill`? Not sure why the layout does not give the canvas a size.
