### ISSUE TITLE
Build warning on Xamarin.iOS when building for physical device

### ISSUE THREAD

**Issue by PatrickRyder** [mono/SkiaSharp#271]
As of the latest updates to SkiaSharp and Xamarin, I am now getting the following warning when building for a physical iOS device:

4>  warning: no debug symbols in executable (-arch armv7)

This does not happen when building for the simulator.  It does not happen if I remove the SkiaSharp package from the project.

If in iOS Build I untick 'Enable device specific builds' I get two of these warnings, the other one being for x64.

My versions are as follows:

Visual Studio Community 2015 on Windows 10 64-bit
Xamarin V4.3.0.789
Xamarin.iOS V10.4.0.128
Xamarin.Forms V2.3.3.193
SkiaSharp V1.56.2
SkiaSharp.Views V1.56.2
SkiaSharp.Views.Forms V1.56.2

**Comment by mattleibow** [comment]
This is working as expected.

In order to reduce the size of the native archive, the libSkiaSharp.framework is stripped of everything.

You can see this in the build log that it is just for the libSkiaSharp:

```
DSymUtil Task
      AppBundleDir: bin/iPhone/Release/SkiaSharpSampleFormsSampleiOS.app
      Architectures: <null>
      DSymDir: bin/iPhone/Release/SkiaSharpSampleFormsSampleiOS.app/../libSkiaSharp.framework.dSYM
      Executable: bin/iPhone/Release/SkiaSharpSampleFormsSampleiOS.app/Frameworks/libSkiaSharp.framework/libSkiaSharp
    Tool /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/dsymutil execution started with arguments: -t 4 -z -o bin/iPhone/Release/SkiaSharpSampleFormsSampleiOS.app/../libSkiaSharp.framework.dSYM bin/iPhone/Release/SkiaSharpSampleFormsSampleiOS.app/Frameworks/libSkiaSharp.framework/libSkiaSharp 
    warning: no debug symbols in executable (-arch armv7)
    warning: no debug symbols in executable (-arch arm64)
```

**Comment by mattleibow** [comment]
I am closing this as it is not really an "issue", but feel free to re-open if this is a bug or causing problems.

**Comment by PatrickRyder** [comment]
Hi, Matthew,


No problem about closing it.  I raised it because my company has a policy of zero errors, zero warnings in builds.  Maybe I can find a way to turn it off.


Sorry to have wasted your time.



Kind wishes - Patrick Ryder

Author of 'Spiders in Your Mind', a collection of new short stories for those of you who like a scare and 'Crossed Shadows', a novel unlike any you will have read before.  A bold claim, I know.
'Crossed Shadows' available at Amazon: http://goo.gl/48d7LD.<http://goo.gl/48d7LD>
Crossed Shadows eBook: Patrick Ryder: Amazon.co.uk: Kindle Store
Crossed Shadows eBook: Patrick Ryder: Amazon.co.uk: Kindle Store
Read more...<http://goo.gl/48d7LD>

Remove preview
'Spiders in Your Mind' available at Amazon: http://www.amazon.co.uk/Patrick-Ryder/e/B00ANLOWR8/ref=ntt_athr_dp_pel_pop_1.
All other e-reader formats??available (e.g. Nook) at Smashwords: http://www.smashwords.com/profile/view/PatrickRyder
Also available in Apple iStore and Barnes & Noble.
My work is free for members of the armed forces. I also have some free copies to give away. Please drop me a line if you would like one. I'd love to hear from you anyway.


________________________________

**Comment by mattleibow** [comment]
@PatrickRyder 

No waste of time.

Is this an actual build warning? I wasn't able to get a warning in the MSBuild results, but this was just visible in the build log. And, this is a warning from Xcode's dsymutil tool. If you set the options in Xcode to strip release builds (a yes/no option) then you will also get this warning.

May this helps with any arguments :)
