### ISSUE TITLE
Drawing Chinese text using DrawText on Blazor WebAssembly is not sharp

### ISSUE THREAD

**Issue by 18779758522** [mono/SkiaSharp#2713]
### Description

Enable Antialias, Blazor WASM DrawText Chinese  is very unclear.
Windows Forms DrawText Chinese is very clear and sharp
What is the method to draw Chinese clearly on Blazor WASM SkiaSharp ？
The following figure shows the test cases：
![WX20240113-110638](https://github.com/mono/SkiaSharp/assets/33852145/474d4f35-5f39-46f1-9b51-5c792fb6584a)
![WX20240113-112424](https://github.com/mono/SkiaSharp/assets/33852145/5d825e79-a9ba-408a-a560-a85a875558a1)

### Code
https://github.com/18779758522/SkiaSharpBlazorWebDemo

### Version of SkiaSharp

2.88.3 (Current)

### Last Known Good Version of SkiaSharp

2.88.2 (Previous)

### IDE / Editor

Visual Studio (Windows)

### Platform / Operating System

Windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by HinTak** [comment]
Isn't this the same as https://github.com/mono/SkiaSharp/issues/2797 ? It is frown upon to file the same issue twice.

**Comment by 18779758522** [comment]
delete
