### ISSUE TITLE
System.AccessViolationException inside libskiasharp

### ISSUE THREAD

**Issue by Sergey-Terekhin** [mono/SkiaSharp#273]
Hi!
I'm trying to perform conversion from SKImage to pixels array, but sometimes it falls with `System.AccessViolationException`.
May be it is because of multi-threading processing - I try to process all  images from folder using Thread pool. Could you advice something?

Using the latest `SkiaSharp` package available (`1.56.2`)

The code below contains exception:
```csharp
//image is SKImage
var pixels = image.PeekPixels();
if (pixels == null)
    throw new ArgumentException($"Can not get pixels from image {source}");
try
{
    if (pixels.BytesPerPixel != 1)
    {
        using (var grayImage = _grayConverter.Convert(source, PixelFormat.Format8bppIndexed))
        {
            pixels.Dispose();
            pixels = ((SkiaImageImpl)grayImage).Image.PeekPixels();
        }
    }
    
    var imageInfo = new ImageInfo(pixels.Width, pixels.Height, PixelFormat.Format8bppIndexed);
    
    var data = new byte[imageInfo.Stride * pixels.Height];
    var ptr = pixels.GetPixels();
    if (ptr == IntPtr.Zero)
    {
        throw new ArgumentException($"Can not get pixels from image {source}");
    }

    // ERROR IS HERE:
    Marshal.Copy(ptr, data, 0, data.Length);
    var result = new RawImage(
        data,
        imageInfo);
    return result;

}
finally
{
    pixels.Dispose();
}
```

**Comment by migueldeicaza** [comment]
to debug this sort of scenarios, you should provide a self-contained test case

**Comment by mattleibow** [comment]
@Sergey-Terekhin I am not sure exactly, but it may be because you are disposing the image and then using it later:

```csharp
using (var grayImage = _grayConverter.Convert(source, PixelFormat.Format8bppIndexed))
{
    pixels.Dispose();
    pixels = ((SkiaImageImpl)grayImage).Image.PeekPixels();
}
```

If this is doing what I think it may be doing, then the underlying pixels are actually disposed/freed when the `grayImage` is disposed. The `PeekPixels()` method returns a small class that simply contains a POINTER to the pixel data contained in the image, and not the pixel data directly.
