### ISSUE TITLE
[BUG] Webp image color change after resize

### ISSUE THREAD

**Issue by MichaelLogutov** [mono/SkiaSharp#2784]
### Description

When loading webp image and saving it in jpg without any transformation all colors preserved correctly. But when scale transformation applied colors became darker.

I've tried it on SkiaSharp `2.88.7` and `3.0.0-preview.2.1`

Here the source webp image: [test.zip](https://github.com/mono/SkiaSharp/files/14492382/test.zip)
Here the results.

Not scaled: ![test-output-not-scaled](https://github.com/mono/SkiaSharp/assets/405031/8aeccca9-5705-4e3a-80e1-266911bc54fc)
Scaled: ![test-output-scaled](https://github.com/mono/SkiaSharp/assets/405031/eaa41834-0591-4257-9fd3-b0840bd94293)

### Code

```cs
using var bitmap = SKBitmap.Decode(@"c:\Temp\test.webp");

using var bitmap2 = new SKBitmap(new SKImageInfo(bitmap.Info.Width / 2, bitmap.Info.Height / 2));
bitmap.ScalePixels(bitmap2, new SKSamplingOptions(SKFilterMode.Nearest, SKMipmapMode.Nearest));

using (var file = new SKFileWStream(@"c:\Temp\test-output-not-scaled.jpg"))
    bitmap.Encode(file, SKEncodedImageFormat.Jpeg, 100);

using (var file = new SKFileWStream(@"c:\Temp\test-output-scaled.jpg"))
    bitmap2.Encode(file, SKEncodedImageFormat.Jpeg, 100);
```

### Version of SkiaSharp

3.x (Alpha)

### Last Known Good Version of SkiaSharp

2.88.2 (Previous)

### IDE / Editor

Other (Please indicate in the description)

### Platform / Operating System

Linux, Windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by TommiGustafsson-HMP** [comment]
I think the problem is that your original picture has a color profile, which is lost at some point. If you open your original picture in Photoshop (Elements) and Convert Color Profile -> Remove Profile, the same thing as reported here will happen.

**Comment by MichaelLogutov** [comment]
Yeah, I think you right. But I can't see why scaling do this.

**Comment by TommiGustafsson-HMP** [comment]
There seems to be a question on this on StackOverflow:
https://stackoverflow.com/questions/50399279/skiasharp-save-image-with-icc-profile
