### ISSUE TITLE
[BUG] Font is not rendering properly when converting DOC to PDF in Blazor WASM NET8.0

### ISSUE THREAD

**Issue by ignasstephanie** [mono/SkiaSharp#2793]
### Description

When converting DOC to PDF using Syncfusion DocIORenderer as shown in the code below, the output font family does not properly show as how it should be. I am using SkiaSharp.Views.Blazor 2.88.7 NuGet package.

### Code
```cs
public MemoryStream BuildPDF()
{
    DocIORenderer render = new DocIORenderer();
    render.Settings.EmbedCompleteFonts = true;
    PdfDocument pdfDocument = render.ConvertToPDF(document);
    MemoryStream outputStream = new MemoryStream();
    pdfDocument.Save(outputStream);
    pdfDocument.Close();
    outputStream.Position = 0;
    return outputStream;
}
```

### Version of SkiaSharp

Other (Please indicate in the description)

### Last Known Good Version of SkiaSharp

2.88.2 (Previous)

### IDE / Editor

Visual Studio Code (Windows)

### Platform / Operating System

Windows

### Relevant Screenshots

The Word document is like the image below:
![image](https://github.com/mono/SkiaSharp/assets/53800465/db714673-a447-4b59-a79f-4e3948a17c00)

On the other hand, the output PDF from conversion:
![image](https://github.com/mono/SkiaSharp/assets/53800465/e7b41b36-49d0-45a2-ad46-33989f4a4c62)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mattleibow** [comment]
I don't know what `DocIORenderer` is. Is that a separate library? Maybe open an issue for that team to investigate.

**Comment by ignasstephanie** [comment]
This issue has been fixed on the Syncfusion's side. Thank you!
