### ISSUE TITLE
[BUG] Drawing Chinese using SkiaSharp in Blazor WASM is very blurry

### ISSUE THREAD

**Issue by 18779758522** [mono/SkiaSharp#2797]
### Description

I have enabled Antialias, but Blazor WASM DrawText in Chinese comes out very blurry, Windows Forms DrawText Chinese is very clear and sharp.

What is the method to draw Chinese clearly on Blazor WASM SkiaSharp?
The following figure shows the test cases: 
![14641710295992_ pic](https://github.com/mono/SkiaSharp/assets/33852145/8d472492-9ea4-4ad9-a4e6-c296fb7ca3c0)

### Code

https://github.com/18779758522/SkiaSharpBlazorWebDemo

### Expected Behavior

I tried upgrading to the latest version and it worked the same way.

### Version of SkiaSharp

2.88.4-preview (Preview)

### Last Known Good Version of SkiaSharp

Other (Please indicate in the description)

### IDE / Editor

Visual Studio Code (Windows)

### Platform / Operating System

All

### Platform / Operating System Version

Goole Chrome 122.0.6261.112

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by HinTak** [comment]
The problem at first glance, is in your code : you asked for `TextSize = 16`. That means it is generated at size 16 (roughly a 16x16 pixel grid, though the actual detail could differ, depending on the font itself), then scaled/drawn on your canvas. If you ask for a much larger size and have skia scale down for you, you would get better results.

**Comment by HinTak** [comment]
Also 16 is likely an embedded bitmap size - ie you are reading the embedded bitmap within the font, rather than using the scalable outlines. Just a much larger value e.g. 32, then scale it to half size within the canvas.

**Comment by 18779758522** [comment]
> 16 也可能是嵌入位图大小 - 即您正在读取字体内嵌入的位图，而不是使用可缩放轮廓。只需一个大得多的值，例如 32，然后在画布内将其缩放到一半大小。

Thank you for your answer, this method may be feasible. It's strange why using Winform can draw text very clearly.

**Comment by HinTak** [comment]
Winform likely defaults to disable the use of embedded bitmaps. This is possible with freetype based renderer (skia) too, but it is not the default.

Some people like the embedded bitmaps - black is black and white is white. Some people prefer the outlines: you can gray pixels but the shapes are never distorted.

Hmm, I think it is the other way round - winforms uses the embedded bitmaps but skiasharp uses outlines. Anyway, you want to look for the embedded bitmap option or scale it yourself.

**Comment by HinTak** [comment]
Found it - you want to play with the embedded bitmap property a bit: https://learn.microsoft.com/en-us/dotnet/api/skiasharp.skfont.embeddedbitmaps?view=skiasharp-2.88#skiasharp-skfont-embeddedbitmaps - i.e. set it on if it is off, etc.

**Comment by 18779758522** [comment]
> Found it - you want to play with the embedded bitmap property a bit: https://learn.microsoft.com/en-us/dotnet/api/skiasharp.skfont.embeddedbitmaps?view=skiasharp-2.88#skiasharp-skfont-embeddedbitmaps - i.e. set it on if it is off, etc.

Wow, it's effective, the drawing effect is the same as Winform.
![WX20240712-093105](https://github.com/user-attachments/assets/304f2485-93d9-47cb-ac7a-fb4acc05915f)

using var paint = new SKPaint
```
{
        TextSize = 16,
        IsAntialias = true,
        Color = SKColors.Black,
        TextAlign = SKTextAlign.Left,
        Typeface = SkiaChinaFont.ChinaFont,
        IsEmbeddedBitmapText = true
};
```
SKPaint.IsEmbeddedBitmapText = true  Just need to set it to true here

**Comment by HinTak** [comment]
Embedded bitmap is what it is - a pixel grid of the glyph within the font. So if you specific to use it, and also disable scaling, you should get identical result with the same font, regardless of which tech you use to display the font.

**Comment by 18779758522** [comment]
close

**Comment by HinTak** [comment]
You should/could close this one too: https://github.com/mono/SkiaSharp/issues/2713
