### ISSUE TITLE
SKBitmap.Decode (SkiaSharp 1.57.0) fails for some type of images 

### ISSUE THREAD

**Issue by Brosten** [mono/SkiaSharp#280]
I'm using Montemagnos CrossMedia plugin to pick a photo from my camera roll.
Then I create a byte[] of the photo and use that byte[] to breate a SKBitmap.

var mf = await CrossMedia.Current.PickPhotoAsync();
byte[] bytes;
var s = new MemoryStream()
mf.GetStream().CopyTo(s);
mf.Dispose();
bytes = s.ToArray();
var bm = SKBitmap.Decode(bytes);

This worked perfect in version 1.56.x of SkiaSharp. (On both Android, UWP and iOS).
After updating to 1.57.0 this still works for iOS and UWP.

However, for some images, on Android, it fails with the dump shown below

This seems to be VERY dependent of witch photo I use. I took a photo with my Samsung S7. Worked fine!
Made the photo a bit brighter (in the phone) and saved a copy. The copy DOES NOT work.
Both photos work if I downgrade SkiaSharp to 1.56.x

----
Stacktrace:
at <unknown> <0xffffffff>
04-26 08:30:18.756 E/mono-rt (28205):   at (wrapper managed-to-native) SkiaSharp.SkiaApi.sk_codec_get_pixels (intptr,SkiaSharp.SKImageInfo&,intptr,intptr,SkiaSharp.SKCodecOptionsInternal&,intptr,int&) <0x00007>
04-26 08:30:18.756 E/mono-rt (28205):   at SkiaSharp.SKCodec.GetPixels (SkiaSharp.SKImageInfo,intptr,int,SkiaSharp.SKCodecOptions,intptr,int&) [0x00097] in <f4b7f147247f4a9789d4dbaebc5c8b24>:0
04-26 08:30:18.757 E/mono-rt (28205):   at SkiaSharp.SKCodec.GetPixels (SkiaSharp.SKImageInfo,intptr,int,SkiaSharp.SKCodecOptions,SkiaSharp.SKColorTable,int&) [0x00020] in <f4b7f147247f4a9789d4dbaebc5c8b24>:0
04-26 08:30:18.757 E/mono-rt (28205):   at SkiaSharp.SKCodec.GetPixels (SkiaSharp.SKImageInfo,intptr,SkiaSharp.SKColorTable,int&) [0x00012] in <f4b7f147247f4a9789d4dbaebc5c8b24>:0
04-26 08:30:18.757 E/mono-rt (28205):   at SkiaSharp.SKBitmap.Decode (SkiaSharp.SKCodec,SkiaSharp.SKImageInfo) [0x0003d] in <f4b7f147247f4a9789d4dbaebc5c8b24>:0
04-26 08:30:18.757 E/mono-rt (28205):   at SkiaSharp.SKBitmap.Decode (SkiaSharp.SKCodec) [0x00018] in <f4b7f147247f4a9789d4dbaebc5c8b24>:0
04-26 08:30:18.757 E/mono-rt (28205):   at SkiaSharp.SKBitmap.Decode (SkiaSharp.SKStream) [0x00026] in <f4b7f147247f4a9789d4dbaebc5c8b24>:0
04-26 08:30:18.757 E/mono-rt (28205):   at SkiaSharp.SKBitmap.Decode (byte[]) [0x00017] in <f4b7f147247f4a9789d4dbaebc5c8b24>:0
04-26 08:30:18.757 E/mono-rt (28205):   at Sketching.Renderer.BackgroundImageRenderer.ResizeBitmap

**Comment by mattleibow** [comment]
Are you able to attach a photo that breaks?

**Comment by Brosten** [comment]
![20170426_094017](https://cloud.githubusercontent.com/assets/10629345/25497237/34ac8f24-2b84-11e7-8a3f-115158adc949.jpg)

**Comment by Brosten** [comment]
This photo worked in its original version. The version i uploaded is slightly brightend and doesn't work. Same height/width... Both photos works well in1.56.2

**Comment by mattleibow** [comment]
I have a simple test app, but it works on both Android and iOS. Are you able to share a sample app that fails for you?

I am using a Nexus 5, so it may be that. What is your device?

[test.zip](https://github.com/mono/SkiaSharp/files/972774/test.zip)

**Comment by Brosten** [comment]
No time to share a test-app right now. Will try to fix one soon! I'm having the problem on a Samsung S7 device.

**Comment by mattleibow** [comment]
I am closing this issue as it is fairly old. Please re-open if this is still not working for you.
