### ISSUE TITLE
Xamarin forms Korean

### ISSUE THREAD

**Issue by SteaI** [mono/SkiaSharp#283]
I used on xamarin forms android, ios but couldn't drawing korean string with device default font family.
And i do not want use custom typeface.

**Comment by mattleibow** [comment]
There are two parts to this:

1. Make sure you have a typeface that has the character:
   Basically, use this to get a typeface: `SKFontManager.MatchCharacter(...)`
   https://github.com/mono/SkiaSharp/issues/232#issuecomment-277458753
2. Supporting right-to-left and top-to-bottom strings:
   See more info on issue #272

**Comment by mattleibow** [comment]
@SteaI My bad. I thought Korean was part of the RTL issue, but it appears that it was just a typeface issue. 

I think the default typefaces do not actually have any Korean characters, thus it will draw blocks. The correct way to find a typeface on the device is to use the `SKFontManager`:

```csharp
// find a typeface that has the characters
var tf = SKFontManager.Default.MatchCharacter('헬');

// create a paint
var paint = new SKPaint { Typeface = tf };

// draw the text
canvas.DrawText("헬로우 월드", ...);
```

**Comment by jys00511** [comment]
Thanks to you, I came to know how to use Hangul.
However, if you do the following, only Hangul("헬로우 월드") will be displayed("123ABC" will not be displayed).

`// find a typeface that has the characters
var tf = SKFontManager.Default.MatchCharacter('헬');

// create a paint
var paint = new SKPaint { Typeface = tf };

// draw the text
canvas.DrawText("헬로우 월드123ABC", ...);`


Is there any way to solve this?
