### ISSUE TITLE
[BUG] SKGLView on .NET MAUI is missing a handler (the return)

### ISSUE THREAD

**Issue by softlion** [mono/SkiaSharp#2838]
### Description

There is no more overload of UseSkiaSharp(true), and the handler for SKGLView is not registered anymore.

This is a regression, or is there a breaking change I missed ?

skiasharp maui 2.88.8   
my maui ios+android app is net8

I verified the source code on github, and I do see the handler being registered.

But when I decompile UseSkiaSharp with rider on get to the ios source code, there is no such registration.

Bad release ?

Should be that code instead :(

https://github.com/mono/SkiaSharp/blob/main/source/SkiaSharp.Views.Maui/SkiaSharp.Views.Maui.Controls/AppHostBuilderExtensions.cs

### Code

Decompiled 2.88.8, not same code as in https://github.com/mono/SkiaSharp/blob/main/source/SkiaSharp.Views.Maui/SkiaSharp.Views.Maui.Controls/AppHostBuilderExtensions.cs

```cs
// Decompiled with JetBrains decompiler
// Type: SkiaSharp.Views.Maui.Controls.Hosting.AppHostBuilderExtensions
// Assembly: SkiaSharp.Views.Maui.Controls, Version=2.88.0.0, Culture=neutral, PublicKeyToken=null
// MVID: 746A20A3-036F-4E0B-9FD2-26297B262D4E
// Assembly location: C:\Users\benja_lfpsq1j\.nuget\packages\skiasharp.views.maui.controls\2.88.8\lib\net6.0-ios13.6\SkiaSharp.Views.Maui.Controls.dll
// XML documentation location: C:\Users\benja_lfpsq1j\.nuget\packages\skiasharp.views.maui.controls\2.88.8\lib\net6.0-ios13.6\SkiaSharp.Views.Maui.Controls.xml

using Microsoft.Maui.Hosting;
using SkiaSharp.Views.Maui.Handlers;
using System;

#nullable enable
namespace SkiaSharp.Views.Maui.Controls.Hosting
{
  public static class AppHostBuilderExtensions
  {
    public static 
    #nullable disable
    MauiAppBuilder UseSkiaSharp(this MauiAppBuilder builder)
    {
      return builder.ConfigureMauiHandlers((Action<IMauiHandlersCollection>) (handlers => handlers.AddHandler<SKCanvasView, SKCanvasViewHandler>())).ConfigureImageSources((Action<IImageSourceServiceCollection>) (sources =>
      {
        sources.AddService<ISKImageImageSource, SKImageSourceService>();
        sources.AddService<ISKBitmapImageSource, SKImageSourceService>();
        sources.AddService<ISKPixmapImageSource, SKImageSourceService>();
        sources.AddService<ISKPictureImageSource, SKImageSourceService>();
      }));
    }
  }
}
```

### Version of SkiaSharp

Other (Please indicate in the description)

### Last Known Good Version of SkiaSharp

Other (Please indicate in the description)

### IDE / Editor

Other (Please indicate in the description)

### Platform / Operating System

Windows

### Platform / Operating System Version

- iOS + Android

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by softlion** [comment]
it looks like it's back in the preview 3 version. 

Did I dream that it was here before ? I don't think so.  
My add did work on iOS before I upgraded.

It used to be there with the `UseSkiSharp(true)` overload.

**Comment by softlion** [comment]
> .NET runtime in .NET 9.0 Preview 3 is broken since they removed some globalization code. For the time being, adding `<InvariantGlobalization>true</InvariantGlobalization>` to your project file should help.

I'm using the .NET 8 stable release, not .NET 9 previews. Does that still apply ?

**Comment by janne-hmp** [comment]
Then it may be something different. On that note, not sure if SkiaSharp 3.0 Preview 3.1 is fully compatible with .NET 8. It seems like it is being developed for .NET 9.

**Comment by softlion** [comment]
> Then it may be something different. On that note, not sure if SkiaSharp 3.0 Preview 3.1 is fully compatible with .NET 8. It seems like it is being developed for .NET 9.

Well when you develop something specifically for .net9, your tfm won't be .net7. Not sure you are right on that one.

**Comment by mattleibow** [comment]
I think the issue about the missing API is that you need to use the compatibility nuget for 2.x: https://github.com/mono/SkiaSharp/blob/release/2.x/source/SkiaSharp.Views.Maui/SkiaSharp.Views.Maui.Controls.Compatibility/AppHostBuilderExtensions.cs#L22

For 3.x, this API is no longer needed since the GL view is now part of the handlers: https://github.com/mono/SkiaSharp/blob/main/source/SkiaSharp.Views.Maui/SkiaSharp.Views.Maui.Controls/AppHostBuilderExtensions.cs#L16

**Comment by softlion** [comment]
Using 3.0.0-preview.3.1, that is finally fixed in that version.
