### ISSUE TITLE
 SKImage.Encode fails after upgrading to SkiaSharp 1.57.0

### ISSUE THREAD

**Issue by salamoun** [mono/SkiaSharp#285]
Hello,
for my Xamarin.iOS project I was using this code to save data as JPG whit SkiaSharp 1.56.2:
```
SKImage image = SKImage.FromBitmap(pageBitmap);
SKData data = image.Encode(SKImageEncodeFormat.Jpeg, 100);
```

When I upgrade to SkiaSharp 1.57.0 and update code like that:
```
SKImage image = SKImage.FromBitmap(pageBitmap);
SKData data = image.Encode(SKEncodedImageFormat.Jpeg, 100);
```

Data are always null. When I downgrade to SkiaSharp 1.56.2 it starts working again.

**Comment by salamoun** [comment]
If I call:
```
SKImage image = SKImage.FromBitmap(pageBitmap);
SKData data = image.Encode();
```

It works even with SkiaSharp 1.57.0, but image has very low quality.

**Comment by mattleibow** [comment]
I am not able to repro this one...

This is my code:

```csharp
var bitmap = new SKBitmap(new SKImageInfo(100, 100));
var image = SKImage.FromBitmap(bitmap);
var data = image.Encode(SKEncodedImageFormat.Jpeg, 100);
```

For me, `data is not `null`. However, I am using the default color type and alpha type for the bitmap. It may be the case that you are using something different. 

Are you decoding a bitmap before trying to save it? If so, your in-memory bitmap may have some unusual color type that is not supported by the JPEG encoder. When you use the parameter-less `Encode()` method, the encoder is the PNG encoder.

If this is the case, you can try decoding into a platform color type and alpha type:

```csharp
// create a codec to read the image
var codec = SKCodec.Create(...);

// create the bitmap using the dimensions in the codec
var bitmap = new SKBitmap(codec.Info.Width, codec.Info.Height);

// decode the image into the bitmap
codec.GetPixels(bitmap.Info, bitmap.GetPixels());
```

If at all possible, if this doesn't help, could you attach the image that you are possibly decoding or some sample code that I could run and see what is up?

**Comment by daniel-luberda** [comment]
The same issue here. Somehow only parameterless method override works correctly in the newest SkiaSharp release.

If you want a working reproduction see this: https://github.com/luberda-molinet/FFImageLoading/blob/master/source/FFImageLoading.Svg.Shared/SvgDataResolver.cs#L148-L149

You can run `ImageLoading.Forms.Sample` sample and choose `SVG example` in a demo list.

**Comment by mattleibow** [comment]
@daniel-luberda Thanks for the repro.

I have managed to find out why things are breaking. Basically with v1.56, `SKImage.Encode` accepted a value of `SKImageEncodeFormat.Png` which had an integer value of `5`. And, then Google went and changed code and now that method does not take that value anymore (they actually removed that type entirely). Now, it takes `SKEncodedImageFormat.Png` which has an integer value of `4`.

I added a mapping function, but I made the mistake of not checking the values:
https://github.com/mono/SkiaSharp/blob/v1.57.1/binding/Binding/SKImage.cs#L14-L24

Release Notes:
https://github.com/mono/SkiaSharp/releases/tag/v1.57.0

I will see about getting a fix out ASAP.

Typically, SkiaSharp is not backwards compatible as I have no control over the API, which is quite fluid. I am working on an update to v1.58, and they have gone and removed a few more types. Thankfully they are not too big, but still annoying. Their reasoning is that it is not used by Chrome and Android, thus not needed.

**Comment by mattleibow** [comment]
@daniel-luberda You can work around this by making sure that you are building against v1.57.0 with all your libraries. Currently you have these three projects still using the old version:

https://github.com/luberda-molinet/FFImageLoading/search?l=XML&q=1.56.1&type=&utf8=%E2%9C%93

**Comment by daniel-luberda** [comment]
@mattleibow Thanks for the info! I suppose that was quite difficult to debug. 

> You can work around this by making sure that you are building against v1.57.0 with all your libraries. 

The workaround I used is to simply use parameterless method override, it works fine. It encodes as PNG by default anyway. I also updated dependencies to `1.57` in the newest prerelease, so it should work now :)

**Comment by salamoun** [comment]
@mattleibow @daniel-luberda  Thanks, for greate support.
