### ISSUE TITLE
[BUG] Horizontal lines disappear when zoomed in

### ISSUE THREAD

**Issue by afcsoft** [mono/SkiaSharp#2856]
### Description

![resim](https://github.com/mono/SkiaSharp/assets/49344491/a8d3d175-f609-40ed-9406-c4a07dcd0b06)
![resim](https://github.com/mono/SkiaSharp/assets/49344491/6b456c32-ddd5-4662-8a6a-a9a0dd386e22)
Horizontal lines disappear when zoomed in using Matrix. 
Stroke width is irrelevant. Anti-aliasing helps to some extent but problem still pursue.

### Code

```cs
// Matrix code
        var zoom = (float)skiaRenderer.Viewport.SceneZ;
        var dpi = 1.5f;

        var drawMatrix = SKMatrix.CreateScale((float)zoom, -(float)zoom);

        var halfScaledWidth = (float)canvas.ActualWidth * 0.5f;
        var halfScaledHeight = (float)canvas.ActualHeight * 0.5f;

        var actualX = -(float)skiaRenderer.Viewport.SceneX * zoom + (halfScaledWidth * dpi);
        var actualY = (float)skiaRenderer.Viewport.SceneY * zoom + (halfScaledHeight * dpi);

        drawMatrix.TransX = actualX;
        drawMatrix.TransY = actualY;

        e.Surface.Canvas.SetMatrix(drawMatrix);      
// Line drawing code
_paint.Color.WithAlpha(255);
_paint.IsAntialias = true;
_paint.StrokeWidth = (float)(1.5 / _viewport.SceneZ);
_paint.StrokeCap = SKStrokeCap.Round;
_paint.IsStroke = true;
surface.Canvas.DrawLine((float)line.Object.Coor.Y, (float)line.Object.Coor.X, (float)line.Coord.Y, (float)line.Coord.X, _paint);
```

### Version of SkiaSharp

2.88.3 (Current)

### Last Known Good Version of SkiaSharp

Other (Please indicate in the description)

### IDE / Editor

Visual Studio (Windows)

### Platform / Operating System

All

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by angelofb** [comment]
I have the same problem

if you can use 1 pixel width stroke then you can set hairline mode with StrokeWidth = 0
https://learn.microsoft.com/en-us/dotnet/api/skiasharp.skpaint.strokewidth?view=skiasharp-2.88#remarks

**Comment by mattleibow** [comment]
I think this will need a sample. It can just be a simple drawing of a line and "zooming" with a slider or something.

There may be things you can do with the hairline if the line gets too thin (like @angelofb says) or make sure your values are not in some weird decimal value (like @taublast says).

But, if you can capture the values when they disappear, then we can also see.

Also, try the 3.x releases and see if the new Skia engine has any bug fixes. However, this is more likely you have a 0.1px line at a 0.3px offset with a scale of 1.05% or something.

**Comment by IUDaria** [comment]
I have the same issue using `ImageSVG` and making transformations with `transform` in parent group.
