### ISSUE TITLE
[BUG] (preview-3.1) SKCanvas.TotalMatrix has (TransX, TransY) swapped with (Persp0, Persp1)

### ISSUE THREAD

**Issue by martinaxure** [mono/SkiaSharp#2868]
### Description

In preview-3.1, `SKCanvas.TotalMatrix` is not returning the correct value. 

I have to run the following to fix the value:
```cs
(matrix.TransX, matrix.TransY) = (matrix.Persp0, matrix.Persp1);
(matrix.Persp0, matrix.Persp1) = (0f, 0f);
```

### Code

If you run the following code:

```cs
Canvas.Save();
Canvas.ResetMatrix();
Console.WriteLine($"BEFORE Canvas.TotalMatrix = {Canvas.TotalMatrix.Values.Select(x => x.ToString()).Join(", ")}");
Canvas.Translate(100, 100);
Console.WriteLine($"AFTER Canvas.TotalMatrix = {Canvas.TotalMatrix.Values.Select(x => x.ToString()).Join(", ")}");
Canvas.Restore();
```

It prints:
```
BEFORE Canvas.TotalMatrix = 1, 0, 0, 0, 1, 0, 0, 0, 1
AFTER Canvas.TotalMatrix = 1, 0, 0, 0, 1, 0, 100, 100, 1
```

The docs for SKMatrix.Values
```
Gets or sets the matrix as a flat array: [ScaleX, SkewX, TransX, SkewY, ScaleY, TransY, Persp0, Persp1, Persp2].
```

so `Persp0` and `Persp1` have the values for `TransX` and `TransY` In previous versions (preview-2.1 and below), it would print:

```
BEFORE Canvas.TotalMatrix = 1, 0, 0, 0, 1, 0, 0, 0, 1
AFTER Canvas.TotalMatrix = 1, 0, 100, 0, 1, 100, 0, 0, 1
```

### Version of SkiaSharp

3.x (Alpha)

### Last Known Good Version of SkiaSharp

Other (Please indicate in the description)

### IDE / Editor

Other (Please indicate in the description)

### Platform / Operating System

Other (Please indicate in the description)

### Platform / Operating System Version

Brave [Version 1.65.126 Chromium: 124.0.6367.118 (Official Build) (arm64)]
Observed on MacOS

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by martinaxure** [comment]
I think the bug was from this pull request:
https://github.com/mono/SkiaSharp/pull/2780/files

**Comment by mattleibow** [comment]
I am not able to repro:

[TestingApp.zip](https://github.com/user-attachments/files/15516037/TestingApp.zip)

```
BEFORE Canvas.TotalMatrix = 1, 0, 0, 0, 1, 0, 0, 0, 1
AFTER Canvas.TotalMatrix = 1, 0, 100, 0, 1, 100, 0, 0, 1
```

**Comment by mattleibow** [comment]
Maybe attach a sample that repro's the issue?

**Comment by martinaxure** [comment]
I'm going to mark this as closed. I was never able to repro this in anything but our codebase, but preview-4.1 has seemingly fixed the issue. Thanks!
