### ISSUE TITLE
The type initializer for 'SkiaSharp.SKManagedStream' threw an exception.

### ISSUE THREAD

**Issue by AwsomeCode** [mono/SkiaSharp#287]
I am trying to convert stream to SKManagedStream. In one pc its working find and in another pc its giving below exception for same image. I am using same code and same package of skiasharp(1.57.0) on both the pc 

Code....
```csharp
public static Stream ResizeImage(Stream imageStream, int mySize, int myQuality = 75)
        {
            int size = mySize;
            int quality = myQuality;
            imageStream.Position = 0;
            using (var inputStream = new SKManagedStream(imageStream))
            { 
                //SomeCode....
            }
}
```
Exception....
```
System.TypeInitializationException occurred
  HResult=0x80131534
  Message=The type initializer for 'SkiaSharp.SKManagedStream' threw an exception.
  Source=SkiaSharp
  StackTrace:
   at SkiaSharp.SKManagedStream..ctor(Stream managedStream)
   at ImageUploadOWIN.Controllers.ImageUploadController.ResizeImage(Stream imageStream, Int32 mySize, Int32 myQuality) in Controllers\ImageUploadController.cs:line 271

Inner Exception 1:
BadImageFormatException: An attempt was made to load a program with an incorrect format. (Exception from HRESULT: 0x8007000B)
```

**Comment by AwsomeCode** [comment]
List of packages.

<package id="Microsoft.AspNet.WebApi.Client" version="5.2.3" targetFramework="net452" />
  <package id="Microsoft.AspNet.WebApi.Core" version="5.2.3" targetFramework="net452" />
  <package id="Microsoft.AspNet.WebApi.Owin" version="5.2.3" targetFramework="net452" />
  <package id="Microsoft.CodeAnalysis.Analyzers" version="1.1.0" targetFramework="net452" />
  <package id="Microsoft.CodeAnalysis.Common" version="1.3.2" targetFramework="net452" />
  <package id="Microsoft.CodeAnalysis.CSharp" version="1.3.2" targetFramework="net452" />
  <package id="Microsoft.CodeDom.Providers.DotNetCompilerPlatform" version="1.0.3" targetFramework="net452" />
  <package id="Microsoft.Net.Compilers" version="1.3.2" targetFramework="net452" developmentDependency="true" />
  <package id="Microsoft.Owin" version="3.0.1" targetFramework="net452" />
  <package id="Microsoft.Owin.Host.SystemWeb" version="3.0.1" targetFramework="net452" />
  <package id="MongoDB.Bson" version="2.4.3" targetFramework="net452" />
  <package id="MongoDB.Driver" version="2.4.3" targetFramework="net452" />
  <package id="MongoDB.Driver.Core" version="2.4.3" targetFramework="net452" />
  <package id="MongoDB.Driver.GridFS" version="2.4.3" targetFramework="net452" />
  <package id="Newtonsoft.Json" version="9.0.1" targetFramework="net452" />
  <package id="Owin" version="1.0" targetFramework="net452" />
  <package id="SkiaSharp" version="1.57.0" targetFramework="net452" />
  <package id="System.Collections" version="4.3.0" targetFramework="net452" />
  <package id="System.Collections.Immutable" version="1.3.1" targetFramework="net452" />
  <package id="System.Diagnostics.Debug" version="4.3.0" targetFramework="net452" />
  <package id="System.Globalization" version="4.3.0" targetFramework="net452" />
  <package id="System.Linq" version="4.3.0" targetFramework="net452" />
  <package id="System.Reflection.Metadata" version="1.4.2" targetFramework="net452" />
  <package id="System.Resources.ResourceManager" version="4.3.0" targetFramework="net452" />
  <package id="System.Runtime" version="4.3.0" targetFramework="net452" />
  <package id="System.Runtime.Extensions" version="4.3.0" targetFramework="net452" />
  <package id="System.Runtime.InteropServices.RuntimeInformation" version="4.3.0" targetFramework="net452" />
  <package id="System.Threading" version="4.3.0" targetFramework="net452" />

**Comment by mattleibow** [comment]
This appears to be an issue with your compiler architecture... "An attempt was made to load a program with an incorrect format."

I am assuming you are running Windows as this is where this type of error usually occurs.

Are you building for x86, x64 or Any CPU? Is this .NET Core or Full .NET Framework? One machine may be running an x86 OS and the other a x64 OS. Because we are using a native library, you may need to build for each architecture separately. If you are building for Any CPU, both platform native files will be copied into the output directory, as well as the current platform in the bin. If you are running on a specific architecture, you can just copy the required native file out of the sub folder into the bin.

**Comment by AwsomeCode** [comment]
Hi @mattleibow ,

I am running on Full .NET Framework with Any CPU. Both the machine running on X64 Windows 10 OS.
Both have native file for each CPU architecture in separate folder and X64 one in bin folder.

The only difference is working one is running on IIS 8 on Xeon Processor. Non working on is using IIS express on Core I7 in debug mode.

I have made simple console application on core i7 Full .NET Framework with Any CPU its working fine.

**Comment by AwsomeCode** [comment]
Its working after changing from x86 to x64. Thanks.

**Comment by mattleibow** [comment]
The build should work for the machine that it is building on (and from the IDE). but as soon as you change it, there is no way for the build to know.

The reason for the two "x86" and "x64" folders is that depending on the destination architecture, you are supposed to copy the contents out of the sub folder and next to the main exe.
