### ISSUE TITLE
Net 7.0 FastReport SkiaSharp

### ISSUE THREAD

**Issue by tiagovbp** [mono/SkiaSharp#2892]
### Description

I have a net 7.0 application and I'm trying to implement FastReports with Docker for Linux.

There is a problem when reporting.Prepare();

{
  "status": 500,
  "message": "Exception in BuildFontRuns() with original length 35 now 35, style run count 1, font run count 0, direction substitutions: False -> Value cannot be null. (Parameter 'asset ')"
}

### Code

The best way to share code for larger projects is a link to a GitHub repository: https://github.com/user/repo/tree/bug-123

But, you can also share a short block of code here:
```cs
// some C# code here
```
You can also share some XAML:
```xaml
<!-- xaml code here -->
```

### Version of SkiaSharp

2.88.3 (Current)

### Last Known Good Version of SkiaSharp

2.88.2 (Previous)

### IDE / Editor

Visual Studio (Windows)

### Platform / Operating System

Linux

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mattleibow** [comment]
This should like an issue with FastReports. Please open an issue with them.

**Comment by tiagovbp** [comment]
After uninstalling SkiaSharp, the following error occurs:

"message": "Exception was thrown by the target of an invocation. -> The type initializer for 'System.Drawing.FontFamily' threw an exception. -> The type initializer for 'SkiaSharp.SKFontManager' threw an exception. -> Unable to load shared library 'libSkiaSharp' or one of its dependencies. To help diagnose loading issues, consider using a tool like strace. If you are using glibc, consider setting the LD_DEBUG: \n/app/ environment variable. bin/. NETCore.App/7.0.20/ libSkiaSharp.so: cannot open shared object file: no such file or directory\n/app/bin/Debug/net7.0/libSkiaSharp.so: cannot open shared object file: no such file or directory does not exist\n/usr/share/dotnet/shared/Microsoft.NETCore.App/7.0.20/ liblibSkiaSharp.so: cannot open shared object file: no such file or directory\n/app/bin/ Debug/net7.0/liblibSkiaSharp.so: cannot open shared object file: no such file or directory\n/app/bin/ Debug/net7.0/runtimes/linux-x64/native/libSkiaSharp: no Can't open shared object file: No such file or directory or directory does not exist\n/app/bin/Debug/net7.0/libSkiaSharp: cannot open shared object file: no such file or directory\n/app/bin/Debug/net7.0/runtimes/ linux-x64/native/liblibSkiaSharp: cannot open shared object file: no such file or directory\n/usr/share/dotnet/shared/Microsoft.NETCore.App/7.0.20/liblibSkiaSharp: cannot open shared object file: No such file or directory\n/app/bin/Debug/net7.0/liblibSkiaSharp: Unable to open shared object file: No such file or directory\n"
}
