### ISSUE TITLE
[BUG] (preview3.1) Access violation when a `Clone`d `SKPaint` is disposed/finalized

### ISSUE THREAD

**Issue by chersoft-oliverb** [mono/SkiaSharp#2899]
### Description

`AccessViolationException` is thrown from the finalizer thread during `DisposeNative()` of an `SKPaint` that is created using the `Clone()` method. This happens whether or not the user actually disposes of the cloned paint themselves.

I notice that `SKPaint.Clone` calls `sk_paint_clone` not `sk_compatpaint_clone`
https://github.com/mono/SkiaSharp/blob/5b31788346b54b3e12a13eec38241b04de1af85c/binding/SkiaSharp/SKPaint.cs#L279-L280

though DisposeNative calls `sk_compatpaint_delete`
https://github.com/mono/SkiaSharp/blob/5b31788346b54b3e12a13eec38241b04de1af85c/binding/SkiaSharp/SKPaint.cs#L72-L73

Maybe related to #2821 or #2794?

### Code

This provokes the crash at about `i`=2

```cs
using var paint = new SKPaint { Color = SKColors.Red, Style = SKPaintStyle.Stroke, StrokeWidth = 1f };

for (int i = 0; i < 512; i++)
{
	using var clonedPaint = paint.Clone(); // Even making this a 'using var' doesn't help

	GC.Collect();
	GC.WaitForPendingFinalizers();
}
```

### Expected Behavior

Probably the finalizer shouldn't get called at all if we disposed it ourselves.
And it definitely shouldn't crash 😅

### Actual Behavior

Process crashes with AccessViolationException

### Version of SkiaSharp

3.x (Alpha)

### Last Known Good Version of SkiaSharp

2.88.2 (Previous)

### IDE / Editor

Visual Studio (Windows)

### Platform / Operating System

Windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jeremy-visionaid** [comment]
I'm also seeing this, might have a stab at a fix if/when I get the chance if someone else doesn't get there first!
