### ISSUE TITLE
Is drawing a SKBitmap in a SKGLView not supported?

### ISSUE THREAD

**Issue by typehm** [mono/SkiaSharp#291]
I try to decode animated WebP file and draw it to canvas, it works, but pretty slow. 
So I think I should use hardware acceleration. When I try to drawing SKBitmap with SKGLView, nothing happened, can't see anything in the view.

**Comment by DeanClaes** [comment]
Hello,

Have you tried calling NotifyPixelsChanged() on the SKBitmap?

**Comment by typehm** [comment]
Hello DeanClaes,
I try to called NotifyPixelsChanged() on the SKBitmap with you answer, but not helps.
Thanks for your reply.

**Comment by typehm** [comment]
Solved. Change bitmap format from BGRA8888 to RGBA8888 will work properly.

**Comment by mattleibow** [comment]
@typehm As the color format changes on each platform, you may want to use the `SKImageInfo.PlatformColorType`. On each platform, the color type will be the correct type that the various bitmaps and surfaces can work best with.

https://developer.xamarin.com/api/field/SkiaSharp.SKImageInfo.PlatformColorType
