### ISSUE TITLE
[BUG] "Handler not found for view SkiaSharp.Views.Maui.Controls.SKGLView."[BUG] <title>

### ISSUE THREAD

**Issue by NastyaZorro169** [mono/SkiaSharp#2910]
### Description

Good afternoon
When the application starts, it gives this error, although I did all the tips that were found, which may not be the case
Microsoft.Maui.Platform.HandlerNotFoundException: 'Handler not found for view SkiaSharp.Views.Maui.Controls.SKGLView
There is a line in MauiProgram .UseSkiaSharp() added
Version SkiaSharp.Views.Maui.Controls 2.88.8

### Code

XAML:
```xaml
<ContentPage xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             xmlns:skia="clr-namespace:SkiaSharp.Views.Maui.Controls;assembly=SkiaSharp.Views.Maui.Controls"
             NavigationPage.HasBackButton="True">
<ContentPage.Content>
    <Grid  RowSpacing="0">
        <Grid.RowDefinitions>
            <RowDefinition Height="*"/>
            <RowDefinition Height="168"/>
        </Grid.RowDefinitions>
        <skia:SKGLView 
            Grid.Row="0"
            x:Name="openGLView" 
            Margin="0, -1, 0, 0"
            HasRenderLoop="true" 
            HorizontalOptions="FillAndExpand" 
            VerticalOptions="FillAndExpand" />
        </Grid>
    </ContentPage.Content>
</ContentPage>
```

### Version of SkiaSharp

Other (Please indicate in the description)

### Last Known Good Version of SkiaSharp

Other (Please indicate in the description)

### IDE / Editor

Visual Studio (Windows)

### Platform / Operating System

Android, iOS

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by TommiGustafsson-HMP** [comment]
Is this on Android and iOS? Or on Windows?

**Comment by NastyaZorro169** [comment]
Android и iOS

> Это на Android и iOS? Или на Windows?

**Comment by TommiGustafsson-HMP** [comment]
Please try 3.0-preview3.1.
