### ISSUE TITLE
[BUG] .Net MAUI SKCanvasView memory leak on IOS

### ISSUE THREAD

**Issue by nevse** [mono/SkiaSharp#2923]
### Description

If you place SKCanvasView on Page it cause a memory leak. 

### Code

I create a simple app wich reproduce this leak https://github.com/nevse/maui-tests-SKCanvasViewLeak

Step to reproduce:
1. Click button "Open Page"
2. Navigate back from page with SKCanvasView
3. Click button "Check Memory Leak"

I use such code to detect memory leak:
```cs
WeakReference pageRef;
void OnOpenPage(object sender, EventArgs e)
{
    var page = new SKCanvasViewPage();
    Navigation.PushAsync(page);
    pageRef = new WeakReference(page);
}
void OnCheckMemoryLeak(object sender, EventArgs e)
{
    GC.Collect();
    GC.WaitForPendingFinalizers();
    GC.Collect();
    if (pageRef != null && pageRef.IsAlive)
    {
        DisplayAlert("Memory Leak", "Memory Leak Detected", "OK");
    }
    else
    {
        DisplayAlert("Memory Leak", "No Memory Leak Detected", "OK");
    }
}
```

### Version of SkiaSharp

2.88.3 (Current)

### Last Known Good Version of SkiaSharp

Other (Please indicate in the description)

### IDE / Editor

Visual Studio Code (macOS)

### Platform / Operating System

iOS

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Alexgoon** [comment]
Some DevExpress components have a memory leak due to this issue, which prevents the entire page from being released. This problem is affecting many of our customers. @mattleibow, could you please take a look at this when you have a chance?

**Comment by janne-hmp** [comment]
I just made a test app (see #2951) that confirms this by crashing my iPad by trying to open and close the same page 500 times. It crashes after opening the page c. 145th time.

**Comment by mattleibow** [comment]
I think I know what is happening. After all our work to fix leaks in Maui itself, it appears that an event on the platform view to the handler keeps everything.

The platform view event keeps the handler alive, the handler keeps the Xaml view alive and the xaml view keeps the parent alive. The virtual view also keeps the handler alive and the handler keeps the platform view. So basically a big web of survival. 

However, there has also been a fix in Maui to break the virtual view and it's parent: https://github.com/dotnet/maui/pull/22561

We just have to do something like this: https://github.com/dotnet/maui/pull/18682

Thanks to the hard work of @jonathanpeppers ❤️

**Comment by jonathanpeppers** [comment]
If some `SKSomethingView` has a circular reference, I don't think https://github.com/dotnet/maui/pull/22561 will fix it.

Do you have any on-device tests, can you write one like:

* https://github.com/dotnet/maui/blob/9251b38bd58921df21ebcf67d84a539e39b74d5c/src/Controls/tests/DeviceTests/Memory/MemoryTests.cs#L166

And then, the solution would be to fix some of the warnings this analyzer catches:

* https://github.com/jonathanpeppers/memory-analyzers
