### ISSUE TITLE
[Question] Can we use Xamarin SkiaSharp for cross platform desktop form development in .NET Core?

### ISSUE THREAD

**Issue by HamedFathi** [mono/SkiaSharp#296]
I want to know Can we use SkiaSharp for cross platform desktop form development like windows forms development but for cross platform purposes ?

something like wxWidgets in C++ Can we use SkiaSharp in .NET Core for desktop development ?

Can we have forms,controls and ... by SkiaSharp ?

Is SkiaSharp could be an alternative to the Windows Forms but in cross platforms ?

**Comment by wieslawsoltes** [comment]
@HamedFathi Take a look at Avalonia https://github.com/AvaloniaUI/Avalonia, its using SkiaSharp for rendering and has WPF like XAML for UI.

**Comment by mattleibow** [comment]
SkiaSharp is more of a drawing engine - for example it is a cross-platform version of System.Drawing or CoreGraphics.

Avalonia is a really cool example of an advanced framework that _uses_ SkiaSharp to draw the controls.
