### ISSUE TITLE
[BUG] [Windows, MAUI] SkiaSharp 3.0-Preview4.1 causes an image to be drawn in a wrong size for some first frames on some high DPI screens (works on 3.0-preview3.1)

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [mono/SkiaSharp#2960]
### Description

On the Windows platform, using .NET MAUI 9.0 Preview 6, SkiaSharp 3.0-preview4.1 has introduced a regression from preview3.1 where SkiaSharp draws images at a wrong size for a few first frames on some high DPI screens.

#### Screenshots
Please have a look at these screenshots:

##### SkiaSharp 3.0-preview4.1

![vlcsnap-2024-07-29-15h14m04s764](https://github.com/user-attachments/assets/5725ea6d-94a8-48ae-b31e-55cc29c0fc05)

##### SkiaSharp 3.0-preview3.1

![vlcsnap-2024-07-29-15h25m38s106](https://github.com/user-attachments/assets/b0f2f817-de55-47ce-af00-20e0c201f855)

#### Videos

Please have a look at the following videos:

##### SkiaSharp 3.0-preview4.1

https://github.com/user-attachments/assets/2d2004de-322e-4573-ae9f-06a42e26536a

1. Download the video.
2. Open the video with VLC Media Player.
3. Move to a place where a window with SkiaSharp background (a scroll) is about to be shown.
4. Press E (move forward one frame) until you see a frame where the background is too small.

##### SkiaSharp 3.0-preview3.1

https://github.com/user-attachments/assets/e245042f-494a-4f33-b3c0-c0fb783b68d6

1. Download the video.
2. Open the video with VLC Media Player.
3. Move to a place where a window with SkiaSharp background (a scroll) is about to be shown.
4. Press E (move forward one frame) until you see the first frame rendered with a scroll background. The scroll is of the right size.

### Public reproduction repository

Download a public reproduction repository (.NET MAUI 9.0 Preview 6 with SkiaSharp 3.0-preview 4.1). This will do:
https://github.com/hyvanmielenpelit/iOSMauiSkiaSharpMemoryLeak

### Expected Behavior

SkiaSharp will draw all frames in the right size on all high DPI screens. (I have 200% scaling.)

### Actual Behavior

SkiaSharp draws some first frames in a wrong size on all high DPI screens. (I have 200% scaling.)

### Version of SkiaSharp

Other (Please indicate in the description)

### Last Known Good Version of SkiaSharp

Other (Please indicate in the description)

### IDE / Editor

Visual Studio (Windows)

### Platform / Operating System

Windows

### Platform / Operating System Version

Processor:	13th Gen Intel(R) Core(TM) i9-13980HX   2.20 GHz
Installed RAM:	32,0 GB (31,6 GB usable)
System type:	64-bit operating system, x64-based processor
Edition:	Windows 11 Pro
Version:	23H2
OS build:	22631.3958
Experience:	Windows Feature Experience Pack 1000.22700.1026.0

#### Display

![image](https://github.com/user-attachments/assets/5e67fc04-17c3-4fe6-9ceb-04c597409c28)

![image](https://github.com/user-attachments/assets/1f421cac-6b95-473e-b12a-9943d809dc8c)

##### Integrated
![image](https://github.com/user-attachments/assets/e8a0e4fa-d2eb-4c0d-951d-9ab0123abac9)

##### Dedicated
![image](https://github.com/user-attachments/assets/bf29cae8-def7-4c49-8b8f-027e0475f4cd)

### Devices

Asus ProArt Studiobook H7604JV

#### From public reproduction repository
![vlcsnap-2024-07-29-15h14m04s764](https://github.com/user-attachments/assets/5725ea6d-94a8-48ae-b31e-55cc29c0fc05)

#### From GnollHack
I have also a screenshot from our game GnollHack about the problem:

![vlcsnap-2024-07-29-13h09m04s873](https://github.com/user-attachments/assets/db469a89-e4b3-482f-b31a-c4d40c1d5351)

https://github.com/hyvanmielenpelit/GnollHack

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by janne-hmp** [comment]
We should check this with .NET MAUI 9.0 RC2 and SkiaSharp 3.0 Preview 5.4 and see if either one has fixed the problem.

**Comment by TommiGustafsson-HMP** [comment]
It seems that SkiaSharp 3.0 Preview 5.4 has fixed this problem, or it happens very rarely.
