### ISSUE TITLE
Use LibraryImport instead of DllImport on net7+ for better performance

### ISSUE THREAD

**Issue by Youssef1313** [mono/SkiaSharp#2964]
### Is your feature request related to a problem?

Performance

### Describe the solution you would like

Update SkiaSharpGenerator to use LibraryImport when possible, e.g:

```csharp
					writer.WriteLine($"\t\t#if NET7_0_OR_GREATER");
					writer.WriteLine($"\t\t[LibraryImport ({config.DllName})]");
					writer.WriteLine($"\t\t#else");
					writer.WriteLine($"\t\t[DllImport ({config.DllName}, CallingConvention = CallingConvention.Cdecl)]");
					writer.WriteLine($"\t\t#endif");
```

(Not sure if it will be that trivial)

### Describe alternatives you have considered

N/A

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Gillibald** [comment]
https://github.com/mono/SkiaSharp/pull/2917

**Comment by Youssef1313** [comment]
Thanks. Closing as a duplicate of https://github.com/mono/SkiaSharp/issues/2615 then
