### ISSUE TITLE
MeasureText in samples seems not to work with zoom on Android emulator

### ISSUE THREAD

**Issue by blazespinnaker** [mono/SkiaSharp#297]
https://us.v-cdn.net/5019960/uploads/editor/3j/tsd7ktfjdfdc.png
https://us.v-cdn.net/5019960/uploads/editor/og/d8et3k89rfl6.png

All I did was edit the MeasureTextSample.cs to add 

public const string TEXT = "This is a longer text string to measure Skia (UTF-8)";

and set the various text strings to TEXT rather than "Skia (UTF-8)";

I then ran the project and did used the emulator in  zoom in / out function.   I am using Visual Studio 17.  I used VisualStudio_android-23_x86_tablet (Android 6.0 - API 23)

I haven't tested this on a device as I do not have one.

Is this expected?

**Comment by mattleibow** [comment]
I have not seen that yet. I tried with a device, the VS emulators as well as the Google emulators. I am assuming the zoom you are talking about is the magnifying glass button on the panel next to the emulator window?

I have a simple sample that just draws and measures text. Can you try that and see what happens?

[AndroidSkiaSharp.zip](https://github.com/mono/SkiaSharp/files/1002873/AndroidSkiaSharp.zip)

**Comment by blazespinnaker** [comment]
I'm actually referring to using the mouse button and dragging it in the emulator.   It creates a pinch zoom effect.   I discovered it because it seemed like the font seemed to be awkwardly shifting in size relative to the boundary box as I was pinch/zooming.  The effect seems a bit haphazard compare to other apps I use.   I experimented further and found you have to carefully zoom in/out to find the extreme examples I listed above.   I don't have access to VS right now, but will try tomorrow when I get some time.

**Comment by mattleibow** [comment]
Is this still an issue? I was not able to repro.

**Comment by Redth** [comment]
We are closing this issue since no response was received.  Please open a new issue referring to this one if you have more information.
