### ISSUE TITLE
the drawText() method ,does it support the text parameter is chinese?

### ISSUE THREAD

**Issue by xiangzLL** [mono/SkiaSharp#298]

**Comment by mattleibow** [comment]
It should. You may have to select a typeface that has the characters and make sure the encoding is correct.

Here are few samples that draw non-English characters:
https://github.com/mono/SkiaSharp/blob/master/samples/SkiaSharpSample.Shared/Samples/UnicodeTextSample.cs
https://github.com/mono/SkiaSharp/blob/master/samples/SkiaSharpSample.Shared/Samples/TextShapingSample.cs

Let me know if you are having a specific problem, or if this helps.

**Comment by baskren** [comment]
Hi @mattleibow .  Where can we find the above samples these days?

**Comment by mattleibow** [comment]
This was moved to a new folder for long paths on Windows...

 - https://github.com/mono/SkiaSharp/blob/master/samples/Gallery/Shared/Samples/UnicodeTextSample.cs
 - https://github.com/mono/SkiaSharp/blob/master/samples/Gallery/Shared/Samples/TextShapingSample.cs

**Comment by mattleibow** [comment]
I am adding a few more APIs in the v1.68.x releases to make this whole process easier. Still not yet a full text shaper with arbitrary text, but this will make things easier.
