### ISSUE TITLE
Color mismatched on Android in Xamarin.Forms

### ISSUE THREAD

**Issue by yinyue200** [mono/SkiaSharp#299]
If I follow [Creating A Splash Screen In Xamarin Forms](https://xamarinhelp.com/creating-splash-screen-xamarin-forms/) >Creating A Splash Screen Android>Better Approach ,the content in SKGLView's color will be mismatched

demo: https://github.com/moespirit/skiademo

![tim20170521164731](https://cloud.githubusercontent.com/assets/13848771/26282519/7eb2eb8a-3e45-11e7-8b9e-fc798a65dc3c.png)

English is not my native language; please excuse typing errors.
Thanks

**Comment by mattleibow** [comment]
I had a look at this, and I can repro this in your sample. However, this may be a Xamarin.Forms or most probably an Android bug. 

I have re-attached your sample, but this time using the Xamarin.Forms `OpenGLView` instead:
[Archive.zip](https://github.com/mono/SkiaSharp/files/1020302/Archive.zip)

The same thing occurs. When I "disabled" the splash screen style, the problem went away. This may have to do with either Xamarin.Forms or the way Android works with OpenGL.

It might be better to ask on the forums.

**Comment by yinyue200** [comment]
@mattleibow Thanks

**Comment by mattleibow** [comment]
I will close this issue as it appears to be a issue relating to Xamarin.Forms and OpenGL. If you have created a new issue somewhere, feel free to link that here.

**Comment by mattleibow** [comment]
I found the issue to the problem. There is a specific attribute that is set in the splash screen style, but is not unset (for some reason) when the style is changed.

In the `splashscreen` style, note this:

```xml
<item name="android:backgroundDimEnabled">true</item>
```
Docs: https://developer.xamarin.com/api/field/Android.Resource+Attribute.BackgroundDimEnabled/

This is not unset when the style is switched. So, to fix this, just set it to false:

```xml
<item name="android:backgroundDimEnabled">false</item>
```

Here is a repository that demonstrates this: https://github.com/mattleibow/AndroidGLSurfaceViewTests
