### ISSUE TITLE
[BUG] letter-spacing not recognized

### ISSUE THREAD

**Issue by scottmrox** [mono/SkiaSharp#3008]
### Description

I have an SVG with the css style letter-spacing.  This style is not recognized. The png is produced, but without the correct spacing.

### Code

The best way to share code for larger projects is a link to a GitHub repository: https://github.com/user/repo/tree/bug-123

But, you can also share a short block of code here:
```cs
// some C# code here
```
You can also share some XAML:
```xaml
<!-- xaml code here -->
```

### Expected Behavior

I expected to see the png match the SVG.

### Version of SkiaSharp

2.88.3 (Current)

### Last Known Good Version of SkiaSharp

2.88.2 (Previous)

### IDE / Editor

Visual Studio (Windows)

### Platform / Operating System

All

### Platform / Operating System Version

Windows 11
Linux

### Devices

Windows 11 laptop

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by taublast** [comment]
What library are you using, can you share your code? Are you using `Svg.Skia` library or plain `SkiaSharp`?

This link is not working https://github.com/user/repo/tree/bug-123
