### ISSUE TITLE
After latest Xamarin.Forms update, SkiaSharp will not install.

### ISSUE THREAD

**Issue by PatrickRyder** [mono/SkiaSharp#301]
I have just been forced to get the latest Xamarin extension inside Visual Studio 2015 and also updated Xamarin.Forms via nugget to V 2.3.4.247.  I tried to update SkiaSharp to 1.58.0 at the same time but this now fails.  Trying to go back to 1.57.1 also now fails with the same error message:

Package 'SkiaSharp.Views.1.57.1 : SkiaSharp [1.57.1, )' does not exist in folder 'D:\Data\Work\Dev\Projects\Live\MyProject\packages'
Could not install package 'SkiaSharp.Views 1.57.1'. You are trying to install this package into a project that targets '.NETPortable,Version=v4.5,Profile=Profile111', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

As things stand, this is a show-stopper, so I'd be very grateful for a workaround or fix.

**Comment by mattleibow** [comment]
Unfortunately, I am unable to reproduce this.

I created a new portable project and made sure that it was Profile111. Then I installed both v1.57.1 and v1.58 without any issues.

If you do a new project and install that, does it work? Also, if you uninstall SkiaSharp and then re-install it, does it still give the same error?

Here is my log:
```
Attempting to gather dependency information for package 'SkiaSharp.1.57.1' with respect to project 'ClassLibrary1', targeting '.NETPortable,Version=v4.5,Profile=Profile111'
Gathering dependency information took 2.08 sec
Attempting to resolve dependencies for package 'SkiaSharp.1.57.1' with DependencyBehavior 'Lowest'
Resolving dependency information took 0 ms
Resolving actions to install package 'SkiaSharp.1.57.1'
Resolved actions to install package 'SkiaSharp.1.57.1'
Retrieving package 'SkiaSharp 1.57.1' from 'nuget.org'.
Adding package 'SkiaSharp.1.57.1' to folder 'C:\Samples\packages'
Added package 'SkiaSharp.1.57.1' to folder 'C:\Samples\packages'
Added package 'SkiaSharp.1.57.1' to 'packages.config'
Successfully installed 'SkiaSharp 1.57.1' to ClassLibrary1
Executing nuget actions took 1.44 sec
========== Finished ==========
Time Elapsed: 00:00:05.5308904
```

**Comment by mattleibow** [comment]
Oh, wait... just saw the package that you are trying to install `SkiaSharp.Views`. That package is not meant to be installed into a PCL as that is platform-specific.

For a PCL, you just need to install the `SkiaSharp` and `SkiaSharp.Views.Forms` packages. For each app project, you should be able to install the same, but then NuGet will automatically pull in the `SkiaSharp.Views` package as well.

**Comment by mattleibow** [comment]
This is the forum post:
https://forums.xamarin.com/discussion/96229/how-do-i-get-skiasharp-to-build-now-i-have-updated-xamarin
