### ISSUE TITLE
SIGSEGV while executing native code

### ISSUE THREAD

**Issue by ahilsing** [mono/SkiaSharp#302]
I have a Xamarin Forms shared project and want to use SkiaSharp in XAML. 

My MainPage.xaml looks like this:

<?xml version="1.0" encoding="utf-8" ?>
<ContentPage xmlns="http://xamarin.com/schemas/2014/forms"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             xmlns:local="clr-namespace:MyAppProto"
             xmlns:forms="clr-namespace:SkiaSharp.Views.Forms;assembly=SkiaSharp.Views.Forms"
             x:Class="MyApp.MainPage">

    <Grid>
        <forms:SKCanvasView x:Name="canvas" PaintSurface="OnPaintSample" HorizontalOptions="FillAndExpand"
                            VerticalOptions="FillAndExpand" >
            <forms:SKCanvasView.GestureRecognizers>
                <TapGestureRecognizer Tapped="TapGestureRecognizer_OnTapped" NumberOfTapsRequired="1" />
            </forms:SKCanvasView.GestureRecognizers>
        </forms:SKCanvasView>
    </Grid>
</ContentPage>

My MainPage.xaml.cs file looks like this:

	public partial class MainPage : ContentPage
	{
	    private const int GridRows = 5;
	    private const int GridCols = 5;
	    private const float RectStrokeWidth = 2;

	    private readonly List<SKRect> _grid = new List<SKRect>();
	    private SKSurface _surface;

		public MainPage()
		{
			InitializeComponent();
		}

	    private void OnPaintSample(object sender, SKPaintSurfaceEventArgs e)
	    {
	        // Get surface info
	        var surfaceWidth = e.Info.Width;
	        var surfaceHeight = e.Info.Height;

	        // Get canvas
	        _surface = e.Surface;
	        var side = Math.Min(surfaceHeight, surfaceWidth);

	        var paint = new SKPaint();
	        // Set background
	        _surface.Canvas.Clear(Color.Black.ToSKColor());

	        // Set rect parameters
	        paint.Color = Color.Yellow.ToSKColor();
	        paint.IsStroke = true;
	        paint.StrokeWidth = RectStrokeWidth;

	        // Set rect's with and height
	        var rectHeight = side / (float) GridRows - RectStrokeWidth * 2;
	        var rectWidth = side / (float) GridCols - RectStrokeWidth * 2;

	        // Draw rects
	        for (var i = 0; i < GridRows; i++)
	        {
	            for (var j = 0; j < GridCols; j++)
	            {
	                var r1 = new SKRect(rectWidth * j, rectHeight * i, rectWidth * j + rectWidth,
	                    rectHeight * i + rectHeight);
	                _grid.Add(r1);
	                _surface.Canvas.DrawRect(r1, paint);
	            }
	        }

	    }
          private void TapGestureRecognizer_OnTapped(object sender, EventArgs e)
	      {
	        var props = _surface.SurfaceProps;
	      }
	}

If I tap on the surface and the _TapGestureRecognizer_OnTapped_ event is fired, the app terminates. It seems that I cannot preserve the SKSurface object during application lifetime. Every time I access the object's properties from somewhere else than the _OnPaintSample_ event, the app crashes.

Here is the stack trace of the exception that is raised:

> 05-25 15:40:34.540 D/Mono    ( 8096): DllImport searching in: 'libSkiaSharp.so' ('libSkiaSharp.so').
> 05-25 15:40:34.540 D/Mono    ( 8096): Searching for 'sk_surface_get_props'.
> 05-25 15:40:34.540 D/Mono    ( 8096): Probing 'sk_surface_get_props'.
> 05-25 15:40:34.540 D/Mono    ( 8096): Found as 'sk_surface_get_props'.
> 05-25 15:40:34.540 E/mono-rt ( 8096): Stacktrace:
> 05-25 15:40:34.540 E/mono-rt ( 8096): 
> 05-25 15:40:34.540 E/mono-rt ( 8096):   at <unknown> <0xffffffff>
> 05-25 15:40:34.540 E/mono-rt ( 8096):   at (wrapper managed-to-native) SkiaSharp.SkiaApi.sk_surface_get_props (intptr,SkiaSharp.SKSurfaceProps&) <0x00012>
> 05-25 15:40:34.540 E/mono-rt ( 8096):   at SkiaSharp.SKSurface.get_SurfaceProps () [0x00008] in <8e4c06e066264a27bdda5f7ce87d3a90>:0
> 05-25 15:40:34.540 E/mono-rt ( 8096):   at (wrapper runtime-invoke) <Module>.runtime_invoke_SKSurfaceProps__this__ (object,intptr,intptr,intptr) [0x00020] in <8e4c06e066264a27bdda5f7ce87d3a90>:0
> 05-25 15:40:34.540 E/mono-rt ( 8096):   at <unknown> <0xffffffff>
> 05-25 15:40:34.540 E/mono-rt ( 8096):   at MyApp.MainPage.TapGestureRecognizer_OnTapped (object,System.EventArgs) [0x00001] in F:\UnderDev\Dev\MyApp\MyApp\MainPage.xaml.cs:115
> 05-25 15:40:34.540 E/mono-rt ( 8096):   at Xamarin.Forms.TapGestureRecognizer.SendTapped (Xamarin.Forms.View) [0x0002e] in C:\BuildAgent3\work\ca3766cfc22354a1\Xamarin.Forms.Core\TapGestureRecognizer.cs:46
> 05-25 15:40:34.540 E/mono-rt ( 8096):   at Xamarin.Forms.Platform.Android.TapGestureHandler.OnTap (int) [0x00028] in C:\BuildAgent3\work\ca3766cfc22354a1\Xamarin.Forms.Platform.Android\TapGestureHandler.cs:36
> 05-25 15:40:34.540 E/mono-rt ( 8096):   at Xamarin.Forms.Platform.Android.InnerGestureListener.Android.Views.GestureDetector.IOnGestureListener.OnSingleTapUp (Android.Views.MotionEvent) [0x0001c] in C:\BuildAgent3\work\ca3766cfc22354a1\Xamarin.Forms.Platform.Android\InnerGestureListener.cs:125
> 05-25 15:40:34.544 E/mono-rt ( 8096):   at Android.Views.GestureDetector/IOnGestureListenerInvoker.n_OnSingleTapUp_Landroid_view_MotionEvent_ (intptr,intptr,intptr) [0x00011] in <33e6e739ac344166b157e323586f11a1>:0
> 05-25 15:40:34.544 E/mono-rt ( 8096):   at (wrapper dynamic-method) object.36d9ca42-c7d7-440f-ae89-3846e8be25a2 (intptr,intptr,intptr) [0x00017] in <d18287e1d683419a8ec3216fd78947b9>:0
> 05-25 15:40:34.544 E/mono-rt ( 8096):   at (wrapper native-to-managed) object.36d9ca42-c7d7-440f-ae89-3846e8be25a2 (intptr,intptr,intptr) [0x00023] in <d18287e1d683419a8ec3216fd78947b9>:0
> 05-25 15:40:34.544 E/mono-rt ( 8096):   at <unknown> <0xffffffff>
> 05-25 15:40:34.544 E/mono-rt ( 8096):   at (wrapper managed-to-native) Java.Interop.NativeMethods.java_interop_jnienv_call_boolean_method_a (intptr,intptr&,intptr,intptr,Java.Interop.JniArgumentValue*) <0x00012>
> 05-25 15:40:34.544 E/mono-rt ( 8096):   at Java.Interop.JniEnvironment/InstanceMethods.CallBooleanMethod (Java.Interop.JniObjectReference,Java.Interop.JniMethodInfo,Java.Interop.JniArgumentValue*) [0x00054] in <5716a943049b49ca928a3a1c8d2386f4>:0
> 05-25 15:40:34.544 E/mono-rt ( 8096):   at Java.Interop.JniPeerMembers/JniInstanceMethods.InvokeVirtualBooleanMethod (string,Java.Interop.IJavaPeerable,Java.Interop.JniArgumentValue*) [0x0002c] in <5716a943049b49ca928a3a1c8d2386f4>:0
> 05-25 15:40:34.544 E/mono-rt ( 8096):   at Android.Views.GestureDetector.OnTouchEvent (Android.Views.MotionEvent) [0x00038] in <33e6e739ac344166b157e323586f11a1>:0
> 05-25 15:40:34.544 E/mono-rt ( 8096):   at Xamarin.Forms.Platform.Android.VisualElementRenderer`1<TElement_REF>.Android.Views.View.IOnTouchListener.OnTouch (Android.Views.View,Android.Views.MotionEvent) [0x0007c] in C:\BuildAgent3\work\ca3766cfc22354a1\Xamarin.Forms.Platform.Android\VisualElementRenderer.cs:115
> 05-25 15:40:34.544 E/mono-rt ( 8096):   at Android.Views.View/IOnTouchListenerInvoker.n_OnTouch_Landroid_view_View_Landroid_view_MotionEvent_ (intptr,intptr,intptr,intptr) [0x0001a] in <33e6e739ac344166b157e323586f11a1>:0
> 05-25 15:40:34.544 E/mono-rt ( 8096):   at (wrapper dynamic-method) object.620578d7-374a-4f1b-9067-0573d938a7f6 (intptr,intptr,intptr,intptr) [0x0001d] in <d18287e1d683419a8ec3216fd78947b9>:0
> 05-25 15:40:34.544 E/mono-rt ( 8096):   at (wrapper native-to-managed) object.620578d7-374a-4f1b-9067-0573d938a7f6 (intptr,intptr,intptr,intptr) [0x00024] in <d18287e1d683419a8ec3216fd78947b9>:0
> 05-25 15:40:34.544 E/mono-rt ( 8096):   at <unknown> <0xffffffff>
> 05-25 15:40:34.544 E/mono-rt ( 8096):   at (wrapper managed-to-native) Java.Interop.NativeMethods.java_interop_jnienv_call_nonvirtual_boolean_method_a (intptr,intptr&,intptr,intptr,intptr,Java.Interop.JniArgumentValue*) <0x00012>
> 05-25 15:40:34.544 E/mono-rt ( 8096):   at Java.Interop.JniEnvironment/InstanceMethods.CallNonvirtualBooleanMethod (Java.Interop.JniObjectReference,Java.Interop.JniObjectReference,Java.Interop.JniMethodInfo,Java.Interop.JniArgumentValue*) [0x00074] in <5716a943049b49ca928a3a1c8d2386f4>:0
> 05-25 15:40:34.544 E/mono-rt ( 8096):   at Java.Interop.JniPeerMembers/JniInstanceMethods.InvokeVirtualBooleanMethod (string,Java.Interop.IJavaPeerable,Java.Interop.JniArgumentValue*) [0x0005f] in <5716a943049b49ca928a3a1c8d2386f4>:0
> 05-25 15:40:34.544 E/mono-rt ( 8096):   at Android.Views.View.DispatchTouchEvent (Android.Views.MotionEvent) [0x00038] in <33e6e739ac344166b157e323586f11a1>:0
> 05-25 15:40:34.544 E/mono-rt ( 8096):   at Xamarin.Forms.Platform.Android.PlatformRenderer.DispatchTouchEvent (Android.Views.MotionEvent) [0x0004e] in C:\BuildAgent3\work\ca3766cfc22354a1\Xamarin.Forms.Platform.Android\PlatformRenderer.cs:35
> 05-25 15:40:34.544 E/mono-rt ( 8096):   at Android.Views.View.n_DispatchTouchEvent_Landroid_view_MotionEvent_ (intptr,intptr,intptr) [0x00011] in <33e6e739ac344166b157e323586f11a1>:0
> 05-25 15:40:34.544 E/mono-rt ( 8096):   at (wrapper dynamic-method) object.d9314838-4c5f-4368-a3d0-8ab1f1d4e7a7 (intptr,intptr,intptr) [0x00017] in <d18287e1d683419a8ec3216fd78947b9>:0
> 05-25 15:40:34.544 E/mono-rt ( 8096):   at (wrapper native-to-managed) object.d9314838-4c5f-4368-a3d0-8ab1f1d4e7a7 (intptr,intptr,intptr) [0x00023] in <d18287e1d683419a8ec3216fd78947b9>:0

**Comment by ahilsing** [comment]
Some more info:
I use Visual Studio 2017 Community Edition and all the latest assemblies from SkiaSharp and Xamarin Forms. SkiaSharp: 1.58, Xamarin Forms: 2.3.4.247

**Comment by mattleibow** [comment]
> It seems that I cannot preserve the SKSurface object during application lifetime.

That is correct.

The `SKSurface` and `SKCanvas` objects from the paint event only live as long as the paint event is firing. As soon as the method is complete, the surface is discarded. The reason for this is that the `SKSurface` is really just a wrapper around the underlying surface - which could be a GPU FBO, a memory block or some other imaging source. 

The reason for this is that the underlying surface may be destroyed by the operating system at any time. 

What are you trying to do here? There may be another way to achieve the same thing.

**Comment by ahilsing** [comment]
I have a grid formed by a bunch of SKRect objects. When I tap on the surface of the grid, I want to do something with the located SKRect object. Set a new background, for instance. Or draw an image within the frame of the rect.
Apart from implementing a special canvas view with touch events, what would be the best approach to do that?

**Comment by mattleibow** [comment]
I am closing this issue as I think it is resolved... But your next question may be better answered on the forums.

The first problem that you need to pass is the ability to get the tap coordinates from the user. Once you have that, you can then start. If you are using Xamarin.Forms, you may have to create some effect: https://developer.xamarin.com/guides/xamarin-forms/advanced/skiasharp/paths/finger-paint/

As the paint loop can be called at ANY time (by the OS or programmer), the best option will be to have some sort of backing array or object that manages the state. Then in the paint loop, just draw that out. If you do this, you can directly respond to the tap event buy updating the backing object, and trigger a refresh of the UI.

I would recommend creating a backing object that can be manipulated, and the paint loop with just draw the backing object to the screen.
