### ISSUE TITLE
SkiaSharp.NativeAssets.Android contains a shared library 'libSkiaSharp.so' which is not correctly aligned

### ISSUE THREAD

**Issue by bcaceiro** [mono/SkiaSharp#3025]
### Is your feature request related to a problem?

Building a .net  MAUI project with Skia gives these warnings

> NuGet package 'SkiaSharp.NativeAssets.Android' version '3.0.0-preview.3.1' contains a shared library 'libSkiaSharp.so' which is not correctly aligned. See https://developer.android.com/guide/practices/page-sizes for more details

### Describe the solution you would like

Alignment issues solved for .net 9 

### Describe alternatives you have considered

It's not ab locking issue, since it can compile, just to leave this into consideration

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mattleibow** [comment]
@jonathanpeppers any thoughts on what this means?

**Comment by jonathanpeppers** [comment]
This is the upcoming 16kb alignment requirement for Google Play, and probably Android 16 / API 36 next year.

@grendello were you looking at this for SkiaSharp?

**Comment by grendello** [comment]
@jonathanpeppers I tried to, but couldn't build it locally and then I got distracted by other tasks.  I'll try to look into it soon.

**Comment by mattleibow** [comment]
Is there some compiler/linker flag? If this is a Google requirement, then I am sure the latest skia code will have it somewhere and I could find it with a code search and backport.

**Comment by grendello** [comment]
> Is there some compiler/linker flag? If this is a Google requirement, then I am sure the latest skia code will have it somewhere and I could find it with a code search and backport.

If building with the NDK r28 (not yet released), the 16k alignment would be enabled automatically.  With older NDK versions, one has to pass the `-Wl,-z,max-page-size=16384` flag to the compiler when linking (or `-z max-page-size=16384` when invoking the linker directly)

You can find more details [here](https://android-developers.googleblog.com/2024/08/adding-16-kb-page-size-to-android.html) and [here](https://developer.android.com/guide/practices/page-sizes)

**Comment by maonaoda** [comment]
Any news? Currently I can't start any page using SkiaSharp on the emulator that API over 35
```
    /usr/local/share/dotnet/packs/Microsoft.Android.Sdk.Darwin/35.0.7/tools/Xamarin.Android.Common.targets(2076,3): warning XA0141: NuGet package 'HarfBuzzSharp.NativeAssets.Android' version '7.3.0.2' contains a shared library 'libHarfBuzzSharp.so' which is not correctly aligned. See https://developer.android.com/guide/practices/page-sizes for more details
    /usr/local/share/dotnet/packs/Microsoft.Android.Sdk.Darwin/35.0.7/tools/Xamarin.Android.Common.targets(2076,3): warning XA0141: NuGet package 'SkiaSharp.NativeAssets.Android' version '3.118.0-preview.1.2' contains a shared library 'libSkiaSharp.so' which is not correctly aligned. See https://developer.android.com/guide/practices/page-sizes for more details
    /usr/local/share/dotnet/packs/Microsoft.Android.Sdk.Darwin/35.0.7/tools/Xamarin.Android.Common.targets(2076,3): warning XA0141: NuGet package 'HarfBuzzSharp.NativeAssets.Android' version '7.3.0.2' contains a shared library 'libHarfBuzzSharp.so' which is not correctly aligned. See https://developer.android.com/guide/practices/page-sizes for more details
    /usr/local/share/dotnet/packs/Microsoft.Android.Sdk.Darwin/35.0.7/tools/Xamarin.Android.Common.targets(2076,3): warning XA0141: NuGet package 'SkiaSharp.NativeAssets.Android' version '3.118.0-preview.1.2' contains a shared library 'libSkiaSharp.so' which is not correctly aligned. See https://developer.android.com/guide/practices/page-sizes for more details
    /usr/local/share/dotnet/packs/Microsoft.Android.Sdk.Darwin/35.0.7/tools/Xamarin.Android.Common.targets(2076,3): warning XA0141: NuGet package '<unknown>' version '<unknown>' contains a shared library 'libbarhopper_v3.so' which is not correctly aligned. See https://developer.android.com/guide/practices/page-sizes for more details
    /usr/local/share/dotnet/packs/Microsoft.Android.Sdk.Darwin/35.0.7/tools/Xamarin.Android.Common.targets(2076,3): warning XA0141: NuGet package '<unknown>' version '<unknown>' contains a shared library 'libbarhopper_v3.so' which is not correctly aligned. See https://developer.android.com/guide/practices/page-sizes for more details
```

![image](https://github.com/user-attachments/assets/07a5bba0-dbbb-4feb-a9ce-f7febb6f5e51)

**Comment by NickDufour** [comment]
We are also encountering the 16 KB page size issue on Android 15 (API 35) with SkiaSharp when running our application on devices that require 16 KB paging

**Comment by mattleibow** [comment]
@jonathanpeppers is this true? The sims won't even launch an app with non-aligned binaries?

**Comment by fntc** [comment]
Tried it yesterday. Can confirm that the very same apk can launch in emulator with image V34 but not with V35. However, I have a few other native libraries the build process complains about

**Comment by grendello** [comment]
> @jonathanpeppers is this true? The sims won't even launch an app with non-aligned binaries?

Yes, they won't.  However, in the emulator one [can disable](https://developer.android.com/guide/practices/page-sizes#developer-option) the 16k alignment (in x86_64 images at least)

**Comment by maonaoda** [comment]
Do you need to modify this?
```
    /usr/local/share/dotnet/packs/Microsoft.Android.Sdk.Darwin/35.0.7/tools/Xamarin.Android.Common.targets(2076,3): warning XA0141: NuGet package 'HarfBuzzSharp.NativeAssets.Android' version '7.3.0.2' contains a shared library 'libHarfBuzzSharp.so' which is not correctly aligned. See https://developer.android.com/guide/practices/page-sizes for more details
    /usr/local/share/dotnet/packs/Microsoft.Android.Sdk.Darwin/35.0.7/tools/Xamarin.Android.Common.targets(2076,3): warning XA0141: NuGet package 'HarfBuzzSharp.NativeAssets.Android' version '7.3.0.2' contains a shared library 'libHarfBuzzSharp.so' which is not correctly aligned. See https://developer.android.com/guide/practices/page-sizes for more details
```

**Comment by maonaoda** [comment]
Well,that because the other packages I referenced are still using the old version

**Comment by mattleibow** [comment]
To solve that, you can just install the latest HarfBuzzSharp and it will pull in the latest dependencies.
