### ISSUE TITLE
[BUG] Blazor standalone app can't build release cause of emcc error.

### ISSUE THREAD

**Issue by vyefymochkyn** [mono/SkiaSharp#3028]
### Description

Create blazor standalone app running .NET8, add SkiaSharp.Views.Blazor package and you can't build app in release mode.

### Code

```xml
<Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="SkiaSharp.Views.Blazor" Version="2.88.8" />
  </ItemGroup>

</Project>
``` 

### Expected Behavior

Debug builds and run fine.

### Actual Behavior
![image](https://github.com/user-attachments/assets/e0fb69a4-fa53-4162-b2a2-7083fd8eab5e)

_No response_

### Version of SkiaSharp

2.88.8 (Current)

### Last Known Good Version of SkiaSharp

Other (Please indicate in the description)

### IDE / Editor

Visual Studio (Windows)

### Platform / Operating System

Windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mattleibow** [comment]
This seems to work for me, please attach a repro so I can check:

![image](https://github.com/user-attachments/assets/38fd775e-3e4e-4197-a9c7-dc24cf3cae82)

[BlazorApp1.zip](https://github.com/user-attachments/files/17703106/BlazorApp1.zip)
