### ISSUE TITLE
Why OnPaintSurface method is called so may times ?

### ISSUE THREAD

**Issue by gayugokhale** [mono/SkiaSharp#303]
on `SKCanvas` I am drawing multiple bitmaps and let user scale, drag and rotate that images.
Everything works fine but `OnPaintSurface` is called 2 times for 1 bitmap. Because of this, my performance gets slow after some time.
These things are decided by OS from device or are managed in plugin itself ?

Please help !

**Comment by mattleibow** [comment]
I think that I may need a bit more information. The paint event will get fired each time something invalidates the underlying surface.

This can include view transformations (animations), view manipulations (resizing) or just by calling `InvalidateSurface()` on some platforms.

How are you doing the transformations? And, have you ensured that you are not attaching multiple event handlers to the event (or the same one multiple times)?

**Comment by gayugokhale** [comment]
Sorry, I am little bit late. Actually when I was searching for this issue, I first tried [this](https://github.com/xamarin/xamarin-forms-samples/tree/master/SkiaSharpForms/SkiaSharpFormsDemos) example. but at that time bitmap scaling translating operations were not implemented. It was just simple skiasharp demo. After that I found [this](https://github.com/mattleibow/SkiaSharpFormsRendererDemo) example. I tried that and implemented using renderer. So now, my current code includes both the code.  Actually I am not at my working place at the time of writing. So here is the description what I have done.

So I have `TouchCanvasView` Where you defined only `OnTouch` I have defined all the other methods `OnScale`,`OnTranslate` and others. Now in renderer in `OnTouch` I calculate distance, scale or rotate and return events defined in `TouchCanvasView`. and catch it in `MainPage.xaml.cs`. And I implemented rotation after `SkiaSharpFormsDemos` got updated. because there was matrix related issue.

I know its crazy but after trying for so many days, its working !! 
And I am not calling event multiple times.

One more question when I `Invalidate` from `MainPage.xaml.cs`, OnPaint is not called. why ??

Thank you !!

**Comment by mattleibow** [comment]
Great to hear that you are making progress.

I am not too sure what you mean by `Invalidate`... Do you mean `InvalidateSurface`? This works for mean - how are you testing that it is not being called? It might be the case that either the width or height is zero, so in this case, the paint is skipped.
