### ISSUE TITLE
[BUG] Blazor App Crashes in AOT mode with SkiaSharp.HarfBuzz in .NET 8

### ISSUE THREAD

**Issue by elepner** [mono/SkiaSharp#3049]
### Description

The library SkiaSharp.HarfBuzz does not work at all in AOT mode with .NET 8 and 9, however everything works fine in .NET 7. 
![image](https://github.com/user-attachments/assets/164a8fd5-333a-403a-927b-bfb7ef695b57)

### Code

The github repo with minimal project to reproduce:
https://github.com/elepner/harfbuzzsharp-wasm-aot-bug/tree/report_bug

Publish the project
``dotnet publish -c Release -o wasm-output``
navigate to the output folder ``wasm-output/wwwroot`` and start any http-server.

### Expected Behavior

The app should not crash.

### Version of SkiaSharp

2.88.8 (Current)

### Last Known Good Version of SkiaSharp

2.88.7 (Previous)

### IDE / Editor

Visual Studio (Windows)

### Platform / Operating System

Other (Please indicate in the description)

### Platform / Operating System Version

Blazor

### Devices

Google chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mattleibow** [comment]
Does it work with SkiaSharp 3.0?

**Comment by elepner** [comment]
If I update ``SkiaSharp.HarfBuzz`` to the version ``3.0.0-preview.5.4`` along with ``SkiaSharp.NativeAssets.WebAssembly`` I get the error 
```
Unhandled exception rendering component: The type initializer for 'SkiaSharp.SKObject' threw an exception.
System.TypeInitializationException: The type initializer for 'SkiaSharp.SKObject' threw an exception.
 ---> System.InvalidOperationException: The version of the native libSkiaSharp library (116.0) is incompatible with this version of SkiaSharp. Supported versions of the native libSkiaSharp library are in the range [88.1, 89.0).
```

**Comment by elepner** [comment]
I have given a try to run this in .net9 with no success. There's another error which appears even in Debug mode.
```
logging.ts:43 MONO_WASM: instantiate_wasm_module() failed CompileError: WebAssembly.compileStreaming(): Compiling function #28714:"CompressionNative_Crc32" failed: expected 1 elements on the stack for fallthru, found 3 @+8898931
```
The code: https://github.com/elepner/harfbuzzsharp-wasm-aot-bug/tree/net9_bug

**Comment by mattleibow** [comment]
This may be fixed with https://github.com/mono/SkiaSharp/pull/3064

Can you try the nightly on the preview feed: `3.118.0-nightly.27`

```
https://aka.ms/skiasharp-eap/index.json
```

Let me know if this fixes it and I will push out the 3.x release.

**Comment by elepner** [comment]
I have [checked](https://github.com/elepner/harfbuzzsharp-wasm-aot-bug/commit/2c5eac71a6dbd976d2aba673d260c3a34b58d3ae) this with .NET9 and get same error
```
MONO_WASM: instantiate_wasm_module() failed CompileError: WebAssembly.compileStreaming(): Compiling function #28716:"CompressionNative_Crc32" failed: expected 1 elements on the stack for fallthru, found 3 @+8897861
```
The code: https://github.com/elepner/harfbuzzsharp-wasm-aot-bug/tree/net9_bug

**Comment by elepner** [comment]
I have checked on this small project version nightly.33 and it works. Tanks @mattleibow! When can one expect this fix published on stable?
