### ISSUE TITLE
SKPaint.Color property

### ISSUE THREAD

**Issue by leonardors** [mono/SkiaSharp#307]
I am having the same problem with version 1.5.8, on simulator and device.

var paint = new SKPaint();
var color = SKColor.Parse("#ff0000");

System.Diagnostics.Debug.WriteLine("CurrentColor: {0}", paint.Color);
System.Diagnostics.Debug.WriteLine("NewColor: {0}", color);
paint.Color = color;
System.Diagnostics.Debug.WriteLine("Result: {0}", paint.Color);

Result:
CurrentColor: #8ef0eee8
NewColor: #ffff0000
Result: #955dfae4

**Comment by mattleibow** [comment]
This was fixed in #284 
The previous fix was overwritten in a commit a few months back during the support for pre-multiplied colors. I will release a fix soon.

**Comment by mattleibow** [comment]
@leonardors What device are you running? I was not able to repro this on my device, just my simulators.

**Comment by pjt33** [comment]
FWIW I ran into this problem both with emulators and with a Woxter Zen 10 tablet, but it's a very tricky one because when I passed my repro code to a colleague it ran without problem in his emulators.

**Comment by mattleibow** [comment]
Just pushed out a release that should resolve this: https://github.com/mono/SkiaSharp/releases/tag/v1.58.1
