### ISSUE TITLE
[BUG] When Compile Blazor Web Assembly App

### ISSUE THREAD

**Issue by ibrhmusta** [mono/SkiaSharp#3074]
### Description

MONO_WASM: instantiate_wasm_module() failed CompileError: WebAssembly.compileStreaming(): Compiling function #27054:"CompressionNative_Crc32

### Code

The best way to share code for larger projects is a link to a GitHub repository: https://github.com/user/repo/tree/bug-123

But, you can also share a short block of code here:
```cs
// some C# code here
```
You can also share some XAML:
```xaml
<!-- xaml code here -->
```

### Expected Behavior

compile correctly and make the application work

### Actual Behavior

It is a correct compile and the application is ready to run but it is not working

### Version of SkiaSharp

3.118.0-preview.1 (Next Preview)

### Last Known Good Version of SkiaSharp

2.88.8 (Previous)

### IDE / Editor

Visual Studio (Windows)

### Platform / Operating System

Windows

### Platform / Operating System Version

Windows 10 x64

### Devices

Dell Desktop

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mattleibow** [comment]
This may be fixed with https://github.com/mono/SkiaSharp/pull/3064

Can you try the nightly on the preview feed: `3.118.0-nightly.27`

```
https://aka.ms/skiasharp-eap/index.json
```

Let me know if this fixes it and I will push out the 3.x release.
