### ISSUE TITLE
[BUG] .Net MAUI 9.0  Windows platform application crashes when using the SKGLView control

### ISSUE THREAD

**Issue by wzy9089** [mono/SkiaSharp#3113]
### Description

dotNet 9.0 Maui application using SKGLView throw System.ExecutionEngineException
  HResult=0x80131506

Call stack screenshot
![屏幕截图 2024-12-12 132156](https://github.com/user-attachments/assets/8eeccbe1-745e-492c-8959-d68a1a47360c)

### Code

The best way to share code for larger projects is a link to a GitHub repository: https://github.com/user/repo/tree/bug-123

But, you can also share a short block of code here:
```cs
// some C# code here
```
You can also share some XAML:
```xaml
<!-- xaml code here -->
<?xml version="1.0" encoding="utf-8" ?>
<ContentPage xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             xmlns:skia="clr-namespace:SkiaSharp.Views.Maui.Controls;assembly=SkiaSharp.Views.Maui.Controls"
             x:Class="MauiGLCanvasTest.MainPage">

    <Grid>
        <skia:SKGLView PaintSurface="SKGLView_PaintSurface"/>
    </Grid>
</ContentPage>


### Expected Behavior

_No response_

### Actual Behavior

_No response_

### Version of SkiaSharp

3.118.0-preview.2 (Next Preview)

### Last Known Good Version of SkiaSharp

2.88.9 (Previous)

### IDE / Editor

Visual Studio (Windows)

### Platform / Operating System

Windows

### Platform / Operating System Version

windows 11

### Devices

thinkpad t14p with intel ultra9 185h cpu

### Relevant Screenshots

_No response_

### Relevant Log Output

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by TommiGustafsson-HMP** [comment]
Please use packaged mode. .NET 9 defaults to unpackaged.

https://github.com/mono/SkiaSharp/issues/2968

Essentially, you need `<WindowsPackageType>MSIX</WindowsPackageType>` in csproj and `"commandName": "MsixPackage"` in launchSettings.json.

**Comment by wzy9089** [comment]
Problem solved, thank you very much！:)

**Comment by TommiGustafsson-HMP** [comment]
Great, you can then close this issue!
