### ISSUE TITLE
Porting SkTextBox to support draw text in wrap

### ISSUE THREAD

**Issue by tangkhaiphuong** [mono/SkiaSharp#313]
Skia native version have SkTextBox support draw text in wrap, please implement to support this feature.

https://github.com/google/skia/blob/fcee51038aeaf3596a4ffcdba0bf18e3155e09b9/include/utils/SkTextBox.h

**Comment by mattleibow** [comment]
This may be related to, or a precursor to: https://github.com/mono/SkiaSharp.Extended/issues/11

**Comment by mattleibow** [comment]
This may be related to, or a precursor to: https://github.com/mono/SkiaSharp.Extended/issues/12

**Comment by gdchet** [comment]
This is desperately needed. Trying to measure text size with Harfbuzz and get the right line breaks from ICU to create wrapped text. It's getting over complicated and the end result is not pretty!

**Comment by mattleibow** [comment]
This issue was moved to mono/SkiaSharp.Extended#28
