### ISSUE TITLE
Android MeasureText returns empty Rect

### ISSUE THREAD

**Issue by LeRondPoint** [mono/SkiaSharp#314]
I'm always getting an empty rectangle as a result fo my calls to MeasureText on Android using Xamarin Forms.

```

        protected override SizeRequest OnMeasure(double widthConstraint, double heightConstraint)
        {
            if (_LastSize == null && HasSomethingToDraw())
            {
                SKRect textBounds = new SKRect();
                Rectangle requestRect;

                _Paint.MeasureText(Text, ref textBounds);
                requestRect = textBounds.ToFormsRect();

                requestRect.Height += _Paint.FontMetrics.Descent;
                requestRect.Width = Math.Ceiling(Math.Min(requestRect.Width, widthConstraint));
                requestRect.Height = Math.Ceiling(Math.Min(requestRect.Height, heightConstraint));

                _LastSize = new SizeRequest(requestRect.Size);
            }

            return _LastSize.GetValueOrDefault(new SizeRequest());
        }
```

You can use this branch for a repro (Check SKLabel class) : https://github.com/LeRondPoint/FormsSkiaBikeTracker/tree/SKCanvasViewBug

![image](https://user-images.githubusercontent.com/15251145/26985612-4479075c-4d12-11e7-973c-bf04238de399.png)

**Comment by LeRondPoint** [comment]
Shoudl have expanded FontMetrics, they are all set at 0...

**Comment by mattleibow** [comment]
This is an interesting issue in that it appears to just be this font, and just for Android. I tried a new font, and your code (almost) works.

There is another issue in that you are disposing the stream. When passing the stream to `SKTypeface` it may or may not be finished using it when the method returns, so you have to leave it up to `SKTypeface` to manage the lifetime of the stream. According to the docs:
> Returns a new typeface given a stream. **Ownership of the stream is transferred, so the caller must not reference it again.**
> https://developer.xamarin.com/api/member/SkiaSharp.SKTypeface.FromStream/p/SkiaSharp.SKStreamAsset/System.Int32/

But, even when we no longer dispose the stream, the font still does nothing. I have a very strong feeling that this is either a bug in Android, but more likely an issue with the font (in some way). That file works on macOS, iOS, and Windows - but not Android???

I have attached proof that this is failing even with normal Android.
Xamarin.Android: [Archive.zip](https://github.com/mono/SkiaSharp/files/1065569/Archive.zip)

_I am going to create a Java Android test app just to confirm that this is in no way something to do with Xamarin - which I don't believe it is._

**Comment by mattleibow** [comment]
Just did a test with Java, same thing: [JavaAndroidFonts.zip](https://github.com/mono/SkiaSharp/files/1065579/JavaAndroidFonts.zip)

I am not sure what to do from here... The easiest would be to just get a new font, but if you can't do that, then maybe ask on StackOverflow - you can just use the attached sample if people want to use Java instead of C# to answer your question.

**Comment by LeRondPoint** [comment]
Wow I'm a lucky guy selecting the only problematic font in the universe and thanks for you thorouh investigation!  I'm just building a demo for a 100% shared UI code app so I'll pick another font.

**Comment by LeRondPoint** [comment]
Apparently it is somewhat widespread... https://stackoverflow.com/questions/27269264/custom-fonts-not-working-in-lollipop
So Skia uses the platform font loading underneath?  It certainly is not the case on iOS since the font is not in the info.plist, which is precisely what I was demoing with this label.

**Comment by LeRondPoint** [comment]
I converted the font to OTF and it works fine now!

**Comment by mattleibow** [comment]
Great to hear!

It does not use the system font loading mechanism - we can provide custom font streams, but we are limited to what the OS can render. I think in this case, Android cannot understand this font file for some reason.
