### ISSUE TITLE
SKElement crash if size isnt set (Width = NaN or/and Height = NaN)

### ISSUE THREAD

**Issue by polipo** [mono/SkiaSharp#326]
In WPF skiasharp library the SKElement is added in autogrow (width = Nan and/or Height = NaN) the project crashes when it try to create a WritableBitmap with zero dimension

**Comment by mattleibow** [comment]
Just pushed out a release that should resolve this: https://github.com/mono/SkiaSharp/releases/tag/v1.58.1
