### ISSUE TITLE
ASP.NET builds fail due to libSkiaSharp.dll being locked

### ISSUE THREAD

**Issue by cs-NET** [mono/SkiaSharp#327]
It appears that libSkiaSharp.dll is copied over to bin on each build, after the first build and use of SkiaSharp the dll becomes locked and future builds will fail with the following:

> Unable to copy file "\packages\SkiaSharp.1.58.0\runtimes\win7-x64\native\libSkiaSharp.dll" to "bin\libSkiaSharp.dll". The process cannot access the file 'bin\libSkiaSharp.dll' because it is being used by another process.

You have to kill w3wp.exe process to remove the lock and build project again. 

If I add 
```
 <ShouldIncludeNativeSkiaSharp>False</ShouldIncludeNativeSkiaSharp> 
```
the issue goes away however you will soon run into issues where you need the dlls copied to the bin again as they have been removed (say from a clean solution, or source control operation).

Looking for a better approach, is there a way to ensure the lock on libSkiaSharp.dll is released? Or does it have to do with x86/x64/AnyCpu platform build logic?

**Update**
I moved SkiaSharp logic to a new Class Library project and set the project's Platform Target to x64. When the ASP.NET application builds the file is still locked in the bin folder, however, the build no longer errors out trying to copy the libSkiaSharp.dll. This is an acceptable workaround. If the project's Platform Target is set to AnyCPU the error will occur.

**Comment by mattleibow** [comment]
It is because of this:

    <CopyToOutputDirectory>Always</CopyToOutputDirectory>

https://github.com/mono/SkiaSharp/blob/v1.58.0/binding/SkiaSharp.Desktop/nuget/build/net45/SkiaSharp.Desktop.targets#L46

This will be fixed in the next release: v1.58.1

**Comment by mattleibow** [comment]
Just pushed out a release that should resolve this: https://github.com/mono/SkiaSharp/releases/tag/v1.58.1

**Comment by cs-NET** [comment]
Thanks @mattleibow , I just changed class library back to AnyCPU and it works like a charm!
