### ISSUE TITLE
WPF SKElement does not call PaintSurface when event attached in Loaded

### ISSUE THREAD

**Issue by wldevries** [mono/SkiaSharp#328]
I made the mistake of attaching the event in the loaded event of Window. For some reason the SKElement will refuse to draw and call the PaintSurface handler.

```
        public MainWindow()
        {
            InitializeComponent();
            this.Loaded += MainWindow_Loaded;
        }

        private void MainWindow_Loaded(object sender, RoutedEventArgs e)
        {
            this.skia.PaintSurface += this.Skia_PaintSurface;
        }

        private void Skia_PaintSurface(object sender, SKPaintSurfaceEventArgs args)
        {
            // paint stuff
        }
```

**Comment by mattleibow** [comment]
The reason for this is that you are attaching the paint event AFTER the paint cycle is complete. The paint is going to happen during the initialization, and most probably will have happened already by the time `Loaded` is called:

> Occurs when a FrameworkElement has been constructed and added to the object tree, and is ready for interaction.

Although you can attach the event in the window constructor:

```csharp
public MainWindow()
{
	InitializeComponent();

	this.skia.PaintSurface += this.Skia_PaintSurface;
}
```

You can also just invalidate the surface after attaching the event

```
private void MainWindow_Loaded(object sender, RoutedEventArgs e)
{
    this.skia.PaintSurface += this.Skia_PaintSurface;
    skia.InvalidateVisual();
}
```
