### ISSUE TITLE
SkDocument PDF output support

### ISSUE THREAD

**Issue by roceh** [mono/SkiaSharp#33]
This looks very cool, PDF output via SkDocument would be a useful addition. Although it is not exposed via the Skia C API it looks at first glance to be a pretty simple class.

**Comment by migueldeicaza** [comment]
This looks very useful, we need to basically bind the SkDocument type.

**Comment by tdenniston** [comment]
Is anyone working on this? Otherwise I can take a crack at it, as this is something I need.

**Comment by tdenniston** [comment]
Update: I've written the C api but I don't know how to get the build to link `libskia_windows` with the `pdf` Skia project (generated from `pdf.gyp`).

**Comment by mattleibow** [comment]
Hey @tdenniston, have you managed to get the build going? The VS projects just need you to add a reference to the pdf vcxproj (and any dependencies). Basically, add the project to the solution, and then reference it in the libSkiaSharp project...

**Comment by tdenniston** [comment]
@mattleibow Hmm, I'm not sure I understand completely. (I'm still learning Windows development practices and Visual Studio). Which solution do I add pdf.vcxproj to? On a related note, I'm now seeing quite a few build problems since the UWP platform was added. I'm developing on Windows 7 but it seems to think I am on a UWP platform.

**Comment by alanricker** [comment]
@mattleibow @migueldeicaza this sounds very useful as I need print also.
Would it be as simple as launching PDF in default browser via xamarin forms, or is there an easier cross-platform way?
Would we also need XPS for Windows WPF or UWP?
Thanks again for all your work on this.

**Comment by mattleibow** [comment]
@alanricker Not too sure exactly, but I do know that Windows UWP has a default PDF reader - Edge. They are discontinuing the PDF reader app, so PDF support is available right from the start

**Comment by mattleibow** [comment]
All right... I have done this in the native bit and wrapped the `SkDocument` and `SkWStream`s. I have a really basic PDF sample (just a single line of text). Just waiting for our CI to pick it up and then I will release a new version.

**Comment by mattleibow** [comment]
tvOS and PDF support was added in the release https://github.com/mono/SkiaSharp/releases/tag/v1.49.4-beta
