### ISSUE TITLE
Resize returns null for PNGs

### ISSUE THREAD

**Issue by kodeo** [mono/SkiaSharp#331]
I'm getting null back from `SKBitmap.Resize()` after loading a PNG, i.e.

```
var original = SKBitmap.Decode(@"c:\test.png");
var resized = original.Resize(new SKImageInfo(w, h), SKBitmapResizeMethod.Lanczos3);
```
...gives `resized` is `null`. Works fine for a JPG.

**Comment by AndersMad** [comment]
check the source color type - it won't work with `SKColorType.Index8`

**Comment by kodeo** [comment]
It is `Index8`. What's the problem with `Index8` then?

**Comment by AndersMad** [comment]
I don't know (except the fact that its much more complicated).. it's a Google Skia base/DLL thing in the `sk_bitmapscaler_resize` - but I see that the road says there will be more focus on GIF in the fure - so maybe that will deal with it.. Until then, convert the image/bitmap by e.g. drawing it to a new surface (will preserve alpha etc.).. Also note this if wanting to use scaling while drawing: https://github.com/mono/SkiaSharp/issues/319

**Comment by kodeo** [comment]
OK. Cheers.

**Comment by sayyildiz** [comment]
My solution is changing colortype before resizing.

```
if (bitmap.ColorType != SKColorType.Bgra8888)
{
    bitmap.CopyTo(bitmap, SKColorType.Bgra8888);
}
```

**Comment by aloisdeniel** [comment]
It didn't worked for me with `SKColorType.Bgra8888`, but it worked with `SKColorType.Rgba8888` (from macOS).

```csharp
if (bitmap.ColorType != SKColorType.Rgba8888)
{
      bitmap.CopyTo(bitmap, SKColorType.Rgba8888);
}
```

**Comment by mattleibow** [comment]
@sayyildiz @aloisdeniel Rather than use a specific type, use the `SKImageInfo.PlatformColorType` so that the code will work on all platforms this code is run on.

Windows is typically `Bgra8888` and Unix is typically `Rgba8888`, but I have noticed that some Linux distros on my VMs mix things up.

**Comment by aloisdeniel** [comment]
Thanks @mattleibow, that's better!

```csharp
bitmap.CopyTo(bitmap, SKImageInfo.PlatformColorType);
```

**Comment by almirvuk** [comment]
Thank you guys! 🤗 @aloisdeniel @mattleibow @sayyildiz

**Comment by mattleibow** [comment]
With the newer versions of SkiaSharp in the pipeline, this won't be needed anymore. Previously, skia supported loading index8 images but not any manipulations. With the later versions, loading index8 automatically gets converted to platform RGBA/BGRA.
