### ISSUE TITLE
Views.Forms.SKTouchAction.Moved event not Firing on Android

### ISSUE THREAD

**Issue by ikaros88** [mono/SkiaSharp#334]
Hi,

i am trying to implement finger painting on an SKCanvasView by building SKPaths from SKTouchAction.Moved events, which works perfectly when debugging in UWP. However, when debugging on a real Android device (or in an emulator), i only get a SKAction.Pressed event, never a SKTouchAction.Moved event.

The Canvas is not in a Scrollview, there are no Gesturehandlers attached anywhere near it.

Can provide code if necessary.

Greetings

**Comment by mattleibow** [comment]
This sounds like you didn't let the OS know that you wanted to continue receiving touch events:

```
private void OnTouch(object sender, SKTouchEventArgs e)
{
	// handle the touch event

	// let the OS know we are interested
	e.Handled = true;
}
```

UWP/macOS don't really require it, as the OS is capable of sending events to multiple destinations, but iOS/Android need you to indicate that you want to receive them. Android will not even send any events further if you don't handle the pressed event - the parent will probably get them all.

**Comment by ikaros88** [comment]
that did the trick, works perfectly now, thanks!
