### ISSUE TITLE
SKBitmap.Decode returns null when provided WebClient Stream with certain jpg

### ISSUE THREAD

**Issue by funkyOne** [mono/SkiaSharp#335]
**Environment:**
Windows 10, .NET Core 2.0 Preview 2, SkiaSharp@1.58.1

SKBitmap.Decode returns null when provided Stream from WebClient for some jpg files.
```csharp
using (var client = new WebClient())
{
    using (var stream = client.OpenRead(url))
    {
        var bitmap = SKBitmap.Decode(stream); //returns null
    }
}
```

Interesting enough, the same image will be decoded fine if first downloaded to memory stream. Also works if converted to bytes. 

I tried to compare failing/working files, using JPEGSnoop. Found out that the following data is present in the failing files. Not sure if it is exactly the reason, but at least some clue.
![image](https://user-images.githubusercontent.com/2235489/27949579-dba54f46-6306-11e7-9897-0b3a94ce9be4.png)

Please see the repro here:
https://github.com/funkyOne/SkiaSharpStreamIssueRepro

This does seem like a bug. I'm happy to help more, but don't have much expertise in imaging stuff. I can provide more of such images if needed.

Thanks

**Comment by kodeo** [comment]
I'm having the same issue using HttpClient, e.g.

```
using (var client = new HttpClient())
{
	var url = "https://image.ibb.co/bO1RLF/broken2.jpg";
	var response = await client.GetAsync(url, HttpCompletionOption.ResponseHeadersRead);
	// var worksWithThis = await response.Content.ReadAsByteArrayAsync();
	using (var stream = await response.Content.ReadAsStreamAsync())
	{
		var skbmp = SKBitmap.Decode(stream);
	}
}
```

It does seem to be something to do with buffering, because it works if I change to `HttpCompletionOption.ResponseContentRead` or uncomment the `worksWithThis` line, but I'm at a complete loss to explain why it affects some files but not others.

**Comment by mattleibow** [comment]
Thanks for reporting this.

**Comment by CmdrNexus** [comment]
Hi there

the "bm" in this method

        public byte[] Image2Byte(SKBitmap bitmap)
        {
            var temp = bitmap.Bytes;

            var bm = SKBitmap.Decode(temp);

            return temp;
        }

is always null.

Is it me, or is should this not be happening?

Cheers

**Comment by mattleibow** [comment]
@CmdrNexus this is a bug that was fixed https://github.com/mono/SkiaSharp/commit/dbd09b0ffeca981c878c5ce5ec333019c85406a4

The basic issue is that the .NET and SkiaSharp streams work differently, and I was not properly handling this.
