### ISSUE TITLE
Cannot install any of the latest nuget packages to fresh Xamarin.Forms project.

### ISSUE THREAD

**Issue by erdmenchen** [mono/SkiaSharp#339]
Setup:
Latest Visual Studio 2017 (Version 15.2).
Fresh new sample solution of Xamarin.Forms with PCL, Android and iOS projects.
PCL targeting profile Profile111.
Latest Xamarin.Forms 2.3.4.247.

Trying to install SkiaSharp for PCL library and platform libraries (Android and iOS).
Nuget install halts for ever during install.

Tried with SkiaSharp 1.57.1, 1.58.0 and 1.58.1.
All fail during nuget package install.

Nuget output:
> Attempting to gather dependency information for package 'SkiaSharp.1.58.1' with respect to project  'SkiaTest.iOS', targeting 'Xamarin.iOS,Version=v1.0'
> Gathering dependency information took 10.74 sec
> Attempting to resolve dependencies for package 'SkiaSharp.1.58.1' with DependencyBehavior 'Lowest'
> Resolving dependency information took 0 ms
> Resolving actions to install package 'SkiaSharp.1.58.1'
> Resolved actions to install package 'SkiaSharp.1.58.1'
> 
> 
> Attempting to gather dependency information for package 'SkiaSharp.1.58.1' with respect to project 'SkiaTest.Android', targeting 'MonoAndroid,Version=v7.1'
> Gathering dependency information took 304.84 ms
> Attempting to resolve dependencies for package 'SkiaSharp.1.58.1' with DependencyBehavior 'Lowest'
> Resolving dependency information took 0 ms
> Resolving actions to install package 'SkiaSharp.1.58.1'
> Resolved actions to install package 'SkiaSharp.1.58.1'
> 
> 
> Attempting to gather dependency information for package 'SkiaSharp.1.58.1' with respect to project 'SkiaTest', targeting '.NETPortable,Version=v4.5,Profile=Profile111'
> Gathering dependency information took 653.14 ms
> Attempting to resolve dependencies for package 'SkiaSharp.1.58.1' with DependencyBehavior 'Lowest'
> Resolving dependency information took 0 ms
> Resolving actions to install package 'SkiaSharp.1.58.1'
> Resolved actions to install package 'SkiaSharp.1.58.1'
> Retrieving package 'SkiaSharp 1.58.1' from 'nuget.org'.
>   GET https://api.nuget.org/packages/skiasharp.1.58.1.nupkg
>   OK https://api.nuget.org/packages/skiasharp.1.58.1.nupkg 883ms
> Installing SkiaSharp 1.58.1.

**Comment by mattleibow** [comment]
@erdmenchen I am not able to repro this.

I tried the iOS, Android, UWP, PCL259 and PCL111 and it installed.

Here is my VS info: https://gist.github.com/mattleibow/e9aeaffc05004f934e8346a9bfff73fe

Is there a error? I can't see any error in the log you posted.

**Comment by erdmenchen** [comment]
No error, it just stops at the last statment for ever. Thats why I cannot give more information...

**Comment by erdmenchen** [comment]
I am sorry. After trying again and letting it sit for more than half a hour, it proceeded and successfully installed. 
Never had this with a nuget package installation before...if this is expected for sciasharp, maybe add it to the documentation.

Thx for looking into this.

**Comment by mattleibow** [comment]
That seems strange... Unless you are on a very slow connection. The package is fairly large ~45MB as it contains binaries for all the platforms. But, this is not too bad...
