### ISSUE TITLE
Support for SkRegion in the future?

### ISSUE THREAD

**Issue by petergolde** [mono/SkiaSharp#34]
I would love to see support for SkRegion, plus more exposure of SkPath. In particular, I'm interested in being able to create an SKRegion from and SkPath, do operations on SkRegion such as intersect, union, subtract, containment, and get the bounary of an SkRegion as an SkPath. Finally, being able to enumerate an SkPath to get all of its components.

All of this is supported in the Skia C++ library; it would be really nice to use this from C#. 

All of these operations can be useful in a 2D application even apart from drawing.

**Comment by petergolde** [comment]
Also really nice would be support for the "pathops" code with the public header: SkPathOps.h

**Comment by migueldeicaza** [comment]
Peter, do you mind filing individual issues for each API that is missing?   It will be a lot easier to track down.
