### ISSUE TITLE
Name SkiaSharp.View.Desktop does not exist in Winform project

### ISSUE THREAD

**Issue by chihkeong** [mono/SkiaSharp#342]
Error CS0234: The type or namespace name 'View' does not exist in the namespace 'SkiaSharp' (are you missing an assembly reference?)

I was able to compile a SkiaSharp project until this line was added in SharpDevelop 4.4 or Visual Studio 2017 Community Release.

using SkiaSharp.View.Desktop;

Development machine is a Windows 10 and build target set to x86, Net 4.5.  

Is this a bug?

**Comment by mattleibow** [comment]
This is because you need to add the package:

https://www.nuget.org/packages/SkiaSharp.Views/

**Comment by chihkeong** [comment]
Hi,

Me bad, in the project, I added the reference to the Skiasharp.View dynamic link library to the project and the namespace errors are gone.  

This is an excellent implementation, will be moving all my GDI drawing routines to Skiasharp!

Thank you.
