### ISSUE TITLE
Instance of SKBitMap is null, when i decode a image from project path

### ISSUE THREAD

**Issue by Padalingam** [mono/SkiaSharp#343]
I wanna display image in SkCanvasView. when i tried to change the image into bitmap by using decode, i got a null in Bitmap. Here is my code in ContentPage Constructor
```
string resourceID = "Helloworld.Media.icon.png";
Assembly assembly = GetType().GetTypeInfo().Assembly;
using (Stream stream = assembly.GetManifestResourceStream(resourceID)) 
using (SKManagedStream skStream = new SKManagedStream(stream))
  {
   resourceBitmap = SKBitmap.Decode(skStream); // System.NullReference
  }
```
And below is drawing surface method
```
void OnCanvasViewPaintSurface(object sender, SKPaintSurfaceEventArgs args)
  {
   SKImageInfo info = args.Info;
   SKSurface surface = args.Surface;
   SKCanvas canvas = surface.Canvas;
   canvas.Clear();
			if (resourceBitmap != null)
			{
			canvas.DrawBitmap(resourceBitmap,
					new SKRect(0, info.Height / 3, info.Width, 2 * info.Height / 3));
			}
}
```
Now, i got a null in SkBitmap.Decode(skStream). I have changed the path also. it doesn't work well

**Comment by mattleibow** [comment]
I am closing this as this is an old issue and there are some causes:
 - is the image marked as **Embedded Resource**?
 - is the image embedded in the **same** assembly as the type returned by `GetType()`?

Assuming the above is true (and the image is valid), then this should work:

```csharp
string resourceID = "Helloworld.Media.icon.png";
Assembly assembly = GetType().GetTypeInfo().Assembly;
using (Stream stream = assembly.GetManifestResourceStream(resourceID))
{
    resourceBitmap = SKBitmap.Decode(stream);
}
```

NOTE: no need for `SKManagedStream` anymore - it is done internally.
