### ISSUE TITLE
UWPSample - cannot create instance of SKSwapChainPanel

### ISSUE THREAD

**Issue by TomTuttle** [mono/SkiaSharp#344]
I got the latest SkiaSharp code.  The solution - UWPSample - under 'samples/UWPSample' has a run time issue.  It builds fine.  However, when I deploy and run I get the error message, 

> An exception of type 'Windows.UI.Xaml.Markup.XamlParseException' occurred in SkiaSharpSample.UWPSample.exe ...
> 
> WinRT information: Cannot create instance of the type 'SkiaSharp.Views.UWP.SKSwapChainPanel' [Line 57 Position: 147]

So, there's an issue with line 57 in the MainPage.xaml.  The line is, 

`<views:SKSwapChainPanel x:Name="glview" Grid.Row="1" PaintSurface="OnPaintGL" DrawInBackground="True" Visibility="Collapsed" />`

If I comment this line out, and then go over to MainPage.xaml.cs and comment out the four references to 'glview', then I can run the sample, and it appears there are no issues.  But, I'd really like to know what the cause of the error is so I don't have to work around it.  Anyone know what is causing this?

**Comment by mattleibow** [comment]
Closing this issue as it is old and the problem appears to have been fixed at some point.
