### ISSUE TITLE
Underline text not available

### ISSUE THREAD

**Issue by drobdymo** [mono/SkiaSharp#345]
In newer versions of SkiaSharp, the SKPaint property UnderlineText is not available. Is this something that was removed intentionally?

**Comment by mattleibow** [comment]
Unfortunately this feature was removed by Google - entirely:

 - https://github.com/google/skia/commit/a01bf9ab748836fc4bf271bd5024151bf1ce2e88

You may want to discuss this with Google (https://groups.google.com/forum/#!forum/skia-discuss) s I am not sure what the best way to do this is.

**Comment by mattleibow** [comment]
I am closing this as skia does not support this anymore.
