### ISSUE TITLE
SKTypeface.FromFamilyName fails with space-separated names 

### ISSUE THREAD

**Issue by joreg** [mono/SkiaSharp#346]
helo,

i'm on windows Desktop trying to use `SKTypeface.FromFamilyName("Lucida Sans Unicode")` but i only get a default typeface ("Segoe UI") back. when i try with a single word like "Arial" i get the correct typeface.

i also checked with `SKFontManager.Default.GetFontFamilies();` and it actually has "Lucida Sans Unicode" listed as available type family.

is there anything i could be doing wrong?

**Comment by joreg** [comment]
sorry, human error!

**Comment by mattleibow** [comment]
What was the issue at the end? Did it have anything to do with SkiaSharp at all?

**Comment by joreg** [comment]
sorry for the noise, it was really just me being stupid. 
i tried:
```
var family = Font.FontFamily.ToString();
var typeface = SKTypeface.FromFamilyName(family);
```
and didn't see that the `family` included more than the actual fonts name... correct is:
`var family = Font.FontFamily.Name;`
