### ISSUE TITLE
SkiaSharp.Views.Forms crashes on Android x86 on startup

### ISSUE THREAD

**Issue by entdark** [mono/SkiaSharp#349]
Hello.
An app with SkiaSharp.Views.Forms crashes on Android x86 on startup with the following messages:

```
Time	Device Name	Type	PID	Tag	Message
08-02 11:46:07.558	Asus _T00I	Info	574	ActivityManager	Process com.companyname.Mobile (pid 19455) has died.
08-02 11:46:07.548	Asus _T00I	Error	19455	monodroid	shared runtime initialization error: Cannot load library: 
08-02 11:46:07.548	Asus _T00I	Warning	19455	monodroid	Trying to load sgen from: /data/data/com.companyname.Mobile/files/.__override__/libmonosgen-2.0.so
08-02 11:46:07.548	Asus _T00I	Warning	19455	monodroid	Trying to load sgen from: /data/data/com.companyname.Mobile/files/.__override__/links/libmonosgen-2.0.so
08-02 11:46:07.548	Asus _T00I	Warning	19455	monodroid	Trying to load sgen from: /storage/emulated/0/Android/data/com.companyname.Mobile/files/.__override__/libmonosgen-2.0.so
08-02 11:46:07.548	Asus _T00I	Warning	19455	monodroid	Using override path: /storage/emulated/0/Android/data/com.companyname.Mobile/files/.__override__
08-02 11:46:07.548	Asus _T00I	Warning	19455	monodroid	Trying to load sgen from: /data/app-lib/com.companyname.Mobile-1/libmonosgen-2.0.so
08-02 11:46:07.548	Asus _T00I	Warning	19455	monodroid	Using override path: /data/data/com.companyname.Mobile/files/.__override__
08-02 11:46:07.538	Asus _T00I	Warning	19455	monodroid	Creating public update directory: `/data/data/com.companyname.Mobile/files/.__override__`
08-02 11:46:07.348	Asus _T00I	Debug	19455	dalvikvm	Added shared lib /data/app-lib/com.companyname.Mobile-1/libmonodroid.so 0x438f7b10
08-02 11:46:07.338	Asus _T00I	Debug	19455	dalvikvm	Trying to load lib /data/app-lib/com.companyname.Mobile-1/libmonodroid.so 0x438f7b10
```
When SkiaSharp.Views.Forms is unloaded then it loads the app fine.

I've tried it with both shared (SkiaSharp.Views.Forms is added to Android project) and PCL (SkiaSharp.Views.Forms is added to PCL project only) projects.

Model: ASUS Zenfone 4
Version: Android 4.4.2
CPU: Intel Atom x86

Maybe it's related to Android version but I think the reason is the ABI x86.

**Comment by entdark** [comment]
Just tested on Genymotion emulator Android 4.4.4 x86 and it was fine.
Also tested on SDK emulator Android 4.4.2 x86 and it was fine.

So I guess the issue is related to exactly that model of smartphone.

**Comment by entdark** [comment]
Tried a release build and got this:
```
Time	Device Name	Type	PID	Tag	Message
09-02 17:41:34.540	Asus _T00I	Info	29817	MonoDroid	UNHANDLED EXCEPTION:
09-02 17:41:34.790	Asus _T00I	Info	29817	MonoDroid	System.DllNotFoundException: libSkiaSharp.so
  at (wrapper managed-to-native) SkiaSharp.SkiaApi:gr_glinterface_create_native_interface ()
  at SkiaSharp.GRGlInterface.CreateNativeGlInterface () [0x00000] in <4037cd6aae714b3695104f4ec98e1b3b>:0 
  at SkiaSharp.Views.Android.SKGLSurfaceViewRenderer.OnSurfaceCreated (Javax.Microedition.Khronos.Opengles.IGL10 gl, Javax.Microedition.Khronos.Egl.EGLConfig config) [0x0005a] in <780a5d92ee6848a4ae3dc605986cb602>:0 
  at Android.Opengl.GLSurfaceView+IRendererInvoker.n_OnSurfaceCreated_Ljavax_microedition_khronos_opengles_GL10_Ljavax_microedition_khronos_egl_EGLConfig_ (System.IntPtr jnienv, System.IntPtr native__this, System.IntPtr native_gl, System.IntPtr native_config) [0x00017] in <e4b8e16d0f8049b2a663baf20e68cb8d>:0 
  at (wrapper dynamic-method) System.Object:de5aed66-d7d1-4ec1-993c-dff7c925ebbf (intptr,intptr,intptr,intptr)
```
Seems like it fails to load the skiasharp shared object for some reason.

**Comment by entdark** [comment]
It fails to load the shared object because it's missing on my device:
![Missing libSkiaSharp.so](https://i.imgur.com/nyrcoBv.png)
But it is always presented on other devices:
![Presented libSkiaSharp.so](https://i.imgur.com/EXUOsJq.png)

**Comment by entdark** [comment]
Alright, this is so weird.
I tried to manually copy `libSkiaSharp.so` into `[bundle]/lib/` from the apk from `/lib/x86/` since I have 
an x86 CPU.
It failed to load it again.

Then I decided to try an alternative ABI but before that I decided to just display my main and alt ABIs by using `Android.OS.Build.CpuAbi + ", " + Android.OS.Build.CpuAbi2`.
And I got the following displayed:
`armeabi-v7a, armeabi`
What? No x86 at all?

Then I decided to copy `libSkiaSharp.so` again but from the apk from `/lib/armeabi-v7a/` this time.
And it started finally working.

The solution for personal use is ofc fine but I need one for public distribution.

Now I think during installation it tries to copy an x86 lib since the CPU is x86 then it fails some internal check for `Android.OS.Build` ABI because it's either `armeabi-v7a` or `armeabi` so it doesn't copy anything at all.
By the way, `libSkiaSharp.so` is also missing in the apk in `/lib/armeabi/`.

Any thought on how to handle that?

P.S.: sorry for the wall of replies on this issue.

**Comment by entdark** [comment]
Finally made it working out of the box.
In project settings I had set supported architectures to: armeabi, armeabi-v7a, x86, x86_64, arm64-v8a.
Then I changed them to: armeabi, armeabi-v7a, arm64-v8a.
And it started working.

I hope my investigation was useful.

**Comment by mattleibow** [comment]
Interesting.
I see your new list does not have x86, but your CPU is x86? What happens if you remove armeabi, armeabi-v7a and just leave arm64-v8a?

What is interesting is that your x86 CPU is saying it is arm. Maybe the box is a lie :)

**Comment by entdark** [comment]
I does not let me to install the APK at all.
Intel Atom x86 can emulate ARM with libhoudini: https://stackoverflow.com/a/31047743

**Comment by entdark** [comment]
It gets even more weird because I tried a blank Android project and got this:
![x86, armeabi-v7a](https://i.imgur.com/uR5LgaL.png)
I also tried a new Forms app and got the same result: `x86, armeabi-v7a`.
My project is on Forms.

**Comment by entdark** [comment]
When I don't reference SkiaSharp.Views.dll and SkiaSharp.dll:
![x86, armeabi-v7a](https://i.imgur.com/pKTVJ6z.png)
When I do reference them:
![armeabi-v7a, armeabi](https://i.imgur.com/5KhNw8V.png)

And I think It's because you SkiaSharp does not specify supported ABIs in `Release` (I was on `Release`, it crashes on `Debug` w/o a single message.): https://github.com/mono/SkiaSharp/blob/master/source/SkiaSharp.Views/SkiaSharp.Views.Android/SkiaSharp.Views.Android.csproj#L20-L40
Only `Debug` specifies the ABIs. By default only `armeabi-v7a` is only supported on `Release`.

**Comment by entdark** [comment]
Anything about my issue?
I'd like to use x86 libSkiaSharp.so on x86 CPU.
But for some reason referencing SkiaSharp.dll and its children makes the app think it needs arm SOs.
Current solution is to exclude x86 out of the support ABIs on the app level, so it forces to load arm SOs which the CPU can emulate to work with. But the startup time increases.
Maybe I could try something myself?

**Comment by deveee** [comment]
Did you find a way to fix it? I see very similar crashes in Sueprtuxkart that happen for x86 architecture on android 4.4 for exactly this phone model (and some others). And it seems to be related only to android 4.4.

It's possible that .so has some missing dependencies and that's why it fails to load. Maybe compile with older app_platform could help? No idea...

**Comment by entdark** [comment]
@deveee
Target to armeabi-v7a and exclude x86 from targets. It works because Intel Arom x86 can emulate armeabi-v7a.
But it slows down the app startup and is not a proper solution, just a workaround. You also won't be able to debug it.
Debugging only possible on x86 emulator (need to include x86 support back) or on a device with actual ARM CPU.

**Comment by deveee** [comment]
What is the message that you get when it fails to load x86 library?

I don't belive that the x86 support is totally broken, there must be a way to make it working. Maybe it just doesn't like this particular ndk platform, ndk version, sdk version, c++ library... You can try to create .so library that just prints hello world to console and then add more features, increase ndk version etc. to see what causes it.

**Comment by entdark** [comment]
>What is the message that you get when it fails to load x86 library?
The message is in my first post.
The problem is that the lib was not extracted when `APK` was installed. So it did not find the lib at all when tried to use it.

I've worked with NDK and I know how it works and yes `x86 .so` libs work on `Intel Atom x86` - tested in my own projects. I've always built my own `.so` libs with the latest NDK (since 2015 until now).
The problem is in SkiaSharp x86 lib that is not detected properly on that CPU.
I've also tried to put manually `x86 libSkiaSharp.so` to `/data/data/project/libs/` (or something) and it failed, but putting there `armeabi-v7a libSkiaSharp.so` worked fine.

**Comment by deveee** [comment]
I meant the message when the x86 library exists and it just failed to use it. Maybe that's the reason that it didn't copy it automatically during installation.

**Comment by entdark** [comment]
Okay, some magic happened.
Updated to SkiaSharp 1.59.2.
It started working.
https://images-cdn.9gag.com/photo/anYZ9Eo_700b.jpg

**Comment by entdark** [comment]
Hah, but now when I target both `x86` and `armeabi-v7a`, it installs `armeabi-v7a` and crashes after startup.

**Comment by deveee** [comment]
So emulated armeabi is default for this device? :P It can be at least fixed by making separate apks and using higher version code for x86...

Actually I wonder if you can try how STK works on this device and give me some feedback. On google play it's probably broken, because it will install the version for arm. But x86 apk is available on our website. Anyway sorry for offtopic.

**Comment by entdark** [comment]
What I also found out:
If you make a single APK with multiple targets then it fails: it displays it's detected as armeabi-v7a then crashes (on the moment when Skia starts loading).
If you make multiple APKs for every target then installing either armeabi-v7a or x86 will display the respective ABIs and won't crash for each.

**Comment by mattleibow** [comment]
Closing this issue as it appears to be device-specific or maybe an older version of Xamarin.Android.

Please re-open if still an issue.
