### ISSUE TITLE
Crash when creating new SKPath in 1.59.1

### ISSUE THREAD

**Issue by Mathieson** [mono/SkiaSharp#350]
Creating a new SKPath instance via SKPath() constructor is causing a crash in 1.59.1 in an iOS project. Haven't tested in Android.

Also tested 1.59.0, 1.58.1, and 1.58.0. Crash still present in 1.59.0, but not in either of the 1.58 versions.

**Comment by Mathieson** [comment]
Went back to v 1.59.1 to get output of the crash and was no longer able to repro. Not sure what the problem was, now. Closing.

**Comment by mattleibow** [comment]
@Mathieson There may have been an issue with the NuGets not being installed into the final app project. Or the package versions did not match.
