### ISSUE TITLE
DrawVertices not antialiased

### ISSUE THREAD

**Issue by joreg** [mono/SkiaSharp#351]
this is a screenshot from the DrawVerticesSample.cs on windows desktop:
![image](https://user-images.githubusercontent.com/1067952/28999286-4f5f17b8-7a41-11e7-96e5-47c042e69980.png)

the triangle is not antialiased even though the code sets it:
```
var paint = new SKPaint
{
   IsAntialias = true
};
```

can this be fixed?

**Comment by mattleibow** [comment]
I don't think this is currently supported:

> https://groups.google.com/forum/#!topic/skia-discuss/Os0S0X37x84
> drawVertices does not support antialiasing.

**Comment by joreg** [comment]
thanks for the pointer!

**Comment by mattleibow** [comment]
I'm closing this as this is not a feature supported by native skia.
