### ISSUE TITLE
SKImage.Encode returns null rather than throwing an Exception when wrong paramters are passed.

### ISSUE THREAD

**Issue by sherif-elmetainy** [mono/SkiaSharp#355]
I was using version 1.59.1 of the library and tried to create an image passing wrong parameters to the `SKImageInfo` constructor and when I tried to call `SKImage.Encode` the returned value was `null`. It took me a while to figure out my mistake and it would be much more helpful if the library would throw an exception on failure explaining what went wrong. I don't know if this is a Google skia issue or skiasharp issue, but since it occurred with skiasharp for me I thought I should report it here. Below is a code snippet to reproduce the problem.

```csharp
var pixelData = new byte[width * height];
unsafe
{
	fixed (byte* pixels = pixelData)
	{
		// Do something with pixel data (irrelevant to the issue)
		// I meant to pass SKColorType.Gray8 but I made a mistake and passed SKColorType.Alpha8 instead
		var imageInfo = new SKImageInfo(width, height, SKColorType.Alpha8, SKAlphaType.Opaque);
		using (var img = SKImage.FromPixels(imageInfo, (IntPtr)pixels))
		{
			var skData = img.Encode();
			// skData is null. should throw an exception
		}
	}
}
```

**Comment by mattleibow** [comment]
Thanks for reporting this. I looked into it and it is rather a limitation of the PNG encoder:
https://github.com/google/skia/blob/97598a506158baff7ba473d5c032b42b2d7a8740/src/images/SkPngEncoder.cpp#L98-L154

It appears that `Alpha8` is not supported. I think this is a limitation of the actual PNG codec.

**Comment by jvanlangen** [comment]
It's 2021 and this still is an issue.
