### ISSUE TITLE
WPFSample: SKGLControl is drawn as a red cross on Windows 7

### ISSUE THREAD

**Issue by entdark** [mono/SkiaSharp#356]
WPF.
SKGLControl is drawn as a red cross (aka painting failed).
Tried on both my and WPFSample projects.
It works fine on Windows 10.

OS: Windows 7 Ultimate x64.

**Comment by entdark** [comment]
Seems like it's related to #213.

ArgumentNullException: Argument cannot be null.
Parameter name: backendContext
>   in SkiaSharp.GRContext.Create(GRBackend backend, GRGlInterface backendContext)
>   in SkiaSharp.Views.Desktop.SKGLControl.OnPaint(PaintEventArgs e)

**Comment by v-vasilev-synergy** [comment]
This happens for me on Windows10 when a GPU is not available.
E.g. samples work correctly for me with intergrated graphics enabled
If I disable the intergrated processor graphics on my machine then the sample fails with the above exceptions.

My guess is that the Windows7 machine used an older processor without integrated/dedicated graphics, and OpenGL failed to load

**Comment by mattleibow** [comment]
I believe that is correct. I am making use of OpenTK's GLControl and that requires the use of OpenGL.
