### ISSUE TITLE
Question: how to get OpenGL backend working on linux

### ISSUE THREAD

**Issue by DanWBR** [mono/SkiaSharp#357]
Hi,

How can I get an OpenGL context on Linux/GTK#? I've tried encapsulating a SKSurface inside an OpenTK.GLWidget (GTK#), but GRGlInterface.CreateNativeGlInterface() always return null, even if the OpenGL graphics context (X11) is created and initialized correctly by the GLWidget.

I've already searched through skia forums and other sites. I suspect that skia doesn't have a GRGlInterface generator for Linux, is that correct? 

My native library was compiled with all GPU bits enabled.

CPU drawing is working nicely on Linux/GTK# through a Gtk.EventBox. 

Thanks in advance.

**Comment by DanWBR** [comment]
Nevermind, I've managed to get it working on a VMWare Ubuntu VM, it seems to be an issue with Ubuntu running on Parallels Desktop, even with vm tools installed.

Really cool to see SkiaSharp using the GPU on all platforms!

![skia_gl_linux_gtk](https://user-images.githubusercontent.com/2669419/29498976-cf3bc46a-85d4-11e7-8199-9a9a9e0803f0.jpg)

**Comment by mattleibow** [comment]
I also noticed the dodgy GPU for linux in mac. It appears to work for linux in hyper-v on Windows.
