### ISSUE TITLE
SKTypeface.FromFamilyName returns inconsistent result

### ISSUE THREAD

**Issue by edamron** [mono/SkiaSharp#360]
I have a service backing a .NET Core Web API that generates images from text (i.e., a picture of the given text).  I have a small method that returns the appropriate SKTypeface, based on the inputs of font family name, bold, and italic.

The first few lines of this method are as follows:

        private static SKTypeface getNewTypeface(FontSettings fontSettings)
        {
            Console.WriteLine(
                $"getNewTypeface (bold: {fontSettings.bold}, italic: {fontSettings.italic})");

            if (!string.IsNullOrWhiteSpace(fontSettings.familyName))
            {
                return SKTypeface.FromFamilyName(fontSettings.familyName,
                    fontSettings.bold ? SKFontStyleWeight.Bold : SKFontStyleWeight.Normal,
                    SKFontStyleWidth.Normal,
                    fontSettings.italic ? SKFontStyleSlant.Italic : SKFontStyleSlant.Upright);
            }

            ...
        }

After three or four tries, I encounter the following situation:
- fontSettings.familyName is a valid family name (e.g., "Helvetica")
- the Console.WriteLine shows "bold: True" and "italic: True"
- the returned SKTypeface.Style is "Italic"

Any thoughts on what might be happening?

Thank you...

**Comment by mattleibow** [comment]
What platform is this?

I did a check on Windows and Mac and both return BoldItalic. What may also be different is the Weight, mine is 700 (bold).

**Comment by edamron** [comment]
.NET Core (standard 1.1) / Kestrel, developing / debugging on the latest Mac OS.

**Comment by mattleibow** [comment]
I can't report this on my mac. Here is my sample:

[Archive.zip](https://github.com/mono/SkiaSharp/files/1271063/Archive.zip)

Does this work for you? If so, could you share some code.

**Comment by mattleibow** [comment]
Closing this as this is an old issue and no response.

**Comment by shshshdy** [comment]
me too! i input "SimSun" trun to  "Helvetica"
