### ISSUE TITLE
Unable to create 8 bit image

### ISSUE THREAD

**Issue by justincersey** [mono/SkiaSharp#363]
I'm working on a simple scenario of creating a filled rectangle, opening a png file and placing it on top of the rectangle and then saving the image as a png. This works, but I am unable to get the outputted file to have a bit depth of 8. It is currently at 32 bits.

I have tried creating an 8 bit SKSurface by setting the SKColorType to Index8 and Alpha8. With Index8 I get null for the surface. With Alpha8 the surface is created, but surface.Snapshot().Encode() returns null.

Also, I am reading in the png file using SKBitmap.Decode(filePath). This results in a SKBitmap with a ColorType of SkiaSharp.SKColorType.Bgra8888.

How can I get an 8 bit output image in this scenario? Thanks.

**Comment by mattleibow** [comment]
Some limitations:
 - `SKImage.Encode` does not support encoding `Alpha8` as this appears not to be supported by .png. To get around this, you may want to use a `Grey8` - it is not the same thing, but can be saved.
 - `SKSurface` cannot be constructed with `Index8` as this is not a color type supported by `SKSurface`. However, you can create a `SKBitmap` - but you will have to provide a color table.

As you noted, the index-8 bitmap can be loaded and draw fine. When I load an index-8 image, my color type is `Index8` - with a color table. (https://user-images.githubusercontent.com/1096616/30549940-5eb294ca-9c96-11e7-9fac-b252fb9275ec.png)

To work with index-8 bitmaps, you can do something like this:

```csharp
var bitmap = new SKBitmap(info, colorTable);

// process the bitmap

var image = SKImage.FromBitmap(b);
var data = image.Encode();

using (var stream = File.OpenWrite(@"C:\Users\mattl\Pictures\new.png"))
    data.SaveTo(stream);
```

The only thing with this is that a surface and canvas can't be used as they don't support index-8 color types.

**Comment by migueldeicaza** [comment]
Matthew, let us make sure the documentation reflects this information.
