### ISSUE TITLE
Failed : SkiaSharp.Tests.SKPathTest.ParsePathReturnsValidPath

### ISSUE THREAD

**Issue by BasileBerckmoes** [mono/SkiaSharp#364]
Im new to app development and trying to install skiasharp for a simple 2D game but I can't figure out how to fix failing test. I attached the log file, you can find the error at the bottom of the txt file.

1) Failed : SkiaSharp.Tests.SKPathTest.ParsePathReturnsValidPath
  Expected: not null
  But was:  null
  at SkiaSharp.Tests.SKPathTest.ParsePathReturnsValidPath () [0x0001f] in <e351613cdc8f47c49fd1a7f0cc3d2fbb>:0 

[Skiasharp_install_log.txt](https://github.com/mono/SkiaSharp/files/1288075/Skiasharp_install_log.txt)

**Comment by mattleibow** [comment]
All the tests pass for me.

What exactly are you trying to do? If you are just installing SkiaSharp, rather use the NuGets:
 - https://www.nuget.org/packages/SkiaSharp
 - https://www.nuget.org/packages/SkiaSharp.Views
 - https://www.nuget.org/packages/SkiaSharp.Views.Forms

If you are trying to build SkiaSharp from scratch, what platform are you building on? And, have you made any changes to the native code?
