### ISSUE TITLE
Building SkiaSharp needs mono on Linux?

### ISSUE THREAD

**Issue by j-hudecek** [mono/SkiaSharp#368]
When following the README I get this error:

    $ ./bootstrapper.sh -t everything
    using local cake.packages.config...
    Downloading NuGet...
    ./bootstrapper.sh: line 93: mono: command not found
    Could not restore NuGet tools.

I have .NET Core 2.0 installed. I'm running CentOS 7

**Comment by masoud-al** [comment]
Please refer to https://github.com/mono/SkiaSharp/wiki/Building-on-Linux
The instruction works for Linux 32 and 64 but not for ARM.

**Comment by j-hudecek** [comment]
ok

**Comment by mattleibow** [comment]
I was looking into getting a pure native Makefile:
 - issue: https://github.com/mono/SkiaSharp/issues/311
 - PR: https://github.com/mono/SkiaSharp/pull/369

But, this was extra work, and I am not that up to standard with make. Obviously we accepts PRs and help. Most of the time, you should be able to install the NuGet from nuget.org, and then just include your own native build of the libSkiaSharp.so for whatever distro/architecture you are running.
