### ISSUE TITLE
Drawing Text with SkiaSharp creates ugly artifacts in image

### ISSUE THREAD

**Issue by hot33331** [mono/SkiaSharp#371]
I created an app in which I want to display text on top of google maps. I chose to use custom markers, but they can only be images, so I decided to create an image from my text utilizing SkiaSharp.

    private static ImageSource CreateImageSource(string text)
    {
        int numberSize = 20;
        int margin = 5;
        SKBitmap bitmap = new SKBitmap(30, numberSize + margin * 2, SKImageInfo.PlatformColorType, SKAlphaType.Premul);
        SKCanvas canvas = new SKCanvas(bitmap);

        SKPaint paint = new SKPaint
        {
            Style = SKPaintStyle.StrokeAndFill,
            TextSize = numberSize,
            Color = SKColors.Red,
            StrokeWidth = 1,
        };

        canvas.DrawText(text.ToString(), 0, numberSize, paint);
        SKImage skImage = SKImage.FromBitmap(bitmap);
        SKData data = skImage.Encode(SKEncodedImageFormat.Png, 100);
        return ImageSource.FromStream(data.AsStream);
    }

The images I create however have ugly artifacts on the top of the resulting image and my feeling is that they get worse if I create multiple images.
Here's an example of the artifacts: https://i.stack.imgur.com/60vC9.png
I built an example app, that shows the artifacts and the code I used to draw the text. It can be found here: https://github.com/hot33331/SkiaSharpExample

**Comment by mattleibow** [comment]
@hot33331 The chances are you are not clearing the canvas/bitmap first.

You can either do `bitmap.Erase(SKColors.Transparent)` or `canvas.Clear(SKColors.Transparent)` (you can use any color).

The reason for this is performance. When creating a new bitmap, the computer has no way of knowing what background color you want. So, if it was to go transparent and you wanted white, then there would be two draw operations to clear the pixels (and this may be very expensive for large images).

During the allocation of the bitmap, the memory is provided, but the actual data is untouched. If there was anything there previously (which there will be), this data appears as colored pixels.

**Comment by hot33331** [comment]
Thanks a bunch Matt! That fixed it for me!!
