### ISSUE TITLE
SKGLView darker than SKCanvasView

### ISSUE THREAD

**Issue by EricTetz** [mono/SkiaSharp#372]
Swapping SKGLView in for SKCanvasView, changing nothing else in the code (in particular, the exact same draw routine), results in 60% darker output.

        
        <skia:SKGLView PaintSurface="OnCanvasViewPaintSurface" />

![](https://us.v-cdn.net/5019960/uploads/editor/8d/owa3v1i6ept0.png "")

**Comment by yinyue200** [comment]
I think the issue is the same as #299

**Comment by mattleibow** [comment]
This is a problem with the styling you are using, see: https://github.com/mono/SkiaSharp/issues/299#issuecomment-331990904
