### ISSUE TITLE
Cake.FileHelpers version in build.cake

### ISSUE THREAD

**Issue by masoud-al** [mono/SkiaSharp#373]
The Cake.FileHelpers nuget package version 2.0.0 causes the following error in the Cake build on both Windows and Linux.

**Could not find any assemblies compatible with .NETFramework,Version=v4.5.**

The workaround for the moment is to modify build.cake change 

`#addin "Cake.FileHelpers"`
to
`#addin nuget:?package=Cake.FileHelpers&version=1.0.4`

**Comment by mattleibow** [comment]
Thanks for reporting this.
