### ISSUE TITLE
StrikeThruText property is missing from SKPaint

### ISSUE THREAD

**Issue by Craig-TSS** [mono/SkiaSharp#374]
The SKPaint documentation indicates there should be a property called StrikeThruText, which is obviously to enable strike through when rendering text. This property is completely missing from the actual SKPaint class.

**Comment by mattleibow** [comment]
Thanks for logging this issue, but unfortunately this is something that we are going to have to deal with as the consumers of SkiaSharp. Google, for whatever reason, just decided that they don't want that feature and removed it. It no longer exists on the native API and thus disappears from the managed API as well.

According to the docs: https://developer.xamarin.com/api/property/SkiaSharp.SKPaint.StrikeThruText/

> Assembly Versions: 1.54.0.0, 1.54.0.0, 1.55.0.0, 1.56.0.0, 1.57.0.0

This indicates that it only exists up to v1.57.x.x.

And just to point fingers, here is Google's commit to remove a feature: https://github.com/google/skia/commit/a01bf9ab748836fc4bf271bd5024151bf1ce2e88

Here are some more comments right from Google:
> In Skia the text decorations (underline and strike-through) only affect drawText calls, and this is done mostly just for backward compatibility and will probably be removed soon. Text decoration can get quite complex with layout, and since different users will disagree about what the behavior should be it's best that the user do the drawing.


That's it! Gone! Sorry about that, I am in as much pain as you are.

**Comment by Craig-TSS** [comment]
Thanks for clearing that up Matthew.
