### ISSUE TITLE
System.ObjectDisposedException when using type fonts loaded from resource

### ISSUE THREAD

**Issue by bay0fred** [mono/SkiaSharp#376]
Hi Matthew,

i have a problem with type fonts loaded from embedded resources and using them in an SKDocument.
I my application i use different type fonts to draw text on the canvas. The type fonts are added as embedded resources and loaded via SKTypeface.FromStream(). As soon as my application reaches the memory limit and the garbage collector gets activated the application crashes with the following exception:

System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'SKManagedStream: -1736448144'.

Here is a repro project to demonstrate the behavior:

[SkiaSharpManagedStreamBug.zip](https://github.com/mono/SkiaSharp/files/1333677/SkiaSharpManagedStreamBug.zip)

I am using version 1.59.1

best regards
Frederik

**Comment by mattleibow** [comment]
Thanks for reporting this. I believe I have located the cause, now working on a solution.

**Comment by mattleibow** [comment]
Closed with the merge of https://github.com/mono/SkiaSharp/pull/386
