### ISSUE TITLE
SKCanvasView in Viewcell does not redraw automatically when it's appeared. (iOS)

### ISSUE THREAD

**Issue by benevbright** [mono/SkiaSharp#378]
Testing enviroment.
XF ver : 2.4.0.280 stable
Skiasharp : 1.59.1
Xamarin.iOS : 11.0.0.0

- ListView.xaml
CachingStrategy="RecycleElement" ON

- ViewCell.xaml
```
<ViewCell>
  <AbsoluteLayout>
    <StackLayout>
      <SKCanvasView>
    </StackLayout>
  </AbsoluteLayout>
</ViewCell>
```

When I scroll down to bottom and back, SKCanvasView does not redraw correctly.

Workaround : 
If I call mySKView.InvalidateSurface(); in OnAppearing() in the VIewCell, it works correctly.
But I don't know if it's necessary.

**Comment by benevbright** [comment]
I guess there are changes on new XF release.

**Comment by mattleibow** [comment]
Closing this as this is working as designed.

Both native and Xamarin.Forms cells do not automatically redraw when scrolling into view. Often it is the case that cells do not change when scrolling (subviews may) and view redraws are not needed. 

Your current logic to redraw the cell when it appears is correct.
