### ISSUE TITLE
Make SkiaSharp.Views.Forms support Xamarin Forms Gtk#

### ISSUE THREAD

**Issue by yinyue200** [mono/SkiaSharp#379]
Xamarin Forms Gtk# Preview nuget package is on https://www.myget.org/F/xamarinforms-dev/api/v3/index.json

Thanks

> VS bug [#727964](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/727964)

**Comment by siebigteroth** [comment]
Any updates on this? I'm quiet interested on the progress :-)

**Comment by mattleibow** [comment]
I will be starting this soon as part of the v1.60.1 release. The v1.60.0 does have the raster-based widget `SKWidget` already in the package.

One thing that I need to consider is the GPU-based view. I see I need to use a newer version of OpenTK that is not available on NuGet, and at the same time, there is an OpenTK bundled in Xamarin.Forms.

So far I have not really looked into this, but what I might do is not provide a GPU-based widget for the platform package (at least not yet), and then base the `SKGLView` off the existing OpenGL view in Xamarin.Forms.

**Comment by siebigteroth** [comment]
Thanks for the feedback and the great work! 👍 

I also got stuck at OpenGL when I took a look at this this weekend. OpenTK's GLWidget looked promising, but this is only available for OpenTK-3.0.0-pre, which requires gtksharp3, which Xamarin doesn't use :-/

**Comment by mattleibow** [comment]
Yeah. Xamarin.Forms bundles their own assemblies that they build somewhere.

**Comment by siebigteroth** [comment]
No plans for 1.60.1?

**Comment by mattleibow** [comment]
Moving this to v1.60.3 so we can get out a version that fixes a UWP bug (#536)

**Comment by hflexgrig** [comment]
Please can someone help me with custom renderer, until this will be fixed in future releases ?

**Comment by lmcdougald** [comment]
Worth noting that Xamarin.GTK now requires OpenTK 3+, so that roadblock shouldn't be a factor anymore.

**Comment by mattleibow** [comment]
I am hoping to get these views in sometime soon. Let me move this to v1.68.2 so we can track this a bit more visibly.
