### ISSUE TITLE
Request for WPF sample

### ISSUE THREAD

**Issue by mgnslndh** [mono/SkiaSharp#38]

**Comment by 8** [comment]
Hi,

I've just tried figuring it out myself and I've come up with a blog post and an example application.

SkiaSharp Wpf Example Application:
https://github.com/8/SkiaSharp-Wpf-Example

Accompanying Blog post:
http://lostindetails.com/blog/post/SkiaSharp-with-Wpf

Maybe it's of help for you.

Take care,
Martin

**Comment by mgnslndh** [comment]
Thanks for sharing your implementation @8 ! I've also been looking at https://github.com/impsnldavid/skiasharpwpfextensions by @impsnldavid. I like how his solution is based on a SkiaControl which handles recreation of the WriteableBitmap when the control size changes and how it hides some of the plumping from the derived type where you put the actual drawing logic. 

I see you use the CompositionTarget for rendering but I am not sure which implementation is most performant. If you like, please take a look at https://github.com/impsnldavid/skiasharpwpfextensions and perhaps it gives you inspiration to evolve your solution. Maybe it is possible to combine the solutions and come up with an improvement.

By the way, your handle is awesome :)

**Comment by mattleibow** [comment]
I have added a sample in the new release v1.54.1
