### ISSUE TITLE
How cant convert ImageSource to FileImageSource

### ISSUE THREAD

**Issue by Urien2017** [mono/SkiaSharp#380]
Assembly assembly = GetType().GetTypeInfo().Assembly;
            Stream stream = assembly.GetManifestResourceStream("TicTacToe.wallpaper.jpg");
            SKManagedStream skStream = new SKManagedStream(stream);
            SKBitmap skBitmap = SKBitmap.Decode(skStream);

            SKImageInfo info = new SKImageInfo(200, 200);
            var pieceBitmap = new SKBitmap(info);

            using (var canvas = new SKCanvas(pieceBitmap))
            {
                canvas.DrawBitmap(skBitmap, 0, 0);
            }

            var streamPiece = new MemoryStream();

            try
            {
                pieceBitmap.LockPixels();
                IntPtr p;
                IntPtr pixels = pieceBitmap.GetPixels(out p); 
                using (var img = SKImage.FromPixels(pieceBitmap.Info, pixels, pieceBitmap.Width * pieceBitmap.BytesPerPixel))
                {
                    var data = img.Encode(SKEncodedImageFormat.Png,300);
                    data.SaveTo(streamPiece);
                    imageSource = ImageSource.FromStream(() => streamPiece);
                }
            }
            finally
            {
                pieceBitmap.UnlockPixels();
            }
            buttonA.Image = (FileImageSource)imageSource; // InvalidCastException in this line

**Comment by mattleibow** [comment]
What you are doing is not correct - `ImageSource.FromStream` will return a `StreamImageSource`.

I would suggest making use of the conversion types provided by the NuGet packages:

 - SkiaSharp.Views
 - SkiaSharp.Views.Forms

For Xamarin.Forms, you should just be able to cast it and it will automatically convert the bitmap into an image source (https://developer.xamarin.com/api/type/SkiaSharp.Views.Forms.SKBitmapImageSource):

    buttonA.Image = (SKBitmapImageSource)pieceBitmap;

In addition to this, you can easily convert from a bitmap into an image:

    SKImage image = SKImage.FromBitmap(pieceBitmap);

Also, you can just encode a bitmap:

    SKPixmap pixmap = pieceBitmap.PeekPixels();
    SKData data = pixmap.Encode(SKEncodedImageFormat.Png, 100);

There are several image source types that may interest you:
 - `SKBitmapImageSource`
 - `SKImageImageSource`
 - `SKPictureImageSource`
 - `SKPixmapImageSource`

**Comment by Urien2017** [comment]
THANKS!!

**Comment by skima** [comment]
I have issue with convert SKBitmapImageSource to FileImageSource

`
public SKBitmapImageSource TestFileImageSource { get; set; }

// read file
            Stream stream = ImageService.Instance
                .LoadEmbeddedResource($"resource://DemoXamarin.UI.Resources.UserIcon.svg?assembly=DemoXamarin.UI")
                .WithCustomDataResolver(new SvgDataResolver(200, 200))
                .CacheKey($"DemoXamarin.UI.Resources.UserIcon.svg")
                .AsPNGStreamAsync().Result;

            SKManagedStream skStream = new SKManagedStream(stream);
            SKBitmap skBitmap = SKBitmap.Decode(skStream);

this.TestFileImageSource = (SKBitmapImageSource)skBitmap;

// using in xml
`
`<Button Image="{Binding TestFileImageSource}" BackgroundColor="Transparent"//>`
Debug log:
[0:] Binding: SkiaSharp.Views.Forms.SKBitmapImageSource can not be converted to type 'Xamarin.Forms.FileImageSource'

**Comment by mattleibow** [comment]
It appears that the `<Button>` element does not support the base `ImageSource` type for some reason:
https://developer.xamarin.com/api/property/Xamarin.Forms.Button.Image/

The `<Image>` element is fine at least.

This is a known issue with buttons and tabs and we will just have to wait. What can be done in the meantime is to just save the image to a temporary location and then pass the path to the button. This is not the most optimal, but it is what we have at this time.

**Comment by skima** [comment]
Thanks a lot for quickly answer. We will wait and make a crutch.
