### ISSUE TITLE
SKPaint.BreakText returns wrong number of characters for special unicode characters

### ISSUE THREAD

**Issue by bay0fred** [mono/SkiaSharp#381]
Hi matthew,

i noticed that the BreakText method returns the wrong number of character for special unicode characters like german umlaute. 
Some examples:
```
paint.TextEncoding = SKTextEncoding.Utf8;
paint.BreakText("ä", 50.0f); => returns 2
paint.BreakText("a", 50.0f); => returns 1

paint.TextEncoding = SKTextEncoding.Utf16;
paint.BreakText("ä", 50.0f); => returns 2
paint.BreakText("a", 50.0f); => returns 2

paint.TextEncoding = SKTextEncoding.Utf32;
paint.BreakText("ä", 50.0f); => returns 4
paint.BreakText("a", 50.0f); => returns 4
```

Best regards
Fred

**Comment by brazilianldsjaguar** [comment]
Running into this exact same problem ... why is this?

**Comment by mattleibow** [comment]
Hi @bay0fred and @brazilianldsjaguar. This is directly a result of me writing incorrect documentation, and as a result of that, I did not properly tweak the return value.

The return value is actually the NUMBER OF BYTES in the string, that is why you see the larger numbers.

**Comment by mattleibow** [comment]
I will investigate the best way to adjust this.
