### ISSUE TITLE
Adding SkiaSharp to .NET Standard projects produces many duplicate DLLs

### ISSUE THREAD

**Issue by chamons** [mono/SkiaSharp#383]
Originally in: https://bugzilla.xamarin.com/show_bug.cgi?id=60353

When I add SkiaSharp to a .NET standard project, the project tree gets overrun with DLLs, and DYLIBs (SO files are missing, where could they be?). Please see attached project and screenshots.

There are several bugs here:

1. Libraries shouldn't display their native file dependencies. I don't see Android support libs, Xamarin iOS, sqlite-raw, or any other native library wrappers showing their dependencies in the tree.

2. There's duplication in the tree: the same DLL shows up multiple times (along with its config files).

3. When compiling, there are duplicate output DLLs. libSkiaSharp.dll shows up no less than 3 times in the bin directory. Once at root, and twice on x86 and x64. 64-bit Intel has been mainstream for 10 years now - maybe we can drop at least the 32-bit version?

I understand you are shipping at least 2 * 3 platforms here (32-bit/64-bit, Linux/Mac/Windows) - but they shouldn't appear in the project tree. And please fix the naming in the bin directory so I actually know what to ship. As it is, I have no idea which of these DLLs actually needs to be deployed with my app.

If you need examples on how to package better, please look at Eric Sink's sqlite-raw. He is covering even more complex scenarios than you and never spills out these implementation details.

[TestSkia.zip](https://github.com/mono/SkiaSharp/files/1411732/TestSkia.zip)
![screenshot 2017-10-24 09 26 24](https://user-images.githubusercontent.com/6392201/31957169-7e21c572-b8b3-11e7-9d19-ee19c5e651bf.png)
![screenshot 2017-10-24 09 24 30](https://user-images.githubusercontent.com/6392201/31957172-80741758-b8b3-11e7-9a20-984b2ce22396.png)

**Comment by mattleibow** [comment]
This should not happen. I tested on VS2017 and VS4Mac 7.2 and this does not happen:

<img width="639" alt="screen shot 2017-10-24 at 8 22 05 pm" src="https://user-images.githubusercontent.com/1096616/31961018-d7ce4e7e-b8f9-11e7-9cde-71ca9de795fc.png">

I also downloaded your project, and this is not the case:

<img width="324" alt="screen shot 2017-10-24 at 8 28 51 pm" src="https://user-images.githubusercontent.com/1096616/31961355-c74c2ff2-b8fa-11e7-90e3-39e991ff04d7.png">

**Comment by praeclarum** [comment]
I updated my VSM and it now shows that structure @mattleibow 

Yes this is much better.

But I'm still getting duplicate dlls. I have 3 copies of `libSkiaSharp.dll`

**Comment by mattleibow** [comment]
Maybe remove the nuget and re-add. delete the obj/bin. When I build, I don't get any native bits:

<img width="503" alt="screen shot 2017-10-24 at 8 55 21 pm" src="https://user-images.githubusercontent.com/1096616/31962383-b0edcce0-b8fd-11e7-986a-e4cf63d48853.png">

**Comment by praeclarum** [comment]
I'm sorry, I left off an important detail: I'm consuming the library from an additional classic project (so that unit tests work in VS). That project is getting the 3 copies.

You're right, the standard project is free of native libs. You can close this since I won't waste your time supporting classic .NET projects.

**Comment by mattleibow** [comment]
classic .net project will copy all the dlls because there is no way to determine what platforms the app will run on. you should be able to take the output of a classic library/app and run in on ANY windows and ANY mac (with mono) without changes. The output folder is the final product that works everywhere - write once, run anywhere

**Comment by mattleibow** [comment]
also, the new vs2017 update adds support for unit tests in .net core apps/test libraries (yay)

**Comment by praeclarum** [comment]
I'm on VS for Mac and it only seems to work with Classic NUnit 2.x. :-(

**Comment by mattleibow** [comment]
ah. that bug
There is a fix in master so the test runner can understand <ProjectReference>
