### ISSUE TITLE
SKGLView rendered over MasterDetailPage [Android]

### ISSUE THREAD

**Issue by VitoTringolo** [mono/SkiaSharp#392]
Hi!!!

When i try to use the SKGLView with the MasterDetailPage the canvas is drawn over the Master page.
Currently i am using the MasterBehavior="Popover" behavior for the Master page.

The problem is present only on Android and it vanish if you start the application with the property IsPresented="True" in this case all works like a charm

Attached you can find the test project. In the test i am using Prism but the same problem is present also without it.
[TestSKGL.zip](https://github.com/mono/SkiaSharp/files/1443493/TestSKGL.zip)

**Comment by mattleibow** [comment]
This is an issue with Android as an OS, and I need to make use of the new `TextureView`: https://github.com/mono/SkiaSharp/issues/263
