### ISSUE TITLE
I‘ve build this project in ubuntu.16.04-x64

### ISSUE THREAD

**Issue by miao17game** [mono/SkiaSharp#393]
I'm new to linux.
I've build this project in my server (ubuntu.16.04-x64), the build result is in "SkiaSharp/externals/skia/out/linux/x64", but i don't know that to do next.

I want to run a docker container with skiaSharp
I meet a error "unable to load 'libSkiaSharp.dll'" when i use image compress and SKBitmap.Draw() in my application before, so i try to build this project in linux.
what should I do next?

**Comment by mattleibow** [comment]
You will have to copy the libSkiaSharp.so into the output directory of the app - next to the .exe/.dll. Then you can run it as normal. But, you don't need to build it yourself, you can use the pre-built binaries on each GitHub release: https://github.com/mono/SkiaSharp/releases/tag/v1.59.2

Direct link: https://github.com/mono/SkiaSharp/releases/download/v1.59.2/libSkiaSharp.so

**Comment by miao17game** [comment]
@mattleibow ！！！I don't know that there's the pre-built binaries ....... XD thanks!
