### ISSUE TITLE
Unable to stretch last row or column using DrawBitmapLattice or DrawBitmapNinePatch

### ISSUE THREAD

**Issue by baskren** [mono/SkiaSharp#395]
## Description: 
There appears to not be a way to have the last row or column be stretchable using the SKCanvas.DrawBitmapLattice or SKCanvas.DrawBitmapNinePatch methods.  I have tried this using the UWP SkiaSharp.Views NuGet package (in a Xamarin.Forms custom renderer) as well as Android, iOS, and UWP Xamarin.Forms apps using SkiaSharp.Views.Forms Nuget package.  For simplicity, a Xamarin.Forms demo app has been provided.

## Demo App: 
https://github.com/baskren/SkiaSharpStretchLastRowColumnFail

## Observations:
1. Clone, build and run demo app for the platform of your choice
2. Click [Test1] button.   Notice the position of the sliders.  This represents the start (left) and end (right) of the stretchable region.  In [Test1], the left is 0 and the right is 25.  PLEASE NOTE THAT THE FIRST COLUMN OF THE BITMAP IS STRETCHED.
3. Click the [Test2] button.  Left is 1 and right is 25.  Note:  The first column is not stretched (as it should be) and the second column is stretched.
4. Click the [Test 3] button.  Left is 25 and right is 49.  Note how this appears to be the symmetrical equivalent of [Test 2] in that the second to last column is stretched but the last column is not.
5. Click the [Test 4] button.  Left is 25 and right is 50.  NOTE THAT THE ENTIRE BITMAP IS STRETCHED - IN OTHER WORDS, THERE ARE NO PATCHES!
7.  Click on the "use DrawBitmapNinePatch" switch and repeat steps 2-5.  Note that the results are the same.

## Expectations:
1. Tests 1 and 2 work as expected.
2. Test 3 should be the case where the last column is stretched (the symmetrical equivalent of Test 1).
3. Left slider 25 and right slider 48 should be the symmetrical equivalent of Test 2 (everything between 25 and the last column- but not the last column) is stretched.

### Visual Studio:
Microsoft Visual Studio Community 2017 
Version 15.4.4
VisualStudio.15.Release/15.4.4+27004.2009
Microsoft .NET Framework
Version 4.7.02046

Installed Version: Community

Visual Basic 2017   00369-60000-00001-AA466
Microsoft Visual Basic 2017

Visual C# 2017   00369-60000-00001-AA466
Microsoft Visual C# 2017

Visual F# 4.1   00369-60000-00001-AA466
Microsoft Visual F# 4.1

Application Insights Tools for Visual Studio Package   8.9.00809.2
Application Insights Tools for Visual Studio

ASP.NET and Web Tools 2017   15.0.30925.0
ASP.NET and Web Tools 2017

ASP.NET Core Razor Language Services   1.0
Provides languages services for ASP.NET Core Razor.

ASP.NET Web Frameworks and Tools 2017   5.2.50921.0
For additional information, visit https://www.asp.net/

Azure App Service Tools v3.0.0   15.0.30915.0
Azure App Service Tools v3.0.0

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

JavaScript Language Service   2.0
JavaScript Language Service

JavaScript Project System   2.0
JavaScript Project System

JavaScript UWP Project System   2.0
JavaScript UWP Project System

Merq   1.1.17-rc (cba4571)
Command Bus, Event Stream and Async Manager for Visual Studio extensions.

Microsoft Azure Tools   2.9
Microsoft Azure Tools for Microsoft Visual Studio 2017 - v2.9.50719.1

Microsoft Continuous Delivery Tools for Visual Studio   0.3
Simplifying the configuration of continuous build integration and continuous build delivery from within the Visual Studio IDE.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual Studio VC Package   1.0
Microsoft Visual Studio VC Package

Mono Debugging for Visual Studio   4.7.4-pre (c2d89eb)
Support for debugging Mono processes with Visual Studio.

NuGet Package Manager   4.4.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit http://docs.nuget.org/.

SQL Server Data Tools   15.1.61707.200
Microsoft SQL Server Data Tools

TypeScript   2.3.5.0
TypeScript tools for Visual Studio

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

Visual Studio Tools for Universal Windows Apps   15.0.27004.2008
The Visual Studio Tools for Universal Windows apps allow you to build a single universal app experience that can reach every device running Windows 10: phone, tablet, PC, and more. It includes the Microsoft Windows 10 Software Development Kit.

VisualStudio.IoT   1.0
Package with IoT components for Visual Studio

VisualStudio.Mac   1.0
Mac Extension for Visual Studio

Xamarin   4.7.10.38 (34c1b6c)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin.Android SDK   8.0.2.1 (HEAD/c2a33d8ea)
Xamarin.Android Reference Assemblies and MSBuild support.

Xamarin.iOS and Xamarin.Mac SDK   11.3.0.47 (51128b8)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.

**Comment by mattleibow** [comment]
Thanks for reporting this.

I had a look and it appears that `DrawBitmapLattice` does not handle your scenario correctly. Under the hood, `DrawBitmapNinePatch` uses `DrawBitmapLattice` so this will also fail.

To work around this issue, I will rather expose the native `drawBitmapNine` until this bug is fixed.

I opened an issue with the native skia:
https://bugs.chromium.org/p/skia/issues/detail?id=7356

**Comment by mattleibow** [comment]
Closing this issue as it is "resolved" by using the native method with handles this case correctly. As soon as the native implementation of the lattice is fixed, it will also be fixed for the managed counterpart.
