### ISSUE TITLE
Unable to deploy on Windows 10

### ISSUE THREAD

**Issue by musictopia** [mono/SkiaSharp#396]
Included is the following code for the most simple program possible.

Imports FileFunctions.FileFunctions
Imports SkiaSharp.Views.Desktop
Imports SkiaSharp.Views.WPF
Imports SkiaSharp

Class MainWindow

    'Private WithEvents ThisDraw As SKElement
    Private WithEvents ThisBut As Button

    Public Sub New()

        ' This call is required by the designer.
        InitializeComponent()
        'Dim ThisPaint As New SKPaint
        'even doing the paint causes this as well

        ThisBut = New Button
        ThisBut.Content = "Hello"
        ThisGrid.Children.Add(ThisBut)
        'ThisDraw = New SKElement
        'ThisGrid.Children.Add(ThisDraw)
        ' Add any initialization after the InitializeComponent() call.
        'Try
        '    WriteText("C:\TempFiles\E.txt", "Hello", False)
        'Catch ex As Exception
        '    MsgBox(ex.Message)
        '    End
        'End Try
        'Dim ThisLabel As New TextBlock
        'ThisLabel.Text = "Hello"
        'ThisGrid.Children.Add(ThisLabel)
        'Dim ThisRadio As New SkiasharpControls.CustomRadioButton
        'ThisGrid.Children.Add(ThisRadio)
    End Sub

    Private Sub ThisBut_Click(sender As Object, e As RoutedEventArgs) Handles ThisBut.Click
        Dim ThisPaint As New SKPaint
        MsgBox("Good Job")
    End Sub
End Class

When I click the button, it crashes immediately on all computers except for the one I am developing one.  I even tried to install the C++ runtime files for Visual Studio 2017 and same issue.  Could not find the link for the 2015 version of it.

**Comment by migueldeicaza** [comment]
Please provide the stack trace that you get and reopen the issue.
