### ISSUE TITLE
SKBitmap.Decode return is null

### ISSUE THREAD

**Issue by xiangzLL** [mono/SkiaSharp#402]
using (var memoryStream = new MemoryStream(ImageData))
                    using (var stream = new SKManagedStream(memoryStream))
                    using (var bitmap = SKBitmap.Decode(stream))

ImageData is a byte array
why in v1.59.1 ,  bitmap always return null? 
in v1.56.0 is normal

**Comment by mattleibow** [comment]
Do you have any details on what type of image was encoded? (png, jpg)
What you can also do is to save `ImageData` to a file (just a direct write bytes) and see if the OS can read the file. It may be corrupted. I don't think skia removed any decoders, so it may be something else.

**Comment by xiangzLL** [comment]
sorry,It's my code problem, i will close this issue. Thx

**Comment by parthipanr** [comment]
@xiangzLL  I am also facing same issue. can you please let me know how you resolve this issue?

**Comment by xiangzLL** [comment]
it's my code problem,my image byte array is wrong.maybe we are not facing the same issue.
or you can show the codes, let me help you.

**Comment by Marshal313** [comment]
I'm facing the same issue using `SKBitmap.Decode(string fileName)` and strangely, the results are randomly null !
It's a lot like returning the Decode method soon without having some Async operation finished first (I'm not sure if it's using async, It just looks like that cuz it's random !)
