### ISSUE TITLE
SKBitmap issues on Ubuntu MATE for Raspberry Pi 2

### ISSUE THREAD

**Issue by DanWBR** [mono/SkiaSharp#406]
Hello,

I was able to successfully compile SkiaSharp for the RPi as detailed in #312. When running my app, the library gets loaded just fine, I see some native skia functions being called, etc etc etc until I try to create the bitmap to draw the canvas:

`System.Exception: Unable to allocate pixels for the bitmap.`

The exception is raised if I remove the using statement and put a try/catch block on here: https://github.com/DanWBR/dwsim5/blob/master/DWSIM.UI.Desktop.GTK/SkiaSharp/CanvasControl.cs#L149

The code in the above works on x86 Linux just fine.

I thought that it could be something related to the low video memory, then tried to fix the bitmap dimensions to 100x100px but it didn't help. Also tried all color types, none of them worked. Finally, I've tried to create the bitmap using the constructor which only takes the dimensions as input, but it also didn't work.

**Comment by DanWBR** [comment]
@mterwoord and @toburguer, did you manage to instantiate a SKBitmap on the RPi?

**Comment by mterwoord** [comment]
No clue, I use avalonia, which worked great!

**Comment by toburger** [comment]
Sorry, I use SkiaSharp exclusively to read image information and resize images (both via SKBitmap.Decode).
Do you have a minimal working example of your problem so I can test it out on my raspi?

**Comment by DanWBR** [comment]
@toburger just try to create a new SKBitmap using the constructor which takes only width and height as arguments. It didn't work for me.

**Comment by toburger** [comment]
I get the same error:

``Unhandled Exception: System.Exception: Unable to allocate pixels for the bitmap.``

**Comment by DanWBR** [comment]
One thing I've noticed is that @mterwoord's script compiles the 1.57.1 version of SkiaSharp, while in my app I have the 1.59.1 managed library. I've tried to update the script to compile 1.59.1 but got a lot of errors. I'll then try to use the managed 1.57.1 library and let you know if it works.

**Comment by mterwoord** [comment]
My script was targetted for building a avalonia-compatible dll.

**Comment by toburger** [comment]
I've completely forgot that I was using 1.57.1 on my project and mistakenly restored the latest SkiaSharp for this test. After using 1.57.1 the code works.

**Comment by DanWBR** [comment]
I can confirm it works fine if we use the correct managed library (1.57.1 in this case):

![](https://cdn.pbrd.co/images/GWnhdQo.jpg)

**Comment by DanWBR** [comment]
I'm closing this issue as it turned out to be the same as #377.
