### ISSUE TITLE
Cannot deploy libSkiaSharp to Windows Server 2012

### ISSUE THREAD

**Issue by atuladhar** [mono/SkiaSharp#411]
I have uploaded my application using libSkiaSharp to a server running Windows Server 2012 and the application is showing error with the libSkiaSharp dll. I have tried using libSkiaSharp for win7-x64, x86, win10-64, 86. How do I deploy to this server?

**Comment by mattleibow** [comment]
This may be a number of things:
 - you do not have the [msvc runtime](https://www.microsoft.com/en-us/download/details.aspx?id=48145) installed
 - you did not place the `libSkiaSharp.dll` alongside the `libSkiaSharp.dll` (in the same directory)
 - the bit-ness was wrong

The first two will throw a DllNotFoundException and the third will throw BadImageFormatException.
