### ISSUE TITLE
System.AccessViolationException: 'Attempted to read or write protected memory. This is often an indication that other memory is corrupt.'

### ISSUE THREAD

**Issue by shravan2x** [mono/SkiaSharp#412]
The exception:
```
System.AccessViolationException: 'Attempted to read or write protected memory. This is often an indication that other memory is corrupt.'
```

Like many others here, I have an ASP.NET Core MVC controller action that generates an image. The last few lines of this action are:
```c#
using (SKImage snapshot = surface.Snapshot())
using (SKData data = snapshot.Encode())
{
    HttpContext.Response.ContentLength = data.Size;
    return File(data.AsStream(), "image/png");
}
```

The issue is that this sometimes leads to memory corruption and crashes the entire server.

I don't have a 100% sure way of reproducing the issue, but it appears the issue goes away when the return statement is changed to use an array instead of SkiaSharp's stream `data.AsStream()` -> `data.ToArray()`.

This may be because of some backend implementation of MVC that uses async to read+write streams. I'm using the latest version of SkiaSharp 1.59.2.

**EDIT**: From what I understand reading other issues here, one possible reason for this might be that the `SKData` object is being disposed before the stream is fully read, leading to bad memory being accessed. But this feels like something SkiaSharp should handle internally.

**Comment by mattleibow** [comment]
That is correct. You are passing the stream to the response and then disposing the data that the stream contains.

The correct way is to not dispose the data, and let the stream do that (by passing `true`):

```csharp
using (SKImage snapshot = surface.Snapshot())
{
    SKData data = snapshot.Encode();

    HttpContext.Response.ContentLength = data.Size;
    return File(data.AsStream(true), "image/png");
}
```

**Comment by shravan2x** [comment]
I tried using `.AsStream(true)` like you recommended, but the issue still persists.

**Comment by mattleibow** [comment]
@shravan2x did you manage to resolve it?

**Comment by shravan2x** [comment]
@mattleibow I did indeed. It works perfect now.
