### ISSUE TITLE
The problem with publishing an application on Windows Server 2016

### ISSUE THREAD

**Issue by VladimirLuzhin** [mono/SkiaSharp#414]
Hi! I have the following problem, I'm building an application on a Windows 7 computer and publish it to a machine running Windows Server 2016. Everything works fine on the local computer, but I get the following error on the server:
`The type initializer for 'SkiaSharp.SKManagedStream' threw an exception.`
Can you help? Thank you in advance

**Comment by iamcarbon** [comment]
@VladimirLuzhin Have you installed the Visual 2015 c++ redistributable? Are you running on the standard or core version?

**Comment by mattleibow** [comment]
Make sure the [Visual C++ Redistributable for Visual Studio 2015 Update 3](https://my.visualstudio.com/Downloads?pid=2082) is installed.
