### ISSUE TITLE
How to convert byte array to SKBitmap in SkiaSharp?

### ISSUE THREAD

**Issue by parthipanr** [mono/SkiaSharp#416]
SKBitmap.Bytes is read only, any suggestion on how to Marshal.Copy a byte array to the SKBitmap? I am using using below code snippet but it not working. 

Code snippet:

            SKBitmap bitmap = new SKBitmap((int)Width, (int)Height);
            bitmap.LockPixels();
            byte[] array = new byte[bitmap.RowBytes * bitmap.Height];
            for (int i = 0; i < pixelArray.Length; i++)
            {
                SKColor color = new SKColor((uint)pixelArray[i]);
                int num = i % (int)Width;
                int num2 = i / (int)Width;
                array[bitmap.RowBytes * num2 + 4 * num] = color.Blue;
                array[bitmap.RowBytes * num2 + 4 * num + 1] = color.Green;
                array[bitmap.RowBytes * num2 + 4 * num + 2] = color.Red;
                array[bitmap.RowBytes * num2 + 4 * num + 3] = color.Alpha;
            }
            Marshal.Copy(array, 0, bitmap.Handle, array.Length);
            bitmap.UnlockPixels();

**Comment by xPaw** [comment]
I was just trying to solve the same problem, it worked for me by using `bitmap.GetPixesl()` instead of `bitmap.Handle`. However I would like to know some approach that could be used without marshalling.

**Comment by parthipanr** [comment]
does retrieving the bitmap pointer by using bitmap.GetPixels() is working properly to copy the byte array to bitmap ?

**Comment by xPaw** [comment]
It worked for me.

**Comment by mattleibow** [comment]
You will always have to do some marshaling as the bitmap lives in unmanaged/native memory and the byte array is in managed code. But, you may be able to do something like this:

```csharp
// the pixel array of uint 32-bit colors
var pixelArray = new uint[] {
	0xFFFF0000, 0xFF00FF00,
	0xFF0000FF, 0xFFFFFF00
};

// create an empty bitmap
bitmap = new SKBitmap();

// pin the managed array so that the GC doesn't move it
var gcHandle = GCHandle.Alloc(pixelArray, GCHandleType.Pinned);

// install the pixels with the color type of the pixel data
var info = new SKImageInfo(2, 2, SKImageInfo.PlatformColorType, SKAlphaType.Unpremul);
bitmap.InstallPixels(info, gcHandle.AddrOfPinnedObject(), info.RowBytes, null, delegate { gcHandle.Free(); }, null);
```

This pins the managed memory and passes the pointer to the bitmap. This way, both are accessing the same memory data and there is no need to actually do any conversions.
