### ISSUE TITLE
Developed with skiasharp and cocos2d

### ISSUE THREAD

**Issue by lovetogs** [mono/SkiaSharp#417]
I wonder if the difference between creating an application using SkiaSharp and creating an application with cocos2d is less than the fever or battery consumption. Also, I am wondering which one is better for smaller projects or large projects when developing with SkiaSharp and cocos2d.

**Comment by mattleibow** [comment]
I think this is best discussed in the forums: 
https://forums.xamarin.com/categories/skiasharp
https://forums.xamarin.com/categories/cocossharp
