### ISSUE TITLE
Support Tizen

### ISSUE THREAD

**Issue by yinyue200** [mono/SkiaSharp#418]

**Comment by mattleibow** [comment]
I am having a look at this now, but it is more of a background task at this point. If the community has had any success, then just leave a comment or share repos or any code/notes.

**Comment by mattleibow** [comment]
Just for an FYI, I saw this: https://github.com/Samsung/skia/commit/7e6c8a5a5d89559e826298a1f2c8180ef54fd03b

Not sure if it helps, but I am just collection information at this point.

**Comment by mattleibow** [comment]
And this repo: https://github.com/pld-linux/skia

**Comment by mattleibow** [comment]
Mostly hacky, but this is the first bits:
https://github.com/mono/SkiaSharp/tree/dev/tizen-support

**Comment by mattleibow** [comment]
This was added in #493 and #479
