### ISSUE TITLE
Implement SKRoundRect to support Skia feature

### ISSUE THREAD

**Issue by VitalickS** [mono/SkiaSharp#420]
As for example usage of native library, we have
```C++
SkRRect rrect;
SkVector radii[4] = {{40, 40}, {40, 40}, {40, 40}, {40, 40}};
rrect.setRectRadii(rect, radii);
```
It helps draw rounded rectangle with custom radii for each corners.
Here skia fiddle https://fiddle.skia.org/c/199fe818c09026c114e165bff166a39f

**Comment by VitalickS** [comment]
Sorry, it's my fault. it seemed to me that the skia supports the indication for different angles of the rectangle, but it is not so

**Comment by mattleibow** [comment]
I checked and they have a special type `SkRRect`. I will investigate getting this supported, but you could probably use a path in the meantime.
