### ISSUE TITLE
Default stroke-width scales incorrectly.

### ISSUE THREAD

**Issue by iansteed** [mono/SkiaSharp#421]
The line's stroke-width does not scale correctly when not specified. See example below. The SVG specification indicates stroke-width should default to a value of 1. Setting the `stroke-width="1"`
 attribute appears to be working correctly.

**SVG**
`<svg viewBox="0 0 20 20">`
`  <line x1="0" y1="0" x2="20" y2="20" stroke="#000000" />`
`  <line x1="20" y1="0" x2="0" y2="20" stroke="#000000" />`
`</svg>`

**Expected Results**
_20 x 20_
![expected-20](https://user-images.githubusercontent.com/10568040/34496391-3e04d9c0-efae-11e7-9fac-b8f37660d451.png)
_100 x 100_
![expected-100](https://user-images.githubusercontent.com/10568040/34496406-4c2861ca-efae-11e7-8d18-c21534dc5876.png)

Rendered with W3 and Chrome
(https://www.w3schools.com/graphics/tryit.asp?filename=trysvg_stroke0)

**Actual Results**
_20 x 20_
![actual-20](https://user-images.githubusercontent.com/10568040/34496623-02aad0ea-efaf-11e7-9395-3b806a25fa57.png)
_100 x 100_
![actual-100](https://user-images.githubusercontent.com/10568040/34496629-0a40841c-efaf-11e7-89ed-a41a543fffc9.png)

Rendered with the following code:
`public static SKImage ToSKImage(this SkiaSharp.Extended.Svg.SKSvg svg, SKSizeI size)`
`{`
`    var scaleX = size.Width / svg.CanvasSize.Width;`
`    var scaleY = size.Height / svg.CanvasSize.Height;`
`    var transform = SKMatrix.MakeScale(scaleX, scaleY);`
`    return SKImage.FromPicture(svg.Picture, size, transform);`
`}`

**Comment by iansteed** [comment]
Moved to SkiaSharp.Extended

**Comment by mattleibow** [comment]
Thanks for moving the issue.
