### ISSUE TITLE
XPS file doesn't release

### ISSUE THREAD

**Issue by jotab123** [mono/SkiaSharp#422]
I'm trying to create an XPS file with this code:

```
using (var document = SKDocument.CreateXps(path + "test.xps"))
{
     using (var c = document.BeginPage(800, 1000))
     {
          item.Draw(c);
          document.EndPage();
     }

     document.Close();
}
```

But test.xps file can't be open until the application is closed. The same code with CreatePdf method instead of CreateXps works.

**Comment by mattleibow** [comment]
Thanks for reporting this.

I have fixed this. A workaround would be to pass a stream instead of a path:

```csharp
using (var stream = new SKManagedWStream (File.OpenWrite (path + "test.xps"), true))
using (var document = CreateXps (stream))
{
    // ...
}
```

_NOTE: the `true` parameter tells the `SKManagedWStream` to close the managed `Stream`._
