### ISSUE TITLE
Problems constructing a long image

### ISSUE THREAD

**Issue by lambdakris** [mono/SkiaSharp#427]
I have a use case along these lines
- I have to obtain a png representing a floor map where an asset is located by asking where the asset is
- The above operation is required to work for multiple assets in one go but grouped, such that if two or more assets are in the same floor, the png will be obtained twice but rendered once
- If there are multiple distinct floor maps obtained (not every asset is on the same floor), then the floor maps should be rendered one below the other and a single image consisting of all the floor maps should be returned

Now, I tried the following approach... (warning, the code is in F# not C#, so apologies if you are not comfortable with F#, but hopefully you can make out the logic)
```fsharp
// renderPositionGroups takes a sequence of byte arrays 
let renderPositionGroups (maps: Byte array seq) =

    // get the image infos ahead of time in order to set the boundaries of the surface
    let mapBitmaps = maps |> Seq.map (fun m -> SKBitmap.Decode(m))

    // get the max width in order to set the width of the surface
    let mapMaxWidth = mapBitmaps |> Seq.map (fun m -> m.Width) |> Seq.max

    // get the total of all maps in order to set the height of the surface
    let mapTotalHeight = mapBitmaps |> Seq.sumBy (fun m -> m.Height)
    
    // initialize the surface with the max width and total height
    use surface = SKSurface.Create(mapMaxWidth, mapTotalHeight, SKColorType.RgbaF16, SKAlphaType.Unpremul)

    // get the canvas to draw on
    use canvas = surface.Canvas
    
    // fold over the maps, passing through the accumulated height of the past images in order to vertically offset the next image
    mapBitmaps
    |> Seq.fold (fun offset mapBitmap ->
        // draw the map on the canvas horizontally flush but vertically offset by the accumulated height so far
        canvas.DrawBitmap(mapBitmap, 0.0f, offset)

        // will eventually render some stuff on the floor map itself
        // ...

        // return the offset plus the height of the current map
        offset + (float32 mapBitmap.Height)
    ) 0.0f // starting offset is 0
    |> ignore

    surface.Snapshot().Encode().ToArray()
```

Now, the approach seems to work with small test images, but as soon as I pass in the floor maps which are larger (around the 5000x5000 pixel range) the surface initialization starts resulting in null once the heights (or even widths) go past the low 10,000s. In other words, after the following expression `use surface = SKSurface.Create(mapMaxWidth, mapTotalHeight, SKColorType.RgbaF16, SKAlphaType.Unpremul)` is evaluated, the value of `surface` is `null`.

I assume there must be a size limit of some kind? If so, are there any alternative techniques to merging/combining/appending images? I did consider shrinking the images before combining them but I don't think that is a scalable technique as with many small images you might still hit the size limit. And I was not able to grok any way to resize the surface itself. And I could not pick out any other append like operation in the docs so any help would be appreciated.

**Comment by mattleibow** [comment]
What platform is this? I don't think this is the case, but it may be: could the device have a low memory space for the app?

Also, is there a particular reason you are using `RgbaF16`? What happens if you use `Rgba8888` or `Bgra8888` (rather use `SKImageInfo.PlatformColorType` as this will automatically pick the correct color)?

**Comment by lambdakris** [comment]
The platform I'm working on is Windows 10 with VS 2017 and .NET Core 2.0.

Now, I think I might be doing something completely incorrectly because trying to create a minimal reproduction, I can't get it to work at all (plus for some reason GH won't let me upload the zip so below are instructions to repro manually)

To create the project, execute the following from a command line...
```
dotnet new console -o repro -lang f#
cd repro
dotnet add package SkiaSharp
```

Now, replace the content in the Program.fs file with the following...

```
open System
open SkiaSharp

[<EntryPoint>]
let main argv =
    
    let surface = SKSurface.Create(50,50, SKColorType.Unknown, SKAlphaType.Unknown)
    
    if surface = null then Console.WriteLine("Surface is null") else Console.WriteLine("Surface is not null")

    Console.WriteLine("Press any key to exit...")
    Console.ReadKey() |> ignore

    0 // exit code
```

What I see is that `surface` is null everytime. Just in case I tried reproducing in a C# project and got the same. I also tried targeting `net471` instead of `netcoreapp2.0` but that didn't make a difference. Also tried targeting x86 and x64 instead of AnyCPU, but that also did not make a difference. 

I am certain there must be something that I'm doing wrong but for the life of me I can't see it...

**Comment by mattleibow** [comment]
@lambdakris The reason is the color type and alpha type. To use the platform defaults I would recommend the overload that takes the `SKImageInfo`:

    var surface = SKSurface.Create(new SKImageInfo(50, 50));

If you don't want to use that, then the color type can't be unknown, so you MUST use a specific type or the platform type: `SKImageInfo.PlatformColorType`. The same goes for the alpha type, use `SKAlphaType.Premul`.

All four parameters are used to determine how much memory to allocate.

**Comment by lambdakris** [comment]
Yeah, it may be that this has nothing to do with image size and I just lost track of what technique was giving what results. Give me a chance to try using SKImageInfo to create the canvas and I'll close the issue if it works.

**Comment by lambdakris** [comment]
Using SKImageInfo to create an SKSurface did resolve the issue. Thank you for your patience.
