### ISSUE TITLE
App is getting Closed after installing skiaSharp

### ISSUE THREAD

**Issue by sreyas1986** [mono/SkiaSharp#428]
I created a new fresh app in vS2017 and installed Skisharp.Views.Forms and  skiaSharp in PCL and Skisharp.Views.Forms ,skiaSharp,skiasharp.views for ios and android  after that the app is getting closed after deploying [new to xamarin] 
![image](https://user-images.githubusercontent.com/4228166/35038222-26945d6c-fba0-11e7-8bd3-af416b6df543.png)

**Comment by mattleibow** [comment]
Is there a stack trace or any messages?

**Comment by mattleibow** [comment]
Closing due to lack of information.
