### ISSUE TITLE
I can't dispose SKCanvasView, memory leaks

### ISSUE THREAD

**Issue by niccolocapitelli** [mono/SkiaSharp#429]
Hi, I created a grid populated with Icons, that are drawn using skia. When I want to clean grid, I would delete Icons, but seems that I can't dispose SKCanvasview using Dispose function at the end of the code. This issue imply a memory leaks every time I create new Icons. How can I dispose a SKCanvasView freeing up memory?

```
public class IconWidget : SKCanvasView, IDisposable
    {
        public event EventHandler<EventArgsGridItemClicked> Tapped;

        public EventHandler<EventArgsGridItemClicked> ItemClickedHandler { get; set; }

        #region ModelProperty
        public static readonly BindableProperty ModelProperty =
            BindableProperty.Create
            (
                propertyName: "Model",
                returnType: typeof(IconWidgetModel),
                declaringType: typeof(IconWidget),
                defaultValue: new IconWidgetModel(IconWidgetState.Active, IconWidgetShape.Square, "bcr_comanda", "Default Main", false),
                defaultBindingMode: BindingMode.OneWay,
                propertyChanged: ModelPropertyChanged
            );
        public IconWidgetModel Model
        {
            get { return (IconWidgetModel)GetValue(ModelProperty); }
            set { SetValue(ModelProperty, value); }
        }
        private static void ModelPropertyChanged(BindableObject bindable, object oldValue, object newValue)
        {
            var control = (IconWidget)bindable;
            if (newValue != null)
            {
                control.Model = (IconWidgetModel)newValue;
                control.Model.RedrawIcon += control.Model_ChangedStatus;

                if (!control.Model.IsSideMenuIcon) {
                    var tap = new TapGestureRecognizer();
                    tap.Tapped += control.Tap_Tapped;
                    control.GestureRecognizers.Add(tap);
                }
            }
        }

       

        private void Model_ChangedStatus(object sender, EventArgs e)
        {
            Device.BeginInvokeOnMainThread(() => {
                InvalidateSurface();
            });
        }
        #endregion

        SKSurface surface;
        SKCanvas canvas;

        public string FakeTopTitle { get; set; }
        public bool IsOnlyOneElementInAggregator { get; set; }
        public bool IsFirstAggregatorElement { get; set; }
        public bool IsLastAggregatorElement { get; set; }
        public bool IsCentralAggregatorElement { get; set; }

        public IconWidget()
        {
            this.PaintSurface += CanvasView_PaintSurface;

            //BackgroundColor = Color.Green;

            VerticalOptions = LayoutOptions.FillAndExpand;
            HorizontalOptions = LayoutOptions.FillAndExpand;

            //Content = canvasView;
            
        }

        private void Tap_Tapped(object sender, EventArgs e)
        {
            Tapped?.Invoke(this, new EventArgsGridItemClicked(Model));
        }

        private float infoHeight;
        private float infoWidth;

        private float percPadd = 0.078f;

        protected virtual void CanvasView_PaintSurface(object sender, SKPaintSurfaceEventArgs e)
        {
            var canvas = e.Surface.Canvas;

            surface = e.Surface;
            canvas = surface.Canvas;

            Color selectedBackground = (Color)Application.Current.Resources["DarkGray"];
            Color nonSelectedBackground = (Color)Application.Current.Resources["MediumGray"];
            var canvasColor = Model.IsSelected ? SKColors.Transparent : SKColors.Transparent;
            canvas.Clear(canvasColor);

            canvas.Translate(e.Info.Width / 2, e.Info.Height / 2);

            using (SKPaint paint = new SKPaint())
            {
                paint.Style = Model.IsFilled ? SKPaintStyle.Fill : SKPaintStyle.Stroke;
                paint.StrokeWidth = 3;
                paint.StrokeJoin = SKStrokeJoin.Round;
                paint.Color = Model.BackgroundColor;
                paint.IsAntialias = true;
                paint.IsDither = true;
                paint.TextAlign = SKTextAlign.Center;
                paint.TextSize = (int)(e.Info.Height * 0.13); 
                //paint.TextSize = (int) UIMeasure.SmallFontSize_Default;
                

                var height = e.Info.Height;
                infoHeight = height;
                infoWidth = e.Info.Width;

                float radius = Math.Min(e.Info.Width, e.Info.Height) / 4.4f; // siccome per disegnare le icone non usiamo misure fisse come quelle da mockup
                                                                             // ed ci è statto segnalato che le misure sono leggermere piu grandi del 10%
                                                                             // anziche dividere per 4 dividiamo per 4.4 (il 10%) cosi dovremmo avere le immagini
                                                                             //della dimensione corretta.

                if (Model.IsTrasparent)
                {
                    paint.Style = SKPaintStyle.Stroke;
                    paint.Color = SKColors.White;
                }

                if (Model.IsTrasparent && Model.IsSelected)
                    paint.Style = SKPaintStyle.StrokeAndFill;


                DrawBackground(Model.Shape, canvas, paint, radius);



                if (Model.IsTrasparent && Model.IsSelected)
                    DrawSvg(canvas, paint, Model.SvgName, SKColors.Black, radius, e.Info);

                else
                    DrawSvg(canvas, paint, Model.SvgName, Model.SvgColor, radius, e.Info);

                DrawTitle(canvas, paint, Model.Title, radius,e.Info.Width,(float)(e.Info.Height * 0.03));

                
                DrawTopTitle(canvas, paint, Model.TopTitle, radius, (int)(e.Info.Height * 0.03), e.Info.Width, e.Info.Height);

            }
        }
 
public void Dispose()
        {
            canvas?.Dispose();
            surface?.Dispose();
        } '
```

**Comment by niccolocapitelli** [comment]
I profiled my app and I noticed that the heap is full of byte related to bitmap creation. It seems that garbage collection can't free up memory and this cause a memory leaks because of multiple use of SKCanvasView.
![memoryleak](https://user-images.githubusercontent.com/30794047/38141252-837f3a18-3437-11e8-9e2d-1682bd30c9be.JPG)

**Comment by mattleibow** [comment]
I tried to repro what you are seeing, but for some reason I can't. Are you able to attach a repro case? Here is mine, maybe you can tweak a few things to get the same thing to happen: [MemoryLeakTest.zip](https://github.com/mono/SkiaSharp/files/1864511/MemoryLeakTest.zip)

Looking at the snippet you attached, I would suggest that you not keep a reference to `SKSurface` or `SKCanvas` outside the paint method as this is a temporary object that will be disposed as soon as the paint is complete.

Also, what you can check is to make sure that you aren't referencing the canvs view anywhere outside the view. Maybe you have some cyclic references as well?

I think I maybe need some more info. I tried on both UWP and Android, but as soon as I clear the UI, the memory is freed. Maybe you have a Xamarin.Forms with a memory leak, or really it could be a whole host of things.

**Comment by mattleibow** [comment]
Also, sorry about the long delay in getting back to you. I was working on many things, both here and in some new projects that are going to be see at //Build :)

**Comment by rhussell** [comment]
I found in MemoryLeakTest.UWP although the IconWidget instances were disposed after "Trigger GC", but some other related "SK" objects always increased. When IconWidget is a SKCanvasView, it is SkiaSharp.Views.UWP.SKXamlCanvas. When IconWidget is SKGLView, they are SkiaSharp.Views.UWP.SKSwapChainPanel, List<SkiaSharp.SKObject>, SkiaSharp.GRContext and SkiaSharp.View.UWP.GlesContext.

I haven't tested it in Android. But I guess there may be similar problems there.

1. In Visual Studio 2017 start MemoryLeakTest.UWP with debugging
2. Click "Add 10" button (twice) then "Clear" and "Trigger GC"
3. Open Diagnostic Tools and Take Snapshot
4. Click "View Heap" and search with "sk"

<img width="560" alt="skcanvasview" src="https://user-images.githubusercontent.com/7099055/40580049-a73260d2-60f3-11e8-8f5e-80ce56ed3b04.png">
<img width="560" alt="skglview" src="https://user-images.githubusercontent.com/7099055/40580050-ab332536-60f3-11e8-9357-f62910b607d0.PNG">

**Comment by mattleibow** [comment]
OK, I'll have a look again and see what happens. Thanks for the images.
I am not sure why I didn't see anything, maybe I was working with something different somewhere.

**Comment by mattleibow** [comment]
I have a fix for the UWP leak: https://github.com/mono/SkiaSharp/commit/3244b370a9eb8a74322a193fb6f224cfa9aaa37f

It was the event that was attached to the static `DisplayInformation` to listen for DPI changes. Thanks @rhussell for pointing it out.

**Comment by mattleibow** [comment]
This is a complicated one, as I can't repro the Android leak. But, the UWP leak cannot be related as it resides in the platform code. I am going to close this as I fixed the UWP leak. Any additional leaks will be better with a new issue so we can focus on a particular platform.

**Comment by mattleibow** [comment]
@niccolocapitelli @rhussell I have just pushed out the release and should be available on NuGet. Here are the release notes and all the links: https://github.com/mono/SkiaSharp/releases/tag/v1.60.2
