### ISSUE TITLE
dotnet publish 

### ISSUE THREAD

**Issue by OpenSpacesAndPlaces** [mono/SkiaSharp#430]
Hi!

We've been using skiasharp dotnet core 2.0 and it's been working great localhost on Windows via VisualStudio.

However, when running a dotnet publish to a IIS 7.5 machine - it doesn't want to fire up:
The type initializer for 'SkiaSharp.SKManagedStream' threw an exception.Unable to load DLL 'libSkiaSharp': The specified module could not be found. (Exception from HRESULT: 0x8007007E)

I can see "SkiaSharp.dll" in the root of the publish directory.
I can see "libSkiaSharp.dll" in "\runtimes\win7-x64\native\" and \runtimes\win7-x86\native\"

I have 2017 x64 C++ redistributable installed on the target machine:
https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads

I tried with and without a run-time specifier of "win-x64" - no difference.
Is there another file or path that should be included in the publish settings to make this work?

Thanks in advance for the help.

**Comment by mattleibow** [comment]
You have to use the VS2015 VCRT Redist: 
https://www.microsoft.com/en-us/download/details.aspx?id=48145

**Comment by OpenSpacesAndPlaces** [comment]
@mattleibow 
> You have to use the VS2015 VCRT Redist:
VS2015 must have already been installed then. 

If it wasn't clear from my second post, the issue was that I have to set the build environment to "win7-x64" for the file to be copied, but if I leave as "AnyCPU" or even just generic win64 "win-x64", then "libSkiaSharp.dll" doesn't copy to the publish root from the runtimes folder.

My current fix was to just leave a static copy of "libSkiaSharp.dll" in the folder root.
