### ISSUE TITLE
Large Gray8 Bitmaps don't interpolate 

### ISSUE THREAD

**Issue by jackkutilek** [mono/SkiaSharp#432]
Bitmaps larger than 2^14 (16384) in width (and possibly height) are not interpolating when drawn at a smaller size. I noticed this with Gray8 bitmaps and Alpha8 image shaders, but I assume it happens with larger pixel formats too. 

Here is a fiddle where it is working in skia: https://fiddle.skia.org/c/374657f33d440c8f81390d9f50a9374a
I ran the test on my computer with the latest Skia code and it worked as well. I tried to build SkiaSharp's fork of Skia but failed, so I wasn't able to test it there.

here is some SkiaSharp code which reproduces it:

            var surfaceWidth = 500;
            var surfaceHeight = 300;
            var surface = SKSurface.Create(surfaceWidth, surfaceHeight, SKColorType.Bgra8888, SKAlphaType.Premul);
            var canvas = surface.Canvas;
            canvas.Clear(new SKColor(255, 255, 255));

            var bitmapWidth = 16384;
            var bitmapHeight = 10;
            var pixels = Marshal.AllocHGlobal(new IntPtr(bitmapWidth * bitmapHeight));
            unsafe
            {
                var bytes = (byte*) pixels;
                for(long y = 0; y < bitmapHeight; y++)
                for (long x = 0; x < bitmapWidth; x++)
                {
                    var index = y * bitmapWidth + x;
                    if (x / 3 == y)
                        bytes[index] = 0;
                    else
                        bytes[index] = 255;
                }
            }

            var info = new SKImageInfo(bitmapWidth, bitmapHeight, SKColorType.Gray8, SKAlphaType.Premul);
            var image = SKImage.FromPixels(info, pixels);

            var scale = .66f;
            canvas.Scale(scale, scale);

            var paint = new SKPaint();
            paint.FilterQuality = SKFilterQuality.High;
            canvas.DrawImage(image, SKRect.Create(bitmapWidth, bitmapHeight), paint);

            using (var stream = new FileStream("renderout.png", FileMode.OpenOrCreate, FileAccess.Write))
            using (var outimage = surface.Snapshot())
            using (var data = outimage.Encode(SKEncodedImageFormat.Png, 100))
                data.SaveTo(stream);

![renderout](https://user-images.githubusercontent.com/1078789/35350108-db34f046-010a-11e8-8ed6-0b3f663eac00.png)

changing the image width to 16383 interpolates as expected:
![renderout](https://user-images.githubusercontent.com/1078789/35350192-28f9fe16-010b-11e8-8855-ee07f1cd8cbb.png)

> VS bug [#738683](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/738683)

**Comment by mattleibow** [comment]
I still need to investigate this more thoroughly, but this may be relevant: https://groups.google.com/forum/#!topic/skia-discuss/UCg8Gtk6e7s

**Comment by mattleibow** [comment]
This is a super old issue, but I just tested this with the latest version and it does not appear to be happing. So yay! 

Closing this for now, if anyone sees this issue again, please open a new issue with a repro sample.
