### ISSUE TITLE
Can NOT DrawText ASCII and unicode togther

### ISSUE THREAD

**Issue by mailfcly** [mono/SkiaSharp#435]
test with xamarin forms, SkiaSharp.Views.Forms, android
```
                var fontManager = SKFontManager.Default;
                var emojiTypeface = fontManager.MatchCharacter('年');
                paint.Typeface = emojiTypeface;

                canvas.DrawText("123年 月456", 20, 80, paint);
```

result in Android:
![image](https://user-images.githubusercontent.com/33271336/35448901-86cf5378-02f6-11e8-9d93-d3e04b2180f1.png)

**Comment by yinyue200** [comment]
I think 

> The real issue is that Skia does not support character fallbacks. If the typeface does not contain the character, it will print a block.

see #232 

I think you should also fix your typo in your issue's title
