### ISSUE TITLE
SKSurface.Snapshot returns null when called from SKGLView

### ISSUE THREAD

**Issue by michaelstonis** [mono/SkiaSharp#436]
When using a `SKGLView` and calling Snapshot appears to return a null SKImage. Switching to a `SKCanvasView` provides the expected output.

```
protected override void OnPaintSurface(SKPaintGLSurfaceEventArgs e)
{
    var snapshot = e.Surface.Snapshot();
    System.Diagnostics.Debug.WriteLine("Has Value: " + snapshot != null);
}
```

**Comment by mattleibow** [comment]
What platform was this?

**Comment by michaelstonis** [comment]
This happened to me when testing with both the iOS simulator and an Android Pixel device. Let me know if I can provide any other feedback.

**Comment by mattleibow** [comment]
This should be working in the latest v1.60.0 release.

**Comment by michaelstonis** [comment]
I can confirm, this is looking good in 1.60.
