### ISSUE TITLE
ToSKBitmap draws abnormal pixels for transparent pixels in original image

### ISSUE THREAD

**Issue by rabbitom** [mono/SkiaSharp#439]
When use ToSKBitmap method to convert a UIImage to SKBitmap, the transparent pixels(all zero for r, g, b, a) in original image will be replaced by random, abnormal pixels. [This project](https://github.com/rabbitom/SkiaSharpDrawBitmapDemo) shows the problem.
![skiasharp-draw-bitmap-abnormal](https://user-images.githubusercontent.com/4596887/35603144-d83f5e78-0676-11e8-9653-9a772f2aac28.png)
It could be caused by not clearing the CGBitmapContext before drawing, I will submit a PR soon.

**Comment by mattleibow** [comment]
Thanks for reporting and the PR. I have merged it and it will be in the next release.
