### ISSUE TITLE
Unable to Load SkiaSharp assembly on Windows Phone 8.1 XAML

### ISSUE THREAD

**Issue by ooikengsiang** [mono/SkiaSharp#444]
I'm trying to use SkiaSharp to do some cross-platform image manipulation.
Get it install through nuget without problem.
But once it run on Windows Phone 8.1 XAML it encounter the following error:

```
Could not load file or assembly 'SkiaSharp, Version=1.59.0.0, Culture=neutral, PublicKeyToken=0738eb9f132ed756' or one of its dependencies. 
Reference assemblies should not be loaded for execution.  
They can only be loaded in the Reflection-only loader context. (Exception from HRESULT: 0x80131058)
```

Is there any additional nuget pack required to get this work?

**Comment by mattleibow** [comment]
Unfortunately, SkiaSharp is not supported on any Windows 8.x as this version of Windows does not support C++11. And, as SkiaSharp is written using C++11, there is nothing I can do.
