### ISSUE TITLE
PeekPixels returns null on decoded SKImage

### ISSUE THREAD

**Issue by rick779** [mono/SkiaSharp#445]
Hi,
I'm trying to get the pointer to the decoded byte array of SKImage, but it always returns null. I also tried with ToRasterImage, but the result is the same.

My code:

SKData data = SKData.Create("test.bmp");
SKImage img = SKImage.FromEncodedData(data);
SKPixmap pix = img.PeekPixels(); <--- NULL
IntPtr ptr = pix.GetPixels();

many thanks

**Comment by mattleibow** [comment]
What platform was this?

**Comment by rick779** [comment]
Windows 10

**Comment by rick779** [comment]
https://we.tl/k2aBEGU1Iv

**Comment by mattleibow** [comment]
Thanks. I think i found out what is happening. In some cases (specifically when decoding a SKData), the image is a "lazy" image that appears not to support `PeekPixels`. I am not sure exactly why, even though ReadPixels works...

For your case where you need the pixel information, I would suggest using `SKBitmap` - this is what `SKImage` uses under the hood. `SKImage` is more for representing some image, whether raster, texture or some other format.

If you really need to use an image for some reason, you can convert without copying data (the bitmap must live as long as the image):

    var image = SKImage.FromBitmap(bitmap);

**Comment by rick779** [comment]
many thanks
