### ISSUE TITLE
SKPaint.IsVerticalText is not work on UWP

### ISSUE THREAD

**Issue by kkc0923** [mono/SkiaSharp#446]
Hi. I tested SkiaSharp with latest Xamarin framework, to build Android and UWP app.

But I found that SKPaint.IsVerticalText = true is not work correctly on UWP platform. 

When I set SKPaint.IsVerticalText = true, SKPaint.MeasureText() return 0 (also return NaN as bounds). Also text is rendered horizontally.

On Android, text is correctly rendered vertically.

This is my test environment:
SkiaSharp v1.59.3
Xamarin.Forms v2.5.0.122203

Android App targeting : Android 8.0 (Oreo)
UWP App targeting : Windows 10 Fall Creators Update (10.0; Build 16299)

**Comment by mattleibow** [comment]
Thanks for reporting this issue. I had a look around and I believe this is not just limited to UWP, but also Win32 and PDF.

This is a known bug that Google has marked as low priority: https://bugs.chromium.org/p/skia/issues/detail?id=4622

If you need this feature, I would suggest starring that issue and adding your argument. They tend to implement features that have a larger community demand.
