### ISSUE TITLE
SkiaSharp.Forms is missing wheel events for mouse platforms

### ISSUE THREAD

**Issue by charlenni** [mono/SkiaSharp#449]
First lets say thank you very much for your work. It is great and I enjoy it.

I'm missing for the SkiaSharp implementation for Xamarin.Forms a SKTouchAction.WheelUp and SKTouchAction.WheelDown for the mouse. The click with the wheel is correct handled as MouseButton.Middle. It would be perfect to have this for platforms, that use a mouse (UWP and Mac).

> VS bug [#727960](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/727960)

**Comment by charlenni** [comment]
Are there any news about this?

**Comment by mattleibow** [comment]
We will be looking into this in the future, depending on demand. I would actually rather see Xamarin.Forms get these mouse, touch and pen interaction features in the framework. Right now, if you use SkiaSharp touch events, they override the Xamarin.Forms gestures.

**Comment by APopatanasov** [comment]
Hi @mattleibow ,

When 1.68.1 is expected to be released? That particular feature is really nice addition to the "Touch" API and I will be glad to use it. 😄 

P.S. @charlenni Nice job! 🥇

**Comment by rbrian** [comment]
Need 1.68.1 :) Wanting to add wheel support for zooming on my canvasview descendant. Great work, @charlenni ! 

I agree with earlier comments that the touch handling needs to be upstream in all of Forms. Can't think of a specific use case in my current projects, but would seem to be a good thing.

**Comment by mattleibow** [comment]
This was added in v1.68.1 over a few PRs.
