### ISSUE TITLE
Please add support for SVG assets!

### ISSUE THREAD

**Issue by Emasoft** [mono/SkiaSharp#45]
If SkyaSharp doesn't support SVG is useless at the moment. Not supporting SVG for a vector library is like not supporting PNG for a bitmap library. I use SVG assets in my Xamarin apps thanks to the NGraphics library, and I have many advantages:
- SMALLER APP FOOTPRINTS : SVG files are so small you can have your entire app graphics in less than 10k!
- FAST DEVELOPMENT - No need to code for creating the views. All the UI controls that once needed DAYS or even WEEKS to code, now are made in a couple of minutes in Inkscape. Productivity boost never seen before!
- EASY TO MODIFY FOR ARTISTS : my graphic artist works with Inkscape and it can edit the SVG files directly, no need to ask me to modify the code to make them work. He can update on the git the svg assets every day and test the changes by himself. And this even at the last moment! It's an amazing workflow!
- PORTABLE AND INDEPENDENT : No more graphic assets to use just once and then thrashed. The SVG assets you make for iOS you can reuse on Android, Windows, Linux versions of your app and on the web app too, with no changes. Also you do not depend on a single graphician or artist anymore. I can hire any pro to make my assets, and they can deliver them in SVG or change the existing one if they replaced another artist in the same project. Inkscape is also multiplatform, you can edit SVG assets on every computer you have!

This is why I really hope that Xamarin goes the way of NGraphics and add support for SVG assets to SkyaSharp. PLEASE.

Some of my SVG assets (I made them in Inkscape):

![ios_app_buttons](https://cloud.githubusercontent.com/assets/713559/5924670/d56b48a0-a65d-11e4-95b4-7377a6b7eda9.png)

You can download the original svg file from my google drive (click on the download button):
http://goo.gl/m7TbmM

Feel free to use them! 

For an easier debug, here it is a splitted version of the two main buttons svg files, you can download the zip from here: 
https://drive.google.com/file/d/0BxexooDWEb8ublZlcm5yRWpXTzQ/view?usp=sharing

**Comment by migueldeicaza** [comment]
We do not have plans on adding an SVG loader to SkiaSharp, as this is a project to bind Skia and SVG is not part of it.

This should be handled somewhere else, with some SVG loader library, that happens to draw the SVG code with Skia.
