### ISSUE TITLE
Webp Lossless format.

### ISSUE THREAD

**Issue by Potmos** [mono/SkiaSharp#451]
From what I can tell when I encode as Webp it generates the webp lossy format.

Is there a way to generate Webp lossless format?

**Comment by mattleibow** [comment]
There might be a way. By default it is the lossy compression when using the `SKImage.Encode` or `SKPixmap.Encode`. However, it appears the each encoder is public and can be used directly. Unfortunately, this has not yet been bound.

The WEBP, PNG and JPG encoders are public in the C++ code and should be visible in the next set of releases after the initial v1.60 release.

**Comment by Potmos** [comment]
Okay thank you I am using the C++ lib for now I will wait for Skiasharp to implement it then.

**Comment by mattleibow** [comment]
This has been added to the upcoming v1.60.2 release:

```csharp
SKPixmap pixmap = bitmap.PeekPixels();
// OR
SKPixmap pixmap = image.PeekPixels();

var options = new SKWebpEncoderOptions(SKWebpEncoderCompression.Lossless, 100);
SKData data = pixmap.Encode(options);
```
