### ISSUE TITLE
error while compiling .so file on CentOS 7: SkTypes.h: No such file or directory

### ISSUE THREAD

**Issue by jcyuan** [mono/SkiaSharp#452]
I just download the whole project from github and tried commands:
1, cd /folder/native-builds/libSkiaSharp_linux/
2, make

and error promps:
    Building ../src/sk_managedpixelserializer.cpp...
    In file included from ../src/sk_managedpixelserializer.cpp:8:0:
    ../src/SkManagedPixelSerializer.h:11:21: fatal error: SkTypes.h: No such file or directory
     #include "SkTypes.h"
                     ^
    compilation terminated.
    make: *** [obj/x64/sk_managedpixelserializer.cpp.o] Error 1

what's the problem and how to get a proper .so file for my CentOS 7?
excellent lib anyway as I tried on Win.

**Comment by mattleibow** [comment]
Here are some issues that you can also read about past Linux builders:

 - https://github.com/mono/SkiaSharp/issues/365
 - https://github.com/mono/SkiaSharp/issues/312
 - https://github.com/mono/SkiaSharp/issues/18

**Comment by jcyuan** [comment]
oh my, I love you bro!!
It does make sense.
thank you very much for you reply.

**Comment by mattleibow** [comment]
Closing this as I think this issue is addressed. Feel free to open a new issue for any other issues.
