### ISSUE TITLE
Width of png file dimensions is limited to 32767

### ISSUE THREAD

**Issue by cluster626** [mono/SkiaSharp#454]
(Title is not entirely accurate, please see below)
The following code in C# will generate a png image that has 36666 in width, but only the first 32767 pixels in width will be correctly generated.
```
                const int TEST_WIDTH = 36666;
                SKPath testPath = new SKPath();
                // A straight horizontal path covering the full width
                testPath.MoveTo(new SKPoint(0, 100));
                testPath.LineTo(TEST_WIDTH, 100);
                // Configure paint
                SKPaint testPaint = new SKPaint
                {
                    Style = SKPaintStyle.Stroke,
                    Color = SKColors.Red,
                    StrokeWidth = 50,
                    StrokeCap = SKStrokeCap.Cyan
                };
                // Save to file
                var bitMap = new SKBitmap(TEST_WIDTH, 200);
                SKCanvas imageCanvas = new SKCanvas(bitMap);
                imageCanvas.DrawPath(testPath, testPaint);
                using (Stream stream = File.OpenWrite('path to png file'))
                {
                    SKData data = SKImage.FromBitmap(bitMap).Encode(SKEncodedImageFormat.Png, 100);
                    data.SaveTo(stream);
                }
```
The resulting image, if opened with Gimp or similar tools, will have a horizontal stroke that only spans to the 32767th pixel in x.

This is found in a Xamarin.Forms project, tested on Nexus 6P running Android 8.1 and iPhone 6s running iOS 11.2.6.

**Comment by mattleibow** [comment]
You will never guess... skia just clips it so that it can fit into it's underlying type:
https://github.com/google/skia/blob/master/src/core/SkScan_Hairline.cpp#L48-L62

They even have a note:
> // We have to pre-clip the line to fit in a SkFixed, so we just chop
> // the line. TODO find a way to actually draw beyond that range.

I am not quite sure what to do at this point... You can still draw in that area (like a rect), just not with lines.

**Comment by mattleibow** [comment]
I asked a question here and we will see what they say: https://groups.google.com/forum/#!topic/skia-discuss/VDuN76yRFvQ

**Comment by cluster626** [comment]
Appreciate the info and post to google forum!

**Comment by mattleibow** [comment]
I just go confirmation that this will happen with lines:

> Yes, I confirm that Skia's CPU backend will always clip the path into 32k x 32k bounds because we're using SkFixed (16.16 format) for scan conversion. The clip may be even smaller (8k x 8k) if 4x4 supersampling AA is used. We're thinking about adding tiling to completely remove that limitation.

**Comment by mattleibow** [comment]
I am going to close this as this is a core issue with skia. As soon as they fix it, it will magically appear in SkiaSharp.

For workarounds, I suggest discussing your case on their forums as they will be able to better help you.
