### ISSUE TITLE
SKGLView crashes in Android 

### ISSUE THREAD

**Issue by pragmatheorist** [mono/SkiaSharp#460]
This can be reproduced with any app using the latest SKGLView (SkiaSharp.Views.Forms 1.60.0), even the [SkiaSharp Xamarin.Forms sample](https://github.com/mono/SkiaSharp/tree/master/samples/Gallery/Xamarin.Forms) app. With the previous version (SkiaSharp.Views.Forms 1.59.3 and Xamarin.Forms 2.4.0) the app works fine, so this bug was likely introduced in 1.60.0.

**Reproduction steps**
1. Start the Xamarin.Forms SkiaSharpSample app in Android.
2. Select OpenGL from settings.
3. Tap Android overview button (square icon).
4. Return back to the app. SKGLView remains empty.
5. Swipe the SKGLView. And the app crashes in a System.NullReferenceException.

**Tested with**
SkiaSharp v1.60.0
Xamarin.Forms v2.5.0.77107 and v2.5.0.280555
Android App targeting : Android 8.0 (Oreo)

**Comment by mattleibow** [comment]
Thanks for reporting this. It very well might be something in the new view. We switched from a GLSurfaceView under the hood, to a TextureView.

I will have a look.

**Comment by hallidev** [comment]
I'll second this one. Just found this thread after starting to pull my hair out. Same steps to re-create as @pragmatheorist details.

**Comment by EEVblog** [comment]
I believe I have the same issue. The issue occurs when an activity is started then closed or the window is resumed. this issue has made it impossible to save files, or switch between apps on the phone without the view crashing and throwing a null reference exception.

The issue does not occur when using the software renderer.

**Comment by mattleibow** [comment]
I managed to find out what was happening. When the app is paused, the texture is destroyed. This is all good so far. However, when the app resumed, the texture is re-created under the hood and thus follows another path - and this is where I was missing logic to recreate the SkiaSharp context.
