### ISSUE TITLE
Trouble getting the SKWidget to appear in the GUI Designer in MonoDevelop (on Linux)

### ISSUE THREAD

**Issue by define-private-public** [mono/SkiaSharp#462]
I added the packages `SkiaSharp` and `SkiaSharp.Views` to my project.  In the GUI designer, I didn't see the `SKWidget` appear in the `Toolbox`.  I have other projects in my solution that have custom widgets and they appear in there.

I tried adding the `SkaiSharp.Views.Gtk` DLL (from the solution's `packages/` folder) using that little "green plus button" and got a `SKWidget` to appear under the `General` section in the toolbox.  But when trying to drag the widget into my GUI, I got an error message saying "The widget 'SkiaSharp.Views.Gtk.SKWidget' could not be found."

What wrong and how can I fix this?  I'd really like to use Skia for my custom widget drawing.

**Comment by mattleibow** [comment]
Thanks for reporting this, I will have a look.
In the meantime, this is what I was doing: https://github.com/mono/SkiaSharp/blob/master/samples/Basic/Gtk/SkiaSharpSample/gtk-gui/gui.stetic

**Comment by define-private-public** [comment]
Is this were the `SkiaSharp` project(s) where included in the same solution?  If that's what I need to do, I won't mind doing it as a temporary fix.

**Comment by define-private-public** [comment]
What do you think you're timeline is to work on this?  I'm fairly interested in using Skia instead of Cairo for a project I'm working on.  I wouldn't mind helping out, but I tried grabbing a copy of this repo (at the latest release) and it failed to fully build on my Linux system.

**Comment by mattleibow** [comment]
I have been looking at this, and I am seeing weird things on my machines now, but not your error.

What I did notice is that I have to restart monodevelop in order to get the item to display in the Toolbox. Using packages.config, the IDE sees the widget after a restart. If I used <PackageReference>, the widget never appeared, but I could manually add the widget:

```xml
<widget class="SkiaSharp.Views.Gtk.SKWidget" id="skiaView">
  <property name="MemberName" />
</widget>
```

I never got your exception, maybe try rebuilding the project or deleting the obj and bin folders.

The issue that I am seeing is that it crashes the app when it tries to swap the red and blue color components before drawing... This was working since I had a demo app that I released to my team, and other users of SkiaSharp are using this just fine. However, on my machines now it just dies... And, not consistently either - If I create a sample app on macOS, it runs fine, but if I add the same code to the unit tests, it crashes with a malloc error. Both my VM and my WSL die with a memory corruption error.

At this point, my IDE is working fine, but fails at runtime with a malloc error - which is not what you have.

Is there a stack trace that you can share that may help?

**Comment by mattleibow** [comment]
I found the error:
https://github.com/mono/SkiaSharp/blob/v1.60.0/source/SkiaSharp.Views/SkiaSharp.Views.Gtk/SKWidget.cs#L46

```csharp
SKSwizzle.SwapRedBlue(pixmap.GetPixels(), pixmap.GetPixels(), info.BytesSize);
```

I am indicating that the number of pixels is the number of bytes, but this is not correct. The number of pixels is width*height. This probably won't fix the issue from @define-private-public , but will make sure the app will actually run when id does work.

The reason it works in some cases is that I may have been lucky in many cases where the data that I was swapping might have been empty data.

**Comment by define-private-public** [comment]
Do you still me to give you that stack trace?  Aside from that, I've got something you may want to try out:

I'm working on a project right now that has some custom Gtk widgets defined in it.  I had to add an explicit reference to `libstetic` to the project.  My custom widgets weren't working in other projects until I added the reference.  e.g.:

```
<Reference Include="libstetic">
  <HintPath>..\..\..\..\..\..\..\usr\lib\monodevelop\AddIns\MonoDevelop.GtkCore\libstetic.dll</HintPath>
</Reference>
```

Can you try adding that to the project for the Gtk DLL and see if it changes anything?

**Comment by mattleibow** [comment]
Did you managed to get the SKWidget to work?

**Comment by define-private-public** [comment]
Um, no.  Actually, I haven't been able to build the project on my machine, I tried following the steps and it failed.  I'll give it another go and report what I've got.

**Comment by define-private-public** [comment]
Sorry for not replying for a while.  I was toying with the latest release and the Gtk Sample included.  After adding NuGet packages to `SkiaSharp` and `SkiaSharp Views` to the project, I was able to get it to build, and run, but and error gets thrown:

```
Loaded assembly: /home/me/Desktop/SKTest/Basic/Gtk/SkiaSharpSample/bin/Debug/SkiaSharpSample.exe
Loaded assembly: /usr/lib/mono/gac/gtk-sharp/2.12.0.0__35e10195dab3c99f/gtk-sharp.dll [External]
Loaded assembly: /usr/lib/mono/gac/glib-sharp/2.12.0.0__35e10195dab3c99f/glib-sharp.dll [External]
Loaded assembly: /usr/lib/mono/gac/atk-sharp/2.12.0.0__35e10195dab3c99f/atk-sharp.dll [External]
Loaded assembly: /usr/lib/mono/gac/System/4.0.0.0__b77a5c561934e089/System.dll [External]
Loaded assembly: /home/me/Desktop/SKTest/Basic/Gtk/SkiaSharpSample/bin/Debug/SkiaSharp.Views.Gtk.dll [External]
Loaded assembly: /home/me/Desktop/SKTest/Basic/Gtk/SkiaSharpSample/bin/Debug/SkiaSharp.Views.Desktop.dll [External]
Loaded assembly: /usr/lib/mono/gac/gdk-sharp/2.12.0.0__35e10195dab3c99f/gdk-sharp.dll [External]
Loaded assembly: /usr/lib/mono/gac/Mono.Posix/4.0.0.0__0738eb9f132ed756/Mono.Posix.dll [External]
Loaded assembly: /home/me/Desktop/SKTest/Basic/Gtk/SkiaSharpSample/bin/Debug/SkiaSharp.dll [External]
Exception in Gtk# callback delegate
  Note: Applications can use GLib.ExceptionManager.UnhandledException to handle the exception.
System.TypeInitializationException: The type initializer for 'SkiaSharp.SKImageInfo' threw an exception. ---> System.DllNotFoundException: libSkiaSharp
  at (wrapper managed-to-native) SkiaSharp.SkiaApi:sk_colortype_get_default_8888 ()
  at SkiaSharp.SKImageInfo..cctor () [0x00000] in <7d2e3bd6812e4881b5c49a3f02b476aa>:0 
   --- End of inner exception stack trace ---
  at (wrapper managed-to-native) System.Object:__icall_wrapper_mono_generic_class_init (intptr)
  at SkiaSharp.Views.Gtk.SKWidget.OnExposeEvent (Gdk.EventExpose evnt) [0x00034] in <510d9f92232b4af09f32eaa2b08842ce>:0 
  at Gtk.Widget.exposeevent_cb (System.IntPtr widget, System.IntPtr evnt) [0x00014] in <7a41aae9f05e45b7b5a8cedfab67f8ff>:0 
  at GLib.ExceptionManager.RaiseUnhandledException (System.Exception e, System.Boolean is_terminal) [0x00000] in <5a439e0caae7469886e7119d9f6bc621>:0 
  at Gtk.Widget.exposeevent_cb (System.IntPtr widget, System.IntPtr evnt) [0x00000] in <7a41aae9f05e45b7b5a8cedfab67f8ff>:0 
  at Gtk.Application.gtk_main () [0x00000] in <7a41aae9f05e45b7b5a8cedfab67f8ff>:0 
  at Gtk.Application.Run () [0x00000] in <7a41aae9f05e45b7b5a8cedfab67f8ff>:0 
  at SkiaSharpSample.MainClass.Main (System.String[] args) [0x00012] in /home/me/Desktop/SKTest/Basic/Gtk/SkiaSharpSample/Program.cs:13 

```

**Comment by define-private-public** [comment]
Hey, it working now. Thanks for getting the fix in!  When grabbing `1.60.1` from NuGet `SKWidget` does show up in the GUI designer and I'm able to drag n' drop use it.  Though, I have noticed some quirks though.

I had a simple single widget window setup, with the widget sizing set `auto fill=false, expanding=true, fill=true`, with no signals/events attached.  Some garbage data was rendered:
![leftovers](https://user-images.githubusercontent.com/4551425/40592939-a12d12b8-61f2-11e8-8274-47328ebaa8f1.png)

Resizing the window though gets rid of them.

If I turned the sizing back to the defaults, there were some specs still visible along the top:
![sepcs](https://user-images.githubusercontent.com/4551425/40592975-e6905bd0-61f2-11e8-9596-719dfc6a6299.png)

The last thing though is a bit more important to me, redrawing (when resizing the window) isn't smooth.  It's flickering a lot, here's a video of how it's working:
![skiasharp-not-so-smooth](https://user-images.githubusercontent.com/4551425/40593046-89891d68-61f3-11e8-8973-80437eceb815.gif)

IIRC, Skia renders much faster than Cairo, but I've never had this before when resizing a Cairo drawing area.  I'm hoping to use SkiaSharp at 60 FPS.

**Comment by mattleibow** [comment]
I see. Thanks for all the info.
I may just be rendering all this wrong. I am not that much of a GTK# expert.

I will see if I can get this better. Could you open a new issue to track this?

_note: The garbage bits is basically the empty memory. Nothing is cleared initially, you have to do that yourself._

**Comment by define-private-public** [comment]
Sure thing.

**Comment by mattleibow** [comment]
Thanks!
