### ISSUE TITLE
SKImage.FromEncodeData(...).Subset(...).Encode(...) encodes the entire image instead of the subset

### ISSUE THREAD

**Issue by raphaelr** [mono/SkiaSharp#465]
Hi,

when creating an image from encoded data, Subset()ting it and then saving the result, the original image is encoded instead of the subset. If the image is created from an SKBitmap instead, this issue doesn't happen.

```csharp
using SkiaSharp;
using System.IO;

class Program {
    // pick your favorite png file.
    const string InputPath = @"input.png";

    static void Main(string[] args) {
        SKImage image = LoadBroken();
        // or: SKImage image = LoadCorrectly();

        // save the right half
        using (var rightHalf = image.Subset(new SKRectI(image.Width / 2, 0, image.Width, image.Height)))
        using (var rightData = rightHalf.Encode())
        using (var outputStream = File.OpenWrite("output.png"))
            rightData.SaveTo(outputStream);
    }

    static SKImage LoadBroken() {
        using (var stream = File.OpenRead(InputPath))
        using (var data = SKData.Create(stream))
            return SKImage.FromEncodedData(data);
    }

    static SKImage LoadCorrectly() {
        using (var stream = File.OpenRead(InputPath))
        using (var bitmap = SKBitmap.Decode(stream))
            return SKImage.FromBitmap(bitmap);
    }
}
```

**Expected output:** The right half of `input.png` is saved to `output.png`.
**Actual output:** The entirety of `input.png` is saved instead.
**Version:** SkiaSharp 1.60.0
**Environment:** .NET Core 2.0 on Windows 10 version 1709

If the call to `LoadBroken()` is replaced with `LoadCorrectly()` the issue doesn't happen.

**Comment by mattleibow** [comment]
This appears to be a bug in skia:
https://fiddle.skia.org/c/46c321af4c4bd87ab77a17d2c75f41f9

I opened a bug there:
https://bugs.chromium.org/p/skia/issues/detail?id=7752

**Comment by mattleibow** [comment]
A workaround is to use `Encode(SKEncodedImageFormat.Png, 100)`.

The current logic makes a mistake of thinking that if there was a source data, then just return it. When you take a subset, the data is passed around but not flagged as a subset. This means that `Encode` just returns the old data. The parameters force a re-encode. 

The benefit of not always re-encoding is that if the image is unchanged (and it is often the case) then no need to do the work. Not sure if this is really a benefit though... When you call encode, it is usually pretty quick and often you are prepared for it to take longer. Just passing the data back is nice, but has issues like this...

**Comment by mattleibow** [comment]
This was fixed in https://github.com/google/skia/commit/cd04356804df66ce3546c3e9b61cee71c612e3d2

I will bring this back down to our version.
