### ISSUE TITLE
Snapshot from Canvas

### ISSUE THREAD

**Issue by Azmarel** [mono/SkiaSharp#468]
Hi
I'm trying to create an image from canvas. Don't know how to extract surface from canvas to do it, so i   do:

        SKSurface surface = null;
        private void OnPaint(object sender, SkiaSharp.Views.Forms.SKPaintGLSurfaceEventArgs e)
        {
            mapDrawing.DrawSample(e.Surface.Canvas, e.RenderTarget.Width, e.RenderTarget.Height);

            surface = e.Surface;
        }

And then try to extract the snapshot from surface in another method after the first paint occurence:

        if (surface == null)
            return null;
  
                var snap = surface.Snapshot();
                var data = snap.Encode();
                byte[] bytearray = data.ToArray();
        }

and I get the expection when invoking surface.Snapshot();

```
03-14 22:11:05.294 D/Mono    (12013): Found as 'sk_surface_new_image_snapshot'.
03-14 22:11:05.294 E/mono-rt (12013): Stacktrace:
03-14 22:11:05.294 E/mono-rt (12013): 
03-14 22:11:05.302 E/mono-rt (12013):   at <unknown> <0xffffffff>
03-14 22:11:05.302 E/mono-rt (12013):   at (wrapper managed-to-native) SkiaSharp.SkiaApi.sk_surface_new_image_snapshot (intptr) <0x00037>
03-14 22:11:05.302 E/mono-rt (12013):   at SkiaSharp.SKSurface.Snapshot () [0x00006] in <5a812555f55f40c0a29350793a12a8ac>:0
```
Can you give ma a hand with this?
Thanks :)

**Comment by mattleibow** [comment]
Ah. What you are doing is keeping the surface around after the paint event. This cannot be done as the surface lives only as long as the method is running. To do what you are doing, take the snapshot _inside_ the paint event.

Although, looking at your code, you probably can just create a new bitmap and call `DrawSample` on that:

```csharp
var bmp = new SKBitmap(desiredWidth, desiredHeight)
var canvas = new SKCanvas(bmp);
mapDrawing.DrawSample(canvas, desiredWidth, desiredHeight);
var pixmap = bmp.PeekPixels();
var data = pixmap.Encode(SKEncodedImageFormat.Png, 100);
```
