### ISSUE TITLE
SkiaSharp.Views.Forms.SKCanvasView draws SKPicture pixelated when scaled up.

### ISSUE THREAD

**Issue by XamDevv** [mono/SkiaSharp#473]
Hi,

we use a custom MapControl for Zooming and Panning it's Content. It contains a SKCanvasView inside, which draws a SKPicture vector graphic. When the user zooms in, the MapControl increases the scale property of the SKCanvasView and the drawn Picture becomes bigger as expected. The Problem is that the Picture is pixelated although it should be scalable without pixelation as it's a vector graphic. I can provide Code or a sample solution if needed.

Thanks in advance for your help!

**Comment by mattleibow** [comment]
This may be because you are scaling _after_ drawing? As soon as you draw the image, the vector becomes a raster. To avoid pixelation, you have to draw the picture with a scale matrix.

How are you drawing the picture before/after scaling?

**Comment by XamDevv** [comment]
Yeah, I figured this is happening. I just hoped that the SKCanvasView used the Xamarin Scale and applied it to the drawing out of the box.

So I have to add a DrawingScale property to a CustomCanvasView and do the scaling manually? Or is it possible to disable the Xamarin default raster scaling only for the CanvasView and use the Scale property for drawing?

**Comment by mattleibow** [comment]
You will have to use a separate scale when drawing as the Xamarin scale property is specifically to scale the _view_ after drawing/rendering. It relates to the fact that after the OS draws the view, it then applies a custom scale.

Instead of scaling the canvas via a property on the view, create a separate property and then just use that as part of the drawing:

```
float DrawingScale { get; set; }
...
void Draw(SKCanvas cnv) {
    cnv.Scale(DrawingScale);
    // draw
}
```

**Comment by mattleibow** [comment]
Closing this as pixelation occurs because the entire view is scale as opposed to the content drawn.

**Comment by XamDevv** [comment]
Thank you for the quick responses. I will try your suggestion.
