### ISSUE TITLE
SKGLView reports touch position incorrectly on UWP with UI scaling set to higher than 100%

### ISSUE THREAD

**Issue by VitezslavImrysek** [mono/SkiaSharp#474]
This can be reproduced with the latest versions of SkiaSharp.Views.Forms 1.60.0 and Xamarin.Forms 2.5.0.280555 running on Windows 10 (FCU) with UI scaling set to more than 100%.

**Reproduction steps**
1. Set SKGLView.EnableTouchEvents to true.
2. Add an event handler to SKGLView.Touch event and watch reported pointer positions.
3. Event handler is raised only until pointer reaches a certain position relative to window: [width / scale; height / scale]. Event handler is not being raised beyond this point even though the pointer is still located right over the SKGLView rendering area. Moreover, the reported pointer position is at all times scaled by UI scale.

Here is a simple repro solution.
[SKGLViewBug.zip](https://github.com/mono/SkiaSharp/files/1844404/SKGLViewBug.zip)

**Comment by mattleibow** [comment]
Moving this out again so that we can release for //build

**Comment by mattleibow** [comment]
![image](https://user-images.githubusercontent.com/19760720/39871868-1e62ffc4-545e-11e8-9320-1fe79b359024.png)

**Comment by mattleibow** [comment]
Moving this to v1.60.3 so we can get out a version that fixes a UWP bug (#536)

**Comment by charlesroddie** [comment]
Any ideas about how to fix this @mattleibow ?
@AxelUser if you have time could you take a look?

**Comment by mattleibow** [comment]
I spent some time looking at this and decided to rewrite the entire view for UWP. The current way was a fair bit of a hack, the new version in the `dev/update-m68` branch is much better and will also fix the #207 bug.

**Comment by mattleibow** [comment]
This is now fixed and in the upcoming 1.68.0-preview release.
