### ISSUE TITLE
Xamarin Forms using FFImageLoading.Svg.Forms and SkiaSharp

### ISSUE THREAD

**Issue by thomashoef** [mono/SkiaSharp#476]
Hi everyone

We have the weirdest of issues with Skia. We use FFImageLoading.Svg.Forms in our Xamarin Forms project (latest version) and SkiaSharp 1.59.1.

When we build our app in some of our custom Debug Modes, the app always works. In *some* release configs, we get a System.DllNotFoundException (Skia Framework). When we use the debug settings in the non-working release configs, or the working release config is copied to a non-working one, it simply does not help. The app always crashes when trying to call a Skia method.

We have seen similiar posts but never with a working solution.

Can anyone help out - the dll is present in the final IPA.

I have added this to the first screen's viewmodel

            LoginPadVisible = true;
            try
            {
                // test an operation that requires the native library
                SKPMColor.PreMultiply(SKColors.Black);
            }
            catch (DllNotFoundException)
            {
                // If we can't load the native library,
                // we may be in some designer.
                // We can make this assumption since any other member will fail
                // at some point in the draw operation.
                Trace.TraceError("skia not loaded");
                LoginPadVisible = false;
            }

Result: The login touchpad is not visible - so it definitely throws the exception.

fyi:

this is part of the stacktrace:
Image loading failed: 
System.DllNotFoundException: @rpath/libSkiaSharp.framework/libSkiaSharp
  at (wrapper managed-to-native) SkiaSharp.SkiaApi:sk_picture_recorder_new ()
  at SkiaSharp.SKPictureRecorder..ctor () [0x00000] in <60ce313fefca407885b10c0e81558bfa>:0 
  at FFImageLoading.Svg.Platform.SKSvg.Load (System.Xml.Linq.XDocument xdoc) [0x00266] in C:\projects\ffimageloading\source\FFImageLoading.Svg.Shared\SkSvg.cs:185 
  at FFImageLoading.Svg.Platform.SKSvg.Load (System.Xml.XmlReader reader) [0x00000] in C:\projects\ffimageloading\source\FFImageLoading.Svg.Shared\SkSvg.cs:115 
  at FFImageLoading.Svg.Platform.SKSvg.Load (System.IO.Stream stream) [0x00012] in C:\projects\ffimageloading\source\FFImageLoading.Svg.Shared\SkSvg.cs:109 
  at FFImageLoading.Svg.Platform.SvgDataResolver+<Resolve>d__20.MoveNext () [0x00198] in C:\projects\ffimageloading\source\FFImageLoading.Svg.Shared\SvgDataResolver.cs:90 
--- End of stack trace from previous location where exception was thrown ---

Similar to this link: https://github.com/luberda-molinet/FFImageLoading/issues/791

But changing the PCL did not help. We upgrade to .NET Standard now and that too, did not help.

Thanks
Thomas

**Comment by mattleibow** [comment]
Are you able to attach an example project? I also don't think I understand your term of "custom Debug Modes" (and this is probably the same for "release configs"...

**Comment by thomashoef** [comment]
Hi @mattleibow 

What I mean with a custom debug config or release config is simply a Visual Studio for Mac Build Configuration such as:

  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'TestDebug|iPhoneSimulator' ">
    <DebugSymbols>true</DebugSymbols>
    <DebugType>full</DebugType>
    <Optimize>false</Optimize>
    <OutputPath>bin\iPhoneSimulator\$(Configuration)</OutputPath>
    <DefineConstants>DEBUG;ENABLE_TEST_CLOUD;</DefineConstants>
    <CodesignEntitlements>Entitlements.plist</CodesignEntitlements>
    <ErrorReport>prompt</ErrorReport>
    <WarningLevel>4</WarningLevel>
    <MtouchDebug>true</MtouchDebug>
    <MtouchNoSymbolStrip>true</MtouchNoSymbolStrip>
    <MtouchFastDev>true</MtouchFastDev>
    <IOSDebuggerPort>40088</IOSDebuggerPort>
    <MtouchLink>None</MtouchLink>
    <MtouchArch>x86_64</MtouchArch>
    <MtouchHttpClientHandler>HttpClientHandler</MtouchHttpClientHandler>
    <DeviceSpecificBuild>false</DeviceSpecificBuild>
    <AssemblyName>XXX.App.iOS-Test</AssemblyName>
    <CustomBuildTarget>Test</CustomBuildTarget>
  </PropertyGroup>

When we run and launch the app in TestDebug as a Buildconfig for example, we do not have a Skia error. If we run it in TestRelease (another set of build parameters), we have a crash. If we copy all of the build parameters of the TestDebug config over to the TestRelease config, so that they are actually an identical set of build parameters, the TestRelease still crashes.

It looks as though some Visual Studio build configurations which are based upon "Release" instead of "Debug" cause the app to crash. 

I have tried executing a method of SkiaSharp when the app fires, and I catch the method execution with a DllNotFoundException. In the given Build config which does not work, the DllNotFound is thrown, yet when we look in the binary (IPA), they look identical.

I have also tried in the appdelegate to directly reference a Skia object so that the linker can not "ignore" the dll, but that does not help.

We get a DllNotFoundException and we have no clue why it is doing this - the only difference we see is Release vs Debug, yet in some Release configurations, for some reason (??) the crash does not occur.

Parameter name: obj
at (wrapper managed-to-native) System.Object.__icall_wrapper_mono_monitor_enter_v4_internal(object,intptr)
SkiaSharp.SKObject.Dispose(bool disposing)
SkiaSharp.SKPictureRecorder.Dispose(bool disposing)
SkiaSharp.SKNativeObject.Finalize()

**Comment by mattleibow** [comment]
I will see what I can find out... Looking at the stack trace, it looks a bit weird: `DllNotFoundException: .framework/libSkiaSharp` the framework name is not correct - it should have a whole bunch of other things in it.

**Comment by thomashoef** [comment]
Hi @mattleibow 

Do you by chance have an idea where this may come from yet? Your help is much appreciated, thanks!
Thomas

**Comment by mattleibow** [comment]
After updating to v1.06 or the latest v1.68 preview, is this still happening?

**Comment by Redth** [comment]
We are closing this issue since no response was received.  Please open a new issue referring to this one if you have more information.
