### ISSUE TITLE
[Question] decode GIF into sequences

### ISSUE THREAD

**Issue by jcyuan** [mono/SkiaSharp#477]
sorry this is not an iusse but wanna know how to decode an GIF into PNG sequences.
I use the code below but it does not seem to work:

    using (var codec = SKCodec.Create(stream))
            {
                var info = codec.Info;
                stream.Position = 0;
                for (int i = 0; i < codec.FrameCount; i++) 
                {
                    var skbitmap = new SKBitmap(info.Width, info.Height, true);
                    IntPtr length;
                    var result = codec.GetPixels(skbitmap.Info, skbitmap.GetPixels(out length));
                    if (result == SKCodecResult.Success)
                    {
                        resizeAndSaveImage(tempDir + "/" + i + ".png", skbitmap, srcRect, dstRect, SKEncodedImageFormat.Png);
                        stream.Position += skbitmap.ByteCount;    //move to next frame??????
                    }
                    else
                        throw new InvalidDataException();
                }
            }

problems:
1, `codec.FrameCount` seems always 1 but not the correct gif frame count
2, `codec.GetPixels` returns `SKCodecResult.IncompleteInput` I have no idea what does it mean.
3, what is the right way to decode GIF?

Thanks in advance.

**Comment by mattleibow** [comment]
I did notice you are moving the stream position - you shouldn't need to do that.

Chances are you need to use the `SKCodecOptions` in there...

Check out this sample that decodes a GIF and runs the frames:
https://github.com/mono/SkiaSharp/blob/master/samples/Gallery/Shared/Samples/DecodeGifFramesSample.cs

**Comment by jcyuan** [comment]
@mattleibow sorry sir, lately a bit busy so missed your answer, the reason is that my aspnet core App form always has only 1 frame image of the GIF uploaded (no idea), so I changed my way to first save the GIF to disk instead of using the form data stream directly, and than use the code above to read GIF from hard disk, and the .FrameCount attribute works well.
and thanks for your tips for the stream position problem and example, I just had it fixed.
