### ISSUE TITLE
GRContext.Create under Debian always returns null with HW acceleration active (vbox)

### ISSUE THREAD

**Issue by BaruchCodes** [mono/SkiaSharp#481]
GRContext.Create always returns null. There is no hint what is the error. Through testing I found that if I disable 3D Acceleration for Virtual Box the context gets created. The project uses OpenTK for OpenGL. Under windows the combination works just fine. What makes me wondering is that there is no error message, nothing. The GRContext is just null.

Code versions i tried:

```
var glInterface = GRGlInterface.CreateNativeGlInterface();
var grContext = GRContext.Create(GRBackend.OpenGL, glInterface);

// or
var grContext = GRContext.Create(GRBackend.OpenGL);

// or
OpenTK.Graphics.GraphicsContext.Assert();
var context = OpenTK.Graphics.GraphicsContext.CurrentContext;
var internalContext = (OpenTK.Graphics.IGraphicsContextInternal)context;
var xglinterface = GRGlInterface.AssembleGlInterface((obj, name) => internalContext.GetAddress(name));
var grContext = GRContext.Create(GRBackend.OpenGL, xglinterface);
```

VBox 5.2.8
Debian 9
Mono 5.10.1.20
NuGet Package of SkiaSharp 1.6.0

*.so files from SkiaSharp copied.

OpenTK itself works. Direct rendering is active in OpenTK, same for glxinfo output.

**Comment by masoud-al** [comment]
Same issue here

VBox 5.2.8
Ubuntu 17
Mono 5.10.1.20
SkiaSharp built from commit b7da89f3b870b61e032650da4dc5d4c720db43bf

**Comment by mneumann** [comment]
@abagorba @BaruchCodes @masoud-al [This patch][1] against [this commit of mono/skia][2] is specifically suited for the Vivante GC880 GPU. I guess that patch would also work in the case you are running Skia within a virtual box, because `GrGLInterface()::validate()` will no longer fail, as we are removing `GL_EXT_draw_instanced` from the list of extensions.

[1]: https://gist.github.com/mneumann/dc6928c35ee8135ff0569a9008f91833
[2]: https://github.com/mono/skia/commit/9217b23761c207bb3b6ed95c57d4427875cde0bb

**Comment by mattleibow** [comment]
We just released a new version of SkiaSharp - [v1.68.0](https://github.com/mono/SkiaSharp/releases/tag/v1.68.0) - that should have hundreds of improvements. Could you test this new version and see if it fixes the issue.

Also, as noted above, make sure your GPU drivers are installed.

**Comment by BaruchCodes** [comment]
Now I have the same issue on a debian not virtualized. Was working before the update with GRContext.Create(GRBackend.OpenGL) after the update this always returns null. Even GRGlInterface.CreateDefaultInterface() will return null....

**Comment by Redth** [comment]
We are closing this issue since no response was received.  Please open a new issue referring to this one if you have more information.
