### ISSUE TITLE
SkiaSharp.SKObject.Dispose can throw ArgumentNullException on finalization

### ISSUE THREAD

**Issue by davkean** [mono/SkiaSharp#482]
Had a customer complaining about crashes in Visual Studio while using SkiaSharp in the WinForms designer: https://developercommunity.visualstudio.com/content/problem/228761/crashing-when-debugging-a-skiasharp-winforms-app-i.html.

Looking into his crashes it looks like SkiaSharp.SKObject.Dispose can throw on finalization:

```
   at System.Threading.Monitor.ReliableEnter(System.Object, Boolean ByRef)
   at SkiaSharp.SKObject.Dispose(Boolean)
   at SkiaSharp.SKPaint.Dispose(Boolean)
   at SkiaSharp.SKNativeObject.Finalize()
```

If you look at Dispose, you can see multiple paths where it attempts to access managed instance and static fields that have no guarantee about already being cleaned up by the time the finalizer has run: https://github.com/mono/SkiaSharp/blob/9a0bff839b2a951334252a18f94cb7367c06c5de/binding/Binding/SKObject.cs#L63 

Any access to member/static reference fields should be guarded with `if (disposing)`.  Or Better yet, wrap the unmanaged handle in a SafeHandle and let it free it.

**Comment by davkean** [comment]
Actually I I'm wrong here - while you shouldn't really touch reference fields in finalize, none of them should null. What I suspect is happening, is that SKPaint is throwing in its constructor (perhaps https://github.com/mono/SkiaSharp/blob/9a0bff839b2a951334252a18f94cb7367c06c5de/binding/Binding/SKPaint.cs#L21) which leaves this field null, but the finalizer still is run. The following demonstrates:



``` C#
    class Program
    {
        static void Main(string[] args)
        {
            try
            {
                new SKPaint();
            }
            catch (Exception)
            {

            }
        }
    }


    class SKPaint : SKObject
    {
        public SKPaint()
            : base(sk_paint_new())
        {
        }

        private static IntPtr sk_paint_new() { throw new Exception(); }
    }

    class SKObject
    {
        private readonly List<string> ownedObjects = new List<string>();

        internal SKObject(IntPtr handle)
        {
        }

        ~SKObject()
        {
            lock (ownedObjects)
            {
            }
        }
    }
```

Which outputs:

```
Unhandled Exception: System.ArgumentNullException: Value cannot be null.
   at System.Threading.Monitor.ReliableEnter(Object obj, Boolean& lockTaken)
   at System.Threading.Monitor.Enter(Object obj, Boolean& lockTaken)
   at ConsoleApp237.SKObject.Finalize()
```

**Comment by aktzbn** [comment]
I encountered the same issue on Debian when libSkiaSharp.so was absent.

**Comment by mattleibow** [comment]
@davkean Thanks for your info and research. I fixed this issue and it is now in master.
