### ISSUE TITLE
InvalidCastException SKCanvasView on Xamarin.Forms 3.0-pre3

### ISSUE THREAD

**Issue by REDECODE** [mono/SkiaSharp#484]
Hi everyone, 
I have an InvalidCastException when I try to add an SKCanvasView inside an AbsoluteLayout because xamarin forms is unable to cast type SkiaSharp.Views.Forms.SKCanvasViewRenderer on type Xamarin.Forms.IRegisterable.

I use Xamarin.Forms 3.0-pre3 (I know is a prerelease.. maybe is because of that) in a WPF project with SkiaSharp 1.60.0

**Comment by xabre** [comment]
I'm haveing a similar issue with WPF and XF. I think there are no WPF Renderers yet for SKCanvasView.

**Comment by mattleibow** [comment]
@xabre That is correct. There are no WPF renderers at this time.
I am closing this issue as this is just a case of missing renderer. I opened a new issue with a more correct idea: https://github.com/mono/SkiaSharp/issues/486
