### ISSUE TITLE
Use GPU when generating bitmaps

### ISSUE THREAD

**Issue by pauldendulk** [mono/SkiaSharp#492]
I am using SkiaSharp to generate bitmaps in a .NET Standard project. I would like to use hardware acceleration but it looks like all the hardware accelerated surfaces are in the platform dependent views. Do you have any advice how to do this? Is there perhaps a hardware accelerated surface in the core? Is this possible at all? Should I inject the platform dependent view? Or use bait and switch?

**Comment by mattleibow** [comment]
Using the GPU to construct images is slightly different: bitmaps are raster based, so this is a pure CPU/memory process.

To create a GPU-backed image, you need to first set up a GL context as you would if you were just using normal OpenGL. Then, you instantiate the `GRContext` to create a surface.

I do this automatically for views, but for headless/.NET Standard libraries, you can have a look at what I do for my GPU tests:

For a Mac test to set up the OpenGL (or rather CGL): https://github.com/mono/SkiaSharp/blob/v1.60.0/tests/Tests/GlContexts/Cgl/CglContext.cs

Once the context is created, you can just create the `SKSurface`:

```csharp
// create the context
var grContext = GRContext.Create(GRBackend.OpenGL);

// create the surface
var surface = SKSurface.Create(grContext, true, new SKImageInfo(100, 100));

// get the canvas for drawing
var canvas = surface.Canvas;
```

I really want to create a .NET Core app that uses the GPU and OpenTK (for example), but I just haven't had the chance to get to it yet.

**Comment by pauldendulk** [comment]
Thanks a lot. I will try to create a sample my self. Maybe you can use it.

**Comment by mattleibow** [comment]
That will be great!

**Comment by mattleibow** [comment]
Closing this as it appears to be "resolved" - if a question can be marked as such.

**Comment by aspecialkey** [comment]
@pauldendulk have got an example you could post?
I`m in the same situation 
[https://stackoverflow.com/questions/53360854/skiasharp-drawing-image-with-gpu-acceleration](url)

**Comment by pauldendulk** [comment]
@aspecialkey I did never get around to implementing this. It looks like your solution is close to how it should work. Did you try disposing all objects you create?

**Comment by aspecialkey** [comment]
@pauldendulk  disposing the object makes no difference
