### ISSUE TITLE
SkiaSharp inn Linux Containers

### ISSUE THREAD

**Issue by ldubrois** [mono/SkiaSharp#499]
Hello,

I have a project with a dependency on SkiaSharp. It was originally running in Windows, and I'm now trying to get it running on a linux docker container.
My project use SkiarSharp v1.60.0. I have manually added in the same folder the libSkiaSharp.so file found in the release's assets.
But when I try to run the container, I get the "`Unable to load DLL 'libSkiaSharp': The specified module or one of its dependencies could not be found.`" error message.

Does anyone knows how to get it working on Linux / Docker ?

Thanks

**Comment by mattleibow** [comment]
Ah, you may be missing some libraries that are missing. Are you using .NET Core or Mono?

**Comment by mattleibow** [comment]
Make sure you have installed fontconfig.

**Comment by ldubrois** [comment]
It is running on net core with a runtime identifier set to debian-x64.

Is there a way to identify all the dependencies required by SkiaSharp?

**Comment by mattleibow** [comment]
It _should_ just be fontconfig, but you can check the dependencies with ldd/lddtree. But, it should just be fontconfig. If you are using GPU, the you will need to install OpenGL as well.

**Comment by mattleibow** [comment]
I created a sample repo with a small container that should just work:
https://github.com/mattleibow/SkiaSharp-Docker

**Comment by mattleibow** [comment]
Closing this as it is working in containers.
Feel free to open another issue if there is a specific problem or question.

**Comment by ldubrois** [comment]
Thanks for your sample, it now does load the library correctly but i encountered an another error : 
`Unable to find an entry point named 'sk_bitmap_lock_pixels' in DLL 'libSkiaSharp'`.

I found previous issues indicating you have to explicitly define what is used or not. Is it still correct ?

In our project, SkiaSharp is a dependency of Flexcel. Is there a way to know / list all the method used by Flexcell to get a complete list of the missing methods ?

Thanks.
