### ISSUE TITLE
Blurring Background

### ISSUE THREAD

**Issue by masiri201** [mono/SkiaSharp#500]
Hi,
I have an App where i use a model popup page with a transparent background, i have a skcanvasview on the bottom of that page and I was trying to apply a blur  with skmaskfilter, but that didnt work. I did it like this:
```csharp
SKMaskFilter mask = SKMaskFilter.CreateBlur(SKBlurStyle.Normal, 50);
                SKPaint paint = new SKPaint() {
                    Color = new SKColor(0, 0, 0, 200),
                    MaskFilter = mask,
 };
canvas.DrawPaint(paint);
```

Then i thought that I can snapshot the background turn it into a bitmap and blur it using skimagefilter, but that doesnt work eithei, the bitmap is not null but it doesnt display the image on background.

```csharp
public async void OnPaint(object sender, SKPaintSurfaceEventArgs e) {
    try {
        SKSurface surface = e.Surface;
        SKCanvas canvas = surface.Canvas;
        var data = surface.Snapshot().Encode(SKEncodedImageFormat.Png, 80);
        SKBitmap bitmap = SKBitmap.Decode(data, new SKImageInfo(e.Info.Width, e.Info.Height));

        SKMaskFilter mask = SKMaskFilter.CreateBlur(SKBlurStyle.Normal, 50);
        SKImageFilter ImageFilter = SKImageFilter.CreateBlur(5, 5);
        SKPaint paint = new SKPaint() {
            ImageFilter = ImageFilter,
            Color = new SKColor(0, 0, 0, 200),
            MaskFilter = mask,
        };
        canvas.DrawRect(new SKRect(0, 0, e.Info.Width, e.Info.Height), paint);
        SKPaint paint1 = new SKPaint() {
            Color = SKColors.Green,
        };
        if (bitmap != null) {
            canvas.DrawBitmap(bitmap, new SKPoint(0, 0), paint);
            Console.WriteLine("Usou a imagem.");
        }
        else {
            canvas.DrawPaint(paint1);
            Console.WriteLine("Não usou a imagem.");
        }
    }
    catch (Exception ex) {
        await DisplayAlert("erro canvas", ex.Message, "ok");
    }
}
```
I am using a popup page from https://github.com/rotorgames/Rg.Plugins.Popup, all i want to do is blur the background, if somebody has ever faced an issue like this please help me.

**Comment by mattleibow** [comment]
I wasn't able to find an issue with your snippet.

```csharp
var surface = e.Surface;
var canvas = surface.Canvas;

// draw usual stuff
// ...

// draw the blurry version
if (IsBusy) {
    // take a snap
    var snap = surface.Snapshot();

    // set up the blur
    var filter = SKImageFilter.CreateBlur(5, 5);
    var paint = new SkPaint {
        ImageFilter = filter
    };

    // draw the blurry screen
    canvas.DrawImage(snap, 0, 0, paint);
}
```

**Comment by masiri201** [comment]
I tried it and it didn't work,

var snap = surface.Snapshot();
            SKImageFilter ImageFilter = SKImageFilter.CreateBlur(5, 5);
            SKPaint paint = new SKPaint() {
                ImageFilter = ImageFilter,
            };
            canvas.DrawImage(snap, 0, 0, paint);

The popup page i have is a full screen popup, the background is all transparent and it has a carousel view on top with two different pages. what im trying to do is blur the popup page background and then display the pages on top of that control,  but skmaskfilter or image filter don't seem to work in my App. I just tried this snippet in a normal content page with a background image and it didnt work either, Im using Visual Studio 2017 community, im compiling to android version 8.0, i don't know if my code is wrong in any way but thank you for your time and patience.

**Comment by mattleibow** [comment]
I may be understanding wrong, but are you trying to create a blurred overlay under the popup?

SkiaSharp can only blur what you specifically draw. Maybe attach a small sample (or create a repo) that demos this so I can see your thoughts.

**Comment by masiri201** [comment]
The ideia is to blur the canvas view, it's not under the popup, it's on the surface, so basically i need to create a blured SKCanvasView, I though I could do that with SKMaskFilter but it didn't work so I tried the snapshot one. I'll try to attach a sample as soon as I'm able to.

**Comment by masiri201** [comment]
Here's the demo:

[https://drive.google.com/drive/folders/1RfQYd7yenQFHX9_r-n3MBJbYQhaQjw_S?usp=sharing](url)

Its only a button that opens the popup, i tried using skmaskfilter and taking the snapshot both didnt work.

**Comment by mattleibow** [comment]
I think I am understanding what is happening here. In your sample you are drawing nothing (or rather a gray block) as a result, only the gray block is blurred - you just can't see it as it is a solid color.

If you want the popup to blur the underlying page behind the popup, you need to use another means. I am not sure of the best mechanism, but this involves taking a screenshot of the underlying activity, blurring that screenshot, and then drawing the image on the screen. Unfortunately, SkiaSharp cannot take this screenshot as it only will get it's own canvas.

I would suggest asking on the forums for more information on this: forums.xamarin.com/

**Comment by masiri201** [comment]
Ok, thanks for your help, I'll close the issue now.
