### ISSUE TITLE
Added skiaharp to a cross-platform net standard project but wont build

### ISSUE THREAD

**Issue by davefxy** [mono/SkiaSharp#502]
I received the following error when building a VS 2017 C# cross-platform net standard project:
Warning	NU1701	Package 'SkiaSharp.Views 1.60.0' was restored using '.NETFramework,Version=v4.6.1' instead of the project target framework '.NETStandard,Version=v2.0'. This package may not be fully compatible with your project.

**Comment by mattleibow** [comment]
That is correct, the "SkiaSharp.Views" is a platform-specific project. If you are building a Xamarin.Forms app, then you need to install the "SkiaSharp.Views.Forms" package.
