### ISSUE TITLE
Drawing of wrong circles  on some android devices

### ISSUE THREAD

**Issue by kappesLab** [mono/SkiaSharp#506]
### Description
On some android devices the circles are drawn on the screen visibly lengthened. To obtain a visibly acceptable circle you must draw an oval with a ratio of 10 to 8, then with rx=100 pixels and ry=80 pixels.

### Code
           var info =  e.Info;
           var surface = e.Surface;
           var canvas  = surface.Canvas;

            // CLEARING THE SURFACE
            canvas.Clear(SKColors.White);

            // DRAWING SHAPES

            // create the paint for the outline of the circle
            SKPaint paint = new SKPaint
            {
                Style = SKPaintStyle.Stroke,
                Color = SKColors.Red,
                StrokeWidth = 25
            };

            // draw the outline of the circle
            canvas.DrawCircle(info.Width / 2, info.Height / 2, 100, paint);

### Expected Behavior
I expect a circle with the same height and width.

### Actual Behavior
On some Android devices the circle shown on the display is extended vertically.

### Basic Information

- Version with issue:  1.60.0
- IDE:  Visual Studio Community 2017 (15.6.7)
- Platform Target Frameworks: 
  - Android: 6.0
 
### Screenshoot
![img_4185b](https://user-images.githubusercontent.com/36405345/39711381-e40192cc-521f-11e8-91cc-8bf56f1509cd.jpeg)

**Comment by kappesLab** [comment]
This problem occurs only with the device _"ASUS - Thinker board/2GB - Android 6.0.1"_ (Part. No. 90MB0QY1-M0EAY0) connected to an _"elo Touch"_ monitor model ET1093L.

The defect could be due to the fact that the Asus board has an output resolution of 1280x720px while the monitor resolution is 1280x800px ?

**Comment by mattleibow** [comment]
That might be it... Are any other controls stretched? Also, what is the pixel dimensions of the canvas (`e.Info`) and the view dimensions?

**Comment by kappesLab** [comment]
It is difficult to determine if there are any other stretched controls, with a circle, as with a square, the difference between height and width is evident. 

For the information that you have requested I enclose the following _sreenshoot_:

![screenshot_20180509-085606](https://user-images.githubusercontent.com/36405345/39806048-13e2139a-5379-11e8-8205-8c38affb6688.png)
-------
produced by the following _code_:

            SKImageInfo info = e.Info;
            SKSurface surface = e.Surface;
            SKCanvas canvas = surface.Canvas;

            canvas.Clear(SKColors.White);

            SKPaint paint = new SKPaint
            {
                Color = SKColors.Black,
                TextSize = 40
            };

            float fontSpacing = paint.FontSpacing;
            float x           = 20;               // left margin
            float y           = fontSpacing;      // first baseline
            float indent      = 100;

            canvas.DrawText("SKCanvasView Height and Width:", x, y, paint);
            y += fontSpacing;
            canvas.DrawText(String.Format("{0:F2} x {1:F2}", canvasView.Width, canvasView.Height), x + indent, y, paint);
            y += fontSpacing * 2;
            canvas.DrawText("SKCanvasView CanvasSize:", x, y, paint);
            y += fontSpacing;
            canvas.DrawText(canvasView.CanvasSize.ToString(), x + indent, y, paint);
            y += fontSpacing * 2;
            canvas.DrawText("SKImageInfo Size:", x, y, paint);
            y += fontSpacing;
            canvas.DrawText(info.Size.ToString(), x + indent, y, paint);

Tomorrow, with this accessory [elo touch cable OSD](https://www.amazon.it/dp/B00C1Q92A0/ref=pe_3310731_185740161_TE_item) I try to inhibit screen resizing on the monitor.

Thank you very much for your interest.

**Comment by mattleibow** [comment]
Another thing that you could try is to do the same drawing without SkiaSharp and just use the native Android APIs.

This looked like an interesting case, so I have created a sample app that tries to draw using Xamarin.Forms, SkiaSharp and Android.Graphics: https://github.com/mattleibow/AndroidStretchingTests

Let me know if there are any differences between drawings - they should all be exactly the same.

**Comment by kappesLab** [comment]
By running the [AndroidStretchingTests](https://github.com/mattleibow/AndroidStretchingTests) on my device I get the three views exactly the same, all three stretched out in the same way along the vertical axis.

I apologise for the delay, but I have only now resumed the project.

In view of the outcome, I consider this _issue_ to be closed.

**Comment by mattleibow** [comment]
Ok, looks as if the screen/android is stretching the entire view/app.
