### ISSUE TITLE
How can I Create Crayon color using ColorFilter? 

### ISSUE THREAD

**Issue by jigneshbodarya** [mono/SkiaSharp#508]
I want to create this kind of color using skiasharp.

![a4098528-471f-4f68-aa73-1c16987c0453](https://user-images.githubusercontent.com/26847946/39737379-5e5b8816-52a2-11e8-8ff3-1b820570c3d5.png)

Please help me.

**Comment by mattleibow** [comment]
This may require a combination of filters. I am not sure exactly, but I would ask on the official Google forums: https://groups.google.com/d/forum/skia-discuss

The guys there will know all that skia is capable of and what the best way to achieve this is.
