### ISSUE TITLE
[UWP] touch event bug when pixels ≠ device independent pixels

### ISSUE THREAD

**Issue by charlesroddie** [mono/SkiaSharp#515]
### Description

On UWP, when `scale` = (pixels / device independent pixels) ≠ 1.
The Touch event fires within a subset of the View (1/scale in each dimension), but Location reports numbers that are too large, by a factor of `scale`.

The possible Location values correctly correspond to the view area in pixels, but they are realized on a subset of the view only.

### Basic Information

- Version with issue:  1.60.0
- IDE:  VS 15.7.0
- Platform Target Frameworks: UWP (other platforms not tested)
  - UWP:  16299 

### Screenshots

<img width="938" alt="skiasharptouchproblem" src="https://user-images.githubusercontent.com/19760720/39871868-1e62ffc4-545e-11e8-9320-1fe79b359024.png">

**Comment by mattleibow** [comment]
Thanks for reporting this.
This is the same issue as https://github.com/mono/SkiaSharp/issues/474.

**Comment by charlesroddie** [comment]
Thanks; I should have noticed that.
