### ISSUE TITLE
Trouble compiling, Missing some files included in SkiaKeeper.c

### ISSUE THREAD

**Issue by ariste1a** [mono/SkiaSharp#52]
Hey guys, not sure if this is the place to ask, but I'm trying to compile SkiaSharp via the instructions and  some files are missing that are referenced in SkiaKeeper.c, specifically sk_typeface.h, sk_stream.h, and sk_bitmap.h.

**Comment by tdenniston** [comment]
@ariste1a I am also seeing this problem. Can you please elaborate on how you fixed it?

**Comment by ariste1a** [comment]
Hey @tdenniston, and anyone else having the same problem, SkiaSharp uses its own branch of Skia which you'd have to pull/download. Navigate to this repo's Skia folder and pull from it. Not sure how to do it from git bash though. You'd also need Google's depot tool to compile.

**Comment by tdenniston** [comment]
Thanks @ariste1a. I can't seem to identify an actual branch of Skia that SkiaSharp uses, but I managed to fix my compile error with the following steps:

- Open the mono/SkiaSharp master branch on Github.
- The 'skia' directory is displayed as something like 'skia @ 15d4e8e'. Take note of the commit hash after the @ sign.
- In Git bash navigate to the 'skia' directory on your filesystem. Execute 'git checkout 15d4e8e'.
- Try rebuilding SkiaSharp.

This fixed this particular compile error for me. Hopefully one of the maintainers can comment on why this was necessary.
