### ISSUE TITLE
Understanding PixelScaling

### ISSUE THREAD

**Issue by pauldendulk** [mono/SkiaSharp#527]
### Description

I am somewhat confused about the system scale in Skia. Below is a sample that draws a line diagonally across the screen to the lower right corner (see screenshot). It does not end there because of the windows screen scale (of 1.25  in this case). I can compensate for this in two ways (see 'solution' in code comments). 

1. Ignore pixel scaling
2. Scale the canvas

My question is, are these methods equivalent, or will one or the other work with a bigger bitmap in the background? 

Also, I don't really understand why I, as a user, need to deal with the windows scaling at all. Should there perhaps be a way to set the dpi of the canvas instead, and keep the coordinate system intact at all times, unless the user explicitly scales the canvas?

### Code

```c#
using System;
using System.Windows;
using System.Windows.Media;
using SkiaSharp;
using SkiaSharp.Views.Desktop;

namespace WpfScaleIssue
{
    /// <summary>
    /// Interaction logic for MainWindow.xaml
    /// </summary>
    public partial class MainWindow
    {
        private float _scale;
        private float _width;
        private float _height;

        public MainWindow()
        {
            InitializeComponent();

            // Solution 1) Ignore pixel scaling
            // SkiaCanvas.IgnorePixelScaling = true;

            SkiaCanvas.PaintSurface += SkiaCanvasOnPaintSurface;
            CompositionTarget.Rendering += (sender, args) => InvalidateVisual();

            SizeChanged += (sender, args) =>
            {
                _scale = DetermineSkiaScale();
                _width = (float)SkiaCanvas.ActualWidth;
                _height = (float)SkiaCanvas.ActualHeight;
            };
        }

        private void SkiaCanvasOnPaintSurface(object sender, SKPaintSurfaceEventArgs args)
        {
            // Solution 2) Scale the canvas
            // args.Surface.Canvas.SetMatrix(SKMatrix.MakeScale(_scale, _scale));
            
            Draw(args.Surface.Canvas);
        }

        private void Draw(SKCanvas canvas)
        {
            canvas.Clear(SKColors.LightPink);
            canvas.DrawLine(0, 0, _width, _height, new SKPaint { Color = SKColors.Red });
            canvas.DrawCircle(_width, _height, 10, new SKPaint { Color = SKColors.Red });
        }

        private float DetermineSkiaScale()
        {
            var presentationSource = PresentationSource.FromVisual(this);
            if (presentationSource == null) throw new Exception("PresentationSource is null");
            var compositionTarget = presentationSource.CompositionTarget;
            if (compositionTarget == null) throw new Exception("CompositionTarget is null");

            var matrix = compositionTarget.TransformToDevice;

            var dpiX = matrix.M11;
            var dpiY = matrix.M22;

            if (dpiX != dpiY) throw new ArgumentException();

            return (float)dpiX;
        }
    }
}

```
### Basic Information

- Version with issue:  1.60.1
- Last known good version:  All the same
- IDE:  Visual Studio
- Platform Target Frameworks: WPF

### Screenshots

![image](https://user-images.githubusercontent.com/963462/40476122-8a03dd9e-5f43-11e8-88f8-4e84559cdb39.png)

### Reproduction Link

https://github.com/pauldendulk/SkiaSharpPlayGround

**Comment by pauldendulk** [comment]
There is some information in this article: [Pixels and Device-Independent Units](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/graphics/skiasharp/basics/pixels).

I don't work with Forms. Measuring these values in WPF I get the values below.

**WPF with IgnorePixelScale = false**
- SkiaCanvas.ActualWidth = 785
- SkiaCanvas.CanvasSize.Width = 982
- args.Info.Width = 982

**WPF with IgnorePixelScale = true**
- SkiaCanvas.ActualWidth = 785
- SkiaCanvas.CanvasSize.Width = 785
- args.Info.Width = 785

On iOS and UWP I get a similar pattern. On Android the pattern is different however.

**Android with IgnorePixelScale = false**
- _skCanvasView.Width = 1080
- _skCanvasView.CanvasSize.Width = 1080
- args.Info.Width = 1080

**Android with IgnorePixelScale = true**
- _skCanvasView.Width = 1080
- _skCanvasView.CanvasSize.Width = 360
- args.Info.Width = 360

I now understand part of my confusion. On Android I get coordinates in device pixels and on the other systems I get device independent units. This is why I failed to implement my platforms in a consistent way. 

The article above states

> If you'd prefer to work entirely in device-independent units, you can do so by setting the IgnorePixelScaling property of the SKCanvasView to true. However, you might not like the results. SkiaSharp renders the graphics on a smaller device surface, with a pixel size equal to the size of the view in device-independent units. 

So, is it correct to say that IgnorePixelScale could be read as UseDeviceIndependentUnits? 

What I also find confusing that with some called 'ignore' I expect it to do nothing, but in the case of Android I does actually alter my coordinate system.

**Comment by pauldendulk** [comment]
For me this item can be closed. There is documentation here on IgnorePixelScaling.
https://docs.microsoft.com/en-us/dotnet/api/skiasharp.views.ios.skcanvasview.ignorepixelscaling?view=skiasharp-views-1.68.1.

For our purposes in Mapsui IgnorePixelScaling was just the wrong way of scaling. It caused pixelation as described in the docs. We use SKCanvas.Scale(float sx, float sy) instead.

Another part of the confusion was that on Android we get coordinates in device pixels and on the other platforms we get coordinates in device independent units. We correct for this with our PixelDensity field.

**Comment by mattleibow** [comment]
@pauldendulk yeah... unfortunately I made bad decisions about that one. No idea why I did it that way, it was always bad.

I am thinking of re-working that one maybe in the v2 release. This should be the same code, but the correct implementation. Effectively transparent to the user.

**Comment by pauldendulk** [comment]
> I am thinking of re-working that one maybe in the v2 release. This should be the same code, but the correct implementation. Effectively transparent to the user.

ah, great. I also found the name IgnorePixelScaling not very clear. Perhaps something like AutoScale would be better.
