### ISSUE TITLE
Having problem cloning repro in Visual Studio 2015 Update 2

### ISSUE THREAD

**Issue by alanricker** [mono/SkiaSharp#53]
I'm getting this message when trying to clone the repro:
    "The repository was cloned, but an error was encountered while recursively cloning submodules.     Error message: The top level repository was cloned, but there was an error cloning its submodules."

I don't have issues with other repros and github.

Thanks!

**Comment by migueldeicaza** [comment]
Not a bug in SkiaSharp, we will keep an eye though.

**Comment by Jaytt** [comment]
How to solve this?

**Comment by mattleibow** [comment]
I think this was maybe a error in the git clone?

**Comment by emanolio** [comment]
This is also happening to me. I have Visual Studio 2015 Update 3. I deleted the clone multiple times and I still get this error. I installed Git for Windows and was able to clone the repository just fine. I'd rather use Visual Studio.

**Comment by mattleibow** [comment]
I haven't tested VS2015 yet, but VS2017 works fine for me. Maybe you had a connection hiccup.
Also, I just want to mention that the new master no longer supports VS2015 - we are working on VS2017.

**Comment by redwhat** [comment]
@mattleibow What do you mean by "the new master no longer supports VS2015"?

**Comment by mattleibow** [comment]
Just that I haven't done any testing in VS2015 - we are moving on to VS2017 and not looking back! The chances are that things will still work, just that I am no longer doing any testing there and I may/may not fix any issues with VS2015. If you really need things to work in VS2015, you probably will have to send in a PR that fixes it yourself.
