### ISSUE TITLE
SKShader performance hit in v1.60 and v1.61

### ISSUE THREAD

**Issue by rvlajcev** [mono/SkiaSharp#543]
### Description

It seems that versions 1.60 and 1.60.1 introduced a performance hit with
SKShader.CreateSweepGradient rendering time.
Not exactly the most precise method,
but there is some noticeable difference between SkiaSkarp versions.

### XAML
```
<Grid>
        <Grid.RowDefinitions>
            <RowDefinition Height="*" />
            <RowDefinition Height="100" />
        </Grid.RowDefinitions>

        <skia:SKCanvasView Grid.Row="0"
                           x:Name="canvasView"
                           PaintSurface="OnPaintSurface"
                           EnableTouchEvents="True"
                           Touch="SkiaTouch" />

        <Label Grid.Row="1"
               x:Name="lblTimer"
               FontSize="24"
               HorizontalTextAlignment="Center"
               VerticalTextAlignment="Center"/>
</Grid>
```
### Code behind
```
public partial class MainPage : ContentPage
    
	{
        private int millis;
        public MainPage()
        {
            InitializeComponent();
            var touchTimer = new Timer { Interval = 1 };
            touchTimer.Elapsed += ElapsedMillis;
            touchTimer.Start();
        }

        private void ElapsedMillis(object sender, ElapsedEventArgs args)
        {
            millis++;
        }

        private void OnPaintSurface(object sender, SKPaintSurfaceEventArgs args)
        {
            var canvas = args.Surface.Canvas;
            var scale = (float)(args.Info.Width / canvasView.Width);
            canvas.Scale(scale);
            canvas.Clear(SKColors.White);

            var width = canvas.LocalClipBounds.Width;
            var height = canvas.LocalClipBounds.Height;

            var defaultSkColors = new SKColor[4];
            defaultSkColors[0] = new SKColor(255, 0, 0);
            defaultSkColors[1] = new SKColor(0, 255, 0);
            defaultSkColors[2] = new SKColor(0, 0, 255);
            defaultSkColors[3] = new SKColor(255, 0, 0);

            var centerPoint = new SKPoint(width / 2, height / 2);

            var shader = SKShader.CreateSweepGradient(centerPoint, defaultSkColors, null);

            SKPaint paint = new SKPaint
            {
                Style = SKPaintStyle.Stroke,
                Shader = shader,
                IsAntialias = true,
                StrokeWidth = 150

            };

            canvas.DrawCircle(width / 2, height / 2, 100, paint);
            lblTimer.Text = millis.ToString();
        }

        private void SkiaTouch(object sender, SKTouchEventArgs args)
        {
            if (args.ActionType != SKTouchAction.Pressed) return;
            millis = 0;
            canvasView.InvalidateSurface();
        }

    }
```
### Behavior
Xamarin Forms: 3.0.0.482510

**## HTC One X (Android 5.1) results:**

**SkiaSharp version: 1.60.1**
Configuration: debug
Rendering time (avg of 5): 177ms

Configuration: release
Rendering time (avg of 5): 181ms

**SkiaSharp version: 1.60**
Configuration: debug
Rendering time (avg of 5): 171ms

Configuration: release
Rendering time (avg of 5): 184ms

**SkiaSharp version: 1.59.3**
Configuration: debug
Rendering time (avg of 5): 58ms

Configuration: release
Rendering time (avg of 5): 51ms

**## Huawei Y6 (Android 8.0)
Notice discrepancy between debug and release configurations**

**SkiaSharp version: 1.60.1**
Configuration: debug
Rendering time (avg of 5): 28ms

Configuration: release
Rendering time (avg of 5): 196ms

**SkiaSharp version: 1.60**
Configuration: debug
Rendering time (avg of 5): 29ms

Configuration: release
Rendering time (avg of 5): 198ms

**SkiaSharp version: 1.59.3**
Configuration: debug
Rendering time (avg of 5): 56ms

Configuration: release
Rendering time (avg of 5): 50ms

### Basic Information
- Version with issue:  1.60 and 1.60.1
- Last known good version:  1.59.3
- IDE:  Visual Studio 2017
- Platform Target Frameworks: 
  - Android: 8.0, 8.1 
  
- Target Devices:
 HTC One X, Huawei Y6
Can test on more if needed

**Comment by mattleibow** [comment]
I believe this was fixed in v1.69.0. Also, it may be better to use a stopwatch to measure the duration of the method.
