### ISSUE TITLE
SKPath, move point

### ISSUE THREAD

**Issue by VoteForPedro** [mono/SkiaSharp#545]
It possible to move single point inside skPath without recreate it?

```
      public void OffsetPointAt(int index, SKPoint p)
        {
            var points = skPath.Points;
            points[index] += p;
            CreatePath(points);
            IsDirty = true;
        }

        protected virtual void CreatePath(SKPoint[] points)
        {
            skPath.Reset();
            skPath.AddPoly(points, true);
        }
```
OffsetPointAt called from touch handler, on move.

**Comment by mattleibow** [comment]
I don't _think_ this is a feature, but it may just be that I haven't come across it in the common API. I would suggest asking on the official skia forums (https://groups.google.com/forum/#!forum/skia-discuss) as they know everything and might be able to show you a "workaround".

**Comment by mattleibow** [comment]
Closing this as the discussion needs to be on the native forums.
