### ISSUE TITLE
Layered SKGLViews with Xamarin Forms

### ISSUE THREAD

**Issue by mgiova** [mono/SkiaSharp#546]
### Description

My application uses 2 different SKGLViews stacked on top of each other to separate the drawing of the background from that of the foreground. This has been working in Android up until version 1.59.3 and stopped in version 1.60. It still works in UWP or if I use SKCanvasView.

###### Xaml
```
<RelativeLayout HorizontalOptions="FillAndExpand" VerticalOptions="FillAndExpand">
    <skia:SKGLView x:Name="canvasView"
        PaintSurface="OnPaintSurface"
        RelativeLayout.WidthConstraint="{ConstraintExpression Type=RelativeToParent, Property=Width, Factor=1}"
        RelativeLayout.HeightConstraint="{ConstraintExpression Type=RelativeToParent, Property=Height, Factor=1}"
    />

    <skia:SKGLView x:Name="canvasView2"
        PaintSurface="OnPaintSurface2"
        RelativeLayout.WidthConstraint="{ConstraintExpression Type=RelativeToParent, Property=Width, Factor=1}"
        RelativeLayout.HeightConstraint="{ConstraintExpression Type=RelativeToParent, Property=Height, Factor=1}"
    />
</RelativeLayout>
```

###### C#
```
private void OnPaintSurface(object sender, SKPaintGLSurfaceEventArgs e)
{
    e.Surface.Canvas.Clear(SKColors.Blue);
}

private void OnPaintSurface2(object sender, SKPaintGLSurfaceEventArgs e)
{
    e.Surface.Canvas.Clear(SKColors.Transparent);
}
```

### Expected Behavior

The top view should be rendered transparent and the bottom canvas should be blue.

### Actual Behavior

The top view is black and the bottom view isn't visible.

### Basic Information

- Version with issue:  1.60, 1.60.1
- Last known good version:  1.59.3
- IDE:  Visual Studio 2015, 2017
- Platform Target Frameworks:
  - Android: 6.0
- Target Device:
  - Samsung Galaxy Tab S

### Reproduction Link

VS2015 Solution @ https://www.dropbox.com/s/qnazdsna10wfer0/TestSkia.zip?dl=0

**Comment by mattleibow** [comment]
This is interesting. In v1.60.x we changed from a `GLSurfaceView` to `TextureView` which _should_ have been a better - in fact, the surface view should not have allowed stacking.

But, since you had it working it appears all my beliefs are crashing down. I will investigate and get back to you as soon as possible.

**Comment by mgiova** [comment]
This is a recurrence of #206 but for the Android platform.

The problem disappears if you set the nativeview transparent with Control.SetOpaque(false) in a custom renderer.

**Comment by mattleibow** [comment]
@mgiova thanks for looking into this. I have got a fix.
