### ISSUE TITLE
SkiaFormsDemoiOS fails to build

### ISSUE THREAD

**Issue by alanricker** [mono/SkiaSharp#55]
I have latest of Visual Studio 2015 Update 2 & latest samples.
It seems to connect to Mac, but I get this error:

> 1>------ Rebuild All started: Project: Skia.Forms.Demo, Configuration: Debug Any CPU ------
1>  Skia.Forms.Demo -> C:\Users\Alan\Source\Repos\SkiaSharp4\samples\Skia.Forms.Demo\bin\Debug\Skia.Forms.Demo.dll
2>------ Rebuild All started: Project: Skia.Forms.Demo.iOS, Configuration: Debug iPhoneSimulator ------
2>  Generated session id: 3fdec0ee21268ffdc7262eca8ff7ce40
2>  Generated build app name: SkiaFormsDemoiOS
2>  Connecting to Mac server iMac.local...
2>C:\Program Files (x86)\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets(996,3): warning : The app icon set "AppIcons" has an unassigned child.
2>  Skia.Forms.Demo.iOS -> C:\Users\Alan\Source\Repos\SkiaSharp4\samples\Skia.Forms.Demo\iOS\bin\iPhoneSimulator\Debug\SkiaFormsDemoiOS.exe
2>C:\Program Files (x86)\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets(673,3): error : Unknown command line argument: '--target-framework'
2>C:\Program Files (x86)\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets(673,3): error : You should provide one root assembly only, found 2 assemblies: 'Xamarin.iOS,v1.0', 'bin/iPhoneSimulator/Debug/SkiaFormsDemoiOS.exe'
========== Rebuild All: 1 succeeded, 1 failed, 0 skipped ==========

**Comment by bholmes** [comment]
@alanricker I am still working to reproduce this one.  While I do that, I want to suggest that you ensure that the installed versions for Windows/VS match the versions installed on the Mac Build Host you are connected to.  

Please let me know if the does or does not work.

**Comment by alanricker** [comment]
Bill, 

Thanks for the suggestion.
Can you point me to documentation on how to do that?

I did an update of my Mac to latest Xamarin tools.
Anything else I need to do?

Alan

**Comment by alanricker** [comment]
Thanks for the suggestion.
I updated both sides again including the git repo & now it builds and runs.

Thanks again for all your great work & assistance!
