### ISSUE TITLE
SKColorSpace.CreateIcc() always returns null with CMYK ICC profiles

### ISSUE THREAD

**Issue by dsyno** [mono/SkiaSharp#551]
### Description

`SKColorSpace.CreateIcc(Byte[] input)` returns null when inputting CMYK ICC profiles. Whereas, it works as expected with RGB ICC profiles.

I suspect SkiaSharp may require this Skia fix: https://bugs.chromium.org/p/chromium/issues/detail?id=727128

### Code

	var cmykICC_ByteArray = ...; // convert CMYK ICC profile into a byte array
	var cmykColorSpace = SKColorSpace.CreateIcc(cmykICC_ByteArray);
	if (cmykColorSpace == null)
	{
		// colorspace is null
	}

### Expected Behavior

CMYK `SKColorSpace` should be created.

### Actual Behavior

CMYK `SKColorSpace` is not created. `SKColorSpace.CreateIcc(cmykICC_ByteArray)` returns null.

### Basic Information

- Version with issue:  1.60.0
- IDE:  Visual Studio
- Platform Target Frameworks: .NET Core 2.0 (AWS Lambda)

### ICC Profiles for Testing

You can use the two ICC profiles in this zip file, to use with the test code above.

Adobe ICC profiles (contains RGB and CMYK profiles): 
[AdobeICC.zip](https://github.com/mono/SkiaSharp/files/2103035/AdobeICC.zip)

> VS bug [#738680](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/738680)

**Comment by dsyno** [comment]
What's your feedback on this @mattleibow?

**Comment by mattleibow** [comment]
This is something that we will be looking at in the future.

**Comment by mattleibow** [comment]
Newer versions of SkiaSharp support loading images with CMYK color spaces, but it appears that we are no longer able to actually _create_ instances to use. SkiaSharp looks to be RGB-only.
