### ISSUE TITLE
SKFontManager and newly installed fonts

### ISSUE THREAD

**Issue by antongit** [mono/SkiaSharp#553]
### Description
Hello,

I'm on a Windows Desktop and trying to use a font which is installed (by choosing a font file in the explorer > install) during my App is running. Unfortunately the font is available for Skia only after restarting the App. Is it somehow possible to force SKFontManager to pick up newly installed fonts?

### Code
I'm trying:
`SKTypeface.FromFamilyName()`
`SKFontManager.FontFamilyCount`
### Expected Behavior
Don't know if it's possible for SKFontManager to pick up new fonts which are installed when the skia is running.

### Actual Behavior
`FontFamilyCount` doesn't change and `FromFamilyName` returns the default font.

### Basic Information

- Version with issue:  10.60.1
- Windows Classic:  Windows10

**Comment by mattleibow** [comment]
This is an interesting case. Google has designed the font manager as a singleton. In the constructors, they query the system, and then assume it will never change. I wonder what will happen if you were to uninstall a font...

I would suggest asking Google directly on their forums: https://groups.google.com/forum/m/#!forum/skia-discuss

**Comment by mattleibow** [comment]
I am closing this as there is nothing that can be done without actually changing the native implementation. Please re-open if they indicate there is a way to update the manager and I will make sure that you can do the same with SkiaSharp.

**Comment by antongit** [comment]
@mattleibow:
Hello Matthew,

I've just got a reply from the Google forums regarding the Font Manager.
Would you please check it and maybe you'll had a chance to answer their question?
https://groups.google.com/forum/#!topic/skia-discuss/wVFB2gSfPwU

Thank you!

Best,
Anton

**Comment by mattleibow** [comment]
I see. So they just spin up a new font manager. I'll see if I can get this in.

**Comment by antongit** [comment]
Amazing!

**Comment by mattleibow** [comment]
I have added this into the next major release: v1.67.0. Pending release.

**Comment by antongit** [comment]
Thank you!
