### ISSUE TITLE
Request for Skia.Forms.Demo.UWP (Universal Windows) Example

### ISSUE THREAD

**Issue by alanricker** [mono/SkiaSharp#56]
Are you creating an example for this configuration also?

**Comment by JimSEOW** [comment]
has anyone manage to try the https://github.com/mono/SkiaSharp/tree/windows-uwp?
Please add a UWP to:
https://github.com/mono/SkiaSharp/tree/windows-uwp/samples/Skia.Forms.Demo

**Comment by mattleibow** [comment]
Hi @alanricker and @JimSEOW I have just pushed a version to NuGet with UWP support. The repo also has a UWP sample. Forms will be coming very soon.

**Comment by mattleibow** [comment]
Added a UWP Xamarin.Forms sample in a0a2991afb48160f169808dc66e24212cd7591c6
