### ISSUE TITLE
BadImageFormatException on .NET Framework 4.6.2 with AnyCPU setting AND Cannot found libskiasharp on desing view

### ISSUE THREAD

**Issue by TerceraFaseSoftware** [mono/SkiaSharp#572]
### Description

We are having problems with SkiaSharp 1.60.2 when we try to run our desktop application. The problem, in our opinion, is that you are not choosing correctly between x64 and x86 when compiling the solution.

On the other hand, we are having problems with the design view of the forms that use skiasharp (we can not use the design view on that forms) and we believe that this error could be related to the previous one.

I do not know if it will help or not, but if the problem is to decide on which platform to run the SkiaSharp version, a possible solution could be this:

### Code

var uri = new Uri(typeof(DWGSpatialDriver).Assembly.CodeBase);
var path = Path.Combine(Path.GetDirectoryName(uri.LocalPath), IntPtr.Size == 8 ? "x64" : "x86");

### Basic Information

- Version with issue:  1.60.2
- Last known good version:  
- IDE:  Visual Studio 2017 (15.7.4)
- Platform Target Frameworks: 
  - Android:  
  - Windows Classic: Windows 10  
- Target Devices:
  -   

### Screenshots

![image](https://user-images.githubusercontent.com/37209374/42156578-b9be7690-7deb-11e8-8def-fdd11a5c2049.png)

### Reproduction Link

> VS bug [#738682](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/738682)

**Comment by Danielku15** [comment]
I personally decided to rather load the native libs manually before start using SkiaSharp. It gives quite nice control about where to exactly load it from: 

Simplified version of the helper class I'm using: 
```cs
public static class SkiaHelper
{
	[DllImport("kernel32.dll", CharSet = CharSet.Auto, SetLastError = true)]
	private static extern IntPtr LoadLibrary(string libname);

	public static void LoadNativeLibrary()
	{
		var libSkiaSharpPath = Path.GetDirectoryName(typeof(Program).Assembly.Location);
		string runtime;
		switch (Environment.OSVersion.Platform)
		{
			case PlatformID.MacOSX:
				libSkiaSharpPath = Path.Combine(libSkiaSharpPath, "runtimes", "osx", "native",
					"libSkiaSharp.dylib");
				break;
			case PlatformID.Unix:
				runtime = IntPtr.Size == 4 ? "tizen-x86" : "tizen-x64";
				libSkiaSharpPath = Path.Combine(libSkiaSharpPath, "runtimes", runtime, "native",
					"libSkiaSharp.so");
				break;
			default:
				runtime = IntPtr.Size == 4 ? "win-x86" : "win-x64";
				libSkiaSharpPath = Path.Combine(libSkiaSharpPath, "runtimes", runtime, "native",
					"libSkiaSharp.dll");
				break;
		}

		Console.WriteLine($"Loading native lib from '{libSkiaSharpPath}'");
		
		// for .net core
		// var lib = System.Runtime.InteropServices.NativeLibrary.Load(libSkiaSharpPath);
		// for .net framework
		var lib = LoadLibrary(libSkiaSharpPath);
		
		Console.WriteLine(lib == IntPtr.Zero
			? $"Loading native lib from '{libSkiaSharpPath}' failed"
			: $"Loading native lib from '{libSkiaSharpPath}' successful"
		);
	}
}
```

The manual load is picked up by SkiaSharp. The different runtimes can be adopted based on the platforms you actually use and which libs you want to load.

**Comment by mattleibow** [comment]
I have recently worked a bit on the targets and the library to get them to work far better with .NET Framework.
However, I am not sure if there is a way to reliably and generically load the libSkiaSharp.dll from the NuGet package - for the designer. 

The good thing is that it works with the .NET Core designer.

I am going to close this as the most probably way to make use of SkiaSharp in the old .NET Framework designer is to probably use the `DesignMode` on controls and not actually draw anything.

If there is another way to get the net4x designer to work, then please open a new issue with any suggestions. I will also see what I can do with the designer teams.

**Comment by Mindfulplays** [comment]
@Danielku15 Thank you for the great solution. 
This is a major problem using a project that works on Windows 10 on a PC; the same project doesn't work on say, Windows 10 on a M1 because of the way SkiaSharp looks up the DLL.
Could @Danielku15 's solution be incorporated as part of SkiaSharp itself please? @mattleibow :) 
I haven't experienced a similar problem with other components, so it seems particular to SkiaSharp (native lib).
thank you in advance!
