### ISSUE TITLE
Unexpected Native File Size Increase

### ISSUE THREAD

**Issue by mattleibow** [mono/SkiaSharp#573]
### Description

The native libraries are getting larger with each v1.60 release. The build system has been changing, so the added linker settings may have gone missing.

Some related issues #174 and https://github.com/luberda-molinet/FFImageLoading/issues/893

### Basic Information

- Version with issue: v1.60.x
- Last known good version: v1.59.x

**Comment by EmilAlipiev** [comment]
i can confirm that i downgraded back to 1.60.0 version and my app has 6 mb size reduced. problem starts with 1.60.1.
