### ISSUE TITLE
VS for Mac, Azure Functions local development, MacOS

### ISSUE THREAD

**Issue by aeonblaire** [mono/SkiaSharp#574]
### Description

I am developing Azure functions on my Mac machine and it gives me:
Unable to load DLL 'libSkiaSharp': The specified module or one of its dependencies could not be found.\n (Exception from HRESULT: 0x8007007E)

I don't see a "bin/Debug/netstandard2.0/bin/libSkiaSharp*" file.
There is a
"bin/Debug/netstandard2.0/bin/SkiaSharp.dll"
and
"bin/Debug/netstandard2.0/bin/runtimes/osx/native/libSkiaSharp.dylib"

I tried with a .NET 4.7 Console app and a .NET Core Console app, and they both work.

The .NET 4.7 Console app has:
"bin/Debug/SkiaSharp.dll"
"bin/Debug/libSkiaSharp.dll"
"bin/Debug/libSkiaSharp.dylib"

The .NET Core Console app has no SkiaSharp binaries from the NuGet package in:
"bin/Debug/netcoreapp2.0"

### Expected Behavior

Runs without issues.

### Actual Behavior

Gives:
Unable to load DLL 'libSkiaSharp': The specified module or one of its dependencies could not be found.\n (Exception from HRESULT: 0x8007007E)

### Basic Information

- Version with issue:  1.60.2
- Last known good version: n/a
- IDE:  Visual Studio for Mac 7.5.2 build 40
- Platform Target Frameworks:
  - macOS High Sierra 10.13.5

**Comment by aeonblaire** [comment]
I copied "bin/Debug/libSkiaSharp.dll" from the .NET 4.7 Console app
and "bin/Debug/netstandard2.0/bin/runtimes/osx/native/libSkiaSharp.dylib" from the Azure Function project to "bin/Debug/netstandard2.0/bin/" of the Azure Function project and it worked.

Maybe "bin/Debug/netstandard2.0/bin/runtimes/osx/native/libSkiaSharp.dylib" from the Azure Function project is the same as "bin/Debug/libSkiaSharp.dylib" from the .NET 4.7 project? Its from the Nuget package right?

What is the difference between SkiaSharp.dll and libSkiaSharp.dll?

**Comment by mattleibow** [comment]
Thanks for reporting this. I had a look and I can confirm that the VSMac runner seems to not copy the native binaries. All is working on Windows. I have contacted the VSMac teams this side to see if they know if there is a bug or something.

With regards to the differences between the assemblies... SkiaSharp.dll is a managed assembly that is written in C# and allows you to write code in C#. The libSkiaSharp.dll/.dylib/.so is the platform-specific, native binary that is the underlying skia engine. Depending on the platform, the same SkiaSharp assembly talks to the different versions of libSkiaSharp.

**Comment by mattleibow** [comment]
This issue appaears to be related to the tooling and will be tracked and fixed in https://github.com/mono/monodevelop/issues/6673
