### ISSUE TITLE
SKColorFilter.CreateGamma missing

### ISSUE THREAD

**Issue by deakjahn** [mono/SkiaSharp#575]
### Description

I'm after SKColorFilter.CreateGamma which, according to the [documentation](https://developer.xamarin.com/api/member/SkiaSharp.SKColorFilter.CreateGamma/p/System.Single/) and the Skia source code should probably still exist somewhere.

### Expected Behavior

Gamma.

### Actual Behavior

No gamma.

### Basic Information

- Version with issue:  1.60

**Comment by mattleibow** [comment]
Unfortunately, Google removed that method, so there is nothing I can do about it directly. If you have a look at the "Assembly Versions" section, you can see it is only supported from v1.54 to v1.57.

**Comment by mattleibow** [comment]
I see you started a discussion on the skia forums. I think they misunderstood because I do things a bit differently, so I made a comment and hopefully they can help out.

https://groups.google.com/forum/#!topic/skia-discuss/Nw9QT7gcl-U

**Comment by mattleibow** [comment]
Closing this as the issue was resolved on the skia forums.
