### ISSUE TITLE
SkiaSharp 1.60.2 NuGet missing PCL support

### ISSUE THREAD

**Issue by DuncWatts** [mono/SkiaSharp#577]
### Description

PCL project used as shared project for a Xamarin Forms application.  Currently using SkiaSharp 1.60.0

When I attempt to update to 1.60.2 I get the following error:

Could not install package 'SkiaSharp 1.60.2'. You are trying to install this package into a project that targets '.NETPortable,Version=v4.5,Profile=Profile111', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

PCL project is targeting .NETPortable,Version=v4.5,Profile=Profile111

You can add netstandard references to PCL projects, so fix should be a case of adding the netstandard libraries into the PCL folder within the NuGet?

This also seems to impact SkiaSharp.Views and SkiaSharp.Views.Forms, which I also use.

**Comment by mattleibow** [comment]
Unfortunately, we won't be adding PCL support back. See https://github.com/mono/SkiaSharp/issues/541
