### ISSUE TITLE
Build error with VS 2015

### ISSUE THREAD

**Issue by tdenniston** [mono/SkiaSharp#58]
I'm seeing a build error with Visual Studio 2015 Update 2 (community edition) on 64-bit Windows 7.

```
"C:\...\SkiaSharp\native-builds\libskia_windows\libskia_windows_x64.sln" (Build target) (1) ->
"C:\...\SkiaSharp\skia\out\gyp\core.vcxproj" (default target) (6) ->
(ClCompile target) ->
  ..\..\src\core\SkVarAlloc.cpp(48): warning C4334: '<<': result of 32-bit shift implicitly converted to 64 bits
(was 64-bit shift intended?) [C:\...\SkiaSharp\skia\out\gyp\core.vcxproj]
```

And the build doesn't complete:

```
 ..\..\src\core\SkVarAlloc.cpp(48): error C2220: warning treated as error
```

Some searching around turned up this skia upstream bug: https://bugs.chromium.org/p/chromium/issues/detail?id=593448. I don't think it's been fixed upstream yet, but they have identified a workaround, which is to suppress warning C4334. 

By applying the following patch in skia, this issue is resolved:

```
diff --git a/gyp/common_conditions.gypi b/gyp/common_conditions.gypi
index cf43271..3cc5dfb 100644
--- a/gyp/common_conditions.gypi
+++ b/gyp/common_conditions.gypi
@@ -54,6 +54,7 @@
             4275,  # An exported class was derived from a class that was not ex
             4345,  # This is an FYI about a behavior change from long ago. Chro
             4355,  # 'this' used in base member initializer list. Off by defaul
+            4334,
         ],
         'msvs_cygwin_shell': 0,
         'msvs_settings': {
```

I don't know that this should be an open issue on SkiaSharp, but I figured it was worth documenting so others don't have to duplicate the effort.

**Comment by bholmes** [comment]
@mattleibow One for you to consider.  Have you hit this?

**Comment by mattleibow** [comment]
I just hit it after updating to Update 2...

**Comment by mattleibow** [comment]
I think I will leave this for Google to fix as it is in a few places. However, to work around it, I build in Release mode.

**Comment by newky2k** [comment]
closing
