### ISSUE TITLE
SKCanvas may be native memory leak in Xamarin.Forms

### ISSUE THREAD

**Issue by j4587698** [mono/SkiaSharp#580]
### Description

SKCanvas looks like not release SKRegion SKShader in next frame. More and more memory is occupied.

### Code

I upload a simple code in [https://github.com/j4587698/SkiaSharpTest.git](https://github.com/j4587698/SkiaSharpTest.git)
If you drag the screen. The memory will increase and not release in GC.

### Expected Behavior

All memory will released in next frame.

### Actual Behavior

More and more memory is occupied.

### Basic Information

- Version with issue:  1.60.2
- Last known good version:  
- IDE:  Visual Studio 
- Platform Target Frameworks: 
  - Android: Android 8.1
  - UWP:  16299
- Target Devices:
  -   android: simulator 6.0
  -   UWP: local

### Screenshots

UWP: ![UWP](https://github.com/j4587698/SkiaSharpTest/blob/master/P2.png?raw=true)
Android: ![Android](https://github.com/j4587698/SkiaSharpTest/blob/master/P1.png?raw=true)

**Comment by mattleibow** [comment]
Is this still happening? I tried your test case, but the GC kicks in after a few seconds and then memory goes down.

![image](https://user-images.githubusercontent.com/1096616/43155840-c78f977e-8f78-11e8-930c-4045857304a1.png)

Even at the highest memory usage, there is hardly any SkiaSharp objects around:

![image](https://user-images.githubusercontent.com/1096616/43155890-e8a84c9e-8f78-11e8-8848-9a505cf65b38.png)

There is just one region and two paths in the list of total skia objects.

**Comment by bnoffer** [comment]
I can confirm this problem on Android with SkiaSharp 1.60.0 and 1.60.2, Operating Systems tested on are Android 7.0 and Android 8.0.

During testing I was able to see the garbage collection clearing memory a few times or even one time only, this is totally random. But after a while the memory runns full.

**Comment by mattleibow** [comment]
Closing this as it was fixed at some point in 1.68.x
