### ISSUE TITLE
DrawCircle/DrawOval pixellated

### ISSUE THREAD

**Issue by pfaucon** [mono/SkiaSharp#592]
### Description

We are in the process of removing NControl/NGraphics and replacing it with SkiaSharp, and we find that the circular shapes in Skia are much more pixellated

### Code

Skia(bad):

        void OnPaintSurface(object sender, SKPaintSurfaceEventArgs e)
        {
            var w = e.Info.Width;
            var h = e.Info.Height;
            var midX = e.Info.Rect.MidX;
            var midY = e.Info.Rect.MidY;
            var canvas = e.Surface.Canvas;
            canvas.Clear();

            SKPaint paint = new SKPaint
            {
                Style = SKPaintStyle.Fill,
                Color = Color.MultiplyAlpha(.4).ToSKColor()
            };

            float radius = Math.Min(w, h) / 2;
            var startX = radius + midX;
            var startY = midY;

            // base circle
            var rect = new SKRect(midX - radius, midY - radius, midX + radius, midY + radius);
            canvas.DrawCircle(midX, midY, radius, paint);

            // filled segment
            paint.Color = Color.ToSKColor();
            var p = new SKPath();
            p.MoveTo(new SKPoint(midX, midY));
            p.LineTo(new SKPoint(midX + radius, midY));
            p.AddArc(rect, 0, (float)Percentage * 360);
            p.LineTo(new SKPoint(midX, midY));
            canvas.DrawPath(p, paint);
        }

NControl (good):

       public override void Draw(ICanvas canvas, Rect rect)
        {
            base.Draw(canvas, rect);

            var formsColor = Color;
            var color = formsColor.ToNColor();

            var procent = Math.Max(Math.Min(Percentage, 1.0), 0.0);
            var resolution = 100;

            var angle = Math.PI;
            var radius = Math.Min(rect.Width, rect.Height) / 2;
            var dv = 2 * Math.PI / resolution;
            var path = new List<PathOp>();

            var startX = radius + rect.Center.X;
            var startY = rect.Center.Y;

            canvas.FillEllipse(rect.Center.X - radius, rect.Center.Y - radius, radius * 2, radius * 2, color.WithAlpha(0.4));

            path.Add(new MoveTo(startX, startY));
            for (var i = 0; i < resolution * procent; i++)
            {
                var x = -radius * Math.Cos(angle) + rect.Center.X;
                var y = radius * Math.Sin(angle) + rect.Center.Y;
                angle -= dv;
                path.Add(new LineTo(x, y));
            }
            path.Add(new LineTo(rect.Center.X, rect.Center.Y));
            path.Add(new ClosePath());

            var brush = new SolidBrush(color);
            canvas.FillPath(path, brush);
        }

### Expected Behavior

Circles should be as smooth as possible, at least as smooth as the previous library

### Actual Behavior

they are not

### Basic Information

Observed on iOS, with SkiaSharp 1.60.0 (also upgrading to .net, but that must come next)

### Screenshots

In the screenshot below the first and third are rendered using skia, the second and fourth use NControl
![screen shot 2018-07-26 at 11 32 58 am](https://user-images.githubusercontent.com/3473919/43254634-20269996-90c8-11e8-945c-74bc04fc735d.png)

### Reproduction Link

Can be generated if it is expected to be useful

**Comment by pfaucon** [comment]
My guess is actually that it has nothing to do with SkiaSharp, but rather the underlying Skia library, so I've made another issue on the Skia library itself https://bugs.chromium.org/p/skia/issues/detail?id=8196

**Comment by neodynamic** [comment]
It seems you're missing setting [IsAntialias](https://developer.xamarin.com/api/property/SkiaSharp.SKPaint.IsAntialias/) on the SKPaint obj

**Comment by pfaucon** [comment]
Good call, thanks! I'm surprised this wasn't enabled by default.
