### ISSUE TITLE
Xamarin Forms Preview crashes when declaring SKPaint as field

### ISSUE THREAD

**Issue by robertmiles3** [mono/SkiaSharp#600]
### Description

For performance (doing some animations), I am reusing several `SKPaint` objects by just declaring them as fields. However, Xamarin Forms preview dies as soon as I do so.

### Code

I've declared a few `SKPaint` objects like...

```
private readonly SKPaint Paint_Fill = new SKPaint
{
    Style = SKPaintStyle.Fill,
    IsAntialias = true
};
```

### Expected Behavior

Preview works

### Actual Behavior

Preview crashes (see screenshot below)

### Basic Information

- Version with issue:  1.60.2
- Last known good version:  ?
- IDE:  Visual Studio for Mac
- Platform Target Frameworks: iOS
  - iOS:  11.4

### Screenshots

![image](https://user-images.githubusercontent.com/944302/43422689-84f808d4-9418-11e8-983a-a49d059b9144.png)

**Comment by mattleibow** [comment]
Looks like it can't find the native bits. Did you install the same packages into the iOS app itself?

**Comment by robertmiles3** [comment]
Yep, all NuGets in both netstandard project as well as iOS project.

**Comment by mattleibow** [comment]
Closing this as even though it probably still is an issue, the preview is not such a high priority with the coming of Hot Reload.
