### ISSUE TITLE
Unable to decode using SKBitmap.Decode when I create the stream or byte[] using RGBA32/Gray8 format image buffer

### ISSUE THREAD

**Issue by msbasanth** [mono/SkiaSharp#603]
### Description
I am trying to resize image buffers (RGBA 32bit/ Gary 8 bit) using SKBitmap.Resize method.
For creating SKBitmap I used SKBitmap.Decode which gives null when passed RGBA 32/8 bit byte[].

### Code

```csharp
    using (Stream stream = new MemoryStream(imageBuffer)) // imageBuffer is byte[] in RGBA 32bit or Gray 8bit
    {
        using (var original = SKBitmap.Decode(stream)) // original is null for me.
        {
            using (var resized = original.Resize(new SKImageInfo(width, height), SKBitmapResizeMethod.Lanczos3))
            {
                bufferOutput = resized.Bytes;
            }
        }
    }
```

### Expected Behavior

SKBitmap.Decode should give me SKBitmap object which I can use for further manipulaions.

### Actual Behavior
SKBitmap.Decode gives null when I pass RGBA 32bit or 8bit image buffer.

### Basic Information
- Version with issue:  1.60
- Last known good version:  This is the first version I used.
- IDE:  Visual Studio 2017
- Platform Target Frameworks: .Net Core 2.0
  - Windows Classic: Windows 7
- Target Devices:
  -   Windows Desktop machines but should run in .Net Core environment.

Whether SKBitmap.Decode is the right approach for creating a SKBitmap from a RGBA byte[].
Please suggest how I can resize a byte[] with SkiaSharp.

Thanks
Basanth

**Comment by mattleibow** [comment]
This really depends on one thing: is the `byte[]` an ENCODED image or just the raw pixel bytes?

If the is encoded, then we need to have a closer look, but I think you are talking about raw memory? In this case, it is quite simple, you are trying to decode an already decoded image.

To do this correctly, you just need to create a bitmap from the memory. The simplest would be to just copy the bytes into an `SKData` object (move it into native memory) and use that:

```csharp
using (var data = SKData.CreateCopy(imageBuffer))
using (var original = new SKBitmap()) {
    // create a new bitmap using the memory
    original.InstallPixels(new SKImageInfo(oldWidth, oldHeight), data.Data);

    // now resize
    using (var resized = original.Resize(new SKImageInfo(width, height), SKBitmapResizeMethod.Lanczos3)) {
        bufferOutput = resized.Bytes;
    }
}
```

If you don't want to copy and don't mind working with marshalling:

```csharp
var gc = GCHandle.Alloc(imageBuffer, GCHandleType.Pinned);
try {
    using (var original = new SKBitmap()) {
        original.InstallPixels(new SKImageInfo(oldWidth, oldHeight), GCHandle.ToIntPtr(gc));
        using (var resized = original.Resize(new SKImageInfo(width, height), SKBitmapResizeMethod.Lanczos3)) {
            bufferOutput = resized.Bytes;
        }
    }
} finally {
    gc.Free();
}
```
If you don't want to copy and don't mind working with pointers:
```csharp
unsafe {
    fixed (byte *b = &imageBuffer[0]) {
        using (var original = new SKBitmap()) {
            original.InstallPixels(new SKImageInfo(oldWidth, oldHeight), (IntPtr) b);
            using (var resized = original.Resize(new SKImageInfo(width, height), SKBitmapResizeMethod.Lanczos3)) {
                bufferOutput = resized.Bytes;
            }
        }
    }
}
```
