### ISSUE TITLE
cannot install the SkiaSharp.Harfbuzz library in nuget

### ISSUE THREAD

**Issue by Luoyingliang** [mono/SkiaSharp#604]
my project was a WPF project used .net framework 4.5,when i install SkiaSharp.Harfbuzz, it doesn't work,but when i changed the framework version to .net framework 4.7.1,we did it.so i confuse that can you add something framework dependency information in the description?

**Comment by mattleibow** [comment]
Thanks for reporting this. We are building a netstandard1.3 nuget, but that requires at least 4.6:
https://docs.microsoft.com/en-us/dotnet/standard/net-standard

I will see what we can do to fix this in the next release.

**Comment by Luoyingliang** [comment]
very thanks
