### ISSUE TITLE
Support for SkColor HSV <-> RGB

### ISSUE THREAD

**Issue by tdenniston** [mono/SkiaSharp#61]
It'd be great to wrap these Skia functions from SkColor: `SkRGBToHSV` and `SkHSVToColor`.

I've already started work on this, but I figured there should be an issue open so that it can be discussed. One problem I'm having already (it would be great if someone can chime in) is how to add a new file `sk_color.{cpp,h}` to the Skia C API. I've modified the `core.gypi` file to include it, and it is compiling, but doesn't seem to be linking it into `libskia_windows.dll`.

**Comment by tdenniston** [comment]
I figured out the linking issue. It also occurs to me that we could simply reimplement these functions in SkiaSharp instead of calling into the library. Any thoughts on this?

**Comment by bholmes** [comment]
Agree.  It feels like these methods should be implemented in C#.  

https://github.com/mono/SkiaSharp/blob/master/binding/Binding/Definitions.cs#L72

**Comment by bholmes** [comment]
How about

`static public SKColor FromHSV (...)`

Can not think of a nice way to get HSV off hand.  Could be `GetHSV (out h, out s, out v)`

**Comment by tdenniston** [comment]
Could do a subclass approach, `SKColorHSV : SKColor` with implicit conversion to RGB. That starts to depart from Skia, though, which does not have a separate class.

**Comment by migueldeicaza** [comment]
Add the `FromHSV` method and `GetHSV` approaches.

Some code from Mono that implements bits of this:

https://github.com/mono/mono/blob/master/mcs/class/System.Drawing/System.Drawing/Color.cs#L231

**Comment by mattleibow** [comment]
Added support for to/from both HSV and HSL in 555a6263951e78c692be8b441625a4117f060ef1
