### ISSUE TITLE
One point doesn't been drawn when SKPath draw to negative horizontal

### ISSUE THREAD

**Issue by zhouandke** [mono/SkiaSharp#611]
### Description
When SKPath has a line command of drawing toward negative horizontal, one point doesn't been drawn

### Code

            var bitmap = new SKBitmap(800, 800);
            var canvas = new SKCanvas(bitmap);
            canvas.Clear(SKColors.White);
            var paint = new SKPaint
            {
                Color = SKColors.Red,
                Style = SKPaintStyle.Stroke
            };
            var path = SKPath.ParseSvgPathData("M 1 0 L 100 0, 100 100, 0 100");
            canvas.DrawPath(path, paint);

### Expected Behavior

   Expect point(100, 100) been drawn

### Actual Behavior

  point(100, 100) doesn't been drawn

### Basic Information

- Version with issue:  none
- Last known good version:  1.60.0.0
- IDE:  VS 2017
- Platform Target Frameworks:  .net framework 4.61
  - Windows Classic:  PC windows 10
- Target Devices: PC
   

### Screenshots

![20180808181506](https://user-images.githubusercontent.com/17719459/43831600-3d175c38-9b37-11e8-85ec-6652a442ba18.png)

### Reproduction Link

> VS bug [#742853](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/742853)

**Comment by zhouandke** [comment]
As I know, in skia, DrawLine method will draw first point, and will not draw last point, for example: when position is (0,0), drawline(10,0), point(0,0) will been drawn, and point(10,0) will not been drawn.

In my code, after execute **(M 1 0 L 100 0, 100 100)**, position change to (100,100), then draw negative horizontal **(0 100)**, I think point(100,100) should be drawn, but it doesn't work

**Comment by mattleibow** [comment]
Thanks for reporting this, I have filed a skia bug: https://bugs.chromium.org/p/skia/issues/detail?id=8605

A workaround is to use a non-zero width, ie 1+

**Comment by mattleibow** [comment]
Closing this not because it is resolved, but this is part by-design and part reality:

> Hairlines do not support joins, which would be necessary to fill in the missing corners.

Basically, with a hairline, the corners may need calculations, and for perf reasons they are not done.

I would have liked for it to just draw that pixel, but setting a StrokeWidth of 1 works. So, all we can do is just not draw hairline. And, if any scaling is done, you do need to set a width of > 0. SO, always set a line so you know what width it is going to be.
