### ISSUE TITLE
Can I combine OpenGL 3D drawing with SkiaSharp?

### ISSUE THREAD

**Issue by ReactorScram** [mono/SkiaSharp#614]
### Description

I'm using SkiaSharp with OpenTK on a Window desktop, but if I try to draw into the OpenGL context directly, both the OpenGL and SkiaSharp drawing is corrupted. I am guessing that they are trampling each other's GL states.

### Code

Can't share any code right now, there isn't anything in the documentation showing whether this is even allowed.

### Expected Behavior

Expected that I can draw something in 3D, call GrContext.ResetContext or similar function, then draw in 2D with SkiaSharp. (Or vice versa, 2D than 3D. Either is fine.)

### Actual Behavior

When I add our existing 3D code to the prototype SkiaSharp project, the 3D scene is not drawn, and the SkiaSharp 2D drawing is 'corrupted', i.e., text is not drawn, some objects are missing, a square appears where a square shouldn't be.

I can't call GrContext.ResetContext, because SKGlControl.grContext is private.

### Basic Information

- Version with issue:  v1.60.2 of SkiaSharp and SkiaSharp.Views, from NuGet.
- Last known good version:  This is the first time I have tried SkiaSharp.
- IDE:  Visual Studio
- Platform Target Frameworks: .NET Framework 4.5.2
  - Android: N/A
  - iOS:  N/A
  - Linux:  Not yet
  - macOS:  N/A
  - Tizen:  N/A
  - tvOS:  N/A
  - UWP:  N/A
  - watchOS:  N/A
  - Windows Classic:  Windows 10
- Target Devices:
  -   Acer laptop

### Screenshots

![image](https://user-images.githubusercontent.com/13400041/43979809-8b81da3a-9cb1-11e8-80f2-3a7c586a8db3.png)

This is the title bar for our app. If I just have OpenGL clear the viewport to purple, then have Skia render, it's okay. (Top) If I have OpenGL actually draw things, then the Home button and title text disappears and I get that grey box. (Bottom)

I could try to manually guess what OpenGL state needs to be corrected, but that sounds fragile.

### Reproduction Link

I can make up a reproduction case if the issue isn't clear, but this is more of a question of "Can I even do this?" and not "Is this broken?"

**Comment by Ollhax** [comment]
I'm rendering OpenGL and using SkiaSharp for creating UI, and the best way I've found to deal with this is to reset the OpenGL state manually after Skia is done. There are occasional issues when I hit some new setting I forgot to reset, but using Renderdoc or just guesswork to debug those problems is not overly difficult.

Note that this isn't really a SkiaSharp error, it's just how Skia works. See here: https://groups.google.com/forum/#!searchin/skia-discuss/gpu$20state%7Csort:relevance/skia-discuss/pj8lF9aHJ3Y/X7oHGhpkE8gJ - the author also posted a list of states he found were changed by Skia, which I found very useful when getting this to work myself. You probably also want to reset the texture unit, e.g. `GL.ActiveTexture(TextureUnit.Texture0);`

You do need to be able to call GrContext.ResetContext before rendering Skia surfaces, though. If you cannot access the GrContext, I recommend filing a separate report for that, and perhaps for now just use some reflection magic to access it.

**Comment by ReactorScram** [comment]
Thanks, Ollhax, it was the "DisableVertexAttribArray" from your Google Groups link that I was missing.

The 3D code I have is legacy - It uses a mix of GL 1 and 2 rendering, so OpenGL must have been trying to send the generic vertex attributes when my code was only sending the fixed vertex and texcoord attributes.

I couldn't get Renderdoc to work for some reason. The last time I had this issue, I was on Linux so I just used apitrace there. I know this is a common issue anywhere 2 different codebases have to share an OpenGL state, imgui has a similar reset () function and a list of GL state that the user must reset themselves.

I'll close it since we all agree it's not technically a bug. Hopefully the next person with this problem finds this thread useful.

**Comment by KnIfER** [comment]
how to combine OpenGL 3D with Skia in C++?

**Comment by KnIfER** [comment]
some problem...

https://user-images.githubusercontent.com/11593903/132338844-ab9b0a37-8ec1-4b46-ace6-f68ba53239ac.mp4


https://groups.google.com/g/skia-discuss/c/3bl1U3D9a_Q
