### ISSUE TITLE
[Android] SKBitmap.Decode crash

### ISSUE THREAD

**Issue by deakjahn** [mono/SkiaSharp#618]
### Description

The Decode() line simply crashes. And only on Android. The app terminates and there will be nothing in Visual Studio debug. No try-catch catches it, either. But we have a LogCat, see below.

### Code

    var source = (FileImageSource)ImageSource.FromFile((Device.RuntimePlatform == Device.UWP) ? "Resources/trans_square.png" : "trans_square.png");
    var bitmap = SKBitmap.Decode(source.File);

### Basic Information

- Version with issue:  1.60.3

### Error

at <unknown> <0xffffffff>  at (wrapper managed-to-native) SkiaSharp.SkiaApi.sk_codec_new_from_stream (intptr) <0x00037>  at SkiaSharp.SKCodec.Create (SkiaSharp.SKStream) [0x00014] in <0665b4d05b9e46c8a33bb731d6f5db83>:0  at SkiaSharp.SKBitmap.Decode (SkiaSharp.SKStream) [0x0000f] in <0665b4d05b9e46c8a33bb731d6f5db83>:0  at SkiaSharp.SKBitmap.Decode (string) [0x00016] in <0665b4d05b9e46c8a33bb731d6f5db83>:0

**Comment by LukePulverenti** [comment]
Is this on all images or is it isolated to specific images?

**Comment by deakjahn** [comment]
It was a transparent one originally but I created a simpler one and the problem appears with both:

![trans_square](https://user-images.githubusercontent.com/2234271/45585073-c14b7b00-b8de-11e8-8373-186467b3f78a.png)
![trans_square2](https://user-images.githubusercontent.com/2234271/45585076-c4df0200-b8de-11e8-82f8-cd8548951312.png)

**Comment by mattleibow** [comment]
This is because you can't open images in the android resources in this manner. Xamarin.Forms has some custom code on Android to translate a resource into an ImageSource.

To decode an Android resource, you have to either:

```csharp
using (var stream = Application.Context.Resources.OpenRawResource(Resource.Drawable.image)) {
    return SKBitmap.Decode(stream);
}
```

or 

```csharp
using (var fd = Application.Context.Resources.OpenRawResourceFd(Resource.Drawable.image))
using (var stream = fd.CreateInputStream()) {
	return SKData.Create(stream, fd.Length);
}
```

I am looking into creating a Xamarin.Forms / cross-platform API that will allow you to access the image from any platform resources. I am thinking something like:

```csharp
var bmp = await ResourceExtensions.DecodeBitmapAsync("icon.png");
var img = ResourceExtensions.DecodeImageAsync("icon.png");
```

Not too set on the names and types yet. Any thoughts? Comments? Suggestions?

**Comment by deakjahn** [comment]
I use the same resources in other places in the app, so this problem couldn't be XF-wide.

**Comment by LeoJHarris** [comment]
> I am looking into creating a Xamarin.Forms / cross-platform API that will allow you to access the image from any platform resources. I am thinking something like:
> 
> ```cs
> var bmp = await ResourceExtensions.DecodeBitmapAsync("icon.png");
> var img = ResourceExtensions.DecodeImageAsync("icon.png");
> ```
> 
> Not too set on the names and types yet. Any thoughts? Comments? Suggestions?

This would be very helpful and exactly what I am trying to do, is there a way provided to do this now?
