### ISSUE TITLE
Troubles rendering a live video feed

### ISSUE THREAD

**Issue by define-private-public** [mono/SkiaSharp#619]
I'm using SkiaSharp on a Linux/Gtk platform, .NET core 2.1 (and this Gtk binding: https://github.com/gtksharp/gtksharp).

At the moment, I'm trying to render a live video feed inside of an `SkWidget`.  At first (to test things out), I was getting my video source when `SkWidget.PaintSurface` was invoked.  Therefore it was running in the Gtk GUI thread (which is a bad idea), and it worked.  It was able to render video in realtime and retrieve it from the source.

The only problem with this was that the video source was from a USB, therefore it was quite slow, and would make the Gtk UI much less responsive (since capture was happing in the GUI thread).

I tried moving the capture over to a `System.Timers.Timer` callback, and added in all of the necessary locks/syncing.  This would work for about 10-15 seconds (GUI was response, `SkWiget` was showing a live feed), the GUI would then freeze up.  I tried using various things, such as Double-Buffered `SkBitmap`s, standard locks, Spin Locks, Reader-Writer locks, etc.

I'm wondering if there is a proper/recommended way of rendering video w/ Skia.  Is there?

**Comment by mattleibow** [comment]
Rendering video should be possible, although this question may be better suited to the forums (https://forums.xamarin.com) or SO.

It all really depends on how the video comes in and how you are storing it in memory. I am not sure what you have, but you could potentially have 2 bitmaps. every time you get a frame, draw it to one bitmap. and render the second. then, when the bitmap is finished reading, swap them out. - you could also use a background thread for the stream/copy

**Comment by define-private-public** [comment]
Hi,

This might have been an issue with how I was getting my video feed (back when I posted the question).  The method is different now and it's working MUCH better now.  I think it's fine to close this for now.
