### ISSUE TITLE
[UWP+Android] wildly alternating touch co-ordinates

### ISSUE THREAD

**Issue by deakjahn** [mono/SkiaSharp#626]
### Description

During a single move operation, I start to get alternating touch co-ordinates like this:

    pt={X=156.8584, Y=207.1211}
    pt={X=170.8299, Y=225.1194}
    pt={X=157.8608, Y=208.1281}
    pt={X=170.8504, Y=226.1232}
    pt={X=157.8608, Y=209.132}
    pt={X=171.8323, Y=227.1271}
    pt={X=157.8435, Y=210.1358}
    pt={X=171.8323, Y=228.1309}
    pt={X=156.8616, Y=210.1185}
    pt={X=170.8299, Y=229.1521}
    pt={X=155.8592, Y=210.139}
    pt={X=170.8472, Y=230.1355}
    pt={X=154.8396, Y=210.1216}
    pt={X=170.8267, Y=231.1566}

This is unfiltered, as it comes in via `SKTouchEventArgs`. It visibly alternates between two, parallel moving values.

The strange thing is that nearly two years ago, in a completely unrelated theme (but, obviously, calling the same underlying platform services as you do), I already saw some very similar behavior: https://forums.xamarin.com/discussion/74168/full-screen-image-viewer-with-pinch-to-zoom-pan-to-move-tap-to-show-captions-for-xamarin-forms It's mentioned in the accepted answer, it was observed in scaling back then but the mechanism was the same.

I tried `IgnorePixelScaling` but it isn't any different. The actual values differ, the jumping around is still there. This was logical, after all.

### Basic Information

- Version with issue:  1.60.3
- Platform Target Frameworks:
  - Android: ???
  - UWP: 16299

**Comment by deakjahn** [comment]
I could receive even worse than that:

    pt={X=40.38327, Y=347.9653}
    pt={X=3162.536, Y=344.9796}
    pt={X=31.04914, Y=339.9905}
    pt={X=3112.068, Y=338.9701}
    pt={X=30.84977, Y=336.9669}
    pt={X=3102.202, Y=335.9843}
    pt={X=30.6504, Y=335.9843}
    pt={X=3091.956, Y=334.9638}
    pt={X=306.7481, Y=334.9638}
    pt={X=306.9811, Y=333.9811}
    pt={X=304.5794, Y=333.9811}

Look at the 3,000+ values. :-)

**Comment by mattleibow** [comment]
I tried to reproduce this, but was not able to. Is it possible to create a simple repro case?

**Comment by deakjahn** [comment]
Dunno. I had an image crop rectangle control that showed this. In the meantime, I replaced it with a more elegant version base mostly on Petzold's Skia article on MSDN (although expanded to cover more functionality) and there is no problem with it now. I could send you the control but, frankly, I don't know how interwoven it is with the rest of my app, whether it's easy to run it separately or not.

**Comment by mattleibow** [comment]
DId you ever get more info on this issue? I was not able to repro and you did say it may be mixed in with the app code.

**Comment by deakjahn** [comment]
Probably not. Might have been something deeper in XF. As I mentioned, my current code doesn't show any such problems but even that older one linked didn't do any fancy stuff, just logged directly what came from the system. So, I suspect the fault was with the system, not my code that was and still is very straightforward. Let's aloow this sink to the bottom.

**Comment by mattleibow** [comment]
OK. I'll close this and if you (or anyone in the community) notices this, either reopen or create a new issue.
