### ISSUE TITLE
Invalid AlphaType obtained from DecodeBounds method

### ISSUE THREAD

**Issue by konrad147** [mono/SkiaSharp#629]
### Description

Hi, I'm trying to use SkiaSharp to merge a few images. To do that I was trying to create a surface using `SKImageInfo` obtained from the first image but the resulting image was brighter than I expected.
It turned out that `AlphaType` for the same image that comes from `DecodeBouns` is different than `AlphaType` that comes from `Decode` method. When I used an `AlphaType` that comes from the `Decode` method then everything started to work.

### Code

```C#
var firstImageInfo = SKBitmap.DecodeBounds(firstImageDataSource.ImageData); // ImageData is type of SKData
var firstImage = SKBitmap.Decode(firstImageDataSource.ImageData);
```

### Expected Behavior

`firstImageInfo.AlphaType == firstImage.Info.AlphaType`

### Actual Behavior

`firstImageInfo.AlphaType` is different than `firstImage.Info.AlphaType`

### Basic Information

- Version with issue:  1.60.3
- Last known good version:  
- IDE:  Rider
- Platform Target Frameworks: .NET Core 2.0
  - Windows Classic:  Windows 10
- Target Devices:
  - PC

**Comment by mattleibow** [comment]
@konrad147 Thanks for reporting this issue. I had a look but wasn't able to reproduce it.
I know this is an old issue, but do you know if this is still happening or do you have the image that caused this issue?

**Comment by Redth** [comment]
We are closing this issue since no response was received.  Please open a new issue referring to this one if you have more information.
