### ISSUE TITLE
SKTypeface.CharsToGlyphs throws IndexOutOfRangeException when no glyphs are returned

### ISSUE THREAD

**Issue by jpatte** [mono/SkiaSharp#630]
### Description

`SKTypeface.CharsToGlyphs()` calls `sk_typeface_chars_to_glyphs()` twice: the first time to get the number of matching glyphs (n) and the second time to retrieve these glyphs into an array of length n.

When n == 0, an IndexOutOfRange exception is raised because the code tries to get a pointer to the first element of the (empty) array.

### Code to reproduce

```csharp
var typeface = SKTypeface.FromFamilyName("Calibri");
ushort[] glyphs;

// try to get the glyph of a character not supported by this typeface
var n = typeface.CharsToGlyphs("这", out glyphs);
```

### Expected Behavior

```csharp
n == 0;
glyphs == ushort[0];
```

### Actual Behavior

An IndexOutOfRange exception is raised.

### Suggested fix

After the first call to `sk_typeface_chars_to_glyphs()`, do not call it again if n == 0.

### Basic Information

- Version with issue:  1.60.2

**Comment by mattleibow** [comment]
This is now fixed in the upcoming preview release.
