### ISSUE TITLE
[macOS] Unsupported Architectures. Your executable contained the following disallowed architectures: '[i386 Payload/MacCoolApp.app/Contents/MonoBundle/libSkiaSharp.dylib)]'

### ISSUE THREAD

**Issue by Adamster** [mono/SkiaSharp#634]
### Steps to Reproduce
1. Open https://github.com/olegoid/SubmissionSamples/tree/master/MacCoolApp
2. Install SkiaSharp as nuget package
3. Build and archive
4. Upload macapp.pkg to iTunesConnect

### Expected Behavior
Upload should be successful

### Actual Behavior

Failed with an error "ERROR: ERROR ITMS-90240: "Unsupported Architectures. Your executable contained the following disallowed architectures: '[i386 (in com.xamarin360.macpublishworkflow.pkg/Payload/MacCoolApp.app/Contents/MonoBundle/llibSkiaSharp.dylib)]'. New apps submitted to the Mac App Store must support 64-bit starting January 2018, and Mac app updates and existing apps must support 64-bit starting June 2018."

### Basic Information
- Version with issue:  1.60 - 1.60.3
- Last known good version:  
- IDE: Visual Studio for Mac
- Platform Target Frameworks: .NET Core 2.0
  - macOS:  10.13
- Target Devices:
  -   Mac Mini, MacBook

**Comment by mattleibow** [comment]
Nice :( It appears that if the dylib even contains the 32-bit architecture, then it is rejected. I will remove it. Are there any 32-bit macs left in the world?

**Comment by mattleibow** [comment]
I did some testing and I think the linker is _supposed_ to remove the 32-bit arch when building just the 64-bit app, but appears not. I will see if I can get a workaround.

**Comment by mattleibow** [comment]
Until the next release, you can remove the x86 arcitecture from the .dylib by adding this to your .csproj:

```xml
<Target Name="StripX86" AfterTargets="Build">
    <ItemGroup>
        <_SkiaSharpNativeDylib Include="@(_NativeLibrary)" Condition="'%(Filename)%(Extension)' == 'libSkiaSharp.dylib'" />
    </ItemGroup>
    <Exec Command="xcrun -sdk macosx lipo -remove i386 -output &quot;@(_SkiaSharpNativeDylib)&quot; &quot;@(_SkiaSharpNativeDylib)&quot;" />
</Target>
```

This basically intercepts the build and removes the i386 platform from the native file - this will also drop ~5MB from the final package (added bonus).

**Comment by Adamster** [comment]
Thank you for solution, waiting for next release :)

**Comment by mattleibow** [comment]
Let me know if it works for you and then I can close this issue.

**Comment by Adamster** [comment]
workaround is working, but just first build , next build is generating an error
![image](https://user-images.githubusercontent.com/2826917/45472802-eeacf300-b73d-11e8-9566-8e0574be55ea.png)
if I do a clean build it is working again

**Comment by mattleibow** [comment]
Hmm. let me have a look, I may be running after the wrong task...

**Comment by mattleibow** [comment]
OK, found out what was happening and made another improvement as well:

```xml

<Target Name="StripX86" AfterTargets="Build">
    <ItemGroup>
        <_SkiaSharpNativeDylib Include="@(_NativeLibrary)" Condition=" '%(Filename)%(Extension)' == 'libSkiaSharp.dylib' " />
    </ItemGroup>
    <Exec Command="xcrun -sdk macosx lipo -extract x86_64 -output &quot;@(_SkiaSharpNativeDylib)&quot; &quot;@(_SkiaSharpNativeDylib)&quot;"
          Condition=" '@(_SkiaSharpNativeDylib)' != '' " />
</Target>
```

**Comment by Adamster** [comment]
Thanks, it works now
