### ISSUE TITLE
Skia Version 70

### ISSUE THREAD

**Issue by john2014** [mono/SkiaSharp#636]
Hey, when will SkiaSharp upgrade to Skia version 70?

Currently SkiaSharp is using skia version 60 which was released around July 2017 (more than a year ago). There has been lots of improvements made in the last ten versions.

Skia version 71 will be released in few weeks: https://skia.org/schedule

**Comment by mattleibow** [comment]
We are currently working on getting a new 68 release out very soon. This is currently in the [`development` branch](https://github.com/mono/SkiaSharp/tree/development).

Even though Google releases a "stable" release, we have found that it is not usually not up the the "stable" standard that we would like. It will often recieve changes multiple times a week. As a result, we have decided to follow the slightly slower release of the Chrome release.

Skia is released at an "alpha" level and used by the preview builds of Chrome. We found that following behind by 3 releases results in a much more stable product. We are working with Google, so any critical bugfixes have been merged back far enough.

As of this comment, m70 has been released, that means we want to release m68 as the latest.

**Comment by john2014** [comment]
Thank you for the detailed explanation. It was very helpful. One quick thing I noticed is that the development tree says that it is at version 67 (instead of 68). This is bottom of the page in this link:

https://github.com/mono/SkiaSharp/tree/development
