### ISSUE TITLE
Method DrawText does'nt support not english letters on IOS 12

### ISSUE THREAD

**Issue by Staskkk** [mono/SkiaSharp#639]
### Description

Method DrawText does'nt support not english letters on IOS 12

### Code

canvas.DrawText("SkiaSharp Русский", coord, paint);

### Expected Behavior

Draw text with russian letters

### Actual Behavior

Draw text with english letters and cubes instead of russian ones.

### Basic Information

- Version with issue:  v1.60.3
- IDE:  Visual Studio
- Platform Target Frameworks: Xamarin, Xamarin.Forms, .Net Framework 4.6
  - iOS:  12
- Target Devices:
  -   iPhone 6s

### Screenshots

![image](https://user-images.githubusercontent.com/7769413/45805007-532ffb00-bcc6-11e8-957e-87b490e3c56f.png)

**Comment by ojb500** [comment]
Hello! Are you setting the Typeface property in your SKPaint?

You might need to call SKFontManager.MatchCharacter with a Cyrillic character, and use the returned SKTypeface.

**Comment by Staskkk** [comment]
Thank you very much!
I change typeface and everything is worknig fine now!
