### ISSUE TITLE
SKBitmap.Decode not working with PNG

### ISSUE THREAD

**Issue by anetapetryla** [mono/SkiaSharp#640]
### Description
When I want to decode my image "photo.png", the Decode method return null (with JPEG works fine). I think, It's a version bug.

### Code
            using (var bitmap = SKBitmap.Decode("photo.png"))
            {
                ....
            }

### Version

SkiaSharp: **1.60.3**
SkiaSharp.Views: **1.60.3**
SkiaSharp.Views.Forms: **1.60.3**

**Comment by GalaxyVelocity** [comment]
Tried to open simple PNG file from MS Paint, all is well.

SkiaSharp: **1.60.3**
.NET Framework **4.6.1**

Maybe a problem in the PNG file, wrong format.

Place the file that you are trying to open.

**Comment by mattleibow** [comment]
You could try and get the error code by doing something like this:

```csharp
// open the stream
var stream = new SKFileStream("photo.png");

// create the codec
var codec = SKCodec.Create(stream));

// we need a place to store the bytes
var bitmap = new SKBitmap(codec.Info);

// decode!
// result should be SKCodecResult.Success, but you may get more information
var result = codec.GetPixels(bitmap.Info, bitmap.GetPixels());
```

**Comment by aneti9862** [comment]
> Tried to open simple PNG file from MS Paint, all is well.
> 
> SkiaSharp: **1.60.3**
> .NET Framework **4.6.1**
> 
> Maybe a problem in the PNG file, wrong format.
> 
> Place the file that you are trying to open.

The format is correct, the photo is opened in every graphic program and I tried to show in application view. So, everything is good

**Comment by aneti9862** [comment]
> You could try and get the error code by doing something like this:
> 
> ```cs
> // open the stream
> var stream = new SKFileStream("photo.png");
> 
> // create the codec
> var codec = SKCodec.Create(stream));
> 
> // we need a place to store the bytes
> var bitmap = new SKBitmap(codec.Info);
> 
> // decode!
> // result should be SKCodecResult.Success, but you may get more information
> var result = codec.GetPixels(bitmap.Info, bitmap.GetPixels());
> ```

Not working, because SKCodec.Create(stream) return null

**Comment by GalaxyVelocity** [comment]
@aneti9862 try reading the byte array

```csharp
var bytes = System.IO.File.ReadAllBytes("photo.png");

using (var bitmap = SKBitmap.Decode(bytes))
{
  ....
}
```

Will receive an error?

**Comment by aneti9862** [comment]
@GalaxyVelocity,  decode method still returns the null, despite the bytes are filled.

![zrzut ekranu 2018-09-21 o 08 38 27](https://user-images.githubusercontent.com/32899557/45864282-cfcfe180-bd79-11e8-8473-1a73534a6c96.png)

**Comment by GalaxyVelocity** [comment]
@aneti9862 Try to convert the png using GDI+ as a test

```csharp
    public byte[] ImageToByteArray(System.Drawing.Image image)
    {
        using (var ms = new System.IO.MemoryStream())
        {
            image.Save(ms, System.Drawing.Imaging.ImageFormat.Png);
            return ms.ToArray();
        }
    }
```

```csharp
    bytes = ImageToByteArray(System.Drawing.Image.FromFile("photo.png"));

    using (var bitmap = SKBitmap.Decode(bytes))
    {
        ...
    }
```

Maybe this temporary solution will help.

**Comment by aneti9862** [comment]
I don't have access to System.Drawing.Image (Xamarin.Forms iOS)

![zrzut ekranu 2018-09-21 o 09 07 08](https://user-images.githubusercontent.com/32899557/45865429-cc3e5980-bd7d-11e8-9a8b-3f281c518d71.png)

**Comment by GalaxyVelocity** [comment]
Yes, sorry. GDI+ graphics library. System.Drawing.Image, is a Win32 implementation that ties into the Windows Desktop.

The test was to convert the original png file and transfer it SKBitmap.Decode.

**Comment by mattleibow** [comment]
@aneti9862 Is it possible to upload the image somewhere? Maybe not here as GitHub processes the image. OneDrive, Dropbox, Google Drive, etc. Then I can check to see exactly what is happening. If you don't want to go public, just send it over to my email maleib@microsoft.com.

**Comment by aneti9862** [comment]
@mattleibow, PNG and JPG photo are set in Google Drive folder (link below):

https://drive.google.com/drive/folders/17JSyRUXGVLIkuShWpDqRO0X_Q8jZbtrD?usp=sharing

**Comment by mattleibow** [comment]
@aneti9862 I think it _may_ have to do with the fact of iOS compressing the .png images with a proprietary format. See https://github.com/mono/SkiaSharp/issues/140

See this comment to fix: https://github.com/mono/SkiaSharp/issues/140#issuecomment-326024217

If this is not the case, could you attach a simple sample? Also, how are you getting the image? is it a resource, or downloaded, or on the device?

**Comment by sergiokoo** [comment]
Despite I have 'Optimize PNG images' turned off in project settings, I still unable to use my *.png on iOS with exactly the same errors as aneti9862 described above. For me, the solution was to replace
```C#
return SKBitmap.Decode(File.OpenRead(path));
```
with
```C#
return UIImage.FromFile(path).ToSKBitmap();
```

**Comment by najak3d** [comment]
> Despite I have 'Optimize PNG images' turned off in project settings, I still unable to use my *.png on iOS with exactly the same errors as aneti9862 described above. For me, the solution was to replace
> 
> ```cs
> return SKBitmap.Decode(File.OpenRead(path));
> ```
> 
> with
> 
> ```cs
> return UIImage.FromFile(path).ToSKBitmap();
> ```

SKBitmap.Decode() - all forms were failing...  many alterations/trials to get it working failed.  It works fine on Android/UWP, but just not iOS!

HOWEVER, THIS KLUDGE WORKED FOR ME!  (using UIImage.FromFile() first)

In order to make it work for our project, only our iOS Launcher included UIImage, since the rest of our project was .Net Standard 2.0.  Therefore, I inserted a plugin method to make this work from our core code, like this:

class PluginMethods
{
   static Func<string, SKBitmap> LoadImageFromFilepath;
}

And then from our Launcher, I hooked up this method to the method that makes it work in AppDelegate.cs:

class AppDelegate 
{
    public override void OnActivated(.....)
   {
          ....
          PluginMethods.LoadImageFromFilepath = _LoadImageFromFilepath;
   }

   static private SKBitmap _LoadImageFromFilepath(string filepath)
   { 
     	UIImage img = UIImage.FromFile(filepath);
	SkiaSharp.SKBitmap bm = img.ToSKBitmap();
	return bm;
   }
}

===
So now my .NET Standard application code is able to load PNG images from file on iOS using "PluginMethods.LoadImageFromFilepath(path)".

Thanks for this kludge!

**Comment by mattleibow** [comment]
@najak3d is it possible to attach a diagnostic build log or a binlog? I'll have a look and see what is happening to the build

**Comment by najak3d** [comment]
Please tell me how to obtain the log you are wanting?    I run from Visual Studio, and when the Decode method is called, nothing shows up in the Console log.  Maybe there is something in the Device Log, or elsewhere.

**Comment by mattleibow** [comment]
@najak3d Ah, sorry. You can either run the build from the command line with:
```
msbuild /r /bl <path-to-ptoject-file>
```

Or, install the extension: https://marketplace.visualstudio.com/items?itemName=VisualStudioProductTeam.ProjectSystemTools

Click the play/start button in the `View > Other Windows > Build Logging` window:

<img width="500" src="https://user-images.githubusercontent.com/1096616/87252281-00629d00-c472-11ea-891d-8bd3ae9d6c73.png" />

When the window appears, you can right-click and save the logs:

<img width="450" src="https://user-images.githubusercontent.com/1096616/87252311-39027680-c472-11ea-8b5b-19d5622d1cb4.png" />

**Comment by najak3d** [comment]
I installed those Project System Tools, and then opened the "Build Logging" window.  Then did a Clean/Rebuild in Visual Studio, but the Build Logging window remained empty black (filter set to "All").   So nothing shows here.

**Comment by mattleibow** [comment]
@najak3d did you click the little black arrow in the top left of the tool window? You need to start a listener.

**Comment by bennor** [comment]
In case anyone else runs into this, the problem for me was that I needed to keep the source stream open, so I was creating a copy:

```csharp
using var copy = new MemoryStream();
await source.CopyToAsync(copy);

using var bitmap = SKBitmap.Decode(copy); // sets bitmap to `null` 😢
```

The solution was to rewind the stream after `CopyTo`:

```csharp
using var copy = new MemoryStream();
await source.CopyTo(copy);
source.Position = 0;
copy.Position = 0;

using var bitmap = SKBitmap.Decode(copy); // 🎉
```
