### ISSUE TITLE
Fill Rectangle with all types of HatchStyle in SkiaSharp

### ISSUE THREAD

**Issue by MathuMohan** [mono/SkiaSharp#641]
I have found a way to fill the rectangle area with hatch pattern using "2D Path by referring [Xamarin forum Link](https://forums.xamarin.com/discussion/88011/is-there-a-way-to-hatch-fill-a-rectangle) But I can't achieve all types of [HatchStyle ](https://docs.microsoft.com/en-us/dotnet/api/system.drawing.drawing2d.hatchstyle?view=netframework-1.1)using SkiaSharp. Can anyone suggest me the logic to Fill the rectangle area with all types of HatchStyles in SkiaSharp?

> VS bug [#736297](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/736297)

**Comment by mattleibow** [comment]
Closing this as this is not something that we support.
