### ISSUE TITLE
SKTypeface.FromFamilyName returns null

### ISSUE THREAD

**Issue by nicolasr75** [mono/SkiaSharp#643]
My app uses the Avalonia library to show UIs on ARM devices. Avalonia internally uses SkiaSharp. I have a strange behavior on the Raspian system where SKTypeface.FromFamilyName returns null if one passes a font family name that does not exist.
The authors of Avalonia say it is expected to return the default font of the system. Unfortunately this unexpected null crashes the application during the application startup.

Any idea what is going wrong here?
Is this an issue with SkiaSharp, Skia or the specific operating system?

I use a self built libSkiaSharp 1.60.3 with .NET Core 2.1 on Raspian 9.4

**Comment by nicolasr75** [comment]
I should add the following:

the Avalonia guys asked me to run the following line on Raspian

    var typeface = SKTypeface.FromFamilyName(FontFamily.Default.Name);

FontFamily.Default.Name is hardcoded in Avalonia as Courier New.
On Raspian this call returns the Liberation Mono font. But the same
call with "Ubuntu" as the name returns null (The Ubuntu font does not
exist on Raspian).

**Comment by mattleibow** [comment]
Hmm. I believe the Rasbian build should be using the fontconfig font manager, so I had a look and noticed this:
https://github.com/google/skia/blob/chrome/m68/src/ports/SkFontMgr_fontconfig.cpp#L894

Basically, if there is a problem matching the style it will return `nullptr`. This is not good, but appears to be the case.

However, there is hope: it appears that if you pass `null` as the name, then it will find something:
https://github.com/google/skia/blob/chrome/m60/src/core/SkTypeface.cpp#L119

So, as a fix, you can do something like this:

```csharp
var typeface = SKTypeface.FromFamilyName(FontFamily.Default.Name) ?? SKTypeface.FromFamilyName(null);
```

In the coming release, I will expose the `SKTypeface.CreateDefault()` method that will _never_ return `null`.

**Comment by nicolasr75** [comment]
Thanks for the analysis!

**Comment by mattleibow** [comment]
I am closing this as I believe there was never a promise that these methods would not return null.
