### ISSUE TITLE
Support for more functionality in Typeface

### ISSUE THREAD

**Issue by agallero** [mono/SkiaSharp#65]
I need to get the real typeface used by the SKTypeface when you create it, if font substitution happens.

From what I see in the Skia C++ docs, I would need to expose the method:

`void SkTypeface::getFamilyName	(SkString * 	name)	const`

I think it could be added as a method GetFamilyName() in the SKTypeface C# type. It could also be a property FamilyName, but I am not sure about the performance implications if we don't cache the family name and call getFamilyName each time you call the property.

I would also need to expose a method GetTables() and GetTableTags() which would be wrappers around SKTypeface::getTableTags and SKTypeface::getTableData. 

As none of those methods are in the C wrappers, I would have to also modify the C headers.

Is it ok if I add those methods and make a pull request, or maybe someone else is working on this already?  If I add them myself, I assume I would have to add some tests too, but what about docs?  I don't see xmldocs used in the binding SKTypeface.cs, so I think you are using a different tool for the docs?

**Comment by mattleibow** [comment]
Hi @agallero, thanks for you interest. Go ahead and make the changes and we can review and merge them.
I don't think anyone is working on them right now, so it's all yours. You can add the C methods and then add the C# wrappers. You can make use of the C# tests (https://github.com/mono/SkiaSharp/tree/master/tests) for any tests, without having to write C tests. To do the docs, there are two ways:

 - `./bootstrapper.sh -t docs`
 - `make update-docs`

You can the go ahead and write the docs by hand o make use of the docs tool: http://github.com/xamarin/DocWriter

**Comment by agallero** [comment]
Thanks!  I had already began looking at it, and I have some questions about how skiasharp is handling the strings, but probably it is better that I ask about that in a different thread.

**Comment by mattleibow** [comment]
@agallero Here are some examples of working with text:
https://github.com/mono/SkiaSharp/blob/master/binding/Binding/SkiaApi.cs#L125-L136
https://github.com/mono/SkiaSharp/blob/master/binding/Binding/SKCanvas.cs#L243-L252
https://github.com/mono/SkiaSharp/blob/master/binding/Binding/Util.cs
