### ISSUE TITLE
Rotating text: letters are jumping

### ISSUE THREAD

**Issue by antongit** [mono/SkiaSharp#651]
### Description
I was trying to make an animation of text rotation.
Unfortunately the letters are swimming / jumping.

I've asked about it in skia-discuss forum, they said I was missing to set the SubpixelText.
https://groups.google.com/forum/#!topic/skia-discuss/XckcdV-wCh8

After doing so in SkiaSharp, the letters are still jumping.
Is it an issue or am I missing something or doing something wrong?

### Code

Skia fiddle (text is smooth, subpixeltext is on):
https://fiddle.skia.org/c/361c252ed2a32078737ae94c97511e45

### Expected Behavior
Smooth rotation of the letters
### Actual Behavior
Letters are swimming (jumping), see the gif.
### Basic Information

- Version with issue:  1.60.3
- Platform Target Frameworks: 
  - Windows Classic:  Windows 10

### Screenshots

![textrotation](https://user-images.githubusercontent.com/1189037/46871321-52a40380-ce31-11e8-9981-6c9b81b197f8.gif)

**Comment by mattleibow** [comment]
Thanks for reporting this. I had a look and there is good news. It appears that this problem is not as visible in the upcoming 1.68.0 release.

**Comment by antongit** [comment]
Great!
Thank you very much.
