### ISSUE TITLE
libSkiaSharp missing when building the WPF Samples project

### ISSUE THREAD

**Issue by v-vasilev-synergy** [mono/SkiaSharp#660]
### Description

Some people may want to try the samples here without having to build SkiaSharp itself to get a showcase of what can be done, but opening the WPF project 
SkiaSharp\samples\Gallery\WPF\SkiaSharpSample\SkiaSharpSample.csproj
And running it results in a runtime exception:
DllNotFoundException: Unable to load DLL 'libSkiaSharp': The specified module could not be found. (Exception from HRESULT: 0x8007007E)

VC++ Runtime is installed and other apps using SkiaSharp older version build and run correctly

The libSkiaSharp dll is not available in the project, so users cannot quickly run the WPF version without downloading Android SDK, etc. to be able to build the whole SkiaSharp project

### Expected Behavior

It will be much easier if WPF project could be built and run without having to build Skia locally (due to additional downloads required) 

### Actual Behavior

The project fails to build, but can be run afterwards, resulting in runtime exception

**Comment by mattleibow** [comment]
This is something that I know is a real pain, and I hope to find a solution somehow. Right now, the samples also form part of the testing to make sure that we didn't break an API.

What you can do is to just download the samples zip from the release:
https://github.com/mono/SkiaSharp/releases/tag/v1.60.3
https://github.com/mono/SkiaSharp/releases/download/v1.60.3/samples.zip

**Comment by v-vasilev-synergy** [comment]
Never thought that the samples are included in the release. Everything works there. Thanks for all of the effort!
