### ISSUE TITLE
Feature request: Support Skottie

### ISSUE THREAD

**Issue by michaldobrodenka** [mono/SkiaSharp#661]
Skia now support Lottie animations via Skottie module.

Would be nice if it is supported. Not a huge priority, just an idea.

https://skia.org/user/modules/skottie

> VS bug [#736299](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/736299)

**Comment by mattleibow** [comment]
This is something we have been keeping an eye on and most probably will make it into SkiaSharp sometime. Right now, it is still in a preview/experimental phase and does not exist in any stable release. As soon as it reaches a more "stable" form, then we can start adding this to the SkiaSharp release.

**Comment by PhilippeCreytens** [comment]
Hey is this still in experimental phase? Because I could really use this to enhance performance in my app

**Comment by emmauss** [comment]
Any update on this. Is i still planned

**Comment by vchelaru** [comment]
I feel obligated to do the once-a-year "is-it-supported-yet" so here goes...

Is it supported yet? I'm dying to get this in my app which uses SkiaSharp.

**Comment by sidneipolo** [comment]
Any updates or estimations for this feature?
