### ISSUE TITLE
Make SKGLDrawable public so users can try to create GPU-powered WPF controls

### ISSUE THREAD

**Issue by v-vasilev-synergy** [mono/SkiaSharp#665]
### Description

By mixing and matching the code for SKElement and SKGLControl, users can try to make a WPF control that uses GPU acceleration, but SKGLDrawable and GRBackendRenderTarget prevent compilation from being successful since SKGLDrawable is internal.
Replicating its code proves to be hard though, since it is a facade for more internal calls,

Hosting the WinForms control proved to be problematic on old machines with no dedicated GPU, but with an integrated one (2nd generation i5) where the samples work, but moving our drawing code to use SKGLControl crashes with AccessViolationException on the 3rd-4th draw on this particular machine (though it works OK when a dedicated GPU is present).
Also using the SKGLControl makes the task of falling back to CPU rendering on an exception much harder, since if we roll our own one once we get an exception during GPU rendering we can just stop using it, and reuse the old SKElement code for CPU only

If SKGLDrawable is public we have the opportunity of experimenting and implementing out own GPU-accelerated WPF controls 
### Code
```

      // create the contexts if not done already
      if (grContext == null) {
        var glInterface = GRGlInterface.CreateNativeGlInterface();
        grContext = GRContext.Create(GRBackend.OpenGL, glInterface);
      }

      // manage the drawing surface
      if (renderTarget == null || surface == null || renderTarget.Width != info.Width || renderTarget.Height != info.Height) {
        // create or update the dimensions
        renderTarget?.Dispose();
        renderTarget = SKGLDrawable.CreateRenderTarget(Width, Height);

        // create the surface
        surface?.Dispose();
       // TODO This fails due to being internal
        surface = SKSurface.Create(grContext, renderTarget, GRSurfaceOrigin.BottomLeft, SKColorType.Rgba8888);
      }

      OnPaintSurface(new SKPaintSurfaceEventArgs(surface, info));
    }
```

**Comment by mattleibow** [comment]
Closing this as `SKGLDrawable` no longer exists.
