### ISSUE TITLE
cannot open .ksp files Xamarin.forms

### ISSUE THREAD

**Issue by mdonogma** [mono/SkiaSharp#666]
When I try open .ksp files on Xamarin.forms I get message that indicates skiasharp.forms.views.skcanvasview cannot be converted to skcanvas.

Trying to create an iPad version of kimono designer and the kimono.core is using skcanvas however the skiasharp.forms.views are using skcanvasview

please help

**Comment by mattleibow** [comment]
The `SKCanvasView` is the UI element that is visible. The `SKCanvas` is the code type that has the various drawing methods.

What you might want to do is add the `SKCanvasView` to your UI, and then in the `PaintSurface` event, use `e.Surface.Canvas` to draw onto that view via `SKCanvas` methods.

**Comment by Redth** [comment]
We are closing this issue since no response was received.  Please open a new issue referring to this one if you have more information.
