### ISSUE TITLE
There is a way to stroke path with image or bitmap like it does SKPaint.PathEffect?

### ISSUE THREAD

**Issue by hongkilldong** [mono/SkiaSharp#667]
I have a bunch of SKPicture objects loaded from SVG files. 
I want to use some of these pictures to stroke some pathes.
I see the only way how to do that is convert pictures to bitmap and then use it as stroking pattern
But, surprise, i did not see support of such operation in skia api.
May i wrong?

**Comment by mattleibow** [comment]
If I think I understand, then you can make use of the blend modes and layers:

```csharp
// get the image that we want to use as the "stroke"
var image = SKImage.FromEncodedData(SKData.Create("baboon.png"));

// create a paint that describes how the picture should be drawn
// basically use the image as the color instead of what was in the SVG
var paint = new SkPaint {
  ImageFilter = SKImageFilter.CreateBlendMode(SKBlendMode.DstIn, SKImageFilter.CreateImage(image))
};

// save the layer, and let SkiaSharp know that the paint is going to override something
canvas.SaveLayer(paint);

// draw the SVG as normal (on to the new layer)
canvas.DrawPicture(svg.Picture, ref matrix);

// apply the layer to the main canvas, through the paint
canvas.Restore();
```

Let me know if this is what you were trying to do.

**Comment by mattleibow** [comment]
This is a very detailed guide to using blend modes: https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/graphics/skiasharp/effects/blend-modes/

**Comment by hongkilldong** [comment]
Thank you for help
I think it is not what i want to get.
Picture below could illustrate better my intentions

![image](https://user-images.githubusercontent.com/12894312/47913134-06863500-deac-11e8-91af-aea99208ff9e.png)


As you can see some pixel pattern is distributed along curve. I try to find a way to do the same with SkiaSharp.

**Comment by mattleibow** [comment]
I see what you mean now. You can always ask on the skia forums as this guy's know everything https://groups.google.com/forum/m/#!forum/skia-discuss

**Comment by hongkilldong** [comment]
Thanks a lot!

**Comment by mattleibow** [comment]
I am closing this as your question is better discussed on the forums (https://forums.xamarin.com/) or on SO.
