### ISSUE TITLE
Missing SKPath methods

### ISSUE THREAD

**Issue by adamped** [mono/SkiaSharp#669]
### Description

There are missing methods from the SKPath

SKPath.isRect
SKPath.isRRect
SKPath.isOval

as per 
https://github.com/google/skia/blob/master/site/user/api/SkPath_Reference.md

Apologies, I'm still rather new to Skia, its versions and what should be available. But these methods are being used by the Flutter Flow Skia Compositor, that I have manually transpiled to C#, and couldn't find any equivalent methods.

### Code

n/a

### Expected Behavior

Methods should be available on instance or static

### Actual Behavior

Not available.

### Basic Information

- Version with issue:  1.60.3
- Last known good version:  n/a
- IDE:  Visual Studio
- Platform Target Frameworks: all
- Target Devices: all

### Screenshots

n/a

### Reproduction Link

n/a

**Comment by mattleibow** [comment]
Implemented!
