### ISSUE TITLE
ASP,NET Core 2.1: throws exception System.DllNotFoundException: Unable to load DLL 'libSkiaSharp' or one of its dependencies: Access is denied.

### ISSUE THREAD

**Issue by eddyuk** [mono/SkiaSharp#672]
### Description

When loading image it throws an error:

{System.TypeInitializationException: The type initializer for 'SkiaSharp.SKAbstractManagedStream' threw an exception. ---> System.DllNotFoundException: Unable to load DLL 'libSkiaSharp' or one of its dependencies: Access is denied.

If I run it in console application, it works and I see that there is an libSkiaSharp.dll in the bin folder while
it is missing in bin folder of ASP.NET MVC project
### Code

string inputPath = @"C:\pexels-photo-248797.jpeg";
                            const int size = 150;
                            const int quality = 75;

                            using (var input = File.OpenRead(inputPath))
                            {
                                using (var inputStream = new SKManagedStream(input)) // This throws the error
                                {

**Comment by eddyuk** [comment]
Ok, I found the problem. Since I was using IIS, needed to grant permissions to library folder

**Comment by mattleibow** [comment]
Great to see that you resolved it! Let us know if you have any other issues!

**Comment by eddyuk** [comment]
> @eddyuk may you tell us how and where to grant such permissions? thanks

I followed [this article](https://docs.microsoft.com/en-us/iis/manage/configuring-security/application-pool-identities) to grand permissions to the web site folder. Note, that is you in development node and used nuget to retrieve the library, you need to do the same to packages folder.
