### ISSUE TITLE
FAILED: obj/src/opts/hsw.SkOpts_hsw.o

### ISSUE THREAD

**Issue by aben1188** [mono/SkiaSharp#673]
I build SkiaSharp on CentOS 7.5. When running:
```
> ./bin/gn gen 'out/linux/x64' --args='
>     is_official_build=true skia_enable_tools=false
>     target_os="linux" target_cpu="x64"
>     skia_use_icu=false skia_use_sfntly=false skia_use_piex=true
>     skia_use_system_expat=false skia_use_system_freetype2=false skia_use_system_libjpeg_turbo=false skia_use_system_libpng=false skia_use_system_libwebp=false skia_use_system_zlib=false
>     skia_enable_gpu=true
>     extra_cflags=[ "-DSKIA_C_DLL" ]
>     linux_soname_version="60.3.0"', 
```
I get this error:

FAILED: obj/src/opts/hsw.SkOpts_hsw.o
c++ -MMD -MF obj/src/opts/hsw.SkOpts_hsw.o.d -DNDEBUG -DSK_SAMPLES_FOR_X -DSK_GAMMA_APPLY_TO_A8 -DSK_ALLOW_STATIC_GLOBAL_INITIALIZERS=0 -DSK_ENABLE_DISCRETE_GPU -DSKIA_IMPLEMENTATION=1 -I../../../include/android -I../../../include/c -I../../../include/codec -I../../../include/config -I../../../include/core -I../../../include/effects -I../../../include/encode -I../../../include/gpu -I../../../include/atlastext -I../../../include/pathops -I../../../include/ports -I../../../include/svg -I../../../include/utils -I../../../include/utils/mac -I../../../include/private -I../../../src/c -I../../../src/codec -I../../../src/core -I../../../src/effects -I../../../src/fonts -I../../../src/image -I../../../src/images -I../../../src/lazy -I../../../src/opts -I../../../src/pathops -I../../../src/pdf -I../../../src/ports -I../../../src/sfnt -I../../../src/shaders -I../../../src/shaders/gradients -I../../../src/sksl -I../../../src/utils -I../../../src/utils/win -I../../../src/xml -I../../../third_party/gif -I../../../src/gpu -march=haswell -fstrict-aliasing -fPIC -fvisibility=hidden -O3 -fdata-sections -ffunction-sections -Wno-unused-parameter -DSKIA_C_DLL -std=c++11 -fvisibility-inlines-hidden -fno-exceptions -fno-rtti -c ../../../src/opts/SkOpts_hsw.cpp -o obj/src/opts/hsw.SkOpts_hsw.o
../../../src/opts/SkOpts_hsw.cpp:1:0: error: bad value (haswell) for -march= switch
 /*
 ^
[381/1045] compile ../../../src/sksl/ir/SkSLVariableReference.cpp
ninja: build stopped: subcommand failed.

How can I solve this problem? I appreciate it!

**Comment by mattleibow** [comment]
I think this may be because you are using an old version of GCC. I believe that GCC 5 or later is required.

What version are you using?

**Comment by aben1188** [comment]
gcc --version
gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-28)

Yes，you are right. Thank you!

**Comment by mattleibow** [comment]
I am going to close this as I think it is resolved? If not, just re-open.
