### ISSUE TITLE
SKBitmap.Decode( NONE_EXISTING_FILE_PATH ) should return null

### ISSUE THREAD

**Issue by MonkeyNinja** [mono/SkiaSharp#677]
### Description

Having trouble catching a useful exception, and will have to write some guard code around it.
MSDN docs suggest that SKBitmap should return null if an error occurs

### Code

SKBitmap.Decode( NONE_EXISTING_FILE_PATH );

### Expected Behavior

either throw file not found or return null

### Actual Behavior

Caused a native crash and so far I have been unable to catch any exception.
From some quick digging, SkiaSharp creates a stream from the path, this stream is already at the end...

### Basic Information

- Version with issue:  1.60.3
- Last known good version:  first time here...
- IDE:  Visual Studio 
- Platform Target Frameworks: 
  - Android: not tested
  - iOS:  not tested
  - Linux:  not tested
  - macOS:  not tested
  - Tizen:  not tested
  - tvOS:  not tested
  - UWP:  not tested
  - watchOS:  not tested
  - Windows Classic:  10 ( so far)
- Target Devices:
  -

**Comment by LukePulverenti** [comment]
Once this is resolved, it would be great if you could make sure that SKFileStream gets the same fix. Thanks.

**Comment by mattleibow** [comment]
Thanks for pointing out the path streams. I had a look and remembered that I had implemented a partial workaround for #390. After updating skia, I see that they fixed the bugs with paths and reverted those changes in #697 and https://github.com/mono/SkiaSharp/commit/51adc3c1b2af5be101cb00f6763df0d3627d471d
