### ISSUE TITLE
SKPath iteration

### ISSUE THREAD

**Issue by tdenniston** [mono/SkiaSharp#68]
It would be nice to wrap the `SKPath::Iter` class for iterating over paths.

**Comment by migueldeicaza** [comment]
Can you point us to a sample that you would like to replicate so we can study the approach to take?

**Comment by tdenniston** [comment]
@migueldeicaza I don't have a sample written, but the motivating use case (for me) is to traverse SKPaths in order to compute bounding boxes. I know there exist other Skia methods for computing rough bounding boxes, but I need tight boxes including path effects like stroking, and I haven't found methods that do that yet. Currently I'm accomplishing it by maintaining "shadow" paths in my C# code, e.g. just lists of the SKPoints, which allows me to traverse the points to compute the bounding boxes. It's fine with me if you'd like to close this issue, as perhaps it's outside of the scope of what SkiaSharp should worry about.

**Comment by mat72** [comment]
Would the skia PathMeasure class help with this?

**Comment by migueldeicaza** [comment]
This has been implemented.
