### ISSUE TITLE
Add SKCanvas Methods

### ISSUE THREAD

**Issue by adamped** [mono/SkiaSharp#680]
### Description

Missing 
- SkCanvas.drawArc (https://skia-doc.commondatastorage.googleapis.com/doxygen/doxygen/html/classSkCanvas.html#ab7d43d64e7e6d756e60a6d42f3dc472d)
- SkCanvas.drawDRRect (https://skia-doc.commondatastorage.googleapis.com/doxygen/doxygen/html/classSkCanvas.html#ad7149e359d4d0cfd2ad708e905f0d8c6)
-SkCanvas.drawAtlas (https://skia-doc.commondatastorage.googleapis.com/doxygen/doxygen/html/classSkCanvas.html#a3bd71bfa1b83de37c63df6f5713d275a)

### Code

n/a

### Expected Behavior

Methods to be available

### Actual Behavior

n/a

### Basic Information

- Version with issue:  1.60.3
- Last known good version:  n/a
- IDE:  Visual Studio
- Platform Target Frameworks: all
- Target Devices: all

### Screenshots

n/a

### Reproduction Link

n/a

> VS bug [#727959](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/727959)

**Comment by mattleibow** [comment]
I'm having a look now and I think I might be able to slip it in for v1.68.2.
