### ISSUE TITLE
SKImage from loaded SKSvg is corrupted most of the time.

### ISSUE THREAD

**Issue by XamDevv** [mono/SkiaSharp#683]
### Description

We load a svg stream from file and load it into a SKSvg. When we create a SKImage from the SKSvg.Picture we get inconsistent results. In debug mode, the SKImage is corrupted only the first time it is executed. Every following execution produces a valid image which can be displayed in a Xamarin.Forms.Image. In release mode the behavior is different. The SKImage is always corrupted. The Xam Image never shows the image.

What you will find in the sample project:
- Create Image Button which triggers the creation of the image and setting the bound ImageSources.
- Three Xamarin.Forms.Image:
  1. ImageSource is loaded from png file for reference. Is always working and displayed.
  2. ImageSource is loaded from SKImage, which is created from svg file.
  3. ImageSource is loaded from png stream, which is created from SKImage above.

What to do to reproduce:
- Click the "Create image" button repeatedly
- Look at the three different Images

We haven't tested if the problem persists on Android and iOs as well. We only use UWP yet.

### Code

            var s1 = await _assetLoader.Load(@"Assets\Test.png");
            ImageSource1 = ImageSource.FromStream(() => s1);

            float width = 500;
            float height = 500;

            var skSvg = new SKSvg(new SKSize(width, height));

            using (var svgStream = await _assetLoader.Load(@"Assets\Basemodule.svg"))
                skSvg.Load(svgStream);

            var recorder = new SKPictureRecorder();
            var canvas = recorder.BeginRecording(new SKRect(0, 0, width, height));
            canvas.Clear(SKColors.Transparent);

            var skImage = SKImage.FromPicture(skSvg.Picture, skSvg.CanvasSize.ToSizeI());
            ImageSource2 = skImage;

            canvas.DrawImage(skImage, 0, 0);

            var skPicture = recorder.EndRecording();

            var s2 = PictureToPngStream(skPicture);
            ImageSource3 = ImageSource.FromStream(() => s2);`

### Expected Behavior

The Xamarin.Forms.Image should display the SKImage on the first execution and on every repeated exection.

### Actual Behavior

The Xamarin.Forms.Image doesn't display the image on the first execution.

### Basic Information

- Version with issue:  1.60.3
- Last known good version:  None
- IDE:  Visual Studio
- Platform Target Frameworks:
  - UWP:  16299
- Target Devices:
  -   Dell Windows 10 Laptop

### Screenshots

Xamarin.Forms.Image doesn't show the image.

### Reproduction Link

https://drive.google.com/open?id=1bHJySrQKEf7gMVPlZeyeAh8rGoEPmA_t

> VS bug [#738686](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/738686)

**Comment by XamDevv** [comment]
Any news about the issue? A workaround would be welcome, too.

**Comment by mattleibow** [comment]
SVG work is not really a feature of SkiaSharp and it is probably good to try out https://www.nuget.org/packages/Svg.Skia

**Comment by XamDevv** [comment]
The problem was solved for us when we updated SkiaSharp from Version 1.60.3 to 1.68.1.1
