### ISSUE TITLE
Distance method missing from SKPoint 

### ISSUE THREAD

**Issue by mgnslndh** [mono/SkiaSharp#684]
### Description

`Distance` method missing from `SKPoint`. See https://skia.org/user/api/SkPoint_Reference#SkPoint_Distance for reference.

### Expected Behavior

`SKPoint` should have a static method `Distance` returning euclidian distance between two points.

### Actual Behavior

`Distance` method missing from `SKPoint`

### Basic Information

- Version with issue:  1.60.3
- IDE:  Visual Studio 
- Platform Target Frameworks: 
  - WPF:  Windows 10

> VS bug [#729964](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/729964)

**Comment by mattleibow** [comment]
Added in ca5eb3a70a543cc5530288e759fca26ce9478728, and a few more ;)
