### ISSUE TITLE
iOS 7 support

### ISSUE THREAD

**Issue by vvolkgang** [mono/SkiaSharp#693]
### Description

I'm not able to use SkiaSharp on a project that needs to support iOS 7. Has anyone tried to compile this dependency as a static library instead?

### Code

N/A

### Expected Behavior

Be able to use SkiaSharp on devices with iOS 7.

### Actual Behavior

Adding SkiaSharp nugget to a project supporting iOS 7, the following error is shown:
![error](https://puu.sh/C4U2G/6fad6178d3.png)

### Basic Information

- Version with issue:  1.60.3
- Last known good version: 
- IDE:  Visual Studio for Mac 
  - iOS:  iOS 7 minimum

### Screenshots

![error](https://puu.sh/C4U2G/6fad6178d3.png)

**Comment by mattleibow** [comment]
At this time, iOS 8 and later are the only versions supported.
This is the vast majority of the versions with Apple phasing out the older versions: https://developer.apple.com/support/app-store/ and https://data.apteligent.com/ios/

I understand that you may be requiring an older OS, but unfortunately this is a OS limitation. As a result, it would not even be possible to support pre iOS 8 versions. You might be able to update the device or the minimum target version.
