### ISSUE TITLE
How to create a Rectangle Shadow VIew Using SkiaSharp

### ISSUE THREAD

**Issue by sylendra7** [mono/SkiaSharp#695]
Hi ,

I created one Rectangle Shadow View using Skiasharp. I wanted to add child elements inside this view but It is not working as expected.

```csharp
    public class ShadowView : ContentView
    {
        public ShadowView()
        {
            SKCanvasView sKCanvasView = new SKCanvasView();
            sKCanvasView.PaintSurface += OnPaintSurface;
            Content = sKCanvasView;
        }

        void OnPaintSurface(object sender, SKPaintSurfaceEventArgs e)
        {
            var skCanvas = e.Surface.Canvas;
            var skinfo = e.Info;
            skCanvas.Clear();

           
            var RectangleStyleFillShadowColor = new SKColor(255, 0, 0, 255);
          
            var RectangleStyleFillShadow = SKImageFilter.CreateDropShadow(0f, 0f, 20f,20f, RectangleStyleFillShadowColor, SKDropShadowImageFilterShadowMode.DrawShadowAndForeground, null, null);
      
            var RectangleStyleFillColor = new SKColor(255, 255, 255, 255);
         
            var RectangleStyleFillPaint = new SKPaint()
            {
                Style = SKPaintStyle.Fill,
                Color = RectangleStyleFillColor,
                BlendMode = SKBlendMode.SrcOver,
                IsAntialias = true,
                ImageFilter = RectangleStyleFillShadow
            };
            var top = (float)(skinfo.Height * 0.1);
            var left = (float)(skinfo.Width * 0.1);
            var bottom = (float)(skinfo.Height);
            var right = (float)(skinfo.Width * 0.1);
            skCanvas.DrawRect(new SKRect(20f, 20f, skinfo.Width-20, skinfo.Height-20), RectangleStyleFillPaint);
        }
    }
```

Xaml: Here the border is not displaying

```xml
<StackLayout
            HorizontalOptions="FillAndExpand"
            Orientation="Vertical"
            VerticalOptions="FillAndExpand">
           <local:ShadowView HeightRequest="150" HorizontalOptions="FillAndExpand" Margin="20">
               <Label Text="Hello" HorizontalOptions="Center" VerticalOptions="CenterAndExpand"/>
            </local:ShadowView>
        </StackLayout>
```

**Comment by sylendra7** [comment]
Hi @mattleibow ,

Thanks for your reply.
Can you please give sample because, I created this as an custom control where I will add many number of Xamarin Controls inside the SkiaShadow View like below

  <local:ShadowView HeightRequest="150" HorizontalOptions="FillAndExpand" Margin="20">
                <StackLayout Orientation="Vertical">
                    <StackLayout Orientation="Horizontal" HorizontalOptions="FillAndExpand">
                        <Label Text="TOTAL INVESTMENTS" FontFamily="{StaticResource MontserratMedium}" FontSize="12" TextColor="Black" HorizontalOptions="StartAndExpand" />
                        <Label Text="This Month" FontSize="11" TextColor="#a4a8b6" FontFamily="{StaticResource MontserratMedium}" HorizontalOptions="End" />
                    </StackLayout>
                    <StackLayout Orientation="Horizontal" HorizontalOptions="FillAndExpand">
                        <StackLayout Orientation="Vertical" Spacing="0" HorizontalOptions="StartAndExpand">
                            <Label HorizontalOptions="End" Text="&gt;" VerticalOptions="Start" FontAttributes="Bold" FontSize="15" Margin="0,0,0,-10" Rotation="-90" TextColor="#51dc8e" />
                            <Label HorizontalOptions="Center" FontSize="Large" Text="20000" TextColor="Black" />
                        </StackLayout>
                    </StackLayout>
                </StackLayout>
   </local:ShadowView>


Can you please help me... I attached the screenshots for clear understanding.


Regards
Sylendra 
<img width="353" alt="screen shot 2018-11-24 at 7 56 16 pm" src="https://user-images.githubusercontent.com/15817571/48969375-bec67980-f023-11e8-93d5-8a2e58b34216.png">
<img width="555" alt="screen shot 2018-11-24 at 8 01 58 pm" src="https://user-images.githubusercontent.com/15817571/48969389-da318480-f023-11e8-9578-cacc26f91e02.png">

**Comment by mattleibow** [comment]
You cannot set the `Content` property of the `ContentView` (the skia canvas) and in the XAML (the stack layout).

I just did a test and instead of a `ContentView` (single child) I used a `Grid` (multiple children) and it appears to do hat you want. You may have to tweak the paddings and margins.

**Comment by sylendra7** [comment]
Hi @mattleibow ,

If I use your code which you sent previously ,is it be adaptable to any screen...?
Why because by using SkiaSharp seems it can be very useful to create any 2d drawings and very customised controls which cannot be done with custom renderers.

If we want to add children to skia sharp controls what will be the alternative ...?

Regards
Sylendra

**Comment by mattleibow** [comment]
You should be able to use my code. Your code will also work if your view type is a layout - such as a grid.
The main issue here is that the skiasharp views are not layouts and cannot have children. If you want something "inside" the view, you have to use a layout - such as a grid - and then add the canvas and the rest of the views.
