### ISSUE TITLE
Hi @mattleibow ,

### ISSUE THREAD

**Issue by sylendra7** [mono/SkiaSharp#696]
Thanks for your reply.
Can you please give sample because, I created this as an custom control where I will add many number of Xamarin Controls inside the SkiaShadow View like below

  <local:ShadowView HeightRequest="150" HorizontalOptions="FillAndExpand" Margin="20">
                <StackLayout Orientation="Vertical">
                    <StackLayout Orientation="Horizontal" HorizontalOptions="FillAndExpand">
                        <Label Text="TOTAL INVESTMENTS" FontFamily="{StaticResource MontserratMedium}" FontSize="12" TextColor="Black" HorizontalOptions="StartAndExpand" />
                        <Label Text="This Month" FontSize="11" TextColor="#a4a8b6" FontFamily="{StaticResource MontserratMedium}" HorizontalOptions="End" />
                    </StackLayout>
                    <StackLayout Orientation="Horizontal" HorizontalOptions="FillAndExpand">
                        <StackLayout Orientation="Vertical" Spacing="0" HorizontalOptions="StartAndExpand">
                            <Label HorizontalOptions="End" Text="&gt;" VerticalOptions="Start" FontAttributes="Bold" FontSize="15" Margin="0,0,0,-10" Rotation="-90" TextColor="#51dc8e" />
                            <Label HorizontalOptions="Center" FontSize="Large" Text="20000" TextColor="Black" />
                        </StackLayout>
                    </StackLayout>
                </StackLayout>
   </local:ShadowView>

Can you please help me... I attached the screenshots for clear understanding.

Regards
Sylendra 
<img width="353" alt="screen shot 2018-11-24 at 7 56 16 pm" src="https://user-images.githubusercontent.com/15817571/48969375-bec67980-f023-11e8-93d5-8a2e58b34216.png">
<img width="555" alt="screen shot 2018-11-24 at 8 01 58 pm" src="https://user-images.githubusercontent.com/15817571/48969389-da318480-f023-11e8-9578-cacc26f91e02.png">

_Originally posted by @sylendra7 in https://github.com/mono/SkiaSharp/issues/695#issuecomment-441372093_

**Comment by mattleibow** [comment]
Closing this one as I will respond in the other issue: https://github.com/mono/SkiaSharp/issues/695
