### ISSUE TITLE
What time will you make skiasharp support hardware acceleration?

### ISSUE THREAD

**Issue by wildfire810** [mono/SkiaSharp#70]
Excuse me, I want to know: what time will you make skiasharp support hardware acceleration?
Can you please tell me?
Because we plan to use it high load on windows wpf now, and the cross platform feature will be useful.

**Comment by migueldeicaza** [comment]
You mean the APIs, or the actual libraries that we ship with the product?

The major challenge is that it would be a larger library for corner cases, so we would need to do some packaging work to sort that out.

In the meantime, we would love if you try it out by building the library on your own.

Currently, our main focus is to complete the API bindings, and likely add some of the missing APIs.

**Comment by wildfire810** [comment]
Is there any hardware acceleration api in skiasharp?
I can not find it.
I think, the hardware render and soft render are different APIs in skia.
Is this true?

**Comment by alanricker** [comment]
I'm confused. Does this mean that the existing version of SkiSharp is using HW graphics acceleration to do the drawing or is it using SW emulation to do the drawing?
If HW, can you tell me what HW graphics API it is using on the various platforms:
* Windows
* iOS
* Android

**Comment by wildfire810** [comment]
I think it is useful

https://skia.org/user/api/canvas

Raster - CPU-only.
Ganesh - Skia’s GPU-accelerated backend.
SkPDF - PDF document creation.
SkPicture - Skia’s display list format.
NullCanvas - Useful for testing only.
SkXPS - Experimental XPS backend.
SkSVG - Experimental XPS backend.

https://skia.org/user/api/canvas#ganesh

https://skia.org/user/special/vulkan

**Comment by kekekeks** [comment]
Actually the only thing needed for hw-acceleration is to properly wire up skia with native OpenGL context. There are some tricks, but I have some experience in doing this in native code. The question is how that should be exposed. See [this issue](https://github.com/mono/SkiaSharp/issues/24) for details. I've also submitted initial design with [implementation example](https://github.com/mono/SkiaSharp/pull/36) but got no response, so I've stopped the work on that front.

**Comment by wildfire810** [comment]
How dose the offical dll work on windows?

**Comment by wildfire810** [comment]
If offical skia can do, skiasharp should too...

**Comment by kekekeks** [comment]
>How dose the offical dll work on windows?

Official dll needs you to manually provide opengl context and manually configure GrContext. Something like this: https://github.com/AvaloniaUI/libperspesk/blob/master/src/gl.cpp

It's not the code that you want to write in C#.

**Comment by wildfire810** [comment]
best work
https://github.com/AvaloniaUI/Avalonia

**Comment by mattleibow** [comment]
@wildfire810 @kekekeks Right now, the native dll on all the platforms link out the GPU bits as there is no support from SkiaSharp yet... but, as I am busy on #33, that requires some of the GPU bits. As a result, the "next" version should have PDF and GPU support. I am not sure if I will include the C# bindings for GPU just then, as it is more PDF-y. But, once the native bits are there, it will be easy to wrap. Basically, I am doing a bit of work for UWP as this is not yet Google-supported

**Comment by alanricker** [comment]
@mattleibow  Thanks for the update!
What is the ETA for "next" version?

**Comment by alanricker** [comment]
@mattleibow Now that you have closed #33 can you update us on the status of GPU support?
Thanks!

**Comment by mattleibow** [comment]
@wildfire810, @alanricker, @kekekeks, @bratsche Hardware support is here (-ish)
I have started with getting all the bits together and I think it is working quite well. Right now All the platforms should have OpenGL support (DirectX is coming in a few). This means all the platforms, except UWP, can draw with hardware acceleration.

The global issue for hardware / GPU is here: https://github.com/mono/SkiaSharp/issues/138
Please leave comments and suggestions so we can get the best product out.

There is also a preview NuGet: https://www.nuget.org/packages/SkiaSharp/1.53.2-gpu1
Please try that out and be sure to comment on how it went - if there are any features needed, just let us know!

**Comment by MuziburRahman** [comment]
@mattleibow any update on GPU acceleration in UWP?

**Comment by mattleibow** [comment]
It has been there for quite some time. Not sure exactly what you mean?

Right out the box, there is the `SKSwapChainPanel` that is GPU-only. There there is the `SKGLView` for Xamrin.Forms.

If you are talking the pure, non-UI way, then you have to first set up a GPU context - using ANGLE - and then do the `SKSurface.Create`.
