### ISSUE TITLE
UWP AngleSwapChainPanel inherits SwapChainPanel

### ISSUE THREAD

**Issue by ergodaveh** [mono/SkiaSharp#704]
### Basic Information

- Version with issue:  
- Last known good version:  
- IDE:  
- Platform Target Frameworks: 
  - Android:  
  - iOS:  
  - Linux:  
  - macOS:  
  - Tizen:   
  - tvOS:  
  - UWP:   
  - watchOS:  
  - Windows Classic:  
- Target Devices:
  -

**Comment by mattleibow** [comment]
The `AngleSwapChainPanel` is not meant to be used directly, and is just for internal SkiaSharp views. However, you can have a look at the code in the source for the UWP SkiaSharp.Views:
https://github.com/mono/SkiaSharp/blob/master/source/SkiaSharp.Views/SkiaSharp.Views.UWP/AngleSwapChainPanel.cs
