### ISSUE TITLE
SKGLView invalid memory exception when calling InvalidateSurface [Xamarin Forms UWP]

### ISSUE THREAD

**Issue by comfr3ak** [mono/SkiaSharp#706]
### Description

Connect SKGLView to the PaintSurface event. When a Xamarin forms page is loading and InvalidateSurface is called before the layout rendering passes are done (which also call the PaintSurface event), there is a memory exception encountered deep within the SKGLView. 

### Expected Behavior

Should not be an unhandled memory exception from C++ libraries underneath SkiaSharp.

### Actual Behavior

When calling SKGLView.InvalidateSurface while the view is still being loaded/rendered, an unhandled memory exception occurs outside of managed code. 

### Basic Information

- Version with issue:  1.60.3
- Last known good version:  
- IDE:  
- Platform Target Frameworks: 
  - Android:  
  - iOS:  
  - Linux:  
  - macOS:  
  - Tizen:   
  - tvOS:  
  - UWP:   
  - watchOS:  
  - Windows Classic:  
- Target Devices:
  -   

### Reproduction Link

> VS bug [#735694](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/735694)

**Comment by comfr3ak** [comment]
Can we have a flag that disables the rendering calls to the PaintSurface method so it only gets called when I call InvalidateSurface? Otherwise, it's impossible to know when the UI thread, which calls PaintSurface sometimes 3 or 4 times, is done doing the loading/resizing of the control.

**Comment by mattleibow** [comment]
@comfr3ak there is a flag to disable the render loop, bot not one to completely disable rendering. That would be a bit hard and non-deterministic. For example, assume the size of the view is 100x100, and the view is resized to 100x200. There is an additional chunk of pixels - what should be rendered there?

**Comment by comfr3ak** [comment]
But how can we tell the difference between a rendering like that and calling invalidate on a background thread to draw a new bitmap? The render calls are stepping on manual calls to invalidatesurface. Do you have a recommendation for proper way to avoid this?

**Comment by comfr3ak** [comment]
Basically the question is whether something underneath is allowing invalidatesirface to be called and run at the same time paintsurface is already rendering which causes the error. Shouldn’t something uh the skglview logic prevent this?

**Comment by mattleibow** [comment]
Good point. It should be running in serial, maybe there is some bad logic somewhere. I will investigate.

**Comment by mattleibow** [comment]
Wait a second... You are using the v1.60.x versions... The entire UWP view has been re-written in v1.68.x. Could you try the preview release and see if the problem goes away?

**Comment by comfr3ak** [comment]
Updated to pre-release version and the same issue still exists. When the page containing the SKGLView loads and I attempt to call InvalidateSurface while the rendering passes are still happening it gives me this: 

"An unhandled exception of type 'System.AccessViolationException' occurred in SkiaSharp.Views.UWP.dll
Attempted to read or write protected memory. This is often an indication that other memory is corrupt."

So far the only workaround is to try and delay things long enough for the rendering to finish but there is no real way to know that since there is no Loaded event or anything that tells me when the control is finished an initial rendering.

**Comment by comfr3ak** [comment]
Some more information. It seems to be that this type of navigation sequence of events always causes the accessviolationexception: 


Home -> Page 1  (view displays fine, page 1 built the first time before navigating)
Page 1 -> Home (Page 1 is stored in memory so it's not rebuilt every time)
Home -> Page 1 (view causes that exception after going back to page 1)

This is slightly different behavior than version 1.60.3 which was able to do this sequence and only intermittently fall into the same exception. Now it appears the exception is happening every single time under the prerelease 1.68.x version.

**Comment by mattleibow** [comment]
The fact that the issue is happening consistently is good as it makes it easier to test. Are you able to submit this 2-page sample so we can test?

As a workaround in the interim, is it possible to delay rendering until after the OnAppearing method of the page has been called? I believe that should only run AFTER the view has been added to the UI? Then you could try setting a flag to true/false with the OnAppearing/OnDisappearing methods.

**Comment by comfr3ak** [comment]
More information, it looks like even if I delay the call to InvalidateSurface and remove everything I'm doing out of the PaintSurface event, it still crashes consistently every time in that scenario when you return to the page and call InvalidateSurface at any point. The project is rather large but I can at least provide some of the code I'm using to init and use the SKGLView and paint method. 

The premise here is that the compressed images come in from a camera system over UDP network communication. We pass them to to be displayed approximately 16 times per second. We were using the SKCanvaseView but found the performance lacked. SKGLView is much better for performance and smoothness but we encountered this crash scenario which doesn't happen with SKCanvasView

[skglcanvas sample.txt](https://github.com/mono/SkiaSharp/files/2620786/skglcanvas.sample.txt)

**Comment by mattleibow** [comment]
I will have a deeper look at this - it may very well be that when the page is navigated away, the OpenGL context is destroyed, but SkiaSharp does not know that. And, when you go back, the references are old.

Also, do you have any stack trace at all? That may shed some light.

Finally, it may be helpful to set up a very simple case with the page navigation (if possible) and just render a red block or something. It is either the UWP view that is not working correctly, or it may be that you are accessing the SkiaSharp objects on multiple threads.

**Comment by comfr3ak** [comment]
Also, I did test the case where I draw nothing in the PaintSurface method and it still happens.

**Comment by comfr3ak** [comment]
More information, If I call SKGLView.InvalidateSurface wrapped in Device.BeginInvokeOnMainThread then I don't encounter this error at all, I can navigate in and out dozens of times with no exception. The result, however, is that the performance is worse than compared to calling it synchronously on the background thread.

**Comment by mattleibow** [comment]
This is something that we will be looking at in the future.

**Comment by comfr3ak** [comment]
Would you recommend only calling Invalidate from anything other than the main thread in the meantime?

**Comment by mattleibow** [comment]
Unless... you are calling invalidate on two different threads at the same time. When you call invalidate, it runs on the thread you called - but if you call invalidate on multiple threads, it does not check to see if another thread is already running. (probably a bug) Then, when you run it on the main thread, this forces a single run at a time.

So, one way is to have some sort of locking for the invalidate to ensure only one ever calls it - but this might not fix it.

The GL canvas for UWP is not technically drawing on the background thread - it always redirects to the UI thread. And, technically, you should always call invalidate on the main thread. So, i think the reason that things are blowing up is that you are calling a UI method on a background thread - the drawing logic is fine, not the fields and other glue under the hood.

So, the fix is to actually enable a property on the native UI view - `DrawInBackground` - on the `SKSwapChainPanel` type. Since you are using Xamarin.Forms, you will have to create a custom renderer to do this.:

```csharp
using SkiaSharp.Views.Forms;
using SkiaSharp.Views.UWP;
using Xamarin.Forms.Platform.UWP;

[assembly: ExportRenderer(typeof(SKGLView), typeof(SkiaSharpSample.UWP.SKGLViewBackgroundRenderer))]

namespace SkiaSharpSample.UWP
{
	public class SKGLViewBackgroundRenderer : SKGLViewRenderer
	{
		protected override SKSwapChainPanel CreateNativeControl()
		{
			var view = base.CreateNativeControl();
			view.DrawInBackground = true;
			return view;
		}
	}
}
```

**Comment by mattleibow** [comment]
Did you get around to trying the custom renderer?

**Comment by Redth** [comment]
We are closing this issue since no response was received.  Please open a new issue referring to this one if you have more information.
