### ISSUE TITLE
React to user input

### ISSUE THREAD

**Issue by gentledepp** [mono/SkiaSharp#71]
I am not sure if this is meant to be part of SkiaSharp, but I was searching through the docs about a way to actually react to user input such as touch gestures.
Reason being, I would like to convert my android drawing app to use shiasharp instead of the drawing canvas api in order to make it kinda platform independant.

Are there any plans to introduce such features at any time? Or are they already there and I missed them?

Sorry for not asking in stackoverflow - I was not sure if you guys would read it there...

Thank you so much for clarifying things!

**Comment by roceh** [comment]
I written a bit more extensive container than the one in the demo app for SkiaSharp here: https://github.com/roceh/MycoLayout

Has a few gestures for the 'skia controls', pan, tap and horizontal swipe.

**Comment by mattleibow** [comment]
Hi @gentledepp,

I don't think we will be adding support for this as is not the goal of Skia. Skia and SkiaSharp are drawing libraries. User interaction is both platform and device dependent, as a result it will be a large undertaking and veer off target.

However, a user interaction library based on Skia is totally fine. Examples like the one above may exist.
