### ISSUE TITLE
SkiaSharp change the image when a combo is selected Xamarin Forms

### ISSUE THREAD

**Issue by cacfucha** [mono/SkiaSharp#710]
Hello, 
Thanks for your contributions have served me. I have a small problem that I do not know how to solve. I need to change the image shown in SkiaSharp when I select another image to show from a combobox. I only change that image when I rotate the device or pulse on the image
Regards.

```xml
<views:SKCanvasView x:Name="canvasView" PaintSurface="OnPainting" EnableTouchEvents="True" Touch="OnTouch"></views:SKCanvasView>
```
 or 

```xml
<views:SKCanvasView x:Name="canvasView" PaintSurface="OnCanvasViewPaintSurface" EnableTouchEvents="True" Touch="OnTouch"></views:SKCanvasView>
```

        void OnCanvasViewPaintSurface(object sender, SKPaintSurfaceEventArgs args)
        {
            SKSurface surface = args.Surface;
            SKCanvas canvas = surface.Canvas;
            canvas.Clear(SKColors.White);

            if (img != null)
            {
                SKBitmap bmp = SKBitmap.Decode(img);
                canvas.DrawBitmap(bmp, 0, 0);
            }
        }

**Comment by mattleibow** [comment]
I am closing this as your question is better discussed on the forums (https://forums.xamarin.com/) or on SO.
