### ISSUE TITLE
Any plan to help x.forms to implement ubiquitous-looking controls?

### ISSUE THREAD

**Issue by juepiezhongren** [mono/SkiaSharp#714]
hey, mathiew

**Comment by mattleibow** [comment]
We are not specifically looking at this right now. This is not to say that we won't in the future, it is just not on the roadmap at this time. There are a few people in the community who are looking at this, so maybe you can have a look and see if any are interesting.

**Comment by charlesroddie** [comment]
@juepiezhongren It is easy to create these. Just take a dependency on SkiaSharp or on SkiaSharp.Forms (the latter supporting touch), make a control, and release it. https://github.com/verybadcat/CSharpMath controls are doing it this way.

This does not need input from Xamarin. And I don't think you can implement controls this way in the Xamarin.Forms repo without more discussion as XF would need to take a SkiaSharp dependency.
