### ISSUE TITLE
HarfBuzzSharp: Buffer is missing AddUtf16 method

### ISSUE THREAD

**Issue by Gillibald** [mono/SkiaSharp#715]
### Description

I am currently in the works of a text layout for SkiaSharp and need to be able to configure the shaper to use UTF-16 indices instead of UTF-8. The only way to do that is adding UTF-16 values to the buffer instead of UTF-8. The shaper should use the current encoding to process the text properly otherwise clusters have the wrong indices.

### Expected Behavior

I would expect that the shaper uses the current encoding.

### Actual Behavior

UTF-8 is used all times.

### Basic Information

- Version with issue:  1.68.0
- Last known good version:  -

> VS bug [#742852](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/742852)

**Comment by mattleibow** [comment]
This is a good thing. I will update harfbuzz and get support for utf8/16/32.

**Comment by Gillibald** [comment]
Will try to implement this myself the next days. In general, adding AddUtf16, AddUtf32 to Buffer and changing SKShaper to use the current TextEncoding. GlyphId will be nonvalid value. Probably need more advanced features in the future so it makes sense I implement it myself.

**Comment by mattleibow** [comment]
Cool! Just an FYI, there is a `SKTextEncoding` and a `SKEncoding`.

I see Google uses both differently, `SKTextEncoding` is for taking a chunk of memory, and writing it to the screen. `SKEncoding` is for taking a chunk of text in memory and converting it to glyph data. There were using the `SKTextEncoding` for both in the past, but they split it.

But, looking at harfbuzz, they have `hb_buffer_add_codepoints` which is the glyph ids if i am not mistaken... I am not sure how that works off the top of my head, but you can try it out and it may be what you need.

**Comment by Gillibald** [comment]
#744

**Comment by mattleibow** [comment]
Merged in https://github.com/mono/SkiaSharp/pull/766 and others.
