### ISSUE TITLE
GPU based Offscreen rendering in windows desktop app

### ISSUE THREAD

**Issue by gregsn** [mono/SkiaSharp#717]
### Description

Imagine n SKGLControls + m OffScreenRenderings yielding SKImages with n, m in N°.
Is there a way of having the OffScreenRenderings GPU accelerated on a Windows Desktop application?

I thought maybe for that we need ANGLE or Vulkan Backends for that, but unsure why the OpenGL would not deliver the expected performance. Then again I am not so familiar with OpenGL and on how to handle MakeCurrent OpenGL calls. Can I expect a performance boost when using those two fancy backends?

The updates on these two threads look promising! Big up!
#243 !  
#252

Maybe related:
#688

**Comment by mattleibow** [comment]
Closing this as the question has been answered: Yes, offscreen drawing is a thing that can be done. OpenGL should be fine as it is a Windows feature. ANGLE/Vulkan may not have that much of an improvement.

Issue #688 has code for iOS and UWP, but you could have a look at other Windows implementations - such as what they do for OpenTK or at the SkiaSharp Windows tests: https://github.com/mono/SkiaSharp/blob/master/tests/Tests/GlContexts/Wgl/WglContext.cs
