### ISSUE TITLE
SKColorFilter.CreateColorCube disappeared?

### ISSUE THREAD

**Issue by deakjahn** [mono/SkiaSharp#720]
### Description

Am I seeing things? A dozen or so versions ago there was support for LUT 3D cubes. The docs still list it: https://docs.microsoft.com/en-us/dotnet/api/skiasharp.skcolorfilter.createcolorcube?view=skiasharp-1.57.1. Probably might have been removed from Skia itself but how come? Are we supposed to go backwards? :-(

**Comment by mattleibow** [comment]
Yeah, I know. This is unfortunate, but Google decided that they aren't going to keep it:
https://github.com/google/skia/commit/efaad3cd53330f063e6feaee8b14ad43ca251184

Just a simple `Remove SkColorCubeFilter.  It is unused.` commit.

The best thing i can suggest is ask on the Google forums: https://groups.google.com/forum/#!forum/skia-discuss They may know what the best replacement - or maybe a better way to do what you want.

**Comment by deakjahn** [comment]
I most certainly will. What a shame. :-)
