### ISSUE TITLE
Missing SkDrawable

### ISSUE THREAD

**Issue by charlenni** [mono/SkiaSharp#726]
### Description

I'm missing the complete SkDrawable concept (object, SkPictureRecorder.EndRecordingAsDrawable, SkCanvas.DrawDrawable). Are there any efforts on this?

> VS bug [#751309](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/751309)

**Comment by charlenni** [comment]
I look into this, but it seems to be complicated. All other classes in SkiaSharp are made as wrapper classes and the native Skia objects used as standard c function calls. This doesn't work for SkDrawable, because SkDrawable is more like an interface. Childs have to implement some funktions (like OnDraw), that would be called from the native side.

Does anyone have any idea, how this could be solved?

**Comment by mattleibow** [comment]
This looks like something that can be done with the way we did the managed stream wrappers:

The C++ class:
https://github.com/mono/skia/blob/xamarin-mobile-bindings/include/xamarin/SkManagedStream.h

The C API:
https://github.com/mono/skia/blob/xamarin-mobile-bindings/include/xamarin/sk_managedstream.h

The managed code:
https://github.com/mono/SkiaSharp/blob/master/binding/Binding/SKAbstractManagedStream.cs
https://github.com/mono/SkiaSharp/blob/master/binding/Binding/SKManagedStream.cs

**Comment by charlenni** [comment]
Äh, I thought, that this class couldn’t the first one.

Thank you for pointing me in the right direction. I will see, what I can do.

**Comment by mattleibow** [comment]
I am going to leave this one open for now so we can actually do this at some point - or if you are interested, then have a place to talk.

**Comment by charlenni** [comment]
I now created a first version (see [Skia](https://github.com/charlenni/skia/tree/SkDrawable) and [SkiaSharp](https://github.com/charlenni/SkiaSharp/tree/SkDrawable)). It exposes the 3 functions OnDraw, OnGetBounds and OnNewPictureSnapshot from C/C++ and adds the missing parts in SkiaSharp.

But how to compile to test it? Are there any scripts? Could I do this with VS 2017?

**Comment by mattleibow** [comment]
Wow! This looks cool! I will take a closer look. 

For most cases, you can actually be very specific and just build the platform and then run the unit tests. _(I need to update - or rather, create - the "contributing" docs)_

**Build Native Code**

macOS:
```
./bootstrapper.sh -t externals-macos
```

Windows:
```
.\bootstrapper.ps1 -t externals-windows
```

Linux:
```
./bootstrapper.sh -t externals-linux
```

**Run Tests in the Console**

macOS & Linux:
```
./bootstrapper.sh -t tests-only
```

Windows:
```
.\bootstrapper.ps1 -t tests-only
```

**Run Tests in the IDE**
Just open the `tests/SkiaSharp.Desktop.Tests/SkiaSharp.Desktop.Tests.sln` solution and run the tests there.

**Comment by mattleibow** [comment]
@charlenni Maybe open a PR to both repos if you want to start a discussion... Then we can talk on each line and stuff. If you are ready, that is.

**Comment by charlenni** [comment]
Thank you for your help @mattleibow.

The above commands are for building SkiaSharp, but not for Skia. Does it build Skia too?

I open a PR when I sure, that I can compile the code.

**Comment by mattleibow** [comment]
Yes, the `externals-xxx` target downloads dependencies and builds skia.

**Comment by charlenni** [comment]
But I have my own Skia, because I changed files there too. So I assume, that I have to copy the Skia files to another place, correct?

**Comment by mattleibow** [comment]
I usually just work in the skia submodule and change that to target whatever I want.

For example:
 1. Fork `skia` and `SkiaSharp`
 2. Create a new `skia` branch (which you have done already)
 3. Clone `SkiaSharp` and update submodules
 4. Checkout your new `SkiaSharp` branch
 5. Add your fork to the `skia` submodule remotes and checkout your new `skia` branch

Now, you should be able to work in both `skia` and `SkiaSharp`. You can commit all the changes for now, and when I merge, I will first merge `skia` and then update your branch back to `xamarin-mobile-bindings`.

**Comment by charlenni** [comment]
Ok, I now integrated Skia into SkiaSharp, downloaded my branch and tried to compile it. But it seems, that I'm missing something. The output is
````
Preparing to run build script...
Running build script...
Analyzing build script...
Processing build script...
Installing tools...
Installing addins...
The assembly 'Cake.Xamarin, Version=3.0.0.0, Culture=neutral, PublicKeyToken=null'
is referencing an older version of Cake.Core (0.26.1).
For best compatibility it should target Cake.Core version 0.28.0.
The assembly 'Cake.XCode, Version=4.0.0.0, Culture=neutral, PublicKeyToken=null'
is referencing an older version of Cake.Core (0.26.1).
For best compatibility it should target Cake.Core version 0.28.0.
The assembly 'Cake.FileHelpers, Version=3.0.0.0, Culture=neutral, PublicKeyToken=null'
is referencing an older version of Cake.Core (0.26.1).
For best compatibility it should target Cake.Core version 0.28.0.
Compiling build script...

Tool Paths:
  Cake.exe:   C:/Entwicklung/SkiaSharp/tools/Cake/Cake.exe
  mdoc:       C:/Entwicklung/SkiaSharp/tools/mdoc.5.7.3.1/tools/mdoc.exe
  msbuild:    [NULL]
  nuget.exe:  C:/Entwicklung/SkiaSharp/tools/nuget.exe
  python:     python

Build Paths:
  ~:              C:/Users/weltz
  NuGet Cache:    C:/Users/weltz/.nuget/packages
  root:           C:/Entwicklung/SkiaSharp
  docs:           C:/Entwicklung/SkiaSharp/docs/xml
  package_cache:  C:/Entwicklung/SkiaSharp/externals/package_cache
  ANGLE:          C:/Entwicklung/SkiaSharp/externals/angle
  depot_tools:    C:/Entwicklung/SkiaSharp/externals/depot_tools
  harfbuzz:       C:/Entwicklung/SkiaSharp/externals/harfbuzz
  skia:           C:/Entwicklung/SkiaSharp/externals/skia

SDK Paths:
  Android SDK:   /Library/Developer/Xamarin/android-sdk-macosx
  Android NDK:   /Library/Developer/Xamarin/android-ndk
  Tizen Studio:  /tizen-studio

Environment Variables (whitelisted):
  NUMBER_OF_PROCESSORS:             8
  OS:                               Windows_NT
  Path:                             C:\VulkanSDK\1.1.85.0\Bin
                                    C:\Windows\system32
                                    C:\Windows
                                    C:\Windows\System32\Wbem
                                    C:\Windows\System32\WindowsPowerShell\v1.0\
                                    C:\Windows\System32\OpenSSH\
                                    C:\Program Files\dotnet\
                                    C:\Program Files (x86)\Common Files\Acronis\VirtualFile\
                                    C:\Program Files (x86)\Common Files\Acronis\VirtualFile64\
                                    C:\Program Files (x86)\Common Files\Acronis\FileProtector\
                                    C:\Program Files (x86)\Common Files\Acronis\FileProtector64\
                                    C:\Program Files (x86)\Common Files\Acronis\SnapAPI\
                                    C:\Program Files\Git\cmd
                                    C:\Users\weltz\AppData\Local\Microsoft\WindowsApps

  PROCESSOR_ARCHITECTURE:           AMD64
  PROCESSOR_IDENTIFIER:             Intel64 Family 6 Model 58 Stepping 9, GenuineIntel
  PSModulePath:                     C:\Users\weltz\Documents\WindowsPowerShell\Modules
                                    C:\Program Files\WindowsPowerShell\Modules
                                    C:\Windows\system32\WindowsPowerShell\v1.0\Modules


========================================
externals-angle-uwp
========================================
Skipping task: externals-angle-uwp

========================================
externals-harfbuzz
========================================
Skipping task: externals-harfbuzz

========================================
externals-init
========================================
Executing task: externals-init
An error occurred when executing task 'externals-init'.
Error: Mindestens ein Fehler ist aufgetreten.
        Das System kann die angegebene Datei nicht finden
````
At the end I get a "File not found" error.

I assume, that I'm missing a package, that is used while compiling. I added Python to VS 2017, because I havn't installed it up to now, but now succes.

If someone has a good idea...

**Comment by charlenni** [comment]
@mattleibow Thank you for the fast support.

Yes, I found in the code, that it uses PYTHON_EXE and MSBUILD_EXE from environment. I now set this two variables and get
````
Tool Paths:
  Cake.exe:   C:/Entwicklung/SkiaSharp/tools/Cake/Cake.exe
  mdoc:       C:/Entwicklung/SkiaSharp/tools/mdoc.5.7.3.1/tools/mdoc.exe
  msbuild:    C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\amd64
  nuget.exe:  C:/Entwicklung/SkiaSharp/tools/nuget.exe
  python:     C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64
````
With this, the error message changes from a "File not found" to a "Access denied" error. But it doesn't tell, which file or folder should be accessed :)

**Comment by mattleibow** [comment]
Did you check out the submodule? There should be an externals/depot_tools

**Comment by charlenni** [comment]
Yes, I did this. There are many Git Python files and a ninja.exe.

**Comment by charlenni** [comment]
I didn't set the environment variables for Android and Tizen, but I assume, that this isn't the problem, because I build for Windows.

**Comment by mattleibow** [comment]
Ah, your python must be to the exe itself. I see you just go to the folder

**Comment by charlenni** [comment]
You are right. So I changed the environment virables PYTHON_EXE and MSBUILD_EXE to the corresponding EXE files. Now I get a step further.

I now get 
````
========================================
externals-init
========================================
Executing task: externals-init
Traceback (most recent call last):
  File "C:/Entwicklung/SkiaSharp/externals/skia/tools/git-sync-deps", line 253, in <module>
    exit(main(sys.argv[1:]))
  File "C:/Entwicklung/SkiaSharp/externals/skia/tools/git-sync-deps", line 245, in main
    git_sync_deps(deps_file_path, argv, verbose)
  File "C:/Entwicklung/SkiaSharp/externals/skia/tools/git-sync-deps", line 190, in git_sync_deps
    deps_file = parse_file_to_dict(deps_file_path)
  File "C:/Entwicklung/SkiaSharp/externals/skia/tools/git-sync-deps", line 170, in parse_file_to_dict
    execfile(path, dictionary)
NameError: name 'execfile' is not defined
An error occurred when executing task 'externals-init'.
Error: Mindestens ein Fehler ist aufgetreten.
        Process 'C:/Program Files (x86)/Microsoft Visual Studio/Shared/Python36_64/python.exe' failed with error: 1
````

**Comment by mattleibow** [comment]
I would try just adding the python to the path... I am not sure how well that has been tested. The tooling might be making some assumptions.

**Comment by charlenni** [comment]
Ok, found the problem: Python 3.x doesn't contain ````execfile()```` anymore. So I have to install a Python 2.x version ;)

**Comment by charlenni** [comment]
It seems to work. The first 380 from 1056 Skia files are allready compiled ;)

**Comment by charlenni** [comment]
It seems, that I need the VS 2015 15.3 development tools. Could be installed via VS 2017 installer. Only addinitional 3.26 GB of space ;)

**Comment by charlenni** [comment]
Ok, with this, the command ````.\bootstrapper.ps1 -t externals-windows```` run through without any errors.

Now I get finally to the real problems. The SkDrawable.OnGetBounds() returns a SkRect. But how to convert this to a IntPtr? Any idea?

**Comment by charlenni** [comment]
Yes, I could compile all and run the tests. Works so far. 

How to create a Nuget package, so that I could add it to an own project?

**Comment by mattleibow** [comment]
Awesome! The NuGet... That will require all the Windows platforms at least. If you want to test, you can hook things up manually. Just add a reference to the SkiaSharp.dll and make sure the platform libSkiSharp.dll is marked as Content and copied to output.

Also, you could test it via one of the sample apps https://github.com/mono/SkiaSharp/blob/master/samples/Basic/Desktop/SkiaSharpSample/SkiaSharpSample.csproj

**Comment by charlenni** [comment]
I test it now via the sample. Works good and so I could go for hunting of bugs.

**Comment by charlenni** [comment]
It seems, that the libSkiaSharp doesn't contain any of the new C/C++ files. Should I add the new file names at any place, so that they compiled and added to the lib?

**Comment by mattleibow** [comment]
ah, yeah. there is a `<skia>/src/xamarin/SkiaKeeper.c` just add a line for one symbol in the array. We have a strict linking process and that is what is kept.

**Comment by charlenni** [comment]
And I had to add the new files to BUILD.gn.

Now I'm at a point where I could compile the library and a sample works. Now I have one more question: should I do anything when dispose the object? Need I a unref or destroy function?

**Comment by mattleibow** [comment]
depending on how you created the object. if you did a `new` in C++, then you need a `delete`, but if you got it via method that had a `sp_ref<SkDrawable>` return, then usually you can just `SkSafeUnref`.

I see you just make a few PRs! NICE! I'll add comments to that so we can talk in code :)

**Comment by charlenni** [comment]
Ok, than I should ````delete```` the ````SkManagedDrawable```` created [here](https://github.com/charlenni/skia/blob/SkDrawable/src/xamarin/sk_manageddrawable.cpp#L52).

**Comment by mattleibow** [comment]
I had a look at the PRs and they are really good - I felt happy reading them :)
Most of my comments relate to the inheritance as I would like to separate the Xamarin bits and the pure binding bits. This is for two reasons:
 1. to match what is happening in the C++ world as Google is prone to changing things, and I would like to be able to just rewrite the Xamarin bits if they decide to break the world.
 2. we have a dream here... to eventually upstream the C API - or at least parts of it (it is a far off dream, but it is still there, somewhere)

**Comment by charlenni** [comment]
I wanted to add the ````sk_drawable.h```` and ````sk_drawable.cpp````. I added the h-file and a reference into SkiaKeeper.c. But it isn't respected while compile Skia? in BUILD.gn I didn't find anything about the folder include/c or src/c. Are I'm missing something?

**Comment by mattleibow** [comment]
I saw you found the `gn/core.gni` file that did things. That is the correct place to put it.

**Comment by mattleibow** [comment]
Thanks for  the PRs, I have merged them into master and CI is taking over... The development branch built fine, so I think all is well.

**Comment by charlenni** [comment]
@mattleibow I hope, you had a good start into the new year.

Is there a timeline, when the 1.68.1-beta is released?
