### ISSUE TITLE
NotSupportedException when trying to use SKGLView

### ISSUE THREAD

**Issue by wojciechsura** [mono/SkiaSharp#729]
### Description

When trying to use SKGLView, application crashes with NotSupportedException. Tested on Android and UWP (desktop Windows)

### Code

Problem occurs when we call `glView.InvalidateSurface()`. We're getting the following message:

    System.NotSupportedException: Specified method is not supported.
      at SkiaSharp.GRContext.Create(GRBackend backend, GRGIInterface backedContext)
      at SkiaSharp.Views.UWP.SKSwapChainPanel.OnRenderFrame(Rect rect)
      at SkiaSharp.Views.UWP.AngleSwapChainPanel.RenderFrame()
      at SkiaSharp.Views.UWP.AngleSwapChainPanel.Invalidate()
      at SkiaSharp.Views.UWP.AngleSwapChainPanel.CalculateBufferSize()
      at SkiaSharp.Views.UWP.AngleSwapChainPanel.OnSizeChanged(Object sender, SizeChangedEventArg e)

The SKGLView is instantiated simply via parameterless constructor. We actually derive our own class from SKGLView to support mouse-wheel handling:

    public class SKGLViewEx : SKGLView
    {
        public void NotifyMouseWheel(int mouseWheelDelta)
        {
            MouseWheel?.Invoke(this, new MouseWheelEventArgs(mouseWheelDelta));
        }

        public event EventHandler<MouseWheelEventArgs> MouseWheel;
    }

Except from that we introduced no changes to Skia.

### Basic Information

- Version with issue:  1.68.0
- Last known good version:  1.60.3
- IDE:  Visual Studio
- Platform Target Frameworks: 
  - Android: 8.1
  - iOS:  (Default)
  - UWP:  17134 
- Target Devices:
  -   Nexus 10
  -   Desktop Windows

![skiaerror](https://user-images.githubusercontent.com/5938870/49936764-1b0b1380-fed5-11e8-9925-ee96e7bb9278.png)

> VS bug [#752324](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/752324)

**Comment by mattleibow** [comment]
I bet this happened when Google swapped the values for the enumerations on me. 😢 

I feel shame.

However, they can't do it again as I have a proxy for this now.

The only thing that I can say is to make sure all your dependencies are either 1.60 or 1.68+. Mixing the versions will do this to you.
