### ISSUE TITLE
DllNotFoundException on Linux (Synology DSM)

### ISSUE THREAD

**Issue by automagisk** [mono/SkiaSharp#733]
### Description

SkiaSharp crashes with DllNotFoundException on Linux (1.68.0 + Core 2.2). I'm pretty sure this has worked sometime but I can't verify that right now. I think that was running .NET Core 1.1 and I can't seem to create a 1.1 project at the moment. It works on Windows though.

### Repro steps (minimal project)

1. Create a new ASP.NET Web Core Application (empty, no ssl, no docker)
2. Add mvc-support
3. Add Nugets SkiaSharp and SkiaSharp.NativeAssets.Linux
4. Add a controller that invokes SkiaSharp
5. Publish with VS Community 15.9.3 (release Linux-64) on Windows 10
6. Add a basic Docker-file
7. Copy files to Linux (Synology custom version based straight on Linux kernel)
8. Build and run with docker
9. Invoke controller, crash

### Exception message

The type initializer for 'SkiaSharp.SKAbstractManagedStream' threw an exception. ---> System.DllNotFoundException: Unable to load shared library 'libSkiaSharp' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: liblibSkiaSharp: cannot open shared object file: No such file or directory

### Files

[project.zip](https://github.com/mono/SkiaSharp/files/2682570/project.zip)
[publish.zip](https://github.com/mono/SkiaSharp/files/2682571/publish.zip)
[log.zip](https://github.com/mono/SkiaSharp/files/2682572/log.zip)

**Comment by POLAK93** [comment]
fix with `RUN apt-get update && apt-get install libfontconfig1 -y && apt-get install libfontconfig -y` works in my case

**Comment by mattleibow** [comment]
I'll close this as the issue seems to be resolved.
