### ISSUE TITLE
Regression - SKPaint.BreakText crashes for Empty string ("" - String.Empty) in SkiaSharp 1.68

### ISSUE THREAD

**Issue by michaldobrodenka** [mono/SkiaSharp#734]
### Description

SKPaint .BreakText throws an exception "System.ArgumentNullException: 'Value cannot be null.
Parameter name: buffer'" for String.Empty. In 1.60.3 it works normally.

### Code

```
            using (var paint = new SKPaint())
            {
                paint.BreakText(String.Empty, 10);
            }
```

### Expected Behavior

no exception, return 0

### Actual Behavior

ArgumentNullException

**Comment by mattleibow** [comment]
Thanks for reporting this! I have found the issue and fixed it.
