### ISSUE TITLE
Access violation in multithreaded code

### ISSUE THREAD

**Issue by deakjahn** [mono/SkiaSharp#738]
Yes, I'm aware of https://github.com/mono/SkiaSharp/issues/235. This is slightly different.

I have a listview with a canvas in each item. Displaying the items might take same time, so to ensure responsivity, the drawing has to be done asynchronously (all listivew items appear immediately, individual contents appear in async when finished). It's obvious that UI operations cannot happen on other threads, so I use the same solution that I use everywhere else in my app when I need to combine tasks and UI: grabbing the synchronization context. This works all right in all cases but not with Skia, it immediately leads to access violation errors.

Consider a simple `PaintSurface` handler that does anything Skia, eg:

    private void OnPainting(object sender, SKPaintSurfaceEventArgs e) {
      e.Surface.Canvas.DrawBitmap(bitmap, 0, 0);
    }

Drawing a bitmap is just an example, any canvas operation will do. Let's simply move this into a task of its own:

    public async Task<bool> Draw(SKCanvas canvas) {
      return await Task.Factory.StartNew(() => {
        canvas.DrawBitmap(bitmap, 0, 0);
        return true;
      }, CancellationToken.None, TaskCreationOptions.None, TaskScheduler.FromCurrentSynchronizationContext());
    }

and call it accordingly:

    private async void OnPainting(object sender, SKPaintSurfaceEventArgs e) {
      await Draw(e.Surface.Canvas);
    }

results in an AccessViolationError. Again, note that it isn't a `Task.Run()`, it's the underlying `Task.Factory.StartNew()` specifying the current sync context. It *can* touch UI all right, no problems with that in general.

**Comment by mattleibow** [comment]
This is because when you await the task, the draw method has completed. Then when the task actually runs, the canvas may/may not be valid still.

To do this, you actually don't await in the draw, but rather render the bitmap somewhere, and then just lit the bitmap to the canvas in a few ms. The actual draw of a bitmap is not that slow, but if you have a complex image, it may take some time. Also, if the image can be cached, you can queue the images as they appear, and render a white block. Then, as soon as the images are done, just invalidate.

I created an example app that does just that to show one possible way to achieve a non-blocking render: https://github.com/mattleibow/SkiaSharpMultiThreadedLists

Let me know if this helps.

**Comment by deakjahn** [comment]
Certainly, that was the first thought but it didn't help because the first canvas operation crashed even then. Looking at your sample, you create a different canvas for the drawing, not using the actual one. Well, that's an idea, I'll try.

**Comment by deakjahn** [comment]
Yep, that was the key, to create an independent canvas for the background drawing. The rest works OK. Having the `SKImageInfo` in my hand, I could also try out the color space approach we spoke about in another thread. Besides, do you know why my drawing takes more time? I finally abandoned the idea (at least for now) of adding back the `SKColorCube` into the package and do the process in software. :-)

**Comment by mattleibow** [comment]
Maybe you can share your code for the color cube and I'll have a look at what you are doing. There might be something to speed it up.

**Comment by mattleibow** [comment]
The issue with the canvas is that it gets destroyed when you leave the draw method. This is because we can't guarantee that it will always be there, for example, if the canvas is resized or if the cell is recycled.

**Comment by deakjahn** [comment]
I'm partly on track. When I specify the color space, the operations using `SKColorFilter.CreateTable` become crazy. Simpler `SKColorFilter.CreateColorMatrix` manipulations are OK. Tables seem to be problematic with color spaces.

**Comment by mattleibow** [comment]
My profile email is good.
