### ISSUE TITLE
Missing method SKMatrix.MakeRotation(theta, pivotX, pivotY)

### ISSUE THREAD

**Issue by charlenni** [mono/SkiaSharp#74]
Method is implemented in Skia, but could not be found in the bindings.

**Comment by migueldeicaza** [comment]
Can you point us to the method?

**Comment by gentledepp** [comment]
see
void SkMatrix::setRotate(SkScalar degrees, SkScalar px, SkScalar py) {
in https://github.com/google/skia/blob/master/src/core/SkMatrix.cpp 
Basically it would be nice, to have an overload to SKMatrix, so that a rotation can be applied with a specified rotation center (translation)

**Comment by migueldeicaza** [comment]
Added

**Comment by gentledepp** [comment]
Which commit?
