### ISSUE TITLE
[FEATURE]  Pressure Info from TouchEventArgs in SkCanvasView for Pen Inputs

### ISSUE THREAD

**Issue by vjlomocso** [mono/SkiaSharp#747]
I need to do pressure sensitive ink strokes from styluses like the surface pen or the apple pencil. The touch event from SkCanvasView already provides the device type (pen, mouse) and the touch action (pressed, moved) but does not show pressure info.

Since the pen device type is also provided, it would be greate if it also holds the pressure information.

Maybe even just a way to override the renderers to add more touch info will be great.

> VS bug [#770233](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/770233)

**Comment by mattleibow** [comment]
This is actually quite a good feature to add.

The platforms that I know have pen support include:
 - Android (eg: SPen)
 - iOS (eg: Apple Pencil)
 - UWP (eg: Surface Pen)

Are there are other pens for the other platforms? My greatest fear is that Android has custom pen APIs for each vendor...

**Comment by vjlomocso** [comment]
You can add Google's Pixelbook Pen to that. The pen is becoming more common.
I saw a new common pen API for android starting Marshmallow. If there are custom SDKs, maybe they're for specific features. Like not all pens have erasers. Or the same number of buttons. Though the Marshmallow API does have up to three buttons.

> For apps targeting Android 6.0 (API level 23), the getButtonState() method returns BUTTON_STYLUS_PRIMARY when the user presses the primary stylus button. If the stylus has a second button, the same method returns BUTTON_STYLUS_SECONDARY when the user presses it. If the user presses both buttons simultaneously, the method returns both values OR'ed together (BUTTON_STYLUS_PRIMARY|BUTTON_STYLUS_SECONDARY).

**Comment by mattleibow** [comment]
Thanks for this info!

**Comment by mattleibow** [comment]
This was added in v1.68.3
