### ISSUE TITLE
[FEATURE] Support webassembly using CanvasKit

### ISSUE THREAD

**Issue by EydenJones** [mono/SkiaSharp#750]
I'm using SkiaSharp now with great success in my Xamarin Forms application.
I would like to dip into Blazor for the same project so I also need a Canvas-like control. While i probably could use javascript interops to the html canvas, it would be great to also have Skia here.
I've recently seen that Skia already supports webassembly, see link: [skia canvaskit](https://skia.org/user/modules/canvaskit
)
Would it be hard to use this to have a SkiaSharp.Web implementation?

Kind regards

> VS bug [#770225](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/770225)

**Comment by EydenJones** [comment]
Has there been an update since? I've seen Uno has made a lot of progression.
https://platform.uno/skiasharp-support-for-webassembly-via-uno-platform/
Are they still plans to have an official release that i'll be able to embed in Client side Blazor (perhaps with a little tutorial :) )

**Comment by baskren** [comment]
FWIW: interesting in using this with Ooui.Forms

**Comment by GeorgeS2019** [comment]
How will the skiasharp be available for Blazor?  Currently there is an option of Canvas2D and WebGl JSinterop as Blazor Extension. Can someone discuss how the UNO skiasharp for webassembly accessible through XAML (UWP) could be modified or adapted to be used as part of Blazor Extension?  The discussion here focuses on skia canvaskit webgl accessible through javascript.  

Is writing a Blazor extension (as above) with WebGL Canvaskit jsinterop the right way to go? if not, how will Skiaharp with canvaskit ported as requested here be integrated into Blazor?

**Comment by isc30** [comment]
If the question is how should we standardize canvas drawing through C#, webgl is always the best alternative in terms of portability. If the idea is to expose an API that simplifies this, skia might not be as performant as an specific canvas 2d api wrapper

**Comment by mattleibow** [comment]
https://github.com/mono/SkiaSharp/issues/1219

**Comment by mattleibow** [comment]
Closing this issue as CanvasKit is not what we are going to do to achieve web assembly support. We are going to be looking at a native implementation.
