### ISSUE TITLE
1.68.0 libSkiaSharp not copied when published WPF

### ISSUE THREAD

**Issue by Etruscian** [mono/SkiaSharp#751]
**Description**
When running this project in debug or release, behavior is as expected. When published, libSkiaSharp.dll is nowhere to be found. I've tried all solutions I could find on github but none seemed to work. I'm using the NuGet package.

**Code**
Code included in zip.

**Expected Behavior**
On launch, the application creates a pdf on your desktop with two pages, both stating ...PDF...
Then it displays a window plotting a red rectangle.
When the window is closed, the pdf is deleted.

**Actual Behavior**
An exception is caught and displayed in a messagebox: "Unable to load DLL 'libSkiaSharp': The specified module could not be found. (Exception from HRESULT: 0x8007007E).

After clicking OK on the messagebox, the window is shown with the red rectangle. The file is never created.

**Basic Information**

- Version with issue:  1.68.0
- Last known good version:  -
- IDE: Visual Studio
- Platform Target Frameworks: 
  - WPF: 4.7.1
- Target Devices:
  - Windows desktop

[WpfApp1.zip](https://github.com/mono/SkiaSharp/files/2737431/WpfApp1.zip)

**Comment by mattleibow** [comment]
Closing this as a duplicate of #1327

**Comment by mattleibow** [comment]
Fixed in #1342 and on the preview feed as v2.80.0-preview.20
