### ISSUE TITLE
[QUESTION]  - What is skia's SkPDFBitmap or SkPDFImage equivalent int SkiaSharp?

### ISSUE THREAD

**Issue by 1saeedsalehi** [mono/SkiaSharp#757]
i am looking for a way to convert SkDocument to an image 
it seems there is no equivalent class for SkPDFBitmap in skiasharp?

does anyone have idea?  or any recommendation for converting SkDocument  to an SkBitmap

**Comment by mattleibow** [comment]
`SkPDFImage` was removed in 2014 I believe and `SkPDFBitmap` does not appear to be a sanctioned public API (these typically have the `SK_API` "modifier"). But, this might not be useful in the general sense as it is basically just a set of helper methods for when an image is draw to the PDF.

If you want to create a PDF document, use `SKDocument`. At this time SkiaSharp does not support loading PDFs.

I would ask on the Google forums (https://groups.google.com/forum/#!forum/skia-discuss) as they will know of all the secrets. They will either be able to point out the types (which I can expose if not already) or give any indication if this will be supported or not.
