### ISSUE TITLE
Unable to create typeface for univers-45-light font

### ISSUE THREAD

**Issue by selvarathinamm** [mono/SkiaSharp#762]
**Description**

I tried to create font face by passing the fontfamily name "Univers 45 Light" but skiasharp is creating some other typeface instead of "Univers 45 Light".

**Code**

SKTypeface typeface = SKTypeface.FromFamilyName("Univers 45 Light", SKTypefaceStyle.Normal)

**Expected Behavior**

Typeface should be created for "Univers 45 Light".

**Actual Behavior**

Typeface should be created for "Segoe UI".

**Basic Information**

- Version with issue:  1.59.3
- IDE:  Visual Studio

Additional Info.

I compared the behavior of GetFontFamilies() API in the SKFontManager with the FontFamily.Families property in GDI+.

Please find the fonts list returned by both GDI+ and SkiaSharp in same machine.
[Skia_getfonts.txt](https://github.com/mono/SkiaSharp/files/2768577/Skia_getfonts.txt)
[GDI_getfonts.txt](https://github.com/mono/SkiaSharp/files/2768578/GDI_getfonts.txt)

On further analyzing I found that "Univers 45 Light" is available as "Univers 45".  

Is there a way to get typeface by passing "Univers 45 Light" just like GDI+?

Font installed in system.
[univers-45-light.zip](https://github.com/mono/SkiaSharp/files/2768575/univers-45-light.zip)

**Comment by mattleibow** [comment]
Ah, this issue. It is almost certainly this one: https://github.com/mono/SkiaSharp/issues/682

You can get the light font by requesting it explicitly:

```csharp
var typeface = SKTypeface.FromFamilyName(
    "Univers 45", SKFontStyleWeight.Light, SKFontStyleWidth.Normal, SKFontStyleSlant.Upright);
```

https://docs.microsoft.com/en-us/dotnet/api/skiasharp.sktypeface.fromfamilyname?view=skiasharp-1.59.3#SkiaSharp_SKTypeface_FromFamilyName_System_String_SkiaSharp_SKFontStyleWeight_SkiaSharp_SKFontStyleWidth_SkiaSharp_SKFontStyleSlant_

I am going to close this one as a duplicate, but feel free to re-open if this doesn't solve your issue.

**Comment by VijayRM** [comment]
The provided solution not working for **TraditionSansXLight** font. Please find the example code.

`SKTypeface.FromFamilyName("TraditionSansX", SKFontStyleWeight.Light, SKFontStyleWidth.Normal, SKFontStyleSlant.Upright); //Not working.`

The above code creates the typeface for "Segoe UI", whereas if we specify the full name of the font then the type face created as expected.

`SKTypeface.FromFamilyName("TraditionSansXLight", SKFontStyleWeight.Light, SKFontStyleWidth.Normal, SKFontStyleSlant.Upright); // Working`

Could you please provide your suggestions ?

**Comment by Gillibald** [comment]
Your font has the name TraditionSansXLight so this is expected. The above issue was related to automatically resolving the font weight by name. Like `FontName Light` or `FontName Bold`

**Comment by VijayRM** [comment]
Then why can't we use below method for "Univers 45 Light" font?

`SKTypeface.FromFamilyName("Univers 45 Light", SKFontStyleWeight.Light, SKFontStyleWidth.Normal, SKFontStyleSlant.Upright);`

We need a common solution for all the fonts. Which approach is best to create type face for following fonts.

- Univers 45 Light
- TraditionSansXLight

**Comment by Gillibald** [comment]
That font's family name is "Univers 45" and you want to use the light variant. Just call SKTypeFace.FromFamilyName("Univers 45", SKFontStyleWeight.Light, SKFontStyleWidth.Normal, SKFontStyleSlant.Upright)

**Comment by VijayRM** [comment]
I think, we must use separate logic to create typeface for these fonts (Univers 45 Light & TraditionSansXLight)

```
SKTypeFace.FromFamilyName("Univers 45", SKFontStyleWeight.Light, SKFontStyleWidth.Normal, SKFontStyleSlant.Upright)
SKTypeface.FromFamilyName("TraditionSansXLight", SKFontStyleWeight.Light, SKFontStyleWidth.Normal, SKFontStyleSlant.Upright);
```

I have used below code to achieve this. Please let me know, if you have any other solution.

```
string fontName = "TraditionSansXLight"; //Or "Univers 45 Light",etc.
SKTypeface typeFace = SKTypeface.FromFamilyName(fontName, SKFontStyleWeight.Light, SKFontStyleWidth.Normal, SKFontStyleSlant.Upright);
if(typeFace.FamilyName != fontName && fontName.Contains("Light"))
{
        fontName = fontName.Replace("Light", string.Empty).Trim();
        typeFace = SKTypeface.FromFamilyName(fontName, SKFontStyleWeight.Light, SKFontStyleWidth.Normal, SKFontStyleSlant.Upright);
}
```

**Comment by selvarathinamm** [comment]
Instead of replacing "Light" try replacing " Light". This might be a better solution.

**Comment by JackPaul3413** [comment]
Hi,

"Instead of replacing "Light" try replacing " Light". This might be a better solution." - this logic works for "Univers 45 Light" this type of font, but for font name of "FrutigerNext LT LightCn", if i remove 
" Light" means i will have the font name of "FrutigerNext LT Cn" so this name is invalid, how to resolve this issue?
 it would be so much appreciable if someone could help.
