### ISSUE TITLE
[BUG] Grayscale font

### ISSUE THREAD

**Issue by rozaxe** [mono/SkiaSharp#763]
**Description**

I tried drawing a text using [Gilbert](https://www.typewithpride.com) font ([OpenType SVG](https://www.colorfonts.wtf)) but the result is gray-scaled instead of colored. When tried with Xamarin.Forms' Label, the text is rendered properly.

**Code**

```cs
var paint = new SKPaint
{
                IsAntialias = true,
                TextAlign = SKTextAlign.Center,
                TextSize = 32,
                Typeface = SKTypeface.FromFamilyName("Gilbert Color")
};
canvas.DrawText("Hello", coord, paint);
```

**Expected Behavior**

The expected result is the same as using Xamarin.Forms :
<img width="121" alt="capture d ecran 2019-01-17 a 18 39 19" src="https://user-images.githubusercontent.com/3525604/51337770-4c54a180-1a88-11e9-87b2-49a1ebba8c5c.png">

**Actual Behavior**

When drawing with SkiaSharp :
<img width="115" alt="capture d ecran 2019-01-17 a 18 40 25" src="https://user-images.githubusercontent.com/3525604/51337794-5bd3ea80-1a88-11e9-95b1-b1f9e542eb33.png">

**Basic Information**

- Version with issue:  1.68
- IDE:  Visual Studio for Mac
- Platform Target Frameworks:
  - macOS:  10.14

**Comment by mattleibow** [comment]
I asked about this on the skia forums, and I hope to get an answer: https://groups.google.com/forum/#!topic/skia-discuss/5qiMEM40o50
