### ISSUE TITLE
[BUG] SKRegion.Intersects() causes Access Violation and instantly crashes program

### ISSUE THREAD

**Issue by vexx32** [mono/SkiaSharp#770]
**Description**

I haven't been able to pin down the _exact_ cause, but from stepping through my code I can see that the instant the code hits a call to SKRegion's `Intersects()` method, having been passed an SKRectI to check intersection against, an access violation is reported and the entire program crashes.

**Code**

```csharp
using System;
using SkiaSharp;

namespace Test
{
    static class Extensions
    {
        public static SKRectI ToSKRectI(this SKRect rect)
        {
            return new SKRectI(
                (int)Math.Round(rect.Left),
                (int)Math.Round(rect.Top),
                (int)Math.Round(rect.Right),
                (int)Math.Round(rect.Bottom));
        }
    }

    class Program
    {
        private static SKSizeI _imageSize { get; } = new SKSizeI(4096, 2304);
        private static string[] _wordList { get; } = new[] { "hello", "darkness", "my", "old", "friend" };
        private static Random _random = new Random();
        private static string _filePath = @"C:\Test\output.svg";

        static void Main(string[] args)
        {
            SKPath wordPath = null;
            Console.WriteLine("Image size is {0}", _imageSize.ToString());

            try
            {
                using (SKRegion occupiedSpace = new SKRegion())
                using (SKPaint brush = new SKPaint())
                using (SKFileWStream streamWriter = new SKFileWStream(_filePath))
                using (SKXmlStreamWriter xmlWriter = new SKXmlStreamWriter(streamWriter))
                using (SKCanvas canvas = SKSvgCanvas.Create(SKRect.Create(_imageSize), xmlWriter))
                {
                    brush.Color = SKColors.Black;
                    foreach (string word in _wordList)
                    {
                        bool next = false;

                        brush.TextSize = _imageSize.Height / (10 * (Array.IndexOf(_wordList, word) + 1));
                        for (float x = 0; x <= _imageSize.Width; x += (float)_random.NextDouble() * _imageSize.Width / 100)
                        {
                            for (float y = 0; y <= _imageSize.Width; y += (float)_random.NextDouble() * _imageSize.Width / 100)
                            {
                                wordPath = brush.GetTextPath(word, x, y);
                                if (!occupiedSpace.Intersects(wordPath.Bounds.ToSKRectI()))
                                {
                                    Console.WriteLine("Found space for word {0} at {1}", word, wordPath.Bounds.Location);
                                    canvas.DrawPath(wordPath, brush);
                                    using (SKRegion wordRegion = new SKRegion())
                                    {
                                        wordRegion.SetRect(SKRectI.Create(_imageSize));
                                        wordRegion.SetPath(wordPath);
                                        occupiedSpace.Op(wordRegion, SKRegionOperation.Union);
                                        next = true;
                                    }
                                }

                                if (next) break;
                            }

                            if (next) break;
                        }
                    }

                    // All words written, tidy and ensure file is saved
                    canvas.Flush();
                    streamWriter.Flush();
                }
            }
            finally
            {
                wordPath?.Dispose();
            }

            Console.WriteLine("Drawing complete; press Enter to exit");
            // Wait for exit
            Console.ReadLine();
            Environment.Exit(0);
        }
    }
}
```

**Expected Behavior**

Program will loop through the word list, attempting to draw each in turn. Console should output found positions as it progresses, and eventually an SVG file would be output at the specified location.

**Actual Behavior**

Program progresses through the first loop and then instantly closes silently. If the application is debugged, an access violation will be reported when the `Intersects()` method is called.

**Basic Information**

- Version with issue:  1.68.0
- Last known good version:  unknown if this ever worked
- IDE:  Visual Studio Code
- Platform Target Frameworks: 
  - Windows Classic:  Windows 10
- Target Devices:   
  - PC

**Reproduction Link**

https://github.com/vexx32/PSWordCloud/tree/Cmdlet/Cmdlet

The following PowerShell module attempts to use SkiaSharp to draw a word cloud. 

1. Use `dotnet publish` to compile the module DLL
2. Open a PowerShell or PowerShell Core console
3. Execute `Import-Module .\PSWordCloud.psm1` from a PowerShell console with current location at this folder in the repo: https://github.com/vexx32/PSWordCloud/tree/Cmdlet/Cmdlet
4. Execute the following command in PowerShell and watch it _burn_ :wink:

```powershell
"Hello darkness my old friend","I've come to talk with you again" | New-WordCloud -Path $env:TEMP\test.svg
```

5. Observe the _entire PowerShell application_ crash due to the access violation without warning.

Elsewhere in the repo you can find working code (check the latest release) written in PowerShell utilising System.Drawing for the same task and example pictures and commands to do the same with the published version of the module.

**Comment by mattleibow** [comment]
Thanks for the detail. I will investigate and get this fixed as soon as possible. Just been flying around and talking at our local #MSIgniteTheTour

**Comment by vexx32** [comment]
Thanks, much appreciated! 😄 

Have fun! ^^

**Comment by vexx32** [comment]
@mattleibow I'll give that a shot and see if it works. Thank you!

**Comment by mattleibow** [comment]
I also just wanted to let you know about some cool methods that you can use - not as cool as the extension method, but we do have `Round`, `Ceiling`, `Floor` and `Truncate` that can be used like this:

```csharp
SKRect floatRect = ...;
SKRectI intRect = SKRectI.Round(floatRect);
```

https://docs.microsoft.com/en-us/dotnet/api/skiasharp.skrecti.round?view=skiasharp-1.68.0#SkiaSharp_SKRectI_Round_SkiaSharp_SKRect_

**Comment by vexx32** [comment]
@mattleibow Thank you for the prompt response!

I recompiled my original version just using regions instead of rectangles and it does seem much more stable.

Interestingly, this doesn't actually seem to detect collisions all that well. ([example](https://www.dropbox.com/s/i2xp0kx4xe7kd5z/paterson.test.svg?dl=0))

I'll have to see if I can figure out whether that's my own code here or the Intersects() method once again... similar code does work with the System.Drawing intersection testing methods, though.

Once again, thank you! Small progress is progress. 😄

**Comment by mattleibow** [comment]
Good to hear things are just exploding. If you get more information, just open a new issue with any deets!
