### ISSUE TITLE
SkBitmap.GetPixel crashes occasionally

### ISSUE THREAD

**Issue by roceh** [mono/SkiaSharp#79]
I'm getting a SIGSEGV occasionally when calling SKBitmap GetPixel, does it it need a SkAutoLockPixels statement before the getColor method is called? All other access to pixels seems to require that looking at the c api.

**Comment by migueldeicaza** [comment]
Please provide a test case, not clear if this is a bug in your code or in Skia.

**Comment by roceh** [comment]
I'm having problems duplicating this, so it could have been an issue with my code.

**Comment by migueldeicaza** [comment]
Closing until we get this data.
