### ISSUE TITLE
Does Skia or SkiaSharp run on Console Platforms, like PS4 or XBOX 360 [QUESTION] 

### ISSUE THREAD

**Issue by ryancheung** [mono/SkiaSharp#803]
Does Skia or SkiaSharp run on Console Platforms, like PS4 or XBOX 360 [QUESTION]

**Comment by entdark** [comment]
It will definitely work on XBOX One (not XBOX 360), since UWP apps are supported there.

**Comment by mattleibow** [comment]
SkiaSharp might work on PS4. I don't think anyone has done any testing in this area though. The native library is very flexible and runs on most platforms today, so you might be able to try a few things if you use the correct SDKs and libraries.

**Comment by mattleibow** [comment]
Closing this as there has been no further comments. If anyone has any further questions on PS4 libraries/games, then feel free to open another issue.
