### ISSUE TITLE
Save as PNG, where to set DPI ?

### ISSUE THREAD

**Issue by TomQv** [mono/SkiaSharp#804]
I'm using this code to render a svg into a png of a specific size. The png is then used as a toolbar-button image in a WPF app. 

Unfortunate the resulting png doesn't have the dpi-tag set properly and I also didn't find a way to set a value.  It should be set to the current Windows screen-resolution to prevent additional scaling from Windows. But where or how?

```

public static byte[] SvgToPngBytes(Stream svgfilestream, int size)
{
	var svg = new SkiaSharp.Extended.Svg.SKSvg();
	svg.Load(svgfilestream);

	var ii = new SKImageInfo(size, size);
	using (var newSurface = SKSurface.Create(ii))
	{
		using (var canvas = newSurface.Canvas)
		{
			canvas.Clear(SKColors.Transparent);

			// calculate the scaling need to fit to size
			float scalew = size / svg.CanvasSize.Width;
			float scaleh = size / svg.CanvasSize.Height;
			var scale = Math.Min(scalew, scaleh);
                        // scale and center in size
			var matrix = SKMatrix.MakeScale(scale, scale);
			matrix.TransX = (size - svg.CanvasSize.Width * scale) / 2;
			matrix.TransY = (size - svg.CanvasSize.Height * scale) / 2;

			canvas.DrawPicture(svg.Picture, ref matrix);
			canvas.Flush();

			// https://stackoverflow.com/questions/48372772/saving-canvas-to-device-memory-in-xamarin-forms
			var data = newSurface.Snapshot();
			var pngImage = data.Encode();
			using (var ms = new MemoryStream())
			{
				pngImage.SaveTo(ms);
				return ms.ToArray();
			}
		}
	}
}

```

**Comment by neodynamic** [comment]
https://forums.xamarin.com/discussion/102644/skbitmap-and-dpi

**Comment by mattleibow** [comment]
Thanks for responding @neodynamic. I believe that this is still the case:
> Well, I'm already scaling the bitmap to simulate the dpi resolution but the problem here is that setting should be stored in the output png image file itself which is useful for printing purposes. Looking at the web, it seems that PNG spec supports it http://www.libpng.org/pub/png/spec/1.2/PNG-Chunks.html#C.pHYs
> I'll try change those bytes through code after getting the byte array from Skia codec. By the way, it seems that Skia does not support it https://groups.google.com/forum/#!searchin/skia-discuss/dpi|sort:relevance/skia-discuss/nY4tLHvjkVs/8vcioy_e8z4J

I am closing this as "not supported" until skia gets a feature to do this.
