### ISSUE TITLE
[QUESTION] Animation buggy with SKGLView

### ISSUE THREAD

**Issue by Al3xlab** [mono/SkiaSharp#805]
I animate a simple path in Xamarin.Forms SKCanvasView and SKGLView, but the rendered images are buggy with SKGLView:
**On SKCanvasView (expected animation):**
![gif1](https://user-images.githubusercontent.com/48130657/53746776-39642800-3ea2-11e9-9dfa-4f3b607e5198.gif)
**On SKGLView (chaotic animation):**
![gif2](https://user-images.githubusercontent.com/48130657/53746807-441ebd00-3ea2-11e9-8f39-c9d95f349263.gif)

The results are the same under UWP and Android (same code).
What am I doing wrong ? Thanks for your help.

**Comment by entdark** [comment]
According to the fact you are using `SKCanvasView` I'd assume you are using some external timer to invalidate the surface from time to time.
It does not work like that in `SKGLView`.

To count animation correctly you suppose to use something like that:
https://github.com/mono/SkiaSharp/issues/533#issuecomment-392337956
You can work with `ElapsedMilliseconds` instead for more precise updates.

Just compare expected time and elapsed and if the elapsed time passed then apply the new rotation. But it's better to use some interpolation functions actually.

`SKGLView` does not need invalidation, it updates itself each frame, and you have to recount your view on each frame all the time.

**Comment by Al3xlab** [comment]
@entdark : my `SKGLView `is configured with `HasRenderLoop = false;` and the result is identical with 1FPS.
 Always image glitches in `SKGLView `(and the rotation is never centered):
![glitch](https://user-images.githubusercontent.com/48130657/53754042-06766000-3eb3-11e9-9401-f90a7b822339.jpg)

In meantime, i've changed the transformation method for the draw path. On my previous animations, it was (for each frame):
```
path.Transform(matrix);// matrix is defined with centered rotation
canvas.DrawPath(path, paint);
path.Transform(invertMatrix);// restore original path
```
And for the new animation below (identical with `SKCanvasView ` and `SKGLView`):
![gif](https://user-images.githubusercontent.com/48130657/53754512-720cfd00-3eb4-11e9-9f24-7614a28cd679.gif)
```
// path.Transform() replaced with canvas.SetMatrix()
canvas.Save();
canvas.SetMatrix(matrix);
canvas.DrawPath(path, paint);
canvas.Restore();
```
No more glitches but the path is deformed (`StrokeWidth != 1`).
So, what's the problem with `path.Transform()` ?

**Comment by Al3xlab** [comment]
I may have found a bug with `SKPath.Transform()` when drawing on `SKGLView`.
I close this comment and open a bug report...

**Comment by mattleibow** [comment]
Did you open a bug so we can track it?

**Comment by mattleibow** [comment]
Is this you? This looks to be the issue: https://groups.google.com/forum/#!topic/skia-discuss/pMbOWNz5ihs

**Comment by Al3xlab** [comment]
No, I didn't open a bug report, because the problem is gone and I don't know why !?
