### ISSUE TITLE
Is it possible to create bezier curves

### ISSUE THREAD

**Issue by sylendra7** [mono/SkiaSharp#813]
Hi is it possible to draw a bezier curves using SkiaSharp...?

I want to create the view using using skiasharp which is like in the image...
want exact same like in the image where I want to place an image on top of the Bezier curve

<img width="371" alt="Screen Shot 2019-03-16 at 2 28 20 AM" src="https://user-images.githubusercontent.com/15817571/54461737-7cbc7180-4793-11e9-9bc3-5aae6cb10bd9.png">

**Comment by patrik-gustavsson** [comment]
It is possible to draw cubic bezier curves with SKCanvasView or SKGLView by using SKCanvas.DrawPath. See https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/graphics/skiasharp/curves/ for further information. I have provided a simple example for your case:

```
private SKPaint paint = new SKPaint() {
    Color = SKColor.Parse("#4EB4F9"),
    ImageFilter = SKImageFilter.CreateDropShadow(0, 1, 0, 100, SKColors.Gray, SKDropShadowImageFilterShadowMode.DrawShadowAndForeground)
};

private void SKCanvasView_PaintSurface(object sender, SkiaSharp.Views.Forms.SKPaintSurfaceEventArgs e)
{
    SKSurface surface = e.Surface;
    SKCanvas canvas = surface.Canvas;
    canvas.Clear(SKColors.White);

    float width = 1200;
            
    SKPath bezierPath = new SKPath();
    bezierPath.MoveTo(0, 0);
    bezierPath.LineTo(0, 600);
    bezierPath.CubicTo(400, 700, width - 400, 300, width, 200);
    bezierPath.LineTo(width, 0);
    bezierPath.LineTo(0, 0);
    bezierPath.Close();
    canvas.DrawPath(bezierPath, paint);
}
```
Result:
![Result](https://user-images.githubusercontent.com/20979157/54491213-e3897a00-48bc-11e9-99ef-097481755b21.jpg)

**Comment by sylendra7** [comment]
Hi @patrik-gustavsson ,

thanks for the reply.. Is it possible to draw an circle view in centre of the curve as shown in my pic...?


Thanks & regards
Slender

**Comment by patrik-gustavsson** [comment]
I updated the comment with code for adding the circle image as well.

**Comment by sylendra7** [comment]
Thank you very much @patrik-gustavsson
