### ISSUE TITLE
Getting SkiaSharp to work with open shift container. 

### ISSUE THREAD

**Issue by wario2k** [mono/SkiaSharp#814]
I am currently trying to get Skiasharp to work on an openshift container that was provided to me. There are certain restrictions placed on the container and because of that I do not have the rights to change the image at all and hence I cannot add any additional configurations to it. The problem that I have been running into seems to be that I keep getting the dll not found issue and the only workaround
![error](https://user-images.githubusercontent.com/11401905/54687224-70b51480-4af1-11e9-9935-a1b9682d2a39.PNG)
 recommended in the forums was including the .so, which I did and I still seem to be getting the same issue. 
There also seems to be some additional dependency on libfontconfig but I have no way of installing that on my container because of the restrictions placed on it. Is there any viable solution that you could suggest? 
Any help would be greatly appreciated.

**Comment by wario2k** [comment]
To anyone having a similar problem @mattleibow came through with the binary. Here is a link to it:

Source: https://github.com/mattleibow/SkiaSharp-Docker/tree/no-fontconfig
Binary: https://github.com/mattleibow/SkiaSharp-Docker/raw/no-fontconfig/libSkiaSharp.so 

Once you have that integrated, the library should work as expected.

**Comment by mattleibow** [comment]
This is the PR that I will be merging soon:

https://github.com/mono/SkiaSharp/pull/821
