### ISSUE TITLE
[QUESTION] WPF native rendering over D3DImage (without WindowsFormsHost and WritableBitmap)

### ISSUE THREAD

**Issue by Mikolaytis** [mono/SkiaSharp#819]
Hi, I'm using SkiaSharp in my WPF app with WGL rendering as described here.
https://github.com/mono/SkiaSharp/issues/745 (GPU-accelerated WPF without WindowsFormsHost)

Fps of this approach is low(all performance is thrown into copy bytes to WritableBitmap), so I'm in search for another solution and found an perfect example, how to render in WPF D3DImage over OpenGL via SharpDX, Angle.
https://github.com/l3m/wpf-gles

Performance is on another level, but I'm failing to connect this example to SkiaSharp.
Is this possible at all?
Did you ever considered this type of approach for WPF apps?
If this approach will connect to skia - it will be awesome!

**Comment by Mikolaytis** [comment]
Here we go! Done: https://github.com/Mikolaytis/WpfSkiaAngleSharpDxOpenTK

**Comment by Mikolaytis** [comment]
Turns out text/line/etc. draw do not render anything, only images are rendering.

**Comment by john-cullen** [comment]
@Mikolaytis did you ever get text / lines rendering for this?

**Comment by mattleibow** [comment]
@Mikolaytis Thanks for all this work. @john-cullen I am closing to close this issue and merge it with #745 so we have one place to discuss this - and to talk solutions.

@john-cullen I think this may be because the stencil buffers aren't set up right. But let's talk in #745
