### ISSUE TITLE
skiasharp .net core razor pages

### ISSUE THREAD

**Issue by pdeman** [mono/SkiaSharp#823]
Hi,
is it possible to use skiasharp to display images in a web api .net core, for example in razor pages ?
I haven't found any example of this.
in xamarin I use this:
```
xmlns:views="clr-namespace:SkiaSharp.Views.Forms;assembly=SkiaSharp.Views.Forms">
and 
<views:SKCanvasView
```
is there an equivalent for razor pages in a Web API MVC ?

**Comment by mattleibow** [comment]
There is no control at this time, but there is nothing stopping you from just creating an image and either storing that in a cache, or using a web API endpoint.

For images displayed in a browser, you typically need the complete image stored on some server (or at least generated on the server). If the image is static, then you could potentially draw an image in memory when it is first requested, and then save it to disk for future requests.

If the image is dynamic, such as changes over time or changes per user, then you can create an API that gives the impression of a static image. This can be done by creating an API controller that returns the image bytes.

For example, you could merge or use one of these ideas. I have created an image in an Azure Function: https://github.com/mattleibow/SkiaSharpFunction/blob/master/SkiaSharpFunction/Images.cs and then created an empty Web API: https://github.com/mattleibow/SkiaSharpWebApi-Docker/blob/master/SkiaSharpWebApi/Controllers/ColorTypeController.cs. You could possible use this as a starting point.

**Comment by mattleibow** [comment]
I am closing this issue as I don't think we will ever embed the image into the HTML of the page, so a REST endpoint or cached image is the way to go.

Feel free to re-open this issue if you have any more comments on this particular question.
