### ISSUE TITLE
How to draw a circle when a button is clicked.[QUESTION] 

### ISSUE THREAD

**Issue by nakulashok** [mono/SkiaSharp#825]
I want to draw a circle only after I click a button. How can i access the canvas to draw on the click event.

**Comment by charlesroddie** [comment]
For example, on the click event, in your view mutate a parameter from false to true, and when painting to the surface (DrawInSurface or PaintSurface), draw the circle if the parameter is true.

**Comment by mattleibow** [comment]
@nakulashok Did @charlesroddie's suggestion work for you? I am closing this now as that is the correct way to achieve that goal.

**Comment by mattleibow** [comment]
I am closing this issue as it appears the question was answered.
