### ISSUE TITLE
[QUESTION] What needs to be disposed and what can be cached?

### ISSUE THREAD

**Issue by kimbell** [mono/SkiaSharp#829]
I'm looking into SkiaSharp for generating images from an ASP.NET Core back-end. 

I have some logo images that will be used multiple times. Is it possible keep references to SKImage and SKBitmap and draw the same instance onto multiple SKCanvas instances? Will I hit threading/locking issues?  

A lot of the SK* based objects implement IDisposable. Lets say I create an SKPaint and draw a line onto an SKCanvas. Do I have to dispose of the SKPaint, or will that happen automatically when I dispose of the SKSurface that I got the SKCanvas from?

**Comment by charlesroddie** [comment]
The API suggests that the various SKObjects are independent of SKCanvas, so there should not be a problem drawing on multiple SKSurface. For the same reason they are not disposed when any particular SKSurface is disposed, so you will need to handle disposals.

**Comment by mattleibow** [comment]
@charlesroddie is correct. The paint objects can be reused multiple times and can be cached. Typically, paints and typefaces are cached as they are data for a draw operation.

In fact, most objects can be cached, including source bitmaps/images.

Just be careful when drawing across threads, some objects are not thread safe. See this discussion: https://groups.google.com/forum/#!topic/skia-discuss/TUy0I596FlM

With regards to the IDisposable, the GC will automatically dispose of the object when they are not referenced anymore, but you can make sure they get disposed sooner by calling Dispose yourself. For restricted devices (such as mobile), disposing objects sooner avoids a larger GC collection.
