### ISSUE TITLE
Crash in SkManagedSkStream when running in multiple threads

### ISSUE THREAD

**Issue by agallero** [mono/SkiaSharp#83]
Hi,

I've been running some stress testing with the SkiaSharp backend, but I am consistently getting exceptions or out of memory conditions. Those are not reproducible, and sometimes the tests run all correctly, but they do happen a lot.

The main issue seems to be with SkManagedStream. I get many "ObjectDisposed" exceptions in AsManagedStream:
![Object disposed Exception](http://www.tmssoftware.biz/flexcel/img/objectdisposed.png)

And also NullExceptions in the SkManagedStream constructor:
![Object disposed Exception](http://www.tmssoftware.biz/flexcel/img/nullexception.png)

Note that in the image above both "this" and "ManagedStreams" are not null.

It is not something that reproduces always, so I can't really provide an automated test, but the following code triggers both exceptions here about 50%  of the times:

``` c#
using SkiaSharp;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading;
using System.Threading.Tasks;

namespace ConsoleApplication2
{
    class Program
    {
        static void Main(string[] args)
        {
            Random rnd = new Random();
            Parallel.For(0, 100, 
            (i)=> {
                OpenImage();
                Thread.Sleep(rnd.Next(100));
            });
            Console.WriteLine("ok!");
        }

        private static void OpenImage()
        {
            using (Stream imgStream = new FileStream(@"R:\tests\WriteBmp\extractedshadow1.png", FileMode.Open, FileAccess.Read, FileShare.ReadWrite))
            {
                using (SKManagedStream aSKManagedStream = new SKManagedStream(imgStream))
                {
                    SKBitmap.Decode(aSKManagedStream);

                }
            }
        }
    }
}

```

In the code above,the image is just an small png, but it should happen with any image. (note that larger images might need a larger Sleep() call so there are more probabilities of crashing.
Just so you can reproduce the test, the image I used is here:
http://www.tmssoftware.biz/flexcel/img/extractedshadow1.png

From what I see in the code, it seems that managedStream is a static dictionary (so it is shared among all threads):

``` c#
        private static readonly Dictionary<IntPtr, WeakReference<SKManagedStream>> managedStreams = new Dictionary<IntPtr, WeakReference<SKManagedStream>>();

```

But there doesn't seem to be any lock or critical sections if 2 threads want to set different values to the dictionary at the same time.

I don't really know the internals of the code and why the design choices, but I am also not sure about the choice of a WeakReference here: isn't a WeakReference supposed to be collected even if the object is still referenced? If that is the case, the code:

``` c#
        private static SKManagedStream AsManagedStream(IntPtr ptr)
        {
            SKManagedStream target;
            if (AsManagedStream (ptr, out target)) {
                return target;
            }
            throw new ObjectDisposedException ("SKManagedStream: " + ptr);
        }

```

Could return null if the object was collected (and so set to null), but the callers of AsManagedStream don't seem to check for null and try to recreate the object if it was collected.

**Comment by migueldeicaza** [comment]
Thanks for reporting this issue!

This should be fixed now.

**Comment by ncthbrt** [comment]
This seems to have returned in dotnet core

**Comment by mattleibow** [comment]
Are you able to provide a test case that I can use to get some stacktrace, or some sort of test.

**Comment by ncthbrt** [comment]
This repo https://github.com/ncthbrt/skia-fsharp reliably crashes out when run and browsing to `http://localhost:5000/api/test/1234/image.png` . It doesn't crash when this line: https://github.com/ncthbrt/skia-fsharp/blob/master/Drawing/Test.fs#L187 is commented out

I've tried a large number of permutations including locking the decoder thread, loading the image as a byte array, using the file path overload, etc.

**Comment by mattleibow** [comment]
Moving to the next release so we can get the new skia out.

**Comment by mattleibow** [comment]
I believe this is the more specific issue: #376

**Comment by mattleibow** [comment]
Closed with the merge of https://github.com/mono/SkiaSharp/pull/386
