### ISSUE TITLE
[QUESTION] Why is SKFontMetrics Leading property sometimes 0?

### ISSUE THREAD

**Issue by washamdev** [mono/SkiaSharp#831]
We have a graphical editor in the browser running Fabric.js, and once editing is complete, we send the raw layout data to our server and use SkiaSharp to interpret the data and draw the image on the server. This works great in almost all circumstances, but one huge problem we've run into is outputting multi-line text. We figured out a way to calculate line height and separate lines of text with that amount of space, but we have run into more and more scenarios where certain custom fonts (TTF or OTF) used in the image don't have a `Leading` property when we try to calculate the line height from the `SKFontMetrics` of the font file. I can't tell any rhyme or reason to this... it's just that some fonts have the `Leading` property, and some don't. The ones that don't are impossible to correctly calculate the line height, which is ruining our solution.

Does anyone have any idea why certain fonts wouldn't have the `Leading` property set on the font's `SKFontMetrics`? The strange thing is that Fabric.js is able to load in the custom font and draw it perfectly, with the right line height. But then it goes to the server, and it's like SkiaSharp can't interpret the font metrics correctly or something.

I posted this question on [StackOverflow](https://stackoverflow.com/questions/53122732/why-is-skfontmetrics-leading-property-sometimes-0) months ago, but received no answers, so if anyone here can answer or if anyone here wants to answer there (and I'll mark it as the correct answer, if it's helpful), we would appreciate it. Thanks!

**Comment by Gillibald** [comment]
Looks like you are calculating the line height wrong. Having a leading of zero is just normal.

`Size = new SKSize(width, descent - ascent + leading);`
`BaselineOrigin = new SKPoint(xOrigin, -ascent);`

**Comment by washamdev** [comment]
@Gillibald I'm not sure I'm entirely following. Here's a bit more detail:

From FabricJs, they pass in a "lineHeight" property, which defaults to 1.16. Looks like what we've been doing is calculating the line height by starting with `fontSize` x `lineHeight`, but then that wasn't giving us the right amount of space between lines. So we then went to using the `SKFontMetrics` to try to get the correct line height by using the `leading` and `ascent` of the font file. It's entirely possible those are the wrong values to use. Do you have any idea how to put together what you suggested with what we have to work with? (e.g. the font size, like `24`, and the line height, like `1.16`, then any `SKFontMetrics` from the font?)

**Comment by Gillibald** [comment]
`SKFontMetrics` always has the scales values of ascent, descent and leading. So before drawing you just set the appropriate TextSize and you should get the right value.

When drawing text you always start from the baseline. So the line height is the sum of | ascent | + | descent | + | leading |

If you have multiple fonts in one line you have to calculate the highest values of those 3.

**Comment by washamdev** [comment]
@Gillibald Really appreciate your expertise here and the in-depth information. I think where I'm continuing to struggle is taking what Fabric.js gives me and trying to use it in SkiaSharp to make it look the same. It's just not working out.

For instance, I just cannot figure out how Fabric.js is measuring text to output what it does. See this screenshot:

![image](https://user-images.githubusercontent.com/4692325/56942329-a3cec880-6adf-11e9-991b-405872766e76.png)

The font size is 16. From the `top` point of the bounding box to the baseline of the first line of text, it's 16 pixels. The line height is 1.16. But measuring from the first baseline to the next baseline is.... 21 pixels? If the distance between lines of text is `fontSize` * `lineHeight`, then the distance should be 18.56. So where is Fabric.js getting the extra 2.44 pixels? And how do I calculate the same 21 pixel line height in SkiaSharp to copy what Fabric.js is doing?

Thanks so much for any further shedding of light you can provide!

**Comment by Gillibald** [comment]
I don't think you can compare Fabric.js's lineheight definition with SkiaSharp's way of rendering text. The lineheight isn't just the maximum height of all glyphs rendered. I guess they don't use the actual data that the font editor supplied. The only way I see to make this work is positioning all glyphs that SkiaSharp should render yourself and somehow find out how the distance between lines is calculated by Fabric.js

SkiaSharp follows the spec and Fabric.js don't.

**Comment by washamdev** [comment]
@Gillibald I will submit a message to the developer of Fabris.js and see if he can provide any insight. Thank you again!
