### ISSUE TITLE
Getting the message "Not replacing existing, living, managed instance with new object."

### ISSUE THREAD

**Issue by BrianHanechak** [mono/SkiaSharp#835]
I'm running locally on Windows and I find that if I run my application multithreaded, I get a lot of the debugger output:

Not replacing existing, living, managed instance with new object.

I don't seem to get this if I only run with a single thread. I haven't tracked down the reproduction any more than that yet.

The source code seems to point to this line:

https://github.com/mono/SkiaSharp/blob/master/binding/Binding/SKObject.cs#L124

But I don't yet understand when `RegisterHandle` gets called.

Is this a harmless message? Is there something I should change to prevent this from occurring?

**Comment by BrianHanechak** [comment]
Here's a small example to reproduce this:

    using System;
    using System.IO;
    using System.Linq;
    using System.Threading.Tasks;
    using SkiaSharp;

    namespace skiatest
    {
        class Program
        {
            public static byte[,] DecodeGrayscaleImage(Stream stream)
            {
                using (var data = SKData.Create(stream))
                {
                    using (var codec = SKCodec.Create(data))
                    {
                        var info = new SKImageInfo(codec.Info.Width, codec.Info.Height, SKColorType.Gray8, SKAlphaType.Opaque, SKColorSpace.CreateSrgb());
                        using (var image = SKBitmap.Decode(codec, info))
                        {
                            return Gray8ImageToBytes(image);
                        }
                    }
                }
            }

            unsafe public static byte[,] Gray8ImageToBytes(SKBitmap image)
            {
                // byte* ptr = (byte*)image.GetPixels().ToPointer();
                byte[,] data = new byte[image.Height, image.Width];
                // for (int y = 0; y < image.Height; y++)
                // {
                //     for (int x = 0; x < image.Width; x++)
                //     {
                //         data[y, x] = *ptr++;
                //     }
                // }
                return data;
            }

            static async Task<int> Main(string[] args)
            {
                var tasks = new Task[1000];

                for (int i = 0; i < 1000; i++)
                {
                    var task = new Task(() => {
                        using (var stream = File.OpenRead("sample-L.png"))
                        {
                            var img = DecodeGrayscaleImage(stream);
                        }
                    });
                    tasks[i] = task;
                    task.Start();
                }
                await Task.WhenAll(tasks);
                Console.WriteLine("done");
                return 0;
            }
        }
    }

**Comment by BrianHanechak** [comment]
@kneedels helped me track down that the object that is producing this message is the color space that's generated from `SKColorSpace.CreateSrgb()`. Even if I put this in its own using block, we still get the message. The only way I've seen to avoid it is to create the color space once before the program runs and then use the same instance for each call.

Is this a good idea? Are `SKColorSpace` objects safe to use simultaneously across threads? 

Is the message causing any actual harm, or should I just ignore it?

**Comment by MichaelRumpler** [comment]
I also get this message a lot. I don't use color spaces at all, but also multiple threads.

My app uses WPF/.NET Core 3.

A background thread writes to a invisible SKBitmap (e.g. with DrawBitmap). About 50x/sec I call InvalidateVisual() on my main SKElement. This triggers OnPaintSurface which uses DrawBitmap to draw the bitmap to the surface of the SKElement.

Currently I don't do any thread synchronization. If the background thread is not finished writing to the bitmap when OnPaintSurface is called, then it will be written to the screen the next time. This is ok for me.

**Comment by mattleibow** [comment]
I have been working on #900 to fix all these cases. The case with the color spaces was a really special one. Even though the method and the docs appear to indicate that you are getting a new instance of an object, you _may_ be getting a static object depending on the arguments.

See this PR: https://github.com/mono/SkiaSharp/pull/922
