### ISSUE TITLE
[QUESTION] Can I use SkiaSharp to draw overlays on top of PictureBox congtrol ?

### ISSUE THREAD

**Issue by boxerab** [mono/SkiaSharp#839]
The PictureBox control displays live video. I would like to display text and bounding boxes as an overlay.

**Comment by charlesroddie** [comment]
Yes should be able to, just by putting it above and making it transparent, e.g. `canvas.Clear(SKColor.Empty)`.

**Comment by boxerab** [comment]
Thanks!
