### ISSUE TITLE
Animation example using AsStream()

### ISSUE THREAD

**Issue by JimSEOW** [mono/SkiaSharp#84]
I read Miguel writing on using AsStream() to deliver animation using SkiaSharp. Could someone provide a link to codes or recipe on how to do that. A self-made Xamarin example/sample using Forms would be a GREAT help!

**Comment by horaciojcfilho** [comment]
I would love to see this too 😄

**Comment by mattleibow** [comment]
@JimSEOW do you have more information with regards to this? I know you can do basic animations by refreshing the screen as you would any game/animation engine:
```
onDraw() {
    render()
    refresh()
}
```

**Comment by JimSEOW** [comment]
I am looking for a way to use SkiaSharp to draw on UrhoSharp Texture to create a smooth dynamic texture

References
https://forums.xamarin.com/discussion/66204/using-skia-with-existing-opengl-context

**Comment by JimSEOW** [comment]
I think there is need to figure out best practice to implement smooth animation using SkiaSharp. I am curious if AsStream is a good option. If so, how to implement in async way 

Reference
https://forums.xamarin.com/discussion/61920/skiasharp-for-animation

**Comment by migueldeicaza** [comment]
This is off-topic for SkiaSharp.

SkiaSharp's sole goal is to give you a 2D drawing API, if you want to animate the results, that belongs in a higher design level.

**Comment by JimSEOW** [comment]
I am in discussion with people using SkiaSharp to implement cross platform WPF's XAML. It will be of interest to the community to understand how to best use SkiaSharp different 2D drawing API capabilities to implement SkiaSharp as backend for higher design such as e.g. cross platform WPF.
