### ISSUE TITLE
missing method: "SKPathOps::AsWinding"

### ISSUE THREAD

**Issue by deakjahn** [mono/SkiaSharp#840]
There is a newer method AsWinding() in:

https://github.com/google/skia/blob/master/include/pathops/SkPathOps.h

It's supposed to help with the even-odd vs. winding problems in Boolean path operations. It would really be needed from SkiaSharp as well...

**Comment by Gillibald** [comment]
This is not part of the m68 release so it will only be available if a newer release is targeted

**Comment by deakjahn** [comment]
Well, considering that the whole Path Ops subsytem is nearly unusable because of that (of course, it also depends on which filling rule you actually need), what are our hopes?

**Comment by deakjahn** [comment]
To put it into some perspective: it seems that no matter what kind of paths you send into the operations, it always comes out in even-odd. This is the function that they added to fix it if you need it in non-zero (winding). Without the function, you simply can't work in non-zero mode at all because you can input but you can't use the output at all. And a rather large part of the world (fonts, PostScript, PDF and so on) uses the non-zero mode.

**Comment by mattleibow** [comment]
Thanks for brining this out, I am hoping to update to the latest skia soon, so we will get this method. I can't say exactly when, but I hope before the end of this year.

**Comment by corliss** [comment]
Hi, we're another user affected by this issue and other related bugs which have been fixed a long time ago in Skia but are not available in SkiaSharp.

From the discussion above perhaps it wasn't clear that these path related fixes are actually quite critical. But we can't test the fixes unless a corresponding version of SkiaSharp is released.

Xamarin usually provides same-day availability when release builds/GMs of new OSes and frameworks become available. What is the expectation regarding drops of SkiaSharp relative to builds of Skia? It has already been 9 months since the last release, so "sometime this year" is unfortunately too painful. Could we please have a new build soon (meaning days to weeks)?

**Comment by Gillibald** [comment]
SkiaSharp has only one maintainer so it is expected to take longer. How many people are working on Skia itself?

**Comment by corliss** [comment]
> expected to take longer.

This is unfortunate. As detailed in the separate issue I opened, the regularity of builds was changed, after years, without any warning or notice to users. I certainly had no reason to "expect it to take longer."

Additionally, Skia is extremely complex to build, and therefore so is SkiaSharp. The maintainer has already released many, many builds in the past, so the incremental task of releasing a new build is far less for the maintainer than for anyone else. Plus, few people have all the devices needed to produce & test a cross-platform nuget, if that is what you're asking. IMHO this is not a good candidate for community contributions, unless the contributor happens to be a well-resourced company.

**Comment by Gillibald** [comment]
It is totally fine to start with all the Windows dependencies and add other platforms later. The build chain to compile everything is part of the repro so you only have to supply all dependencies that are needed to build for your target platform. On Windows this is mainly msbuild (VisualStudio).

The moment you create a pull request you can use DevOps to build for all platforms.

I am contributing to SkiaSharp myself and haven't had any issues building everything I need. This is all done in my free time.

The community can help bringing this project further.

**Comment by mattleibow** [comment]
At least m80 has this feature and it can be added.
