### ISSUE TITLE
[QUESTION] Can I use Custom Pixel Shaders with SkiaSharp?

### ISSUE THREAD

**Issue by mxjones** [mono/SkiaSharp#841]
Hi,

I have had a search around for similiar issues but couldn't see anything - apologies if this *is* already somewhere or this is the wrong place to ask!

I am playing around with SkiaSharp a little bit (some basic porting of WPF graphics library so far) and one of the bits that I can't see how to do is being able to use a custom pixel shader (eg. HLSL/GLSL shader) - Is this something that is possible in Skia(sharp)? 

**Some background:**
In WPF I am using the base 'ShaderEffect' functionality, and HLSL shaders compiled to *.ps - Thinking of XPlatform I know would need to port these over to GLSL also, but wanted to know whether I could even use these custom shaders in SkiaSharp or if I would need to possibly re-implement the functionality from the shaders directly in SkiaSharp a different way. I've been looking at SKShader & SKColorFilter but don't see anything to pass a custom shader too

Cheers,
Max

**Comment by mxjones** [comment]
Closing this at i don't think this is currently possible

**Comment by mattleibow** [comment]
Just FYI: https://groups.google.com/forum/#!topic/skia-discuss/RWe01JHXKH8

> Skia doesn't really have support for injecting custom shaders today, but it's definitely something on our minds.  On a scale of 1 to 10, 1 being "seems like a good idea" and 10 being "totally working and recommended to use", I think we're at about a 2 today.
