### ISSUE TITLE
[QUESTION] Copy a rectangular area within a bitmap

### ISSUE THREAD

**Issue by MichaelRumpler** [mono/SkiaSharp#842]
I want to copy a rectangular area in my SKBitmap to another position. The simple approach is:

    using (var canvas = new SKCanvas(Bitmap))
    {
        var sourceRect = new SKRect(sourceLeft, sourceTop, sourceLeft + width, sourceTop + height);
        var targetRect = new SKRect(targetLeft, targetTop, targetLeft + width, targetTop + height);
        canvas.DrawBitmap(Bitmap, sourceRect, targetRect);
        canvas.Flush();
    }

But this only works, if the rectangles don't intersect or if the sourceRect is below the targetRect.

As a workaround I check for this and copy the pixels myself starting at the end in this case.

	private void Copy(int sourceLeft, int sourceTop, int targetLeft, int targetTop, int width, int height)
	{
		using (var canvas = new SKCanvas(Bitmap))
		{
			var sourceRect = new SKRect(sourceLeft, sourceTop, sourceLeft + width, sourceTop + height);
			var targetRect = new SKRect(targetLeft, targetTop, targetLeft + width, targetTop + height);

			var sourceEnd = (sourceTop + height - 1) * Bitmap.Width + sourceLeft + width;
			var targetEnd = (targetTop + height - 1) * Bitmap.Width + targetLeft + width;

			if (sourceRect.IntersectsWith(targetRect)           // it they intersect
				&& sourceEnd < targetEnd)                       // and the source should be copied down
			{                                                   // then I can't use DrawBitmap
				int lineDelta = Bitmap.Width - width;
				IntPtr pixelsAddr = Bitmap.GetPixels();

				if (Bitmap.BytesPerPixel == 4)      // just to be sure, may have to work for other sizes too
				{
					unsafe
					{
						uint* ptr = (uint*)pixelsAddr.ToPointer();
						uint* sourcePtr = ptr + sourceEnd;
						uint* targetPtr = ptr + targetEnd;

						int x, y = height;
						while (y > 0)
						{
							x = width;
							while (x > 0)
							{
								x--;
								sourcePtr--;
								targetPtr--;
								*targetPtr = *sourcePtr;
							}
							sourcePtr -= lineDelta;
							targetPtr -= lineDelta;
							y--;
						}
					}
				}
			}
			else
			{
				canvas.DrawBitmap(Bitmap, sourceRect, targetRect);
			}
			canvas.Flush();
		}
	}

So before I vectorize this code (which would still not be hardware accelerated) I wanted to ask, if there is an easier way to do this. Can this be considered a bug in Skia(Sharp) or is it simply not meant to copy areas of a bitmap within itself?

**Comment by MichaelRumpler** [comment]
I found several versions how to work around this problem. It looks like they are all faster (and correct), than `SKCanvas.DrawBitmap`.

You can find them on https://github.com/MichaelRumpler/CopyBitmap.

I prefer the version with `GetPixelSpan<T>` where my code does not have to be `unsafe`.

**Comment by mattleibow** [comment]
@MichaelRumpler we are adding the spans directly into the SkiaSharp APIs #865 so the next release will be easier to manipulate. Also, thanks for those benchmarks, they are helpful. The operations seem to be about the same speed regardless of method used (except for manual copying).

You could probably create a hybrid that checks the rectangle and then uses SkiaCopyDown, and then falls back to the Span copy.

With regards to your question:

> Can this be considered a bug in Skia(Sharp) or is it simply not meant to copy areas of a bitmap within itself?

This is more of a feature that is not typically done, and thus has no support at this time. In most cases, you are going to be drawing a bitmap - or part of it - onto the canvas that you are creating.

**Comment by MichaelRumpler** [comment]
Ok, thanks!

I settled for my `GetPixelSpan()` to get a `Span<byte>` and then `Span<byte>.CopyTo()` as a workaround. This is pretty fast and checks from which direction to copy.
