### ISSUE TITLE
[BUG] System.DllNotFoundException: libSkiaSharp assembly missing issue in ASP.NET Core Blazor client side application

### ISSUE THREAD

**Issue by prasanthelvr** [mono/SkiaSharp#846]
**Description**

We are using SkiaSharp to create image in ASP.NET Core Blazor application. In Blazor server side application, SkiaSharp works fine without any issue. But, when we use SkiaSharp in Blazor client side application we are facing libSkiaSharp assembly not found issue.  

**Code**

```C#
@page "/"
@using System.IO;
@using SkiaSharp;

<h1>Hello, world!</h1>

Welcome to your new app.
<br />
<button class="btn btn-primary" onclick="@Create">Create</button>

<p>@exception</p>

@functions{
    string exception = string.Empty;
    private void Create()
    {
        try
        {
            using (SKBitmap bitmap = new SKBitmap(500, 500, SKImageInfo.PlatformColorType, SKAlphaType.Premul))
            {
                using (SKSurface sKSurface = SKSurface.Create(bitmap.Info))
                {
                    SKCanvas sKCanvas = sKSurface.Canvas;
                    SKPaint sKPaint = new SKPaint();
                    sKPaint.Color = new SKColor(255, 0, 0);
                    sKCanvas.DrawText("Blazor", new SKPoint(250, 250), sKPaint);
                    MemoryStream stream = new MemoryStream();
                    sKSurface.Snapshot().Encode(SKEncodedImageFormat.Png, 100).SaveTo(stream);
                }
            }
        }
        catch (Exception ex)
        {
            exception = ex.ToString();
        }
    }
}
```

**Expected Behavior**

SkiaSharp should work properly in Blazor client side application.

**Actual Behavior**

The following exception is thrown.

`System.TypeInitializationException: The type initializer for 'SkiaSharp.SKImageInfo' threw an exception. ---> System.DllNotFoundException: libSkiaSharp assembly:<unknown assembly> type:<unknown type> member:(null) at (wrapper managed-to-native) SkiaSharp.SkiaApi.sk_colortype_get_default_8888() at SkiaSharp.SKImageInfo..cctor () <0x20f1170 + 0x00000> in <f0c24c4dec0742d096b8ec67614c0af5>:0 --- End of inner exception stack trace --- at Blazor_SkiaSharp.Pages.Index.Create () [0x00002] in C:\Users\labuser\source\repos\Blazor_SkiaSharp\Blazor_SkiaSharp\Pages\Index.razor:19`

**Basic Information**

- Version with issue:  1.68.0
- IDE:  Visual Studio 2019
- Platform: ASP.NET Core Blazor (client-side) 
- Platform Target Frameworks: .NET Core SDK 3.0.100-preview4-011223

**Reproduction Link**

[Blazor_SkiaSharp.zip](https://github.com/mono/SkiaSharp/files/3202266/Blazor_SkiaSharp.zip)

**Comment by Gillibald** [comment]
Isn't client side Blazor running under WebAssembly?

**Comment by prasanthelvr** [comment]
@Gillibald Client side blazor is running under WebAssembly [https://docs.microsoft.com/en-us/aspnet/core/blazor/?view=aspnetcore-3.0#blazor-client-side](https://docs.microsoft.com/en-us/aspnet/core/blazor/?view=aspnetcore-3.0#blazor-client-side).

**Comment by Gillibald** [comment]
That is currently not supported

**Comment by prasanthelvr** [comment]
@Gillibald  Can you please provide the time line for this implementation?

**Comment by Gillibald** [comment]
Pls have a look at this: https://github.com/nventive/Uno.SkiaSharp

**Comment by mattleibow** [comment]
Thanks @Gillibald.
@prasanthelvr, As mentioned, web assembly is not yet supported by SkiaSharp in this repo, but the Uno folks are working on things - as well as the mono folks. We are looking to get official support sometime (see #750), but we have to wait until the various bits fall into place. Fingers crossed it is soon.

**Comment by edgarhd** [comment]
Is this supposed to work now?
I am still having this error in client side Blazor
