### ISSUE TITLE
[BUG] ToSKBitmap() doesn't work properly

### ISSUE THREAD

**Issue by derekshreds** [mono/SkiaSharp#849]
ToSKBitmap() causes artifacts and displays at the incorrect size in Windows Forms.

I'm able to generate the correct bitmaps with my own method below:

```
        public static SKBitmap BitmapToSKBitmap(Bitmap bitmap)
        {
            var info = new SKImageInfo(bitmap.Width, bitmap.Height);
            var skiaBitmap = new SKBitmap(info);

            for (int i = 0; i < bitmap.Width; i++)
            {
                for (int j = 0; j < bitmap.Height; j++)
                {
                    Color color = bitmap.GetPixel(i, j);
                    skiaBitmap.SetPixel(i, j, new SKColor(color.R, color.G, color.B, color.A));
                }
            }

            return skiaBitmap;
        }
```

**Comment by Odirb** [comment]
Hello,
I have the same kind of problem with ToSKBitmap function when I use bitmaps with transparency. The problem can be reproduce easily with this sample : https://github.com/Odirb/BugSkiaSharpWinform

I have fixed a problem inside ToSKPixmap function, and I will send a pull request.
Regards.

**Comment by Mondonno** [comment]
@mattleibow Hi! I try to load image by using:
UIImage img = UIImage.FromFile("./me.png");
SKBitmap bitmap = new SKBitmap(300,300, false);
bitmap = img.ToSKBitmap();

What i getting?
![Zrzut ekranu 2020-09-1 o 11 54 13](https://user-images.githubusercontent.com/53169453/91835572-dd6e9100-ec49-11ea-8d2a-92ecc1b288cc.png)
What i do wrong? 
Thanks

**Comment by mattleibow** [comment]
@Mondonno make sure you install the `SkiaSharp.Views` package as well. The normal `SkiaSharp` package is just the .NET Standard library. For platform specifics, it is found inside the `.Views` packages.
