### ISSUE TITLE
[BUG] Much higher RAM usage on x64 compared with x86

### ISSUE THREAD

**Issue by Mikolaytis** [mono/SkiaSharp#858]
**Description**

We are putting images to GPU(texture based SKImage) to render them later with perfect performance.
On x86 build images are allocating only GPU RAM.
On x64 build images are allocating also CPU RAM.

This is a huge issue for us  👎. App is working some times slower on x64 and eating a lot more RAM, like 10 times more in some cases(200mb vs 2gb), because we store a lot images on GPU.

I've provided a repro project repo link below.

**Code**

```
using (var surf = SKSurface.Create(_grContext, false, _imageInfo, 1, GRSurfaceOrigin.TopLeft))
{
    surf.Canvas.DrawImage(_rasterImg, 0, 0);
    surf.Canvas.Flush();
    _textureImages.Add(surf.Snapshot());
}
```

Is there a better way to transform raster image to texture-backed image? We've tried to create textures and then push image to it - but this approach generated some artifacts on rendering. 

**Expected Behavior**

On x86 Snapshot() SKImage is allocating only GPU memory
On x64 Snapshot() SKImage is allocating only GPU memory

**Actual Behavior**

On x64 Snapshot() SKImage is allocating only GPU memory
On x64 Snapshot() SKImage is allocating GPU and CPU memory

**Basic Information**

- Version with issue:  1.68
- IDE:  Visual Studio
  - Windows Classic:  Windows 10
- Target Devices:  High-end PC

**Reproduction Link**

https://github.com/Mikolaytis/SkiaSharpMemoryIssue

**Comment by AndreyGrishin** [comment]
Yes, this is really a problem(

**Comment by Donsezan** [comment]
This is a big problem! Please help!

**Comment by Mikolaytis** [comment]
New prerelease 1.68.1-pre did not fix this issue

**Comment by Mikolaytis** [comment]
**Update**: on x86 OpenGL prefers to use shared GPU memory,
![image](https://user-images.githubusercontent.com/4997065/73128557-4ae67f00-3fe2-11ea-9ffd-8120a4f395a3.png)

but x64 OpenGL prefers to use just a process RAM, not shared GPU memory.

![image](https://user-images.githubusercontent.com/4997065/73128555-41f5ad80-3fe2-11ea-9fdc-97926569168a.png)

It can be:
1) a driver issue
2) an OpenGL issue
3) Windows issue
4) Skia issue
5) SkiaSharp issue
6) not an issue at all, maybe it's an expected behavior... idk...
