### ISSUE TITLE
[QUESTION] .NET Core on-screen rendering

### ISSUE THREAD

**Issue by elgunhuseynli** [mono/SkiaSharp#860]
Hi. I'm interested in creating desktop (Windows, macOS, Linux) GUI app with .NET Core and SkiaSharp. Unfortunately .NET Core samples are only showing how to render to offscreen canvas and save result to file. There are some examples like WPF and WinForms but they aren't cross-platform.

Can we do on-screen rendering with SkiaSharp in .NET Core? If yes, does it benefit from hardware acceleration?

I want very basic 2D rendering, not something like Avalonia.

Thanks.

**Comment by elgunhuseynli** [comment]
Actually, what I want to do is build a something like [Flutter](https://github.com/flutter/flutter), but in .NET Core 😃

Note: Flutter is also using Skia.

**Comment by Gillibald** [comment]
https://github.com/AvaloniaUI/Avalonia

**Comment by elgunhuseynli** [comment]
@Gillibald Avalonia is too feature rich. I'm looking for very basic 2D drawing in SkiaSharp.

**Comment by Gillibald** [comment]
It has everything you need to draw onto a window surface. You can extract just the windowing platform for your needs if you want. Have a look at the Avalonia.Skia bits.

**Comment by entdark** [comment]
> @Gillibald Avalonia is too feature rich. I'm looking for very basic 2D drawing in SkiaSharp.

Skia and SkiaSharp are basic 2D drawing tool out of the box itself.

**Comment by elgunhuseynli** [comment]
@entdark Thanks. I know that. But I'm looking for how can I create window in .NET Core to on-screen render with SkiaSharp. :)

**Comment by mattleibow** [comment]
You could have a look at [XWT](https://github.com/mono/xwt) or GTK# to create Windows.

I did hack this together for somthing else? https://github.com/mattleibow/SkiaSharpNetCoreGtkSharp
Keep in mind that this is a super hacky way and I have not tested it anywhere other than Windows 10.

**Comment by mattleibow** [comment]
Closing this as this is not a feature of SkiaSharp at this time.

**Comment by bmitc** [comment]
Hi @elgunhuseynli. Did you ever figure something out? I have the same question. I'd like to do my own basic graphics and GUI framework from scratch using SkiaSharp in .NET Core (.NET 5) but am having trouble understanding how to do this without having to revert to using Xamarin.Forms.
