### ISSUE TITLE
How to use/create eraser for finger print on bitpmap?

### ISSUE THREAD

**Issue by Naografix** [mono/SkiaSharp#864]
Hello,

I use "FingerPaintSavePage" to try to create an eraser for my finger painting.
I loaded a bitmap with: 

`this.saveBitmap = BitmapExtensions.LoadBitmapResource(this.GetType(), "SkiaSharpFormsDemos.Media.MonkeyFace.png");`

And now, I can draw on this little monkey.

I found this post where "mario.mora" said: "You have to set transparent color and blendmode as "Src", shomehow like this:"
But when I do that, I can erase my bitmap behind (it's render like a white paint)...

How can I do an eraser?

Thanks

**Comment by mattleibow** [comment]
@Naografix you probably need to draw using a blend mode. Most probably set [`SKPaint.BlendMode`](https://docs.microsoft.com/dotnet/api/SkiaSharp.SKPaint.BlendMode) to `Src` or `SrcOver`.

Se also: https://docs.microsoft.com/dotnet/api/skiasharp.skblendmode
