### ISSUE TITLE
[BUG] [WPF] SKElement crash when ActualWidth or ActualHeight is less than 1px

### ISSUE THREAD

**Issue by Odirb** [mono/SkiaSharp#867]
Hello,

In a very basic Wpf application with an SKElement in a grid, it's possible to have a crash just by resizing the window when ActualHeight or ActualWidth of the control becomes less than 1 pixel.

The OnRender function verify if ActualWidth or ActualHeight are equal to zero, but since theses values are defined as double in WPF and later cast to integer, the constructor of WriteableBitmap can be called with width and/or height parameter set to zero.

The problem is reproducted with a simple WPF application like this one https://github.com/Odirb/BugSkiaSharpSKElement

I'll push a pull request with a fix.

Regards.

**Comment by mattleibow** [comment]
Thanks for reporting this and the PR. Will be merging as soon as the build finishes.

**Comment by mattleibow** [comment]
Merged. Thanks for the PR!
