### ISSUE TITLE
[BUG] App can crash due to trying to set SKCanvasView EnableTouchEvents to false

### ISSUE THREAD

**Issue by vchelaru** [mono/SkiaSharp#870]
**Description**

Testers for our apps are experiencing crashes which seem to be caused by setting an instance of a `SKCanvasView.EnabledTouchEvents = true`.

Unfortunately this happens in a rather complex app and I cannot share the app or source related to the app for reproduction, but I will provide as much information as I can to help solve the problem.

**Code**

In our case we have a page which has a view with the following snippet:

```
public class MyView : SKCanvasView
{
    public MyView()
    {
        ....

        PaintSurface += HandlePaintSurface;
        SizeChanged += HandleSizeChanged;

        EnableTouchEvents = true; // <- This is the critical line of code
        Touch += HandleTouch;
        
    }
}
```

For testing, our testers navigate in and out and in and out of this page multiple times, sometimes 7 times or more. The app will not crash until going to a different page - possibly when a GC occurs?

If we instead change the assignment to EnableTouchEvents to false, testers cannot reproduce this crash:

```
  ...
  EnableTouchEvents = false;
  ..
```
Note that testers have not been able to reproduce this with a debugger attached, only with a deployed build, disconnected from Visual Studio. I don't know if that's relevant here.

**Expected Behavior**

The underling code should properly be able to set EnabledTouchEvent (or whatever platform-specific equivalent exists) without crashing.

**Actual Behavior**

Given enough back and forth navigation, the application will crash.

**Basic Information**

- Version with issue:  1.68.0
- Last known good version:  Unknown, this is a new page in our app that was added after we upgraded to 1.68.0.
- IDE:  Visual Studio on Windows 10
- Platform Target Frameworks: 
  - Android: Android 8.1 (API Level 27 - Oreo)
- Target Devices:  
  - Nexus 5X
  - Emulator (Android 8.1.0)
  - Pixel (Android 9.0 - this is the original pixel)

**Screenshots**

**Reproduction Link**

**Additional Information**

The following information is provided by AppCenter:

SKTouchHandler.SetEnabled (Android.Views.View view, System.Boolean enableTouchEvents)
System.ObjectDisposedException: Cannot access a disposed object. Object name: 'SkiaSharp.Views.Android.SKCanvasView'.

Callstack:

```
JniPeerMembers.AssertSelf (Java.Interop.IJavaPeerable self)
JniPeerMembers+JniInstanceMethods.InvokeVirtualVoidMethod (System.String encodedMember, Java.Interop.IJavaPeerable self, Java.Interop.JniArgumentValue* parameters)
View.SetOnTouchListener (Android.Views.View+IOnTouchListener l)
View+<>c__DisplayClass2576_0.<remove_Touch>b__0 (Android.Views.View+IOnTouchListener __v)
EventHelper.RemoveEventHandler[TInterface,TImplementor] (System.WeakReference& implementor, System.Func`2[T,TResult] empty, System.Action`1[T] unsetListener, System.Action`1[T] remove)
View.remove_Touch (System.EventHandler`1[TEventArgs] value)
SKTouchHandler.SetEnabled (Android.Views.View view, System.Boolean enableTouchEvents)
SKTouchHandler.Detach (Android.Views.View view)
SKCanvasViewRendererBase`2[TFormsView,TNativeView].Dispose (System.Boolean disposing)
Object.Finalize ()
```

**Comment by vchelaru** [comment]
** Workaround **

I found that a workaround! The page that contains the SKCanvasView can enable/disable touch events:

```
protected override void OnAppearing()
{
    base.OnAppearing();
    view.EnableTouchEvents = true;
}

protected override void OnDisappearing()
{
    view.EnableTouchEvents = false;
    base.OnDisappearing();
}
```

Maybe this will help others who run into this problem until a proper fix is put in place.

**Comment by mattleibow** [comment]
This should no longer be happening due to dispose keeping a reference to the control during execution.

**Comment by vchelaru** [comment]
Unfortunately I have been able to reproduce this again:

```
[mono-rt] [ERROR] FATAL UNHANDLED EXCEPTION: System.ObjectDisposedException: Cannot access a disposed object.
[mono-rt] Object name: 'SkiaSharp.Views.Android.SKCanvasView'.
[mono-rt]   at Java.Interop.JniPeerMembers.AssertSelf (Java.Interop.IJavaPeerable self) [0x00029] in <bd6bd528a8784b7caf03e9f25c9f0d7b>:0 
[mono-rt]   at Java.Interop.JniPeerMembers+JniInstanceMethods.InvokeVirtualVoidMethod (System.String encodedMember, Java.Interop.IJavaPeerable self, Java.Interop.JniArgumentValue* parameters) [0x00000] in <bd6bd528a8784b7caf03e9f25c9f0d7b>:0 
[mono-rt]   at Android.Views.View.SetOnTouchListener (Android.Views.View+IOnTouchListener l) [0x0002c] in /Users/builder/azdo/_work/1/s/xamarin-android/src/Mono.Android/obj/Release/monoandroid10/android-30/mcw/Android.Views.View.cs:23279 
[mono-rt]   at Android.Views.View+<>c__DisplayClass2854_0.<remove_Touch>b__0 (Android.Views.View+IOnTouchListener __v) [0x00000] in /Users/builder/azdo/_work/1/s/xamarin-android/src/Mono.Android/obj/Release/monoandroid10/android-30/mcw/Android.Views.View.cs:24822 
[mono-rt]   at Java.Interop.EventHelper.RemoveEventHandler[TInterface,TImplementor] (System.WeakReference& implementor, System.Func`2[T,TResult] empty, System.Action`1[T] unsetListener, System.Action`1[T] remove) [0x00032] in /Users/builder/azdo/_work/1/s/xamarin-android/src/Mono.Android/Java.Interop/EventHelper.cs:35 
[mono-rt]   at Android.Views.View.remove_Touch (System.EventHandler`1[TEventArgs] value) [0x00014] in /Users/builder/azdo/_work/1/s/xamarin-android/src/Mono.Android/obj/Release/monoandroid10/android-30/mcw/Android.Views.View.cs:24819 
[mono-rt]   at SkiaSharp.Views.Forms.SKTouchHandler.SetEnabled (Android.Views.View view, System.Boolean enableTouchEvents) [0x00003] in <70db931b20b148d097dc1e71a7f1cc73>:0 
[mono-rt]   at SkiaSharp.Views.Forms.SKTouchHandler.Detach (Android.Views.View view) [0x00000] in <70db931b20b148d097dc1e71a7f1cc73>:0 
[mono-rt]   at SkiaSharp.Views.Forms.SKCanvasViewRendererBase`2[TFormsView,TNativeView].Dispose (System.Boolean disposing) [0x00059] in <70db931b20b148d097dc1e71a7f1cc73>:0 
[mono-rt]   at Java.Lang.Object.Java.Interop.IJavaPeerable.Finalized () [0x00000] in /Users/builder/azdo/_work/1/s/xamarin-android/src/Mono.Android/Java.Lang/Object.cs:183 
[mono-rt]   at Android.Runtime.AndroidValueManager.FinalizePeer (Java.Interop.IJavaPeerable value) [0x00068] in /Users/builder/azdo/_work/1/s/xamarin-android/src/Mono.Android/Android.Runtime/AndroidRuntime.cs:675 
[mono-rt]   at Java.Lang.Object.Finalize () [0x00010] in /Users/builder/azdo/_work/1/s/xamarin-android/src/Mono.Android/Java.Lang/Object.cs:65 
```

This time I am using:

Skia Sharp 2.80.3
Xamarin Forms 5.0.0.2244
SkiaSharp.Views 2.80.3
SkiaSharp.Views.Forms 2.80.3

**Comment by MaximMikhisor** [comment]
> This should no longer be happening due to dispose keeping a reference to the control during execution.

In what version was it fix?

We also still gettting this error.
We are using Skia Sharp 2.80.2
