### ISSUE TITLE
How do I get the native binaries for a Managed-only build?

### ISSUE THREAD

**Issue by danien** [mono/SkiaSharp#883]
I'm trying to do a managed-only build by following [the instructions here](https://github.com/mono/SkiaSharp/wiki/Building-SkiaSharp#preparation-1) since I wasn't able to get the externals/skia native builds to complete without compilation errors (in GrAHardwareBufferImageGenerator.cpp, line 217, GrBackendTexture backendTex: no matching constructor).

However, I don't know how to get the correct Azure Build IDs. If I go to the [Azure build page](https://dev.azure.com/xamarin/public/_build?definitionId=4) and pick one of the builds from SkiaSharp (Public) that appears to have built successfully with a green tick (e.g., [build 3348](https://dev.azure.com/xamarin/public/_build/results?buildId=3348)) ) and copy the buildId from the URL (e.g., 3348), and use that with the bootstrapper,

```
./bootstrapper.sh -t externals-download --azureBuildId=3348
```
(Also tried "3348" in quotes.)

I get the following error:

```
========================================
externals-download
========================================
An error occurred when executing task 'externals-download'.
Error: One or more errors occurred. (One or more errors occurred. (404 (Not Found)))
	404 (Not Found)

```

I found the AZURE_BUILD_URL that the SkiaSharp/build.cake and SkiaSharp/cake/BuildExternals.cake build scripts use to download the native binaries in a zip file. Using that URL with the buildId and "native" for the artifactName field, I get the following error:

```
{"$id":"1","innerException":null,"message":"Artifact native was not found for build 3348.","typeName":"Microsoft.TeamFoundation.Build.WebApi.ArtifactNotFoundException, Microsoft.TeamFoundation.Build2.WebApi","typeKey":"ArtifactNotFoundException","errorCode":0,"eventId":3000}
```

I've tried several of the other builds and also the ones from SkiaSharp.Extended (Public) and they all return the same error.

Is there a way I can figure out which builds contain the native binaries without guessing?

Thank you.

**Comment by Gillibald** [comment]
You can download them from here https://dev.azure.com/xamarin/public/_build/results?buildId=3348

**Comment by danien** [comment]
> https://dev.azure.com/xamarin/public/_build/results?buildId=3348

Do I click on the Artifact button and just select any/all of the options? When I tried that, I get the following error:

```
{"$id":"1","innerException":null,"message":"TF400813: The user '<github user id>' is not authorized to access this resource.","typeName":"Microsoft.TeamFoundation.Framework.Server.UnauthorizedRequestException, Microsoft.TeamFoundation.Framework.Server","typeKey":"UnauthorizedRequestException","errorCode":0,"eventId":3000}
```

**Comment by Gillibald** [comment]
You should be able to download the `nuget.zip`

**Comment by danien** [comment]
> You should be able to download the `nuget.zip`

Ah, thank you! I was able to download just that file, which contains all the built nupkgs.

My partially built output folder seems to have a different layout with nuget subfolders:

```
output/
    HarfBuzzSharp/
        nuget/
    SkiaSharp/
        nuget/
    SkiaSharp.HarfBuzz/
        nuget/
    SkiaSharp.Views/
        nuget/
    SkiaSharp.Views.Forms/
        nuget/
```
so I'm guessing I have to unzip the contents of the nupkgs into their respective nuget subfolders in order to get the Managed-only build to be able to use them?

Thanks again and apologies for all the questions as I'm rather new to SkiaSharp.

**Comment by Gillibald** [comment]
For example: `SkiaSharp\output\native\windows\x64`
![Anmerkung 2019-06-24 183826](https://user-images.githubusercontent.com/5928797/60036438-89fccc80-96af-11e9-9869-b81e2435736a.png)
![Anmerkung 2019-06-24 183850](https://user-images.githubusercontent.com/5928797/60036444-8c5f2680-96af-11e9-9e81-150fc8fce228.png)
![Anmerkung 2019-06-24 183912](https://user-images.githubusercontent.com/5928797/60036452-8e28ea00-96af-11e9-817c-8e072b306a01.png)
![Anmerkung 2019-06-24 183940](https://user-images.githubusercontent.com/5928797/60036455-8ff2ad80-96af-11e9-9052-200265126b0d.png)
![Anmerkung 2019-06-24 184002](https://user-images.githubusercontent.com/5928797/60036459-91bc7100-96af-11e9-85c5-73a571faddcc.png)

**Comment by danien** [comment]
Thanks! I wouldn't have known to add a native subfolder under output.

I found runtime/<platform>/native subfolders with the binaries (dll, dylib, so, no pdbs), so I'll try that tomorrow.

Really appreciate your help!

**Comment by danien** [comment]
Unfortunately, the nuget.zip seems to be missing the android, ios, tvos, watchos binaries and it's quite hard to figure out all the subfolder names that the binaries should go into. e.g., For tizen, the build appears to look for i386, while the nuget has the binaries in tizen-armel, tizen-x86 folders, etc.

Is there another way to get the native.zip or to get the "externals-download" target to work for people without access to the Azure Build pipeline so that this line in the documentation works?

```
./bootstrapper.ps1 -t externals-download --azureBuildId=<build-id>
```

Thanks.

**Comment by Gillibald** [comment]
You can also download the package from Nuget.org https://www.nuget.org/api/v2/package/SkiaSharp/1.68.0

**Comment by danien** [comment]
> You can also download the package from Nuget.org https://www.nuget.org/api/v2/package/SkiaSharp/1.68.0
> 
> But downloading the externals directly from CI is probably the best.
> 
> To test things added to the binding you don't need to use the bootstrapper.ps1 you can just build the projects directly

This doesn't seem to have the android, ios, etc folders and binaries as well. The nuget.zip that I managed to download for build 3348 has a similar structure as this (except it's a later version 1.68.1).

If there is a way to download the externals (I'm guessing native-default, native-*, under Artifacts) from CI without contributor permissions, please let me know how.

My goal is actually to try to update the SkiaSharp and SkiaSharp.Views.Forms managed libraries for netstandard 2.0 and Xamarin.Forms 4.0 for use with Fabulous (F#), which is still on SkiaSharp 1.60.3 and is missing the SKGLView, but I wanted to learn to build the whole project from scratch if possible.

I'll try building just the ones I need without the bootstrapper then. Just running into a lot of issues especially with Android.

**Comment by mattleibow** [comment]
@danien you can download the `native-default` artifacts to just get all the native assets, and the `nuget` artifact to get all the nupkgs.

For example, it you are getting the bits for build `3425`, you can go to that build:
https://dev.azure.com/xamarin/public/_build/results?buildId=3425

And then download the `native-default` artifact:
<img src="https://user-images.githubusercontent.com/1096616/60121331-1d530200-9783-11e9-945c-37a65134a843.png" width="400" />

**Comment by mattleibow** [comment]
Once this PR is merged (https://github.com/mono/SkiaSharp/pull/889), you should be able to access the artifacts.

So we will have 2 public artifacts:
 - `native-default` - for accessing all the native assets from all the platforms
 - `nuget` - for accessing all the packaged NuGets for all the platforms

If you need a REST endpoint, you can use:

```
https://dev.azure.com/xamarin/public/_apis/build/builds/BUILD_ID/artifacts?artifactName=ARTIFACT NAME&%24format=zip
```

Where:
 - `BUILD_ID` is the build ID (eg: `3425`)
 - `ARTIFACT NAME` is the artifact name (eg: `nuget` or `native-default`)

**Comment by danien** [comment]
Confirmed that it works. Also confirmed that it works with [building the rest of the project](https://github.com/mono/SkiaSharp/wiki/Building-SkiaSharp#building) using
```
.\bootstrapper.ps1 -t everything --skipExternals=all
```
after unzipping the contents into the output/native folder.

Should the "externals-download" task in cake/BuildExternals.cake be updated from "native" to "native-default" for the artifact name as well?

```
Task ("externals-download")
    .Does (() =>
{
    ...
    var url = string.Format(AZURE_BUILD_URL, AZURE_BUILD_ID, "native-default");
    ...
});
```

(For convenience, here's the [Azure build Id #3459](https://dev.azure.com/xamarin/public/_build/results?buildId=3459).)

**Comment by mattleibow** [comment]
> Should the "externals-download" task in cake/BuildExternals.cake be updated from "native" to "native-default"

Good catch, yes it should be `native-default`.

And the rename should just be a matter of moving the dir after extraction:

```csharp
MoveDirectory ("./output/native-default", "./output/native");
```

Do you want to edit the file? Then you can join the ranks as a SkiaSharp contributor.

**Comment by danien** [comment]
> Do you want to edit the file? Then you can join the ranks as a SkiaSharp contributor!

Cool. I've submitted a pull request #892 for your review but if it's easier, I've added the code from the [BuildExternals.cake](https://github.com/danien/SkiaSharp/blob/dev/change-externals-download-native-artifact-name/cake/BuildExternals.cake) file here.

I'm new to Github contributions, so let me know if I'm doing anything wrong. Thanks again!

```
Task ("externals-download")
    .Does (() =>
{
    if (string.IsNullOrEmpty (AZURE_BUILD_ID))
        throw new Exception ("Specify a build ID with --azureBuildId=<ID>");

    var artifactName = "native-default";
    var artifactFilename = $"{artifactName}.zip";
    var url = string.Format(AZURE_BUILD_URL, AZURE_BUILD_ID, artifactName);

    var outputPath = "./output";
    EnsureDirectoryExists (outputPath);
    CleanDirectories (outputPath);

    DownloadFile (url, $"{outputPath}/{artifactFilename}");
    Unzip ($"{outputPath}/{artifactFilename}", outputPath);
    MoveDirectory ($"{outputPath}/{artifactName}", $"{outputPath}/native");
});
```

**Comment by mattleibow** [comment]
@danien you did everything right! Merging!
