### ISSUE TITLE
[QUESTION] .NET Standard 2.0 Support

### ISSUE THREAD

**Issue by arggrande** [mono/SkiaSharp#887]
Hi,

Just wondering if there are any plans on .NET Standard 2.0 Support in the near future? :)

Cheers,
Adam

**Comment by neodynamic** [comment]
SkiaSharp can be used in .NET Standard 2.0 projects! Not sure what you meant by supporting .NET Standard 2.0...

**Comment by mattleibow** [comment]
The current support is from .NET Standard 1.3 and above.

**Comment by mattleibow** [comment]
Closing this as SkiaSharp is .NET Standard 1.3+ - which means 2.0 is supported.
