### ISSUE TITLE
[BUG] CentOS 7 libSkiaSharp.so error 'CXXABI_1.3.8' not found and 'GLIBCXX_3.4.21' not found 

### ISSUE THREAD

**Issue by BruceHunter** [mono/SkiaSharp#888]
**Description**
On CentOS 7 you get the following error. This code works on windows 10 just fine.

```
#ldd libSkiaSharp.so

libSkiaSharp.so

'CXXABI_1.3.8' not found
'GLIBCXX_3.4.21' not found 
```

- Version with issue:  
```
    <PackageReference Include="SkiaSharp" Version="1.68.0" />
    <PackageReference Include="SkiaSharp.NativeAssets.Linux" Version="1.68.0" />
```

- Last known good version:  First time using SkiaSharp.
- IDE:  Visual Studio (2017,2019) / Visual Studio Code latest
- Platform Target Frameworks: .net core 2.2
- runtime : linux-x64 and win-x64
 - Linux:  CentOS 7 (fully updated)

The solution I found was the following. (install gcc,gcc-c++ 4.8.5) to be utilized to bootstrap compiling to the latest 9.* version via source.

CentOS 7 Steps

1) Upgrade GCC,GCC-C++ (Steps are online).
2) Reboot
3) Run these commands to fix actual issue for error list above.

```
#cd /usr/local/lib64
#cp libstdc++.so.6.0.29 /usr/lib64/
#cd /usr/lib64/
#mv libstdc++.so.6 libstdc++.so.6.OLD
#ln -sf libstdc++.so.6.0.29
```

After upgrading gcc, I was able to get a self-contained published .net core 2.2 app working on centos 7 server.

I have gotten it to work on dotnet (FDD and SCD) deployment models.

**Comment by LukePulverenti** [comment]
@BruceHunter are you planning on trying the RC build?

**Comment by davorinv** [comment]
> You could try using the preview feed and one of the later rc versions. We switched to a static compilation and clang. We also have a 'NoDependencies' package that should have no dependencies.
> 
> Preview feed: https://nugetized.blob.core.windows.net/skiasharp-eap/index.json

I tried using build 1.68.1-rc.138 and that fixed the issue on CentOS 7.6.1810

**Comment by BruceHunter** [comment]
I was on vacation, sorry. I will switch to the preview feed instead. Also, seeing blurry images when using the resize, but that is another issue. Maybe the preview feed will fix that as well. I will report back once I switch over.

**Comment by mattleibow** [comment]
Closing this issue for now as it seems to be fixed.

Please open a new issue if this is still happening.
