### ISSUE TITLE
Split the SkiaSharp.Views package for desktop

### ISSUE THREAD

**Issue by mattleibow** [mono/SkiaSharp#893]
**Is your feature request related to a problem?**

Currently, the SkiaSharp.Views NuGet package includes all the UI controls for all the native platforms. This is typically fine, except for desktop platforms (Windows, macOS, Linux) as there are MULTIPLE frameworks for each:

 - Windows
    - Windows Forms
    - WPF
    - GTK# (both v2 and v3)
 - macOS
    - Cocoa/AppKit
    - GTK# (both v2 and v3)
    - *Potentially UIKit*
 - Linux
    - GTK# (both v2 and v3)
    - *Potentially others*

In addition to this, there is the whole .NET Core world where WPF and WinForms works on both Full Framework (eg: net45) and Core (eg: netcoreapp3.0).

At this point in time, it is a very messy package and is going to be causing all sorts of issues later.

**Describe the solution you'd like**

> ⚠ WARNING: BREAKING CHANGE ⚠

We are looking to move the desktop views out into separate packages:

 - SkiaSharp.Views       *(existing core package with iOS, Android, etc)*
 - SkiaSharp.Views.WinForms
 - SkiaSharp.Views.WPF
 - SkiaSharp.Views.Mac
 - SkiaSharp.Views.Gtk2
 - SkiaSharp.Views.Gtk3

As a result of this, we will change the core SkiaSharp.Views package to rather show a set of warnings when it detects that it was installed, but does not have the correct platform packages. 

For example, if you install the core package onto net47 and it detects a reference to WPF, it will ask you to install the SkiaSharp.Views.WPF package. Or, if you have a netcoreapp3.0 and it dtects a reference to GtkSharp3, then it will suggest installing the SkiaSharp.Views.Gtk3 package.

**Comment by MichaelRumpler** [comment]
If bait & switch does not work, then I'm fine with installing the correct platform package manually. Namespaces and APIs should be the same as far as possible.

A breaking change is always preferred to keeping a broken API forever (as XF does it).

Specifically I want to share code between WPF for Core, Android and iOS. But that's just now. Who knows what the future brings.

**Comment by mattleibow** [comment]
I have been playing around with GTK# v3 and that seems to be a nice way to make a fully cross-platform netcoreapp. But, right now, you are forced to use GTK# v2, which is very old. And it brings in the WPF and WinForms dll into your build.

But, an important thing is that this should not be a breaking change for Xamarin.Forms users as the SkiaSharp.Views.Forms package will still bring in the same APIs.

**Comment by mattleibow** [comment]
And, I will make sure to create a nice warning/error if you install the SkiaSharp.Views package, but forget to install the actual platform framework package.

**Comment by mattleibow** [comment]
I just realised that this is not such a breaking change. Because there is no cross-platform code in this package, all the platforms can technically be separate.

For the desktop builds, we will have to have a type forwarding assembly so we don't break everyone.
