### ISSUE TITLE
Cannot set width of canvas view to more then 1000

### ISSUE THREAD

**Issue by sarthak199526** [mono/SkiaSharp#896]
**Description**

I am trying to create a custom bar chart using canvas view on **xamarin forms** . So I need to draw almost 500 rect of 30 width with 30 spacing within each of them so the width of canvas view will become almost 30000 the rectangle is drawing but when the pages load canvas view becomes blank with white color . Everything works fine when when I set widht to 1000 . Note I am having the canvas view in horizontal scroll view so the user can scroll horizontally to the last rect . It would be better if you could add bar chart sample to skia sharp demo sample of xamarin forms . Let me know if it's not possible so that I'll start finding any other solution

**Code**
Xaml
<skia:SKCanvasView HeightRequest="500" WidthRequest="30000" x:Name="skiaView" PaintSurface="OnPaintSurface" /> 

Code Behind
float lastx = 0;
for (int k = 0; k < mData.mergedLists.Count; k++)
            {
                var rect = SKRect.Create(lastx, (float)skiaView.Height - (float)mData.mergedLists[k].WidthValue, 30, (float)mData.mergedLists[k].WidthValue);
                var paint = new SKPaint
                {
                    Style = SKPaintStyle.Fill,
                    Color = SKColors.Blue
                };
                canvas.DrawRect(rect, paint);
                paint.Style = SKPaintStyle.Stroke;
                paint.Color = SKColors.Red;
                canvas.DrawRect(rect, paint);

                var rect2 = SKRect.Create(rect.Right, (float)skiaView.Height - (float)mData.mergedLists[k].PeakValue, 30, (float)mData.mergedLists[k].PeakValue);
                var paint2 = new SKPaint
                {
                    Style = SKPaintStyle.Fill,
                    Color = SKColors.Red
                };
                // draw fill
                // change the brush (stroke with red)
                paint.Style = SKPaintStyle.Stroke;
                paint.Color = SKColors.Blue;
                canvas.DrawRect(rect2, paint2);
                lstx = rect2.Right + 30;
            }
**Expected Behavior**

It should have set to whatever width we set to canvas view

Canvas view becomes blank with white color in it . 

**Basic Information**

- Version with issue:  
- Platform Target Frameworks: 
  - Android:  
  - iOS:

**Comment by michaldobrodenka** [comment]
Maximum canvas size is dependent on the os and graphic hw. I think it's between 4096*4096 to 16384*16384 pixels

**Comment by sarthak199526** [comment]
This mean it's not possible to create a horizontally scrollable long bar chart using skia-sharp canvas view since I might gonna need width so much greater then the above you suggest ?

**Comment by michaldobrodenka** [comment]
Exactly. You should keep size of canvas smaller or not much bigger than size of screen.

We have Skiasharp drawn charts, they are scrollable and zoom able. But scroll is implemented within canvas. I listen for Move/Pan/Zoom event/gesture (I don't know how it's called in Xamarin Forms implementation, I use WPF, Xamarin.Android/iOS native), and redraw canvas accordingly.

**Comment by sarthak199526** [comment]
Understood thanks mate
