### ISSUE TITLE
UWP store version has crashes from libSkiaSharp.dll

### ISSUE THREAD

**Issue by zipswich** [mono/SkiaSharp#905]
At one point of time, I could see the following code causing app to exit despite it is in a catch block:

`SKBitmap skb = SKBitmap.Decode(codec, skiInfo);`

It seems updating all NuGet packages fixed it for the debug version. The published store version causes app crash on every one of the few computers used to test it:
The stack trace is something like the following:

```
Frame	Image	Function	Offset
       Frame	Image	Function	Offset
0	ucrtbase.dll	abort	0x000000000000004E	
1	VCRUNTIME140_APP.dll	_purecall	0x000000000000002E	
2	libSkiaSharp.dll	sk_rrect_transform	0x0000000000233C57	
3	libSkiaSharp.dll	sk_rrect_transform	0x0000000000233D72	
4	libSkiaSharp.dll	sk_rrect_transform	0x0000000000043770	
5	libSkiaSharp.dll	sk_codec_get_pixels	0x0000000000000073	
6	MY_APP.dll	null	0x0000000001C88D19	
7	null	null	0x0000000000000000	
8	libSkiaSharp.dll	sk_rrect_transform	0x0000000000031416	
9	libSkiaSharp.dll	sk_rrect_transform	0x000000000003168C	
```
The app has only one place using SkiaSharp.  The code is something like the following (the enclosing try-catch block is omitted):
```
using (MemoryStream ms = new MemoryStream(abSnapshot))
{
    SKStream skStream = new SKManagedStream(ms);
    SKCodec codec = SKCodec.Create(skStream);
    SKImageInfo skInfo = codec.Info;
    int iWidthOriginal = skInfo.Width;
    int iHeightOriginal = skInfo.Height;
    double dScale = Math.Min((float)iWidthNew / iWidthOriginal, 1);
    uint uiWidthNew = (uint)(iWidthOriginal * dScale);
    uint uiHeightNew = (uint)(iHeightOriginal * dScale);
    SKSizeI ssi = codec.GetScaledDimensions((float)dScale);
    SKImageInfo skiInfo = new SKImageInfo(ssi.Width, ssi.Height);

    SKBitmap skb = SKBitmap.Decode(codec, skiInfo);
    StorageFile sfNew = await sfSnapshots.CreateFileAsync(sID + "-last.jpg", CreationCollisionOption.ReplaceExisting);
    if (sfNew == null)
    {
        //...
    }
    else
    {
        using (Stream stream = await sfNew.OpenStreamForWriteAsync())
        {
            using (SKImage skImage = SKImage.FromBitmap(skb))
            using (SKData data = skImage.Encode(SKEncodedImageFormat.Jpeg, 80))
            {
                data.SaveTo(stream);
            }
        }
    }
}
```
Could anyone offer a tip on how to prevent app crash from this code?

**Comment by mattleibow** [comment]
The code looks valid, so I am not sure exactly. I also see a few calls to `sk_rrect_transform` - which is the `Transform` method on the `SKRoundRect` type. Are you using that somewhere?

I have also noticed a few native memory issues that I am fixing as part of #900. I hope to merge this soon and you can try it out.

**Comment by zipswich** [comment]
Thank you for looking into it.
No, I do not SKRoundRect directly at all. 
Since it is 100% reproducible, I will be able to tell if #900 will fix the problem as soon as I get the new package.

**Comment by mattleibow** [comment]
This should be fixed now with all the memory fixes merged.
