### ISSUE TITLE
[QUESTION] 

### ISSUE THREAD

**Issue by al3xmeister** [mono/SkiaSharp#906]
Good morning,

Trying to implement a pdf export from skia sharp drawings, using api .CreatePdf(stream, metadata)), in a xamarin forms project that targets UWP.

Really struggling to get it implemented, particularly at the save/create stage - I was wondering if there is any way to receive some assistance on implementing it? I've followed the documentation here https://github.com/mono/SkiaSharp/blob/master/samples/Gallery/Shared/Samples/CreatePdfSample.cs#L47

but I must be doing something wrong, the file doesnt save after calling pdfCanvas.DrawBitmap and  document.Close();.

Many thanks in advance

**Comment by charlesroddie** [comment]
Please format your issue.

**Comment by mattleibow** [comment]
I am not sure what errors are you getting? Is it a crash/exception? Is it saving wrong? Is it not saving at all? What version of SkiaSharp are you using?

**Comment by mattleibow** [comment]
Closing this due to lack of a response.
