### ISSUE TITLE
SkiaSharp wrong appearance after converting SVG to PNG

### ISSUE THREAD

**Issue by 8m0** [mono/SkiaSharp#907]
Hi, i already asked about the problem on SO. I hope someone can help me here.
[Post on StackOverflow](https://stackoverflow.com/questions/56558040/skiasharp-converting-svg-to-png-spoils-image)

**Comment by charlesroddie** [comment]
Are you using SkiaSharp.Svg 1.60? That release is broken. Try 1.59.1.
The fixes have been merged but not released https://github.com/mono/SkiaSharp.Extended/issues/68
@mattleibow

**Comment by 8m0** [comment]
> Are you using SkiaSharp.Svg 1.60? That release is broken. Try 1.59.1.
> The fixes have been merged but not released [mono/SkiaSharp.Extended#68](https://github.com/mono/SkiaSharp.Extended/issues/68)
> @mattleibow

The same bug appears with 1.59.1.

**Comment by mattleibow** [comment]
It is highly likely that you are using features not supported in the current implementation of SVG. I would suggest opening an issue against the https://github.com/mono/SkiaSharp.Extended repo. At this time, the SVG work is taking a slightly lower priority. This is unfortunate, but you can ping https://twitter.com/davidortinau on twitter and get him to get me some points :)

There is some work being done to create a fully featured SVG engine for SkiaSharp: https://twitter.com/wieslawsoltes/status/1154801781542739968

**Comment by wieslawsoltes** [comment]
@8m0 Can you post orignal `.svg` file?

**Comment by mattleibow** [comment]
SVG work is not really a feature of SkiaSharp and it is probably good to try out https://www.nuget.org/packages/Svg.Skia
