### ISSUE TITLE
SKColorType.Index8 removed - why?

### ISSUE THREAD

**Issue by nietras** [mono/SkiaSharp#908]
SKColorType.Index8 has been removed in 1.68.0, see https://github.com/mono/SkiaSharp/blob/master/changelogs/SkiaSharp/1.68.0/SkiaSharp.breaking.md, why has it been removed?

**Comment by nietras** [comment]
It appears this type now loads as Bgr instead, which is not what we want, this is a pretty big breaking change for us. Does this come from Skia itself or from the .NET wrapping code?

**Comment by nietras** [comment]
Actually appears to have been removed from skia itself, not good:

https://bugs.chromium.org/p/skia/issues/detail?id=6620&can=1&q=Index8&colspec=ID%20Type%20Status%20Priority%20M%20Area%20Owner%20Summary

**Comment by mattleibow** [comment]
Google didn't need it so they removed it. It is unfortunate, but not much we can do about it.
