### ISSUE TITLE
UWP ARM NEON

### ISSUE THREAD

**Issue by mattleibow** [mono/SkiaSharp#91]
This currently gives a compiler error about the initializer:

``` cpp
// (/skia/src/opts/SkNx_neon.h)
SkNx(uint16_t a, uint16_t b, uint16_t c, uint16_t d) {
    fVec = (uint16x4_t) { a,b,c,d };
}
```

I need to catch up on C++ a bit and why this works (if it is reached) on the other ARM platforms, such as Android armv7a

**Comment by migueldeicaza** [comment]
This is a compiler/architecture specific data type `uint16x4_t`, it packs the values a, b, c, d into a SIMD register.   Likely, the target platform does not have support for this.

**Comment by newky2k** [comment]
this is not supported
