### ISSUE TITLE
[BUG] Using ToHsv then FromHsv can give you different SKColors

### ISSUE THREAD

**Issue by daltonks** [mono/SkiaSharp#912]
**Description**

`SKColor.ToHsv(...)` and `SKColor.FromHsv(...)` do not invert each other properly.

This seems to be fixed by rounding R, G, B in `SKColor.FromHsv(...)`, but I don't know if that's the proper way to do it:
`return new SKColor ((byte)Math.Round(r), (byte)Math.Round(g), (byte)Math.Round(b), a);`

**Code**

```
var yellow = new SKColor(byte.MaxValue, byte.MaxValue, 0);
yellow.ToHsv(out var h, out var s, out var v);
var notYellow = SKColor.FromHsv(h, s, v);

// notYellow is #FEFF00
```

**Comment by mattleibow** [comment]
This is one of the unfortunate things with this. I would suggest using the new `SKColorF` color type which is using floating-point values to represent color and does not have this data loss.
