### ISSUE TITLE
Strong named assemblies

### ISSUE THREAD

**Issue by callanh** [mono/SkiaSharp#92]
Hi! Just getting started with SkiaSharp for Xamarin Android/iOS. Hoping it will perform much better than the custom view drawing that I am using at the moment.
Because of the way my projects are structured, it would be helpful if the SkiaSharp assemblies delivered via NuGet were strongly named.
I can help/offer advice if you need any.

**Comment by mattleibow** [comment]
@migueldeicaza, @bholmes This is a decision that we should make as soon as possible to avoid issues later on.

If we sign, then we don't have to worry about signing later. Also, other signed libraries can depend on this.

If we are to sign, what key should we use? The mono key, or should we just create a new key?

**Comment by mattleibow** [comment]
Approval from the boss! Going to be signing with the mono key.
