### ISSUE TITLE
[QUESTION] Question about SkiaSharp NuGet package.

### ISSUE THREAD

**Issue by AlexNosk** [mono/SkiaSharp#924]
Why there are both runtimes\osx and lib\Xamarin.Mac20? I mean Xamarin.Mac can be covered by .NET Standard and the appropriate runtime - looks like duplication. Correct me if I am wrong. The same applies to other Xamarin libraries provided in the package. Will not it be more correct to provide .NET Standard library and appropriate native skia libraries in runtimes?
https://github.com/dotnet/standard/blob/master/docs/versions.md
According to the table .NET Standard 1.3 covers Xamarin.iOS 10.0 and higher, Xamarin.Android 7.0 and higher and Xamarin.Mac 3.0 and higher. Is not the purpose of .NET Standard to share code between all these platforms?

**Comment by mattleibow** [comment]
You are correct that .NET Standard works on Mac. However the runtimes folder sadly only applies to netcoreapp.
It results in issues like this: https://github.com/xamarin/xamarin-macios/issues/6065

Right now, the Xamarin.Mac library has special attributes and embedded files that the toolchain know to extract and link. This goes for all the Xamarin platforms. The reason for this is that Xamarin was doing native files long before .NET Core was even a thing. As a result, there was a fair amount of differences - especially around native things. As .NET Core matures and gains the required features, things like this will start to disappear.

I am working with the .NET teams on these issues for all the platforms. I am hoping this will be addressed with .NET 5 later next year.
