### ISSUE TITLE
[BUG] Linux build is exporting symbols from statically linked dependencies

### ISSUE THREAD

**Issue by kekekeks** [mono/SkiaSharp#927]
On Linux library imports don't have a library name attached to them, so when dynamic loader sees multiple exported functions with the same name it just picks the one which was loaded first.

This causes issues when application tries to use a dynamic version of a library that was statically linked into libSkiaSharp.so.

We need to build the library with a [version script](https://www.gnu.org/software/gnulib/manual/html_node/LD-Version-Scripts.html) which will hide everything but Skia C API exports, e. g.

```
{
        global:
                sk_*; 
                gr_*;
        local:
                *;
};
```

linker script can be set via ldflags, e. g.
```
LDFLAGS += -Wl,--version-script=libSkiaSharp.map
```

**Comment by mattleibow** [comment]
Fixed in #984
