### ISSUE TITLE
Unable to allocate pixels for the bitmap. On linux server

### ISSUE THREAD

**Issue by nelson-fm** [mono/SkiaSharp#928]
hi i have the same problem, i dowload the from libSkiaSharp.so https://jenkins.mono-project.com/view/Components/job/Components-SkiaSharp-Linux/79/Azure/processDownloadRequest/ArtifactsFor-79/3c31bd5c5701a6eb3651110b4708bb1d0492c7fc/output/native/linux/x64/libSkiaSharp.so.

My project is a net core 2.1 project, I include the library into my project with property "copy always" and alse in my startup.cs, i put context.LoadUnmanagedLibrary(Path.Combine(Directory.GetCurrentDirectory(), "libSkiaSharp.so")) and i got error:

```
Unable to allocate pixels for the bitmap.
  at SkiaSharp.SKBitmap..ctor(SKImageInfo info, Int32 rowBytes)
  at SkiaSharp.SKBitmap..ctor(SKImageInfo info) 
  at SkiaSharp.SKBitmap.Decode(SKCodec codec, SKImageInfo bitmapInfo) 
  at SkiaSharp.SKBitmap.Decode(SKCodec codec) 
  at SkiaSharp.SKBitmap.Decode(Stream stream)
```

My deploy machine is an amazon with OS CentOS Linux 7 (Core). I installed libgdiplus and also i install mono-complete.

I appreciate your help if i need install someting else. I dont know what else i need to install.

**Comment by mattleibow** [comment]
Most often, this case is just because there is a maximum supported size for bitmaps: https://github.com/mono/SkiaSharp/issues/1249
