### ISSUE TITLE
SKPaint with more font weights such as a Thin, Light, Heavy, etc

### ISSUE THREAD

**Issue by callanh** [mono/SkiaSharp#93]
Hi again!  I am wondering if SkiaSharp can support more font weights? SKTypefaceStyle seems to only support normal, bold, italic and bolditalic.  Have I missed something?

I think this is an important capability for modern apps as we have moved past the days of 'bold' and 'not bold' being enough choice for our user interfaces.

iOS has good native support:

```C#
public enum UIFontWeight
{
  UltraLight = 0,
  Thin = 1,
  Light = 2,
  Regular = 3,
  Medium = 4,
  Semibold = 5,
  Bold = 6,
  Heavy = 7,
  Black = 8,
}
```

Android native support is (a bit weird) via the family name:

```C#
var Thin = Android.Graphics.Typeface.Create("sans-serif-thin", Android.Graphics.TypefaceStyle.Normal);
var Light = Android.Graphics.Typeface.Create("sans-serif-light", Android.Graphics.TypefaceStyle.Normal);
etc
```

Wpf has good native support:

```C#
System.Windows.FontWeights.Thin;
System.Windows.FontWeights.ExtraBold;
etc
```

WinRT (UWP) also has good native support:

```C#
Windows.UI.Text.FontWeights.Thin;
Windows.UI.Text.FontWeights.ExtraBold;
etc
```

**Comment by migueldeicaza** [comment]
The C++ API does not seem to support this.

Could you try using the Android-approach?

    SKTypeface.FromFamilyName ("sans-serif-thin");

And report back?

**Comment by callanh** [comment]
I can confirm that the Android approach works with SkiaSharp.

**Comment by migueldeicaza** [comment]
Ok, documented this.

**Comment by robertmiles3** [comment]
Is there a way to get Open Sans Light working? I've tried all kinds of combinations and none seem to work.

`SKTypeface.FromFamilyName("Open Sans")`
`SKTypeface.FromFamilyName("Open Sans-Light")`
`SKTypeface.FromFamilyName("Open Sans Light")`
`SKTypeface.FromFamilyName("OpenSans-Light")`
`SKTypeface.FromFamilyName("open-sans-light")`
