### ISSUE TITLE
[BUG] Bad black image on scaling image (not bitmap) for certain JPGs

### ISSUE THREAD

**Issue by AndersMad** [mono/SkiaSharp#932]
**Description**

Scaling fails for image (not bitmap) on certain JPG's - see attached image below.

**Code**

Bad - draws a black image instead of scaled (for certain images - using web server code):
```
var img = SKImage.FromPixelCopy(codec.info, codec.Pixels);
canvas.DrawImage(img, SKRect.Create(0, 0, w, h), SKRect.Create(0, 0, 450, 450));
// This is ok - so only fails on scaling
canvas.DrawImage(bmp, 0, 0);
```

Works:
```
var bmp = SKBitmap.Decode(codec);
canvas.DrawBitmap(bmp, SKRect.Create(0, 0, w, h), SKRect.Create(0, 0, 450, 450));
```

Codec is read like:
```
imgStream = new SKManagedStream(inStream);
codec = SKCodec.Create(imgStream, out SKCodecResult result);
```

**Expected Behavior**

A scaled image.

**Actual Behavior**

Black image.

**Basic Information**

- Version with issue: 1.68
- Last known good version: 1.60
- IDE: VS.NET 2019
- Platform Target Frameworks: .NET Standard 4.8 - Windows Web Server

I read that bitmap is on its way out - but I had to revert to bitmap (back from image) as it fails on certain images. I took the attached image and re-saved in Paint and then it works. Comparing the two files shows that non-working has a thumbnail (that might be the culprit!?)

I have had several other issues on v1.68 (from v1.60) (e.g. #719) and wonder if Google has/is neglecting CPU/non-GPU. 

I chance we can soon get a preview build? Thanks

Bad image: ![file-3717](https://user-images.githubusercontent.com/4574570/63246424-eff67200-c262-11e9-8f5a-f028eebf07b0.jpg)

**Comment by mattleibow** [comment]
Appears to be fixed in v2.80!
