### ISSUE TITLE
[BUG] SKBitmap.Decode returns null when decode PNG image.

### ISSUE THREAD

**Issue by AlexNosk** [mono/SkiaSharp#933]
**Description**

PNG image cannot be decoded with SKBitmap.Decode. The problematic image is attached.

**Code**

SkiaSharp.SKBitmap bmp = SkiaSharp.SKBitmap.Decode(@"C:\Temp\image1.png");
Assert.IsNotNull(bmp);

![image1](https://user-images.githubusercontent.com/31235892/63347183-4943cb80-c35f-11e9-8d58-247cad52b13b.png)
![image10](https://user-images.githubusercontent.com/31235892/63347238-5fea2280-c35f-11e9-884f-58fb04f7f62c.png)

**Comment by AlexNosk** [comment]
Are there any news about this issue? Strange thing is that this worked in 1.60.1 version of SkiaSharp.

**Comment by mattleibow** [comment]
Even though this issue is way earlier, this other thread has a bit more info: #1981

Seems to be the same. `SKImage.FromEncodedData` return an invalid image, `SKBitmap.Decode` returns null.

They both use the same decoding logic, so who knows right now.

**Comment by mattleibow** [comment]
Duplicate of #1981
