### ISSUE TITLE
[FEATURE] 

### ISSUE THREAD

**Issue by Harachie** [mono/SkiaSharp#935]
**Is your feature request related to a problem? Please describe.**
I need to get the glyph path for a specific glyph id, not for a string.
The SkFont in skia has the getPath method.
SkiaSharp is missing the SKFont class and bindings though.
https://skia.org/user/api/SkFont_Reference#SkFont_getPath

**Describe the solution you'd like**
Please add a wrapper for SkFont.

**Describe alternatives you've considered**
I used the GetTextPath method from SKPaint. But when I shape with HarfBuzz, the codepoints differ for ligature texts (e.g. tt gets converted to one glyph for two characters).
I have no possibility to get the correct glyph path for this glyph id.
The glyp id I get from HarfBuzz.
Is there any way to use this glyph id elsewhere?

Thanks for all the work to the team! Great work!

**Comment by Gillibald** [comment]
GetTextPath should work with GlyphId just copy the glyph id's from the shaped result into a buffer and pass that buffer to GetTextPath. Make sure the text encoding is set to GlyphId.

**Comment by Harachie** [comment]
Thank you so much!
That's working like a charm!

You are my hero of the day :)
