### ISSUE TITLE
SKMatrix.MakeRotation - wrong parameter name "radians"

### ISSUE THREAD

**Issue by gentledepp** [mono/SkiaSharp#94]
Hi!

`SKMatrix SKMatrix.MakeRotation(float radians)`
should be renamed to
`SKMatrix SKMatrix.MakeRotation(float degrees)`
as this is greatly misleading!

I am using "1.49.4-beta"

**Comment by migueldeicaza** [comment]
The argument is in radians, I am adding a new method "MakeRotationDegrees" that will take degrees.
