### ISSUE TITLE
Missing method "SKPath.AddPath(SKPath childPath)"

### ISSUE THREAD

**Issue by gentledepp** [mono/SkiaSharp#95]
SKPath is missing the method "AddPath(SKPath childPath)"
see:
`void SkPath::addPath(const SkPath& path, SkScalar dx, SkScalar dy, AddPathMode mode) `
in https://github.com/google/skia/blob/master/src/core/SkPath.cpp

I need this method, as I am replacing Android.Canvas with SkiaSharp
and Android.Graphics.Path has such an "AddPath" method
https://developer.android.com/reference/android/graphics/Path.html

I am using 1.49.4-beta

**Comment by migueldeicaza** [comment]
I have added the C API for Skia, =but have not done the binding yet.

**Comment by migueldeicaza** [comment]
Implemneted
