### ISSUE TITLE
When will the next build of SkiaSharp be made available?

### ISSUE THREAD

**Issue by corliss** [mono/SkiaSharp#954]
Related to #840,

**Comment by corliss** [comment]
From [Nuget's history of SkiaSharp builds](https://www.nuget.org/packages/SkiaSharp/), we see that updates to SkiaSharp have been getting less frequent, starting with one or two builds a month in 2016, to not a single build this year. Last year the frequency was about once every two or three months.

Skia is actively in development and there are several fixes that are urgently needed by users of SkiaSharp. Could we please get back to a more predictable cycle of SkiaSharp builds?

Thank you very much.

**Comment by jupdike** [comment]
Waiting for some fixes for an active project. Thanks.

**Comment by corliss** [comment]
This issue was moved to "Needs Triage" 6 days ago.

Unfortunately, it seems there is very little triaging activity going on. There are:
- 115 issues in "Needs Triage"
- 3 issues in "Needs Info"
- 4 issues in "High Priority"
- 17 issues in "Low Priority"
- 9 issues in "Blocked"
- 0 issues in "In Progress"   <---

A total of 255 issues were fixed since the project began in early 2016.

Given this backlog, could we *please* have a response asap? The current state is anxiety-producing.

@migueldeicaza @mattleibow 

Thank you very much.

**Comment by mattleibow** [comment]
We have increased our rate of releases of previews as well as implemented a preview feed: https://aka.ms/skiasharp-eap/index.json

We are also working on all the new bits in a "v2" version of SkiaSharp which is currently available on the preview feed.
