### ISSUE TITLE
Unable to load DLL 'libSkiaSharp' ASP.NET WebApp, net472

### ISSUE THREAD

**Issue by ndenkha** [mono/SkiaSharp#955]
I've tried everything mentioned in https://github.com/mono/SkiaSharp/issues/513, and none of the suggestions helped. I'm creating this new bug in hope to resurrect the above-closed ticket.

I'm using TallComponents Rasterizer4 and have a ticket about this with them. They use SkiaSharp 1.60.3, and all works fine on my development box running Win 10 Pro, 64bit, with Any CPU selected on my ASP.NET Web App, with .NET Framework 4.7.2 and VS 2019.

But, when I deploy to QA environment which is Win 2012 R2, 64bit, selecting anything from Any CPU, or doing the suggestions mentioned in the above ticket #513  none of them works, I keep getting the exception below.
I even tried upgrading to the latest SkiaSharp version 1.68.0, with no luck.

This the exception I'm getting.

System.TypeInitializationException: The type initializer for 'SkiaSharp.SKImageInfo' threw an exception. ---> System.DllNotFoundException: Unable to load DLL 'libSkiaSharp': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
   at SkiaSharp.SkiaApi.sk_colortype_get_default_8888()
   at SkiaSharp.SKImageInfo..cctor()

I really hope someone can point me in the right direction. Thanks.

**Comment by ndenkha** [comment]
After further research into this, I found out different posts indicating that SkiaSharp requires C++ VS 2015 dist, so I installed it from here https://www.microsoft.com/en-us/download/details.aspx?id=53587
and it seems to work now. I would have to do further testing, some end-2-end to make sure all works fine.

But, this is really embarrassing for the team not to include the needed DLLs in the first place and makin this requirement hidden in all kinds of posts. I hope you guys can fix this and make a new release soon.

**Comment by Gillibald** [comment]
It is possible to use static linking for the needed libs but that will increase file size. Maybe this could be optional. In the end it isn't a big deal to install that dependency. This should be documented so everyone knows these requirements.

**Comment by mattleibow** [comment]
I believe that we _do_ have it now in the 1.68.x releases. I believe it was documented in the readme with 1.60, but I think it got removed once we moved on to 1.68

**Comment by mattleibow** [comment]
Closing because it is now statically compiled in since v1.68.x.
