### ISSUE TITLE
[QUESTION] Can OpenGL ES be used as backend

### ISSUE THREAD

**Issue by kipy-be** [mono/SkiaSharp#959]
Hello,

I made a C native library to create a EGL context on a raspberry pi 4 and be able to draw in a VideoCore native window. The context is successfully created and can be used in that native lib.

I then made a C# lib to wrap the native one using p/invoke. The call is made, and the EGL context is created.

Is it possible to use it as a backend for SkiaSharp ?

I tried the following code : 

```CSharp 
IntPtr glContext = _bridge.CreateGLContext(); // My native call
var info = new SKImageInfo(1920, 1080);
var context = GRContext.Create(GRBackend.OpenGL); // null
var surface = SKSurface.Create(context, false, info); // Exception
```

And
```CSharp 
IntPtr glContext = _bridge.CreateGLContext();
var info = new SKImageInfo(1920, 1080);
var glInterface = GRGlInterface.CreateNativeGlInterface(); // maybe this ?
var context = GRContext.Create(GRBackend.OpenGL, glInterface); // nope, still null
var surface = SKSurface.Create(context, false, info);
```

It's of course, on the same thread.

I don't know what to do or is this even possible

Thanks for your help

**Comment by Gillibald** [comment]
I think you have to make sure the context is attached to the right thread you want to use it on by calling https://www.khronos.org/registry/EGL/sdk/docs/man/html/eglMakeCurrent.xhtml before you can create a GRContext. Just a guess.

**Comment by kipy-be** [comment]
Thanks for your reply, but I'm already doing this :)

without all the check/asserts and the videocore stuff, here's basically what i'm doing with egl : 

```C
display = eglGetDisplay(EGL_DEFAULT_DISPLAY);
eglInitialize(...);
eglBindAPI(EGL_OPENGL_ES_API);
eglChooseConfig(...);
surface = eglCreateWindowSurface(...);
context = eglCreateContext(...);
eglMakeCurrent(display, surface, surface, context);
```

**Comment by Gillibald** [comment]
Please try to pass the GRGlInterface explicitly. You can create one with https://docs.microsoft.com/en-us/dotnet/api/skiasharp.grglinterface.assembleglesinterface?view=skiasharp-1.68.0 and call https://docs.microsoft.com/en-us/dotnet/api/skiasharp.grcontext.create?view=skiasharp-1.68.0#SkiaSharp_GRContext_Create_SkiaSharp_GRBackend_SkiaSharp_GRGlInterface_ afterwards.

**Comment by kipy-be** [comment]
I tried that, but I honestly don't know what to do with that.
In the C lib, I return the pointer from eglCreateContext() to the C# layer (IntPtr object)

I tried this : 

```CSharp
var glInterface = GRGlInterface.AssembleGlesInterface((ctx, name) => {
    return _bridge.CreateGLContext();
});
var context = GRContext.Create(GRBackend.OpenGL, glInterface);
```
but the AssembleGlesInterface call lead me to a Segmentation fault

But maybe it's not what I suppose to do.

I tried with both broadcom and mesa OpenGL driver

**Comment by mattleibow** [comment]
Have a look at the unit tests for some ideas:
https://github.com/mono/SkiaSharp/blob/master/tests/Tests/GlContexts/Glx/GlxContext.cs

SkiaSharp has GTK views that you can also try out if you are using that.

For the construction of the actual OpenGL ES contexts, it might be better to chat those those folks. But, in terms of support? Yes. It is currently being used on the mobile platforms.
