### ISSUE TITLE
Missing property "SKPaint.PathEffect" and "DashPathEffect"

### ISSUE THREAD

**Issue by gentledepp** [mono/SkiaSharp#96]
Hi,

I need to draw dashed lines.
As it seems, in Skia there is a property "PathEffect" on the SKPaint object.
see: https://bugs.chromium.org/p/skia/issues/detail?id=874

or directly the source for dashpatheffect:
https://github.com/google/skia/blob/master/gm/dashing.cpp

Rendering dashed lines is very important to us :-|

**Comment by hypeartist** [comment]
It was already issued quite time ago:
[#47](https://github.com/mono/SkiaSharp/issues/47)
with no visible progress though...

**Comment by gentledepp** [comment]
Sorry O:-)

**Comment by migueldeicaza** [comment]
Closing as this is a duplicate
