### ISSUE TITLE
ARM64_32 architecture for WatchOS missing in NuGet package

### ISSUE THREAD

**Issue by OABsoftware** [mono/SkiaSharp#961]
**Description**

I started to use SkiaSharp in a Xamarin WatchOS project for drawing charts in a Watch app.
Since the Apple Watch Series 4 was introduced, it became mandatary to compile Watch apps against the ARM64_32 architecture.
But when I try to compile my app, that now includes the SkiaSharp package, against that architecture the linker gives an error.

To prevent this, the NuGet package for SkiaSharp would need to be extended with a version of the SkiaSharp library compiled against the ARM64_32 architecture for WatchOS.

**Expected Behavior**

It would be great if I could use SkiaSharp in a WatchOS app that is compiled against the ARM64_32 architecture.

**Actual Behavior**

When compiling the Watch app, the linker currently gives the following error:
`ARM64_32 architecture for WatchOS missing in NuGet package`

**Basic Information**

- Version with issue:  1.68.0
- IDE:  Visual Studio for Mac 8.3 with Xcode 11
- Platform Target Frameworks:
  - iOS: 13
  - watchOS: 6.0
- Target Devices:
  - iPhone X running iOS 13
  - Apple Watch Series 4 running WatchOS 6

**Steps to reproduce**

- Start Visual Studio 8.3 for Mac
- Create a new iOS project
- Add a new WatchOS project to the solution
- Open the project properties of the WatchOSExtension project
- Select configuration Debug and platform iPhone
- Change the supported architecture to ARM64_32
  (if you don't, the app can't be deployed to a Series 4 or higher Apple Watch)
- Click OK
- Add the SkiaSharp NuGet package to the WatchOSExtension project
- E.g. in the InterfaceController.CS file add the following lines of code to the Awake method:

`            SKBitmap oBitmap = new SKBitmap(400, 300, false);`
`            SKCanvas oCanvas = new SKCanvas(oBitmap);`
`            oCanvas.Clear(SKColors.Blue);`
`            SKPaint oPaint = new SKPaint();`
`            oPaint.Color = SKColors.Yellow;`
`            oPaint.StrokeWidth = 5;`
`            oCanvas.DrawCircle(200, 150, 100, oPaint);`

- Try to compile the solution
- You will see the linker error in the error list pane

**Comment by mattleibow** [comment]
Thanks for reporting this, I'm having a look now and I'll see if I can get an update out ASAP.

**Comment by mattleibow** [comment]
https://github.com/mono/SkiaSharp/pull/967 was just merged with arm64_32 support. I'll push to the preview feed ass soon as I can and update this issue.

**Comment by OABsoftware** [comment]
That's great. Thanks!

**Comment by mattleibow** [comment]
Merged in https://github.com/mono/SkiaSharp/pull/967

**Comment by mattleibow** [comment]
@OABsoftware I just pushed the latest master build to the internal feed:
https://nugetized.blob.core.windows.net/skiasharp-eap/index.json

You should find a 1.68.1-rc.151 build for all the SkiaSharp packages.

**Comment by OABsoftware** [comment]
Great! I will try again with that version.
