### ISSUE TITLE
Bind SkPictureShader 

### ISSUE THREAD

**Issue by alexandrvslv** [mono/SkiaSharp#969]
Hi. I implement [Pdf rendering with SkiaSharp](https://github.com/alexandrvslv/pdf-clown) and to paint "Tiling Pattern" requires [SkPictureShader](https://github.com/google/skia/blob/master/src/shaders/SkPictureShader.h) 

It will be great to see bindings for this type of shader.

Let me know what the best solution is: make pull request by myself or fork project.

**Comment by Gillibald** [comment]
Now at the right place :)

I had a quick look at this and it seems the C wrapper already has the needed functions to create a picture shader just the binding is missing the needed bits.

The C API is defined here:
https://github.com/mono/skia/blob/xamarin-mobile-bindings/src/c/sk_shader.cpp#L37

P/Invoke:
https://github.com/mono/SkiaSharp/blob/master/binding/Binding/SkiaApi.cs#L591

And the C# Binding is defined here: https://github.com/mono/SkiaSharp/blob/master/binding/Binding/SKShader.cs

If you can fork SkiaSharp and create a PR against current master.

**Comment by alexandrvslv** [comment]
Great! I will try my best for a few days.
