### ISSUE TITLE
SKMatrix methods "Inverse" and "Concat"

### ISSUE THREAD

**Issue by gentledepp** [mono/SkiaSharp#97]
Hi!

I am currently replacing my Android Canvas API stuff with SkiaSharp as I am hoping for better performance.
One problem I am facing is that the implementation of SKMatrix is rather dumb.
It would be sufficient, if it was at least possible 
1) to concatenate two matrices like
SKMatrix SKMatrix.Concat(SKMatrix m1, SKMatrix m2);

2) and to get the inverse of a specified matrix
SKMatrix SKMatrix.MakeInverse(SKMatrix other);

these two basic methods would solve almost all of my matrix calculations!
Thank you for considering this :)

**Comment by migueldeicaza** [comment]
Added Concat, PreConcat, PostConcat and TryInvert.
