### ISSUE TITLE
[QUESTION] Pdf Type1 Fonts loading

### ISSUE THREAD

**Issue by alexandrvslv** [mono/SkiaSharp#970]
Hi. I implement [Pdf rendering with SkiaSharp](https://github.com/alexandrvslv/pdf-clown) and have trouble on loading Pdf Type1 Fonts(PostScript Program) on windows by SKTypeface. 

Have you any decision? 

Test's show's that HarfBuzz can load this type of fonts. But is it possible to Draw text with HarfBuzzFace and escape SkTypeface?

**Comment by Gillibald** [comment]
I had a quick look at this and it seems the c wrapper already has the needed functions to create a picture shade just the binding is missing the needed bits.

The C API is defined here: 
https://github.com/mono/skia/blob/xamarin-mobile-bindings/src/c/sk_shader.cpp#L37

P/Invoke: 
https://github.com/mono/SkiaSharp/blob/master/binding/Binding/SkiaApi.cs#L591

And the C# Binding is defined here: https://github.com/mono/SkiaSharp/blob/master/binding/Binding/SKShader.cs

If you can fork SkiaSharp and create a PR against current master after you added needed functions.

**Comment by alexandrvslv** [comment]
Greate,  but it was previus issue)

> 
> 
> I had a quick look at this and it seems the C wrapper already has the needed functions to create a picture shader just the binding is missing the needed bits.
> 
> The C API is defined here:
> https://github.com/mono/skia/blob/xamarin-mobile-bindings/src/c/sk_shader.cpp#L37
> 
> P/Invoke:
> https://github.com/mono/SkiaSharp/blob/master/binding/Binding/SkiaApi.cs#L591
> 
> And the C# Binding is defined here: https://github.com/mono/SkiaSharp/blob/master/binding/Binding/SKShader.cs
> 
> If you can fork SkiaSharp and create a PR against current master.

**Comment by Gillibald** [comment]
DirectWrite doesn't support Type 1 typefaces so I don't think this will ever work. It is probably time to use a newer format. Looks like FreeType isn't supporting this aswell.

**Comment by alexandrvslv** [comment]
Ok. look's like that fonts requires to implement custom text extraction for mystic encodings from 90's)
