### ISSUE TITLE
missing method "SKCanvas.Scale(float scaleX, float scaleY, float focusX, float focusY)"

### ISSUE THREAD

**Issue by gentledepp** [mono/SkiaSharp#98]
SKCanvas is missing a scale function overload that allows to specify the x- and y- center of the scale operation.

Interestingly, I could not find this in the Skia source code at
https://github.com/google/skia/blob/master/include/core/SkCanvas.h

but as I am replacing Android.Canvas api calls, where the Android.Graphics.Canvas class has this overload (and it is internally using Skia itself, I guess) there should be a way to implement this... :-|

Can I achieve this in any other way? (I am not so good at matrix operations, sorry for that)

I am using 1.49.4-beta

**Comment by migueldeicaza** [comment]
you can replicate the behavior like this:

https://github.com/android/platform_frameworks_base/blob/master/graphics/java/android/graphics/Canvas.java#L589

**Comment by gentledepp** [comment]
Thanks! That was my workaroud till now :)

**Comment by mattleibow** [comment]
![scale-normal](https://cloud.githubusercontent.com/assets/1096616/17616004/407ede98-6072-11e6-83b7-d838191792c3.PNG)
![scale-0 0](https://cloud.githubusercontent.com/assets/1096616/17616002/407da8ca-6072-11e6-9185-f86907f8b13c.PNG)
![scale- 5 5](https://cloud.githubusercontent.com/assets/1096616/17616001/407d9ba0-6072-11e6-9bfd-a46e062387c2.PNG)
![scale-1 1](https://cloud.githubusercontent.com/assets/1096616/17616003/407dca3a-6072-11e6-9bdb-f14fadcd1974.PNG)
