### ISSUE TITLE
missing method "SKCanvas.DrawCircle(...)"

### ISSUE THREAD

**Issue by gentledepp** [mono/SkiaSharp#99]
Hi!
the following method is missing on SKCanvas:

`  void drawCircle(SkScalar cx, SkScalar cy, SkScalar radius,
                    const SkPaint& paint);`

found at : https://github.com/google/skia/blob/master/include/core/SkCanvas.h

I am using 1.49.4-beta

**Comment by migueldeicaza** [comment]
Added
