### ISSUE TITLE
[QUESTION] How the doc of SkiaSharp is written?

### ISSUE THREAD

**Issue by ngocdaothanh** [mono/SkiaSharp#990]
I'm curious how the doc of SkiaSharp is written and converted to create the web site https://docs.microsoft.com/en-us/dotnet/api/skiasharp.

I can see a lot of XML at this repo:
https://github.com/mono/SkiaSharp-API-docs

Is the XML hand-written?
Why not put the doc in the source code, then extract it later?

**Comment by mattleibow** [comment]
Good question. It is generated from the compiled assemblies and stored in a separate repo for edits and possibly other languages.

I'll put together wiki now.

**Comment by mattleibow** [comment]
I have a WIP for the docs process: https://github.com/mono/SkiaSharp/wiki/Writing-Docs

Still need to merge https://github.com/mono/SkiaSharp/pull/997

It is not perfect yet - I would really like to move all the docs bits into the docs repo, but just not there yet.
