### ISSUE TITLE
[BUG] sk_ipoint_t and sk_isize_t should use integer members

### ISSUE THREAD

**Issue by ngocdaothanh** [mono/SkiaSharp#991]
See: https://github.com/mono/skia/blob/xamarin-mobile-bindings/include/c/sk_types.h

Current code:

```c
typedef struct {
    float   x;
    float   y;
} sk_ipoint_t;

typedef struct {
    float   w;
    float   h;
} sk_isize_t;

typedef struct {
    int32_t left;
    int32_t top;
    int32_t right;
    int32_t bottom;
} sk_irect_t;
```

Coincidentally, the size of `float` is 32.
But for correctness, `sk_ipoint_t` and `sk_isize_t` should use `int32_t`.

**Comment by mattleibow** [comment]
Thanks for the issue and PR. Merged!
