### ISSUE TITLE
Hebrew text is drawn reversed

### ISSUE THREAD

**Issue by Chasyl** [mono/SkiaSharp#999]
Hi,

I want to use skiasharp to write hebrew text on an image, but hebrew text is drawn reversed.
Can you take care of it?

Thanks!

**Comment by Gillibald** [comment]
Pls use the DrawShapedText method

**Comment by Chasyl** [comment]
I'm using version 1.60.0 and I don't see this function.

**Comment by Gillibald** [comment]
You need to use the SkiaSharp.HarfBuzz package https://www.nuget.org/packages/SkiaSharp.HarfBuzz/

**Comment by Chasyl** [comment]
Thanks!!

**Comment by Chasyl** [comment]
Hi can I write mixed text (English and hebrew together)?
I tried doing it and the english text becomes rectangles.

**Comment by Gillibald** [comment]
You have to split your text into runs with a unique direction. So you have to draw Hebrew and English text separately. Also consider using the font mager for character matching to find a suitable Typeface.

**Comment by mattleibow** [comment]
@Gillibald at some point we are going to have to get icu or some similar library bound.

**Comment by Gillibald** [comment]
I think we can bundle SkiaSharp.HarfBuzz with a text segmenter that is producing a text blob of unique runs. For more advanced scenarios we need a markup for styled text.

**Comment by Gillibald** [comment]
https://github.com/Gillibald/Avalonia/blob/feature/SkiaTextLayout/src/Skia/Avalonia.Skia/TextRunIterator.cs
https://github.com/Gillibald/Avalonia/blob/feature/SkiaTextLayout/src/Avalonia.Visuals/Media/Text/Unicode/LineBreaker.cs
Combined in one component
